#! /usr/bin/env bash
echo 190126_add_feed_info >> scripts.log

add_part_info.py -p FDV1 -r A -c "MIT version 1" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV1 -r A -c "1mm lower flange, no upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV1 -r A -c "No PVC stiffeners" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV1 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV1 -r A -c "No coating flange tip at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV1 -r A -c "No coating at blade top connection" --date 2019/01/26 --time 10:05
add_part_info.py -p FDV1 -r A -c "Blade lower cutouts hand cut" --date 2019/01/26 --time 10:06

add_part_info.py -p FDV2 -r A -c "MIT version 1" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV2 -r A -c "1mm lower flange, no upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV2 -r A -c "No PVC stiffeners" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV2 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV2 -r A -c "No coating flange tip at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV2 -r A -c "No coating at blade top connection" --date 2019/01/26 --time 10:05
add_part_info.py -p FDV2 -r A -c "Blade lower cutouts hand cut" --date 2019/01/26 --time 10:06

add_part_info.py -p FDV3 -r A -c "MIT version 1" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV3 -r A -c "1mm lower flange, no upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV3 -r A -c "No PVC stiffeners" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV3 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV3 -r A -c "No coating flange tip at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV3 -r A -c "No coating at blade top connection" --date 2019/01/26 --time 10:05
add_part_info.py -p FDV3 -r A -c "Blade lower cutouts hand cut" --date 2019/01/26 --time 10:06

add_part_info.py -p FDV4 -r A -c "UK version 1" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV4 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV4 -r A -c "No PVC stiffeners" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV4 -r A -c "PVC frame plate and braces 15mm thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV4 -r A -c "Surtec 650 flange tip at brass field pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV4 -r A -c "No coating at blade top connection" --date 2019/01/26 --time 10:05

add_part_info.py -p FDV5 -r A -c "UK version 1" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV5 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV5 -r A -c "No PVC stiffeners" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV5 -r A -c "PVC frame plate and braces 15mm thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV5 -r A -c "Surtec 650 flange tip at brass field pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV5 -r A -c "No coating at blade top connection" --date 2019/01/26 --time 10:05

add_part_info.py -p FDV6 -r A -c "UK version 1" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV6 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV6 -r A -c "No PVC stiffeners" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV6 -r A -c "PVC frame plate and braces 15mm thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV6 -r A -c "Surtec 650 flange tip at brass field pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV6 -r A -c "No coating at blade top connection" --date 2019/01/26 --time 10:05

add_part_info.py -p FDV7 -r A -c "UK version 1" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV7 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV7 -r A -c "No PVC stiffeners" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV7 -r A -c "PVC frame plate and braces 15mm thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV7 -r A -c "Surtec 650 flange tip at brass field pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV7 -r A -c "No coating at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV8 -r A -t feed -m 008 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV8 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV8 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV8 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV8 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV8 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV8 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV9 -r A -t feed -m 009 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV9 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV9 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV9 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV9 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV9 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV9 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV10 -r A -t feed -m 010 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV10 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV10 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV10 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV10 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV10 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV10 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV11 -r A -t feed -m 011 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV11 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV11 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV11 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV11 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV11 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV11 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV12 -r A -t feed -m 012 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV12 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV12 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV12 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV12 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV12 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV12 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV13 -r A -t feed -m 013 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV13 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV13 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV13 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV13 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV13 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV13 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV14 -r A -t feed -m 014 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV14 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV14 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV14 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV14 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV14 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV14 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV15 -r A -t feed -m 015 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV15 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV15 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV15 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV15 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV15 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV15 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV16 -r A -t feed -m 016 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV16 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV16 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV16 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV16 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV16 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV16 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV17 -r A -t feed -m 017 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV17 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV17 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV17 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV17 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV17 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV17 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV18 -r A -t feed -m 018 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV18 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV18 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV18 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV18 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV18 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV18 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV19 -r A -t feed -m 019 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV19 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV19 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV19 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV19 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV19 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV19 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV20 -r A -t feed -m 020 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV20 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV20 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV20 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV20 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV20 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV20 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV21 -r A -t feed -m 021 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV21 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV21 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV21 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV21 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV21 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV21 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV22 -r A -t feed -m 022 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV22 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV22 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV22 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV22 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV22 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV22 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV23 -r A -t feed -m 023 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV23 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV23 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV23 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV23 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV23 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV23 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV24 -r A -t feed -m 024 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV24 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV24 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV24 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV24 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV24 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV24 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05

add_part.py -p FDV25 -r A -t feed -m 025 --date 2019/01/26 --time 10:00 --actually_do_it
add_part_info.py -p FDV25 -r A -c "MIT/SA version" --date 2019/01/26 --time 10:00
add_part_info.py -p FDV25 -r A -c "2mm lower and upper flange" --date 2019/01/26 --time 10:01
add_part_info.py -p FDV25 -r A -c "PVC stiffeners upper and lower" --date 2019/01/26 --time 10:02
add_part_info.py -p FDV25 -r A -c "PVC frame plate and braces 5/8in thick" --date 2019/01/26 --time 10:03
add_part_info.py -p FDV25 -r A -c "Penetrox A at brass feed pin location" --date 2019/01/26 --time 10:04
add_part_info.py -p FDV25 -r A -c "Penetrix A at blade top connection" --date 2019/01/26 --time 10:05
