#! /usr/bin/env bash
echo "../cm_updates/191031_overview_update_1606" >> scripts.log 
update_apriori.py -p HH83 -s not_connected --date 2019/10/04 --time 12:00:00
update_apriori.py -p HH40 -s not_connected --date 2019/10/03 --time 12:00:00
update_apriori.py -p HH41 -s not_connected --date 2019/10/03 --time 12:00:00
update_apriori.py -p HH42 -s not_connected --date 2019/10/03 --time 12:00:00
update_apriori.py -p HH54 -s not_connected --date 2019/10/03 --time 12:00:00
update_apriori.py -p HH55 -s not_connected --date 2019/10/03 --time 12:00:00
update_apriori.py -p HH56 -s not_connected --date 2019/10/03 --time 12:00:00
update_apriori.py -p HH57 -s not_connected --date 2019/10/03 --time 12:00:00
update_apriori.py -p HH69 -s not_connected --date 2019/10/03 --time 12:00:00
update_apriori.py -p HH70 -s not_connected --date 2019/10/03 --time 12:00:00
update_apriori.py -p HH71 -s not_connected --date 2019/10/03 --time 12:00:00
update_apriori.py -p HH72 -s not_connected --date 2019/10/03 --time 12:00:00
update_apriori.py -p HH116 -s not_connected --date 2019/10/04 --time 12:00:00
