#! /usr/bin/env bash
echo "191004_add_antennas" >> scripts.log 
add_part.py -p FDV26 -r A -t feed -m FDV26 --date 2019/10/02 --time 10:00
add_connection.py -u A81 --uprev H --upport focus -d FDV26 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FDV26 --uprev A --upport terminals -d FEM017 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FEM017 --uprev A --upport e -d NBP07 --dnrev A --dnport e1 --date 2019/10/02 --time 11:00
add_connection.py -u FEM017 --uprev A --upport n -d NBP07 --dnrev A --dnport n1 --date 2019/10/02 --time 11:00
add_part.py -p FDV27 -r A -t feed -m FDV27 --date 2019/10/02 --time 10:00
add_part.py -p FEM051 -r A -t front-end -m FEM051 --date 2019/10/02 --time 10:00
add_connection.py -u A82 --uprev H --upport focus -d FDV27 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FDV27 --uprev A --upport terminals -d FEM051 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FEM051 --uprev A --upport e -d NBP07 --dnrev A --dnport e2 --date 2019/10/02 --time 11:00
add_connection.py -u FEM051 --uprev A --upport n -d NBP07 --dnrev A --dnport n2 --date 2019/10/02 --time 11:00
add_part.py -p FDV28 -r A -t feed -m FDV28 --date 2019/10/02 --time 10:00
add_part.py -p FEM050 -r A -t front-end -m FEM050 --date 2019/10/02 --time 10:00
add_connection.py -u A98 --uprev H --upport focus -d FDV28 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FDV28 --uprev A --upport terminals -d FEM050 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FEM050 --uprev A --upport e -d NBP07 --dnrev A --dnport e7 --date 2019/10/02 --time 11:00
add_connection.py -u FEM050 --uprev A --upport n -d NBP07 --dnrev A --dnport n7 --date 2019/10/02 --time 11:00
add_part.py -p FDV29 -r A -t feed -m FDV29 --date 2019/10/02 --time 10:00
add_part.py -p FEM052 -r A -t front-end -m FEM052 --date 2019/10/02 --time 10:00
add_connection.py -u A99 --uprev H --upport focus -d FDV29 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FDV29 --uprev A --upport terminals -d FEM052 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FEM052 --uprev A --upport e -d NBP07 --dnrev A --dnport e8 --date 2019/10/02 --time 11:00
add_connection.py -u FEM052 --uprev A --upport n -d NBP07 --dnrev A --dnport n8 --date 2019/10/02 --time 11:00
add_part.py -p FDV30 -r A -t feed -m FDV30 --date 2019/10/02 --time 10:00
add_part.py -p FEM048 -r A -t front-end -m FEM048 --date 2019/10/02 --time 10:00
add_connection.py -u A100 --uprev H --upport focus -d FDV30 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FDV30 --uprev A --upport terminals -d FEM048 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FEM048 --uprev A --upport e -d NBP07 --dnrev A --dnport e4 --date 2019/10/02 --time 11:00
add_connection.py -u FEM048 --uprev A --upport n -d NBP07 --dnrev A --dnport n4 --date 2019/10/02 --time 11:00
add_part.py -p FDV31 -r A -t feed -m FDV31 --date 2019/10/02 --time 10:00
add_part.py -p FEM014 -r A -t front-end -m FEM014 --date 2019/10/02 --time 10:00
add_connection.py -u A116 --uprev H --upport focus -d FDV31 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FDV31 --uprev A --upport terminals -d FEM014 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FEM014 --uprev A --upport e -d NBP07 --dnrev A --dnport e9 --date 2019/10/02 --time 11:00
add_connection.py -u FEM014 --uprev A --upport n -d NBP07 --dnrev A --dnport n9 --date 2019/10/02 --time 11:00
add_part.py -p FDV32 -r A -t feed -m FDV32 --date 2019/10/02 --time 10:00
add_part.py -p FEM015 -r A -t front-end -m FEM015 --date 2019/10/02 --time 10:00
add_connection.py -u A117 --uprev H --upport focus -d FDV32 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FDV32 --uprev A --upport terminals -d FEM015 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FEM015 --uprev A --upport e -d NBP07 --dnrev A --dnport e10 --date 2019/10/02 --time 11:00
add_connection.py -u FEM015 --uprev A --upport n -d NBP07 --dnrev A --dnport n10 --date 2019/10/02 --time 11:00
add_part.py -p FDV33 -r A -t feed -m FDV33 --date 2019/10/02 --time 10:00
add_part.py -p FEM053 -r A -t front-end -m FEM053 --date 2019/10/02 --time 10:00
add_connection.py -u A118 --uprev H --upport focus -d FDV33 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FDV33 --uprev A --upport terminals -d FEM053 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FEM053 --uprev A --upport e -d NBP07 --dnrev A --dnport e11 --date 2019/10/02 --time 11:00
add_connection.py -u FEM053 --uprev A --upport n -d NBP07 --dnrev A --dnport n11 --date 2019/10/02 --time 11:00
add_part.py -p FDV34 -r A -t feed -m FDV34 --date 2019/10/02 --time 10:00
add_part.py -p FEM013 -r A -t front-end -m FEM013 --date 2019/10/02 --time 10:00
add_connection.py -u A119 --uprev H --upport focus -d FDV34 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FDV34 --uprev A --upport terminals -d FEM013 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FEM013 --uprev A --upport e -d NBP07 --dnrev A --dnport e5 --date 2019/10/02 --time 11:00
add_connection.py -u FEM013 --uprev A --upport n -d NBP07 --dnrev A --dnport n5 --date 2019/10/02 --time 11:00
add_part.py -p FDV49 -r A -t feed -m FDV49 --date 2019/10/02 --time 10:00
add_part.py -p FEM049 -r A -t front-end -m FEM049 --date 2019/10/02 --time 10:00
add_connection.py -u A137 --uprev H --upport focus -d FDV49 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FDV49 --uprev A --upport terminals -d FEM049 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FEM049 --uprev A --upport e -d NBP07 --dnrev A --dnport e12 --date 2019/10/02 --time 11:00
add_connection.py -u FEM049 --uprev A --upport n -d NBP07 --dnrev A --dnport n12 --date 2019/10/02 --time 11:00
add_part.py -p FDV47 -r A -t feed -m FDV47 --date 2019/10/02 --time 10:00
add_part.py -p FEM047 -r A -t front-end -m FEM047 --date 2019/10/02 --time 10:00
add_connection.py -u A138 --uprev H --upport focus -d FDV47 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FDV47 --uprev A --upport terminals -d FEM047 --dnrev A --dnport input --date 2019/10/02 --time 11:00
add_connection.py -u FEM047 --uprev A --upport e -d NBP07 --dnrev A --dnport e6 --date 2019/10/02 --time 11:00
add_connection.py -u FEM047 --uprev A --upport n -d NBP07 --dnrev A --dnport n6 --date 2019/10/02 --time 11:00
