#! /usr/bin/env bash
echo "191106_add_nodes_4_5" >> scripts.log 
add_station.py ND04 --sernum 4 --date 2019/10/31 --time 10:00
add_part.py -p FPS06 -r A -t fem-power-supply -m FPS06 --date 2019/10/31 --time 10:00
add_part.py -p PCH05 -r A -t pam-chassis -m PCH05 --date 2019/10/31 --time 10:00
add_part.py -p NCMPro3 -r A -t node-control-module -m NCMPro3 --date 2019/10/31 --time 10:00
add_part.py -p N04 -r A -t node -m 4 --date 2019/10/31 --time 10:00
add_part.py -p NBP04 -r A -t node-bulkhead -m 4 --date 2019/10/31 --time 10:00
add_part.py -p PAM101 -r A -t post-amp -m 101 --date 2019/10/31 --time 10:00
add_part.py -p PAM102 -r A -t post-amp -m 102 --date 2019/10/31 --time 10:00
add_part.py -p PAM103 -r A -t post-amp -m 103 --date 2019/10/31 --time 10:00
add_part.py -p PAM104 -r A -t post-amp -m 104 --date 2019/10/31 --time 10:00
add_part.py -p PAM105 -r A -t post-amp -m 105 --date 2019/10/31 --time 10:00
add_part.py -p PAM106 -r A -t post-amp -m 106 --date 2019/10/31 --time 10:00
add_part.py -p PAM107 -r A -t post-amp -m 107 --date 2019/10/31 --time 10:00
add_part.py -p PAM108 -r A -t post-amp -m 108 --date 2019/10/31 --time 10:00
add_part.py -p PAM109 -r A -t post-amp -m 109 --date 2019/10/31 --time 10:00
add_part.py -p PAM110 -r A -t post-amp -m 110 --date 2019/10/31 --time 10:00
add_part.py -p PAM111 -r A -t post-amp -m 111 --date 2019/10/31 --time 10:00
add_part.py -p PAM112 -r A -t post-amp -m 112 --date 2019/10/31 --time 10:00
add_part.py -p SNPC000022 -r A -t snap -m C000022 --date 2019/10/31 --time 10:00
add_part.py -p SNPC000003 -r A -t snap -m C000003 --date 2019/10/31 --time 10:00
add_part.py -p SNPC000048 -r A -t snap -m C000048 --date 2019/10/31 --time 10:00
add_part.py -p SNPC000040 -r A -t snap -m C000040 --date 2019/10/31 --time 10:00
add_connection.py -u N04 --uprev A --upport @ground -d ND04 --dnrev A --dnport @ground --date 2019/10/31 --time 11:00
add_connection.py -u FPS06 --uprev A --upport @rack -d N04 --dnrev A --dnport @top --date 2019/10/31 --time 11:00
add_connection.py -u PCH05 --uprev A --upport @rack -d N04 --dnrev A --dnport @bottom --date 2019/10/31 --time 11:00
add_connection.py -u NCMPro3 --uprev A --upport @rack -d N04 --dnrev A --dnport @middle --date 2019/10/31 --time 11:00
add_connection.py -u PAM101 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot1 --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport e1 -d PAM101 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport n1 -d PAM101 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM102 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot2 --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport e2 -d PAM102 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport n2 -d PAM102 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM103 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot3 --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport e3 -d PAM103 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport n3 -d PAM103 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM104 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot4 --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport e4 -d PAM104 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport n4 -d PAM104 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM105 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot5 --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport e5 -d PAM105 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport n5 -d PAM105 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM106 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot6 --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport e6 -d PAM106 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport n6 -d PAM106 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM107 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot7 --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport e7 -d PAM107 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport n7 -d PAM107 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM108 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot8 --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport e8 -d PAM108 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport n8 -d PAM108 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM109 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot9 --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport e9 -d PAM109 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport n9 -d PAM109 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM110 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot10 --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport e10 -d PAM110 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport n10 -d PAM110 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM111 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot11 --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport e11 -d PAM111 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport n11 -d PAM111 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM112 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot12 --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport e12 -d PAM112 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP04 --uprev A --upport n12 -d PAM112 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u SNPC000022 --uprev A --upport rack -d N04 --dnrev A --dnport loc0 --date 2019/10/31 --time 11:00
add_connection.py -u PAM101 --uprev A --upport e -d SNPC000022 --dnrev A --dnport e2 --date 2019/10/31 --time 11:00
add_connection.py -u PAM102 --uprev A --upport e -d SNPC000022 --dnrev A --dnport e6 --date 2019/10/31 --time 11:00
add_connection.py -u PAM103 --uprev A --upport e -d SNPC000022 --dnrev A --dnport e10 --date 2019/10/31 --time 11:00
add_connection.py -u PAM101 --uprev A --upport n -d SNPC000022 --dnrev A --dnport n0 --date 2019/10/31 --time 11:00
add_connection.py -u PAM102 --uprev A --upport n -d SNPC000022 --dnrev A --dnport n4 --date 2019/10/31 --time 11:00
add_connection.py -u PAM103 --uprev A --upport n -d SNPC000022 --dnrev A --dnport n8 --date 2019/10/31 --time 11:00
add_connection.py -u SNPC000003 --uprev A --upport rack -d N04 --dnrev A --dnport loc1 --date 2019/10/31 --time 11:00
add_connection.py -u PAM104 --uprev A --upport e -d SNPC000003 --dnrev A --dnport e2 --date 2019/10/31 --time 11:00
add_connection.py -u PAM105 --uprev A --upport e -d SNPC000003 --dnrev A --dnport e6 --date 2019/10/31 --time 11:00
add_connection.py -u PAM106 --uprev A --upport e -d SNPC000003 --dnrev A --dnport e10 --date 2019/10/31 --time 11:00
add_connection.py -u PAM104 --uprev A --upport n -d SNPC000003 --dnrev A --dnport n0 --date 2019/10/31 --time 11:00
add_connection.py -u PAM105 --uprev A --upport n -d SNPC000003 --dnrev A --dnport n4 --date 2019/10/31 --time 11:00
add_connection.py -u PAM106 --uprev A --upport n -d SNPC000003 --dnrev A --dnport n8 --date 2019/10/31 --time 11:00
add_connection.py -u SNPC000048 --uprev A --upport rack -d N04 --dnrev A --dnport loc2 --date 2019/10/31 --time 11:00
add_connection.py -u PAM107 --uprev A --upport e -d SNPC000048 --dnrev A --dnport e2 --date 2019/10/31 --time 11:00
add_connection.py -u PAM108 --uprev A --upport e -d SNPC000048 --dnrev A --dnport e6 --date 2019/10/31 --time 11:00
add_connection.py -u PAM109 --uprev A --upport e -d SNPC000048 --dnrev A --dnport e10 --date 2019/10/31 --time 11:00
add_connection.py -u PAM107 --uprev A --upport n -d SNPC000048 --dnrev A --dnport n0 --date 2019/10/31 --time 11:00
add_connection.py -u PAM108 --uprev A --upport n -d SNPC000048 --dnrev A --dnport n4 --date 2019/10/31 --time 11:00
add_connection.py -u PAM109 --uprev A --upport n -d SNPC000048 --dnrev A --dnport n8 --date 2019/10/31 --time 11:00
add_connection.py -u SNPC000040 --uprev A --upport rack -d N04 --dnrev A --dnport loc3 --date 2019/10/31 --time 11:00
add_connection.py -u PAM110 --uprev A --upport e -d SNPC000040 --dnrev A --dnport e2 --date 2019/10/31 --time 11:00
add_connection.py -u PAM111 --uprev A --upport e -d SNPC000040 --dnrev A --dnport e6 --date 2019/10/31 --time 11:00
add_connection.py -u PAM112 --uprev A --upport e -d SNPC000040 --dnrev A --dnport e10 --date 2019/10/31 --time 11:00
add_connection.py -u PAM110 --uprev A --upport n -d SNPC000040 --dnrev A --dnport n0 --date 2019/10/31 --time 11:00
add_connection.py -u PAM111 --uprev A --upport n -d SNPC000040 --dnrev A --dnport n4 --date 2019/10/31 --time 11:00
add_connection.py -u PAM112 --uprev A --upport n -d SNPC000040 --dnrev A --dnport n8 --date 2019/10/31 --time 11:00
add_station.py ND05 --sernum 5 --date 2019/10/31 --time 10:00
add_part.py -p FPS07 -r A -t fem-power-supply -m FPS07 --date 2019/10/31 --time 10:00
add_part.py -p PCH06 -r A -t pam-chassis -m PCH06 --date 2019/10/31 --time 10:00
add_part.py -p NCMPro4 -r A -t node-control-module -m NCMPro4 --date 2019/10/31 --time 10:00
add_part.py -p N05 -r A -t node -m 5 --date 2019/10/31 --time 10:00
add_part.py -p NBP05 -r A -t node-bulkhead -m 5 --date 2019/10/31 --time 10:00
add_part.py -p PAM113 -r A -t post-amp -m 113 --date 2019/10/31 --time 10:00
add_part.py -p PAM114 -r A -t post-amp -m 114 --date 2019/10/31 --time 10:00
add_part.py -p PAM115 -r A -t post-amp -m 115 --date 2019/10/31 --time 10:00
add_part.py -p PAM116 -r A -t post-amp -m 116 --date 2019/10/31 --time 10:00
add_part.py -p PAM117 -r A -t post-amp -m 117 --date 2019/10/31 --time 10:00
add_part.py -p PAM118 -r A -t post-amp -m 118 --date 2019/10/31 --time 10:00
add_part.py -p PAM119 -r A -t post-amp -m 119 --date 2019/10/31 --time 10:00
add_part.py -p PAM120 -r A -t post-amp -m 120 --date 2019/10/31 --time 10:00
add_part.py -p PAM121 -r A -t post-amp -m 121 --date 2019/10/31 --time 10:00
add_part.py -p PAM122 -r A -t post-amp -m 122 --date 2019/10/31 --time 10:00
add_part.py -p PAM123 -r A -t post-amp -m 123 --date 2019/10/31 --time 10:00
add_part.py -p PAM124 -r A -t post-amp -m 124 --date 2019/10/31 --time 10:00
add_part.py -p SNPC000058 -r A -t snap -m C000058 --date 2019/10/31 --time 10:00
add_part.py -p SNPC000050 -r A -t snap -m C000050 --date 2019/10/31 --time 10:00
add_part.py -p SNPC000032 -r A -t snap -m C000032 --date 2019/10/31 --time 10:00
add_part.py -p SNPC000018 -r A -t snap -m C000018 --date 2019/10/31 --time 10:00
add_connection.py -u N05 --uprev A --upport @ground -d ND05 --dnrev A --dnport @ground --date 2019/10/31 --time 11:00
add_connection.py -u FPS07 --uprev A --upport @rack -d N05 --dnrev A --dnport @top --date 2019/10/31 --time 11:00
add_connection.py -u PCH06 --uprev A --upport @rack -d N05 --dnrev A --dnport @bottom --date 2019/10/31 --time 11:00
add_connection.py -u NCMPro4 --uprev A --upport @rack -d N05 --dnrev A --dnport @middle --date 2019/10/31 --time 11:00
add_connection.py -u PAM113 --uprev A --upport @slot -d PCH06 --dnrev A --dnport @slot1 --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport e1 -d PAM113 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport n1 -d PAM113 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM114 --uprev A --upport @slot -d PCH06 --dnrev A --dnport @slot2 --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport e2 -d PAM114 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport n2 -d PAM114 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM115 --uprev A --upport @slot -d PCH06 --dnrev A --dnport @slot3 --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport e3 -d PAM115 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport n3 -d PAM115 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM116 --uprev A --upport @slot -d PCH06 --dnrev A --dnport @slot4 --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport e4 -d PAM116 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport n4 -d PAM116 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM117 --uprev A --upport @slot -d PCH06 --dnrev A --dnport @slot5 --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport e5 -d PAM117 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport n5 -d PAM117 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM118 --uprev A --upport @slot -d PCH06 --dnrev A --dnport @slot6 --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport e6 -d PAM118 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport n6 -d PAM118 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM119 --uprev A --upport @slot -d PCH06 --dnrev A --dnport @slot7 --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport e7 -d PAM119 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport n7 -d PAM119 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM120 --uprev A --upport @slot -d PCH06 --dnrev A --dnport @slot8 --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport e8 -d PAM120 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport n8 -d PAM120 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM121 --uprev A --upport @slot -d PCH06 --dnrev A --dnport @slot9 --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport e9 -d PAM121 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport n9 -d PAM121 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM122 --uprev A --upport @slot -d PCH06 --dnrev A --dnport @slot10 --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport e10 -d PAM122 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport n10 -d PAM122 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM123 --uprev A --upport @slot -d PCH06 --dnrev A --dnport @slot11 --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport e11 -d PAM123 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport n11 -d PAM123 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u PAM124 --uprev A --upport @slot -d PCH06 --dnrev A --dnport @slot12 --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport e12 -d PAM124 --dnrev A --dnport e --date 2019/10/31 --time 11:00
add_connection.py -u NBP05 --uprev A --upport n12 -d PAM124 --dnrev A --dnport n --date 2019/10/31 --time 11:00
add_connection.py -u SNPC000058 --uprev A --upport rack -d N05 --dnrev A --dnport loc0 --date 2019/10/31 --time 11:00
add_connection.py -u PAM113 --uprev A --upport e -d SNPC000058 --dnrev A --dnport e2 --date 2019/10/31 --time 11:00
add_connection.py -u PAM114 --uprev A --upport e -d SNPC000058 --dnrev A --dnport e6 --date 2019/10/31 --time 11:00
add_connection.py -u PAM115 --uprev A --upport e -d SNPC000058 --dnrev A --dnport e10 --date 2019/10/31 --time 11:00
add_connection.py -u PAM113 --uprev A --upport n -d SNPC000058 --dnrev A --dnport n0 --date 2019/10/31 --time 11:00
add_connection.py -u PAM114 --uprev A --upport n -d SNPC000058 --dnrev A --dnport n4 --date 2019/10/31 --time 11:00
add_connection.py -u PAM115 --uprev A --upport n -d SNPC000058 --dnrev A --dnport n8 --date 2019/10/31 --time 11:00
add_connection.py -u SNPC000050 --uprev A --upport rack -d N05 --dnrev A --dnport loc1 --date 2019/10/31 --time 11:00
add_connection.py -u PAM116 --uprev A --upport e -d SNPC000050 --dnrev A --dnport e2 --date 2019/10/31 --time 11:00
add_connection.py -u PAM117 --uprev A --upport e -d SNPC000050 --dnrev A --dnport e6 --date 2019/10/31 --time 11:00
add_connection.py -u PAM118 --uprev A --upport e -d SNPC000050 --dnrev A --dnport e10 --date 2019/10/31 --time 11:00
add_connection.py -u PAM116 --uprev A --upport n -d SNPC000050 --dnrev A --dnport n0 --date 2019/10/31 --time 11:00
add_connection.py -u PAM117 --uprev A --upport n -d SNPC000050 --dnrev A --dnport n4 --date 2019/10/31 --time 11:00
add_connection.py -u PAM118 --uprev A --upport n -d SNPC000050 --dnrev A --dnport n8 --date 2019/10/31 --time 11:00
add_connection.py -u SNPC000032 --uprev A --upport rack -d N05 --dnrev A --dnport loc2 --date 2019/10/31 --time 11:00
add_connection.py -u PAM119 --uprev A --upport e -d SNPC000032 --dnrev A --dnport e2 --date 2019/10/31 --time 11:00
add_connection.py -u PAM120 --uprev A --upport e -d SNPC000032 --dnrev A --dnport e6 --date 2019/10/31 --time 11:00
add_connection.py -u PAM121 --uprev A --upport e -d SNPC000032 --dnrev A --dnport e10 --date 2019/10/31 --time 11:00
add_connection.py -u PAM119 --uprev A --upport n -d SNPC000032 --dnrev A --dnport n0 --date 2019/10/31 --time 11:00
add_connection.py -u PAM120 --uprev A --upport n -d SNPC000032 --dnrev A --dnport n4 --date 2019/10/31 --time 11:00
add_connection.py -u PAM121 --uprev A --upport n -d SNPC000032 --dnrev A --dnport n8 --date 2019/10/31 --time 11:00
add_connection.py -u SNPC000018 --uprev A --upport rack -d N05 --dnrev A --dnport loc3 --date 2019/10/31 --time 11:00
add_connection.py -u PAM122 --uprev A --upport e -d SNPC000018 --dnrev A --dnport e2 --date 2019/10/31 --time 11:00
add_connection.py -u PAM123 --uprev A --upport e -d SNPC000018 --dnrev A --dnport e6 --date 2019/10/31 --time 11:00
add_connection.py -u PAM124 --uprev A --upport e -d SNPC000018 --dnrev A --dnport e10 --date 2019/10/31 --time 11:00
add_connection.py -u PAM122 --uprev A --upport n -d SNPC000018 --dnrev A --dnport n0 --date 2019/10/31 --time 11:00
add_connection.py -u PAM123 --uprev A --upport n -d SNPC000018 --dnrev A --dnport n4 --date 2019/10/31 --time 11:00
add_connection.py -u PAM124 --uprev A --upport n -d SNPC000018 --dnrev A --dnport n8 --date 2019/10/31 --time 11:00
