#! /bin/bash
source ~/.bashrc
echo "191213_infoupd_1642" >> scripts.log 
update_apriori.py -p HH92 -s passed_checks --date 2019/12/13 --time 16:42
update_apriori.py -p HH93 -s passed_checks --date 2019/12/13 --time 16:42
update_apriori.py -p HH94 -s passed_checks --date 2019/12/13 --time 16:42
update_apriori.py -p HH109 -s passed_checks --date 2019/12/13 --time 16:42
update_apriori.py -p HH110 -s needs_checking --date 2019/12/13 --time 16:42
update_apriori.py -p HH111 -s passed_checks --date 2019/12/13 --time 16:42
update_apriori.py -p HH112 -s passed_checks --date 2019/12/13 --time 16:42
update_apriori.py -p HH127 -s needs_checking --date 2019/12/13 --time 16:42
update_apriori.py -p HH128 -s needs_checking --date 2019/12/13 --time 16:42
update_apriori.py -p HH129 -s needs_checking --date 2019/12/13 --time 16:42
update_apriori.py -p HH130 -s passed_checks --date 2019/12/13 --time 16:42
