#! /bin/bash
echo "./191205_add_stations.py" >> scripts.log 
add_station.py HH288 --sernum 287 --date 2019/11/28 --time 10:00
add_part.py -p A288 -r H -t antenna -m S/N287 --date 2019/11/28 --time 10:00
add_connection.py -u HH288 --uprev A --upport ground -d A288 --dnrev H --dnport ground --date 2019/11/28 --time 10:00
add_station.py HH289 --sernum 288 --date 2019/11/29 --time 10:00
add_part.py -p A289 -r H -t antenna -m S/N288 --date 2019/11/29 --time 10:00
add_connection.py -u HH289 --uprev A --upport ground -d A289 --dnrev H --dnport ground --date 2019/11/29 --time 10:00
add_station.py HH290 --sernum 290 --date 2019/12/02 --time 10:00
add_part.py -p A290 -r H -t antenna -m S/N290 --date 2019/12/02 --time 10:00
add_connection.py -u HH290 --uprev A --upport ground -d A290 --dnrev H --dnport ground --date 2019/12/02 --time 10:00
add_station.py HH291 --sernum 262 --date 2019/12/03 --time 10:00
add_part.py -p A291 -r H -t antenna -m S/N262 --date 2019/12/03 --time 10:00
add_connection.py -u HH291 --uprev A --upport ground -d A291 --dnrev H --dnport ground --date 2019/12/03 --time 10:00
add_station.py HH292 --sernum 275 --date 2019/12/03 --time 10:00
add_part.py -p A292 -r H -t antenna -m S/N275 --date 2019/12/03 --time 10:00
add_connection.py -u HH292 --uprev A --upport ground -d A292 --dnrev H --dnport ground --date 2019/12/03 --time 10:00
