#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220105_infoupd_0342" >> scripts.log 
add_part_info.py -p HH134 -r A -c 'cables too short' -l "infoupd" --date 2022/01/05 --time 03:42:00
