#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220130_infoupd_1742" >> scripts.log 
add_part_info.py -p HH210 -r A -c 'Feed heights (NE/SE/SW/NW): 4.408' -l "infoupd" --date 2022/01/30 --time 17:42:00
