#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220216_infoupd_1542" >> scripts.log 
add_part_info.py -p HH22 -r A -c 'Feed heights (NE/SE/SW/NW): 4.402' -l "infoupd" --date 2022/02/16 --time 15:42:00
add_part_info.py -p HH34 -r A -c 'Feed heights (NE/SE/SW/NW): 4.408' -l "infoupd" --date 2022/02/16 --time 15:42:00
add_part_info.py -p HH35 -r A -c 'Feed heights (NE/SE/SW/NW): 4.415' -l "infoupd" --date 2022/02/16 --time 15:42:00
add_part_info.py -p HH47 -r A -c 'Feed heights (NE/SE/SW/NW): 4.41' -l "infoupd" --date 2022/02/16 --time 15:42:00
add_part_info.py -p HH61 -r A -c 'Feed heights (NE/SE/SW/NW): 4.413' -l "infoupd" --date 2022/02/16 --time 15:42:00
