#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220217_infoupd_1342" >> scripts.log 
add_part_info.py -p HH77 -r A -c 'Feed heights (NE/SE/SW/NW): 4.402' -l "infoupd" --date 2022/02/17 --time 13:42:00
add_part_info.py -p HH48 -r A -c 'FEM changed to 324' -l "infoupd" --date 2022/02/17 --time 13:42:00
add_part_info.py -p HH48 -r A -c 'Feed heights (NE/SE/SW/NW): 4.405' -l "infoupd" --date 2022/02/17 --time 13:42:02
add_part_info.py -p HH49 -r A -c 'Feed heights (NE/SE/SW/NW): 4.402' -l "infoupd" --date 2022/02/17 --time 13:42:00
add_part_info.py -p HH62 -r A -c 'Feed heights (NE/SE/SW/NW): 4.405' -l "infoupd" --date 2022/02/17 --time 13:42:00
add_part_info.py -p HH63 -r A -c 'FEM changed to 295' -l "infoupd" --date 2022/02/17 --time 13:42:00
add_part_info.py -p HH63 -r A -c 'Feed heights (NE/SE/SW/NW): 4.411' -l "infoupd" --date 2022/02/17 --time 13:42:02
add_part_info.py -p HH64 -r A -c 'Feed heights (NE/SE/SW/NW): 4.406' -l "infoupd" --date 2022/02/17 --time 13:42:00
add_part_info.py -p HH78 -r A -c 'Feed heights (NE/SE/SW/NW): 4.407' -l "infoupd" --date 2022/02/17 --time 13:42:00
