#! /bin/bash
echo "220318_add_node17" >> scripts.log 
add_station.py ND17 --sernum ND17 --date 2022/03/18 --time 10:00
add_part.py -p FPS23 -r A -t fem-power-supply -m FPS23 --date 2022/03/18 --time 10:00
add_part.py -p PCH23 -r A -t pam-chassis -m PCH23 --date 2022/03/18 --time 10:00
add_part.py -p NBP17 -r A -t node-bulkhead -m NBP17 --date 2022/03/18 --time 10:00
add_part.py -p PAM293 -r A -t post-amp -m 293 --date 2022/03/18 --time 10:00
add_part.py -p PAM294 -r A -t post-amp -m 294 --date 2022/03/18 --time 10:00
add_part.py -p PAM295 -r A -t post-amp -m 295 --date 2022/03/18 --time 10:00
add_part.py -p PAM296 -r A -t post-amp -m 296 --date 2022/03/18 --time 10:00
add_part.py -p PAM297 -r A -t post-amp -m 297 --date 2022/03/18 --time 10:00
add_part.py -p PAM298 -r A -t post-amp -m 298 --date 2022/03/18 --time 10:00
add_part.py -p PAM299 -r A -t post-amp -m 299 --date 2022/03/18 --time 10:00
add_part.py -p PAM300 -r A -t post-amp -m 300 --date 2022/03/18 --time 10:00
add_part.py -p PAM301 -r A -t post-amp -m 301 --date 2022/03/18 --time 10:00
add_part.py -p PAM302 -r A -t post-amp -m 302 --date 2022/03/18 --time 10:00
add_part.py -p PAM303 -r A -t post-amp -m 303 --date 2022/03/18 --time 10:00
add_part.py -p PAM304 -r A -t post-amp -m 304 --date 2022/03/18 --time 10:00
add_connection.py -u N17 --uprev A --upport ground -d ND17 --dnrev A --dnport ground --date 2022/03/18 --time 10:00
add_connection.py -u FPS23 --uprev A --upport rack -d N17 --dnrev A --dnport top --date 2022/03/18 --time 10:00
add_connection.py -u PCH23 --uprev A --upport rack -d N17 --dnrev A --dnport bottom --date 2022/03/18 --time 10:00
add_connection.py -u NCM22 --uprev A --upport rack -d N17 --dnrev A --dnport middle --date 2022/03/18 --time 10:00
add_connection.py -u PAM293 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot1 --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport e1 -d PAM293 --dnrev A --dnport e --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport n1 -d PAM293 --dnrev A --dnport n --date 2022/03/18 --time 10:00
add_connection.py -u PAM294 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot2 --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport e2 -d PAM294 --dnrev A --dnport e --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport n2 -d PAM294 --dnrev A --dnport n --date 2022/03/18 --time 10:00
add_connection.py -u PAM295 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot3 --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport e3 -d PAM295 --dnrev A --dnport e --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport n3 -d PAM295 --dnrev A --dnport n --date 2022/03/18 --time 10:00
add_connection.py -u PAM296 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot4 --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport e4 -d PAM296 --dnrev A --dnport e --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport n4 -d PAM296 --dnrev A --dnport n --date 2022/03/18 --time 10:00
add_connection.py -u PAM297 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot5 --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport e5 -d PAM297 --dnrev A --dnport e --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport n5 -d PAM297 --dnrev A --dnport n --date 2022/03/18 --time 10:00
add_connection.py -u PAM298 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot6 --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport e6 -d PAM298 --dnrev A --dnport e --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport n6 -d PAM298 --dnrev A --dnport n --date 2022/03/18 --time 10:00
add_connection.py -u PAM299 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot7 --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport e7 -d PAM299 --dnrev A --dnport e --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport n7 -d PAM299 --dnrev A --dnport n --date 2022/03/18 --time 10:00
add_connection.py -u PAM300 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot8 --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport e8 -d PAM300 --dnrev A --dnport e --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport n8 -d PAM300 --dnrev A --dnport n --date 2022/03/18 --time 10:00
add_connection.py -u PAM301 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot9 --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport e9 -d PAM301 --dnrev A --dnport e --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport n9 -d PAM301 --dnrev A --dnport n --date 2022/03/18 --time 10:00
add_connection.py -u PAM302 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot10 --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport e10 -d PAM302 --dnrev A --dnport e --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport n10 -d PAM302 --dnrev A --dnport n --date 2022/03/18 --time 10:00
add_connection.py -u PAM303 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot11 --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport e11 -d PAM303 --dnrev A --dnport e --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport n11 -d PAM303 --dnrev A --dnport n --date 2022/03/18 --time 10:00
add_connection.py -u PAM304 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot12 --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport e12 -d PAM304 --dnrev A --dnport e --date 2022/03/18 --time 10:00
add_connection.py -u NBP17 --uprev A --upport n12 -d PAM304 --dnrev A --dnport n --date 2022/03/18 --time 10:00
add_connection.py -u SNPC000087 --uprev A --upport rack -d N17 --dnrev A --dnport loc0 --date 2022/03/18 --time 10:00
add_connection.py -u PAM293 --uprev A --upport e -d SNPC000087 --dnrev A --dnport e2 --date 2022/03/18 --time 10:00
add_connection.py -u PAM294 --uprev A --upport e -d SNPC000087 --dnrev A --dnport e6 --date 2022/03/18 --time 10:00
add_connection.py -u PAM295 --uprev A --upport e -d SNPC000087 --dnrev A --dnport e10 --date 2022/03/18 --time 10:00
add_connection.py -u PAM293 --uprev A --upport n -d SNPC000087 --dnrev A --dnport n0 --date 2022/03/18 --time 10:00
add_connection.py -u PAM294 --uprev A --upport n -d SNPC000087 --dnrev A --dnport n4 --date 2022/03/18 --time 10:00
add_connection.py -u PAM295 --uprev A --upport n -d SNPC000087 --dnrev A --dnport n8 --date 2022/03/18 --time 10:00
add_connection.py -u SNPC000052 --uprev A --upport rack -d N17 --dnrev A --dnport loc1 --date 2022/03/18 --time 10:00
add_connection.py -u PAM296 --uprev A --upport e -d SNPC000052 --dnrev A --dnport e2 --date 2022/03/18 --time 10:00
add_connection.py -u PAM297 --uprev A --upport e -d SNPC000052 --dnrev A --dnport e6 --date 2022/03/18 --time 10:00
add_connection.py -u PAM298 --uprev A --upport e -d SNPC000052 --dnrev A --dnport e10 --date 2022/03/18 --time 10:00
add_connection.py -u PAM296 --uprev A --upport n -d SNPC000052 --dnrev A --dnport n0 --date 2022/03/18 --time 10:00
add_connection.py -u PAM297 --uprev A --upport n -d SNPC000052 --dnrev A --dnport n4 --date 2022/03/18 --time 10:00
add_connection.py -u PAM298 --uprev A --upport n -d SNPC000052 --dnrev A --dnport n8 --date 2022/03/18 --time 10:00
add_connection.py -u SNPC000034 --uprev A --upport rack -d N17 --dnrev A --dnport loc2 --date 2022/03/18 --time 10:00
add_connection.py -u PAM299 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e2 --date 2022/03/18 --time 10:00
add_connection.py -u PAM300 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e6 --date 2022/03/18 --time 10:00
add_connection.py -u PAM301 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e10 --date 2022/03/18 --time 10:00
add_connection.py -u PAM299 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n0 --date 2022/03/18 --time 10:00
add_connection.py -u PAM300 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n4 --date 2022/03/18 --time 10:00
add_connection.py -u PAM301 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n8 --date 2022/03/18 --time 10:00
add_connection.py -u SNPC000027 --uprev A --upport rack -d N17 --dnrev A --dnport loc3 --date 2022/03/18 --time 10:00
add_connection.py -u PAM302 --uprev A --upport e -d SNPC000027 --dnrev A --dnport e2 --date 2022/03/18 --time 10:00
add_connection.py -u PAM303 --uprev A --upport e -d SNPC000027 --dnrev A --dnport e6 --date 2022/03/18 --time 10:00
add_connection.py -u PAM304 --uprev A --upport e -d SNPC000027 --dnrev A --dnport e10 --date 2022/03/18 --time 10:00
add_connection.py -u PAM302 --uprev A --upport n -d SNPC000027 --dnrev A --dnport n0 --date 2022/03/18 --time 10:00
add_connection.py -u PAM303 --uprev A --upport n -d SNPC000027 --dnrev A --dnport n4 --date 2022/03/18 --time 10:00
add_connection.py -u PAM304 --uprev A --upport n -d SNPC000027 --dnrev A --dnport n8 --date 2022/03/18 --time 10:00
