#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220328_infoupd_1642" >> scripts.log 
add_part_info.py -p HH171 -r A -c 'Spectre: N16P2N' -l "infoupd" --date 2022/03/28 --time 16:42:00
add_part_info.py -p HH192 -r A -c 'Spectre: N15P5N' -l "infoupd" --date 2022/03/28 --time 16:42:00
add_part_info.py -p HH193 -r A -c 'Spectre: N16P6E' -l "infoupd" --date 2022/03/28 --time 16:42:00
add_part_info.py -p HH193 -r A -c 'Spectre: N16P6N' -l "infoupd" --date 2022/03/28 --time 16:42:02
add_part_info.py -p HH152 -r A -c 'Spectre: N16P7E' -l "infoupd" --date 2022/03/28 --time 16:42:00
add_part_info.py -p HH152 -r A -c 'Spectre: N16P7N' -l "infoupd" --date 2022/03/28 --time 16:42:02
add_part_info.py -p HH153 -r A -c 'Spectre: N16P8E' -l "infoupd" --date 2022/03/28 --time 16:42:00
add_part_info.py -p HH153 -r A -c 'Spectre: N16P8N' -l "infoupd" --date 2022/03/28 --time 16:42:02
add_part_info.py -p HH154 -r A -c 'Spectre: N16P9E' -l "infoupd" --date 2022/03/28 --time 16:42:00
add_part_info.py -p HH154 -r A -c 'Spectre: N16P9N' -l "infoupd" --date 2022/03/28 --time 16:42:02
add_part_info.py -p HH174 -r A -c 'Spectre: N16P10E' -l "infoupd" --date 2022/03/28 --time 16:42:00
add_part_info.py -p HH174 -r A -c 'Spectre: N16P10N' -l "infoupd" --date 2022/03/28 --time 16:42:02
