#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220304_infoupd_1442" >> scripts.log 
add_part_info.py -p HH6 -r A -c 'Need to replace mesh panel' -l "infoupd" --date 2022/03/04 --time 14:42:00
add_part_info.py -p N12 -r A -c 'no plastic inside node, very dusty inside, bottom temperature sensor has no data (port 0), NCM temperature port 2 broken, no utility power strip' -l "infoupd" --date 2022/03/04 --time 14:42:00
