#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220308_infoupd_0942" >> scripts.log 
add_part_info.py -p N20 -r A -c 'humidity sensor broken (port 1, temperature measurement on temperature-humidity sensor is still working)' -l "infoupd" --date 2022/03/08 --time 09:42:00
