#! /bin/bash
echo "/Users/ddeboer/Documents/ubase/Projects/HERA/ops/hera_cm_db_updates/220317_ddb_0914" >> scripts.log 
# Stop old connections
stop_connection.py -u WRA000089 --uprev A --upport mnt -d NCM05 --dnrev A --dnport mnt1 --date 2022/03/04 --time 10:00
stop_connection.py -u WRA000080 --uprev A --upport mnt -d NCM12 --dnrev A --dnport mnt1 --date 2022/03/08 --time 10:00
# Remove IP info
add_part_info.py -p WRA000089 -r A -c 'IP - ' -l removed --date 2022/03/04 --time 10:00
add_part_info.py -p WRA000080 -r A -c 'IP - ' -l removed --date 2022/03/08 --time 10:00
# Adding missing parts
add_part.py -p WRA000758 -r A -t white-rabbit -m 7S-WRLEN-V1.1-S4-758 --date 2022/03/08 --time 09:00
# Adding new connections
add_connection.py -u WRA000095 --uprev A --upport mnt -d NCM05 --dnrev A --dnport mnt1 --date 2022/03/04 --time 11:00
add_connection.py -u WRA000758 --uprev A --upport mnt -d NCM12 --dnrev A --dnport mnt1 --date 2022/03/08 --time 11:00
# Add info
add_part_info.py -p WRA000095 -r A -c 'IP - 10.80.2.151' -l added --date 2022/03/04 --time 10:00
add_part_info.py -p WRA000758 -r A -c 'MAC - 08:00:30:b7:11:d0' -l added --date 2022/03/08 --time 10:00
add_part_info.py -p WRA000758 -r A -c 'IP - 10.80.2.147' -l added --date 2022/03/08 --time 10:01
