#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220328_infoupd_1542" >> scripts.log 
add_part_info.py -p HH115 -r A -c 'Spectre: N11P2E' -l "infoupd" --date 2022/03/28 --time 15:42:00
add_part_info.py -p HH115 -r A -c 'Spectre: N11P2N' -l "infoupd" --date 2022/03/28 --time 15:42:02
add_part_info.py -p HH96 -r A -c 'Spectre: N11P8E' -l "infoupd" --date 2022/03/28 --time 15:42:00
add_part_info.py -p HH96 -r A -c 'Spectre: N11P8N' -l "infoupd" --date 2022/03/28 --time 15:42:02
add_part_info.py -p HH79 -r A -c 'Spectre: N11P10E' -l "infoupd" --date 2022/03/28 --time 15:42:00
add_part_info.py -p HH79 -r A -c 'Spectre: N11P10N' -l "infoupd" --date 2022/03/28 --time 15:42:02
add_part_info.py -p HH95 -r A -c 'Feed heights (NE/SE/SW/NW): 4.408' -l "infoupd" --date 2022/03/28 --time 15:42:00
add_part_info.py -p HH95 -r A -c 'Spectre: N11P11E' -l "infoupd" --date 2022/03/28 --time 15:42:02
add_part_info.py -p HH95 -r A -c 'Spectre: N11P11N' -l "infoupd" --date 2022/03/28 --time 15:42:04
add_part_info.py -p HH151 -r A -c 'Spectre: N16P1E' -l "infoupd" --date 2022/03/28 --time 15:42:00
add_part_info.py -p HH151 -r A -c 'Spectre: N16P1N' -l "infoupd" --date 2022/03/28 --time 15:42:02
add_part_info.py -p HH171 -r A -c 'Spectre: N16P2E' -l "infoupd" --date 2022/03/28 --time 15:42:00
add_part_info.py -p HH171 -r A -c 'Spectre: N16P2n' -l "infoupd" --date 2022/03/28 --time 15:42:02
add_part_info.py -p HH192 -r A -c 'Spectre: N16P5E' -l "infoupd" --date 2022/03/28 --time 15:42:00
add_part_info.py -p HH154 -r A -c 'Feed heights (NE/SE/SW/NW): 4.400' -l "infoupd" --date 2022/03/28 --time 15:42:00
