#! /bin/bash
echo "/Users/ddeboer/Documents/ubase/Projects/HERA/ops/hera_cm_db_updates/220317_connupd_1109" >> scripts.log 
# Adding missing parts
add_part.py -p FEM293 -r A -t front-end -m FEM293 --date 2022/03/17 --time 11:04
add_part.py -p FDV216 -r A -t feed -m FDV216 --date 2022/03/17 --time 11:04
add_part.py -p PAM305 -r A -t post-amp -m PAM305 --date 2022/03/17 --time 11:04
add_part.py -p PAM312 -r A -t post-amp -m PAM312 --date 2022/03/17 --time 11:04
add_part.py -p FDV256 -r A -t feed -m FDV256 --date 2022/03/17 --time 11:04
add_part.py -p FEM298 -r A -t front-end -m FEM298 --date 2022/03/17 --time 11:04
add_part.py -p FEM302 -r A -t front-end -m FEM302 --date 2022/03/17 --time 11:04
add_part.py -p FEM294 -r A -t front-end -m FEM294 --date 2022/03/17 --time 11:04
add_part.py -p FDV259 -r A -t feed -m FDV259 --date 2022/03/17 --time 11:04
add_part.py -p FDV220 -r A -t feed -m FDV220 --date 2022/03/17 --time 11:04
add_part.py -p FDV258 -r A -t feed -m FDV258 --date 2022/03/17 --time 11:04
add_part.py -p FEM310 -r A -t front-end -m FEM310 --date 2022/03/17 --time 11:04
add_part.py -p PAM307 -r A -t post-amp -m PAM307 --date 2022/03/17 --time 11:04
add_part.py -p PAM306 -r A -t post-amp -m PAM306 --date 2022/03/17 --time 11:04
add_part.py -p FDV219 -r A -t feed -m FDV219 --date 2022/03/17 --time 11:04
add_part.py -p FEM304 -r A -t front-end -m FEM304 --date 2022/03/17 --time 11:04
add_part.py -p PAM311 -r A -t post-amp -m PAM311 --date 2022/03/17 --time 11:04
add_part.py -p PAM313 -r A -t post-amp -m PAM313 --date 2022/03/17 --time 11:04
add_part.py -p NBP21 -r A -t node-bulkhead -m NBP21 --date 2022/03/17 --time 11:04
# Adding missing connections
add_connection.py -u A175 --uprev H --upport focus -d FDV258 --dnrev A --dnport input --date 2022/03/17 --time 11:09
add_connection.py -u FDV258 --uprev A --upport terminals -d FEM293 --dnrev A --dnport input --date 2022/03/17 --time 11:09
add_connection.py -u FEM293 --uprev A --upport e -d NBP21 --dnrev A --dnport e1 --date 2022/03/17 --time 11:09
add_connection.py -u FEM293 --uprev A --upport n -d NBP21 --dnrev A --dnport n1 --date 2022/03/17 --time 11:09
add_connection.py -u NBP21 --uprev A --upport e1 -d PAM305 --dnrev A --dnport e --date 2022/03/17 --time 11:09
add_connection.py -u NBP21 --uprev A --upport n1 -d PAM305 --dnrev A --dnport n --date 2022/03/17 --time 11:09
add_connection.py -u NBP21 --uprev A --upport e2 -d PAM306 --dnrev A --dnport e --date 2022/03/17 --time 11:09
add_connection.py -u NBP21 --uprev A --upport n2 -d PAM306 --dnrev A --dnport n --date 2022/03/17 --time 11:09
add_connection.py -u NBP21 --uprev A --upport e7 -d PAM311 --dnrev A --dnport e --date 2022/03/17 --time 11:09
add_connection.py -u NBP21 --uprev A --upport n7 -d PAM311 --dnrev A --dnport n --date 2022/03/17 --time 11:09
add_connection.py -u NBP21 --uprev A --upport e3 -d PAM307 --dnrev A --dnport e --date 2022/03/17 --time 11:09
add_connection.py -u NBP21 --uprev A --upport n3 -d PAM307 --dnrev A --dnport n --date 2022/03/17 --time 11:09
add_connection.py -u NBP21 --uprev A --upport e8 -d PAM312 --dnrev A --dnport e --date 2022/03/17 --time 11:09
add_connection.py -u NBP21 --uprev A --upport n8 -d PAM312 --dnrev A --dnport n --date 2022/03/17 --time 11:09
add_connection.py -u NBP21 --uprev A --upport e9 -d PAM313 --dnrev A --dnport e --date 2022/03/17 --time 11:09
add_connection.py -u NBP21 --uprev A --upport n9 -d PAM313 --dnrev A --dnport n --date 2022/03/17 --time 11:09
add_connection.py -u PAM305 --uprev A --upport e -d SNPC000099 --dnrev A --dnport e2 --date 2022/03/17 --time 11:09
add_connection.py -u PAM305 --uprev A --upport n -d SNPC000099 --dnrev A --dnport n0 --date 2022/03/17 --time 11:09
add_connection.py -u SNPC000099 --uprev A --upport rack -d N21 --dnrev A --dnport loc0 --date 2022/03/17 --time 11:09
add_connection.py -u A195 --uprev H --upport focus -d FDV259 --dnrev A --dnport input --date 2022/03/17 --time 11:09
add_connection.py -u FDV259 --uprev A --upport terminals -d FEM302 --dnrev A --dnport input --date 2022/03/17 --time 11:09
add_connection.py -u FEM302 --uprev A --upport e -d NBP21 --dnrev A --dnport e2 --date 2022/03/17 --time 11:09
add_connection.py -u FEM302 --uprev A --upport n -d NBP21 --dnrev A --dnport n2 --date 2022/03/17 --time 11:09
add_connection.py -u PAM306 --uprev A --upport e -d SNPC000099 --dnrev A --dnport e6 --date 2022/03/17 --time 11:09
add_connection.py -u PAM306 --uprev A --upport n -d SNPC000099 --dnrev A --dnport n4 --date 2022/03/17 --time 11:09
add_connection.py -u A212 --uprev H --upport focus -d FDV256 --dnrev A --dnport input --date 2022/03/17 --time 11:09
add_connection.py -u FDV256 --uprev A --upport terminals -d FEM294 --dnrev A --dnport input --date 2022/03/17 --time 11:09
add_connection.py -u FEM294 --uprev A --upport e -d NBP21 --dnrev A --dnport e7 --date 2022/03/17 --time 11:09
add_connection.py -u FEM294 --uprev A --upport n -d NBP21 --dnrev A --dnport n7 --date 2022/03/17 --time 11:09
add_connection.py -u PAM311 --uprev A --upport e -d SNPC000098 --dnrev A --dnport e2 --date 2022/03/17 --time 11:09
add_connection.py -u PAM311 --uprev A --upport n -d SNPC000098 --dnrev A --dnport n0 --date 2022/03/17 --time 11:09
add_connection.py -u SNPC000098 --uprev A --upport rack -d N21 --dnrev A --dnport loc2 --date 2022/03/17 --time 11:09
add_connection.py -u A214 --uprev H --upport focus -d FDV216 --dnrev A --dnport input --date 2022/03/17 --time 11:09
add_connection.py -u FDV216 --uprev A --upport terminals -d FEM310 --dnrev A --dnport input --date 2022/03/17 --time 11:09
add_connection.py -u FEM310 --uprev A --upport e -d NBP21 --dnrev A --dnport e3 --date 2022/03/17 --time 11:09
add_connection.py -u FEM310 --uprev A --upport n -d NBP21 --dnrev A --dnport n3 --date 2022/03/17 --time 11:09
add_connection.py -u PAM307 --uprev A --upport e -d SNPC000099 --dnrev A --dnport e10 --date 2022/03/17 --time 11:09
add_connection.py -u PAM307 --uprev A --upport n -d SNPC000099 --dnrev A --dnport n8 --date 2022/03/17 --time 11:09
add_connection.py -u A231 --uprev H --upport focus -d FDV220 --dnrev A --dnport input --date 2022/03/17 --time 11:09
add_connection.py -u FDV220 --uprev A --upport terminals -d FEM298 --dnrev A --dnport input --date 2022/03/17 --time 11:09
add_connection.py -u FEM298 --uprev A --upport e -d NBP21 --dnrev A --dnport e8 --date 2022/03/17 --time 11:09
add_connection.py -u FEM298 --uprev A --upport n -d NBP21 --dnrev A --dnport n8 --date 2022/03/17 --time 11:09
add_connection.py -u PAM312 --uprev A --upport e -d SNPC000098 --dnrev A --dnport e6 --date 2022/03/17 --time 11:09
add_connection.py -u PAM312 --uprev A --upport n -d SNPC000098 --dnrev A --dnport n4 --date 2022/03/17 --time 11:09
add_connection.py -u A232 --uprev H --upport focus -d FDV219 --dnrev A --dnport input --date 2022/03/17 --time 11:09
add_connection.py -u FDV219 --uprev A --upport terminals -d FEM304 --dnrev A --dnport input --date 2022/03/17 --time 11:09
add_connection.py -u FEM304 --uprev A --upport e -d NBP21 --dnrev A --dnport e9 --date 2022/03/17 --time 11:09
add_connection.py -u FEM304 --uprev A --upport n -d NBP21 --dnrev A --dnport n9 --date 2022/03/17 --time 11:09
add_connection.py -u PAM313 --uprev A --upport e -d SNPC000098 --dnrev A --dnport e10 --date 2022/03/17 --time 11:09
add_connection.py -u PAM313 --uprev A --upport n -d SNPC000098 --dnrev A --dnport n8 --date 2022/03/17 --time 11:09
# Adding missing parts
