#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220304_infoupd_1042" >> scripts.log 
add_part_info.py -p HH167 -r A -c 'feed conduit fell out' -l "infoupd" --date 2022/03/04 --time 10:42:00
add_part_info.py -p HH207 -r A -c 'door open 03/03/22' -l "infoupd" --date 2022/03/04 --time 10:42:00
