#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220323_infoupd_1142" >> scripts.log 
add_part_info.py -p HH151 -r A -c 'Feed heights (NE/SE/SW/NW): 4.409' -l "infoupd" --date 2022/03/23 --time 11:42:00
add_part_info.py -p HH171 -r A -c 'Feed heights (NE/SE/SW/NW): 4.404' -l "infoupd" --date 2022/03/23 --time 11:42:00
add_part_info.py -p HH192 -r A -c 'Feed heights (NE/SE/SW/NW): 4.406' -l "infoupd" --date 2022/03/23 --time 11:42:00
add_part_info.py -p HH193 -r A -c 'Feed heights (NE/SE/SW/NW): 4.403' -l "infoupd" --date 2022/03/23 --time 11:42:00
add_part_info.py -p HH152 -r A -c 'Feed heights (NE/SE/SW/NW): 4.405' -l "infoupd" --date 2022/03/23 --time 11:42:00
add_part_info.py -p HH153 -r A -c 'Feed heights (NE/SE/SW/NW): 4.410' -l "infoupd" --date 2022/03/23 --time 11:42:00
add_part_info.py -p HH154 -r A -c 'Feed heights (NE/SE/SW/NW): 4.40' -l "infoupd" --date 2022/03/23 --time 11:42:00
add_part_info.py -p HH174 -r A -c 'Feed heights (NE/SE/SW/NW): 4.402' -l "infoupd" --date 2022/03/23 --time 11:42:00
