#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220317_infoupd_0842" >> scripts.log 
add_part_info.py -p HH115 -r A -c 'Feed heights (NE/SE/SW/NW): 4.416' -l "infoupd" --date 2022/03/17 --time 08:42:00
add_part_info.py -p HH96 -r A -c 'Feed heights (NE/SE/SW/NW): 4.407' -l "infoupd" --date 2022/03/17 --time 08:42:00
add_part_info.py -p HH79 -r A -c 'Feed heights (NE/SE/SW/NW): 4.406' -l "infoupd" --date 2022/03/17 --time 08:42:00
