#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220424_infoupd_1842" >> scripts.log 
add_part_info.py -p HH18 -r A -c 'Josh noted time variability over a few nights.' -l "infoupd" --date 2022/04/24 --time 18:42:00
add_part_info.py -p HH94 -r A -c 'Josh noted time variability over a few nights.' -l "infoupd" --date 2022/04/24 --time 18:42:00
add_part_info.py -p HH200 -r A -c 'East channel has low power feed not raised' -l "infoupd" --date 2022/04/24 --time 18:42:00
add_part_info.py -p HH201 -r A -c 'door closed 25/10/2021' -l "infoupd" --date 2022/04/24 --time 18:42:00
add_part_info.py -p HH201 -r A -c 'Spectre: N18P2E' -l "infoupd" --date 2022/04/24 --time 18:42:02
add_part_info.py -p HH201 -r A -c 'Feed heights (NE/SE/SW/NW): 4.407' -l "infoupd" --date 2022/04/24 --time 18:42:04
add_part_info.py -p HH201 -r A -c 'Spectre: N18P2N' -l "infoupd" --date 2022/04/24 --time 18:42:06
add_part_info.py -p HH202 -r A -c 'door closed 25/10/2021' -l "infoupd" --date 2022/04/24 --time 18:42:00
add_part_info.py -p HH202 -r A -c 'Spectre: N18P3E' -l "infoupd" --date 2022/04/24 --time 18:42:02
add_part_info.py -p HH202 -r A -c 'Feed heights (NE/SE/SW/NW): 4.401' -l "infoupd" --date 2022/04/24 --time 18:42:04
add_part_info.py -p HH202 -r A -c 'Spectre: N18P3N' -l "infoupd" --date 2022/04/24 --time 18:42:06
add_part_info.py -p HH203 -r A -c 'East channel has low power feed not raised' -l "infoupd" --date 2022/04/24 --time 18:42:00
add_part_info.py -p HH219 -r A -c 'door closed 25/10/2021' -l "infoupd" --date 2022/04/24 --time 18:42:00
add_part_info.py -p HH219 -r A -c 'Spectre: N18P5E' -l "infoupd" --date 2022/04/24 --time 18:42:02
add_part_info.py -p HH219 -r A -c 'Feed heights (NE/SE/SW/NW): 4.404' -l "infoupd" --date 2022/04/24 --time 18:42:04
add_part_info.py -p HH219 -r A -c 'Spectre: N18P5N' -l "infoupd" --date 2022/04/24 --time 18:42:06
add_part_info.py -p HH220 -r A -c 'door closed 25/10/2021' -l "infoupd" --date 2022/04/24 --time 18:42:00
add_part_info.py -p HH220 -r A -c 'Spectre: N18P7E' -l "infoupd" --date 2022/04/24 --time 18:42:02
add_part_info.py -p HH220 -r A -c 'Feed heights (NE/SE/SW/NW): 4.412' -l "infoupd" --date 2022/04/24 --time 18:42:04
add_part_info.py -p HH220 -r A -c 'Spectre: N18P7N' -l "infoupd" --date 2022/04/24 --time 18:42:06
add_part_info.py -p HH221 -r A -c 'door closed 25/10/2021' -l "infoupd" --date 2022/04/24 --time 18:42:00
add_part_info.py -p HH221 -r A -c 'Spectre: N18P8E' -l "infoupd" --date 2022/04/24 --time 18:42:02
add_part_info.py -p HH221 -r A -c 'Feed heights (NE/SE/SW/NW): 4.413' -l "infoupd" --date 2022/04/24 --time 18:42:04
add_part_info.py -p HH221 -r A -c 'Spectre: N18P8N' -l "infoupd" --date 2022/04/24 --time 18:42:06
add_part_info.py -p HH222 -r A -c 'door closed 25/10/2021' -l "infoupd" --date 2022/04/24 --time 18:42:00
add_part_info.py -p HH222 -r A -c 'Spectre: N18P9E' -l "infoupd" --date 2022/04/24 --time 18:42:02
add_part_info.py -p HH222 -r A -c 'Feed heights (NE/SE/SW/NW): 4.413' -l "infoupd" --date 2022/04/24 --time 18:42:04
add_part_info.py -p HH222 -r A -c 'Spectre: N18P9N' -l "infoupd" --date 2022/04/24 --time 18:42:06
add_part_info.py -p HH239 -r A -c 'door closed 25/10/2021' -l "infoupd" --date 2022/04/24 --time 18:42:00
add_part_info.py -p HH239 -r A -c 'Spectre: N18P10E' -l "infoupd" --date 2022/04/24 --time 18:42:02
add_part_info.py -p HH239 -r A -c 'Feed heights (NE/SE/SW/NW): 4.406' -l "infoupd" --date 2022/04/24 --time 18:42:04
add_part_info.py -p HH239 -r A -c 'Spectre: N18P10N' -l "infoupd" --date 2022/04/24 --time 18:42:06
add_part_info.py -p HH238 -r A -c 'door closd 25/10/2021' -l "infoupd" --date 2022/04/24 --time 18:42:00
add_part_info.py -p HH238 -r A -c 'Spectre: N18P11E' -l "infoupd" --date 2022/04/24 --time 18:42:02
add_part_info.py -p HH238 -r A -c 'Feed heights (NE/SE/SW/NW): 4.411' -l "infoupd" --date 2022/04/24 --time 18:42:04
add_part_info.py -p HH238 -r A -c 'Spectre: N18P11N' -l "infoupd" --date 2022/04/24 --time 18:42:06
add_part_info.py -p HH237 -r A -c 'door closed 25/10/2021' -l "infoupd" --date 2022/04/24 --time 18:42:00
add_part_info.py -p HH237 -r A -c 'Spectre: N18P12E' -l "infoupd" --date 2022/04/24 --time 18:42:02
add_part_info.py -p HH237 -r A -c 'Feed heights (NE/SE/SW/NW): 4.411' -l "infoupd" --date 2022/04/24 --time 18:42:04
add_part_info.py -p HH237 -r A -c 'Spectre: N18P12N' -l "infoupd" --date 2022/04/24 --time 18:42:06
add_part_info.py -p HH321 -r A -c 'Feed heights (NE/SE/SW/NW): 4.408' -l "infoupd" --date 2022/04/24 --time 18:42:00
add_part_info.py -p HH321 -r A -c 'Spectre: N2P11E' -l "infoupd" --date 2022/04/24 --time 18:42:02
add_part_info.py -p HH321 -r A -c 'Spectre: N2P11N' -l "infoupd" --date 2022/04/24 --time 18:42:04
add_part_info.py -p HH323 -r A -c 'Feed heights (NE/SE/SW/NW): 4.407' -l "infoupd" --date 2022/04/24 --time 18:42:00
add_part_info.py -p HH323 -r A -c 'Spectre: N2P12E' -l "infoupd" --date 2022/04/24 --time 18:42:02
add_part_info.py -p HH323 -r A -c 'Spectre: N2P12N' -l "infoupd" --date 2022/04/24 --time 18:42:04
add_part_info.py -p N15 -r A -c 'Snap 0 being is not working tonight -- removed from yaml' -l "infoupd" --date 2022/04/24 --time 18:42:00
