#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220506_infoupd_1142" >> scripts.log 
add_part_info.py -p HH206 -r A -c 'Spectre: N19P3E' -l "infoupd" --date 2022/05/06 --time 11:42:00
add_part_info.py -p HH206 -r A -c 'Feed heights (NE/SE/SW/NW): 4.404' -l "infoupd" --date 2022/05/06 --time 11:42:02
add_part_info.py -p HH206 -r A -c 'Spectre: N19P3N' -l "infoupd" --date 2022/05/06 --time 11:42:04
add_part_info.py -p HH243 -r A -c 'Feed heights (NE/SE/SW/NW): 4.406' -l "infoupd" --date 2022/05/06 --time 11:42:00
add_part_info.py -p HH70 -r A -c 'Feed Installed By: Installed splitter and power meter on E pol.' -l "infoupd" --date 2022/05/06 --time 11:42:00
add_part_info.py -p HH57 -r A -c 'Spectre: N4P11N' -l "infoupd" --date 2022/05/06 --time 11:42:00
add_part_info.py -p HH324 -r A -c 'Feed heights: 4.400' -l "infoupd" --date 2022/05/06 --time 11:42:00
add_part_info.py -p HH324 -r A -c 'Spectre: N4P12E' -l "infoupd" --date 2022/05/06 --time 11:42:02
add_part_info.py -p HH324 -r A -c 'Feed Installed By: https://drive.google.com/drive/folders/1bHiRKy2b-xxflyGtJwySjkze8-Pi6PNf?usp=sharing' -l "infoupd" --date 2022/05/06 --time 11:42:04
add_part_info.py -p HH324 -r A -c 'Spectre: N4P12N' -l "infoupd" --date 2022/05/06 --time 11:42:06
add_part_info.py -p HH322 -r A -c 'Feed heights (NE/SE/SW/NW): 4.403' -l "infoupd" --date 2022/05/06 --time 11:42:00
add_part_info.py -p HH322 -r A -c 'Feed Installed By: https://drive.google.com/drive/folders/1bHiRKy2b-xxflyGtJwySjkze8-Pi6PNf?usp=sharing' -l "infoupd" --date 2022/05/06 --time 11:42:02
add_part_info.py -p HH81 -r A -c 'Removed splitter/power meter on E pol.' -l "infoupd" --date 2022/05/06 --time 11:42:00
add_part_info.py -p HH325 -r A -c 'HEIGHT: 4.397' -l "infoupd" --date 2022/05/06 --time 11:42:00
add_part_info.py -p HH325 -r A -c 'SPECTRE: N9P7E' -l "infoupd" --date 2022/05/06 --time 11:42:02
add_part_info.py -p HH325 -r A -c 'SPECTRE: N9P7N' -l "infoupd" --date 2022/05/06 --time 11:42:04
add_part_info.py -p N03 -r A -c 'Ground around node 3 pitbox is opening up.' -l "infoupd" --date 2022/05/06 --time 11:42:00
add_part_info.py -p N08 -r A -c 'Reseated snap0 power to see if that was the problem.' -l "infoupd" --date 2022/05/06 --time 11:42:00
