#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220506_infoupd_1130" >> scripts.log 
add_part_info.py -p HH190 -r A -c 'Feed conduit fell out' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH204 -r A -c 'North channel low' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH205 -r A -c 'Spectre: N19P2E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH205 -r A -c 'Feed heights (NE/SE/SW/NW): 4.404' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH205 -r A -c 'Spectre: N19P2N' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p HH206 -r A -c 'Spectre: N19P3E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH206 -r A -c 'Feed heights (NE/SE/SW/NW): 4.404' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH206 -r A -c 'Spectre: N19P3N' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p HH207 -r A -c 'Spectre: N19P4E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH207 -r A -c 'Feed heights (NE/SE/SW/NW): 4.408' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH207 -r A -c 'Spectre: N19P4N' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p HH223 -r A -c 'Spectre: N19P5E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH223 -r A -c 'Feed heights (NE/SE/SW/NW): 4.405' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH223 -r A -c 'Spectre: N19P5N' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p HH224 -r A -c 'Spectre: N19P6E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH224 -r A -c 'Feed heights (NE/SE/SW/NW): 4.404' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH224 -r A -c 'Spectre: N19P6N' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p HH225 -r A -c 'Spectre: N19P7E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH225 -r A -c 'Feed heights (NE/SE/SW/NW): 4.412' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH225 -r A -c 'Spectre: N19P7N' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p HH226 -r A -c 'Spectre: N19P8E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH226 -r A -c 'Feed heights (NE/SE/SW/NW): 4.412' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH226 -r A -c 'Spectre: N19P8N' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p HH241 -r A -c 'Spectre: N19P10E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH241 -r A -c 'Feed heights (NE/SE/SW/NW): 4.405' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH241 -r A -c 'Spectre: N19P10N' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p HH242 -r A -c 'Spectre: N19P11E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH242 -r A -c 'Feed heights (NE/SE/SW/NW): 4.404' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH242 -r A -c 'Spectre: N19P11N' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p HH243 -r A -c 'Spectre: N19P12E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH243 -r A -c 'Feed heights (NE/SE/SW/NW): 4.406' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH243 -r A -c 'Spectre: N19P12N' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p HH175 -r A -c 'Feed heights (NE/SE/SW/NW): 4.402' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH195 -r A -c 'Feed heights (NE/SE/SW/NW): 4.407' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH214 -r A -c 'Feed heights (NE/SE/SW/NW): 4.409' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH212 -r A -c 'Feed heights (NE/SE/SW/NW): 4.408' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH231 -r A -c 'Feed heights (NE/SE/SW/NW): 4.403' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH232 -r A -c 'Feed heights (NE/SE/SW/NW): 4.409' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH65 -r A -c 'Spectra: N3P1E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH65 -r A -c 'Spectra: N3P1N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH66 -r A -c 'Spectra: N3P2E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH66 -r A -c 'Spectra: N3P2N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH67 -r A -c 'Spectra: N3P3E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH67 -r A -c 'Spectra: N3P3N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH68 -r A -c 'Spectra: N3P4E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH68 -r A -c 'Spectra: N3P4N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH37 -r A -c 'Spectra: N3P5E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH37 -r A -c 'Spectra: N3P5N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH38 -r A -c 'Spectra: N3P6E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH38 -r A -c 'Spectra: N3P6N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH53 -r A -c 'Spectra: N3P7E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH53 -r A -c 'Spectra: N3P7N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH320 -r A -c 'height: 4.405' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH320 -r A -c 'Spectra: N3P8E' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH320 -r A -c 'Spectra: N3P8N' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p HH51 -r A -c 'Spectra: N3P9E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH51 -r A -c 'Spectra: N3P9N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH52 -r A -c 'Feed conduit fell out.' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH52 -r A -c 'Spectra: N3P10E' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH52 -r A -c 'Spectra: N3P10N' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p HH36 -r A -c 'Spectra: N3P11E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH36 -r A -c 'Spectra: N3P11N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH50 -r A -c 'Spectra: N3P12E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH50 -r A -c 'Spectra: N3P12N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH72 -r A -c 'Spectre: N4P1E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH72 -r A -c 'Spectre: N4P1N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH42 -r A -c 'Spectre: N4P2E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH42 -r A -c 'Spectre: N4P2N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH54 -r A -c 'Spectre: N4P3E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH54 -r A -c 'Spectre: N4P3N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH56 -r A -c 'Spectre: N4P4E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH56 -r A -c 'Spectre: N4P4N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH69 -r A -c 'Spectre: N4P5E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH69 -r A -c 'Spectre: N4P5N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH40 -r A -c 'Spectre: N4P6E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH40 -r A -c 'Spectre: N4P6N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH55 -r A -c 'Spectre: N4P7E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH55 -r A -c 'Spectre: N4P7N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH71 -r A -c 'Spectre: N4P8E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH71 -r A -c 'Spectre: N4P8N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH70 -r A -c 'Spectre: N4P9E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH70 -r A -c 'Feed Installed By: Installed splitter and power meter on E pol.' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH70 -r A -c 'Spectre: N4P9N' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p HH41 -r A -c 'Spectre: N4P10E' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH41 -r A -c 'Spectre: N4P10N' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH57 -r A -c 'Feed heights: 4.407' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH57 -r A -c 'Spectre: N4P11E' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH57 -r A -c 'Spectre: N4P11N' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p HH324 -r A -c 'Feed heights: 4.400' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH324 -r A -c 'Spectre: N4P12E' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH324 -r A -c 'Feed Installed By: https://drive.google.com/drive/folders/1bHiRKy2b-xxflyGtJwySjkze8-Pi6PNf?usp=sharing' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p HH324 -r A -c 'Spectre: N4P12N' -l "infoupd" --date 2022/05/06 --time 11:30:06
add_part_info.py -p HH322 -r A -c 'Feed heights (NE/SE/SW/NW): 4.403' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH322 -r A -c 'Feed Installed By: https://drive.google.com/drive/folders/1bHiRKy2b-xxflyGtJwySjkze8-Pi6PNf?usp=sharing' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH81 -r A -c 'Removed splitter/power meter on E pol.' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH325 -r A -c 'HEIGHT: 4.397' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p HH325 -r A -c 'SPECTRE: N9P7E' -l "infoupd" --date 2022/05/06 --time 11:30:02
add_part_info.py -p HH325 -r A -c 'SPECTRE: N9P7N' -l "infoupd" --date 2022/05/06 --time 11:30:04
add_part_info.py -p N03 -r A -c 'Ground around node 3 pitbox is opening up.' -l "infoupd" --date 2022/05/06 --time 11:30:00
add_part_info.py -p N08 -r A -c 'Reseated snap0 power to see if that was the problem.' -l "infoupd" --date 2022/05/06 --time 11:30:00
