#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220523_infoupd_1545" >> scripts.log 
add_part_info.py -p HH211 -r A -c 'Spectre: N20P1E' -l "infoupd" --date 2022/05/23 --time 15:45:00
add_part_info.py -p HH211 -r A -c 'Feed heights (NE/SE/SW/NW): 4.407' -l "infoupd" --date 2022/05/23 --time 15:45:02
add_part_info.py -p HH211 -r A -c 'Spectre: N20P1N' -l "infoupd" --date 2022/05/23 --time 15:45:04
add_part_info.py -p HH244 -r A -c 'Feed heights (NE/SE/SW/NW): 4.399' -l "infoupd" --date 2022/05/23 --time 15:45:00
add_part_info.py -p HH244 -r A -c 'Spectre: N20P2N' -l "infoupd" --date 2022/05/23 --time 15:45:02
add_part_info.py -p HH245 -r A -c 'Spectre: N20P3E' -l "infoupd" --date 2022/05/23 --time 15:45:00
add_part_info.py -p HH245 -r A -c 'Feed heights (NE/SE/SW/NW): 4.404' -l "infoupd" --date 2022/05/23 --time 15:45:02
add_part_info.py -p HH245 -r A -c 'Spectre: N20P3N' -l "infoupd" --date 2022/05/23 --time 15:45:04
add_part_info.py -p HH246 -r A -c 'Spectre: N20P4E' -l "infoupd" --date 2022/05/23 --time 15:45:00
add_part_info.py -p HH246 -r A -c 'Spectre: N20P3N' -l "infoupd" --date 2022/05/23 --time 15:45:02
add_part_info.py -p HH261 -r A -c 'Spectre: N20P4E' -l "infoupd" --date 2022/05/23 --time 15:45:00
add_part_info.py -p HH261 -r A -c 'Feed heights (NE/SE/SW/NW): 4.403' -l "infoupd" --date 2022/05/23 --time 15:45:02
add_part_info.py -p HH261 -r A -c 'Spectre: N20P4N' -l "infoupd" --date 2022/05/23 --time 15:45:04
add_part_info.py -p HH228 -r A -c 'Spectre: N20P11E' -l "infoupd" --date 2022/05/23 --time 15:45:00
add_part_info.py -p HH228 -r A -c 'Feed heights (NE/SE/SW/NW): 4.403' -l "infoupd" --date 2022/05/23 --time 15:45:02
add_part_info.py -p HH228 -r A -c 'Spectre: N20P11N' -l "infoupd" --date 2022/05/23 --time 15:45:04
add_part_info.py -p HH229 -r A -c 'Spectre: N20P12E' -l "infoupd" --date 2022/05/23 --time 15:45:00
add_part_info.py -p HH229 -r A -c 'Spectre: N20P12N' -l "infoupd" --date 2022/05/23 --time 15:45:02
