#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220523_infoupd_2142" >> scripts.log 
update_apriori.py -p HH84 -s RF_maintenance --date 2022/05/23 --time 21:43
add_part_info.py -p HH84 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2022/05/23 --time 21:43
update_apriori.py -p HH87 -s RF_maintenance --date 2022/05/23 --time 21:43
add_part_info.py -p HH87 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2022/05/23 --time 21:43
update_apriori.py -p HH101 -s RF_maintenance --date 2022/05/23 --time 21:43
add_part_info.py -p HH101 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2022/05/23 --time 21:43
update_apriori.py -p HH104 -s RF_maintenance --date 2022/05/23 --time 21:43
add_part_info.py -p HH104 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2022/05/23 --time 21:43
update_apriori.py -p HH120 -s RF_maintenance --date 2022/05/23 --time 21:43
add_part_info.py -p HH120 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2022/05/23 --time 21:43
update_apriori.py -p HH122 -s RF_maintenance --date 2022/05/23 --time 21:43
add_part_info.py -p HH122 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2022/05/23 --time 21:43
