#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220523_infoupd_2242" >> scripts.log 
update_apriori.py -p HH103 -s RF_maintenance --date 2022/05/23 --time 22:43
add_part_info.py -p HH103 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2022/05/23 --time 22:43
update_apriori.py -p HH123 -s RF_maintenance --date 2022/05/23 --time 22:43
add_part_info.py -p HH123 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2022/05/23 --time 22:43
