#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220424_infoupd_1842" >> scripts.log 
add_part_info.py -p HH120 -r A -c 'Removed 3dB pad on E pol and 6 dB pad on N pol.' -l "ddb" --date 2022/05/04 --time 10:42:00
add_part_info.py -p HH120 -r A -c 'Hooked up ports 1/2 of Nimas noise generator onto E/N' -l "ddb" --date 2022/05/04 --time 10:52:00
add_part_info.py -p HH103 -r A -c 'Hooked up port 3 of Nimas noise generator onto E' -l "ddb" --date 2022/05/04 --time 10:52:00
add_part_info.py -p HH103 -r A -c 'Installed VLF-180+ onto N pol' -l "ddb" --date 2022/05/04 --time 11:02:00
add_part_info.py -p HH121 -r A -c 'Hooked up port 4 of Nimas noise generator onto E' -l "ddb" --date 2022/05/04 --time 10:52:00
add_part_info.py -p HH121 -r A -c 'Installed VLF-180+ onto N pol' -l "ddb" --date 2022/05/04 --time 11:02:00
add_part_info.py -p HH104 -r A -c 'Installed VLF-180+ onto  pol' -l "ddb" --date 2022/05/04 --time 11:02:00
add_part_info.py -p HH87 -r A -c 'Installed VLF-180+ onto both pols' -l "ddb" --date 2022/05/04 --time 11:02:00
add_part_info.py -p HH101 -r A -c 'Installed VLF-180+ onto both pols' -l "ddb" --date 2022/05/04 --time 11:02:00
add_part_info.py -p HH122 -r A -c 'Installed VLF-180+ onto both pols' -l "ddb" --date 2022/05/04 --time 11:02:00
add_part_info.py -p HH84 -r A -c 'Installed VLF-180+ onto  both pols' -l "ddb" --date 2022/05/04 --time 11:02:00
add_part_info.py -p HH123 -r A -c 'Installed VLF-180+ onto both pols' -l "ddb" --date 2022/05/04 --time 11:02:00
add_part_info.py -p HH81 -r A -c 'Hooked in signal from splitter (shared with noise meter) on E pol' -l "ddb" --date 2022/05/04 --time 11:12:00
