#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220610_connupd_1714" >> scripts.log 
# Adding missing parts
add_part.py -p PAM323 -r A -t post-amp -m PAM323 --date 2022/06/10 --time 17:09
add_part.py -p PAM322 -r A -t post-amp -m PAM322 --date 2022/06/10 --time 17:09
add_part.py -p PAM320 -r A -t post-amp -m PAM320 --date 2022/06/10 --time 17:09
add_part.py -p PAM321 -r A -t post-amp -m PAM321 --date 2022/06/10 --time 17:09
add_part.py -p PAM324 -r A -t post-amp -m PAM324 --date 2022/06/10 --time 17:09
add_part.py -p NBP22 -r A -t node-bulkhead -m NBP22 --date 2022/06/10 --time 17:09
# Adding missing connections
add_connection.py -u NBP22 --uprev A --upport e7 -d PAM214 --dnrev A --dnport e --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport n7 -d PAM214 --dnrev A --dnport n --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport e4 -d PAM323 --dnrev A --dnport e --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport n4 -d PAM323 --dnrev A --dnport n --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport e3 -d PAM322 --dnrev A --dnport e --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport n3 -d PAM322 --dnrev A --dnport n --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport e9 -d PAM190 --dnrev A --dnport e --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport n9 -d PAM190 --dnrev A --dnport n --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport e6 -d PAM148 --dnrev A --dnport e --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport n6 -d PAM148 --dnrev A --dnport n --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport e5 -d PAM324 --dnrev A --dnport e --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport n5 -d PAM324 --dnrev A --dnport n --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport e8 -d PAM123 --dnrev A --dnport e --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport n8 -d PAM123 --dnrev A --dnport n --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport e10 -d PAM207 --dnrev A --dnport e --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport n10 -d PAM207 --dnrev A --dnport n --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport e2 -d PAM321 --dnrev A --dnport e --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport n2 -d PAM321 --dnrev A --dnport n --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport e1 -d PAM320 --dnrev A --dnport e --date 2022/06/10 --time 17:14
add_connection.py -u NBP22 --uprev A --upport n1 -d PAM320 --dnrev A --dnport n --date 2022/06/10 --time 17:14
add_connection.py -u SNPC000128 --uprev A --upport rack -d N22 --dnrev A --dnport loc3 --date 2022/06/10 --time 17:14
add_connection.py -u PAM323 --uprev A --upport e -d SNPC000123 --dnrev A --dnport e2 --date 2022/06/10 --time 17:14
add_connection.py -u PAM323 --uprev A --upport n -d SNPC000123 --dnrev A --dnport n0 --date 2022/06/10 --time 17:14
add_connection.py -u SNPC000123 --uprev A --upport rack -d N22 --dnrev A --dnport loc1 --date 2022/06/10 --time 17:14
add_connection.py -u PAM322 --uprev A --upport e -d SNPC000118 --dnrev A --dnport e10 --date 2022/06/10 --time 17:14
add_connection.py -u PAM322 --uprev A --upport n -d SNPC000118 --dnrev A --dnport n8 --date 2022/06/10 --time 17:14
add_connection.py -u SNPC000118 --uprev A --upport rack -d N22 --dnrev A --dnport loc0 --date 2022/06/10 --time 17:14
add_connection.py -u PAM324 --uprev A --upport e -d SNPC000123 --dnrev A --dnport e6 --date 2022/06/10 --time 17:14
add_connection.py -u PAM324 --uprev A --upport n -d SNPC000123 --dnrev A --dnport n4 --date 2022/06/10 --time 17:14
add_connection.py -u PAM321 --uprev A --upport e -d SNPC000118 --dnrev A --dnport e6 --date 2022/06/10 --time 17:14
add_connection.py -u PAM321 --uprev A --upport n -d SNPC000118 --dnrev A --dnport n4 --date 2022/06/10 --time 17:14
add_connection.py -u PAM320 --uprev A --upport e -d SNPC000118 --dnrev A --dnport e2 --date 2022/06/10 --time 17:14
add_connection.py -u PAM320 --uprev A --upport n -d SNPC000118 --dnrev A --dnport n0 --date 2022/06/10 --time 17:14
# Adding partial connections
add_connection.py -u PAM148 --uprev A --upport e -d SNPC000123 --dnrev A --dnport e10 --date 2022/06/10 --time 17:14
add_connection.py -u PAM148 --uprev A --upport n -d SNPC000123 --dnrev A --dnport n8 --date 2022/06/10 --time 17:14
add_connection.py -u PAM207 --uprev A --upport e -d SNPC000128 --dnrev A --dnport e2 --date 2022/06/10 --time 17:14
add_connection.py -u PAM207 --uprev A --upport n -d SNPC000128 --dnrev A --dnport n0 --date 2022/06/10 --time 17:14
# Adding different connections
