#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220615_connupd_1849" >> scripts.log 
# Adding partial connections
add_connection.py -u PAM148 --uprev A --upport slot -d PCH21 --dnrev A --dnport slot6 --date 2022/06/15 --time 18:49
add_connection.py -u PAM328 --uprev A --upport slot -d PCH14 --dnrev A --dnport slot11 --date 2022/06/15 --time 18:49
# Adding different connections
stop_connection.py -u PAM214 --uprev A --upport slot -d PCH13 --dnrev A --dnport slot6 --date 2022/06/15 --time 18:47
stop_connection.py -u PAM190 --uprev A --upport slot -d PCH12 --dnrev A --dnport slot6 --date 2022/06/15 --time 18:47
add_connection.py -u PAM214 --uprev A --upport slot -d PCH21 --dnrev A --dnport slot7 --date 2022/06/15 --time 18:49
add_connection.py -u PAM190 --uprev A --upport slot -d PCH21 --dnrev A --dnport slot9 --date 2022/06/15 --time 18:49
# Adding different parts
