#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220628_infoupd_1442" >> scripts.log 
add_part_info.py -p N07 -r A -c '6/28: reinstalled pam chassis' -l "infoupd" --date 2022/06/28 --time 14:42:00
add_part_info.py -p N13 -r A -c 'swapped PAMS in positions 1 and 2 (161 and 162)' -l "infoupd" --date 2022/06/28 --time 14:42:00
