#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220604_infoupd_1442" >> scripts.log 
update_apriori.py -p HH84 -s digital_ok --date 2022/06/04 --time 14:43
add_part_info.py -p HH84 -r A -c 'apriori_antenna status change: RF_maintenance > digital_ok' -l "apa-infoupd" --date 2022/06/04 --time 14:43
update_apriori.py -p HH101 -s digital_ok --date 2022/06/04 --time 14:43
add_part_info.py -p HH101 -r A -c 'apriori_antenna status change: RF_maintenance > digital_ok' -l "apa-infoupd" --date 2022/06/04 --time 14:43
update_apriori.py -p HH103 -s digital_ok --date 2022/06/04 --time 14:43
add_part_info.py -p HH103 -r A -c 'apriori_antenna status change: RF_maintenance > digital_ok' -l "apa-infoupd" --date 2022/06/04 --time 14:43
update_apriori.py -p HH122 -s digital_ok --date 2022/06/04 --time 14:43
add_part_info.py -p HH122 -r A -c 'apriori_antenna status change: RF_maintenance > digital_ok' -l "apa-infoupd" --date 2022/06/04 --time 14:43
update_apriori.py -p HH123 -s digital_ok --date 2022/06/04 --time 14:43
add_part_info.py -p HH123 -r A -c 'apriori_antenna status change: RF_maintenance > digital_ok' -l "apa-infoupd" --date 2022/06/04 --time 14:43
