#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220713_connupd_1735" >> scripts.log 
# add parts for gsheet_not_active
add_part.py -p SNPC000073 -r A -t snap -m SNPC000073 --date 2022/06/28 --time 16:35
# add connections for gsheet_not_active
add_connection.py -u PAM062 --uprev A --upport e -d SNPC000073 --dnrev A --dnport e2 --date 2022/06/28 --time 17:35
add_connection.py -u PAM062 --uprev A --upport n -d SNPC000073 --dnrev A --dnport n0 --date 2022/06/28 --time 17:35
add_connection.py -u SNPC000073 --uprev A --upport rack -d N07 --dnrev A --dnport loc3 --date 2022/06/28 --time 17:35
add_connection.py -u PAM063 --uprev A --upport e -d SNPC000073 --dnrev A --dnport e6 --date 2022/06/28 --time 17:35
add_connection.py -u PAM063 --uprev A --upport n -d SNPC000073 --dnrev A --dnport n4 --date 2022/06/28 --time 17:35
add_connection.py -u PAM049 --uprev A --upport e -d SNPC000073 --dnrev A --dnport e10 --date 2022/06/28 --time 17:35
add_connection.py -u PAM049 --uprev A --upport n -d SNPC000073 --dnrev A --dnport n8 --date 2022/06/28 --time 17:35
# stop connections for active_not_gsheet
stop_connection.py -u PAM062 --uprev A --upport e -d SNPC000031 --dnrev A --dnport e2 --date 2022/06/28 --time 17:15
stop_connection.py -u PAM062 --uprev A --upport n -d SNPC000031 --dnrev A --dnport n0 --date 2022/06/28 --time 17:15
stop_connection.py -u PAM063 --uprev A --upport e -d SNPC000031 --dnrev A --dnport e6 --date 2022/06/28 --time 17:15
stop_connection.py -u PAM063 --uprev A --upport n -d SNPC000031 --dnrev A --dnport n4 --date 2022/06/28 --time 17:15
stop_connection.py -u PAM049 --uprev A --upport e -d SNPC000031 --dnrev A --dnport e10 --date 2022/06/28 --time 17:15
stop_connection.py -u PAM049 --uprev A --upport n -d SNPC000031 --dnrev A --dnport n8 --date 2022/06/28 --time 17:15
stop_connection.py -u SNPC000031 --uprev A --upport rack -d N07 --dnrev A --dnport loc3 --date 2022/06/28 --time 17:15
