#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220727_infoupd_1742" >> scripts.log 
update_apriori.py -p HH93 -s digital_ok --date 2022/07/27 --time 17:48
add_part_info.py -p HH93 -r A -c 'apriori_antenna status change: RF_maintenance > digital_ok' -l "apa-infoupd" --date 2022/07/27 --time 17:48
update_apriori.py -p HH130 -s digital_ok --date 2022/07/27 --time 17:48
add_part_info.py -p HH130 -r A -c 'apriori_antenna status change: digital_maintenance > digital_ok' -l "apa-infoupd" --date 2022/07/27 --time 17:48
