#! /bin/bash
echo "/Users/ddeboer/Documents/ubase/Projects/HERA/ops/hera_cm_db_updates/220705_connupd_1115" >> scripts.log 
# add parts for gsheet_not_active
add_part.py -p FDV283 -r A -t feed -m 283 --date 2022/07/05 --time 10:15
add_part.py -p FEM348 -r A -t front-end -m 348 --date 2022/07/05 --time 10:15
# add connections for gsheet_not_active
add_connection.py -u FDV283 --uprev A --upport terminals -d FEM348 --dnrev A --dnport input --date 2022/07/05 --time 11:15
add_connection.py -u A253 --uprev H --upport focus -d FDV283 --dnrev A --dnport input --date 2022/07/05 --time 11:15
add_connection.py -u FEM348 --uprev A --upport pwr -d FPS25 --dnrev A --dnport pwr3 --date 2022/07/05 --time 11:15
add_connection.py -u FEM348 --uprev A --upport e -d NBP22 --dnrev A --dnport E3 --date 2022/07/05 --time 11:15
add_connection.py -u FEM348 --uprev A --upport n -d NBP22 --dnrev A --dnport N3 --date 2022/07/05 --time 11:15
add_connection.py -u A255 --uprev H --upport focus -d FDV218 --dnrev A --dnport input --date 2022/07/05 --time 11:15

