#! /bin/bash
echo "/Users/ddeboer/Documents/ubase/Projects/HERA/ops/hera_cm_db_updates/220701_connupd_0842" >> scripts.log 
# Adding missing parts
add_part.py -p FDV218 -r A -t feed -m FDV218 --date 2022/06/30 --time 08:42
add_part.py -p FEM346 -r A -t front-end -m FEM346 --date 2022/06/30 --time 08:42
add_part.py -p FDV249 -r A -t feed -m FDV249 --date 2022/06/30 --time 08:42
add_part.py -p FEM357 -r A -t front-end -m FEM357 --date 2022/06/30 --time 08:42
add_part.py -p FEM361 -r A -t front-end -m FEM361 --date 2022/06/30 --time 08:42
add_part.py -p FEM339 -r A -t front-end -m FEM339 --date 2022/06/30 --time 08:42
add_part.py -p FEM333 -r A -t front-end -m FEM333 --date 2022/06/30 --time 08:42
add_part.py -p FEM365 -r A -t front-end -m FEM365 --date 2022/06/30 --time 08:42
add_part.py -p FDV255 -r A -t feed -m FDV255 --date 2022/06/30 --time 08:42
add_part.py -p FDV250 -r A -t feed -m FDV250 --date 2022/06/30 --time 08:42
add_part.py -p FDV264 -r A -t feed -m FDV264 --date 2022/06/30 --time 08:42
add_part.py -p FEM350 -r A -t front-end -m FEM350 --date 2022/06/30 --time 08:42
add_part.py -p FEM356 -r A -t front-end -m FEM356 --date 2022/06/30 --time 08:42
add_part.py -p FDV231 -r A -t feed -m FDV231 --date 2022/06/30 --time 08:42
add_part.py -p FEM367 -r A -t front-end -m FEM367 --date 2022/06/30 --time 08:42
add_part.py -p FDV224 -r A -t feed -m FDV224 --date 2022/06/30 --time 08:42
add_part.py -p FEM337 -r A -t front-end -m FEM337 --date 2022/06/30 --time 08:42
add_part.py -p FEM332 -r A -t front-end -m FEM332 --date 2022/06/30 --time 08:42
add_part.py -p FDV234 -r A -t feed -m FDV234 --date 2022/06/30 --time 08:42
add_part.py -p FDV260 -r A -t feed -m FDV260 --date 2022/06/30 --time 08:42
add_part.py -p FEM359 -r A -t front-end -m FEM359 --date 2022/06/30 --time 08:42
add_part.py -p FEM334 -r A -t front-end -m FEM334 --date 2022/06/30 --time 08:42
add_part.py -p FDV261 -r A -t feed -m FDV261 --date 2022/06/30 --time 08:42
add_part.py -p FEM342 -r A -t front-end -m FEM342 --date 2022/06/30 --time 08:42
add_part.py -p FDV237 -r A -t feed -m FDV237 --date 2022/06/30 --time 08:42
add_part.py -p FEM362 -r A -t front-end -m FEM362 --date 2022/06/30 --time 08:42
add_part.py -p FDV263 -r A -t feed -m FDV263 --date 2022/06/30 --time 08:42
add_part.py -p FEM340 -r A -t front-end -m FEM340 --date 2022/06/30 --time 08:42
add_part.py -p FDV346 -r A -t feed -m FDV346 --date 2022/06/30 --time 08:42
add_part.py -p FDV272 -r A -t feed -m FDV272 --date 2022/06/30 --time 08:42
add_part.py -p FDV269 -r A -t feed -m FDV269 --date 2022/06/30 --time 08:42
add_part.py -p FDV266 -r A -t feed -m FDV266 --date 2022/06/30 --time 08:42
add_part.py -p FDV238 -r A -t feed -m FDV238 --date 2022/06/30 --time 08:42
add_part.py -p FDV325 -r A -t feed -m FDV325 --date 2022/06/30 --time 08:42
add_part.py -p FEM343 -r A -t front-end -m FEM343 --date 2022/06/30 --time 08:42
add_part.py -p FDV267 -r A -t feed -m FDV267 --date 2022/06/30 --time 08:42
add_part.py -p FDV236 -r A -t feed -m FDV236 --date 2022/06/30 --time 08:42
add_part.py -p FDV217 -r A -t feed -m FDV217 --date 2022/06/30 --time 08:42
add_part.py -p FEM335 -r A -t front-end -m FEM335 --date 2022/06/30 --time 08:42
add_part.py -p FEM360 -r A -t front-end -m FEM360 --date 2022/06/30 --time 08:42
add_part.py -p FEM338 -r A -t front-end -m FEM338 --date 2022/06/30 --time 08:42
add_part.py -p FEM336 -r A -t front-end -m FEM336 --date 2022/06/30 --time 08:42
add_part.py -p FDV248 -r A -t feed -m FDV248 --date 2022/06/30 --time 08:42
add_part.py -p FEM341 -r A -t front-end -m FEM341 --date 2022/06/30 --time 08:42
# Adding missing parts
# add missing_all connections
add_connection.py -u FDV272 --uprev A --upport terminals -d FEM356 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A283 --uprev H --upport focus -d FDV272 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM356 --uprev A --upport pwr -d FPS25 --dnrev A --dnport pwr1 --date 2022/07/01 --time 08:42
add_connection.py -u FEM356 --uprev A --upport e -d NBP22 --dnrev A --dnport E1 --date 2022/07/01 --time 08:42
add_connection.py -u FEM356 --uprev A --upport n -d NBP22 --dnrev A --dnport N1 --date 2022/07/01 --time 08:42
add_connection.py -u FDV263 --uprev A --upport terminals -d FEM357 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A282 --uprev H --upport focus -d FDV263 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM357 --uprev A --upport pwr -d FPS25 --dnrev A --dnport pwr2 --date 2022/07/01 --time 08:42
add_connection.py -u FEM357 --uprev A --upport e -d NBP22 --dnrev A --dnport E2 --date 2022/07/01 --time 08:42
add_connection.py -u FEM357 --uprev A --upport n -d NBP22 --dnrev A --dnport N2 --date 2022/07/01 --time 08:42
add_connection.py -u FDV218 --uprev A --upport terminals -d FEM334 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A253 --uprev H --upport focus -d FDV218 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FDV261 --uprev A --upport terminals -d FEM360 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A252 --uprev H --upport focus -d FDV261 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM360 --uprev A --upport pwr -d FPS25 --dnrev A --dnport pwr4 --date 2022/07/01 --time 08:42
add_connection.py -u FEM360 --uprev A --upport e -d NBP22 --dnrev A --dnport E4 --date 2022/07/01 --time 08:42
add_connection.py -u FEM360 --uprev A --upport n -d NBP22 --dnrev A --dnport N4 --date 2022/07/01 --time 08:42
add_connection.py -u FDV234 --uprev A --upport terminals -d FEM346 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A268 --uprev H --upport focus -d FDV234 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM346 --uprev A --upport pwr -d FPS25 --dnrev A --dnport pwr5 --date 2022/07/01 --time 08:42
add_connection.py -u FEM346 --uprev A --upport e -d NBP22 --dnrev A --dnport E5 --date 2022/07/01 --time 08:42
add_connection.py -u FEM346 --uprev A --upport n -d NBP22 --dnrev A --dnport N5 --date 2022/07/01 --time 08:42
add_connection.py -u FDV346 --uprev A --upport terminals -d FEM359 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A267 --uprev H --upport focus -d FDV346 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM359 --uprev A --upport pwr -d FPS25 --dnrev A --dnport pwr6 --date 2022/07/01 --time 08:42
add_connection.py -u FEM359 --uprev A --upport e -d NBP22 --dnrev A --dnport E6 --date 2022/07/01 --time 08:42
add_connection.py -u FEM359 --uprev A --upport n -d NBP22 --dnrev A --dnport N6 --date 2022/07/01 --time 08:42
add_connection.py -u FDV260 --uprev A --upport terminals -d FEM350 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A250 --uprev H --upport focus -d FDV260 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM350 --uprev A --upport pwr -d FPS25 --dnrev A --dnport pwr7 --date 2022/07/01 --time 08:42
add_connection.py -u FEM350 --uprev A --upport e -d NBP22 --dnrev A --dnport E7 --date 2022/07/01 --time 08:42
add_connection.py -u FEM350 --uprev A --upport n -d NBP22 --dnrev A --dnport N7 --date 2022/07/01 --time 08:42
add_connection.py -u FDV248 --uprev A --upport terminals -d FEM365 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A269 --uprev H --upport focus -d FDV248 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM365 --uprev A --upport pwr -d FPS25 --dnrev A --dnport pwr8 --date 2022/07/01 --time 08:42
add_connection.py -u FEM365 --uprev A --upport e -d NBP22 --dnrev A --dnport E8 --date 2022/07/01 --time 08:42
add_connection.py -u FEM365 --uprev A --upport n -d NBP22 --dnrev A --dnport N8 --date 2022/07/01 --time 08:42
add_connection.py -u FDV224 --uprev A --upport terminals -d FEM361 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A266 --uprev H --upport focus -d FDV224 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM361 --uprev A --upport pwr -d FPS25 --dnrev A --dnport pwr9 --date 2022/07/01 --time 08:42
add_connection.py -u FEM361 --uprev A --upport e -d NBP22 --dnrev A --dnport E9 --date 2022/07/01 --time 08:42
add_connection.py -u FEM361 --uprev A --upport n -d NBP22 --dnrev A --dnport N9 --date 2022/07/01 --time 08:42
add_connection.py -u FDV264 --uprev A --upport terminals -d FEM367 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A281 --uprev H --upport focus -d FDV264 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM367 --uprev A --upport pwr -d FPS25 --dnrev A --dnport pwr10 --date 2022/07/01 --time 08:42
add_connection.py -u FEM367 --uprev A --upport e -d NBP22 --dnrev A --dnport E10 --date 2022/07/01 --time 08:42
add_connection.py -u FEM367 --uprev A --upport n -d NBP22 --dnrev A --dnport N10 --date 2022/07/01 --time 08:42
add_connection.py -u FDV266 --uprev A --upport terminals -d FEM362 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A251 --uprev H --upport focus -d FDV266 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM362 --uprev A --upport pwr -d FPS25 --dnrev A --dnport pwr11 --date 2022/07/01 --time 08:42
add_connection.py -u FEM362 --uprev A --upport e -d NBP22 --dnrev A --dnport E11 --date 2022/07/01 --time 08:42
add_connection.py -u FEM362 --uprev A --upport n -d NBP22 --dnrev A --dnport N11 --date 2022/07/01 --time 08:42
add_connection.py -u A295 --uprev H --upport focus -d FDV325 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM339 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr1 --date 2022/07/01 --time 08:42
add_connection.py -u FEM339 --uprev A --upport e -d NBP23 --dnrev A --dnport E1 --date 2022/07/01 --time 08:42
add_connection.py -u FEM339 --uprev A --upport n -d NBP23 --dnrev A --dnport N1 --date 2022/07/01 --time 08:42
add_connection.py -u FDV231 --uprev A --upport terminals -d FEM338 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A285 --uprev H --upport focus -d FDV231 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM338 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr2 --date 2022/07/01 --time 08:42
add_connection.py -u FEM338 --uprev A --upport e -d NBP23 --dnrev A --dnport E2 --date 2022/07/01 --time 08:42
add_connection.py -u FEM338 --uprev A --upport n -d NBP23 --dnrev A --dnport N2 --date 2022/07/01 --time 08:42
add_connection.py -u FDV236 --uprev A --upport terminals -d FEM333 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A286 --uprev H --upport focus -d FDV236 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM333 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr3 --date 2022/07/01 --time 08:42
add_connection.py -u FEM333 --uprev A --upport e -d NBP23 --dnrev A --dnport E3 --date 2022/07/01 --time 08:42
add_connection.py -u FEM333 --uprev A --upport n -d NBP23 --dnrev A --dnport N3 --date 2022/07/01 --time 08:42
add_connection.py -u FDV269 --uprev A --upport terminals -d FEM340 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A287 --uprev H --upport focus -d FDV269 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM340 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr4 --date 2022/07/01 --time 08:42
add_connection.py -u FEM340 --uprev A --upport e -d NBP23 --dnrev A --dnport E4 --date 2022/07/01 --time 08:42
add_connection.py -u FEM340 --uprev A --upport n -d NBP23 --dnrev A --dnport N4 --date 2022/07/01 --time 08:42
add_connection.py -u FDV237 --uprev A --upport terminals -d FEM335 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A270 --uprev H --upport focus -d FDV237 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM335 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr5 --date 2022/07/01 --time 08:42
add_connection.py -u FEM335 --uprev A --upport e -d NBP23 --dnrev A --dnport E5 --date 2022/07/01 --time 08:42
add_connection.py -u FEM335 --uprev A --upport n -d NBP23 --dnrev A --dnport N5 --date 2022/07/01 --time 08:42
add_connection.py -u FDV238 --uprev A --upport terminals -d FEM341 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A271 --uprev H --upport focus -d FDV238 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM341 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr6 --date 2022/07/01 --time 08:42
add_connection.py -u FEM341 --uprev A --upport e -d NBP23 --dnrev A --dnport E6 --date 2022/07/01 --time 08:42
add_connection.py -u FEM341 --uprev A --upport n -d NBP23 --dnrev A --dnport N6 --date 2022/07/01 --time 08:42
add_connection.py -u FDV217 --uprev A --upport terminals -d FEM337 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A254 --uprev H --upport focus -d FDV217 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM337 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr7 --date 2022/07/01 --time 08:42
add_connection.py -u FEM337 --uprev A --upport e -d NBP23 --dnrev A --dnport E7 --date 2022/07/01 --time 08:42
add_connection.py -u FEM337 --uprev A --upport n -d NBP23 --dnrev A --dnport N7 --date 2022/07/01 --time 08:42
add_connection.py -u FDV255 --uprev A --upport terminals -d FEM343 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A256 --uprev H --upport focus -d FDV255 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM343 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr9 --date 2022/07/01 --time 08:42
add_connection.py -u FEM343 --uprev A --upport e -d NBP23 --dnrev A --dnport E9 --date 2022/07/01 --time 08:42
add_connection.py -u FEM343 --uprev A --upport n -d NBP23 --dnrev A --dnport N9 --date 2022/07/01 --time 08:42
add_connection.py -u FDV249 --uprev A --upport terminals -d FEM336 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A272 --uprev H --upport focus -d FDV249 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM336 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr10 --date 2022/07/01 --time 08:42
add_connection.py -u FEM336 --uprev A --upport e -d NBP23 --dnrev A --dnport E10 --date 2022/07/01 --time 08:42
add_connection.py -u FEM336 --uprev A --upport n -d NBP23 --dnrev A --dnport N10 --date 2022/07/01 --time 08:42
add_connection.py -u FDV250 --uprev A --upport terminals -d FEM332 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A273 --uprev H --upport focus -d FDV250 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM332 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr11 --date 2022/07/01 --time 08:42
add_connection.py -u FEM332 --uprev A --upport e -d NBP23 --dnrev A --dnport E11 --date 2022/07/01 --time 08:42
add_connection.py -u FEM332 --uprev A --upport n -d NBP23 --dnrev A --dnport N11 --date 2022/07/01 --time 08:42
add_connection.py -u FDV267 --uprev A --upport terminals -d FEM342 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u A257 --uprev H --upport focus -d FDV267 --dnrev A --dnport input --date 2022/07/01 --time 08:42
add_connection.py -u FEM342 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr12 --date 2022/07/01 --time 08:42
add_connection.py -u FEM342 --uprev A --upport e -d NBP23 --dnrev A --dnport E12 --date 2022/07/01 --time 08:42
add_connection.py -u FEM342 --uprev A --upport n -d NBP23 --dnrev A --dnport N12 --date 2022/07/01 --time 08:42
# stop missing_all connections
stop_connection.py -u PAM322 --uprev A --upport e -d SNPC000118 --dnrev A --dnport e10 --date 2022/07/01 --time 08:42
stop_connection.py -u PAM322 --uprev A --upport n -d SNPC000118 --dnrev A --dnport n8 --date 2022/07/01 --time 08:42
stop_connection.py -u PAM322 --uprev A --upport slot -d PCH21 --dnrev A --dnport slot3 --date 2022/07/01 --time 08:42
# stop missing_ports connections
stop_connection.py -u NBP22 --uprev A --upport e3 -d PAM322 --dnrev A --dnport e --date 2022/07/01 --time 08:42
stop_connection.py -u NBP22 --uprev A --upport n3 -d PAM322 --dnrev A --dnport n --date 2022/07/01 --time 08:42
# Adding connections that differ
add_connection.py -u PAM162 --uprev A --upport slot -d PCH10 --dnrev A --dnport slot2 --date 2022/07/01 --time 08:42
add_connection.py -u PAM162 --uprev A --upport e -d SNPC000035 --dnrev A --dnport e6 --date 2022/07/01 --time 08:42
add_connection.py -u PAM162 --uprev A --upport n -d SNPC000035 --dnrev A --dnport n4 --date 2022/07/01 --time 08:42
add_connection.py -u NBP13 --uprev A --upport e1 -d PAM161 --dnrev A --dnport e --date 2022/07/01 --time 08:42
add_connection.py -u NBP13 --uprev A --upport n1 -d PAM161 --dnrev A --dnport n --date 2022/07/01 --time 08:42
add_connection.py -u NBP13 --uprev A --upport e2 -d PAM162 --dnrev A --dnport e --date 2022/07/01 --time 08:42
add_connection.py -u NBP13 --uprev A --upport n2 -d PAM162 --dnrev A --dnport n --date 2022/07/01 --time 08:42
add_connection.py -u PAM161 --uprev A --upport slot -d PCH10 --dnrev A --dnport slot1 --date 2022/07/01 --time 08:42
add_connection.py -u PAM161 --uprev A --upport e -d SNPC000035 --dnrev A --dnport e2 --date 2022/07/01 --time 08:42
add_connection.py -u PAM161 --uprev A --upport n -d SNPC000035 --dnrev A --dnport n0 --date 2022/07/01 --time 08:42
add_connection.py -u NBP22 --uprev A --upport e8 -d PAM123 --dnrev A --dnport e --date 2022/07/01 --time 08:42
add_connection.py -u NBP22 --uprev A --upport n8 -d PAM123 --dnrev A --dnport n --date 2022/07/01 --time 08:42
add_connection.py -u SNPC000124 --uprev A --upport rack -d N23 --dnrev A --dnport loc2 --date 2022/07/01 --time 08:42
# Stopping connections that differ
stop_connection.py -u PAM162 --uprev A --upport slot -d PCH10 --dnrev A --dnport slot2 --date 2022/04/02 --time 08:42
stop_connection.py -u PAM162 --uprev A --upport e -d SNPC000035 --dnrev A --dnport e6 --date 2022/04/02 --time 08:42
stop_connection.py -u PAM162 --uprev A --upport n -d SNPC000035 --dnrev A --dnport n4 --date 2022/04/02 --time 08:42
stop_connection.py -u NBP13 --uprev A --upport e1 -d PAM161 --dnrev A --dnport e --date 2022/04/02 --time 08:42
stop_connection.py -u NBP13 --uprev A --upport n1 -d PAM161 --dnrev A --dnport n --date 2022/04/02 --time 08:42
stop_connection.py -u NBP13 --uprev A --upport e2 -d PAM162 --dnrev A --dnport e --date 2022/04/02 --time 08:42
stop_connection.py -u NBP13 --uprev A --upport n2 -d PAM162 --dnrev A --dnport n --date 2022/04/02 --time 08:42
stop_connection.py -u PAM161 --uprev A --upport slot -d PCH10 --dnrev A --dnport slot1 --date 2022/04/02 --time 08:42
stop_connection.py -u PAM161 --uprev A --upport e -d SNPC000035 --dnrev A --dnport e2 --date 2022/04/02 --time 08:42
stop_connection.py -u PAM161 --uprev A --upport n -d SNPC000035 --dnrev A --dnport n0 --date 2022/04/02 --time 08:42
