#! /bin/bash
echo "/Users/ddeboer/Documents/ubase/Projects/HERA/ops/hera_cm_db_updates/220722_connupd_1507" >> scripts.log 
# add parts for gsheet_not_active
add_part.py -p FEM351 -r A -t front-end -m FEM351 --date 2022/07/21 --time 10:06
# add connections for gsheet_not_active
add_connection.py -u FDV79 --uprev A --upport terminals -d FEM351 --dnrev A --dnport input --date 2022/07/21 --time 10:08
add_connection.py -u FEM351 --uprev A --upport pwr -d FPS08 --dnrev A --dnport pwr2 --date 2022/07/21 --time 10:08
add_connection.py -u FEM351 --uprev A --upport e -d NBP10 --dnrev A --dnport E2 --date 2022/07/21 --time 10:08
add_connection.py -u FEM351 --uprev A --upport n -d NBP10 --dnrev A --dnport N2 --date 2022/07/21 --time 10:08
# stop connections for active_not_gsheet
stop_connection.py -u FEM141 --uprev A --upport pwr -d FPS08 --dnrev A --dnport pwr2 --date 2022/07/21 --time 10:07
stop_connection.py -u FEM141 --uprev A --upport e -d NBP10 --dnrev A --dnport e2 --date 2022/07/21 --time 10:07
stop_connection.py -u FEM141 --uprev A --upport n -d NBP10 --dnrev A --dnport n2 --date 2022/07/21 --time 10:07
stop_connection.py -u FDV79 --uprev A --upport terminals -d FEM141 --dnrev A --dnport input --date 2022/07/21 --time 10:07
