#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220709_connupd_0035" >> scripts.log 
# add parts for gsheet_not_active
add_part.py -p FDV213 -r A -t feed -m FDV213 --date 2022/07/08 --time 23:35
# add connections for gsheet_not_active
add_connection.py -u A152 --uprev H --upport focus -d FDV213 --dnrev A --dnport input --date 2022/07/09 --time 00:35
add_connection.py -u FDV213 --uprev A --upport terminals -d FEM276 --dnrev A --dnport input --date 2022/07/09 --time 00:35
add_connection.py -u A284 --uprev H --upport focus -d FDV230 --dnrev A --dnport input --date 2022/07/09 --time 00:35
add_connection.py -u FDV230 --uprev A --upport terminals -d FEM339 --dnrev A --dnport input --date 2022/07/09 --time 00:35
# stop connections for active_not_gsheet
stop_connection.py -u A152 --uprev H --upport focus -d FDV230 --dnrev A --dnport input --date 2022/07/09 --time 00:35
stop_connection.py -u FDV230 --uprev A --upport terminals -d FEM276 --dnrev A --dnport input --date 2022/07/09 --time 00:35
