#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220816_infoupd_1442" >> scripts.log 
add_part_info.py -p HH18 -r A -c 'RY, FY, TY, WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH27 -r A -c 'RN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH28 -r A -c 'RY,FY,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH29 -r A -c 'RY,FY,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH30 -r A -c 'RY,FB,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH6 -r A -c 'RN Cables too short' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH3 -r A -c 'RY,FY,TY,WY' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH4 -r A -c 'RY,FY,TY,WY' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH5 -r A -c 'RY,FY,TY,WN Fiber has bare spots' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH15 -r A -c 'RY, FY, TY, WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH16 -r A -c 'RY, FY, TY, WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH17 -r A -c 'RY, FY, TY, WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH7 -r A -c 'RY,FB,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH8 -r A -c 'RY,FB,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH9 -r A -c 'RY,FB,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH19 -r A -c 'RY,FB,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH20 -r A -c 'RY,FB,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH21 -r A -c 'RY,FB,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH31 -r A -c 'RY,FB,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH32 -r A -c 'RY,FB,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH33 -r A -c 'RY,FB,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH37 -r A -c 'RY,F?,TY,WY' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH38 -r A -c 'RY,F?,TY,WY' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH53 -r A -c 'RY,F?,TY,WY - RJ45 tilted' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH51 -r A -c 'RY,F?,TY,WY' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH52 -r A -c 'RY,F?,TY,WN Conduit on hub' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH36 -r A -c 'RY,FY,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH50 -r A -c 'RY,FY,TY,WN Conduit on hub' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH42 -r A -c 'RY,FY,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH54 -r A -c 'RY,FY,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH56 -r A -c 'RY,FY,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH40 -r A -c 'RY,FY,TY,WN  Cladding out' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH55 -r A -c 'RY,FY,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH41 -r A -c 'RY,FY,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH57 -r A -c 'RY,F?,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH45 -r A -c 'RN,F?,TY,W?' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH46 -r A -c 'RY,FY,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH59 -r A -c 'RY,FY,TY,WN Conduit on hub' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH58 -r A -c 'RY,FY,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH44 -r A -c 'RY,FY,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH60 -r A -c 'RY,FY,TY,WN Conduit on hub' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH43 -r A -c 'RY,FY,TY,WN' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH22 -r A -c 'History: RY,FB,TY,WY Conduit 1 ft below feed' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH34 -r A -c 'History: RY,FB,TY,WY' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH35 -r A -c 'History: RY,FB,TY,WY' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH47 -r A -c 'History: RY,FB,TY,WY' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH61 -r A -c 'History: RY,FB,TY,WY' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH48 -r A -c 'History: RY,FB,TY,WY' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH49 -r A -c 'History: RY,FB,TY,WY' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH62 -r A -c 'History: RY,FB,TY,WY' -l "infoupd" --date 2022/08/16 --time 14:42:00
add_part_info.py -p HH63 -r A -c 'History: RY,FB,TY,WY' -l "infoupd" --date 2022/08/16 --time 14:42:00
