#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220810_infoupd_1842" >> scripts.log 
update_apriori.py -p HH38 -s digital_ok --date 2022/08/10 --time 18:48
add_part_info.py -p HH38 -r A -c 'apriori_antenna status change: RF_maintenance > digital_ok' -l "apa-infoupd" --date 2022/08/10 --time 18:48
update_apriori.py -p HH50 -s RF_maintenance --date 2022/08/10 --time 18:48
add_part_info.py -p HH50 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2022/08/10 --time 18:48
update_apriori.py -p HH57 -s RF_maintenance --date 2022/08/10 --time 18:48
add_part_info.py -p HH57 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2022/08/10 --time 18:48
update_apriori.py -p HH67 -s digital_ok --date 2022/08/10 --time 18:48
add_part_info.py -p HH67 -r A -c 'apriori_antenna status change: RF_maintenance > digital_ok' -l "apa-infoupd" --date 2022/08/10 --time 18:48
update_apriori.py -p HH145 -s RF_maintenance --date 2022/08/10 --time 18:48
add_part_info.py -p HH145 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2022/08/10 --time 18:48
