#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220805_infoupd_2142" >> scripts.log 
update_apriori.py -p HH85 -s digital_ok --date 2022/08/05 --time 21:48
add_part_info.py -p HH85 -r A -c 'apriori_antenna status change: RF_maintenance > digital_ok' -l "apa-infoupd" --date 2022/08/05 --time 21:48
update_apriori.py -p HH86 -s digital_ok --date 2022/08/05 --time 21:48
add_part_info.py -p HH86 -r A -c 'apriori_antenna status change: RF_maintenance > digital_ok' -l "apa-infoupd" --date 2022/08/05 --time 21:48
