#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220930_infoupd_0842" >> scripts.log 
add_part_info.py -p HH177 -r A -c "H6C: Feed Height Before: 4.399Sticker Targets: InstalledStiffener Braces: Present AlreadyCarey Caps: Present AlreadyProtected Fiber: InstalledCable Conduit: InstalledSpiral Wrap: InstalledD Shackle Cable Tie: InstalledCables Labelled: Completed" -l "infoupd" --date 2022/09/30 --time 08:42:00
add_part_info.py -p HH135 -r A -c "Feed heights (NE/SE/SW/NW): 4.403" -l "infoupd" --date 2022/09/30 --time 08:42:00
add_part_info.py -p HH135 -r A -c "H6C: Feed Height Before: 4.401Sticker Targets: InstalledStiffener Braces: Present AlreadyCarey Caps: Present AlreadyProtected Fiber: InstalledCable Conduit: Already PresentSpiral Wrap: Already PresentD Shackle Cable Tie: InstalledCables Labelled: Completed" -l "infoupd" --date 2022/09/30 --time 08:42:02
add_part_info.py -p HH136 -r A -c "Feed heights (NE/SE/SW/NW): 4.405" -l "infoupd" --date 2022/09/30 --time 08:42:00
add_part_info.py -p HH136 -r A -c "H6C: Feed Height Before: 4.403Sticker Targets: Prsent AlreadyStiffener Braces: Present AlreadyCarey Caps: Present AlreadyProtected Fiber: InstalledCable Conduit: Already PresentSpiral Wrap: InstalledD Shackle Cable Tie: InstalledCables Labelled: Already Present" -l "infoupd" --date 2022/09/30 --time 08:42:02
add_part_info.py -p HH155 -r A -c "Feed heights (NE/SE/SW/NW): 4.411" -l "infoupd" --date 2022/09/30 --time 08:42:00
add_part_info.py -p HH155 -r A -c "H6C: Feed Height Before: 4.409Sticker Targets: InstalledStiffener Braces: Present AlreadyCarey Caps: Present AlreadyProtected Fiber: InstalledCable Conduit: Already PresentSpiral Wrap: Already presentD Shackle Cable Tie: InstalledCables Labelled: Completed" -l "infoupd" --date 2022/09/30 --time 08:42:02
add_part_info.py -p HH156 -r A -c "Feed heights (NE/SE/SW/NW): 4.405" -l "infoupd" --date 2022/09/30 --time 08:42:00
add_part_info.py -p HH156 -r A -c "H6C: Feed Height Before: 4.407Sticker Targets: InstalledStiffener Braces: Present AlreadyCarey Caps: Present AlreadyProtected Fiber: InstalledCable Conduit: Already PresentSpiral Wrap: InstalledD Shackle Cable Tie: InstalledCables Labelled: Completed" -l "infoupd" --date 2022/09/30 --time 08:42:02
add_part_info.py -p HH157 -r A -c "Feed heights (NE/SE/SW/NW): 4.406" -l "infoupd" --date 2022/09/30 --time 08:42:00
add_part_info.py -p HH157 -r A -c "H6C: Feed Height Before: 4.399Sticker Targets: InstalledStiffener Braces: Present AlreadyCarey Caps: Present AlreadyProtected Fiber: InstalledCable Conduit: Already PresentSpiral Wrap: InstalledD Shackle Cable Tie: InstalledCables Labelled: Completed" -l "infoupd" --date 2022/09/30 --time 08:42:02
