#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220922_connupd_1450" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u RD31 --uprev A --upport mnt -d NCMP2 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD46 --uprev A --upport mnt -d NCM02 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD20 --uprev A --upport mnt -d NCM06 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD43 --uprev A --upport mnt -d NCM10 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD18 --uprev A --upport mnt -d NCM13 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD04 --uprev A --upport mnt -d NCM15 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD42 --uprev A --upport mnt -d NCM03 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD15 --uprev A --upport mnt -d NCM07 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD11 --uprev A --upport mnt -d NCM11 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD41 --uprev A --upport mnt -d NCM04 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD45 --uprev A --upport mnt -d NCM01 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD07 --uprev A --upport mnt -d NCM16 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD06 --uprev A --upport mnt -d NCM05 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD19 --uprev A --upport mnt -d NCM08 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD40 --uprev A --upport mnt -d NCM09 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD14 --uprev A --upport mnt -d NCM20 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD16 --uprev A --upport mnt -d NCM18 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD47 --uprev A --upport mnt -d NCM17 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD48 --uprev A --upport mnt -d NCM19 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
stop_connection.py -u RD02 --uprev A --upport mnt -d NCMP1 --dnrev A --dnport mnt2 --date 2022/09/22 --time 14:44
# add parts for gsheet_not_active
add_part.py -p PAM025 -r A -t post-amp -m PAM025 --date 2022/09/22 --time 14:20
add_part.py -p PAM041 -r A -t post-amp -m PAM041 --date 2022/09/22 --time 14:20
add_part.py -p PAM039 -r A -t post-amp -m PAM039 --date 2022/09/22 --time 14:20
add_part.py -p PAM062 -r A -t post-amp -m PAM062 --date 2022/09/22 --time 14:20
# add connections for gsheet_not_active
add_connection.py -u PAM013 --uprev A --upport slot -d PCH16 --dnrev A --dnport slot1 --date 2022/09/22 --time 14:50
add_connection.py -u PAM013 --uprev A --upport e -d SNPC000078 --dnrev A --dnport e2 --date 2022/09/22 --time 14:50
add_connection.py -u PAM013 --uprev A --upport n -d SNPC000078 --dnrev A --dnport n0 --date 2022/09/22 --time 14:50
add_connection.py -u NBP19 --uprev A --upport E1 -d PAM013 --dnrev A --dnport e --date 2022/09/22 --time 14:50
add_connection.py -u NBP19 --uprev A --upport N1 -d PAM013 --dnrev A --dnport n --date 2022/09/22 --time 14:50
add_connection.py -u NBP20 --uprev A --upport E6 -d PAM039 --dnrev A --dnport e --date 2022/09/22 --time 14:50
add_connection.py -u NBP20 --uprev A --upport N6 -d PAM039 --dnrev A --dnport n --date 2022/09/22 --time 14:50
add_connection.py -u NBP20 --uprev A --upport E7 -d PAM041 --dnrev A --dnport e --date 2022/09/22 --time 14:50
add_connection.py -u NBP20 --uprev A --upport N7 -d PAM041 --dnrev A --dnport n --date 2022/09/22 --time 14:50
add_connection.py -u NBP20 --uprev A --upport E8 -d PAM016 --dnrev A --dnport e --date 2022/09/22 --time 14:50
add_connection.py -u NBP20 --uprev A --upport N8 -d PAM016 --dnrev A --dnport n --date 2022/09/22 --time 14:50
add_connection.py -u NBP20 --uprev A --upport E9 -d PAM025 --dnrev A --dnport e --date 2022/09/22 --time 14:50
add_connection.py -u NBP20 --uprev A --upport N9 -d PAM025 --dnrev A --dnport n --date 2022/09/22 --time 14:50
add_connection.py -u PAM039 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot6 --date 2022/09/22 --time 14:50
add_connection.py -u PAM039 --uprev A --upport e -d SNPC000082 --dnrev A --dnport e10 --date 2022/09/22 --time 14:50
add_connection.py -u PAM039 --uprev A --upport n -d SNPC000082 --dnrev A --dnport n8 --date 2022/09/22 --time 14:50
add_connection.py -u PAM041 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot7 --date 2022/09/22 --time 14:50
add_connection.py -u PAM041 --uprev A --upport e -d SNPC000085 --dnrev A --dnport e2 --date 2022/09/22 --time 14:50
add_connection.py -u PAM041 --uprev A --upport n -d SNPC000085 --dnrev A --dnport n0 --date 2022/09/22 --time 14:50
add_connection.py -u PAM016 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot8 --date 2022/09/22 --time 14:50
add_connection.py -u PAM016 --uprev A --upport e -d SNPC000085 --dnrev A --dnport e6 --date 2022/09/22 --time 14:50
add_connection.py -u PAM016 --uprev A --upport n -d SNPC000085 --dnrev A --dnport n4 --date 2022/09/22 --time 14:50
add_connection.py -u PAM025 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot9 --date 2022/09/22 --time 14:50
add_connection.py -u PAM025 --uprev A --upport e -d SNPC000085 --dnrev A --dnport e10 --date 2022/09/22 --time 14:50
add_connection.py -u PAM025 --uprev A --upport n -d SNPC000085 --dnrev A --dnport n8 --date 2022/09/22 --time 14:50
add_connection.py -u NBP22 --uprev A --upport E9 -d PAM010 --dnrev A --dnport e --date 2022/09/22 --time 14:50
add_connection.py -u NBP22 --uprev A --upport N9 -d PAM010 --dnrev A --dnport n --date 2022/09/22 --time 14:50
add_connection.py -u NBP22 --uprev A --upport E11 -d PAM062 --dnrev A --dnport e --date 2022/09/22 --time 14:50
add_connection.py -u NBP22 --uprev A --upport N11 -d PAM062 --dnrev A --dnport n --date 2022/09/22 --time 14:50
add_connection.py -u NBP22 --uprev A --upport E12 -d PAM019 --dnrev A --dnport e --date 2022/09/22 --time 14:50
add_connection.py -u NBP22 --uprev A --upport N12 -d PAM019 --dnrev A --dnport n --date 2022/09/22 --time 14:50
add_connection.py -u PAM010 --uprev A --upport slot -d PCH21 --dnrev A --dnport slot9 --date 2022/09/22 --time 14:50
add_connection.py -u PAM010 --uprev A --upport e -d SNPC000126 --dnrev A --dnport e10 --date 2022/09/22 --time 14:50
add_connection.py -u PAM010 --uprev A --upport n -d SNPC000126 --dnrev A --dnport n8 --date 2022/09/22 --time 14:50
add_connection.py -u PAM062 --uprev A --upport slot -d PCH21 --dnrev A --dnport slot11 --date 2022/09/22 --time 14:50
add_connection.py -u PAM062 --uprev A --upport e -d SNPC000128 --dnrev A --dnport e6 --date 2022/09/22 --time 14:50
add_connection.py -u PAM062 --uprev A --upport n -d SNPC000128 --dnrev A --dnport n4 --date 2022/09/22 --time 14:50
add_connection.py -u PAM019 --uprev A --upport slot -d PCH21 --dnrev A --dnport slot12 --date 2022/09/22 --time 14:50
add_connection.py -u PAM019 --uprev A --upport e -d SNPC000128 --dnrev A --dnport e10 --date 2022/09/22 --time 14:50
add_connection.py -u PAM019 --uprev A --upport n -d SNPC000128 --dnrev A --dnport n8 --date 2022/09/22 --time 14:50
