#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220929_infoupd_1342" >> scripts.log 
add_part_info.py -p HH176 -r A -c "Feed heights (NE/SE/SW/NW): 4.411" -l "infoupd" --date 2022/09/29 --time 13:42:00
add_part_info.py -p HH176 -r A -c "H6C: Feed Height Before: 4.410Sticker Targets: InstalledStiffener Braces: Present AlreadyCarey Caps: Present AlreadyProtected Fiber: InstalledCable Conduit: Already PresentSpiral Wrap: InstalledD Shackle Cable Tie: InstalledCables Labelled: Completed" -l "infoupd" --date 2022/09/29 --time 13:42:02
