#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220918_infoupd_1142" >> scripts.log 
add_part_info.py -p N16 -r A -c 'PAMs removed for retrofit.' -l "infoupd" --date 2022/09/18 --time 11:42:00
add_part_info.py -p N18 -r A -c 'PAMs removed for retrofit.' -l "infoupd" --date 2022/09/18 --time 11:42:00
add_part_info.py -p N18 -r A -c 'Original NCM returned' -l "infoupd" --date 2022/09/18 --time 11:42:02
add_part_info.py -p N19 -r A -c 'PAMs removed for retrofit.' -l "infoupd" --date 2022/09/18 --time 11:42:00
add_part_info.py -p N20 -r A -c 'PAMs removed for retrofit.' -l "infoupd" --date 2022/09/18 --time 11:42:00
add_part_info.py -p N21 -r A -c 'NCM removed for update.' -l "infoupd" --date 2022/09/18 --time 11:42:00
