#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221004_connupd_1335" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u FEM167 --uprev A --upport pwr -d FPS11 --dnrev A --dnport pwr11 --date 2022/10/04 --time 13:29
stop_connection.py -u FEM167 --uprev A --upport e -d NBP13 --dnrev A --dnport e11 --date 2022/10/04 --time 13:29
stop_connection.py -u FEM167 --uprev A --upport n -d NBP13 --dnrev A --dnport n11 --date 2022/10/04 --time 13:29
stop_connection.py -u FDV119 --uprev A --upport terminals -d FEM167 --dnrev A --dnport input --date 2022/10/04 --time 13:29
# add parts for gsheet_not_active
add_part.py -p FEM176 -r A -t front-end -m FEM176 --date 2022/10/04 --time 13:05
# add connections for gsheet_not_active
add_connection.py -u FDV119 --uprev A --upport terminals -d FEM176 --dnrev A --dnport input --date 2022/10/04 --time 13:35
add_connection.py -u FEM176 --uprev A --upport pwr -d FPS11 --dnrev A --dnport pwr11 --date 2022/10/04 --time 13:35
add_connection.py -u FEM176 --uprev A --upport e -d NBP13 --dnrev A --dnport E11 --date 2022/10/04 --time 13:35
add_connection.py -u FEM176 --uprev A --upport n -d NBP13 --dnrev A --dnport N11 --date 2022/10/04 --time 13:35
