#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221012_infoupd_1342" >> scripts.log 
add_part_info.py -p HH166 -r A -c "Feed Heights: 4.408" -l "infoupd" --date 2022/10/12 --time 13:42:00
add_part_info.py -p HH166 -r A -c "H6C: Feed Height Before: 4.398 Sticker Targets: Already Present Stiffener Braces: Installed Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2022/10/12 --time 13:42:02
add_part_info.py -p HH186 -r A -c "Feed Heights: 4.400" -l "infoupd" --date 2022/10/12 --time 13:42:00
add_part_info.py -p HH186 -r A -c "H6C: Feed Height Before: 4.400 Sticker Targets: Present Already Stiffener Braces: Installed Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2022/10/12 --time 13:42:02
add_part_info.py -p HH187 -r A -c "Feed Heights: 4.405" -l "infoupd" --date 2022/10/12 --time 13:42:00
add_part_info.py -p HH187 -r A -c "H6C: Feed Height Before: 4.399 Sticker Targets: Present Already Stiffener Braces: Installed Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Present Already Cables Labelled: Completed" -l "infoupd" --date 2022/10/12 --time 13:42:02
add_part_info.py -p HH168 -r A -c "Feed heights (NE/SE/SW/NW): 4.400" -l "infoupd" --date 2022/10/12 --time 13:42:00
add_part_info.py -p HH168 -r A -c "H6C: Feed Height Before: 4.406 Sticker Targets: Already Present Stiffener Braces: Installed Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2022/10/12 --time 13:42:02
add_part_info.py -p HH169 -r A -c "Feed heights (NE/SE/SW/NW): 4.400" -l "infoupd" --date 2022/10/12 --time 13:42:00
add_part_info.py -p HH169 -r A -c "H6C: Feed Height Before: 4.408 Sticker Targets: Already Present Stiffener Braces: Installed Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2022/10/12 --time 13:42:02
