#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221004_connupd_1653" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u A70 --uprev H --upport focus -d FDV55 --dnrev A --dnport input --date 2022/10/04 --time 16:47
stop_connection.py -u A71 --uprev H --upport focus -d FDV63 --dnrev A --dnport input --date 2022/10/04 --time 16:47
# add connections for gsheet_not_active
add_connection.py -u A70 --uprev H --upport focus -d FDV63 --dnrev A --dnport input --date 2022/10/04 --time 16:53
add_connection.py -u A71 --uprev H --upport focus -d FDV55 --dnrev A --dnport input --date 2022/10/04 --time 16:53
