#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221018_infoupd_0842" >> scripts.log 
add_part_info.py -p HH139 -r A -c "Feed heights (NE/SE/SW/NW): 4.408" -l "infoupd" --date 2022/10/18 --time 08:42:00
add_part_info.py -p HH139 -r A -c "H6C: Feed Height Before: New Connection Sticker Targets: Installed Stiffener Braces: Installed Carey Caps: Installed Protected Fiber: Installed Cable Conduit: Installed Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2022/10/18 --time 08:42:02
add_part_info.py -p HH159 -r A -c "FEM Switch error -DCJ" -l "infoupd" --date 2022/10/18 --time 08:42:00
add_part_info.py -p HH159 -r A -c "Feed heights (NE/SE/SW/NW): 4.410" -l "infoupd" --date 2022/10/18 --time 08:42:02
add_part_info.py -p HH159 -r A -c "H6C: Feed Height Before: New Connection Sticker Targets: Installed Stiffener Braces: Installed Carey Caps: Installed Protected Fiber: Installed Cable Conduit: Installed Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2022/10/18 --time 08:42:04
add_part_info.py -p HH146 -r A -c "Feed Heights: 4.406" -l "infoupd" --date 2022/10/18 --time 08:42:00
add_part_info.py -p HH146 -r A -c "H6C: Feed Height Before: New Connection Sticker Targets: Installed Stiffener Braces: Installed Carey Caps: Installed Protected Fiber: Installed Cable Conduit: Installed Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2022/10/18 --time 08:42:02
