#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221012_infoupd_1442" >> scripts.log 
add_part_info.py -p HH145 -r A -c "H6C: Feed Height Before: 4.399 Sticker Targets: Already Present Stiffener Braces: Already Present Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2022/10/12 --time 14:42:00
add_part_info.py -p HH148 -r A -c "Feed heights (NE/SE/SW/NW): 4.398" -l "infoupd" --date 2022/10/12 --time 14:42:00
add_part_info.py -p HH148 -r A -c "H6C: Feed Height Before: 4.397 Sticker Targets: Already Present Stiffener Braces: Installed Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2022/10/12 --time 14:42:02
