#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221022_infoupd_2042" >> scripts.log 
update_apriori.py -p HH44 -s digital_ok --date 2022/10/22 --time 20:48
add_part_info.py -p HH44 -r A -c "apriori_antenna status change: digital_maintenance > digital_ok" -l "apa-infoupd" --date 2022/10/22 --time 20:48
update_apriori.py -p HH59 -s digital_ok --date 2022/10/22 --time 20:48
add_part_info.py -p HH59 -r A -c "apriori_antenna status change: digital_maintenance > digital_ok" -l "apa-infoupd" --date 2022/10/22 --time 20:48
update_apriori.py -p HH74 -s RF_maintenance --date 2022/10/22 --time 20:48
add_part_info.py -p HH74 -r A -c "apriori_antenna status change: digital_maintenance > RF_maintenance" -l "apa-infoupd" --date 2022/10/22 --time 20:48
update_apriori.py -p HH135 -s RF_maintenance --date 2022/10/22 --time 20:48
add_part_info.py -p HH135 -r A -c "apriori_antenna status change: digital_maintenance > RF_maintenance" -l "apa-infoupd" --date 2022/10/22 --time 20:48
update_apriori.py -p HH136 -s digital_ok --date 2022/10/22 --time 20:48
add_part_info.py -p HH136 -r A -c "apriori_antenna status change: digital_maintenance > digital_ok" -l "apa-infoupd" --date 2022/10/22 --time 20:48
update_apriori.py -p HH201 -s RF_maintenance --date 2022/10/22 --time 20:48
add_part_info.py -p HH201 -r A -c "apriori_antenna status change: RF_ok > RF_maintenance" -l "apa-infoupd" --date 2022/10/22 --time 20:48
update_apriori.py -p HH202 -s digital_ok --date 2022/10/22 --time 20:48
add_part_info.py -p HH202 -r A -c "apriori_antenna status change: RF_ok > digital_ok" -l "apa-infoupd" --date 2022/10/22 --time 20:48
update_apriori.py -p HH219 -s RF_maintenance --date 2022/10/22 --time 20:48
add_part_info.py -p HH219 -r A -c "apriori_antenna status change: RF_ok > RF_maintenance" -l "apa-infoupd" --date 2022/10/22 --time 20:48
update_apriori.py -p HH220 -s RF_maintenance --date 2022/10/22 --time 20:48
add_part_info.py -p HH220 -r A -c "apriori_antenna status change: RF_ok > RF_maintenance" -l "apa-infoupd" --date 2022/10/22 --time 20:48
add_part_info.py -p HH179 -r A -c "H6Ccheck: no-sky power after fem 301 Reported in issue 780. -DCJ" -l "infoupd" --date 2022/10/22 --time 20:42:00
add_part_info.py -p HH135 -r A -c "H6Ccheck: No sky in N -DCJ" -l "apa-infoupd" --date 2022/10/22 --time 20:42:00
add_part_info.py -p HH135 -r A -c "H6Ccheck: looks ok -dcj" -l "apa-infoupd" --date 2022/10/22 --time 20:42:02
add_part_info.py -p HH200 -r A -c "one bad pol, one too high! -DCJ" -l "infoupd" --date 2022/10/22 --time 20:42:00
add_part_info.py -p HH201 -r A -c "power too high -DCJ" -l "apa-infoupd" --date 2022/10/22 --time 20:42:00
add_part_info.py -p HH203 -r A -c "power too low, no sky -DCJ" -l "infoupd" --date 2022/10/22 --time 20:42:00
add_part_info.py -p HH219 -r A -c "power too high -DCJ" -l "apa-infoupd" --date 2022/10/22 --time 20:42:00
add_part_info.py -p HH220 -r A -c "power too high -DCJ" -l "apa-infoupd" --date 2022/10/22 --time 20:42:00
add_part_info.py -p HH59 -r A -c "no evidence of digital issue -DCJ" -l "apa-infoupd" --date 2022/10/22 --time 20:42:00
add_part_info.py -p HH44 -r A -c "spectra a little odd, but no evidence of digital issue -DCJ" -l "apa-infoupd" --date 2022/10/22 --time 20:42:00
