#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221024_infoupd_1442" >> scripts.log 
add_part_info.py -p HH147 -r A -c "Feed heights (NE/SE/SW/NW): 4.408" -l "infoupd" --date 2022/10/24 --time 14:42:00
add_part_info.py -p HH147 -r A -c "H6C: Feed Height Before: 4.409 Sticker Targets: Already Present Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2022/10/24 --time 14:42:02
add_part_info.py -p HH84 -r A -c "FEM 54 replaced with 305" -l "infoupd" --date 2022/10/24 --time 14:42:00
add_part_info.py -p HH84 -r A -c "Feed heights (NE/SE/SW/NW): 4.407" -l "infoupd" --date 2022/10/24 --time 14:42:02
add_part_info.py -p HH84 -r A -c "H6C: Feed Height Before: 4.399 Sticker Targets: Present Already Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2022/10/24 --time 14:42:04
