#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221107_connupd_1535" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u FDV35 --uprev A --upport terminals -d FEM305 --dnrev A --dnport input --date 2022/11/07 --time 15:29
stop_connection.py -u FEM305 --uprev A --upport pwr -d FPS04 --dnrev A --dnport pwr10 --date 2022/11/07 --time 15:29
stop_connection.py -u FEM305 --uprev A --upport e -d NBP08 --dnrev A --dnport E10 --date 2022/11/07 --time 15:29
stop_connection.py -u FEM305 --uprev A --upport n -d NBP08 --dnrev A --dnport N10 --date 2022/11/07 --time 15:29
# add parts for gsheet_not_active
add_part.py -p FEM376 -r A -t front-end -m FEM376 --date 2022/11/07 --time 15:05
# add connections for gsheet_not_active
add_connection.py -u FDV35 --uprev A --upport terminals -d FEM376 --dnrev A --dnport input --date 2022/11/07 --time 15:35
add_connection.py -u FEM376 --uprev A --upport pwr -d FPS04 --dnrev A --dnport pwr10 --date 2022/11/07 --time 15:35
add_connection.py -u FEM376 --uprev A --upport e -d NBP08 --dnrev A --dnport E10 --date 2022/11/07 --time 15:35
add_connection.py -u FEM376 --uprev A --upport n -d NBP08 --dnrev A --dnport N10 --date 2022/11/07 --time 15:35
