#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221117_infoupd_1942" >> scripts.log 
update_apriori.py -p HH155 -s digital_ok --date 2022/11/17 --time 19:48
add_part_info.py -p HH155 -r A -c "apriori_antenna status change: RF_maintenance > digital_ok" -l "apa-infoupd" --date 2022/11/17 --time 19:48
