#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221129_connupd_1735" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u NBP14 --uprev A --upport e3 -d PAM175 --dnrev A --dnport e --date 2022/11/29 --time 17:29
stop_connection.py -u NBP14 --uprev A --upport n3 -d PAM175 --dnrev A --dnport n --date 2022/11/29 --time 17:29
stop_connection.py -u NBP14 --uprev A --upport e5 -d PAM177 --dnrev A --dnport e --date 2022/11/29 --time 17:29
stop_connection.py -u NBP14 --uprev A --upport n5 -d PAM177 --dnrev A --dnport n --date 2022/11/29 --time 17:29
stop_connection.py -u FEM184 --uprev A --upport e -d NBP14 --dnrev A --dnport e5 --date 2022/11/29 --time 17:29
stop_connection.py -u FEM184 --uprev A --upport n -d NBP14 --dnrev A --dnport n5 --date 2022/11/29 --time 17:29
stop_connection.py -u FEM184 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr5 --date 2022/11/29 --time 17:29
stop_connection.py -u PAM175 --uprev A --upport slot -d PCH11 --dnrev A --dnport slot3 --date 2022/11/29 --time 17:29
stop_connection.py -u PAM177 --uprev A --upport slot -d PCH11 --dnrev A --dnport slot5 --date 2022/11/29 --time 17:29
stop_connection.py -u FEM369 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr3 --date 2022/11/29 --time 17:29
stop_connection.py -u FEM369 --uprev A --upport e -d NBP14 --dnrev A --dnport E3 --date 2022/11/29 --time 17:29
stop_connection.py -u FEM369 --uprev A --upport n -d NBP14 --dnrev A --dnport N3 --date 2022/11/29 --time 17:29
# add connections for gsheet_not_active
add_connection.py -u NBP14 --uprev A --upport E5 -d PAM175 --dnrev A --dnport e --date 2022/11/29 --time 17:35
add_connection.py -u NBP14 --uprev A --upport N5 -d PAM175 --dnrev A --dnport n --date 2022/11/29 --time 17:35
add_connection.py -u NBP14 --uprev A --upport E3 -d PAM177 --dnrev A --dnport e --date 2022/11/29 --time 17:35
add_connection.py -u NBP14 --uprev A --upport N3 -d PAM177 --dnrev A --dnport n --date 2022/11/29 --time 17:35
add_connection.py -u FEM369 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr5 --date 2022/11/29 --time 17:35
add_connection.py -u FEM369 --uprev A --upport e -d NBP14 --dnrev A --dnport E5 --date 2022/11/29 --time 17:35
add_connection.py -u FEM369 --uprev A --upport n -d NBP14 --dnrev A --dnport N5 --date 2022/11/29 --time 17:35
add_connection.py -u PAM175 --uprev A --upport slot -d PCH11 --dnrev A --dnport slot5 --date 2022/11/29 --time 17:35
add_connection.py -u FEM184 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr3 --date 2022/11/29 --time 17:35
add_connection.py -u FEM184 --uprev A --upport e -d NBP14 --dnrev A --dnport E3 --date 2022/11/29 --time 17:35
add_connection.py -u FEM184 --uprev A --upport n -d NBP14 --dnrev A --dnport N3 --date 2022/11/29 --time 17:35
add_connection.py -u PAM177 --uprev A --upport slot -d PCH11 --dnrev A --dnport slot3 --date 2022/11/29 --time 17:35
