#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221101_connupd_1651" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u A186 --uprev H --upport focus -d FDV112 --dnrev A --dnport input --date 2022/11/01 --time 16:45
stop_connection.py -u FEM163 --uprev A --upport pwr -d FPS10 --dnrev A --dnport pwr10 --date 2022/11/01 --time 16:45
stop_connection.py -u FEM163 --uprev A --upport e -d NBP12 --dnrev A --dnport e10 --date 2022/11/01 --time 16:45
stop_connection.py -u FEM163 --uprev A --upport n -d NBP12 --dnrev A --dnport n10 --date 2022/11/01 --time 16:45
stop_connection.py -u FDV98 --uprev A --upport terminals -d FEM163 --dnrev A --dnport input --date 2022/11/01 --time 16:45
stop_connection.py -u A185 --uprev H --upport focus -d FDV125 --dnrev A --dnport input --date 2022/11/01 --time 16:45
# add parts for gsheet_not_active
add_part.py -p FEM155 -r A -t front-end -m FEM155 --date 2022/11/01 --time 16:21
# add connections for gsheet_not_active
add_connection.py -u FDV98 --uprev A --upport terminals -d FEM155 --dnrev A --dnport input --date 2022/11/01 --time 16:51
add_connection.py -u FEM155 --uprev A --upport pwr -d FPS10 --dnrev A --dnport pwr10 --date 2022/11/01 --time 16:51
add_connection.py -u FEM155 --uprev A --upport e -d NBP12 --dnrev A --dnport E10 --date 2022/11/01 --time 16:51
add_connection.py -u FEM155 --uprev A --upport n -d NBP12 --dnrev A --dnport N10 --date 2022/11/01 --time 16:51
add_connection.py -u A186 --uprev H --upport focus -d FDV125 --dnrev A --dnport input --date 2022/11/01 --time 16:51
add_connection.py -u A185 --uprev H --upport focus -d FDV112 --dnrev A --dnport input --date 2022/11/01 --time 16:51
