#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221104_infoupd_1642" >> scripts.log 
add_part_info.py -p HH46 -r A -c "Feed heights (NE/SE/SW/NW): 4.407" -l "infoupd" --date 2022/11/04 --time 16:42:00
add_part_info.py -p HH46 -r A -c "H6C: Feed Height Before: 4.399 Sticker Targets: Installed Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2022/11/04 --time 16:42:02
