#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221104_infoupd_1742" >> scripts.log 
update_apriori.py -p HH76 -s digital_maintenance --date 2022/11/04 --time 17:48
add_part_info.py -p HH76 -r A -c "apriori_antenna status change: RF_maintenance > digital_maintenance" -l "apa-infoupd" --date 2022/11/04 --time 17:48
add_part_info.py -p HH76 -r A -c "Feed heights (NE/SE/SW/NW): 4.409" -l "apa-infoupd" --date 2022/11/04 --time 17:42:00
add_part_info.py -p HH76 -r A -c "H6C: Feed Height Before: New connection Sticker Targets: Installed Stiffener Braces: Installed Carey Caps: Installed Protected Fiber: Installed Cable Conduit: Installed Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "apa-infoupd" --date 2022/11/04 --time 17:42:02
