#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221103_infoupd_1542" >> scripts.log 
add_part_info.py -p HH60 -r A -c "Feed heights (NE/SE/SW/NW): 4.408" -l "infoupd" --date 2022/11/03 --time 15:42:00
add_part_info.py -p HH60 -r A -c "H6C: Feed Height Before: 4.399 Sticker Targets: Present Already Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2022/11/03 --time 15:42:02
add_part_info.py -p HH43 -r A -c "Feed heights (NE/SE/SW/NW): 4.411" -l "infoupd" --date 2022/11/03 --time 15:42:00
add_part_info.py -p HH43 -r A -c "H6C: Feed Height Before: 4.391 Sticker Targets: Present Already Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2022/11/03 --time 15:42:02
add_part_info.py -p HH75 -r A -c "Feed heights (NE/SE/SW/NW): 4.407" -l "infoupd" --date 2022/11/03 --time 15:42:00
add_part_info.py -p HH75 -r A -c "H6C: Feed Height Before: 4.407 Sticker Targets: Present Already Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2022/11/03 --time 15:42:02
