#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221125_infoupd_1642" >> scripts.log 
add_part_info.py -p HH22 -r A -c "Feed heights (NE/SE/SW/NW): 4.407" -l "infoupd" --date 2022/11/25 --time 16:42:00
add_part_info.py -p HH22 -r A -c "H6C: Feed Height Before: 4.410 Sticker Targets: Present Already  Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Installed  Spiral Wrap: Present Already D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2022/11/25 --time 16:42:02
add_part_info.py -p HH77 -r A -c "FEM number is 292 not 291" -l "infoupd" --date 2022/11/25 --time 16:42:00
add_part_info.py -p HH77 -r A -c "Feed heights (NE/SE/SW/NW): 4.41" -l "infoupd" --date 2022/11/25 --time 16:42:02
add_part_info.py -p HH77 -r A -c "H6C: Feed Height Before: 4.407 Sticker Targets: Present Already  Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Installed  Spiral Wrap: Present Already D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2022/11/25 --time 16:42:04
add_part_info.py -p HH63 -r A -c "Feed heights (NE/SE/SW/NW): 4.404" -l "infoupd" --date 2022/11/25 --time 16:42:00
add_part_info.py -p HH63 -r A -c "H6C: Feed Height Before: 4.397 Sticker Targets: Present Already  Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Installed  Spiral Wrap: Present Already D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2022/11/25 --time 16:42:02
add_part_info.py -p HH64 -r A -c "Feed heights (NE/SE/SW/NW): 4.402" -l "infoupd" --date 2022/11/25 --time 16:42:00
add_part_info.py -p HH64 -r A -c "H6C: Feed Height Before: 4.410 Sticker Targets: Present Already  Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Installed  Spiral Wrap: Present Already D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2022/11/25 --time 16:42:02
add_part_info.py -p HH78 -r A -c "Feed heights (NE/SE/SW/NW): 4.408" -l "infoupd" --date 2022/11/25 --time 16:42:00
add_part_info.py -p HH78 -r A -c "H6C: Feed Height Before: 4.410 Sticker Targets: Present Already  Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Installed  Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2022/11/25 --time 16:42:02
