#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221123_infoupd_1042" >> scripts.log 
add_part_info.py -p HH166 -r A -c "Feed Heights: 4.406" -l "infoupd" --date 2022/11/23 --time 10:42:00
add_part_info.py -p HH166 -r A -c "H6C: Feed Height Before: 4.401 Sticker Targets: Already Present Stiffener Braces: Installed Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2022/11/23 --time 10:42:02
add_part_info.py -p HH186 -r A -c "Feed Heights: 4.406" -l "infoupd" --date 2022/11/23 --time 10:42:00
add_part_info.py -p HH186 -r A -c "H6C: Feed Height Before: 4.402 Sticker Targets: Present Already  Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Installed  Spiral Wrap: Present Already D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2022/11/23 --time 10:42:02
add_part_info.py -p HH185 -r A -c "Feed Heights: 4.410" -l "infoupd" --date 2022/11/23 --time 10:42:00
add_part_info.py -p HH185 -r A -c "H6C: Feed Height Before: 4.407 Sticker Targets: Present Already Stiffener Braces: Installed Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2022/11/23 --time 10:42:02
add_part_info.py -p HH187 -r A -c "Feed Heights: 4.409" -l "infoupd" --date 2022/11/23 --time 10:42:00
add_part_info.py -p HH187 -r A -c "H6C: Feed Height Before: 4.403 Sticker Targets: Present Already Stiffener Braces: Installed Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Present Already Cables Labelled: Completed" -l "infoupd" --date 2022/11/23 --time 10:42:02
add_part_info.py -p HH59 -r A -c "Feed heights (NE/SE/SW/NW): 4.407" -l "infoupd" --date 2022/11/23 --time 10:42:00
add_part_info.py -p HH59 -r A -c "FEM 103 replaced with FEM 334" -l "infoupd" --date 2022/11/23 --time 10:42:02
