#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221129_infoupd_2342" >> scripts.log 
update_apriori.py -p HH151 -s digital_ok --date 2022/11/29 --time 23:48
add_part_info.py -p HH151 -r A -c "apriori_antenna status change: not_connected > digital_ok" -l "apa-infoupd" --date 2022/11/29 --time 23:48
update_apriori.py -p HH152 -s digital_ok --date 2022/11/29 --time 23:48
add_part_info.py -p HH152 -r A -c "apriori_antenna status change: not_connected > digital_ok" -l "apa-infoupd" --date 2022/11/29 --time 23:48
update_apriori.py -p HH153 -s digital_ok --date 2022/11/29 --time 23:48
add_part_info.py -p HH153 -r A -c "apriori_antenna status change: not_connected > digital_ok" -l "apa-infoupd" --date 2022/11/29 --time 23:48
update_apriori.py -p HH154 -s digital_ok --date 2022/11/29 --time 23:48
add_part_info.py -p HH154 -r A -c "apriori_antenna status change: not_connected > digital_ok" -l "apa-infoupd" --date 2022/11/29 --time 23:48
update_apriori.py -p HH171 -s digital_ok --date 2022/11/29 --time 23:48
add_part_info.py -p HH171 -r A -c "apriori_antenna status change: not_connected > digital_ok" -l "apa-infoupd" --date 2022/11/29 --time 23:48
update_apriori.py -p HH172 -s digital_ok --date 2022/11/29 --time 23:48
add_part_info.py -p HH172 -r A -c "apriori_antenna status change: not_connected > digital_ok" -l "apa-infoupd" --date 2022/11/29 --time 23:48
update_apriori.py -p HH173 -s digital_ok --date 2022/11/29 --time 23:48
add_part_info.py -p HH173 -r A -c "apriori_antenna status change: not_connected > digital_ok" -l "apa-infoupd" --date 2022/11/29 --time 23:48
update_apriori.py -p HH174 -s digital_maintenance --date 2022/11/29 --time 23:48
add_part_info.py -p HH174 -r A -c "apriori_antenna status change: not_connected > digital_maintenance" -l "apa-infoupd" --date 2022/11/29 --time 23:48
update_apriori.py -p HH192 -s digital_ok --date 2022/11/29 --time 23:48
add_part_info.py -p HH192 -r A -c "apriori_antenna status change: not_connected > digital_ok" -l "apa-infoupd" --date 2022/11/29 --time 23:48
update_apriori.py -p HH193 -s digital_ok --date 2022/11/29 --time 23:48
add_part_info.py -p HH193 -r A -c "apriori_antenna status change: not_connected > digital_ok" -l "apa-infoupd" --date 2022/11/29 --time 23:48
update_apriori.py -p HH194 -s digital_maintenance --date 2022/11/29 --time 23:48
add_part_info.py -p HH194 -r A -c "apriori_antenna status change: not_connected > digital_maintenance" -l "apa-infoupd" --date 2022/11/29 --time 23:48
update_apriori.py -p HH213 -s digital_maintenance --date 2022/11/29 --time 23:48
add_part_info.py -p HH213 -r A -c "apriori_antenna status change: not_connected > digital_maintenance" -l "apa-infoupd" --date 2022/11/29 --time 23:48
