#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221210_infoupd_1442" >> scripts.log 
add_part_info.py -p HH131 -r A -c "Yellow FEM covers installed." -l "infoupd" --date 2022/12/10 --time 14:42:00
add_part_info.py -p HH131 -r A -c "Feed heights (NE/SE/SW/NW): 4.401" -l "infoupd" --date 2022/12/10 --time 14:42:02
add_part_info.py -p HH133 -r A -c "Yellow FEM covers installed" -l "infoupd" --date 2022/12/10 --time 14:42:00
add_part_info.py -p HH80 -r A -c "Yellow FEM cover installed." -l "infoupd" --date 2022/12/10 --time 14:42:00
add_part_info.py -p HH80 -r A -c "Feed heights (NE/SE/SW/NW): 4.404" -l "infoupd" --date 2022/12/10 --time 14:42:02
add_part_info.py -p N19 -r A -c "2 of 4 link lights are on for the SNAPs -- checking fiber." -l "infoupd" --date 2022/12/10 --time 14:42:00
add_part_info.py -p N20 -r A -c "(NCM15) WR-Len firmware updated" -l "infoupd" --date 2022/12/10 --time 14:42:00
