#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221207_infoupd_1542" >> scripts.log 
add_part_info.py -p N09 -r A -c "Power cycled once and now the arduino is accessible." -l "infoupd" --date 2022/12/07 --time 15:42:00
add_part_info.py -p N14 -r A -c "Power cycled twice and now it is accessible." -l "infoupd" --date 2022/12/07 --time 15:42:00
add_part_info.py -p N16 -r A -c "3 of 4 link lights are on for the SNAPs -- checking fiber" -l "infoupd" --date 2022/12/07 --time 15:42:00
add_part_info.py -p N19 -r A -c "2 of 4 link lights are on for the SNAPs -- checking fiber" -l "infoupd" --date 2022/12/07 --time 15:42:00
add_part_info.py -p N20 -r A -c "0 of 4 link lights are on for the SNAPs -- checking fiber" -l "infoupd" --date 2022/12/07 --time 15:42:00
