#! /usr/bin/env bash
echo 180109_update_ants >> scripts.log
stop_part.py -p A100 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A101 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A102 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A103 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A106 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A109 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A110 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A111 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A113 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A114 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A115 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A116 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A117 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A118 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A119 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A120 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A121 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A122 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A123 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A124 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A125 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A12 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A17 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A21 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A30 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A32 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A34 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A44 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A45 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A46 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A47 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A49 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A50 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A5 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A57 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A58 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A59 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A60 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A61 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A62 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A63 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A66 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A73 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A74 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A76 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A77 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A78 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A79 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A7 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A82 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A83 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A90 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A93 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A94 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A95 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A98 -r P --date 2016/10/01 --time 10:00 --actually_do_it
stop_part.py -p A99 -r P --date 2016/10/01 --time 10:00 --actually_do_it
add_part.py -p FEM75053 -r A -t front-end -m 75053 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p FEM75054 -r A -t front-end -m 75054 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p FEM75055 -r A -t front-end -m 75055 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p FEM75056 -r A -t front-end -m 75056 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p FEM75057 -r A -t front-end -m 75057 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p FEM75058 -r A -t front-end -m 75058 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p FEM75059 -r A -t front-end -m 75059 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p FEM75060 -r A -t front-end -m 75060 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p FEM75068 -r A -t front-end -m 75068 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p PAM75123 -r B -t post-amp -m 75123 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p PAM75124 -r B -t post-amp -m 75124 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p PAM75125 -r B -t post-amp -m 75125 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p PAM75126 -r B -t post-amp -m 75126 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p PAM75127 -r B -t post-amp -m 75127 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p PAM75128 -r B -t post-amp -m 75128 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p PAM75129 -r B -t post-amp -m 75129 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p PAM75130 -r B -t post-amp -m 75130 --date 2017/11/23 --time 10:00 --actually_do_it
add_part.py -p PAM75131 -r B -t post-amp -m 75131 --date 2017/11/23 --time 10:00 --actually_do_it
add_connection.py -u RI3A7E --uprev A --upport b -d PAM75123 --dnrev B --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75123 --uprev B --upport eb -d RO3A7E --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3A7N --uprev A --upport b -d PAM75123 --dnrev B --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75123 --uprev B --upport nb -d RO3A7N --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_station.py HH99
add_part.py -p A99 -r H -t antenna -m S/N58 --date 2018/01/08 --time 10:00 --actually_do_it
add_part.py -p FDA36 -r B -t feed -m P36 --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u HH99 --uprev A --upport ground -d A99 --dnrev H --dnport ground --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u A99 --uprev H --upport focus -d FDA36 --dnrev B --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FDA36 --uprev B --upport terminals -d FEM75057 --dnrev A --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75057 --uprev A --upport e -d C7F99 --dnrev A --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75057 --uprev A --upport n -d C7F99 --dnrev A --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F99 --uprev A --upport eb -d RI3A7E --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F99 --uprev A --upport nb -d RI3A7N --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3A8E --uprev A --upport b -d PAM75124 --dnrev B --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75124 --uprev B --upport eb -d RO3A8E --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3A8N --uprev A --upport b -d PAM75124 --dnrev B --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75124 --uprev B --upport nb -d RO3A8N --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_station.py HH100
add_part.py -p A100 -r H -t antenna -m S/N59 --date 2018/01/08 --time 10:00 --actually_do_it
add_part.py -p FDA37 -r B -t feed -m P37 --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u HH100 --uprev A --upport ground -d A100 --dnrev H --dnport ground --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u A100 --uprev H --upport focus -d FDA37 --dnrev B --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FDA37 --uprev B --upport terminals -d FEM75056 --dnrev A --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75056 --uprev A --upport e -d C7F100 --dnrev A --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75056 --uprev A --upport n -d C7F100 --dnrev A --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F100 --uprev A --upport eb -d RI3A8E --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F100 --uprev A --upport nb -d RI3A8N --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3B1E --uprev A --upport b -d PAM75125 --dnrev B --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75125 --uprev B --upport eb -d RO3B1E --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3B1N --uprev A --upport b -d PAM75125 --dnrev B --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75125 --uprev B --upport nb -d RO3B1N --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_station.py HH101
add_part.py -p A101 -r H -t antenna -m S/N60 --date 2018/01/08 --time 10:00 --actually_do_it
add_part.py -p FDA38 -r B -t feed -m P38 --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u HH101 --uprev A --upport ground -d A101 --dnrev H --dnport ground --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u A101 --uprev H --upport focus -d FDA38 --dnrev B --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FDA38 --uprev B --upport terminals -d FEM75055 --dnrev A --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75055 --uprev A --upport e -d C7F101 --dnrev A --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75055 --uprev A --upport n -d C7F101 --dnrev A --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F101 --uprev A --upport eb -d RI3B1E --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F101 --uprev A --upport nb -d RI3B1N --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3B2E --uprev A --upport b -d PAM75126 --dnrev B --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75126 --uprev B --upport eb -d RO3B2E --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3B2N --uprev A --upport b -d PAM75126 --dnrev B --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75126 --uprev B --upport nb -d RO3B2N --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_station.py HH102
add_part.py -p A102 -r H -t antenna -m S/N61 --date 2018/01/08 --time 10:00 --actually_do_it
add_part.py -p FDA39 -r B -t feed -m P39 --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u HH102 --uprev A --upport ground -d A102 --dnrev H --dnport ground --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u A102 --uprev H --upport focus -d FDA39 --dnrev B --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FDA39 --uprev B --upport terminals -d FEM75054 --dnrev A --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75054 --uprev A --upport e -d C7F102 --dnrev A --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75054 --uprev A --upport n -d C7F102 --dnrev A --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F102 --uprev A --upport eb -d RI3B2E --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F102 --uprev A --upport nb -d RI3B2N --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3B3E --uprev A --upport b -d PAM75127 --dnrev B --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75127 --uprev B --upport eb -d RO3B3E --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3B3N --uprev A --upport b -d PAM75127 --dnrev B --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75127 --uprev B --upport nb -d RO3B3N --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_station.py HH103
add_part.py -p A103 -r H -t antenna -m S/N62 --date 2018/01/08 --time 10:00 --actually_do_it
add_part.py -p FDA40 -r B -t feed -m P40 --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u HH103 --uprev A --upport ground -d A103 --dnrev H --dnport ground --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u A103 --uprev H --upport focus -d FDA40 --dnrev B --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FDA40 --uprev B --upport terminals -d FEM75053 --dnrev A --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75053 --uprev A --upport e -d C7F103 --dnrev A --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75053 --uprev A --upport n -d C7F103 --dnrev A --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F103 --uprev A --upport eb -d RI3B3E --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F103 --uprev A --upport nb -d RI3B3N --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3B4E --uprev A --upport b -d PAM75128 --dnrev B --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75128 --uprev B --upport eb -d RO3B4E --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3B4N --uprev A --upport b -d PAM75128 --dnrev B --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75128 --uprev B --upport nb -d RO3B4N --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_station.py HH104
add_part.py -p A104 -r H -t antenna -m S/N63 --date 2018/01/08 --time 10:00 --actually_do_it
add_part.py -p FDA41 -r B -t feed -m P41 --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u HH104 --uprev A --upport ground -d A104 --dnrev H --dnport ground --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u A104 --uprev H --upport focus -d FDA41 --dnrev B --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FDA41 --uprev B --upport terminals -d FEM75068 --dnrev A --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75068 --uprev A --upport e -d C7F104 --dnrev A --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75068 --uprev A --upport n -d C7F104 --dnrev A --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F104 --uprev A --upport eb -d RI3B4E --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F104 --uprev A --upport nb -d RI3B4N --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_station.py HH105
add_part.py -p A105 -r H -t antenna -m S/N64 --date 2018/01/08 --time 10:00 --actually_do_it
add_part.py -p FDA42 -r B -t feed -m P42 --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u HH105 --uprev A --upport ground -d A105 --dnrev H --dnport ground --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u A105 --uprev H --upport focus -d FDA42 --dnrev B --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_station.py HH106
add_part.py -p A106 -r H -t antenna -m S/N65 --date 2018/01/08 --time 10:00 --actually_do_it
add_part.py -p FDA44 -r B -t feed -m P44 --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u HH106 --uprev A --upport ground -d A106 --dnrev H --dnport ground --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u A106 --uprev H --upport focus -d FDA44 --dnrev B --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3B5E --uprev A --upport b -d PAM75129 --dnrev B --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75129 --uprev B --upport eb -d RO3B5E --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3B5N --uprev A --upport b -d PAM75129 --dnrev B --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75129 --uprev B --upport nb -d RO3B5N --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_station.py HH117
add_part.py -p A117 -r H -t antenna -m S/N66 --date 2018/01/08 --time 10:00 --actually_do_it
add_part.py -p FDA45 -r B -t feed -m P45 --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u HH117 --uprev A --upport ground -d A117 --dnrev H --dnport ground --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u A117 --uprev H --upport focus -d FDA45 --dnrev B --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FDA45 --uprev B --upport terminals -d FEM75060 --dnrev A --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75060 --uprev A --upport e -d C7F117 --dnrev A --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75060 --uprev A --upport n -d C7F117 --dnrev A --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F117 --uprev A --upport eb -d RI3B5E --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F117 --uprev A --upport nb -d RI3B5N --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3B6E --uprev A --upport b -d PAM75130 --dnrev B --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75130 --uprev B --upport eb -d RO3B6E --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3B6N --uprev A --upport b -d PAM75130 --dnrev B --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75130 --uprev B --upport nb -d RO3B6N --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_station.py HH118
add_part.py -p A118 -r H -t antenna -m S/N67 --date 2018/01/08 --time 10:00 --actually_do_it
add_part.py -p FDA46 -r B -t feed -m P46 --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u HH118 --uprev A --upport ground -d A118 --dnrev H --dnport ground --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u A118 --uprev H --upport focus -d FDA46 --dnrev B --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FDA46 --uprev B --upport terminals -d FEM75059 --dnrev A --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75059 --uprev A --upport e -d C7F118 --dnrev A --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75059 --uprev A --upport n -d C7F118 --dnrev A --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F118 --uprev A --upport eb -d RI3B6E --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F118 --uprev A --upport nb -d RI3B6N --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3B7E --uprev A --upport b -d PAM75131 --dnrev B --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75131 --uprev B --upport eb -d RO3B7E --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u RI3B7N --uprev A --upport b -d PAM75131 --dnrev B --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u PAM75131 --uprev B --upport nb -d RO3B7N --dnrev A --dnport b --date 2018/01/08 --time 10:00 --actually_do_it
add_station.py HH119
add_part.py -p A119 -r H -t antenna -m S/N68 --date 2018/01/08 --time 10:00 --actually_do_it
add_part.py -p FDA47 -r B -t feed -m P47 --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u HH119 --uprev A --upport ground -d A119 --dnrev H --dnport ground --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u A119 --uprev H --upport focus -d FDA47 --dnrev B --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FDA47 --uprev B --upport terminals -d FEM75058 --dnrev A --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75058 --uprev A --upport e -d C7F119 --dnrev A --dnport ea --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u FEM75058 --uprev A --upport n -d C7F119 --dnrev A --dnport na --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F119 --uprev A --upport eb -d RI3B7E --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u C7F119 --uprev A --upport nb -d RI3B7N --dnrev A --dnport a --date 2018/01/08 --time 10:00 --actually_do_it
add_station.py HH125
add_part.py -p A125 -r H -t antenna -m S/N69 --date 2018/01/08 --time 10:00 --actually_do_it
add_part.py -p FDA56 -r B -t feed -m P56 --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u HH125 --uprev A --upport ground -d A125 --dnrev H --dnport ground --date 2018/01/08 --time 10:00 --actually_do_it
add_connection.py -u A125 --uprev H --upport focus -d FDA56 --dnrev B --dnport input --date 2018/01/08 --time 10:00 --actually_do_it
