#! /usr/bin/env bash
echo 181101_update >> scripts.log
stop_connection.py -u A13 --uprev H --upport focus -d FDA31 --dnrev B --dnport input --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u A25 --uprev H --upport focus -d FDA20 --dnrev B --dnport input --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u A26 --uprev H --upport focus -d FDA89 --dnrev B --dnport input --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u FDV2 --uprev A --upport terminals -d FEM92 --dnrev A --dnport input --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u FEM92 --uprev A --upport e -d CRF001 --dnrev A --dnport ea --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u FEM92 --uprev A --upport n -d CRF001 --dnrev A --dnport na --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u CRF000 --uprev A --upport eb -d PAM75199 --dnrev A --dnport ea --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u CRF000 --uprev A --upport nb -d PAM75199 --dnrev A --dnport na --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u PAM75199 --uprev A --upport eb -d SNPA000022 --dnrev A --dnport e2 --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u PAM75199 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot01 --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u FDV1 --uprev A --upport terminals -d FEM96 --dnrev A --dnport input --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u FEM96 --uprev A --upport e -d CRF000 --dnrev A --dnport ea --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u FEM96 --uprev A --upport n -d CRF000 --dnrev A --dnport na --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u CRF001 --uprev A --upport eb -d PAM75196 --dnrev A --dnport ea --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u CRF001 --uprev A --upport nb -d PAM75196 --dnrev A --dnport na --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u PAM75196 --uprev A --upport nb -d SNPA000022 --dnrev A --dnport n4 --date 2018/10/30 --time 10:00 --actually_do_it
stop_connection.py -u PAM75196 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot02 --date 2018/10/30 --time 10:00 --actually_do_it
stop_part.py -p FEM92 -r A --date 2018/10/30 --time 10:10 --actually_do_it
stop_part.py -p FEM96 -r A --date 2018/10/30 --time 10:10 --actually_do_it
add_part.py -p FEM010 -r A -t front-end -m FEM010 --date 2018/10/30 --time 10:20 --actually_do_it
add_part.py -p FEM011 -r A -t front-end -m FEM011 --date 2018/10/30 --time 10:20 --actually_do_it
add_part.py -p FEM012 -r A -t front-end -m FEM012 --date 2018/10/30 --time 10:20 --actually_do_it
add_part.py -p FEM013 -r A -t front-end -m FEM013 --date 2018/10/30 --time 10:20 --actually_do_it
add_part.py -p FEM014 -r A -t front-end -m FEM014 --date 2018/10/30 --time 10:20 --actually_do_it
add_part.py -p FEM015 -r A -t front-end -m FEM015 --date 2018/10/30 --time 10:20 --actually_do_it
add_part.py -p PAM010 -r A -t post-amp -m PAM010 --date 2018/10/30 --time 10:20 --actually_do_it
add_part.py -p PAM011 -r A -t post-amp -m PAM011 --date 2018/10/30 --time 10:20 --actually_do_it
add_part.py -p PAM012 -r A -t post-amp -m PAM012 --date 2018/10/30 --time 10:20 --actually_do_it
add_part.py -p PAM013 -r A -t post-amp -m PAM013 --date 2018/10/30 --time 10:20 --actually_do_it
add_part.py -p PAM014 -r A -t post-amp -m PAM014 --date 2018/10/30 --time 10:20 --actually_do_it
add_part.py -p PAM015 -r A -t post-amp -m PAM015 --date 2018/10/30 --time 10:20 --actually_do_it
add_part.py -p CRF012 -r A -t cable-rfof -m orangegray --date 2018/10/30 --time 10:20 --actually_do_it
add_part.py -p CRF013 -r A -t cable-rfof -m 1/2 --date 2018/10/30 --time 10:20 --actually_do_it
add_part.py -p CRF025 -r A -t cable-rfof -m 3/4 --date 2018/10/30 --time 10:20 --actually_do_it
add_part.py -p CRF026 -r A -t cable-rfof -m 5/6 --date 2018/10/30 --time 10:20 --actually_do_it
add_connection.py -u FDV1 --uprev A --upport terminals -d FEM010 --dnrev A --dnport input --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FEM010 --uprev A --upport e -d CRF000 --dnrev A --dnport ea --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FEM010 --uprev A --upport n -d CRF000 --dnrev A --dnport na --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u CRF000 --uprev A --upport eb -d PAM010 --dnrev A --dnport ea --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u CRF000 --uprev A --upport nb -d PAM010 --dnrev A --dnport na --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM010 --uprev A --upport eb -d SNPA000008 --dnrev A --dnport e2 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM010 --uprev A --upport nb -d SNPA000008 --dnrev A --dnport n0 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM010 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot01 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FDV2 --uprev A --upport terminals -d FEM011 --dnrev A --dnport input --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FEM011 --uprev A --upport e -d CRF001 --dnrev A --dnport ea --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FEM011 --uprev A --upport n -d CRF001 --dnrev A --dnport na --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u CRF001 --uprev A --upport eb -d PAM011 --dnrev A --dnport ea --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u CRF001 --uprev A --upport nb -d PAM011 --dnrev A --dnport na --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM011 --uprev A --upport eb -d SNPA000008 --dnrev A --dnport e6 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM011 --uprev A --upport nb -d SNPA000008 --dnrev A --dnport n4 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM011 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot02 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FDV3 --uprev A --upport terminals -d FEM012 --dnrev A --dnport input --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FEM012 --uprev A --upport e -d CRF012 --dnrev A --dnport ea --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FEM012 --uprev A --upport n -d CRF012 --dnrev A --dnport na --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u CRF012 --uprev A --upport eb -d PAM012 --dnrev A --dnport ea --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u CRF012 --uprev A --upport nb -d PAM012 --dnrev A --dnport na --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM012 --uprev A --upport eb -d SNPA000008 --dnrev A --dnport e10 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM012 --uprev A --upport nb -d SNPA000008 --dnrev A --dnport n8 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM012 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot03 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FDV4 --uprev A --upport terminals -d FEM013 --dnrev A --dnport input --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FEM013 --uprev A --upport e -d CRF013 --dnrev A --dnport ea --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FEM013 --uprev A --upport n -d CRF013 --dnrev A --dnport na --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u CRF013 --uprev A --upport eb -d PAM013 --dnrev A --dnport ea --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u CRF013 --uprev A --upport nb -d PAM013 --dnrev A --dnport na --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM013 --uprev A --upport eb -d SNPA000022 --dnrev A --dnport e2 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM013 --uprev A --upport nb -d SNPA000022 --dnrev A --dnport n0 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM013 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot04 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FDV6 --uprev A --upport terminals -d FEM014 --dnrev A --dnport input --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FEM014 --uprev A --upport e -d CRF025 --dnrev A --dnport ea --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FEM014 --uprev A --upport n -d CRF025 --dnrev A --dnport na --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u CRF025 --uprev A --upport eb -d PAM014 --dnrev A --dnport ea --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u CRF025 --uprev A --upport nb -d PAM014 --dnrev A --dnport na --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM014 --uprev A --upport eb -d SNPA000022 --dnrev A --dnport e10 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM014 --uprev A --upport nb -d SNPA000022 --dnrev A --dnport n8 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM014 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot05 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FDV7 --uprev A --upport terminals -d FEM015 --dnrev A --dnport input --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FEM015 --uprev A --upport e -d CRF026 --dnrev A --dnport ea --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u FEM015 --uprev A --upport n -d CRF026 --dnrev A --dnport na --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u CRF026 --uprev A --upport eb -d PAM015 --dnrev A --dnport ea --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u CRF026 --uprev A --upport nb -d PAM015 --dnrev A --dnport na --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM015 --uprev A --upport eb -d SNPA000024 --dnrev A --dnport e2 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM015 --uprev A --upport nb -d SNPA000024 --dnrev A --dnport n0 --date 2018/10/30 --time 10:30 --actually_do_it
add_connection.py -u PAM015 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot06 --date 2018/10/30 --time 10:30 --actually_do_it
