#! /usr/bin/env bash
echo 181206_add_stations >> scripts.log
add_station.py HH61 --date 2018/12/04 --time 10:00
add_station.py HH62 --date 2018/12/04 --time 10:00
add_station.py HH77 --date 2018/12/04 --time 10:00
add_part.py -p A61 -r H -t antenna -m S/NS/N207 --date 2018/12/04 --time 10:00 --actually_do_it
add_part.py -p A62 -r H -t antenna -m S/NS/N208 --date 2018/12/04 --time 10:00 --actually_do_it
add_part.py -p A77 -r H -t antenna -m S/NS/N209 --date 2018/12/04 --time 10:00 --actually_do_it
add_connection.py -u HH61 --uprev A --upport ground -d A61 --dnrev H --dnport ground --date 2018/12/04 --time 12:00 --actually_do_it
add_connection.py -u HH62 --uprev A --upport ground -d A62 --dnrev H --dnport ground --date 2018/12/04 --time 12:00 --actually_do_it
add_connection.py -u HH77 --uprev A --upport ground -d A77 --dnrev H --dnport ground --date 2018/12/04 --time 12:00 --actually_do_it
