#! /bin/bash
echo "210716_connupd_1724" >> scripts.log 
# Adding missing parts
add_part.py -p FEM289 -r A -t front-end -m FEM289 --date 2021/07/16 --time 17:19
add_part.py -p FDV181 -r A -t feed -m FDV181 --date 2021/07/16 --time 17:19
add_part.py -p FDV227 -r A -t feed -m FDV227 --date 2021/07/16 --time 17:19
add_part.py -p FEM287 -r A -t front-end -m FEM287 --date 2021/07/16 --time 17:19
add_part.py -p FDV204 -r A -t feed -m FDV204 --date 2021/07/16 --time 17:19
add_part.py -p FDV159 -r A -t feed -m FDV159 --date 2021/07/16 --time 17:19
add_part.py -p FEM233 -r A -t front-end -m FEM233 --date 2021/07/16 --time 17:19
add_part.py -p FEM263 -r A -t front-end -m FEM263 --date 2021/07/16 --time 17:19
add_part.py -p FDV177 -r A -t feed -m FDV177 --date 2021/07/16 --time 17:19
add_part.py -p FDV228 -r A -t feed -m FDV228 --date 2021/07/16 --time 17:19
add_part.py -p FDV246 -r A -t feed -m FDV246 --date 2021/07/16 --time 17:19
add_part.py -p FEM234 -r A -t front-end -m FEM234 --date 2021/07/16 --time 17:19
add_part.py -p FEM290 -r A -t front-end -m FEM290 --date 2021/07/16 --time 17:19
add_part.py -p FDV215 -r A -t feed -m FDV215 --date 2021/07/16 --time 17:19
add_part.py -p FDV222 -r A -t feed -m FDV222 --date 2021/07/16 --time 17:19
add_part.py -p FDV229 -r A -t feed -m FDV229 --date 2021/07/16 --time 17:19
add_part.py -p FDV230 -r A -t feed -m FDV230 --date 2021/07/16 --time 17:19
add_part.py -p FDV206 -r A -t feed -m FDV206 --date 2021/07/16 --time 17:19
add_part.py -p FEM284 -r A -t front-end -m FEM284 --date 2021/07/16 --time 17:19
add_part.py -p FDV133 -r A -t feed -m FDV133 --date 2021/07/16 --time 17:19
add_part.py -p FEM251 -r A -t front-end -m FEM251 --date 2021/07/16 --time 17:19
add_part.py -p FDV239 -r A -t feed -m FDV239 --date 2021/07/16 --time 17:19
add_part.py -p FDV212 -r A -t feed -m FDV212 --date 2021/07/16 --time 17:19
add_part.py -p FEM277 -r A -t front-end -m FEM277 --date 2021/07/16 --time 17:19
add_part.py -p FEM246 -r A -t front-end -m FEM246 --date 2021/07/16 --time 17:19
add_part.py -p FEM292 -r A -t front-end -m FEM292 --date 2021/07/16 --time 17:19
add_part.py -p FEM281 -r A -t front-end -m FEM281 --date 2021/07/16 --time 17:19
add_part.py -p FEM267 -r A -t front-end -m FEM267 --date 2021/07/16 --time 17:19
add_part.py -p FEM256 -r A -t front-end -m FEM256 --date 2021/07/16 --time 17:19
add_part.py -p FDV199 -r A -t feed -m FDV199 --date 2021/07/16 --time 17:19
add_part.py -p FDV245 -r A -t feed -m FDV245 --date 2021/07/16 --time 17:19
add_part.py -p FDV166 -r A -t feed -m FDV166 --date 2021/07/16 --time 17:19
add_part.py -p FEM244 -r A -t front-end -m FEM244 --date 2021/07/16 --time 17:19
add_part.py -p FDV178 -r A -t feed -m FDV178 --date 2021/07/16 --time 17:19
add_part.py -p FEM275 -r A -t front-end -m FEM275 --date 2021/07/16 --time 17:19
add_part.py -p FEM274 -r A -t front-end -m FEM274 --date 2021/07/16 --time 17:19
add_part.py -p FEM239 -r A -t front-end -m FEM239 --date 2021/07/16 --time 17:19
add_part.py -p FEM278 -r A -t front-end -m FEM278 --date 2021/07/16 --time 17:19
add_part.py -p FEM242 -r A -t front-end -m FEM242 --date 2021/07/16 --time 17:19
add_part.py -p FEM250 -r A -t front-end -m FEM250 --date 2021/07/16 --time 17:19
add_part.py -p FEM276 -r A -t front-end -m FEM276 --date 2021/07/16 --time 17:19
add_part.py -p FDV168 -r A -t feed -m FDV168 --date 2021/07/16 --time 17:19
add_part.py -p FDV253 -r A -t feed -m FDV253 --date 2021/07/16 --time 17:19
add_part.py -p FDV205 -r A -t feed -m FDV205 --date 2021/07/16 --time 17:19
add_part.py -p FDV242 -r A -t feed -m FDV242 --date 2021/07/16 --time 17:19
add_part.py -p FDV243 -r A -t feed -m FDV243 --date 2021/07/16 --time 17:19
add_part.py -p FEM241 -r A -t front-end -m FEM241 --date 2021/07/16 --time 17:19
add_part.py -p FDV251 -r A -t feed -m FDV251 --date 2021/07/16 --time 17:19
add_part.py -p FDV207 -r A -t feed -m FDV207 --date 2021/07/16 --time 17:19
add_part.py -p FDV208 -r A -t feed -m FDV208 --date 2021/07/16 --time 17:19
add_part.py -p FDV252 -r A -t feed -m FDV252 --date 2021/07/16 --time 17:19
add_part.py -p FDV167 -r A -t feed -m FDV167 --date 2021/07/16 --time 17:19
add_part.py -p FDV194 -r A -t feed -m FDV194 --date 2021/07/16 --time 17:19
add_part.py -p FDV179 -r A -t feed -m FDV179 --date 2021/07/16 --time 17:19
add_part.py -p FDV271 -r A -t feed -m FDV271 --date 2021/07/16 --time 17:19
add_part.py -p FDV175 -r A -t feed -m FDV175 --date 2021/07/16 --time 17:19
add_part.py -p FDV221 -r A -t feed -m FDV221 --date 2021/07/16 --time 17:19
add_part.py -p FEM240 -r A -t front-end -m FEM240 --date 2021/07/16 --time 17:19
add_part.py -p FEM269 -r A -t front-end -m FEM269 --date 2021/07/16 --time 17:19
add_part.py -p FDV180 -r A -t feed -m FDV180 --date 2021/07/16 --time 17:19
add_part.py -p FEM243 -r A -t front-end -m FEM243 --date 2021/07/16 --time 17:19
add_part.py -p FEM285 -r A -t front-end -m FEM285 --date 2021/07/16 --time 17:19
add_part.py -p FEM270 -r A -t front-end -m FEM270 --date 2021/07/16 --time 17:19
add_part.py -p FEM288 -r A -t front-end -m FEM288 --date 2021/07/16 --time 17:19
add_part.py -p FEM268 -r A -t front-end -m FEM268 --date 2021/07/16 --time 17:19
add_part.py -p FEM245 -r A -t front-end -m FEM245 --date 2021/07/16 --time 17:19
add_part.py -p FDV241 -r A -t feed -m FDV241 --date 2021/07/16 --time 17:19
add_part.py -p FEM286 -r A -t front-end -m FEM286 --date 2021/07/16 --time 17:19
add_part.py -p FDV173 -r A -t feed -m FDV173 --date 2021/07/16 --time 17:19
add_part.py -p FDV268 -r A -t feed -m FDV268 --date 2021/07/16 --time 17:19
add_part.py -p FEM253 -r A -t front-end -m FEM253 --date 2021/07/16 --time 17:19
add_part.py -p FDV7176 -r A -t feed -m FDV7176 --date 2021/07/16 --time 17:19
add_part.py -p FDV174 -r A -t feed -m FDV174 --date 2021/07/16 --time 17:19
add_part.py -p FEM258 -r A -t front-end -m FEM258 --date 2021/07/16 --time 17:19
add_part.py -p FDV201 -r A -t feed -m FDV201 --date 2021/07/16 --time 17:19
add_part.py -p FEM247 -r A -t front-end -m FEM247 --date 2021/07/16 --time 17:19
add_part.py -p FEM273 -r A -t front-end -m FEM273 --date 2021/07/16 --time 17:19
add_part.py -p FEM271 -r A -t front-end -m FEM271 --date 2021/07/16 --time 17:19
add_part.py -p FEM238 -r A -t front-end -m FEM238 --date 2021/07/16 --time 17:19
add_part.py -p FDV270 -r A -t feed -m FDV270 --date 2021/07/16 --time 17:19
add_part.py -p FDV214 -r A -t feed -m FDV214 --date 2021/07/16 --time 17:19
add_part.py -p FDV247 -r A -t feed -m FDV247 --date 2021/07/16 --time 17:19
add_part.py -p FEM283 -r A -t front-end -m FEM283 --date 2021/07/16 --time 17:19
add_part.py -p FEM280 -r A -t front-end -m FEM280 --date 2021/07/16 --time 17:19
add_part.py -p FDV160 -r A -t feed -m FDV160 --date 2021/07/16 --time 17:19
add_part.py -p FDV244 -r A -t feed -m FDV244 --date 2021/07/16 --time 17:19
add_part.py -p FDV223 -r A -t feed -m FDV223 --date 2021/07/16 --time 17:19
add_part.py -p FEM237 -r A -t front-end -m FEM237 --date 2021/07/16 --time 17:19
add_part.py -p FEM282 -r A -t front-end -m FEM282 --date 2021/07/16 --time 17:19
add_part.py -p FEM291 -r A -t front-end -m FEM291 --date 2021/07/16 --time 17:19
add_part.py -p FEM236 -r A -t front-end -m FEM236 --date 2021/07/16 --time 17:19
# Adding missing connections
add_connection.py -u A22 --uprev H --upport focus -d FDV180 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV180 --uprev A --upport terminals -d FEM284 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM284 --uprev A --upport e -d NBP06 --dnrev A --dnport e1 --date 2021/07/16 --time 17:24
add_connection.py -u FEM284 --uprev A --upport n -d NBP06 --dnrev A --dnport n1 --date 2021/07/16 --time 17:24
add_connection.py -u A34 --uprev H --upport focus -d FDV177 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV177 --uprev A --upport terminals -d FEM285 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM285 --uprev A --upport e -d NBP06 --dnrev A --dnport e2 --date 2021/07/16 --time 17:24
add_connection.py -u FEM285 --uprev A --upport n -d NBP06 --dnrev A --dnport n2 --date 2021/07/16 --time 17:24
add_connection.py -u A35 --uprev H --upport focus -d FDV168 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV168 --uprev A --upport terminals -d FEM289 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM289 --uprev A --upport e -d NBP06 --dnrev A --dnport e3 --date 2021/07/16 --time 17:24
add_connection.py -u FEM289 --uprev A --upport n -d NBP06 --dnrev A --dnport n3 --date 2021/07/16 --time 17:24
add_connection.py -u A47 --uprev H --upport focus -d FDV179 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV179 --uprev A --upport terminals -d FEM290 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM290 --uprev A --upport e -d NBP06 --dnrev A --dnport e4 --date 2021/07/16 --time 17:24
add_connection.py -u FEM290 --uprev A --upport n -d NBP06 --dnrev A --dnport n4 --date 2021/07/16 --time 17:24
add_connection.py -u A48 --uprev H --upport focus -d FDV178 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV178 --uprev A --upport terminals -d FEM288 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM288 --uprev A --upport e -d NBP06 --dnrev A --dnport e7 --date 2021/07/16 --time 17:24
add_connection.py -u FEM288 --uprev A --upport n -d NBP06 --dnrev A --dnport n7 --date 2021/07/16 --time 17:24
add_connection.py -u A49 --uprev H --upport focus -d FDV181 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV181 --uprev A --upport terminals -d FEM287 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM287 --uprev A --upport e -d NBP06 --dnrev A --dnport e8 --date 2021/07/16 --time 17:24
add_connection.py -u FEM287 --uprev A --upport n -d NBP06 --dnrev A --dnport n8 --date 2021/07/16 --time 17:24
add_connection.py -u A61 --uprev H --upport focus -d FDV167 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV167 --uprev A --upport terminals -d FEM281 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM281 --uprev A --upport e -d NBP06 --dnrev A --dnport e5 --date 2021/07/16 --time 17:24
add_connection.py -u FEM281 --uprev A --upport n -d NBP06 --dnrev A --dnport n5 --date 2021/07/16 --time 17:24
add_connection.py -u A62 --uprev H --upport focus -d FDV166 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV166 --uprev A --upport terminals -d FEM292 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM292 --uprev A --upport e -d NBP06 --dnrev A --dnport e9 --date 2021/07/16 --time 17:24
add_connection.py -u FEM292 --uprev A --upport n -d NBP06 --dnrev A --dnport n9 --date 2021/07/16 --time 17:24
add_connection.py -u A63 --uprev H --upport focus -d FDV7176 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV7176 --uprev A --upport terminals -d FEM236 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM236 --uprev A --upport e -d NBP06 --dnrev A --dnport e10 --date 2021/07/16 --time 17:24
add_connection.py -u FEM236 --uprev A --upport n -d NBP06 --dnrev A --dnport n10 --date 2021/07/16 --time 17:24
add_connection.py -u A64 --uprev H --upport focus -d FDV175 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV175 --uprev A --upport terminals -d FEM286 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM286 --uprev A --upport e -d NBP06 --dnrev A --dnport e11 --date 2021/07/16 --time 17:24
add_connection.py -u FEM286 --uprev A --upport n -d NBP06 --dnrev A --dnport n11 --date 2021/07/16 --time 17:24
add_connection.py -u A77 --uprev H --upport focus -d FDV174 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV174 --uprev A --upport terminals -d FEM291 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM291 --uprev A --upport e -d NBP06 --dnrev A --dnport e6 --date 2021/07/16 --time 17:24
add_connection.py -u FEM291 --uprev A --upport n -d NBP06 --dnrev A --dnport n6 --date 2021/07/16 --time 17:24
add_connection.py -u A78 --uprev H --upport focus -d FDV173 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV173 --uprev A --upport terminals -d FEM283 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM283 --uprev A --upport e -d NBP06 --dnrev A --dnport e12 --date 2021/07/16 --time 17:24
add_connection.py -u FEM283 --uprev A --upport n -d NBP06 --dnrev A --dnport n12 --date 2021/07/16 --time 17:24
add_connection.py -u A79 --uprev H --upport focus -d FDV243 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV243 --uprev A --upport terminals -d FEM239 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM239 --uprev A --upport e -d NBP11 --dnrev A --dnport e10 --date 2021/07/16 --time 17:24
add_connection.py -u FEM239 --uprev A --upport n -d NBP11 --dnrev A --dnport n10 --date 2021/07/16 --time 17:24
add_connection.py -u A80 --uprev H --upport focus -d FDV268 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV268 --uprev A --upport terminals -d FEM237 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM237 --uprev A --upport e -d NBP11 --dnrev A --dnport e7 --date 2021/07/16 --time 17:24
add_connection.py -u FEM237 --uprev A --upport n -d NBP11 --dnrev A --dnport n7 --date 2021/07/16 --time 17:24
add_connection.py -u A95 --uprev H --upport focus -d FDV245 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV245 --uprev A --upport terminals -d FEM238 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM238 --uprev A --upport e -d NBP11 --dnrev A --dnport e11 --date 2021/07/16 --time 17:24
add_connection.py -u FEM238 --uprev A --upport n -d NBP11 --dnrev A --dnport n11 --date 2021/07/16 --time 17:24
add_connection.py -u A96 --uprev H --upport focus -d FDV244 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV244 --uprev A --upport terminals -d FEM241 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM241 --uprev A --upport e -d NBP11 --dnrev A --dnport e8 --date 2021/07/16 --time 17:24
add_connection.py -u FEM241 --uprev A --upport n -d NBP11 --dnrev A --dnport n8 --date 2021/07/16 --time 17:24
add_connection.py -u A97 --uprev H --upport focus -d FDV246 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV246 --uprev A --upport terminals -d FEM233 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM233 --uprev A --upport e -d NBP11 --dnrev A --dnport e5 --date 2021/07/16 --time 17:24
add_connection.py -u FEM233 --uprev A --upport n -d NBP11 --dnrev A --dnport n5 --date 2021/07/16 --time 17:24
add_connection.py -u A113 --uprev H --upport focus -d FDV271 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV271 --uprev A --upport terminals -d FEM243 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM243 --uprev A --upport e -d NBP11 --dnrev A --dnport e12 --date 2021/07/16 --time 17:24
add_connection.py -u FEM243 --uprev A --upport n -d NBP11 --dnrev A --dnport n12 --date 2021/07/16 --time 17:24
add_connection.py -u A114 --uprev H --upport focus -d FDV270 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV270 --uprev A --upport terminals -d FEM244 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM244 --uprev A --upport e -d NBP11 --dnrev A --dnport e9 --date 2021/07/16 --time 17:24
add_connection.py -u FEM244 --uprev A --upport n -d NBP11 --dnrev A --dnport n9 --date 2021/07/16 --time 17:24
add_connection.py -u A115 --uprev H --upport focus -d FDV247 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV247 --uprev A --upport terminals -d FEM282 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM282 --uprev A --upport e -d NBP11 --dnrev A --dnport e2 --date 2021/07/16 --time 17:24
add_connection.py -u FEM282 --uprev A --upport n -d NBP11 --dnrev A --dnport n2 --date 2021/07/16 --time 17:24
add_connection.py -u A131 --uprev H --upport focus -d FDV253 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV253 --uprev A --upport terminals -d FEM240 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM240 --uprev A --upport e -d NBP11 --dnrev A --dnport e1 --date 2021/07/16 --time 17:24
add_connection.py -u FEM240 --uprev A --upport n -d NBP11 --dnrev A --dnport n1 --date 2021/07/16 --time 17:24
add_connection.py -u A132 --uprev H --upport focus -d FDV241 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV241 --uprev A --upport terminals -d FEM234 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM234 --uprev A --upport e -d NBP11 --dnrev A --dnport e6 --date 2021/07/16 --time 17:24
add_connection.py -u FEM234 --uprev A --upport n -d NBP11 --dnrev A --dnport n6 --date 2021/07/16 --time 17:24
add_connection.py -u A133 --uprev H --upport focus -d FDV239 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV239 --uprev A --upport terminals -d FEM242 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM242 --uprev A --upport e -d NBP11 --dnrev A --dnport e3 --date 2021/07/16 --time 17:24
add_connection.py -u FEM242 --uprev A --upport n -d NBP11 --dnrev A --dnport n3 --date 2021/07/16 --time 17:24
add_connection.py -u A134 --uprev H --upport focus -d FDV242 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u A151 --uprev H --upport focus -d FDV252 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV252 --uprev A --upport terminals -d FEM274 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM274 --uprev A --upport e -d NBP16 --dnrev A --dnport e1 --date 2021/07/16 --time 17:24
add_connection.py -u FEM274 --uprev A --upport n -d NBP16 --dnrev A --dnport n1 --date 2021/07/16 --time 17:24
add_connection.py -u A152 --uprev H --upport focus -d FDV230 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV230 --uprev A --upport terminals -d FEM276 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM276 --uprev A --upport e -d NBP16 --dnrev A --dnport e7 --date 2021/07/16 --time 17:24
add_connection.py -u FEM276 --uprev A --upport n -d NBP16 --dnrev A --dnport n7 --date 2021/07/16 --time 17:24
add_connection.py -u A153 --uprev H --upport focus -d FDV215 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV215 --uprev A --upport terminals -d FEM277 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM277 --uprev A --upport e -d NBP16 --dnrev A --dnport e8 --date 2021/07/16 --time 17:24
add_connection.py -u FEM277 --uprev A --upport n -d NBP16 --dnrev A --dnport n8 --date 2021/07/16 --time 17:24
add_connection.py -u A154 --uprev H --upport focus -d FDV221 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u A171 --uprev H --upport focus -d FDV133 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u A172 --uprev H --upport focus -d FDV222 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV222 --uprev A --upport terminals -d FEM269 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM269 --uprev A --upport e -d NBP16 --dnrev A --dnport e3 --date 2021/07/16 --time 17:24
add_connection.py -u FEM269 --uprev A --upport n -d NBP16 --dnrev A --dnport n3 --date 2021/07/16 --time 17:24
add_connection.py -u A173 --uprev H --upport focus -d FDV214 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV214 --uprev A --upport terminals -d FEM275 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM275 --uprev A --upport e -d NBP16 --dnrev A --dnport e4 --date 2021/07/16 --time 17:24
add_connection.py -u FEM275 --uprev A --upport n -d NBP16 --dnrev A --dnport n4 --date 2021/07/16 --time 17:24
add_connection.py -u A174 --uprev H --upport focus -d FDV212 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV212 --uprev A --upport terminals -d FEM273 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM273 --uprev A --upport e -d NBP16 --dnrev A --dnport e10 --date 2021/07/16 --time 17:24
add_connection.py -u FEM273 --uprev A --upport n -d NBP16 --dnrev A --dnport n10 --date 2021/07/16 --time 17:24
add_connection.py -u A192 --uprev H --upport focus -d FDV251 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV251 --uprev A --upport terminals -d FEM270 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM270 --uprev A --upport e -d NBP16 --dnrev A --dnport e5 --date 2021/07/16 --time 17:24
add_connection.py -u FEM270 --uprev A --upport n -d NBP16 --dnrev A --dnport n5 --date 2021/07/16 --time 17:24
add_connection.py -u A193 --uprev H --upport focus -d FDV229 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV229 --uprev A --upport terminals -d FEM280 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM280 --uprev A --upport e -d NBP16 --dnrev A --dnport e6 --date 2021/07/16 --time 17:24
add_connection.py -u FEM280 --uprev A --upport n -d NBP16 --dnrev A --dnport n6 --date 2021/07/16 --time 17:24
add_connection.py -u A194 --uprev H --upport focus -d FDV223 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV223 --uprev A --upport terminals -d FEM271 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM271 --uprev A --upport e -d NBP16 --dnrev A --dnport e11 --date 2021/07/16 --time 17:24
add_connection.py -u FEM271 --uprev A --upport n -d NBP16 --dnrev A --dnport n11 --date 2021/07/16 --time 17:24
add_connection.py -u A200 --uprev H --upport focus -d FDV194 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV194 --uprev A --upport terminals -d FEM251 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM251 --uprev A --upport e -d NBP18 --dnrev A --dnport e1 --date 2021/07/16 --time 17:24
add_connection.py -u FEM251 --uprev A --upport n -d NBP18 --dnrev A --dnport n1 --date 2021/07/16 --time 17:24
add_connection.py -u A201 --uprev H --upport focus -d FDV159 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV159 --uprev A --upport terminals -d FEM247 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM247 --uprev A --upport e -d NBP18 --dnrev A --dnport e2 --date 2021/07/16 --time 17:24
add_connection.py -u FEM247 --uprev A --upport n -d NBP18 --dnrev A --dnport n2 --date 2021/07/16 --time 17:24
add_connection.py -u A202 --uprev H --upport focus -d FDV199 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV199 --uprev A --upport terminals -d FEM245 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM245 --uprev A --upport e -d NBP18 --dnrev A --dnport e3 --date 2021/07/16 --time 17:24
add_connection.py -u FEM245 --uprev A --upport n -d NBP18 --dnrev A --dnport n3 --date 2021/07/16 --time 17:24
add_connection.py -u A203 --uprev H --upport focus -d FDV201 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV201 --uprev A --upport terminals -d FEM250 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM250 --uprev A --upport e -d NBP18 --dnrev A --dnport e4 --date 2021/07/16 --time 17:24
add_connection.py -u FEM250 --uprev A --upport n -d NBP18 --dnrev A --dnport n4 --date 2021/07/16 --time 17:24
add_connection.py -u A213 --uprev H --upport focus -d FDV228 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV228 --uprev A --upport terminals -d FEM278 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM278 --uprev A --upport e -d NBP16 --dnrev A --dnport e12 --date 2021/07/16 --time 17:24
add_connection.py -u FEM278 --uprev A --upport n -d NBP16 --dnrev A --dnport n12 --date 2021/07/16 --time 17:24
add_connection.py -u A219 --uprev H --upport focus -d FDV205 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV205 --uprev A --upport terminals -d FEM258 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM258 --uprev A --upport e -d NBP18 --dnrev A --dnport e5 --date 2021/07/16 --time 17:24
add_connection.py -u FEM258 --uprev A --upport n -d NBP18 --dnrev A --dnport n5 --date 2021/07/16 --time 17:24
add_connection.py -u A220 --uprev H --upport focus -d FDV208 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV208 --uprev A --upport terminals -d FEM256 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM256 --uprev A --upport e -d NBP18 --dnrev A --dnport e7 --date 2021/07/16 --time 17:24
add_connection.py -u FEM256 --uprev A --upport n -d NBP18 --dnrev A --dnport n7 --date 2021/07/16 --time 17:24
add_connection.py -u A221 --uprev H --upport focus -d FDV207 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV207 --uprev A --upport terminals -d FEM246 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM246 --uprev A --upport e -d NBP18 --dnrev A --dnport e8 --date 2021/07/16 --time 17:24
add_connection.py -u FEM246 --uprev A --upport n -d NBP18 --dnrev A --dnport n8 --date 2021/07/16 --time 17:24
add_connection.py -u A222 --uprev H --upport focus -d FDV206 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV206 --uprev A --upport terminals -d FEM268 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM268 --uprev A --upport e -d NBP18 --dnrev A --dnport e9 --date 2021/07/16 --time 17:24
add_connection.py -u FEM268 --uprev A --upport n -d NBP18 --dnrev A --dnport n9 --date 2021/07/16 --time 17:24
add_connection.py -u A237 --uprev H --upport focus -d FDV227 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV227 --uprev A --upport terminals -d FEM253 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM253 --uprev A --upport e -d NBP18 --dnrev A --dnport e12 --date 2021/07/16 --time 17:24
add_connection.py -u FEM253 --uprev A --upport n -d NBP18 --dnrev A --dnport n12 --date 2021/07/16 --time 17:24
add_connection.py -u A238 --uprev H --upport focus -d FDV204 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV204 --uprev A --upport terminals -d FEM263 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM263 --uprev A --upport e -d NBP18 --dnrev A --dnport e11 --date 2021/07/16 --time 17:24
add_connection.py -u FEM263 --uprev A --upport n -d NBP18 --dnrev A --dnport n11 --date 2021/07/16 --time 17:24
add_connection.py -u A239 --uprev H --upport focus -d FDV160 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FDV160 --uprev A --upport terminals -d FEM267 --dnrev A --dnport input --date 2021/07/16 --time 17:24
add_connection.py -u FEM267 --uprev A --upport e -d NBP18 --dnrev A --dnport e10 --date 2021/07/16 --time 17:24
add_connection.py -u FEM267 --uprev A --upport n -d NBP18 --dnrev A --dnport n10 --date 2021/07/16 --time 17:24
# Adding missing parts
