#! /bin/bash
echo "220610_update_node_23" >> scripts.log 
add_station.py ND23 --sernum ND23 --date 2022/06/01 --time 10:00
add_part.py -p FPS26 -r A -t fem-power-supply -m FPS26 --date 2022/06/01 --time 10:00
add_part.py -p PCH24 -r A -t pam-chassis -m PCH24 --date 2022/06/01 --time 10:00
add_part.py -p NBP23 -r A -t node-bulkhead -m NBP23 --date 2022/06/01 --time 10:00
add_part.py -p PAM332 -r A -t post-amp -m 332 --date 2022/06/01 --time 10:00
add_part.py -p PAM333 -r A -t post-amp -m 333 --date 2022/06/01 --time 10:00
add_part.py -p PAM334 -r A -t post-amp -m 334 --date 2022/06/01 --time 10:00
add_part.py -p PAM335 -r A -t post-amp -m 335 --date 2022/06/01 --time 10:00
add_part.py -p PAM336 -r A -t post-amp -m 336 --date 2022/06/01 --time 10:00
add_part.py -p PAM337 -r A -t post-amp -m 337 --date 2022/06/01 --time 10:00
add_part.py -p PAM338 -r A -t post-amp -m 338 --date 2022/06/01 --time 10:00
add_part.py -p PAM339 -r A -t post-amp -m 339 --date 2022/06/01 --time 10:00
add_part.py -p PAM340 -r A -t post-amp -m 340 --date 2022/06/01 --time 10:00
add_part.py -p PAM341 -r A -t post-amp -m 341 --date 2022/06/01 --time 10:00
add_part.py -p PAM342 -r A -t post-amp -m 342 --date 2022/06/01 --time 10:00
add_part.py -p PAM343 -r A -t post-amp -m 343 --date 2022/06/01 --time 10:00
add_connection.py -u N23 --uprev A --upport ground -d ND23 --dnrev A --dnport ground --date 2022/06/01 --time 11:00
add_connection.py -u FPS26 --uprev A --upport rack -d N23 --dnrev A --dnport top --date 2022/06/01 --time 11:00
add_connection.py -u PCH24 --uprev A --upport rack -d N23 --dnrev A --dnport bottom --date 2022/06/01 --time 11:00
add_connection.py -u NCM19 --uprev A --upport rack -d N23 --dnrev A --dnport middle --date 2022/06/01 --time 11:00
add_connection.py -u PAM332 --uprev A --upport slot -d PCH24 --dnrev A --dnport slot1 --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport e1 -d PAM332 --dnrev A --dnport e --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport n1 -d PAM332 --dnrev A --dnport n --date 2022/06/01 --time 11:00
add_connection.py -u PAM333 --uprev A --upport slot -d PCH24 --dnrev A --dnport slot2 --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport e2 -d PAM333 --dnrev A --dnport e --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport n2 -d PAM333 --dnrev A --dnport n --date 2022/06/01 --time 11:00
add_connection.py -u PAM334 --uprev A --upport slot -d PCH24 --dnrev A --dnport slot3 --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport e3 -d PAM334 --dnrev A --dnport e --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport n3 -d PAM334 --dnrev A --dnport n --date 2022/06/01 --time 11:00
add_connection.py -u PAM335 --uprev A --upport slot -d PCH24 --dnrev A --dnport slot4 --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport e4 -d PAM335 --dnrev A --dnport e --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport n4 -d PAM335 --dnrev A --dnport n --date 2022/06/01 --time 11:00
add_connection.py -u PAM336 --uprev A --upport slot -d PCH24 --dnrev A --dnport slot5 --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport e5 -d PAM336 --dnrev A --dnport e --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport n5 -d PAM336 --dnrev A --dnport n --date 2022/06/01 --time 11:00
add_connection.py -u PAM337 --uprev A --upport slot -d PCH24 --dnrev A --dnport slot6 --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport e6 -d PAM337 --dnrev A --dnport e --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport n6 -d PAM337 --dnrev A --dnport n --date 2022/06/01 --time 11:00
add_connection.py -u PAM338 --uprev A --upport slot -d PCH24 --dnrev A --dnport slot7 --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport e7 -d PAM338 --dnrev A --dnport e --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport n7 -d PAM338 --dnrev A --dnport n --date 2022/06/01 --time 11:00
add_connection.py -u PAM339 --uprev A --upport slot -d PCH24 --dnrev A --dnport slot8 --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport e8 -d PAM339 --dnrev A --dnport e --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport n8 -d PAM339 --dnrev A --dnport n --date 2022/06/01 --time 11:00
add_connection.py -u PAM340 --uprev A --upport slot -d PCH24 --dnrev A --dnport slot9 --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport e9 -d PAM340 --dnrev A --dnport e --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport n9 -d PAM340 --dnrev A --dnport n --date 2022/06/01 --time 11:00
add_connection.py -u PAM341 --uprev A --upport slot -d PCH24 --dnrev A --dnport slot10 --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport e10 -d PAM341 --dnrev A --dnport e --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport n10 -d PAM341 --dnrev A --dnport n --date 2022/06/01 --time 11:00
add_connection.py -u PAM342 --uprev A --upport slot -d PCH24 --dnrev A --dnport slot11 --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport e11 -d PAM342 --dnrev A --dnport e --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport n11 -d PAM342 --dnrev A --dnport n --date 2022/06/01 --time 11:00
add_connection.py -u PAM343 --uprev A --upport slot -d PCH24 --dnrev A --dnport slot12 --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport e12 -d PAM343 --dnrev A --dnport e --date 2022/06/01 --time 11:00
add_connection.py -u NBP23 --uprev A --upport n12 -d PAM343 --dnrev A --dnport n --date 2022/06/01 --time 11:00
add_connection.py -u SNPC000113 --uprev A --upport rack -d N23 --dnrev A --dnport loc0 --date 2022/06/01 --time 11:00
add_connection.py -u PAM332 --uprev A --upport e -d SNPC000113 --dnrev A --dnport e2 --date 2022/06/01 --time 11:00
add_connection.py -u PAM333 --uprev A --upport e -d SNPC000113 --dnrev A --dnport e6 --date 2022/06/01 --time 11:00
add_connection.py -u PAM334 --uprev A --upport e -d SNPC000113 --dnrev A --dnport e10 --date 2022/06/01 --time 11:00
add_connection.py -u PAM332 --uprev A --upport n -d SNPC000113 --dnrev A --dnport n0 --date 2022/06/01 --time 11:00
add_connection.py -u PAM333 --uprev A --upport n -d SNPC000113 --dnrev A --dnport n4 --date 2022/06/01 --time 11:00
add_connection.py -u PAM334 --uprev A --upport n -d SNPC000113 --dnrev A --dnport n8 --date 2022/06/01 --time 11:00
add_connection.py -u SNPC000121 --uprev A --upport rack -d N23 --dnrev A --dnport loc1 --date 2022/06/01 --time 11:00
add_connection.py -u PAM335 --uprev A --upport e -d SNPC000121 --dnrev A --dnport e2 --date 2022/06/01 --time 11:00
add_connection.py -u PAM336 --uprev A --upport e -d SNPC000121 --dnrev A --dnport e6 --date 2022/06/01 --time 11:00
add_connection.py -u PAM337 --uprev A --upport e -d SNPC000121 --dnrev A --dnport e10 --date 2022/06/01 --time 11:00
add_connection.py -u PAM335 --uprev A --upport n -d SNPC000121 --dnrev A --dnport n0 --date 2022/06/01 --time 11:00
add_connection.py -u PAM336 --uprev A --upport n -d SNPC000121 --dnrev A --dnport n4 --date 2022/06/01 --time 11:00
add_connection.py -u PAM337 --uprev A --upport n -d SNPC000121 --dnrev A --dnport n8 --date 2022/06/01 --time 11:00
add_connection.py -u SNPC000124 --uprev A --upport rack -d N23 --dnrev A --dnport loc2 --date 2022/06/01 --time 11:00
add_connection.py -u PAM338 --uprev A --upport e -d SNPC000124 --dnrev A --dnport e2 --date 2022/06/01 --time 11:00
add_connection.py -u PAM339 --uprev A --upport e -d SNPC000124 --dnrev A --dnport e6 --date 2022/06/01 --time 11:00
add_connection.py -u PAM340 --uprev A --upport e -d SNPC000124 --dnrev A --dnport e10 --date 2022/06/01 --time 11:00
add_connection.py -u PAM338 --uprev A --upport n -d SNPC000124 --dnrev A --dnport n0 --date 2022/06/01 --time 11:00
add_connection.py -u PAM339 --uprev A --upport n -d SNPC000124 --dnrev A --dnport n4 --date 2022/06/01 --time 11:00
add_connection.py -u PAM340 --uprev A --upport n -d SNPC000124 --dnrev A --dnport n8 --date 2022/06/01 --time 11:00
add_connection.py -u SNPC000129 --uprev A --upport rack -d N23 --dnrev A --dnport loc3 --date 2022/06/01 --time 11:00
add_connection.py -u PAM341 --uprev A --upport e -d SNPC000129 --dnrev A --dnport e2 --date 2022/06/01 --time 11:00
add_connection.py -u PAM342 --uprev A --upport e -d SNPC000129 --dnrev A --dnport e6 --date 2022/06/01 --time 11:00
add_connection.py -u PAM343 --uprev A --upport e -d SNPC000129 --dnrev A --dnport e10 --date 2022/06/01 --time 11:00
add_connection.py -u PAM341 --uprev A --upport n -d SNPC000129 --dnrev A --dnport n0 --date 2022/06/01 --time 11:00
add_connection.py -u PAM342 --uprev A --upport n -d SNPC000129 --dnrev A --dnport n4 --date 2022/06/01 --time 11:00
add_connection.py -u PAM343 --uprev A --upport n -d SNPC000129 --dnrev A --dnport n8 --date 2022/06/01 --time 11:00
