#! /usr/bin/env bash
echo 171011_part_info >> scripts.log
part_info.py -p RO4A1E -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4A1N -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4A2E -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4A2N -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4A3E -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4A3N -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4A4E -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4A4N -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4A5E -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4A5N -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4A6E -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4A6N -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4A7E -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4A7N -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4A8E -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4A8N -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B1E -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B1N -r A -c 'Has 10 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B2E -r A -c 'Has 9 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B2N -r A -c 'Has 9 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B3E -r A -c 'Has 9 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B3N -r A -c 'Has 9 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B4E -r A -c 'Has 9 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B4N -r A -c 'Has 9 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B5E -r A -c 'Has 9 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B5N -r A -c 'Has 9 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B6E -r A -c 'Has 9 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B6N -r A -c 'Has 9 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B7E -r A -c 'Has 9 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B7N -r A -c 'Has 9 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B8E -r A -c 'Has 9 dB pad on rcvr output' -l none --date Now
part_info.py -p RO4B8N -r A -c 'Has 9 dB pad on rcvr output' -l none --date Now
part_info.py -p PAM75112 -r B -c 'Apparently died and has been replaced by PAM75168' -l none --date Now
part_info.py -p RI4A1E -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4A1N -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4A2E -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4A2N -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4A3E -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4A3N -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4A4E -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4A4N -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4A5E -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4A5N -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4A7E -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4A7N -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4A8E -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4A8N -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4B1E -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4B1N -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4B3E -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4B3N -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4B4E -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4B4N -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4B5E -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4B5N -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4B6E -r A -c 'E/N pol swapped at receiverator input' -l none --date Now
part_info.py -p RI4B6N -r A -c 'E/N pol swapped at receiverator input' -l none --date Now