#! /usr/bin/env bash
echo 171011_add_deepthis_ants_back_in >> scripts.log
add_connection.py -u C7F24 --uprev A --upport eb -d RI8B1E --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F24 --uprev A --upport nb -d RI8B1N --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F25 --uprev A --upport eb -d RI8B2E --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F25 --uprev A --upport nb -d RI8B2N --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F26 --uprev A --upport eb -d RI8B3E --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F26 --uprev A --upport nb -d RI8B3N --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F27 --uprev A --upport eb -d RI8B4E --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F27 --uprev A --upport nb -d RI8B4N --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F52 --uprev A --upport eb -d RI8A5E --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F52 --uprev A --upport nb -d RI8A5N --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F53 --uprev A --upport eb -d RI8A6E --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F53 --uprev A --upport nb -d RI8A6N --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F54 --uprev A --upport eb -d RI8A7E --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F54 --uprev A --upport nb -d RI8A7N --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F55 --uprev A --upport eb -d RI5B3E --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F55 --uprev A --upport nb -d RI5B3N --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F84 --uprev A --upport eb -d RI8A1E --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F84 --uprev A --upport nb -d RI8A1N --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F85 --uprev A --upport eb -d RI8A2E --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F85 --uprev A --upport nb -d RI8A2N --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F86 --uprev A --upport eb -d RI8A3E --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F86 --uprev A --upport nb -d RI8A3N --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F87 --uprev A --upport eb -d RI8A4E --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
add_connection.py -u C7F87 --uprev A --upport nb -d RI8A4N --dnrev A --dnport a --date 2017/10/10 --time 15:00 --actually_do_it
