#! /usr/bin/env bash
echo "190830_add_stations" >> scripts.log 
add_station.py HH80 --sernum 265 --date 2019/08/13 --time 10:00
add_part.py -p A80 -r H -t antenna -m S/N265 --date 2019/08/13 --time 10:00
add_connection.py -u HH80 --uprev A --upport ground -d A80 --dnrev H --dnport ground --date 2019/08/13 --time 10:00
add_station.py HH97 --sernum 266 --date 2019/08/13 --time 10:00
add_part.py -p A97 -r H -t antenna -m S/N266 --date 2019/08/13 --time 10:00
add_connection.py -u HH97 --uprev A --upport ground -d A97 --dnrev H --dnport ground --date 2019/08/13 --time 10:00
add_station.py HH113 --sernum 267 --date 2019/08/13 --time 10:00
add_part.py -p A113 -r H -t antenna -m S/N267 --date 2019/08/13 --time 10:00
add_connection.py -u HH113 --uprev A --upport ground -d A113 --dnrev H --dnport ground --date 2019/08/13 --time 10:00
