#! /usr/bin/env bash
echo "190917_overview_update_2028" >> scripts.log 
update_apriori.py -p HH85 -s needs_checking --date 2019/09/17 --time 12:00
update_apriori.py -p HH86 -s needs_checking --date 2019/09/17 --time 12:00
update_apriori.py -p HH88 -s needs_checking --date 2019/09/17 --time 12:00
update_apriori.py -p HH90 -s needs_checking --date 2019/09/17 --time 12:00
update_apriori.py -p HH91 -s needs_checking --date 2019/09/17 --time 12:00
update_apriori.py -p HH102 -s needs_checking --date 2019/09/17 --time 12:00
add_part.py -p FEM034 -r A -t front-end -m FEM034 --date 2019/09/17 --time 12:00
stop_connection.py -u FDV41 --uprev A --upport terminals -d FEM060 --dnrev A --dnport input --date 2019/09/17 --time 12:00
stop_connection.py -u FEM060 --uprev A --upport e -d NBP08 --dnrev A --dnport e6 --date 2019/09/17 --time 12:00
stop_connection.py -u FEM060 --uprev A --upport n -d NBP08 --dnrev A --dnport n6 --date 2019/09/17 --time 12:00
add_connection.py -u FDV41 --uprev A --upport terminals -d FEM034 --dnrev A --dnport input --date 2019/09/17 --time 12:00
add_connection.py -u FEM034 --uprev A --upport e -d NBP08 --dnrev A --dnport e6 --date 2019/09/17 --time 12:00
add_connection.py -u FEM034 --uprev A --upport n -d NBP08 --dnrev A --dnport n6 --date 2019/09/17 --time 12:00
update_apriori.py -p HH103 -s needs_checking --date 2019/09/17 --time 12:00
update_apriori.py -p HH104 -s needs_checking --date 2019/09/17 --time 12:00
update_apriori.py -p HH105 -s needs_checking --date 2019/09/17 --time 12:00
update_apriori.py -p HH120 -s needs_checking --date 2019/09/17 --time 12:00
update_apriori.py -p HH123 -s needs_checking --date 2019/09/17 --time 12:00
