#! /usr/bin/env bash
echo "191115_misc_fixes" >> scripts.log 
add_part_info.py -p N03 -r A -c "Has full set of air curtains.  Fan pipe has extra bends into ground." --date 2019/11/13 --time 11:00
add_part_info.py -p N04 -r A -c "Has full set of air curtains." --date 2019/11/13 --time 11:00
add_part_info.py -p N05 -r A -c "Has full set of air curtains." --date 2019/11/13 --time 11:00
add_part_info.py -p N07 -r A -c "No air curtains and fan pipe has extra bends into ground." --date 2019/11/13 --time 11:00
add_part_info.py -p N08 -r A -c "No air curtains." --date 2019/11/13 --time 11:00
add_part_info.py -p N09 -r A -c "No air curtains." --date 2019/11/13 --time 11:00
