#! /usr/bin/env bash
echo "191118_add_antennas" >> scripts.log 
add_part.py -p FDV50 -r A -t feed -m FDV50 --date 2019/11/16 --time 10:00
add_part.py -p FEM116 -r A -t front-end -m FEM116 --date 2019/11/16 --time 10:00
add_connection.py -u A43 --uprev H --upport focus -d FDV50 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV50 --uprev A --upport terminals -d FEM116 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM116 --uprev A --upport e -d NBP05 --dnrev A --dnport e8 --date 2019/11/16 --time 11:00
add_connection.py -u FEM116 --uprev A --upport n -d NBP05 --dnrev A --dnport n8 --date 2019/11/16 --time 11:00
add_part.py -p FDV59 -r A -t feed -m FDV59 --date 2019/11/16 --time 10:00
add_part.py -p FEM109 -r A -t front-end -m FEM109 --date 2019/11/16 --time 10:00
add_connection.py -u A44 --uprev H --upport focus -d FDV59 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV59 --uprev A --upport terminals -d FEM109 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM109 --uprev A --upport e -d NBP05 --dnrev A --dnport e6 --date 2019/11/16 --time 11:00
add_connection.py -u FEM109 --uprev A --upport n -d NBP05 --dnrev A --dnport n6 --date 2019/11/16 --time 11:00
add_part.py -p FDV56 -r A -t feed -m FDV56 --date 2019/11/16 --time 10:00
add_part.py -p FEM102 -r A -t front-end -m FEM102 --date 2019/11/16 --time 10:00
add_connection.py -u A45 --uprev H --upport focus -d FDV56 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV56 --uprev A --upport terminals -d FEM102 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM102 --uprev A --upport e -d NBP05 --dnrev A --dnport e1 --date 2019/11/16 --time 11:00
add_connection.py -u FEM102 --uprev A --upport n -d NBP05 --dnrev A --dnport n1 --date 2019/11/16 --time 11:00
add_part.py -p FDV57 -r A -t feed -m FDV57 --date 2019/11/16 --time 10:00
add_part.py -p FEM110 -r A -t front-end -m FEM110 --date 2019/11/16 --time 10:00
add_connection.py -u A46 --uprev H --upport focus -d FDV57 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV57 --uprev A --upport terminals -d FEM110 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM110 --uprev A --upport e -d NBP05 --dnrev A --dnport e2 --date 2019/11/16 --time 11:00
add_connection.py -u FEM110 --uprev A --upport n -d NBP05 --dnrev A --dnport n2 --date 2019/11/16 --time 11:00
add_part.py -p FDV67 -r A -t feed -m FDV67 --date 2019/11/16 --time 10:00
add_part.py -p FEM118 -r A -t front-end -m FEM118 --date 2019/11/16 --time 10:00
add_connection.py -u A58 --uprev H --upport focus -d FDV67 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV67 --uprev A --upport terminals -d FEM118 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM118 --uprev A --upport e -d NBP05 --dnrev A --dnport e5 --date 2019/11/16 --time 11:00
add_connection.py -u FEM118 --uprev A --upport n -d NBP05 --dnrev A --dnport n5 --date 2019/11/16 --time 11:00
add_part.py -p FDV66 -r A -t feed -m FDV66 --date 2019/11/16 --time 10:00
add_part.py -p FEM103 -r A -t front-end -m FEM103 --date 2019/11/16 --time 10:00
add_connection.py -u A59 --uprev H --upport focus -d FDV66 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV66 --uprev A --upport terminals -d FEM103 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM103 --uprev A --upport e -d NBP05 --dnrev A --dnport e4 --date 2019/11/16 --time 11:00
add_connection.py -u FEM103 --uprev A --upport n -d NBP05 --dnrev A --dnport n4 --date 2019/11/16 --time 11:00
add_part.py -p FDV64 -r A -t feed -m FDV64 --date 2019/11/16 --time 10:00
add_part.py -p FEM108 -r A -t front-end -m FEM108 --date 2019/11/16 --time 10:00
add_connection.py -u A60 --uprev H --upport focus -d FDV64 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV64 --uprev A --upport terminals -d FEM108 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM108 --uprev A --upport e -d NBP05 --dnrev A --dnport e7 --date 2019/11/16 --time 11:00
add_connection.py -u FEM108 --uprev A --upport n -d NBP05 --dnrev A --dnport n7 --date 2019/11/16 --time 11:00
add_part.py -p FDV60 -r A -t feed -m FDV60 --date 2019/11/16 --time 10:00
add_part.py -p FEM122 -r A -t front-end -m FEM122 --date 2019/11/16 --time 10:00
add_connection.py -u A73 --uprev H --upport focus -d FDV60 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV60 --uprev A --upport terminals -d FEM122 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM122 --uprev A --upport e -d NBP05 --dnrev A --dnport e3 --date 2019/11/16 --time 11:00
add_connection.py -u FEM122 --uprev A --upport n -d NBP05 --dnrev A --dnport n3 --date 2019/11/16 --time 11:00
add_part.py -p FDV73 -r A -t feed -m FDV73 --date 2019/11/16 --time 10:00
add_part.py -p FEM111 -r A -t front-end -m FEM111 --date 2019/11/16 --time 10:00
add_connection.py -u A74 --uprev H --upport focus -d FDV73 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV73 --uprev A --upport terminals -d FEM111 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM111 --uprev A --upport e -d NBP05 --dnrev A --dnport e9 --date 2019/11/16 --time 11:00
add_connection.py -u FEM111 --uprev A --upport n -d NBP05 --dnrev A --dnport n9 --date 2019/11/16 --time 11:00
add_part.py -p FDV62 -r A -t feed -m FDV62 --date 2019/11/16 --time 10:00
add_part.py -p FEM115 -r A -t front-end -m FEM115 --date 2019/11/16 --time 10:00
add_connection.py -u A75 --uprev H --upport focus -d FDV62 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV62 --uprev A --upport terminals -d FEM115 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM115 --uprev A --upport e -d NBP05 --dnrev A --dnport e10 --date 2019/11/16 --time 11:00
add_connection.py -u FEM115 --uprev A --upport n -d NBP05 --dnrev A --dnport n10 --date 2019/11/16 --time 11:00
add_part.py -p FDV58 -r A -t feed -m FDV58 --date 2019/11/16 --time 10:00
add_part.py -p FEM101 -r A -t front-end -m FEM101 --date 2019/11/16 --time 10:00
add_connection.py -u A40 --uprev H --upport focus -d FDV58 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV58 --uprev A --upport terminals -d FEM101 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM101 --uprev A --upport e -d NBP04 --dnrev A --dnport e6 --date 2019/11/16 --time 11:00
add_connection.py -u FEM101 --uprev A --upport n -d NBP04 --dnrev A --dnport n6 --date 2019/11/16 --time 11:00
add_part.py -p FDV52 -r A -t feed -m FDV52 --date 2019/11/16 --time 10:00
add_part.py -p FEM104 -r A -t front-end -m FEM104 --date 2019/11/16 --time 10:00
add_connection.py -u A41 --uprev H --upport focus -d FDV52 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV52 --uprev A --upport terminals -d FEM104 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM104 --uprev A --upport e -d NBP04 --dnrev A --dnport e10 --date 2019/11/16 --time 11:00
add_connection.py -u FEM104 --uprev A --upport n -d NBP04 --dnrev A --dnport n10 --date 2019/11/16 --time 11:00
add_part.py -p FDV53 -r A -t feed -m FDV53 --date 2019/11/16 --time 10:00
add_part.py -p FEM123 -r A -t front-end -m FEM123 --date 2019/11/16 --time 10:00
add_connection.py -u A42 --uprev H --upport focus -d FDV53 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV53 --uprev A --upport terminals -d FEM123 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM123 --uprev A --upport e -d NBP04 --dnrev A --dnport e2 --date 2019/11/16 --time 11:00
add_connection.py -u FEM123 --uprev A --upport n -d NBP04 --dnrev A --dnport n2 --date 2019/11/16 --time 11:00
add_part.py -p FDV54 -r A -t feed -m FDV54 --date 2019/11/16 --time 10:00
add_part.py -p FEM120 -r A -t front-end -m FEM120 --date 2019/11/16 --time 10:00
add_connection.py -u A54 --uprev H --upport focus -d FDV54 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV54 --uprev A --upport terminals -d FEM120 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM120 --uprev A --upport e -d NBP04 --dnrev A --dnport e3 --date 2019/11/16 --time 11:00
add_connection.py -u FEM120 --uprev A --upport n -d NBP04 --dnrev A --dnport n3 --date 2019/11/16 --time 11:00
add_part.py -p FEM119 -r A -t front-end -m FEM119 --date 2019/11/16 --time 10:00
add_connection.py -u A55 --uprev H --upport focus -d FDV23 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV23 --uprev A --upport terminals -d FEM119 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM119 --uprev A --upport e -d NBP04 --dnrev A --dnport e7 --date 2019/11/16 --time 11:00
add_connection.py -u FEM119 --uprev A --upport n -d NBP04 --dnrev A --dnport n7 --date 2019/11/16 --time 11:00
add_part.py -p FDV72 -r A -t feed -m FDV72 --date 2019/11/16 --time 10:00
add_part.py -p FEM105 -r A -t front-end -m FEM105 --date 2019/11/16 --time 10:00
add_connection.py -u A56 --uprev H --upport focus -d FDV72 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV72 --uprev A --upport terminals -d FEM105 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM105 --uprev A --upport e -d NBP04 --dnrev A --dnport e4 --date 2019/11/16 --time 11:00
add_connection.py -u FEM105 --uprev A --upport n -d NBP04 --dnrev A --dnport n4 --date 2019/11/16 --time 11:00
add_part.py -p FDV71 -r A -t feed -m FDV71 --date 2019/11/16 --time 10:00
add_part.py -p FEM113 -r A -t front-end -m FEM113 --date 2019/11/16 --time 10:00
add_connection.py -u A57 --uprev H --upport focus -d FDV71 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV71 --uprev A --upport terminals -d FEM113 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM113 --uprev A --upport e -d NBP04 --dnrev A --dnport e11 --date 2019/11/16 --time 11:00
add_connection.py -u FEM113 --uprev A --upport n -d NBP04 --dnrev A --dnport n11 --date 2019/11/16 --time 11:00
add_part.py -p FDV65 -r A -t feed -m FDV65 --date 2019/11/16 --time 10:00
add_part.py -p FEM121 -r A -t front-end -m FEM121 --date 2019/11/16 --time 10:00
add_connection.py -u A69 --uprev H --upport focus -d FDV65 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV65 --uprev A --upport terminals -d FEM121 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM121 --uprev A --upport e -d NBP04 --dnrev A --dnport e5 --date 2019/11/16 --time 11:00
add_connection.py -u FEM121 --uprev A --upport n -d NBP04 --dnrev A --dnport n5 --date 2019/11/16 --time 11:00
add_part.py -p FDV55 -r A -t feed -m FDV55 --date 2019/11/16 --time 10:00
add_part.py -p FEM112 -r A -t front-end -m FEM112 --date 2019/11/16 --time 10:00
add_connection.py -u A70 --uprev H --upport focus -d FDV55 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV55 --uprev A --upport terminals -d FEM112 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM112 --uprev A --upport e -d NBP04 --dnrev A --dnport e9 --date 2019/11/16 --time 11:00
add_connection.py -u FEM112 --uprev A --upport n -d NBP04 --dnrev A --dnport n9 --date 2019/11/16 --time 11:00
add_part.py -p FDV63 -r A -t feed -m FDV63 --date 2019/11/16 --time 10:00
add_part.py -p FEM114 -r A -t front-end -m FEM114 --date 2019/11/16 --time 10:00
add_connection.py -u A71 --uprev H --upport focus -d FDV63 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV63 --uprev A --upport terminals -d FEM114 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM114 --uprev A --upport e -d NBP04 --dnrev A --dnport e8 --date 2019/11/16 --time 11:00
add_connection.py -u FEM114 --uprev A --upport n -d NBP04 --dnrev A --dnport n8 --date 2019/11/16 --time 11:00
add_part.py -p FDV61 -r A -t feed -m FDV61 --date 2019/11/16 --time 10:00
add_part.py -p FEM124 -r A -t front-end -m FEM124 --date 2019/11/16 --time 10:00
add_connection.py -u A72 --uprev H --upport focus -d FDV61 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FDV61 --uprev A --upport terminals -d FEM124 --dnrev A --dnport input --date 2019/11/16 --time 11:00
add_connection.py -u FEM124 --uprev A --upport e -d NBP04 --dnrev A --dnport e1 --date 2019/11/16 --time 11:00
add_connection.py -u FEM124 --uprev A --upport n -d NBP04 --dnrev A --dnport n1 --date 2019/11/16 --time 11:00
