#! /usr/bin/env bash
echo "../cm_updates/191118_overview_update_1214" >> scripts.log 
add_part_info.py -p HH42 -r A -c "PAM 103 replaced with 112" --date 2019/11/18 --time 12:00:00
add_part_info.py -p HH43 -r A -c "E channel shows ~6dB lower gain due to fibre.  We tested the fibre for both channels and the E channel had 3dB more loss (6dB in RF)" --date 2019/11/18 --time 12:00:00
add_part_info.py -p HH43 -r A -c "almost aligned" --date 2019/11/18 --time 12:00:01
add_part_info.py -p HH45 -r A -c "Aligned 4.401 (from jig same as 58)" --date 2019/11/18 --time 12:00:00
add_part_info.py -p HH46 -r A -c "xy aligned but no heights yet" --date 2019/11/18 --time 12:00:00
add_part_info.py -p HH58 -r A -c "Aligned 4.401 (from jig)" --date 2019/11/18 --time 12:00:00
add_part_info.py -p HH59 -r A -c "Aligned 4.413 (from jig)" --date 2019/11/18 --time 12:00:00
add_part_info.py -p HH60 -r A -c "xy aligned but no heights yet" --date 2019/11/18 --time 12:00:00
add_part_info.py -p HH73 -r A -c "Aligned 4.399 (from jig)" --date 2019/11/18 --time 12:00:00
add_part_info.py -p HH74 -r A -c "Aligned 4.404 (from jig)" --date 2019/11/18 --time 12:00:00
add_part_info.py -p HH75 -r A -c "xy aligned but no heights yet" --date 2019/11/18 --time 12:00:00
add_part_info.py -p HH81 -r A -c "FEM checked, xyz positioned, height 4.407" --date 2019/11/15 --time 12:00:00
add_part_info.py -p HH82 -r A -c "FEM checked, xyz positioned, height 4.403" --date 2019/11/15 --time 12:00:00
add_part_info.py -p HH83 -r A -c "FEM checked, xyz positioned, height 4.409" --date 2019/11/15 --time 12:00:00
add_part_info.py -p HH83 -r A -c "PAM input seems fixed maybe after reseating PAM in swap and removing dirt" --date 2019/11/15 --time 12:00:01
add_part_info.py -p HH98 -r A -c "FEM checked, xyz positioned, height 4.414" --date 2019/11/15 --time 12:00:00
add_part_info.py -p HH99 -r A -c "lowered, broken RF fiber" --date 2019/11/11 --time 12:00:00
add_part_info.py -p HH100 -r A -c "raised. North lifting line is failing - needs to be replaced" --date 2019/11/19 --time 12:00:00
add_part_info.py -p HH116 -r A -c "FEM checked, xyz positioned, height 4.398" --date 2019/11/19 --time 12:00:00
add_part_info.py -p HH118 -r A -c "raised" --date 2019/11/4 --time 12:00:00
add_part_info.py -p HH119 -r A -c "raised" --date 2019/11/4 --time 12:00:00
add_part_info.py -p HH137 -r A -c "raised" --date 2019/11/4 --time 12:00:00
add_part_info.py -p HH138 -r A -c "raised" --date 2019/11/4 --time 12:00:00
add_part_info.py -p HH88 -r A -c "height raised from 4.205m to 4.418m 10/31/19" --date 2019/11/18 --time 12:00:00
add_part_info.py -p HH107 -r A -c "Low amplitude after equalized to noise" --date 2019/11/18 --time 12:00:00
add_part_info.py -p HH126 -r A -c "height raised from 4.15m to 4.446m 10/31/19" --date 2019/11/18 --time 12:00:00
