#! /usr/bin/env bash
echo "191121_add_stations" >> scripts.log 
add_station.py HH213 --sernum 281 --date 2019/10/22 --time 10:00
add_part.py -p A213 -r H -t antenna -m S/N281 --date 2019/10/22 --time 10:00
add_connection.py -u HH213 --uprev A --upport ground -d A213 --dnrev H --dnport ground --date 2019/10/22 --time 10:00
add_station.py HH154 --sernum 282 --date 2019/11/4 --time 10:00
add_part.py -p A154 -r H -t antenna -m S/N282 --date 2019/11/4 --time 10:00
add_connection.py -u HH154 --uprev A --upport ground -d A154 --dnrev H --dnport ground --date 2019/11/4 --time 10:00
add_station.py HH175 --sernum 283 --date 2019/11/5 --time 10:00
add_part.py -p A175 -r H -t antenna -m S/N283 --date 2019/11/5 --time 10:00
add_connection.py -u HH175 --uprev A --upport ground -d A175 --dnrev H --dnport ground --date 2019/11/5 --time 10:00
add_station.py HH194 --sernum 286 --date 2019/11/7 --time 10:00
add_part.py -p A194 -r H -t antenna -m S/N286 --date 2019/11/7 --time 10:00
add_connection.py -u HH194 --uprev A --upport ground -d A194 --dnrev H --dnport ground --date 2019/11/7 --time 10:00
