#! /usr/bin/env bash
echo "../cm_updates/191101_overview_update_1438" >> scripts.log 
stop_connection.py -u PAM058 --uprev A --upport e -d SNPC000021 --dnrev A --dnport e10 --date 2019/11/01 --time 12:00:00
stop_connection.py -u PAM058 --uprev A --upport n -d SNPC000021 --dnrev A --dnport n8 --date 2019/11/01 --time 12:00:00
stop_connection.py -u PAM058 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot6 --date 2019/11/01 --time 12:00:00
stop_connection.py -u NBP07 --uprev A --upport e6 -d PAM058 --dnrev A --dnport e --date 2019/11/01 --time 12:00:00
stop_connection.py -u NBP07 --uprev A --upport n6 -d PAM058 --dnrev A --dnport n --date 2019/11/01 --time 12:00:00




stop_connection.py -u PAM055 --uprev A --upport e -d SNPC000019 --dnrev A --dnport e10 --date 2019/11/01 --time 12:00:00
stop_connection.py -u PAM055 --uprev A --upport n -d SNPC000019 --dnrev A --dnport n8 --date 2019/11/01 --time 12:00:00
stop_connection.py -u PAM055 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot3 --date 2019/11/01 --time 12:00:00
stop_connection.py -u NBP07 --uprev A --upport e3 -d PAM055 --dnrev A --dnport e --date 2019/11/01 --time 12:00:00
stop_connection.py -u NBP07 --uprev A --upport n3 -d PAM055 --dnrev A --dnport n --date 2019/11/01 --time 12:00:00



add_connection.py -u PAM055 --uprev A --upport e -d PAM058 --dnrev A --dnport e10 --date 2019/11/01 --time 12:00:00
add_connection.py -u PAM055 --uprev A --upport n -d PAM058 --dnrev A --dnport n8 --date 2019/11/01 --time 12:00:00
add_connection.py -u PAM055 --uprev A --upport @slot -d PAM058 --dnrev A --dnport @slot3 --date 2019/11/01 --time 12:00:00
add_connection.py -u PAM058 --uprev A --upport e3 -d PAM055 --dnrev A --dnport e --date 2019/11/01 --time 12:00:00
add_connection.py -u PAM058 --uprev A --upport n3 -d PAM055 --dnrev A --dnport n --date 2019/11/01 --time 12:00:00



stop_connection.py -u PAM055 --uprev A --upport e -d SNPC000019 --dnrev A --dnport e10 --date 2019/11/01 --time 12:00:00
stop_connection.py -u PAM055 --uprev A --upport n -d SNPC000019 --dnrev A --dnport n8 --date 2019/11/01 --time 12:00:00
stop_connection.py -u PAM055 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot3 --date 2019/11/01 --time 12:00:00
stop_connection.py -u NBP07 --uprev A --upport e3 -d PAM055 --dnrev A --dnport e --date 2019/11/01 --time 12:00:00
stop_connection.py -u NBP07 --uprev A --upport n3 -d PAM055 --dnrev A --dnport n --date 2019/11/01 --time 12:00:00
stop_connection.py -u PAM058 --uprev A --upport e -d SNPC000021 --dnrev A --dnport e10 --date 2019/11/01 --time 12:00:00
stop_connection.py -u PAM058 --uprev A --upport n -d SNPC000021 --dnrev A --dnport n8 --date 2019/11/01 --time 12:00:00
stop_connection.py -u PAM058 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot6 --date 2019/11/01 --time 12:00:00
stop_connection.py -u NBP07 --uprev A --upport e6 -d PAM058 --dnrev A --dnport e --date 2019/11/01 --time 12:00:00
stop_connection.py -u NBP07 --uprev A --upport n6 -d PAM058 --dnrev A --dnport n --date 2019/11/01 --time 12:00:00
add_connection.py -u PAM058 --uprev A --upport e -d PAM055 --dnrev A --dnport e10 --date 2019/11/01 --time 12:00:00
add_connection.py -u PAM058 --uprev A --upport n -d PAM055 --dnrev A --dnport n8 --date 2019/11/01 --time 12:00:00
add_connection.py -u PAM058 --uprev A --upport @slot -d PAM055 --dnrev A --dnport @slot6 --date 2019/11/01 --time 12:00:00
add_connection.py -u PAM055 --uprev A --upport e6 -d PAM058 --dnrev A --dnport e --date 2019/11/01 --time 12:00:00
add_connection.py -u PAM055 --uprev A --upport n6 -d PAM058 --dnrev A --dnport n --date 2019/11/01 --time 12:00:00
