#! /usr/bin/env bash
echo "191116_add_nodes_3_10" >> scripts.log 
add_station.py ND03 --sernum H0030-2601.2#7 --date 2019/11/13 --time 10:00
add_part.py -p FPS09 -r A -t fem-power-supply -m FPS09 --date 2019/11/13 --time 10:00
add_part.py -p PCH07 -r A -t pam-chassis -m PCH07 --date 2019/11/13 --time 10:00
add_part.py -p NCMPro5 -r A -t node-control-module -m NCMPro5 --date 2019/11/13 --time 10:00
add_part.py -p N03 -r A -t node -m H0030-2601.2#7 --date 2019/11/13 --time 10:00
add_part.py -p NBP03 -r A -t node-bulkhead -m H0030-2601.2#7 --date 2019/11/13 --time 10:00
add_part.py -p PAM125 -r A -t post-amp -m 125 --date 2019/11/13 --time 10:00
add_part.py -p PAM126 -r A -t post-amp -m 126 --date 2019/11/13 --time 10:00
add_part.py -p PAM127 -r A -t post-amp -m 127 --date 2019/11/13 --time 10:00
add_part.py -p PAM128 -r A -t post-amp -m 128 --date 2019/11/13 --time 10:00
add_part.py -p PAM129 -r A -t post-amp -m 129 --date 2019/11/13 --time 10:00
add_part.py -p PAM130 -r A -t post-amp -m 130 --date 2019/11/13 --time 10:00
add_part.py -p PAM131 -r A -t post-amp -m 131 --date 2019/11/13 --time 10:00
add_part.py -p PAM132 -r A -t post-amp -m 132 --date 2019/11/13 --time 10:00
add_part.py -p PAM133 -r A -t post-amp -m 133 --date 2019/11/13 --time 10:00
add_part.py -p PAM134 -r A -t post-amp -m 134 --date 2019/11/13 --time 10:00
add_part.py -p PAM135 -r A -t post-amp -m 135 --date 2019/11/13 --time 10:00
add_part.py -p PAM136 -r A -t post-amp -m 136 --date 2019/11/13 --time 10:00
add_part.py -p SNPC000001 -r A -t snap -m C000001 --date 2019/11/13 --time 10:00
add_part.py -p SNPC000002 -r A -t snap -m C000002 --date 2019/11/13 --time 10:00
add_part.py -p SNPC000037 -r A -t snap -m C000037 --date 2019/11/13 --time 10:00
add_part.py -p SNPC000054 -r A -t snap -m C000054 --date 2019/11/13 --time 10:00
add_connection.py -u N03 --uprev A --upport @ground -d ND03 --dnrev A --dnport @ground --date 2019/11/13 --time 11:00
add_connection.py -u FPS09 --uprev A --upport @rack -d N03 --dnrev A --dnport @top --date 2019/11/13 --time 11:00
add_connection.py -u PCH07 --uprev A --upport @rack -d N03 --dnrev A --dnport @bottom --date 2019/11/13 --time 11:00
add_connection.py -u NCMPro5 --uprev A --upport @rack -d N03 --dnrev A --dnport @middle --date 2019/11/13 --time 11:00
add_connection.py -u PAM125 --uprev A --upport @slot -d PCH07 --dnrev A --dnport @slot1 --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport e1 -d PAM125 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport n1 -d PAM125 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM126 --uprev A --upport @slot -d PCH07 --dnrev A --dnport @slot2 --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport e2 -d PAM126 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport n2 -d PAM126 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM127 --uprev A --upport @slot -d PCH07 --dnrev A --dnport @slot3 --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport e3 -d PAM127 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport n3 -d PAM127 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM128 --uprev A --upport @slot -d PCH07 --dnrev A --dnport @slot4 --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport e4 -d PAM128 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport n4 -d PAM128 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM129 --uprev A --upport @slot -d PCH07 --dnrev A --dnport @slot5 --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport e5 -d PAM129 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport n5 -d PAM129 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM130 --uprev A --upport @slot -d PCH07 --dnrev A --dnport @slot6 --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport e6 -d PAM130 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport n6 -d PAM130 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM131 --uprev A --upport @slot -d PCH07 --dnrev A --dnport @slot7 --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport e7 -d PAM131 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport n7 -d PAM131 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM132 --uprev A --upport @slot -d PCH07 --dnrev A --dnport @slot8 --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport e8 -d PAM132 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport n8 -d PAM132 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM133 --uprev A --upport @slot -d PCH07 --dnrev A --dnport @slot9 --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport e9 -d PAM133 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport n9 -d PAM133 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM134 --uprev A --upport @slot -d PCH07 --dnrev A --dnport @slot10 --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport e10 -d PAM134 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport n10 -d PAM134 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM135 --uprev A --upport @slot -d PCH07 --dnrev A --dnport @slot11 --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport e11 -d PAM135 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport n11 -d PAM135 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM136 --uprev A --upport @slot -d PCH07 --dnrev A --dnport @slot12 --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport e12 -d PAM136 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP03 --uprev A --upport n12 -d PAM136 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u SNPC000001 --uprev A --upport rack -d N03 --dnrev A --dnport loc0 --date 2019/11/13 --time 11:00
add_connection.py -u PAM125 --uprev A --upport e -d SNPC000001 --dnrev A --dnport e2 --date 2019/11/13 --time 11:00
add_connection.py -u PAM126 --uprev A --upport e -d SNPC000001 --dnrev A --dnport e6 --date 2019/11/13 --time 11:00
add_connection.py -u PAM127 --uprev A --upport e -d SNPC000001 --dnrev A --dnport e10 --date 2019/11/13 --time 11:00
add_connection.py -u PAM125 --uprev A --upport n -d SNPC000001 --dnrev A --dnport n0 --date 2019/11/13 --time 11:00
add_connection.py -u PAM126 --uprev A --upport n -d SNPC000001 --dnrev A --dnport n4 --date 2019/11/13 --time 11:00
add_connection.py -u PAM127 --uprev A --upport n -d SNPC000001 --dnrev A --dnport n8 --date 2019/11/13 --time 11:00
add_connection.py -u SNPC000002 --uprev A --upport rack -d N03 --dnrev A --dnport loc1 --date 2019/11/13 --time 11:00
add_connection.py -u PAM128 --uprev A --upport e -d SNPC000002 --dnrev A --dnport e2 --date 2019/11/13 --time 11:00
add_connection.py -u PAM129 --uprev A --upport e -d SNPC000002 --dnrev A --dnport e6 --date 2019/11/13 --time 11:00
add_connection.py -u PAM130 --uprev A --upport e -d SNPC000002 --dnrev A --dnport e10 --date 2019/11/13 --time 11:00
add_connection.py -u PAM128 --uprev A --upport n -d SNPC000002 --dnrev A --dnport n0 --date 2019/11/13 --time 11:00
add_connection.py -u PAM129 --uprev A --upport n -d SNPC000002 --dnrev A --dnport n4 --date 2019/11/13 --time 11:00
add_connection.py -u PAM130 --uprev A --upport n -d SNPC000002 --dnrev A --dnport n8 --date 2019/11/13 --time 11:00
add_connection.py -u SNPC000037 --uprev A --upport rack -d N03 --dnrev A --dnport loc2 --date 2019/11/13 --time 11:00
add_connection.py -u PAM131 --uprev A --upport e -d SNPC000037 --dnrev A --dnport e2 --date 2019/11/13 --time 11:00
add_connection.py -u PAM132 --uprev A --upport e -d SNPC000037 --dnrev A --dnport e6 --date 2019/11/13 --time 11:00
add_connection.py -u PAM133 --uprev A --upport e -d SNPC000037 --dnrev A --dnport e10 --date 2019/11/13 --time 11:00
add_connection.py -u PAM131 --uprev A --upport n -d SNPC000037 --dnrev A --dnport n0 --date 2019/11/13 --time 11:00
add_connection.py -u PAM132 --uprev A --upport n -d SNPC000037 --dnrev A --dnport n4 --date 2019/11/13 --time 11:00
add_connection.py -u PAM133 --uprev A --upport n -d SNPC000037 --dnrev A --dnport n8 --date 2019/11/13 --time 11:00
add_connection.py -u SNPC000054 --uprev A --upport rack -d N03 --dnrev A --dnport loc3 --date 2019/11/13 --time 11:00
add_connection.py -u PAM134 --uprev A --upport e -d SNPC000054 --dnrev A --dnport e2 --date 2019/11/13 --time 11:00
add_connection.py -u PAM135 --uprev A --upport e -d SNPC000054 --dnrev A --dnport e6 --date 2019/11/13 --time 11:00
add_connection.py -u PAM136 --uprev A --upport e -d SNPC000054 --dnrev A --dnport e10 --date 2019/11/13 --time 11:00
add_connection.py -u PAM134 --uprev A --upport n -d SNPC000054 --dnrev A --dnport n0 --date 2019/11/13 --time 11:00
add_connection.py -u PAM135 --uprev A --upport n -d SNPC000054 --dnrev A --dnport n4 --date 2019/11/13 --time 11:00
add_connection.py -u PAM136 --uprev A --upport n -d SNPC000054 --dnrev A --dnport n8 --date 2019/11/13 --time 11:00
add_station.py ND10 --sernum H0030-2601.2#6 --date 2019/11/13 --time 10:00
add_part.py -p FPS08 -r A -t fem-power-supply -m FPS08 --date 2019/11/13 --time 10:00
add_part.py -p PCH08 -r A -t pam-chassis -m PCH08 --date 2019/11/13 --time 10:00
add_part.py -p NCMPro6 -r A -t node-control-module -m NCMPro6 --date 2019/11/13 --time 10:00
add_part.py -p N10 -r A -t node -m H0030-2601.2#6 --date 2019/11/13 --time 10:00
add_part.py -p NBP10 -r A -t node-bulkhead -m H0030-2601.2#6 --date 2019/11/13 --time 10:00
add_part.py -p PAM137 -r A -t post-amp -m 137 --date 2019/11/13 --time 10:00
add_part.py -p PAM138 -r A -t post-amp -m 138 --date 2019/11/13 --time 10:00
add_part.py -p PAM139 -r A -t post-amp -m 139 --date 2019/11/13 --time 10:00
add_part.py -p PAM140 -r A -t post-amp -m 140 --date 2019/11/13 --time 10:00
add_part.py -p PAM141 -r A -t post-amp -m 141 --date 2019/11/13 --time 10:00
add_part.py -p PAM142 -r A -t post-amp -m 142 --date 2019/11/13 --time 10:00
add_part.py -p PAM143 -r A -t post-amp -m 143 --date 2019/11/13 --time 10:00
add_part.py -p PAM144 -r A -t post-amp -m 144 --date 2019/11/13 --time 10:00
add_part.py -p PAM145 -r A -t post-amp -m 145 --date 2019/11/13 --time 10:00
add_part.py -p PAM146 -r A -t post-amp -m 146 --date 2019/11/13 --time 10:00
add_part.py -p PAM147 -r A -t post-amp -m 147 --date 2019/11/13 --time 10:00
add_part.py -p PAM148 -r A -t post-amp -m 148 --date 2019/11/13 --time 10:00
add_part.py -p SNPC000014 -r A -t snap -m C000014 --date 2019/11/13 --time 10:00
add_part.py -p SNPC000016 -r A -t snap -m C000016 --date 2019/11/13 --time 10:00
add_part.py -p SNPC000042 -r A -t snap -m C000042 --date 2019/11/13 --time 10:00
add_part.py -p SNPC000045 -r A -t snap -m C000045 --date 2019/11/13 --time 10:00
add_connection.py -u N10 --uprev A --upport @ground -d ND10 --dnrev A --dnport @ground --date 2019/11/13 --time 11:00
add_connection.py -u FPS08 --uprev A --upport @rack -d N10 --dnrev A --dnport @top --date 2019/11/13 --time 11:00
add_connection.py -u PCH08 --uprev A --upport @rack -d N10 --dnrev A --dnport @bottom --date 2019/11/13 --time 11:00
add_connection.py -u NCMPro6 --uprev A --upport @rack -d N10 --dnrev A --dnport @middle --date 2019/11/13 --time 11:00
add_connection.py -u PAM137 --uprev A --upport @slot -d PCH08 --dnrev A --dnport @slot1 --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport e1 -d PAM137 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport n1 -d PAM137 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM138 --uprev A --upport @slot -d PCH08 --dnrev A --dnport @slot2 --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport e2 -d PAM138 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport n2 -d PAM138 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM139 --uprev A --upport @slot -d PCH08 --dnrev A --dnport @slot3 --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport e3 -d PAM139 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport n3 -d PAM139 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM140 --uprev A --upport @slot -d PCH08 --dnrev A --dnport @slot4 --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport e4 -d PAM140 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport n4 -d PAM140 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM141 --uprev A --upport @slot -d PCH08 --dnrev A --dnport @slot5 --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport e5 -d PAM141 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport n5 -d PAM141 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM142 --uprev A --upport @slot -d PCH08 --dnrev A --dnport @slot6 --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport e6 -d PAM142 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport n6 -d PAM142 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM143 --uprev A --upport @slot -d PCH08 --dnrev A --dnport @slot7 --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport e7 -d PAM143 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport n7 -d PAM143 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM144 --uprev A --upport @slot -d PCH08 --dnrev A --dnport @slot8 --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport e8 -d PAM144 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport n8 -d PAM144 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM145 --uprev A --upport @slot -d PCH08 --dnrev A --dnport @slot9 --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport e9 -d PAM145 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport n9 -d PAM145 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM146 --uprev A --upport @slot -d PCH08 --dnrev A --dnport @slot10 --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport e10 -d PAM146 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport n10 -d PAM146 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM147 --uprev A --upport @slot -d PCH08 --dnrev A --dnport @slot11 --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport e11 -d PAM147 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport n11 -d PAM147 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u PAM148 --uprev A --upport @slot -d PCH08 --dnrev A --dnport @slot12 --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport e12 -d PAM148 --dnrev A --dnport e --date 2019/11/13 --time 11:00
add_connection.py -u NBP10 --uprev A --upport n12 -d PAM148 --dnrev A --dnport n --date 2019/11/13 --time 11:00
add_connection.py -u SNPC000014 --uprev A --upport rack -d N10 --dnrev A --dnport loc0 --date 2019/11/13 --time 11:00
add_connection.py -u PAM137 --uprev A --upport e -d SNPC000014 --dnrev A --dnport e2 --date 2019/11/13 --time 11:00
add_connection.py -u PAM138 --uprev A --upport e -d SNPC000014 --dnrev A --dnport e6 --date 2019/11/13 --time 11:00
add_connection.py -u PAM139 --uprev A --upport e -d SNPC000014 --dnrev A --dnport e10 --date 2019/11/13 --time 11:00
add_connection.py -u PAM137 --uprev A --upport n -d SNPC000014 --dnrev A --dnport n0 --date 2019/11/13 --time 11:00
add_connection.py -u PAM138 --uprev A --upport n -d SNPC000014 --dnrev A --dnport n4 --date 2019/11/13 --time 11:00
add_connection.py -u PAM139 --uprev A --upport n -d SNPC000014 --dnrev A --dnport n8 --date 2019/11/13 --time 11:00
add_connection.py -u SNPC000016 --uprev A --upport rack -d N10 --dnrev A --dnport loc1 --date 2019/11/13 --time 11:00
add_connection.py -u PAM140 --uprev A --upport e -d SNPC000016 --dnrev A --dnport e2 --date 2019/11/13 --time 11:00
add_connection.py -u PAM141 --uprev A --upport e -d SNPC000016 --dnrev A --dnport e6 --date 2019/11/13 --time 11:00
add_connection.py -u PAM142 --uprev A --upport e -d SNPC000016 --dnrev A --dnport e10 --date 2019/11/13 --time 11:00
add_connection.py -u PAM140 --uprev A --upport n -d SNPC000016 --dnrev A --dnport n0 --date 2019/11/13 --time 11:00
add_connection.py -u PAM141 --uprev A --upport n -d SNPC000016 --dnrev A --dnport n4 --date 2019/11/13 --time 11:00
add_connection.py -u PAM142 --uprev A --upport n -d SNPC000016 --dnrev A --dnport n8 --date 2019/11/13 --time 11:00
add_connection.py -u SNPC000042 --uprev A --upport rack -d N10 --dnrev A --dnport loc2 --date 2019/11/13 --time 11:00
add_connection.py -u PAM143 --uprev A --upport e -d SNPC000042 --dnrev A --dnport e2 --date 2019/11/13 --time 11:00
add_connection.py -u PAM144 --uprev A --upport e -d SNPC000042 --dnrev A --dnport e6 --date 2019/11/13 --time 11:00
add_connection.py -u PAM145 --uprev A --upport e -d SNPC000042 --dnrev A --dnport e10 --date 2019/11/13 --time 11:00
add_connection.py -u PAM143 --uprev A --upport n -d SNPC000042 --dnrev A --dnport n0 --date 2019/11/13 --time 11:00
add_connection.py -u PAM144 --uprev A --upport n -d SNPC000042 --dnrev A --dnport n4 --date 2019/11/13 --time 11:00
add_connection.py -u PAM145 --uprev A --upport n -d SNPC000042 --dnrev A --dnport n8 --date 2019/11/13 --time 11:00
add_connection.py -u SNPC000045 --uprev A --upport rack -d N10 --dnrev A --dnport loc3 --date 2019/11/13 --time 11:00
add_connection.py -u PAM146 --uprev A --upport e -d SNPC000045 --dnrev A --dnport e2 --date 2019/11/13 --time 11:00
add_connection.py -u PAM147 --uprev A --upport e -d SNPC000045 --dnrev A --dnport e6 --date 2019/11/13 --time 11:00
add_connection.py -u PAM148 --uprev A --upport e -d SNPC000045 --dnrev A --dnport e10 --date 2019/11/13 --time 11:00
add_connection.py -u PAM146 --uprev A --upport n -d SNPC000045 --dnrev A --dnport n0 --date 2019/11/13 --time 11:00
add_connection.py -u PAM147 --uprev A --upport n -d SNPC000045 --dnrev A --dnport n4 --date 2019/11/13 --time 11:00
add_connection.py -u PAM148 --uprev A --upport n -d SNPC000045 --dnrev A --dnport n8 --date 2019/11/13 --time 11:00
