#! /bin/bash
source ~/.bashrc
echo "200916_infoupd_0142" >> scripts.log 
update_apriori.py -p HH3 -s RF_maintenance --date 2020/09/16 --time 01:42
update_apriori.py -p HH4 -s RF_ok --date 2020/09/16 --time 01:42
update_apriori.py -p HH5 -s RF_maintenance --date 2020/09/16 --time 01:42
update_apriori.py -p HH6 -s RF_maintenance --date 2020/09/16 --time 01:42
update_apriori.py -p HH15 -s RF_maintenance --date 2020/09/16 --time 01:42
update_apriori.py -p HH16 -s RF_maintenance --date 2020/09/16 --time 01:42
update_apriori.py -p HH17 -s RF_maintenance --date 2020/09/16 --time 01:42
update_apriori.py -p HH18 -s RF_maintenance --date 2020/09/16 --time 01:42
update_apriori.py -p HH27 -s RF_maintenance --date 2020/09/16 --time 01:42
update_apriori.py -p HH28 -s RF_maintenance --date 2020/09/16 --time 01:42
update_apriori.py -p HH29 -s RF_maintenance --date 2020/09/16 --time 01:42
update_apriori.py -p HH30 -s RF_maintenance --date 2020/09/16 --time 01:42
add_part_info.py -p HH28 -r A -c 'Feed heights (NE/SE/SW/NW): Z = 4.402' -l "apa-infoupd" --date 2020/09/16 --time 01:42:00
add_part_info.py -p HH29 -r A -c 'Feed heights (NE/SE/SW/NW): Z = 4.403' -l "apa-infoupd" --date 2020/09/16 --time 01:42:00
add_part_info.py -p HH6 -r A -c 'cable too short to reach Node ' -l "apa-infoupd" --date 2020/09/16 --time 01:42:00
add_part_info.py -p HH3 -r A -c 'Feed heights (NE/SE/SW/NW): Z = 4.406' -l "apa-infoupd" --date 2020/09/16 --time 01:42:00
add_part_info.py -p HH4 -r A -c 'Feed heights (NE/SE/SW/NW): Z = 4.414' -l "apa-infoupd" --date 2020/09/16 --time 01:42:00
add_part_info.py -p HH15 -r A -c 'Feed heights (NE/SE/SW/NW): Z = 4.410' -l "apa-infoupd" --date 2020/09/16 --time 01:42:00
