#! /bin/bash
source ~/.bashrc
echo "200910_infoupd_2042" >> scripts.log 
update_apriori.py -p HH91 -s RF_ok --date 2020/09/10 --time 20:42
update_apriori.py -p HH92 -s RF_maintenance --date 2020/09/10 --time 20:42
update_apriori.py -p HH93 -s RF_maintenance --date 2020/09/10 --time 20:42
update_apriori.py -p HH94 -s RF_maintenance --date 2020/09/10 --time 20:42
update_apriori.py -p HH105 -s RF_ok --date 2020/09/10 --time 20:42
update_apriori.py -p HH108 -s RF_maintenance --date 2020/09/10 --time 20:42
update_apriori.py -p HH124 -s RF_ok --date 2020/09/10 --time 20:42
update_apriori.py -p HH128 -s RF_ok --date 2020/09/10 --time 20:42
update_apriori.py -p HH129 -s RF_maintenance --date 2020/09/10 --time 20:42
add_part_info.py -p HH92 -r A -c 'Not seeing sky in 59100 notebook' -l "apa-infoupd" --date 2020/09/10 --time 20:42:00
add_part_info.py -p HH92 -r A -c 'Not seeing sky in 59100 notebook' -l "apa-infoupd" --date 2020/09/10 --time 20:42:02
add_part_info.py -p HH93 -r A -c 'Not seeing sky in 59100 notebook' -l "apa-infoupd" --date 2020/09/10 --time 20:42:00
add_part_info.py -p HH93 -r A -c 'Not seeing sky in 59100 notebook' -l "apa-infoupd" --date 2020/09/10 --time 20:42:02
add_part_info.py -p HH94 -r A -c 'Not seeing sky in 59100 notebook' -l "apa-infoupd" --date 2020/09/10 --time 20:42:00
add_part_info.py -p HH94 -r A -c 'Not seeing sky in 59100 notebook' -l "apa-infoupd" --date 2020/09/10 --time 20:42:02
add_part_info.py -p HH128 -r A -c 'Looks fine in 59100 notebook' -l "apa-infoupd" --date 2020/09/10 --time 20:42:00
add_part_info.py -p HH128 -r A -c 'Looks fine in 59100 notebook' -l "apa-infoupd" --date 2020/09/10 --time 20:42:02
add_part_info.py -p HH129 -r A -c 'See nice autos in 59100 notebook, but no z height' -l "apa-infoupd" --date 2020/09/10 --time 20:42:00
add_part_info.py -p HH129 -r A -c 'See nice autos in 59100 notebook, but no z height' -l "apa-infoupd" --date 2020/09/10 --time 20:42:02
add_part_info.py -p HH108 -r A -c 'nice autos in the 49100 notebook, but in heranow 10Sept2221 Sitetime it looks like 108 is not seeing sky' -l "apa-infoupd" --date 2020/09/10 --time 20:42:00
add_part_info.py -p HH108 -r A -c 'nice autos in the 49100 notebook, but in heranow 10Sept2221 Sitetime it looks like 108 is not seeing sky' -l "apa-infoupd" --date 2020/09/10 --time 20:42:02
