#! /bin/bash
source ~/.bashrc
echo "200910_infoupd_2342" >> scripts.log 
update_apriori.py -p HH46 -s RF_maintenance --date 2020/09/10 --time 23:42
update_apriori.py -p HH58 -s RF_maintenance --date 2020/09/10 --time 23:42
update_apriori.py -p HH59 -s RF_maintenance --date 2020/09/10 --time 23:42
add_part_info.py -p HH46 -r A -c 'bad auto in 59103 live autos; FEM in ant' -l "apa-infoupd" --date 2020/09/10 --time 23:42:00
add_part_info.py -p HH46 -r A -c 'bad auto in 59103 live autos; FEM in ant' -l "apa-infoupd" --date 2020/09/10 --time 23:42:02
add_part_info.py -p HH58 -r A -c 'bad auto in 59103 live autos; FEM in ant' -l "apa-infoupd" --date 2020/09/10 --time 23:42:00
add_part_info.py -p HH58 -r A -c 'bad auto in 59103 live autos; FEM in ant' -l "apa-infoupd" --date 2020/09/10 --time 23:42:02
add_part_info.py -p HH59 -r A -c 'bad auto in 59103 live autos; FEM in ant' -l "apa-infoupd" --date 2020/09/10 --time 23:42:00
add_part_info.py -p HH59 -r A -c 'bad auto in 59103 live autos; FEM in ant' -l "apa-infoupd" --date 2020/09/10 --time 23:42:02
