#! /bin/bash
source ~/.bashrc
echo "200910_infoupd_1942" >> scripts.log 
update_apriori.py -p HH136 -s RF_ok --date 2020/09/10 --time 19:42
update_apriori.py -p HH156 -s RF_maintenance --date 2020/09/10 --time 19:42
update_apriori.py -p HH157 -s RF_maintenance --date 2020/09/10 --time 19:42
add_part_info.py -p HH135 -r A -c 'SNAP specta not OK 10 sept' -l "infoupd" --date 2020/09/10 --time 19:42:00
add_part_info.py -p HH135 -r A -c 'SNAP specta not OK 10 sept' -l "infoupd" --date 2020/09/10 --time 19:42:02
add_part_info.py -p HH136 -r A -c 'SNAP specta OK 10 sept' -l "apa-infoupd" --date 2020/09/10 --time 19:42:00
add_part_info.py -p HH136 -r A -c 'SNAP specta OK 10 sept' -l "apa-infoupd" --date 2020/09/10 --time 19:42:02
