#! /bin/bash
source ~/.bashrc
echo "200910_infoupd_1442" >> scripts.log 
update_apriori.py -p HH141 -s RF_ok --date 2020/09/10 --time 14:42
update_apriori.py -p HH162 -s RF_maintenance --date 2020/09/10 --time 14:42
update_apriori.py -p HH176 -s RF_ok --date 2020/09/10 --time 14:42
update_apriori.py -p HH181 -s RF_maintenance --date 2020/09/10 --time 14:42
update_apriori.py -p HH182 -s RF_maintenance --date 2020/09/10 --time 14:42
add_part_info.py -p HH176 -r A -c 'SNAP specta OK 10 sept' -l "apa-infoupd" --date 2020/09/10 --time 14:42:00
add_part_info.py -p HH176 -r A -c 'SNAP specta OK 10 sept' -l "apa-infoupd" --date 2020/09/10 --time 14:42:02
