#! /bin/bash
echo "./201002_add_rd.py" >> scripts.log 
add_part.py -p RD05 -r A -t arduino -m RD05 --date 2020/03/01 --time 10:00
add_part.py -p NCM21 -r A -t node-control-module -m NCM-Pro21 --date 2020/03/01 --time 10:00
add_connection.py -u RD05 --uprev A --upport mnt -d NCM21 --dnrev A --dnport mnt2 --date 2020/03/01 --time 11:00
add_part.py -p RD09 -r A -t arduino -m RD09 --date 2020/03/01 --time 10:00
add_part.py -p NCM22 -r A -t node-control-module -m NCM-Pro22 --date 2020/03/01 --time 10:00
add_connection.py -u RD09 --uprev A --upport mnt -d NCM22 --dnrev A --dnport mnt2 --date 2020/03/01 --time 11:00
add_part.py -p RD13 -r A -t arduino -m RD13 --date 2020/03/01 --time 10:00
add_part.py -p NCM14 -r A -t node-control-module -m NCM-Pro14 --date 2020/03/01 --time 10:00
add_connection.py -u RD13 --uprev A --upport mnt -d NCM14 --dnrev A --dnport mnt2 --date 2020/03/01 --time 11:00
add_part.py -p RD14 -r A -t arduino -m RD14 --date 2020/03/01 --time 10:00
add_part.py -p NCM20 -r A -t node-control-module -m NCM-Pro20 --date 2020/03/01 --time 10:00
add_connection.py -u RD14 --uprev A --upport mnt -d NCM20 --dnrev A --dnport mnt2 --date 2020/03/01 --time 11:00
add_part.py -p RD16 -r A -t arduino -m RD16 --date 2020/03/01 --time 10:00
add_part.py -p NCM18 -r A -t node-control-module -m NCM-Pro18 --date 2020/03/01 --time 10:00
add_connection.py -u RD16 --uprev A --upport mnt -d NCM18 --dnrev A --dnport mnt2 --date 2020/03/01 --time 11:00
add_part.py -p RD47 -r A -t arduino -m RD47 --date 2020/03/01 --time 10:00
add_part.py -p NCM17 -r A -t node-control-module -m NCM-Pro17 --date 2020/03/01 --time 10:00
add_connection.py -u RD47 --uprev A --upport mnt -d NCM17 --dnrev A --dnport mnt2 --date 2020/03/01 --time 11:00
add_part.py -p RD48 -r A -t arduino -m RD48 --date 2020/03/01 --time 10:00
add_part.py -p NCM19 -r A -t node-control-module -m NCM-Pro19 --date 2020/03/01 --time 10:00
add_connection.py -u RD48 --uprev A --upport mnt -d NCM19 --dnrev A --dnport mnt2 --date 2020/03/01 --time 11:00
