#! /bin/bash
echo "./210212_add_wr.py" >> scripts.log 
add_part.py -p WRA000157 -r A -t white-rabbit -m S10.486 --date 2020/03/01 --time 10:00
add_part.py -p NCM23 -r A -t node-control-module -m NCM-Pro23 --date 2021/02/01 --time 10:00
add_connection.py -u WRA000157 --uprev A --upport mnt -d NCM23 --dnrev A --dnport mnt1 --date 2021/02/01 --time 11:00
add_part_info.py -p WRA000157 -r A -c 'MAC - 08:00:30:6e:b8:f5' --date 2021/02/01 --time 11:00
add_part.py -p WRA000099 -r A -t white-rabbit -m S10.495 --date 2020/03/01 --time 10:00
add_part.py -p NCM24 -r A -t node-control-module -m NCM-Pro24 --date 2021/02/01 --time 10:00
add_connection.py -u WRA000099 --uprev A --upport mnt -d NCM24 --dnrev A --dnport mnt1 --date 2021/02/01 --time 11:00
add_part_info.py -p WRA000099 -r A -c 'MAC - 08:00:30:6e:a7:8b' --date 2021/02/01 --time 11:00
add_part.py -p WRA000098 -r A -t white-rabbit -m S10.490 --date 2020/03/01 --time 10:00
add_part.py -p NCM25 -r A -t node-control-module -m NCM-Pro25 --date 2021/02/01 --time 10:00
add_connection.py -u WRA000098 --uprev A --upport mnt -d NCM25 --dnrev A --dnport mnt1 --date 2021/02/01 --time 11:00
add_part_info.py -p WRA000098 -r A -c 'MAC - 08:00:30:6e:cd:a4' --date 2021/02/01 --time 11:00
add_part.py -p WRA000088 -r A -t white-rabbit -m S9.393 --date 2020/03/01 --time 10:00
add_part.py -p NCM26 -r A -t node-control-module -m NCM-Pro26 --date 2021/02/01 --time 10:00
add_connection.py -u WRA000088 --uprev A --upport mnt -d NCM26 --dnrev A --dnport mnt1 --date 2021/02/01 --time 11:00
add_part_info.py -p WRA000088 -r A -c 'MAC - 08:00:30:b2:55:30' --date 2021/02/01 --time 11:00
add_part.py -p WRA000155 -r A -t white-rabbit -m S10.475 --date 2020/03/01 --time 10:00
add_part.py -p NCM27 -r A -t node-control-module -m NCM-Pro27 --date 2021/02/01 --time 10:00
add_connection.py -u WRA000155 --uprev A --upport mnt -d NCM27 --dnrev A --dnport mnt1 --date 2021/02/01 --time 11:00
add_part_info.py -p WRA000155 -r A -c 'MAC - 08:00:30:6e:6c:bc' --date 2021/02/01 --time 11:00
add_part.py -p WRA000156 -r A -t white-rabbit -m S10.474 --date 2020/03/01 --time 10:00
add_part.py -p NCM18 -r A -t node-control-module -m NCM-Pro18 --date 2021/02/01 --time 10:00
add_connection.py -u WRA000156 --uprev A --upport mnt -d NCM18 --dnrev A --dnport mnt1 --date 2021/02/01 --time 11:00
add_part_info.py -p WRA000156 -r A -c 'MAC - 08:00:30:6e:6e:f0' --date 2021/02/01 --time 11:00
add_part.py -p WRA000100 -r A -t white-rabbit -m S10.483 --date 2020/03/01 --time 10:00
add_part.py -p NCM19 -r A -t node-control-module -m NCM-Pro19 --date 2021/02/01 --time 10:00
add_connection.py -u WRA000100 --uprev A --upport mnt -d NCM19 --dnrev A --dnport mnt1 --date 2021/02/01 --time 11:00
add_part_info.py -p WRA000100 -r A -c 'MAC - 08:00:30:6e:7d:ca' --date 2021/02/01 --time 11:00
add_part.py -p WRA000158 -r A -t white-rabbit -m S10.487 --date 2020/03/01 --time 10:00
add_part.py -p NCM30 -r A -t node-control-module -m NCM-Pro30 --date 2021/02/01 --time 10:00
add_connection.py -u WRA000158 --uprev A --upport mnt -d NCM30 --dnrev A --dnport mnt1 --date 2021/02/01 --time 11:00
add_part_info.py -p WRA000158 -r A -c 'MAC - 08:00:30:6e:b8:fa' --date 2021/02/01 --time 11:00
add_part.py -p WRA000095 -r A -t white-rabbit -m S10.488 --date 2020/03/01 --time 10:00
add_part.py -p NCM31 -r A -t node-control-module -m NCM-Pro31 --date 2021/02/01 --time 10:00
add_connection.py -u WRA000095 --uprev A --upport mnt -d NCM31 --dnrev A --dnport mnt1 --date 2021/02/01 --time 11:00
add_part_info.py -p WRA000095 -r A -c 'MAC - 08:00:30:6e:b9:75' --date 2021/02/01 --time 11:00
