#! /bin/bash
source ~/.bashrc
echo "211015_infoupd_0942" >> scripts.log 
add_part_info.py -p HH36 -r A -c 'Spectra: n3p1E' -l "infoupd" --date 2021/10/15 --time 09:42:00
add_part_info.py -p HH36 -r A -c 'Spectra: N3P1N' -l "infoupd" --date 2021/10/15 --time 09:42:02
add_part_info.py -p HH37 -r A -c 'Spectra: N3P2E' -l "infoupd" --date 2021/10/15 --time 09:42:00
add_part_info.py -p HH37 -r A -c 'Spectra: N3P2N' -l "infoupd" --date 2021/10/15 --time 09:42:02
add_part_info.py -p HH38 -r A -c 'Spectra: N3P3E' -l "infoupd" --date 2021/10/15 --time 09:42:00
add_part_info.py -p HH38 -r A -c 'Spectra: N3P3N' -l "infoupd" --date 2021/10/15 --time 09:42:02
