#! /bin/bash
echo "./211014_add_built_ants.py" >> scripts.log 
add_station.py HA331 --sernum 333 --date 2021/09/27 --time 10:00
add_part.py -p A331 -r H -t antenna -m H333 --date 2021/09/27 --time 10:00
add_connection.py -u HA331 --uprev A --upport ground -d A331 --dnrev H --dnport ground --date 2021/09/27 --time 10:00
add_station.py HB332 --sernum 334 --date 2021/09/23 --time 10:00
add_part.py -p A332 -r H -t antenna -m H334 --date 2021/09/23 --time 10:00
add_connection.py -u HB332 --uprev A --upport ground -d A332 --dnrev H --dnport ground --date 2021/09/23 --time 10:00
add_station.py HA335 --sernum 335 --date 2021/09/23 --time 10:00
add_part.py -p A335 -r H -t antenna -m H335 --date 2021/09/23 --time 10:00
add_connection.py -u HA335 --uprev A --upport ground -d A335 --dnrev H --dnport ground --date 2021/09/23 --time 10:00
add_station.py HB336 --sernum 336 --date 2021/09/29 --time 10:00
add_part.py -p A336 -r H -t antenna -m H336 --date 2021/09/29 --time 10:00
add_connection.py -u HB336 --uprev A --upport ground -d A336 --dnrev H --dnport ground --date 2021/09/29 --time 10:00
add_station.py HA339 --sernum 337 --date 2021/09/28 --time 10:00
add_part.py -p A339 -r H -t antenna -m H337 --date 2021/09/28 --time 10:00
add_connection.py -u HA339 --uprev A --upport ground -d A339 --dnrev H --dnport ground --date 2021/09/28 --time 10:00
add_station.py HB340 --sernum 338 --date 2021/09/27 --time 10:00
add_part.py -p A340 -r H -t antenna -m H338 --date 2021/09/27 --time 10:00
add_connection.py -u HB340 --uprev A --upport ground -d A340 --dnrev H --dnport ground --date 2021/09/27 --time 10:00
