#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220215_infoupd_1142" >> scripts.log 
add_part_info.py -p HH210 -r A -c 'Door closed 9/2/22' -l "infoupd" --date 2022/02/15 --time 11:42:00
add_part_info.py -p HH210 -r A -c 'Spectre: N20P9E' -l "infoupd" --date 2022/02/15 --time 11:42:02
add_part_info.py -p HH210 -r A -c 'Spectre: N20P9N' -l "infoupd" --date 2022/02/15 --time 11:42:04
