#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220308_infoupd_1542" >> scripts.log 
add_part_info.py -p N04 -r A -c 'WR endpoint is not functioning properly (works as a switch, but not for timing) -- swapped it (NCM4) with the one in node 21 (NCM21), plastic detatched and inside of node very dusty, temperature sensor 1 has broken plastic coating (not a big deal), bottom temperature sensor has no data' -l "infoupd" --date 2022/03/08 --time 15:42:00
