#! /bin/bash
echo "/Users/ddeboer/Documents/ubase/Projects/HERA/ops/hera_cm_db_updates/220617_connupd_1303" >> scripts.log 
# Stopping missing connections
stop_connection.py -u NBP18 --uprev A --upport n4 -d PAM236 --dnrev A --dnport n --date 2022/06/17 --time 13:03
stop_connection.py -u NBP18 --uprev A --upport e4 -d PAM236 --dnrev A --dnport e --date 2022/06/17 --time 13:03
stop_connection.py -u NBP20 --uprev A --upport e9 -d PAM265 --dnrev A --dnport e --date 2022/06/17 --time 13:03
stop_connection.py -u NBP20 --uprev A --upport n9 -d PAM265 --dnrev A --dnport n --date 2022/06/17 --time 13:03
stop_connection.py -u FEM044 --uprev A --upport pwr -d FPS02 --dnrev A --dnport pwr9 --date 2022/06/17 --time 13:03
stop_connection.py -u FEM030 --uprev A --upport pwr -d FPS02 --dnrev A --dnport pwr10 --date 2022/06/17 --time 13:03
stop_connection.py -u FEM031 --uprev A --upport pwr -d FPS02 --dnrev A --dnport pwr1 --date 2022/06/17 --time 13:03
stop_connection.py -u FEM032 --uprev A --upport pwr -d FPS02 --dnrev A --dnport pwr8 --date 2022/06/17 --time 13:03
stop_connection.py -u FEM029 --uprev A --upport pwr -d FPS02 --dnrev A --dnport pwr12 --date 2022/06/17 --time 13:03
stop_connection.py -u FEM028 --uprev A --upport pwr -d FPS02 --dnrev A --dnport pwr11 --date 2022/06/17 --time 13:03
stop_connection.py -u NBP19 --uprev A --upport e1 -d PAM221 --dnrev A --dnport e --date 2022/06/17 --time 13:03
stop_connection.py -u NBP19 --uprev A --upport n1 -d PAM221 --dnrev A --dnport n --date 2022/06/17 --time 13:03
stop_connection.py -u NBP16 --uprev A --upport e11 -d PAM291 --dnrev A --dnport e --date 2022/06/17 --time 13:03
stop_connection.py -u NBP16 --uprev A --upport n11 -d PAM291 --dnrev A --dnport n --date 2022/06/17 --time 13:03
stop_connection.py -u NBP11 --uprev A --upport e3 -d PAM247 --dnrev A --dnport e --date 2022/06/17 --time 13:03
stop_connection.py -u NBP11 --uprev A --upport n3 -d PAM247 --dnrev A --dnport n --date 2022/06/17 --time 13:03
stop_connection.py -u NBP11 --uprev A --upport e4 -d PAM248 --dnrev A --dnport e --date 2022/06/17 --time 13:03
stop_connection.py -u NBP11 --uprev A --upport n4 -d PAM248 --dnrev A --dnport n --date 2022/06/17 --time 13:03
stop_connection.py -u NBP11 --uprev A --upport e5 -d PAM249 --dnrev A --dnport e --date 2022/06/17 --time 13:03
stop_connection.py -u NBP11 --uprev A --upport n5 -d PAM249 --dnrev A --dnport n --date 2022/06/17 --time 13:03
stop_connection.py -u NBP11 --uprev A --upport e7 -d PAM251 --dnrev A --dnport e --date 2022/06/17 --time 13:03
stop_connection.py -u NBP11 --uprev A --upport n7 -d PAM251 --dnrev A --dnport n --date 2022/06/17 --time 13:03
stop_connection.py -u NBP16 --uprev A --upport e3 -d PAM283 --dnrev A --dnport e --date 2022/06/17 --time 13:03
stop_connection.py -u NBP16 --uprev A --upport n3 -d PAM283 --dnrev A --dnport n --date 2022/06/17 --time 13:03
stop_connection.py -u NBP16 --uprev A --upport e4 -d PAM284 --dnrev A --dnport e --date 2022/06/17 --time 13:03
stop_connection.py -u NBP16 --uprev A --upport n4 -d PAM284 --dnrev A --dnport n --date 2022/06/17 --time 13:03
stop_connection.py -u NBP20 --uprev A --upport e6 -d PAM262 --dnrev A --dnport e --date 2022/06/17 --time 13:03
stop_connection.py -u NBP20 --uprev A --upport n6 -d PAM262 --dnrev A --dnport n --date 2022/06/17 --time 13:03
stop_connection.py -u NBP20 --uprev A --upport e7 -d PAM263 --dnrev A --dnport e --date 2022/06/17 --time 13:03
stop_connection.py -u NBP20 --uprev A --upport n7 -d PAM263 --dnrev A --dnport n --date 2022/06/17 --time 13:03
stop_connection.py -u NBP20 --uprev A --upport e8 -d PAM264 --dnrev A --dnport e --date 2022/06/17 --time 13:03
stop_connection.py -u NBP20 --uprev A --upport n8 -d PAM264 --dnrev A --dnport n --date 2022/06/17 --time 13:03
