#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220602_infoupd_2138" >> scripts.log 
update_apriori.py -p HB320 -s dish_maintenance --date 2022/06/02 --time 21:40
add_part_info.py -p HB320 -r A -c 'apriori_antenna status change: not_connected > dish_maintenance' -l "apa-infoupd" --date 2022/06/02 --time 21:40
update_apriori.py -p HB322 -s RF_maintenance --date 2022/06/02 --time 21:40
add_part_info.py -p HB322 -r A -c 'apriori_antenna status change: not_connected > RF_maintenance' -l "apa-infoupd" --date 2022/06/02 --time 21:40
update_apriori.py -p HA325 -s dish_ok --date 2022/06/02 --time 21:40
add_part_info.py -p HA325 -r A -c 'apriori_antenna status change: not_connected > dish_ok' -l "apa-infoupd" --date 2022/06/02 --time 21:40
update_apriori.py -p HB329 -s dish_maintenance --date 2022/06/02 --time 21:40
add_part_info.py -p HB329 -r A -c 'apriori_antenna status change: not_connected > dish_maintenance' -l "apa-infoupd" --date 2022/06/02 --time 21:40
update_apriori.py -p HB333 -s dish_maintenance --date 2022/06/02 --time 21:40
add_part_info.py -p HB333 -r A -c 'apriori_antenna status change: not_connected > dish_maintenance' -l "apa-infoupd" --date 2022/06/02 --time 21:40
add_part_info.py -p HB329 -r A -c 'For outrigger' -l "apa-infoupd" --date 2022/06/02 --time 21:38:00
add_part_info.py -p HB329 -r A -c 'Feed heights (NE/SE/SW/NW): 4.410' -l "apa-infoupd" --date 2022/06/02 --time 21:38:02
add_part_info.py -p HB329 -r A -c 'For outrigger' -l "apa-infoupd" --date 2022/06/02 --time 21:38:04
add_part_info.py -p HB333 -r A -c 'for outrigger' -l "apa-infoupd" --date 2022/06/02 --time 21:38:00
add_part_info.py -p HB333 -r A -c 'Feed heights (NE/SE/SW/NW): 4.408' -l "apa-infoupd" --date 2022/06/02 --time 21:38:02
add_part_info.py -p HB333 -r A -c 'for outrigger' -l "apa-infoupd" --date 2022/06/02 --time 21:38:04
add_part_info.py -p HB332 -r A -c 'Spectre: N21P4E' -l "infoupd" --date 2022/06/02 --time 21:38:00
add_part_info.py -p HB332 -r A -c 'Feed heights (NE/SE/SW/NW): 4.404' -l "infoupd" --date 2022/06/02 --time 21:38:02
add_part_info.py -p HB332 -r A -c 'Spectre: N21P4N' -l "infoupd" --date 2022/06/02 --time 21:38:04
add_part_info.py -p HB336 -r A -c 'Spectre: N21P5E' -l "infoupd" --date 2022/06/02 --time 21:38:00
add_part_info.py -p HB336 -r A -c 'Feed heights (NE/SE/SW/NW): 4.408' -l "infoupd" --date 2022/06/02 --time 21:38:02
add_part_info.py -p HB336 -r A -c 'Spectre: N21P5N' -l "infoupd" --date 2022/06/02 --time 21:38:04
add_part_info.py -p HB340 -r A -c 'Spectre: N21P6E' -l "infoupd" --date 2022/06/02 --time 21:38:00
add_part_info.py -p HB340 -r A -c 'Feed heights (NE/SE/SW/NW): 4.406' -l "infoupd" --date 2022/06/02 --time 21:38:02
add_part_info.py -p HB340 -r A -c 'Spectre: N21P6N' -l "infoupd" --date 2022/06/02 --time 21:38:04
add_part_info.py -p HA326 -r A -c 'Spectre: N21P10E' -l "infoupd" --date 2022/06/02 --time 21:38:00
add_part_info.py -p HA326 -r A -c 'Feed heights (NE/SE/SW/NW): 4.406' -l "infoupd" --date 2022/06/02 --time 21:38:02
add_part_info.py -p HA326 -r A -c 'Spectre: N21P10N' -l "infoupd" --date 2022/06/02 --time 21:38:04
add_part_info.py -p HA327 -r A -c 'Spectre: N21P11E' -l "infoupd" --date 2022/06/02 --time 21:38:00
add_part_info.py -p HA327 -r A -c 'Feed heights (NE/SE/SW/NW): 4.408' -l "infoupd" --date 2022/06/02 --time 21:38:02
add_part_info.py -p HA327 -r A -c 'Spectre: N21P11N' -l "infoupd" --date 2022/06/02 --time 21:38:04
add_part_info.py -p HA331 -r A -c 'Spectre: N21P12E' -l "infoupd" --date 2022/06/02 --time 21:38:00
add_part_info.py -p HA331 -r A -c 'Feed heights (NE/SE/SW/NW): 4.407' -l "infoupd" --date 2022/06/02 --time 21:38:02
add_part_info.py -p HA331 -r A -c 'Spectre: N21P12N' -l "infoupd" --date 2022/06/02 --time 21:38:04
add_part_info.py -p HB320 -r A -c 'Installed SLP-250+ on E pol' -l "apa-infoupd" --date 2022/06/02 --time 21:38:00
add_part_info.py -p HB320 -r A -c 'height: 4.405' -l "apa-infoupd" --date 2022/06/02 --time 21:38:02
add_part_info.py -p HB320 -r A -c 'Spectra: N3P8E' -l "apa-infoupd" --date 2022/06/02 --time 21:38:04
add_part_info.py -p HB320 -r A -c 'Installed SLP-250+ on N pol' -l "apa-infoupd" --date 2022/06/02 --time 21:38:06
add_part_info.py -p HB320 -r A -c 'Spectra: N3P8N' -l "apa-infoupd" --date 2022/06/02 --time 21:38:08
add_part_info.py -p HB324 -r A -c 'Feed heights: 4.400' -l "infoupd" --date 2022/06/02 --time 21:38:00
add_part_info.py -p HB324 -r A -c 'Spectre: N4P12E' -l "infoupd" --date 2022/06/02 --time 21:38:02
add_part_info.py -p HB324 -r A -c 'Spectre: N4P12N' -l "infoupd" --date 2022/06/02 --time 21:38:04
add_part_info.py -p HB322 -r A -c 'Feed heights (NE/SE/SW/NW): 4.403' -l "apa-infoupd" --date 2022/06/02 --time 21:38:00
add_part_info.py -p HA325 -r A -c 'HEIGHT: 4.397' -l "apa-infoupd" --date 2022/06/02 --time 21:38:00
add_part_info.py -p HA325 -r A -c 'SPECTRE: N9P7E' -l "apa-infoupd" --date 2022/06/02 --time 21:38:02
add_part_info.py -p HA325 -r A -c 'SPECTRE: N9P7N' -l "apa-infoupd" --date 2022/06/02 --time 21:38:04
