#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220608_connupd_1803" >> scripts.log 
# Adding missing parts
add_part.py -p FDV235 -r A -t feed -m FDV235 --date 2022/06/08 --time 17:58
add_part.py -p FDV232 -r A -t feed -m FDV232 --date 2022/06/08 --time 17:58
add_part.py -p FDV209 -r A -t feed -m FDV209 --date 2022/06/08 --time 17:58
add_part.py -p FDV200 -r A -t feed -m FDV200 --date 2022/06/08 --time 17:58
add_part.py -p FDV226 -r A -t feed -m FDV226 --date 2022/06/08 --time 17:58
add_part.py -p FDV225 -r A -t feed -m FDV225 --date 2022/06/08 --time 17:58
add_part.py -p FDV280 -r A -t feed -m FDV280 --date 2022/06/08 --time 17:58
add_part.py -p FDV279 -r A -t feed -m FDV279 --date 2022/06/08 --time 17:58
add_part.py -p FDV257 -r A -t feed -m FDV257 --date 2022/06/08 --time 17:58
add_part.py -p FDV254 -r A -t feed -m FDV254 --date 2022/06/08 --time 17:58
add_part.py -p FEM203 -r A -t front-end -m FEM203 --date 2022/06/08 --time 17:58
add_part.py -p FDV240 -r A -t feed -m FDV240 --date 2022/06/08 --time 17:58
# Adding missing connections
add_connection.py -u A196 --uprev H --upport focus -d FDV240 --dnrev A --dnport input --date 2022/06/08 --time 18:03
add_connection.py -u A197 --uprev H --upport focus -d FDV232 --dnrev A --dnport input --date 2022/06/08 --time 18:03
add_connection.py -u A198 --uprev H --upport focus -d FDV280 --dnrev A --dnport input --date 2022/06/08 --time 18:03
add_connection.py -u A199 --uprev H --upport focus -d FDV279 --dnrev A --dnport input --date 2022/06/08 --time 18:03
add_connection.py -u A215 --uprev H --upport focus -d FDV257 --dnrev A --dnport input --date 2022/06/08 --time 18:03
add_connection.py -u A216 --uprev H --upport focus -d FDV235 --dnrev A --dnport input --date 2022/06/08 --time 18:03
add_connection.py -u A217 --uprev H --upport focus -d FDV200 --dnrev A --dnport input --date 2022/06/08 --time 18:03
add_connection.py -u A218 --uprev H --upport focus -d FDV209 --dnrev A --dnport input --date 2022/06/08 --time 18:03
add_connection.py -u A233 --uprev H --upport focus -d FDV254 --dnrev A --dnport input --date 2022/06/08 --time 18:03
add_connection.py -u A234 --uprev H --upport focus -d FDV226 --dnrev A --dnport input --date 2022/06/08 --time 18:03
add_connection.py -u A235 --uprev H --upport focus -d FDV225 --dnrev A --dnport input --date 2022/06/08 --time 18:03
add_connection.py -u FEM203 --uprev A --upport e -d NBP02 --dnrev A --dnport e11 --date 2022/06/08 --time 18:03
add_connection.py -u FEM203 --uprev A --upport n -d NBP02 --dnrev A --dnport n11 --date 2022/06/08 --time 18:03
# Adding different connections
stop_connection.py -u FDV259 --uprev A --upport terminals -d FEM702 --dnrev A --dnport input --date 2022/06/08 --time 18:02
stop_connection.py -u FEM302 --uprev A --upport e -d NBP02 --dnrev A --dnport e11 --date 2022/06/08 --time 18:02
stop_connection.py -u FEM302 --uprev A --upport n -d NBP02 --dnrev A --dnport n11 --date 2022/06/08 --time 18:02
stop_connection.py -u FDV287 --uprev A --upport terminals -d FEM302 --dnrev A --dnport input --date 2022/06/08 --time 18:02
add_connection.py -u FDV259 --uprev A --upport terminals -d FEM302 --dnrev A --dnport input --date 2022/06/08 --time 18:03
add_connection.py -u FEM302 --uprev A --upport e -d NBP21 --dnrev A --dnport e2 --date 2022/06/08 --time 18:03
add_connection.py -u FEM302 --uprev A --upport n -d NBP21 --dnrev A --dnport n2 --date 2022/06/08 --time 18:03
add_connection.py -u FDV287 --uprev A --upport terminals -d FEM203 --dnrev A --dnport input --date 2022/06/08 --time 18:03
# Adding missing parts
# Adding different parts
