#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/220926_connupd_1919" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u NBP02 --uprev A --upport n2 -d PAM198 --dnrev A --dnport n --date 2022/09/26 --time 19:13
stop_connection.py -u NBP02 --uprev A --upport e2 -d PAM198 --dnrev A --dnport e --date 2022/09/26 --time 19:13
stop_connection.py -u NBP14 --uprev A --upport e9 -d PAM181 --dnrev A --dnport e --date 2022/09/26 --time 19:13
stop_connection.py -u NBP14 --uprev A --upport n9 -d PAM181 --dnrev A --dnport n --date 2022/09/26 --time 19:13
stop_connection.py -u NBP08 --uprev A --upport e4 -d PAM013 --dnrev A --dnport e --date 2022/09/26 --time 19:13
stop_connection.py -u NBP08 --uprev A --upport e7 -d PAM016 --dnrev A --dnport e --date 2022/09/26 --time 19:13
stop_connection.py -u NBP08 --uprev A --upport e10 -d PAM019 --dnrev A --dnport e --date 2022/09/26 --time 19:13
stop_connection.py -u NBP08 --uprev A --upport n4 -d PAM013 --dnrev A --dnport n --date 2022/09/26 --time 19:13
stop_connection.py -u NBP08 --uprev A --upport n7 -d PAM016 --dnrev A --dnport n --date 2022/09/26 --time 19:13
stop_connection.py -u NBP08 --uprev A --upport n10 -d PAM019 --dnrev A --dnport n --date 2022/09/26 --time 19:13
stop_connection.py -u NBP13 --uprev A --upport e3 -d PAM163 --dnrev A --dnport e --date 2022/09/26 --time 19:13
stop_connection.py -u NBP13 --uprev A --upport n3 -d PAM163 --dnrev A --dnport n --date 2022/09/26 --time 19:13
stop_connection.py -u PAM163 --uprev A --upport e -d SNPC000035 --dnrev A --dnport e10 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM163 --uprev A --upport slot -d PCH10 --dnrev A --dnport slot3 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM163 --uprev A --upport n -d SNPC000035 --dnrev A --dnport n8 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM198 --uprev A --upport e -d SNPC000066 --dnrev A --dnport e6 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM198 --uprev A --upport n -d SNPC000066 --dnrev A --dnport n4 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM198 --uprev A --upport slot -d PCH14 --dnrev A --dnport slot2 --date 2022/09/26 --time 19:13
stop_connection.py -u NCM04 --uprev A --upport rack -d N18 --dnrev A --dnport middle --date 2022/09/26 --time 19:13
stop_connection.py -u NCMP1 --uprev A --upport rack -d N00 --dnrev A --dnport middle --date 2022/09/26 --time 19:13
stop_connection.py -u PAM181 --uprev A --upport slot -d PCH11 --dnrev A --dnport slot9 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM181 --uprev A --upport e -d SNPC000028 --dnrev A --dnport e10 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM181 --uprev A --upport n -d SNPC000028 --dnrev A --dnport n8 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM013 --uprev A --upport slot -d PCH03 --dnrev A --dnport slot4 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM013 --uprev A --upport e -d SNPC000044 --dnrev A --dnport e2 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM013 --uprev A --upport n -d SNPC000044 --dnrev A --dnport n0 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM016 --uprev A --upport slot -d PCH03 --dnrev A --dnport slot7 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM016 --uprev A --upport e -d SNPC000055 --dnrev A --dnport e2 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM016 --uprev A --upport n -d SNPC000055 --dnrev A --dnport n0 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM019 --uprev A --upport slot -d PCH03 --dnrev A --dnport slot10 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM019 --uprev A --upport e -d SNPC000056 --dnrev A --dnport e2 --date 2022/09/26 --time 19:13
stop_connection.py -u PAM019 --uprev A --upport n -d SNPC000056 --dnrev A --dnport n0 --date 2022/09/26 --time 19:13
# add parts for gsheet_not_active
add_part.py -p PAM296 -r A -t post-amp -m PAM296 --date 2022/09/26 --time 18:49
add_part.py -p PAM294 -r A -t post-amp -m PAM294 --date 2022/09/26 --time 18:49
add_part.py -p PAM297 -r A -t post-amp -m PAM297 --date 2022/09/26 --time 18:49
# add connections for gsheet_not_active
add_connection.py -u NBP13 --uprev A --upport E3 -d PAM301 --dnrev A --dnport e --date 2022/09/26 --time 19:19
add_connection.py -u NBP13 --uprev A --upport N3 -d PAM301 --dnrev A --dnport n --date 2022/09/26 --time 19:19
add_connection.py -u PAM301 --uprev A --upport slot -d PCH10 --dnrev A --dnport slot3 --date 2022/09/26 --time 19:19
add_connection.py -u PAM301 --uprev A --upport e -d SNPC000035 --dnrev A --dnport e10 --date 2022/09/26 --time 19:19
add_connection.py -u PAM301 --uprev A --upport n -d SNPC000035 --dnrev A --dnport n8 --date 2022/09/26 --time 19:19
add_connection.py -u NBP14 --uprev A --upport E9 -d PAM295 --dnrev A --dnport e --date 2022/09/26 --time 19:19
add_connection.py -u NBP14 --uprev A --upport N9 -d PAM295 --dnrev A --dnport n --date 2022/09/26 --time 19:19
add_connection.py -u PAM295 --uprev A --upport slot -d PCH11 --dnrev A --dnport slot9 --date 2022/09/26 --time 19:19
add_connection.py -u PAM295 --uprev A --upport e -d SNPC000028 --dnrev A --dnport e10 --date 2022/09/26 --time 19:19
add_connection.py -u PAM295 --uprev A --upport n -d SNPC000028 --dnrev A --dnport n8 --date 2022/09/26 --time 19:19
add_connection.py -u NCMP1 --uprev A --upport rack -d N18 --dnrev A --dnport middle --date 2022/09/26 --time 19:19
add_connection.py -u PAM013 --uprev A --upport slot -d PCH16 --dnrev A --dnport slot1 --date 2022/09/26 --time 19:19
add_connection.py -u PAM013 --uprev A --upport e -d SNPC000078 --dnrev A --dnport e2 --date 2022/09/26 --time 19:19
add_connection.py -u PAM013 --uprev A --upport n -d SNPC000078 --dnrev A --dnport n0 --date 2022/09/26 --time 19:19
add_connection.py -u NBP19 --uprev A --upport E1 -d PAM013 --dnrev A --dnport e --date 2022/09/26 --time 19:19
add_connection.py -u NBP19 --uprev A --upport N1 -d PAM013 --dnrev A --dnport n --date 2022/09/26 --time 19:19
add_connection.py -u NBP02 --uprev A --upport E2 -d PAM298 --dnrev A --dnport e --date 2022/09/26 --time 19:19
add_connection.py -u NBP02 --uprev A --upport N2 -d PAM298 --dnrev A --dnport n --date 2022/09/26 --time 19:19
add_connection.py -u NBP20 --uprev A --upport E8 -d PAM016 --dnrev A --dnport e --date 2022/09/26 --time 19:19
add_connection.py -u NBP20 --uprev A --upport N8 -d PAM016 --dnrev A --dnport n --date 2022/09/26 --time 19:19
add_connection.py -u PAM016 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot8 --date 2022/09/26 --time 19:19
add_connection.py -u PAM016 --uprev A --upport e -d SNPC000085 --dnrev A --dnport e6 --date 2022/09/26 --time 19:19
add_connection.py -u PAM016 --uprev A --upport n -d SNPC000085 --dnrev A --dnport n4 --date 2022/09/26 --time 19:19
add_connection.py -u NBP22 --uprev A --upport E9 -d PAM010 --dnrev A --dnport e --date 2022/09/26 --time 19:19
add_connection.py -u NBP22 --uprev A --upport N9 -d PAM010 --dnrev A --dnport n --date 2022/09/26 --time 19:19
add_connection.py -u NBP22 --uprev A --upport E12 -d PAM019 --dnrev A --dnport e --date 2022/09/26 --time 19:19
add_connection.py -u NBP22 --uprev A --upport N12 -d PAM019 --dnrev A --dnport n --date 2022/09/26 --time 19:19
add_connection.py -u PAM010 --uprev A --upport slot -d PCH21 --dnrev A --dnport slot9 --date 2022/09/26 --time 19:19
add_connection.py -u PAM010 --uprev A --upport e -d SNPC000126 --dnrev A --dnport e10 --date 2022/09/26 --time 19:19
add_connection.py -u PAM010 --uprev A --upport n -d SNPC000126 --dnrev A --dnport n8 --date 2022/09/26 --time 19:19
add_connection.py -u PAM019 --uprev A --upport slot -d PCH21 --dnrev A --dnport slot12 --date 2022/09/26 --time 19:19
add_connection.py -u PAM019 --uprev A --upport e -d SNPC000128 --dnrev A --dnport e10 --date 2022/09/26 --time 19:19
add_connection.py -u PAM019 --uprev A --upport n -d SNPC000128 --dnrev A --dnport n8 --date 2022/09/26 --time 19:19
add_connection.py -u NBP08 --uprev A --upport E4 -d PAM296 --dnrev A --dnport e --date 2022/09/26 --time 19:19
add_connection.py -u NBP08 --uprev A --upport N4 -d PAM296 --dnrev A --dnport n --date 2022/09/26 --time 19:19
add_connection.py -u NBP08 --uprev A --upport E7 -d PAM294 --dnrev A --dnport e --date 2022/09/26 --time 19:19
add_connection.py -u NBP08 --uprev A --upport N7 -d PAM294 --dnrev A --dnport n --date 2022/09/26 --time 19:19
add_connection.py -u NBP08 --uprev A --upport E10 -d PAM297 --dnrev A --dnport e --date 2022/09/26 --time 19:19
add_connection.py -u NBP08 --uprev A --upport N10 -d PAM297 --dnrev A --dnport n --date 2022/09/26 --time 19:19
add_connection.py -u PAM296 --uprev A --upport slot -d PCH03 --dnrev A --dnport slot4 --date 2022/09/26 --time 19:19
add_connection.py -u PAM296 --uprev A --upport e -d SNPC000044 --dnrev A --dnport e2 --date 2022/09/26 --time 19:19
add_connection.py -u PAM296 --uprev A --upport n -d SNPC000044 --dnrev A --dnport n0 --date 2022/09/26 --time 19:19
add_connection.py -u PAM294 --uprev A --upport slot -d PCH03 --dnrev A --dnport slot7 --date 2022/09/26 --time 19:19
add_connection.py -u PAM294 --uprev A --upport e -d SNPC000055 --dnrev A --dnport e2 --date 2022/09/26 --time 19:19
add_connection.py -u PAM294 --uprev A --upport n -d SNPC000055 --dnrev A --dnport n0 --date 2022/09/26 --time 19:19
add_connection.py -u PAM297 --uprev A --upport slot -d PCH03 --dnrev A --dnport slot10 --date 2022/09/26 --time 19:19
add_connection.py -u PAM297 --uprev A --upport e -d SNPC000056 --dnrev A --dnport e2 --date 2022/09/26 --time 19:19
add_connection.py -u PAM297 --uprev A --upport n -d SNPC000056 --dnrev A --dnport n0 --date 2022/09/26 --time 19:19
add_connection.py -u PAM298 --uprev A --upport slot -d PCH14 --dnrev A --dnport slot2 --date 2022/09/26 --time 19:19
add_connection.py -u PAM298 --uprev A --upport e -d SNPC000066 --dnrev A --dnport e6 --date 2022/09/26 --time 19:19
add_connection.py -u PAM298 --uprev A --upport n -d SNPC000066 --dnrev A --dnport n4 --date 2022/09/26 --time 19:19
