#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221128_connupd_2040" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u FDV166 --uprev A --upport terminals -d FEM292 --dnrev A --dnport input --date 2022/11/25 --time 20:34
stop_connection.py -u FEM292 --uprev A --upport e -d NBP06 --dnrev A --dnport e9 --date 2022/11/25 --time 20:34
stop_connection.py -u FEM292 --uprev A --upport n -d NBP06 --dnrev A --dnport n9 --date 2022/11/25 --time 20:34
stop_connection.py -u FEM292 --uprev A --upport pwr -d FPS21 --dnrev A --dnport pwr9 --date 2022/11/25 --time 20:34
stop_connection.py -u FEM236 --uprev A --upport e -d NBP06 --dnrev A --dnport e10 --date 2022/11/25 --time 20:34
stop_connection.py -u FEM236 --uprev A --upport n -d NBP06 --dnrev A --dnport n10 --date 2022/11/25 --time 20:34
stop_connection.py -u FEM236 --uprev A --upport pwr -d FPS21 --dnrev A --dnport pwr10 --date 2022/11/25 --time 20:34
stop_connection.py -u FEM291 --uprev A --upport pwr -d FPS21 --dnrev A --dnport pwr6 --date 2022/11/25 --time 20:34
stop_connection.py -u FEM291 --uprev A --upport e -d NBP06 --dnrev A --dnport e6 --date 2022/11/25 --time 20:34
stop_connection.py -u FEM291 --uprev A --upport n -d NBP06 --dnrev A --dnport n6 --date 2022/11/25 --time 20:34
stop_connection.py -u FDV174 --uprev A --upport terminals -d FEM291 --dnrev A --dnport input --date 2022/11/25 --time 20:34
stop_connection.py -u FDV176 --uprev A --upport terminals -d FEM236 --dnrev A --dnport input --date 2022/11/25 --time 20:34
# add parts for gsheet_not_active
add_part.py -p FEM295 -r A -t front-end -m FEM295 --date 2022/11/25 --time 20:10
# add connections for gsheet_not_active
add_connection.py -u FDV174 --uprev A --upport terminals -d FEM292 --dnrev A --dnport input --date 2022/11/25 --time 20:40
add_connection.py -u FEM292 --uprev A --upport pwr -d FPS21 --dnrev A --dnport pwr6 --date 2022/11/25 --time 20:40
add_connection.py -u FEM292 --uprev A --upport e -d NBP06 --dnrev A --dnport E6 --date 2022/11/25 --time 20:40
add_connection.py -u FEM292 --uprev A --upport n -d NBP06 --dnrev A --dnport N6 --date 2022/11/25 --time 20:40
add_connection.py -u FDV166 --uprev A --upport terminals -d FEM291 --dnrev A --dnport input --date 2022/11/25 --time 20:40
add_connection.py -u FEM291 --uprev A --upport pwr -d FPS21 --dnrev A --dnport pwr9 --date 2022/11/25 --time 20:40
add_connection.py -u FEM291 --uprev A --upport e -d NBP06 --dnrev A --dnport E9 --date 2022/11/25 --time 20:40
add_connection.py -u FEM291 --uprev A --upport n -d NBP06 --dnrev A --dnport N9 --date 2022/11/25 --time 20:40
add_connection.py -u FDV176 --uprev A --upport terminals -d FEM295 --dnrev A --dnport input --date 2022/11/25 --time 20:40
add_connection.py -u FEM295 --uprev A --upport pwr -d FPS21 --dnrev A --dnport pwr10 --date 2022/11/25 --time 20:40
add_connection.py -u FEM295 --uprev A --upport e -d NBP06 --dnrev A --dnport E10 --date 2022/11/25 --time 20:40
add_connection.py -u FEM295 --uprev A --upport n -d NBP06 --dnrev A --dnport N10 --date 2022/11/25 --time 20:40
