#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221115_connupd_0835" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u FEM170 --uprev A --upport pwr -d FPS11 --dnrev A --dnport pwr9 --date 2022/11/15 --time 08:29
stop_connection.py -u FEM170 --uprev A --upport e -d NBP13 --dnrev A --dnport e9 --date 2022/11/15 --time 08:29
stop_connection.py -u FEM170 --uprev A --upport n -d NBP13 --dnrev A --dnport n9 --date 2022/11/15 --time 08:29
stop_connection.py -u FDV121 --uprev A --upport terminals -d FEM170 --dnrev A --dnport input --date 2022/11/15 --time 08:29
# add parts for gsheet_not_active
add_part.py -p FEM374 -r A -t front-end -m FEM374 --date 2022/11/15 --time 08:05
# add connections for gsheet_not_active
add_connection.py -u FDV121 --uprev A --upport terminals -d FEM374 --dnrev A --dnport input --date 2022/11/15 --time 08:35
add_connection.py -u FEM374 --uprev A --upport pwr -d FPS11 --dnrev A --dnport pwr9 --date 2022/11/15 --time 08:35
add_connection.py -u FEM374 --uprev A --upport e -d NBP13 --dnrev A --dnport E9 --date 2022/11/15 --time 08:35
add_connection.py -u FEM374 --uprev A --upport n -d NBP13 --dnrev A --dnport N9 --date 2022/11/15 --time 08:35
