#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221122_connupd_1235" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u FEM108 --uprev A --upport pwr -d FPS06 --dnrev A --dnport pwr7 --date 2022/11/22 --time 12:29
stop_connection.py -u FEM108 --uprev A --upport e -d NBP05 --dnrev A --dnport e7 --date 2022/11/22 --time 12:29
stop_connection.py -u FEM108 --uprev A --upport n -d NBP05 --dnrev A --dnport n7 --date 2022/11/22 --time 12:29
stop_connection.py -u FDV64 --uprev A --upport terminals -d FEM108 --dnrev A --dnport input --date 2022/11/22 --time 12:29
# add connections for gsheet_not_active
add_connection.py -u FDV64 --uprev A --upport terminals -d FEM342 --dnrev A --dnport input --date 2022/11/22 --time 12:35
add_connection.py -u FEM342 --uprev A --upport pwr -d FPS06 --dnrev A --dnport pwr7 --date 2022/11/22 --time 12:35
add_connection.py -u FEM342 --uprev A --upport e -d NBP05 --dnrev A --dnport E7 --date 2022/11/22 --time 12:35
add_connection.py -u FEM342 --uprev A --upport n -d NBP05 --dnrev A --dnport N7 --date 2022/11/22 --time 12:35
