#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221104_connupd_1735" >> scripts.log 
# stop connections for active_not_gsheet
# add parts for gsheet_not_active
add_part.py -p FEM379 -r A -t front-end -m FEM379 --date 2022/11/04 --time 17:05
# add connections for gsheet_not_active
add_connection.py -u A76 --uprev H --upport focus -d FDV48 --dnrev A --dnport input --date 2022/11/04 --time 17:35
add_connection.py -u FDV48 --uprev A --upport terminals -d FEM379 --dnrev A --dnport input --date 2022/11/04 --time 17:35
add_connection.py -u FEM379 --uprev A --upport pwr -d FPS06 --dnrev A --dnport pwr12 --date 2022/11/04 --time 17:35
add_connection.py -u FEM379 --uprev A --upport e -d NBP05 --dnrev A --dnport E12 --date 2022/11/04 --time 17:35
add_connection.py -u FEM379 --uprev A --upport n -d NBP05 --dnrev A --dnport N12 --date 2022/11/04 --time 17:35
