#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221118_connupd_1335" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u FDV178 --uprev A --upport terminals -d FEM288 --dnrev A --dnport input --date 2022/11/18 --time 13:29
stop_connection.py -u FEM288 --uprev A --upport e -d NBP06 --dnrev A --dnport e7 --date 2022/11/18 --time 13:29
stop_connection.py -u FEM288 --uprev A --upport n -d NBP06 --dnrev A --dnport n7 --date 2022/11/18 --time 13:29
stop_connection.py -u FEM288 --uprev A --upport pwr -d FPS21 --dnrev A --dnport pwr7 --date 2022/11/18 --time 13:29
stop_connection.py -u FEM180 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr3 --date 2022/11/18 --time 13:29
stop_connection.py -u FEM180 --uprev A --upport e -d NBP14 --dnrev A --dnport e3 --date 2022/11/18 --time 13:29
stop_connection.py -u FEM180 --uprev A --upport n -d NBP14 --dnrev A --dnport n3 --date 2022/11/18 --time 13:29
stop_connection.py -u FDV107 --uprev A --upport terminals -d FEM180 --dnrev A --dnport input --date 2022/11/18 --time 13:29
# add parts for gsheet_not_active
add_part.py -p FEM369 -r A -t front-end -m FEM369 --date 2022/11/18 --time 13:05
add_part.py -p FEM324 -r A -t front-end -m FEM324 --date 2022/11/18 --time 13:05
# add connections for gsheet_not_active
add_connection.py -u FDV107 --uprev A --upport terminals -d FEM369 --dnrev A --dnport input --date 2022/11/18 --time 13:35
add_connection.py -u FEM369 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr3 --date 2022/11/18 --time 13:35
add_connection.py -u FEM369 --uprev A --upport e -d NBP14 --dnrev A --dnport E3 --date 2022/11/18 --time 13:35
add_connection.py -u FEM369 --uprev A --upport n -d NBP14 --dnrev A --dnport N3 --date 2022/11/18 --time 13:35
add_connection.py -u FDV178 --uprev A --upport terminals -d FEM324 --dnrev A --dnport input --date 2022/11/18 --time 13:35
add_connection.py -u FEM324 --uprev A --upport pwr -d FPS21 --dnrev A --dnport pwr7 --date 2022/11/18 --time 13:35
add_connection.py -u FEM324 --uprev A --upport e -d NBP06 --dnrev A --dnport E7 --date 2022/11/18 --time 13:35
add_connection.py -u FEM324 --uprev A --upport n -d NBP06 --dnrev A --dnport N7 --date 2022/11/18 --time 13:35
