#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/221215_connupd_2146" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u FDV238 --uprev A --upport terminals -d FEM341 --dnrev A --dnport input --date 2022/12/13 --time 10:29
stop_connection.py -u FEM341 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr6 --date 2022/12/13 --time 10:29
stop_connection.py -u FEM341 --uprev A --upport e -d NBP23 --dnrev A --dnport E6 --date 2022/12/13 --time 10:29
stop_connection.py -u FEM341 --uprev A --upport n -d NBP23 --dnrev A --dnport N6 --date 2022/12/13 --time 10:29
stop_connection.py -u FEM133 --uprev A --upport pwr -d FPS09 --dnrev A --dnport pwr9 --date 2022/12/13 --time 10:29
stop_connection.py -u FEM133 --uprev A --upport e -d NBP03 --dnrev A --dnport e9 --date 2022/12/13 --time 10:29
stop_connection.py -u FEM133 --uprev A --upport n -d NBP03 --dnrev A --dnport n9 --date 2022/12/13 --time 10:29
stop_connection.py -u FDV75 --uprev A --upport terminals -d FEM133 --dnrev A --dnport input --date 2022/12/13 --time 10:29
# add connections for gsheet_not_active
add_connection.py -u FDV75 --uprev A --upport terminals -d FEM341 --dnrev A --dnport input --date 2022/12/13 --time 10:35
add_connection.py -u FEM341 --uprev A --upport pwr -d FPS09 --dnrev A --dnport pwr9 --date 2022/12/13 --time 10:35
add_connection.py -u FEM341 --uprev A --upport e -d NBP03 --dnrev A --dnport E9 --date 2022/12/13 --time 10:35
add_connection.py -u FEM341 --uprev A --upport n -d NBP03 --dnrev A --dnport N9 --date 2022/12/13 --time 10:35
