#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230215_connupd_0035" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u FEM198 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr2 --date 2023/02/15 --time 00:29
stop_connection.py -u FEM198 --uprev A --upport e -d NBP14 --dnrev A --dnport e2 --date 2023/02/15 --time 00:29
stop_connection.py -u FEM198 --uprev A --upport n -d NBP14 --dnrev A --dnport n2 --date 2023/02/15 --time 00:29
stop_connection.py -u FEM175 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr9 --date 2023/02/15 --time 00:29
stop_connection.py -u FEM175 --uprev A --upport e -d NBP14 --dnrev A --dnport e9 --date 2023/02/15 --time 00:29
stop_connection.py -u FEM175 --uprev A --upport n -d NBP14 --dnrev A --dnport n9 --date 2023/02/15 --time 00:29
stop_connection.py -u FEM183 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr11 --date 2023/02/15 --time 00:29
stop_connection.py -u FEM183 --uprev A --upport e -d NBP14 --dnrev A --dnport e11 --date 2023/02/15 --time 00:29
stop_connection.py -u FEM183 --uprev A --upport n -d NBP14 --dnrev A --dnport n11 --date 2023/02/15 --time 00:29
stop_connection.py -u FEM378 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr3 --date 2023/02/15 --time 00:29
stop_connection.py -u FEM378 --uprev A --upport e -d NBP14 --dnrev A --dnport E3 --date 2023/02/15 --time 00:29
stop_connection.py -u FEM378 --uprev A --upport n -d NBP14 --dnrev A --dnport N3 --date 2023/02/15 --time 00:29
stop_connection.py -u FEM369 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr5 --date 2023/02/15 --time 00:29
stop_connection.py -u FEM369 --uprev A --upport e -d NBP14 --dnrev A --dnport E5 --date 2023/02/15 --time 00:29
stop_connection.py -u FEM369 --uprev A --upport n -d NBP14 --dnrev A --dnport N5 --date 2023/02/15 --time 00:29
# add connections for gsheet_not_active
add_connection.py -u FEM378 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr2 --date 2023/02/15 --time 00:35
add_connection.py -u FEM378 --uprev A --upport e -d NBP14 --dnrev A --dnport E2 --date 2023/02/15 --time 00:35
add_connection.py -u FEM378 --uprev A --upport n -d NBP14 --dnrev A --dnport N2 --date 2023/02/15 --time 00:35
add_connection.py -u FEM198 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr5 --date 2023/02/15 --time 00:35
add_connection.py -u FEM198 --uprev A --upport e -d NBP14 --dnrev A --dnport E5 --date 2023/02/15 --time 00:35
add_connection.py -u FEM198 --uprev A --upport n -d NBP14 --dnrev A --dnport N5 --date 2023/02/15 --time 00:35
add_connection.py -u FEM369 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr3 --date 2023/02/15 --time 00:35
add_connection.py -u FEM369 --uprev A --upport e -d NBP14 --dnrev A --dnport E3 --date 2023/02/15 --time 00:35
add_connection.py -u FEM369 --uprev A --upport n -d NBP14 --dnrev A --dnport N3 --date 2023/02/15 --time 00:35
add_connection.py -u FEM183 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr9 --date 2023/02/15 --time 00:35
add_connection.py -u FEM183 --uprev A --upport e -d NBP14 --dnrev A --dnport E9 --date 2023/02/15 --time 00:35
add_connection.py -u FEM183 --uprev A --upport n -d NBP14 --dnrev A --dnport N9 --date 2023/02/15 --time 00:35
add_connection.py -u FEM175 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr11 --date 2023/02/15 --time 00:35
add_connection.py -u FEM175 --uprev A --upport e -d NBP14 --dnrev A --dnport E11 --date 2023/02/15 --time 00:35
add_connection.py -u FEM175 --uprev A --upport n -d NBP14 --dnrev A --dnport N11 --date 2023/02/15 --time 00:35
