#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230203_connupd_1535" >> scripts.log 
# stop connections for active_not_gsheet
# add parts for gsheet_not_active
add_part.py -p FEM919 -r A -t front-end -m FEM919 --date 2023/02/03 --time 15:05
add_part.py -p FEM235 -r A -t front-end -m FEM235 --date 2023/02/03 --time 15:05
add_part.py -p FEM311 -r A -t front-end -m FEM311 --date 2023/02/03 --time 15:05
add_part.py -p FDV290 -r A -t feed -m FDV290 --date 2023/02/03 --time 15:05
# add connections for gsheet_not_active
add_connection.py -u A328 --uprev H --upport focus -d FDV290 --dnrev A --dnport input --date 2023/02/03 --time 15:35
add_connection.py -u FDV290 --uprev A --upport terminals -d FEM235 --dnrev A --dnport input --date 2023/02/03 --time 15:35
add_connection.py -u FEM235 --uprev A --upport pwr -d FPS08 --dnrev A --dnport pwr12 --date 2023/02/03 --time 15:35
add_connection.py -u FEM235 --uprev A --upport e -d NBP10 --dnrev A --dnport E12 --date 2023/02/03 --time 15:35
add_connection.py -u FEM235 --uprev A --upport n -d NBP10 --dnrev A --dnport N12 --date 2023/02/03 --time 15:35
add_connection.py -u FDV242 --uprev A --upport terminals -d FEM311 --dnrev A --dnport input --date 2023/02/03 --time 15:35
add_connection.py -u FEM311 --uprev A --upport pwr -d FPS18 --dnrev A --dnport pwr4 --date 2023/02/03 --time 15:35
add_connection.py -u FEM311 --uprev A --upport e -d NBP11 --dnrev A --dnport E4 --date 2023/02/03 --time 15:35
add_connection.py -u FEM311 --uprev A --upport n -d NBP11 --dnrev A --dnport N4 --date 2023/02/03 --time 15:35
add_connection.py -u FDV197 --uprev A --upport terminals -d FEM919 --dnrev A --dnport input --date 2023/02/03 --time 15:35
add_connection.py -u FEM919 --uprev A --upport pwr -d FPS17 --dnrev A --dnport pwr1 --date 2023/02/03 --time 15:35
add_connection.py -u FEM919 --uprev A --upport e -d NBP19 --dnrev A --dnport E1 --date 2023/02/03 --time 15:35
add_connection.py -u FEM919 --uprev A --upport n -d NBP19 --dnrev A --dnport N1 --date 2023/02/03 --time 15:35
