#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230420_infoupd_1942" >> scripts.log 
add_part_info.py -p HH155 -r A -c "H6Ccheck: No sky in E -DCJ" -l "infoupd" --date 2023/04/20 --time 19:42:00
add_part_info.py -p HH156 -r A -c "H6Ccheck: No Sky in E -DCJ" -l "infoupd" --date 2023/04/20 --time 19:42:00
add_part_info.py -p HH46 -r A -c "No sky in N per ACS -DCJ" -l "infoupd" --date 2023/04/20 --time 19:42:00
add_part_info.py -p HH73 -r A -c "no sky per antenna classification summary -DCJ" -l "infoupd" --date 2023/04/20 --time 19:42:00
add_part_info.py -p HH58 -r A -c "no sky per antenna classification summary -DCJ" -l "infoupd" --date 2023/04/20 --time 19:42:00
add_part_info.py -p HH60 -r A -c "no sky per antenna classification summary -DCJ" -l "infoupd" --date 2023/04/20 --time 19:42:00
add_part_info.py -p HH43 -r A -c "no sky in E per ACS -DCJ" -l "infoupd" --date 2023/04/20 --time 19:42:00
add_part_info.py -p HH74 -r A -c "no sky per antenna classification summary -DCJ" -l "infoupd" --date 2023/04/20 --time 19:42:00
add_part_info.py -p HH75 -r A -c "No sky in N per ACS  -DCJ" -l "infoupd" --date 2023/04/20 --time 19:42:00
