#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230430_infoupd_1742" >> scripts.log 
add_part_info.py -p HH186 -r A -c "swap due to high chisq" -l "infoupd" --date 2023/04/30 --time 17:42:00
add_part_info.py -p HH186 -r A -c "Feed Heights: 4.408" -l "infoupd" --date 2023/04/30 --time 17:42:02
