#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230408_infoupd_1442" >> scripts.log 
add_part_info.py -p HH145 -r A -c "Feed Heights: 4.409" -l "infoupd" --date 2023/04/08 --time 14:42:00
