#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230417_infoupd_1142" >> scripts.log 
add_part_info.py -p HH149 -r A -c "Feed heights (NE/SE/SW/NW): 4.411" -l "infoupd" --date 2023/04/17 --time 11:42:00
add_part_info.py -p HH149 -r A -c "H6C: Feed Height Before: 4.401 Sticker Targets: Already Present Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Installed Spiral Wrap: Installed D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2023/04/17 --time 11:42:02
add_part_info.py -p HH150 -r A -c "Feed heights (NE/SE/SW/NW): 4.408" -l "infoupd" --date 2023/04/17 --time 11:42:00
add_part_info.py -p HH150 -r A -c "H6C: Feed Height Before: 4.399 Sticker Targets: Already Present Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Installed Spiral Wrap: Installed D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2023/04/17 --time 11:42:02
add_part_info.py -p HH170 -r A -c "Feed heights (NE/SE/SW/NW): 4.405" -l "infoupd" --date 2023/04/17 --time 11:42:00
add_part_info.py -p HH170 -r A -c "H6C: Feed Height Before: 4.402 Sticker Targets: Already Present Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2023/04/17 --time 11:42:02
