#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230416_infoupd_0942" >> scripts.log 
add_part_info.py -p HH139 -r A -c "Feed heights (NE/SE/SW/NW): 4.408" -l "infoupd" --date 2023/04/16 --time 09:42:00
add_part_info.py -p HH139 -r A -c "H6C: Feed Height Before: New Connection Sticker Targets: Installed Stiffener Braces: Installed Carey Caps: Installed Protected Fiber: Installed Cable Conduit: Installed Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2023/04/16 --time 09:42:02
add_part_info.py -p HH159 -r A -c "FEM Switch error -DCJ" -l "infoupd" --date 2023/04/16 --time 09:42:00
add_part_info.py -p HH159 -r A -c "Feed heights (NE/SE/SW/NW): 4.410" -l "infoupd" --date 2023/04/16 --time 09:42:02
add_part_info.py -p HH159 -r A -c "H6C: Feed Height Before: New Connection Sticker Targets: Installed Stiffener Braces: Installed Carey Caps: Installed Protected Fiber: Installed Cable Conduit: Installed Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2023/04/16 --time 09:42:04
