#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230522_infoupd_1142" >> scripts.log 
add_part_info.py -p HH59 -r A -c "Feed heights (NE/SE/SW/NW): 4.407" -l "infoupd" --date 2023/05/22 --time 11:42:00
add_part_info.py -p HH59 -r A -c "FEM 103 replaced with FEM 334" -l "infoupd" --date 2023/05/22 --time 11:42:02
