#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230502_infoupd_1742" >> scripts.log 
update_apriori.py -p HH62 -s digital_ok --date 2023/05/02 --time 17:48
add_part_info.py -p HH62 -r A -c "apriori_antenna status change: not_connected > digital_ok" -l "apa-infoupd" --date 2023/05/02 --time 17:48
