#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230529_infoupd_1042" >> scripts.log 
add_part_info.py -p HH97 -r A -c "Feed heights (NE/SE/SW/NW): 4.408" -l "infoupd" --date 2023/05/29 --time 10:42:00
add_part_info.py -p HH97 -r A -c "H6C: Feed Height Before: 4.399 Sticker Targets: Already Present Stiffener Braces: Present Already  Carey Caps: Present Already Protected Fiber: Present Already  Cable Conduit: Installed Spiral Wrap: Present Already D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2023/05/29 --time 10:42:02
add_part_info.py -p HH114 -r A -c "Feed heights (NE/SE/SW/NW): 4.408" -l "infoupd" --date 2023/05/29 --time 10:42:00
add_part_info.py -p HH114 -r A -c "H6C: Feed Height Before: 4.397 Sticker Targets: Already Present Stiffener Braces: Present Already  Carey Caps: Present Already Protected Fiber: Present Already  Cable Conduit: Installed Spiral Wrap: Present Already D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2023/05/29 --time 10:42:02
add_part_info.py -p HH113 -r A -c "H6C: Feed Height Before: 4.409 Sticker Targets: Already Present Stiffener Braces: Present Already  Carey Caps: Present Already Protected Fiber: Present Already  Cable Conduit: Installed Spiral Wrap: Present Already D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2023/05/29 --time 10:42:00
add_part_info.py -p HH156 -r A -c "Replaced FEM 155 with FEM 336" -l "infoupd" --date 2023/05/29 --time 10:42:00
add_part_info.py -p HH190 -r A -c "Feed heights (NE/SE/SW/NW): 4.408" -l "infoupd" --date 2023/05/29 --time 10:42:00
add_part_info.py -p HH190 -r A -c "H6C: Feed Height Before: 4.407 Sticker Targets: Already Present Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Installed Spiral Wrap: Installed D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2023/05/29 --time 10:42:02
