#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230501_infoupd_1642" >> scripts.log 
add_part_info.py -p HH73 -r A -c "Feed heights (NE/SE/SW/NW): 4.403" -l "infoupd" --date 2023/05/01 --time 16:42:00
add_part_info.py -p HH73 -r A -c "H6C: Feed Height Before: 4.398 Sticker Targets: Installed Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2023/05/01 --time 16:42:02
add_part_info.py -p HH58 -r A -c "Feed heights (NE/SE/SW/NW): 4.407" -l "infoupd" --date 2023/05/01 --time 16:42:00
add_part_info.py -p HH58 -r A -c "H6C: Feed Height Before: 4.411 Sticker Targets: Installed Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2023/05/01 --time 16:42:02
add_part_info.py -p HH74 -r A -c "Feed heights (NE/SE/SW/NW): 4.401" -l "infoupd" --date 2023/05/01 --time 16:42:00
add_part_info.py -p HH74 -r A -c "H6C: Feed Height Before: 4.398 Sticker Targets: Installed Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Installed Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2023/05/01 --time 16:42:02
