#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230605_connupd_1135" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u PAM049 --uprev A --upport slot -d PCH04 --dnrev A --dnport slot12 --date 2023/06/05 --time 11:29
stop_connection.py -u PAM061 --uprev A --upport slot -d PCH04 --dnrev A --dnport slot9 --date 2023/06/05 --time 11:29
stop_connection.py -u PAM302 --uprev A --upport slot -d PCH04 --dnrev A --dnport slot11 --date 2023/06/05 --time 11:29
stop_connection.py -u PAM053 --uprev A --upport slot -d PCH04 --dnrev A --dnport slot1 --date 2023/06/05 --time 11:29
stop_connection.py -u PAM054 --uprev A --upport slot -d PCH04 --dnrev A --dnport slot2 --date 2023/06/05 --time 11:29
stop_connection.py -u PAM056 --uprev A --upport slot -d PCH04 --dnrev A --dnport slot4 --date 2023/06/05 --time 11:29
stop_connection.py -u PCH04 --uprev A --upport rack -d N07 --dnrev A --dnport bottom --date 2023/06/05 --time 11:29
stop_connection.py -u PAM057 --uprev A --upport slot -d PCH04 --dnrev A --dnport slot5 --date 2023/06/05 --time 11:29
stop_connection.py -u PAM304 --uprev A --upport slot -d PCH04 --dnrev A --dnport slot6 --date 2023/06/05 --time 11:29
stop_connection.py -u PAM060 --uprev A --upport slot -d PCH04 --dnrev A --dnport slot8 --date 2023/06/05 --time 11:29
stop_connection.py -u PAM058 --uprev A --upport slot -d PCH04 --dnrev A --dnport slot3 --date 2023/06/05 --time 11:29
stop_connection.py -u PAM059 --uprev A --upport slot -d PCH04 --dnrev A --dnport slot7 --date 2023/06/05 --time 11:29
stop_connection.py -u PAM299 --uprev A --upport slot -d PCH04 --dnrev A --dnport slot10 --date 2023/06/05 --time 11:29
stop_connection.py -u PCH23 --uprev A --upport rack -d N17 --dnrev A --dnport bottom --date 2023/06/05 --time 11:29
# add parts for gsheet_not_active
add_part.py -p PCH -r A -t pam-chassis -m PCH --date 2023/06/05 --time 11:05
# add connections for gsheet_not_active
add_connection.py -u PCH --uprev A --upport rack -d N17 --dnrev A --dnport bottom --date 2023/06/05 --time 11:35
add_connection.py -u PCH23 --uprev A --upport rack -d N07 --dnrev A --dnport bottom --date 2023/06/05 --time 11:35
add_connection.py -u PAM053 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot1 --date 2023/06/05 --time 11:35
add_connection.py -u PAM054 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot2 --date 2023/06/05 --time 11:35
add_connection.py -u PAM058 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot3 --date 2023/06/05 --time 11:35
add_connection.py -u PAM056 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot4 --date 2023/06/05 --time 11:35
add_connection.py -u PAM057 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot5 --date 2023/06/05 --time 11:35
add_connection.py -u PAM304 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot6 --date 2023/06/05 --time 11:35
add_connection.py -u PAM059 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot7 --date 2023/06/05 --time 11:35
add_connection.py -u PAM060 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot8 --date 2023/06/05 --time 11:35
add_connection.py -u PAM061 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot9 --date 2023/06/05 --time 11:35
add_connection.py -u PAM299 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot10 --date 2023/06/05 --time 11:35
add_connection.py -u PAM302 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot11 --date 2023/06/05 --time 11:35
add_connection.py -u PAM049 --uprev A --upport slot -d PCH23 --dnrev A --dnport slot12 --date 2023/06/05 --time 11:35
