#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230610_connupd_1535" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u FDV24 --uprev A --upport terminals -d FEM032 --dnrev A --dnport input --date 2023/06/10 --time 15:29
stop_connection.py -u FEM032 --uprev A --upport pwr -d FPS02 --dnrev A --dnport pwr8 --date 2023/06/10 --time 15:29
stop_connection.py -u FEM032 --uprev A --upport n -d NBP09 --dnrev A --dnport n8 --date 2023/06/10 --time 15:29
stop_connection.py -u FEM032 --uprev A --upport e -d NBP09 --dnrev A --dnport e8 --date 2023/06/10 --time 15:29
# add connections for gsheet_not_active
add_connection.py -u FDV24 --uprev A --upport terminals -d FEM359 --dnrev A --dnport input --date 2023/06/10 --time 15:35
add_connection.py -u FEM359 --uprev A --upport pwr -d FPS02 --dnrev A --dnport pwr8 --date 2023/06/10 --time 15:35
add_connection.py -u FEM359 --uprev A --upport e -d NBP09 --dnrev A --dnport E8 --date 2023/06/10 --time 15:35
add_connection.py -u FEM359 --uprev A --upport n -d NBP09 --dnrev A --dnport N8 --date 2023/06/10 --time 15:35
