#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230728_connupd_0135" >> scripts.log 
# stop connections for active_not_gsheet
# add parts for gsheet_not_active
add_part.py -p FEM337 -r A -t front-end -m FEM337 --date 2023/07/28 --time 01:05
add_part.py -p FEM145 -r A -t front-end -m FEM145 --date 2023/07/28 --time 01:05
# add connections for gsheet_not_active
add_connection.py -u FDV232 --uprev A --upport terminals -d FEM337 --dnrev A --dnport input --date 2023/07/28 --time 01:35
add_connection.py -u FEM337 --uprev A --upport pwr -d FPS23 --dnrev A --dnport pwr2 --date 2023/07/28 --time 01:35
add_connection.py -u FEM337 --uprev A --upport e -d NBP17 --dnrev A --dnport E2 --date 2023/07/28 --time 01:35
add_connection.py -u FEM337 --uprev A --upport n -d NBP17 --dnrev A --dnport N2 --date 2023/07/28 --time 01:35
add_connection.py -u FDV280 --uprev A --upport terminals -d FEM204 --dnrev A --dnport input --date 2023/07/28 --time 01:35
add_connection.py -u FDV257 --uprev A --upport terminals -d FEM145 --dnrev A --dnport input --date 2023/07/28 --time 01:35
add_connection.py -u FEM145 --uprev A --upport pwr -d FPS23 --dnrev A --dnport pwr7 --date 2023/07/28 --time 01:35
add_connection.py -u FEM145 --uprev A --upport e -d NBP17 --dnrev A --dnport E7 --date 2023/07/28 --time 01:35
add_connection.py -u FEM145 --uprev A --upport n -d NBP17 --dnrev A --dnport N7 --date 2023/07/28 --time 01:35
add_connection.py -u FDV235 --uprev A --upport terminals -d FEM376 --dnrev A --dnport input --date 2023/07/28 --time 01:35
add_connection.py -u FEM376 --uprev A --upport pwr -d FPS23 --dnrev A --dnport pwr8 --date 2023/07/28 --time 01:35
add_connection.py -u FEM376 --uprev A --upport e -d NBP17 --dnrev A --dnport E8 --date 2023/07/28 --time 01:35
add_connection.py -u FEM376 --uprev A --upport n -d NBP17 --dnrev A --dnport N8 --date 2023/07/28 --time 01:35
add_connection.py -u FEM204 --uprev A --upport pwr -d FPS23 --dnrev A --dnport pwr3 --date 2023/07/28 --time 01:35
add_connection.py -u FEM204 --uprev A --upport e -d NBP17 --dnrev A --dnport E3 --date 2023/07/28 --time 01:35
add_connection.py -u FEM204 --uprev A --upport n -d NBP17 --dnrev A --dnport N3 --date 2023/07/28 --time 01:35
