#! /bin/bash
source ~/.bashrc
echo cc230802_connupd_1655 >> scripts.log
# add_part
add_part.py -p FEM381 -r A -t front-end -m FEM381 --date 2023/07/31 --time 08:05
add_part.py -p FEM382 -r A -t front-end -m FEM382 --date 2023/07/31 --time 08:05
add_part.py -p FEM384 -r A -t front-end -m FEM384 --date 2023/07/31 --time 08:05
add_part.py -p FEM388 -r A -t front-end -m FEM388 --date 2023/07/31 --time 08:05
add_part.py -p FEM313 -r A -t front-end -m FEM313 --date 2023/07/31 --time 11:05
add_part.py -p FEM386 -r A -t front-end -m FEM386 --date 2023/07/31 --time 11:05
add_part.py -p FEM296 -r A -t front-end -m FEM296 --date 2023/07/31 --time 11:05
# add_connection
add_connection.py -u FDV240 --uprev A --upport terminals -d FEM382 --dnrev A --dnport input --date 2023/07/31 --time 08:35
add_connection.py -u FEM382 --uprev A --upport pwr -d FPS23 --dnrev A --dnport pwr1 --date 2023/07/31 --time 08:35
add_connection.py -u FEM382 --uprev A --upport e -d NBP17 --dnrev A --dnport E1 --date 2023/07/31 --time 08:35
add_connection.py -u FEM382 --uprev A --upport n -d NBP17 --dnrev A --dnport N1 --date 2023/07/31 --time 08:35
add_connection.py -u FDV279 --uprev A --upport terminals -d FEM384 --dnrev A --dnport input --date 2023/07/31 --time 08:35
add_connection.py -u FEM384 --uprev A --upport pwr -d FPS23 --dnrev A --dnport pwr4 --date 2023/07/31 --time 08:35
add_connection.py -u FEM384 --uprev A --upport e -d NBP17 --dnrev A --dnport E4 --date 2023/07/31 --time 08:35
add_connection.py -u FEM384 --uprev A --upport n -d NBP17 --dnrev A --dnport N4 --date 2023/07/31 --time 08:35
add_connection.py -u FDV254 --uprev A --upport terminals -d FEM381 --dnrev A --dnport input --date 2023/07/31 --time 08:35
add_connection.py -u FEM381 --uprev A --upport pwr -d FPS23 --dnrev A --dnport pwr11 --date 2023/07/31 --time 08:35
add_connection.py -u FEM381 --uprev A --upport e -d NBP17 --dnrev A --dnport E11 --date 2023/07/31 --time 08:35
add_connection.py -u FEM381 --uprev A --upport n -d NBP17 --dnrev A --dnport N11 --date 2023/07/31 --time 08:35
add_connection.py -u FDV226 --uprev A --upport terminals -d FEM388 --dnrev A --dnport input --date 2023/07/31 --time 08:35
add_connection.py -u FEM388 --uprev A --upport pwr -d FPS23 --dnrev A --dnport pwr12 --date 2023/07/31 --time 08:35
add_connection.py -u FEM388 --uprev A --upport e -d NBP17 --dnrev A --dnport E12 --date 2023/07/31 --time 08:35
add_connection.py -u FEM388 --uprev A --upport n -d NBP17 --dnrev A --dnport N12 --date 2023/07/31 --time 08:35
add_connection.py -u FDV225 --uprev A --upport terminals -d FEM313 --dnrev A --dnport input --date 2023/07/31 --time 11:35
add_connection.py -u FEM313 --uprev A --upport pwr -d FPS23 --dnrev A --dnport pwr5 --date 2023/07/31 --time 11:35
add_connection.py -u FEM313 --uprev A --upport e -d NBP17 --dnrev A --dnport E5 --date 2023/07/31 --time 11:35
add_connection.py -u FEM313 --uprev A --upport n -d NBP17 --dnrev A --dnport N5 --date 2023/07/31 --time 11:35
add_connection.py -u FDV200 --uprev A --upport terminals -d FEM386 --dnrev A --dnport input --date 2023/07/31 --time 11:35
add_connection.py -u FEM386 --uprev A --upport pwr -d FPS23 --dnrev A --dnport pwr9 --date 2023/07/31 --time 11:35
add_connection.py -u FEM386 --uprev A --upport e -d NBP17 --dnrev A --dnport E9 --date 2023/07/31 --time 11:35
add_connection.py -u FEM386 --uprev A --upport n -d NBP17 --dnrev A --dnport N9 --date 2023/07/31 --time 11:35
add_connection.py -u FDV209 --uprev A --upport terminals -d FEM296 --dnrev A --dnport input --date 2023/07/31 --time 11:35
add_connection.py -u FEM296 --uprev A --upport pwr -d FPS23 --dnrev A --dnport pwr10 --date 2023/07/31 --time 11:35
add_connection.py -u FEM296 --uprev A --upport e -d NBP17 --dnrev A --dnport E10 --date 2023/07/31 --time 11:35
add_connection.py -u FEM296 --uprev A --upport n -d NBP17 --dnrev A --dnport N10 --date 2023/07/31 --time 11:35
