#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230913_connupd_1435" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u PAM278 --uprev A --upport n -d SNPC000100 --dnrev A --dnport n0 --date 2023/09/13 --time 14:29
stop_connection.py -u PAM278 --uprev A --upport e -d SNPC000100 --dnrev A --dnport e2 --date 2023/09/13 --time 14:29
stop_connection.py -u PAM279 --uprev A --upport n -d SNPC000100 --dnrev A --dnport n4 --date 2023/09/13 --time 14:29
stop_connection.py -u PAM279 --uprev A --upport e -d SNPC000100 --dnrev A --dnport e6 --date 2023/09/13 --time 14:29
stop_connection.py -u FEM277 --uprev A --upport pwr -d FPS12 --dnrev A --dnport pwr8 --date 2023/09/13 --time 14:29
stop_connection.py -u FEM279 --uprev A --upport pwr -d FPS12 --dnrev A --dnport pwr2 --date 2023/09/13 --time 14:29
stop_connection.py -u FEM307 --uprev A --upport pwr -d FPS12 --dnrev A --dnport pwr3 --date 2023/09/13 --time 14:29
stop_connection.py -u FEM243 --uprev A --upport pwr -d FPS12 --dnrev A --dnport pwr4 --date 2023/09/13 --time 14:29
stop_connection.py -u FEM237 --uprev A --upport pwr -d FPS12 --dnrev A --dnport pwr12 --date 2023/09/13 --time 14:29
stop_connection.py -u FEM273 --uprev A --upport pwr -d FPS12 --dnrev A --dnport pwr10 --date 2023/09/13 --time 14:29
stop_connection.py -u FEM270 --uprev A --upport pwr -d FPS12 --dnrev A --dnport pwr5 --date 2023/09/13 --time 14:29
stop_connection.py -u FPS12 --uprev A --upport rack -d N16 --dnrev A --dnport top --date 2023/09/13 --time 14:29
stop_connection.py -u FEM274 --uprev A --upport pwr -d FPS12 --dnrev A --dnport pwr1 --date 2023/09/13 --time 14:29
stop_connection.py -u FEM280 --uprev A --upport pwr -d FPS12 --dnrev A --dnport pwr6 --date 2023/09/13 --time 14:29
stop_connection.py -u FEM271 --uprev A --upport pwr -d FPS12 --dnrev A --dnport pwr11 --date 2023/09/13 --time 14:29
stop_connection.py -u PAM362 --uprev A --upport e -d SNPC000100 --dnrev A --dnport e10 --date 2023/09/13 --time 14:29
stop_connection.py -u PAM362 --uprev A --upport n -d SNPC000100 --dnrev A --dnport n8 --date 2023/09/13 --time 14:29
stop_connection.py -u FEM276 --uprev A --upport pwr -d FPS12 --dnrev A --dnport pwr7 --date 2023/09/13 --time 14:29
stop_connection.py -u FEM325 --uprev A --upport pwr -d FPS12 --dnrev A --dnport pwr9 --date 2023/09/13 --time 14:29
stop_connection.py -u SNPC000100 --uprev A --upport rack -d N06 --dnrev A --dnport loc3 --date 2023/09/13 --time 14:29
# add parts for gsheet_not_active
add_part.py -p SNPC000104 -r A -t snap -m SNPC000104 --date 2023/09/13 --time 14:05
add_part.py -p FPS30 -r A -t fem-power-supply -m FPS30 --date 2023/09/13 --time 14:05
# add connections for gsheet_not_active
add_connection.py -u FPS30 --uprev A --upport rack -d N16 --dnrev A --dnport top --date 2023/09/13 --time 14:35
add_connection.py -u FEM274 --uprev A --upport pwr -d FPS30 --dnrev A --dnport pwr1 --date 2023/09/13 --time 14:35
add_connection.py -u FEM279 --uprev A --upport pwr -d FPS30 --dnrev A --dnport pwr2 --date 2023/09/13 --time 14:35
add_connection.py -u FEM307 --uprev A --upport pwr -d FPS30 --dnrev A --dnport pwr3 --date 2023/09/13 --time 14:35
add_connection.py -u FEM243 --uprev A --upport pwr -d FPS30 --dnrev A --dnport pwr4 --date 2023/09/13 --time 14:35
add_connection.py -u FEM270 --uprev A --upport pwr -d FPS30 --dnrev A --dnport pwr5 --date 2023/09/13 --time 14:35
add_connection.py -u FEM280 --uprev A --upport pwr -d FPS30 --dnrev A --dnport pwr6 --date 2023/09/13 --time 14:35
add_connection.py -u FEM276 --uprev A --upport pwr -d FPS30 --dnrev A --dnport pwr7 --date 2023/09/13 --time 14:35
add_connection.py -u FEM277 --uprev A --upport pwr -d FPS30 --dnrev A --dnport pwr8 --date 2023/09/13 --time 14:35
add_connection.py -u FEM325 --uprev A --upport pwr -d FPS30 --dnrev A --dnport pwr9 --date 2023/09/13 --time 14:35
add_connection.py -u FEM273 --uprev A --upport pwr -d FPS30 --dnrev A --dnport pwr10 --date 2023/09/13 --time 14:35
add_connection.py -u FEM271 --uprev A --upport pwr -d FPS30 --dnrev A --dnport pwr11 --date 2023/09/13 --time 14:35
add_connection.py -u FEM237 --uprev A --upport pwr -d FPS30 --dnrev A --dnport pwr12 --date 2023/09/13 --time 14:35
add_connection.py -u PAM278 --uprev A --upport e -d SNPC000104 --dnrev A --dnport e2 --date 2023/09/13 --time 14:35
add_connection.py -u PAM278 --uprev A --upport n -d SNPC000104 --dnrev A --dnport n0 --date 2023/09/13 --time 14:35
add_connection.py -u SNPC000104 --uprev A --upport rack -d N06 --dnrev A --dnport loc3 --date 2023/09/13 --time 14:35
add_connection.py -u PAM279 --uprev A --upport e -d SNPC000104 --dnrev A --dnport e6 --date 2023/09/13 --time 14:35
add_connection.py -u PAM279 --uprev A --upport n -d SNPC000104 --dnrev A --dnport n4 --date 2023/09/13 --time 14:35
add_connection.py -u PAM362 --uprev A --upport e -d SNPC000104 --dnrev A --dnport e10 --date 2023/09/13 --time 14:35
add_connection.py -u PAM362 --uprev A --upport n -d SNPC000104 --dnrev A --dnport n8 --date 2023/09/13 --time 14:35
