#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230914_connupd_1927" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u SNPC000034 --uprev A --upport rack -d N17 --dnrev A --dnport loc1 --date 2023/09/14 --time 19:21
stop_connection.py -u PAM383 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e2 --date 2023/09/14 --time 19:21
stop_connection.py -u PAM383 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n0 --date 2023/09/14 --time 19:21
stop_connection.py -u PAM384 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e6 --date 2023/09/14 --time 19:21
stop_connection.py -u PAM384 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n4 --date 2023/09/14 --time 19:21
stop_connection.py -u PAM385 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e10 --date 2023/09/14 --time 19:21
stop_connection.py -u PAM385 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n8 --date 2023/09/14 --time 19:21
stop_connection.py -u SNPC000052 --uprev A --upport rack -d N17 --dnrev A --dnport loc2 --date 2023/09/14 --time 19:21
stop_connection.py -u PAM386 --uprev A --upport e -d SNPC000052 --dnrev A --dnport e2 --date 2023/09/14 --time 19:21
stop_connection.py -u PAM386 --uprev A --upport n -d SNPC000052 --dnrev A --dnport n0 --date 2023/09/14 --time 19:21
stop_connection.py -u PAM387 --uprev A --upport e -d SNPC000052 --dnrev A --dnport e6 --date 2023/09/14 --time 19:21
stop_connection.py -u PAM387 --uprev A --upport n -d SNPC000052 --dnrev A --dnport n4 --date 2023/09/14 --time 19:21
stop_connection.py -u PAM388 --uprev A --upport e -d SNPC000052 --dnrev A --dnport e10 --date 2023/09/14 --time 19:21
stop_connection.py -u PAM388 --uprev A --upport n -d SNPC000052 --dnrev A --dnport n8 --date 2023/09/14 --time 19:21
# add connections for gsheet_not_active
add_connection.py -u PAM383 --uprev A --upport e -d SNPC000052 --dnrev A --dnport e2 --date 2023/09/14 --time 19:27
add_connection.py -u PAM383 --uprev A --upport n -d SNPC000052 --dnrev A --dnport n0 --date 2023/09/14 --time 19:27
add_connection.py -u SNPC000052 --uprev A --upport rack -d N17 --dnrev A --dnport loc1 --date 2023/09/14 --time 19:27
add_connection.py -u PAM384 --uprev A --upport e -d SNPC000052 --dnrev A --dnport e6 --date 2023/09/14 --time 19:27
add_connection.py -u PAM384 --uprev A --upport n -d SNPC000052 --dnrev A --dnport n4 --date 2023/09/14 --time 19:27
add_connection.py -u PAM385 --uprev A --upport e -d SNPC000052 --dnrev A --dnport e10 --date 2023/09/14 --time 19:27
add_connection.py -u PAM385 --uprev A --upport n -d SNPC000052 --dnrev A --dnport n8 --date 2023/09/14 --time 19:27
add_connection.py -u PAM386 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e2 --date 2023/09/14 --time 19:27
add_connection.py -u PAM386 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n0 --date 2023/09/14 --time 19:27
add_connection.py -u SNPC000034 --uprev A --upport rack -d N17 --dnrev A --dnport loc2 --date 2023/09/14 --time 19:27
add_connection.py -u PAM387 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e6 --date 2023/09/14 --time 19:27
add_connection.py -u PAM387 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n4 --date 2023/09/14 --time 19:27
add_connection.py -u PAM388 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e10 --date 2023/09/14 --time 19:27
add_connection.py -u PAM388 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n8 --date 2023/09/14 --time 19:27
