#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230914_connupd_1200" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u PAM223 --uprev A --upport n -d SNPC000078 --dnrev A --dnport n8 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM223 --uprev A --upport e -d SNPC000078 --dnrev A --dnport e10 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM222 --uprev A --upport e -d SNPC000078 --dnrev A --dnport e6 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM222 --uprev A --upport n -d SNPC000078 --dnrev A --dnport n4 --date 2023/09/14 --time 11:54
stop_connection.py -u SNPC000078 --uprev A --upport rack -d N19 --dnrev A --dnport loc0 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM013 --uprev A --upport e -d SNPC000078 --dnrev A --dnport e2 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM013 --uprev A --upport n -d SNPC000078 --dnrev A --dnport n0 --date 2023/09/14 --time 11:54
stop_connection.py -u SNPC000031 --uprev A --upport rack -d N17 --dnrev A --dnport loc0 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM380 --uprev A --upport e -d SNPC000031 --dnrev A --dnport e2 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM380 --uprev A --upport n -d SNPC000031 --dnrev A --dnport n0 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM381 --uprev A --upport e -d SNPC000031 --dnrev A --dnport e6 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM381 --uprev A --upport n -d SNPC000031 --dnrev A --dnport n4 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM382 --uprev A --upport e -d SNPC000031 --dnrev A --dnport e10 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM382 --uprev A --upport n -d SNPC000031 --dnrev A --dnport n8 --date 2023/09/14 --time 11:54
stop_connection.py -u SNPC000087 --uprev A --upport rack -d N17 --dnrev A --dnport loc3 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM389 --uprev A --upport e -d SNPC000087 --dnrev A --dnport e2 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM389 --uprev A --upport n -d SNPC000087 --dnrev A --dnport n0 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM390 --uprev A --upport e -d SNPC000087 --dnrev A --dnport e6 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM390 --uprev A --upport n -d SNPC000087 --dnrev A --dnport n4 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM391 --uprev A --upport e -d SNPC000087 --dnrev A --dnport e10 --date 2023/09/14 --time 11:54
stop_connection.py -u PAM391 --uprev A --upport n -d SNPC000087 --dnrev A --dnport n8 --date 2023/09/14 --time 11:54
# add parts for gsheet_not_active
add_part.py -p SNPC000088 -r A -t snap -m SNPC000088 --date 2023/09/14 --time 11:30
# add connections for gsheet_not_active
add_connection.py -u SNPC000087 --uprev A --upport rack -d N17 --dnrev A --dnport loc0 --date 2023/09/14 --time 12:00
add_connection.py -u PAM380 --uprev A --upport e -d SNPC000087 --dnrev A --dnport e2 --date 2023/09/14 --time 12:00
add_connection.py -u PAM380 --uprev A --upport n -d SNPC000087 --dnrev A --dnport n0 --date 2023/09/14 --time 12:00
add_connection.py -u PAM381 --uprev A --upport e -d SNPC000087 --dnrev A --dnport e6 --date 2023/09/14 --time 12:00
add_connection.py -u PAM381 --uprev A --upport n -d SNPC000087 --dnrev A --dnport n4 --date 2023/09/14 --time 12:00
add_connection.py -u PAM382 --uprev A --upport e -d SNPC000087 --dnrev A --dnport e10 --date 2023/09/14 --time 12:00
add_connection.py -u PAM382 --uprev A --upport n -d SNPC000087 --dnrev A --dnport n8 --date 2023/09/14 --time 12:00
add_connection.py -u SNPC000031 --uprev A --upport rack -d N17 --dnrev A --dnport loc3 --date 2023/09/14 --time 12:00
add_connection.py -u PAM389 --uprev A --upport e -d SNPC000031 --dnrev A --dnport e2 --date 2023/09/14 --time 12:00
add_connection.py -u PAM389 --uprev A --upport n -d SNPC000031 --dnrev A --dnport n0 --date 2023/09/14 --time 12:00
add_connection.py -u PAM390 --uprev A --upport e -d SNPC000031 --dnrev A --dnport e6 --date 2023/09/14 --time 12:00
add_connection.py -u PAM390 --uprev A --upport n -d SNPC000031 --dnrev A --dnport n4 --date 2023/09/14 --time 12:00
add_connection.py -u PAM391 --uprev A --upport e -d SNPC000031 --dnrev A --dnport e10 --date 2023/09/14 --time 12:00
add_connection.py -u PAM391 --uprev A --upport n -d SNPC000031 --dnrev A --dnport n8 --date 2023/09/14 --time 12:00
add_connection.py -u PAM013 --uprev A --upport e -d SNPC000088 --dnrev A --dnport e2 --date 2023/09/14 --time 12:00
add_connection.py -u PAM013 --uprev A --upport n -d SNPC000088 --dnrev A --dnport n0 --date 2023/09/14 --time 12:00
add_connection.py -u SNPC000088 --uprev A --upport rack -d N19 --dnrev A --dnport loc0 --date 2023/09/14 --time 12:00
add_connection.py -u PAM222 --uprev A --upport e -d SNPC000088 --dnrev A --dnport e6 --date 2023/09/14 --time 12:00
add_connection.py -u PAM222 --uprev A --upport n -d SNPC000088 --dnrev A --dnport n4 --date 2023/09/14 --time 12:00
add_connection.py -u PAM223 --uprev A --upport e -d SNPC000088 --dnrev A --dnport e10 --date 2023/09/14 --time 12:00
add_connection.py -u PAM223 --uprev A --upport n -d SNPC000088 --dnrev A --dnport n8 --date 2023/09/14 --time 12:00
