#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/240202_connupd_1149" >> scripts.log 
# stop connections for active_not_gsheet
# add parts for gsheet_not_active
add_part.py -p FDV162 -r A -t feed -m FDV162 --date 2024/02/02 --time 11:19
add_part.py -p FDV140 -r A -t feed -m FDV140 --date 2024/02/02 --time 11:19
# add connections for gsheet_not_active
add_connection.py -u A6 --uprev H --upport focus -d FDV162 --dnrev A --dnport input --date 2024/02/02 --time 11:49
add_connection.py -u A188 --uprev H --upport focus -d FDV140 --dnrev A --dnport input --date 2024/02/02 --time 11:49
add_connection.py -u FDV140 --uprev A --upport terminals -d FEM155 --dnrev A --dnport input --date 2024/02/02 --time 11:49
add_connection.py -u A248 --uprev H --upport focus -d FDV347 --dnrev A --dnport input --date 2024/02/02 --time 11:49
add_connection.py -u A264 --uprev H --upport focus -d FDV348 --dnrev A --dnport input --date 2024/02/02 --time 11:49
