#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/240201_connupd_1635" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u PAM113 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e2 --date 2024/02/01 --time 16:29
stop_connection.py -u PAM113 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n0 --date 2024/02/01 --time 16:29
stop_connection.py -u PAM114 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e6 --date 2024/02/01 --time 16:29
stop_connection.py -u PAM114 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n4 --date 2024/02/01 --time 16:29
stop_connection.py -u A322 --uprev H --upport focus -d FDV328 --dnrev A --dnport input --date 2024/02/01 --time 16:29
stop_connection.py -u FDV328 --uprev A --upport terminals -d FEM312 --dnrev A --dnport input --date 2024/02/01 --time 16:29
stop_connection.py -u PAM115 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e10 --date 2024/02/01 --time 16:29
stop_connection.py -u PAM115 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n8 --date 2024/02/01 --time 16:29
stop_connection.py -u SNPC000034 --uprev A --upport rack -d N05 --dnrev A --dnport loc0 --date 2024/02/01 --time 16:29
# add parts for gsheet_not_active
add_part.py -p FDV314 -r A -t feed -m FDV314 --date 2024/02/01 --time 16:05
add_part.py -p FDV289 -r A -t feed -m FDV289 --date 2024/02/01 --time 16:05
add_part.py -p SNPC000056 -r A -t snap -m SNPC000056 --date 2024/02/01 --time 16:05
# add connections for gsheet_not_active
add_connection.py -u A337 --uprev H --upport focus -d FDV314 --dnrev A --dnport input --date 2024/02/01 --time 16:35
add_connection.py -u PAM113 --uprev A --upport e -d SNPC000056 --dnrev A --dnport e2 --date 2024/02/01 --time 16:35
add_connection.py -u PAM113 --uprev A --upport n -d SNPC000056 --dnrev A --dnport n0 --date 2024/02/01 --time 16:35
add_connection.py -u SNPC000056 --uprev A --upport rack -d N05 --dnrev A --dnport loc0 --date 2024/02/01 --time 16:35
add_connection.py -u PAM114 --uprev A --upport e -d SNPC000056 --dnrev A --dnport e6 --date 2024/02/01 --time 16:35
add_connection.py -u PAM114 --uprev A --upport n -d SNPC000056 --dnrev A --dnport n4 --date 2024/02/01 --time 16:35
add_connection.py -u PAM115 --uprev A --upport e -d SNPC000056 --dnrev A --dnport e10 --date 2024/02/01 --time 16:35
add_connection.py -u PAM115 --uprev A --upport n -d SNPC000056 --dnrev A --dnport n8 --date 2024/02/01 --time 16:35
add_connection.py -u A322 --uprev H --upport focus -d FDV289 --dnrev A --dnport input --date 2024/02/01 --time 16:35
add_connection.py -u FDV289 --uprev A --upport terminals -d FEM312 --dnrev A --dnport input --date 2024/02/01 --time 16:35
