#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/240812_connupd_1035" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u NBP01 --uprev A --upport e6 -d PAM364 --dnrev A --dnport e --date 2024/08/12 --time 10:29
stop_connection.py -u NBP01 --uprev A --upport n6 -d PAM364 --dnrev A --dnport n --date 2024/08/12 --time 10:29
stop_connection.py -u SNPC000063 --uprev A --upport rack -d N01 --dnrev A --dnport loc0 --date 2024/08/12 --time 10:29
stop_connection.py -u PAM210 --uprev A --upport e -d SNPC000063 --dnrev A --dnport e6 --date 2024/08/12 --time 10:29
stop_connection.py -u PAM210 --uprev A --upport n -d SNPC000063 --dnrev A --dnport n4 --date 2024/08/12 --time 10:29
stop_connection.py -u PAM211 --uprev A --upport e -d SNPC000063 --dnrev A --dnport e10 --date 2024/08/12 --time 10:29
stop_connection.py -u PAM211 --uprev A --upport n -d SNPC000063 --dnrev A --dnport n8 --date 2024/08/12 --time 10:29
stop_connection.py -u PAM365 --uprev A --upport n -d SNPC000063 --dnrev A --dnport n0 --date 2024/08/12 --time 10:29
stop_connection.py -u PAM365 --uprev A --upport e -d SNPC000063 --dnrev A --dnport e2 --date 2024/08/12 --time 10:29
stop_connection.py -u FDV148 --uprev A --upport terminals -d FEM217 --dnrev A --dnport input --date 2024/08/12 --time 10:29
stop_connection.py -u FEM217 --uprev A --upport e -d NBP01 --dnrev A --dnport e1 --date 2024/08/12 --time 10:29
stop_connection.py -u FEM217 --uprev A --upport n -d NBP01 --dnrev A --dnport n1 --date 2024/08/12 --time 10:29
stop_connection.py -u FEM217 --uprev A --upport pwr -d FPS15 --dnrev A --dnport pwr1 --date 2024/08/12 --time 10:29
stop_connection.py -u FDV155 --uprev A --upport terminals -d FEM211 --dnrev A --dnport input --date 2024/08/12 --time 10:29
stop_connection.py -u FEM211 --uprev A --upport e -d NBP01 --dnrev A --dnport e2 --date 2024/08/12 --time 10:29
stop_connection.py -u FEM211 --uprev A --upport n -d NBP01 --dnrev A --dnport n2 --date 2024/08/12 --time 10:29
stop_connection.py -u FEM211 --uprev A --upport pwr -d FPS15 --dnrev A --dnport pwr2 --date 2024/08/12 --time 10:29
stop_connection.py -u FDV154 --uprev A --upport terminals -d FEM218 --dnrev A --dnport input --date 2024/08/12 --time 10:29
stop_connection.py -u FEM218 --uprev A --upport e -d NBP01 --dnrev A --dnport e3 --date 2024/08/12 --time 10:29
stop_connection.py -u FEM218 --uprev A --upport n -d NBP01 --dnrev A --dnport n3 --date 2024/08/12 --time 10:29
stop_connection.py -u FEM218 --uprev A --upport pwr -d FPS15 --dnrev A --dnport pwr3 --date 2024/08/12 --time 10:29
stop_connection.py -u FEM703 --uprev A --upport e -d NBP01 --dnrev A --dnport e11 --date 2024/08/12 --time 10:29
stop_connection.py -u FEM703 --uprev A --upport n -d NBP01 --dnrev A --dnport n11 --date 2024/08/12 --time 10:29
stop_connection.py -u FEM703 --uprev A --upport pwr -d FPS15 --dnrev A --dnport pwr11 --date 2024/08/12 --time 10:29
stop_connection.py -u PAM364 --uprev A --upport slot -d PCH13 --dnrev A --dnport slot6 --date 2024/08/12 --time 10:29
stop_connection.py -u PAM364 --uprev A --upport e -d SNPC000071 --dnrev A --dnport e10 --date 2024/08/12 --time 10:29
stop_connection.py -u PAM364 --uprev A --upport n -d SNPC000071 --dnrev A --dnport n8 --date 2024/08/12 --time 10:29
stop_connection.py -u FDV156 --uprev A --upport terminals -d FEM213 --dnrev A --dnport input --date 2024/08/12 --time 10:29
stop_connection.py -u FEM213 --uprev A --upport pwr -d FPS15 --dnrev A --dnport pwr7 --date 2024/08/12 --time 10:29
stop_connection.py -u FEM213 --uprev A --upport e -d NBP01 --dnrev A --dnport e7 --date 2024/08/12 --time 10:29
stop_connection.py -u FEM213 --uprev A --upport n -d NBP01 --dnrev A --dnport n7 --date 2024/08/12 --time 10:29
stop_connection.py -u FDV149 --uprev A --upport terminals -d FEM703 --dnrev A --dnport input --date 2024/08/12 --time 10:29
stop_connection.py -u A6 --uprev H --upport focus -d FDV162 --dnrev A --dnport input --date 2024/08/12 --time 10:29
# add parts for gsheet_not_active
add_part.py -p FEM355 -r A -t front-end -m FEM355 --date 2024/08/12 --time 10:05
add_part.py -p FEM353 -r A -t front-end -m FEM353 --date 2024/08/12 --time 10:05
add_part.py -p FEM345 -r A -t front-end -m FEM345 --date 2024/08/12 --time 10:05
# add connections for gsheet_not_active
add_connection.py -u FDV148 --uprev A --upport terminals -d FEM345 --dnrev A --dnport input --date 2024/08/12 --time 10:35
add_connection.py -u FEM345 --uprev A --upport pwr -d FPS15 --dnrev A --dnport pwr1 --date 2024/08/12 --time 10:35
add_connection.py -u FEM345 --uprev A --upport e -d NBP01 --dnrev A --dnport e1 --date 2024/08/12 --time 10:35
add_connection.py -u FEM345 --uprev A --upport n -d NBP01 --dnrev A --dnport n1 --date 2024/08/12 --time 10:35
add_connection.py -u PAM365 --uprev A --upport e -d SNPC000036 --dnrev A --dnport e2 --date 2024/08/12 --time 10:35
add_connection.py -u PAM365 --uprev A --upport n -d SNPC000036 --dnrev A --dnport n0 --date 2024/08/12 --time 10:35
add_connection.py -u SNPC000036 --uprev A --upport rack -d N01 --dnrev A --dnport loc0 --date 2024/08/12 --time 10:35
add_connection.py -u FDV155 --uprev A --upport terminals -d FEM353 --dnrev A --dnport input --date 2024/08/12 --time 10:35
add_connection.py -u FEM353 --uprev A --upport pwr -d FPS15 --dnrev A --dnport pwr2 --date 2024/08/12 --time 10:35
add_connection.py -u FEM353 --uprev A --upport e -d NBP01 --dnrev A --dnport e2 --date 2024/08/12 --time 10:35
add_connection.py -u FEM353 --uprev A --upport n -d NBP01 --dnrev A --dnport n2 --date 2024/08/12 --time 10:35
add_connection.py -u PAM210 --uprev A --upport e -d SNPC000036 --dnrev A --dnport e6 --date 2024/08/12 --time 10:35
add_connection.py -u PAM210 --uprev A --upport n -d SNPC000036 --dnrev A --dnport n4 --date 2024/08/12 --time 10:35
add_connection.py -u FDV154 --uprev A --upport terminals -d FEM355 --dnrev A --dnport input --date 2024/08/12 --time 10:35
add_connection.py -u FEM355 --uprev A --upport pwr -d FPS15 --dnrev A --dnport pwr3 --date 2024/08/12 --time 10:35
add_connection.py -u FEM355 --uprev A --upport e -d NBP01 --dnrev A --dnport e3 --date 2024/08/12 --time 10:35
add_connection.py -u FEM355 --uprev A --upport n -d NBP01 --dnrev A --dnport n3 --date 2024/08/12 --time 10:35
add_connection.py -u PAM211 --uprev A --upport e -d SNPC000036 --dnrev A --dnport e10 --date 2024/08/12 --time 10:35
add_connection.py -u PAM211 --uprev A --upport n -d SNPC000036 --dnrev A --dnport n8 --date 2024/08/12 --time 10:35
add_connection.py -u FDV156 --uprev A --upport terminals -d FEM212 --dnrev A --dnport input --date 2024/08/12 --time 10:35
add_connection.py -u FEM212 --uprev A --upport pwr -d FPS15 --dnrev A --dnport pwr7 --date 2024/08/12 --time 10:35
add_connection.py -u FEM212 --uprev A --upport e -d NBP01 --dnrev A --dnport e7 --date 2024/08/12 --time 10:35
add_connection.py -u FEM212 --uprev A --upport n -d NBP01 --dnrev A --dnport n7 --date 2024/08/12 --time 10:35
add_connection.py -u FDV149 --uprev A --upport terminals -d FEM357 --dnrev A --dnport input --date 2024/08/12 --time 10:35
add_connection.py -u FEM357 --uprev A --upport pwr -d FPS15 --dnrev A --dnport pwr11 --date 2024/08/12 --time 10:35
add_connection.py -u FEM357 --uprev A --upport e -d NBP01 --dnrev A --dnport e11 --date 2024/08/12 --time 10:35
add_connection.py -u FEM357 --uprev A --upport n -d NBP01 --dnrev A --dnport n11 --date 2024/08/12 --time 10:35
