#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/250211_connupd_2035" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u NCM26 --uprev A --upport rack -d N06 --dnrev A --dnport middle --date 2025/02/11 --time 20:29
stop_connection.py -u FDV126 --uprev A --upport terminals -d FEM220 --dnrev A --dnport input --date 2025/02/11 --time 20:29
stop_connection.py -u FEM220 --uprev A --upport pwr -d FPS13 --dnrev A --dnport pwr2 --date 2025/02/11 --time 20:29
stop_connection.py -u FEM220 --uprev A --upport e -d NBP15 --dnrev A --dnport e2 --date 2025/02/11 --time 20:29
stop_connection.py -u FEM220 --uprev A --upport n -d NBP15 --dnrev A --dnport n2 --date 2025/02/11 --time 20:29
stop_connection.py -u FDV75 --uprev A --upport terminals -d FEM341 --dnrev A --dnport input --date 2025/02/11 --time 20:29
stop_connection.py -u FEM341 --uprev A --upport pwr -d FPS09 --dnrev A --dnport pwr9 --date 2025/02/11 --time 20:29
stop_connection.py -u FEM341 --uprev A --upport e -d NBP03 --dnrev A --dnport e9 --date 2025/02/11 --time 20:29
stop_connection.py -u FEM341 --uprev A --upport n -d NBP03 --dnrev A --dnport n9 --date 2025/02/11 --time 20:29
stop_connection.py -u PAM113 --uprev A --upport e -d SNPC000056 --dnrev A --dnport e2 --date 2025/02/11 --time 20:29
stop_connection.py -u PAM113 --uprev A --upport n -d SNPC000056 --dnrev A --dnport n0 --date 2025/02/11 --time 20:29
stop_connection.py -u SNPC000056 --uprev A --upport rack -d N05 --dnrev A --dnport loc0 --date 2025/02/11 --time 20:29
stop_connection.py -u PAM114 --uprev A --upport e -d SNPC000056 --dnrev A --dnport e6 --date 2025/02/11 --time 20:29
stop_connection.py -u PAM114 --uprev A --upport n -d SNPC000056 --dnrev A --dnport n4 --date 2025/02/11 --time 20:29
stop_connection.py -u PAM115 --uprev A --upport e -d SNPC000056 --dnrev A --dnport e10 --date 2025/02/11 --time 20:29
stop_connection.py -u PAM115 --uprev A --upport n -d SNPC000056 --dnrev A --dnport n8 --date 2025/02/11 --time 20:29
# add parts for gsheet_not_active
add_part.py -p SNPC000109 -r A -t snap -m SNPC000109 --date 2025/02/11 --time 20:05
add_part.py -p NCM28 -r A -t node-control-module -m NCM28 --date 2025/02/11 --time 20:05
add_part.py -p FEM382 -r A -t front-end -m FEM382 --date 2025/02/11 --time 20:05
# add connections for gsheet_not_active
add_connection.py -u FDV126 --uprev A --upport terminals -d FEM382 --dnrev A --dnport input --date 2025/02/11 --time 20:35
add_connection.py -u FEM382 --uprev A --upport pwr -d FPS13 --dnrev A --dnport pwr2 --date 2025/02/11 --time 20:35
add_connection.py -u FEM382 --uprev A --upport e -d NBP15 --dnrev A --dnport e2 --date 2025/02/11 --time 20:35
add_connection.py -u FEM382 --uprev A --upport n -d NBP15 --dnrev A --dnport n2 --date 2025/02/11 --time 20:35
add_connection.py -u FDV75 --uprev A --upport terminals -d FEM304 --dnrev A --dnport input --date 2025/02/11 --time 20:35
add_connection.py -u PAM113 --uprev A --upport e -d SNPC000109 --dnrev A --dnport e2 --date 2025/02/11 --time 20:35
add_connection.py -u PAM113 --uprev A --upport n -d SNPC000109 --dnrev A --dnport n0 --date 2025/02/11 --time 20:35
add_connection.py -u SNPC000109 --uprev A --upport rack -d N05 --dnrev A --dnport loc0 --date 2025/02/11 --time 20:35
add_connection.py -u PAM114 --uprev A --upport e -d SNPC000109 --dnrev A --dnport e6 --date 2025/02/11 --time 20:35
add_connection.py -u PAM114 --uprev A --upport n -d SNPC000109 --dnrev A --dnport n4 --date 2025/02/11 --time 20:35
add_connection.py -u PAM115 --uprev A --upport e -d SNPC000109 --dnrev A --dnport e10 --date 2025/02/11 --time 20:35
add_connection.py -u PAM115 --uprev A --upport n -d SNPC000109 --dnrev A --dnport n8 --date 2025/02/11 --time 20:35
add_connection.py -u NCM28 --uprev A --upport rack -d N06 --dnrev A --dnport middle --date 2025/02/11 --time 20:35
add_connection.py -u FEM304 --uprev A --upport pwr -d FPS09 --dnrev A --dnport pwr9 --date 2025/02/11 --time 20:35
add_connection.py -u FEM304 --uprev A --upport e -d NBP03 --dnrev A --dnport e9 --date 2025/02/11 --time 20:35
add_connection.py -u FEM304 --uprev A --upport n -d NBP03 --dnrev A --dnport n9 --date 2025/02/11 --time 20:35
