#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/250407_connupd_2333" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u A0 --uprev H --upport focus -d FDV1 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A2 --uprev H --upport focus -d FDV8 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A311 --uprev H --upport focus -d FDV833 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A1 --uprev H --upport focus -d FDV2 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FEM018 --uprev A --upport n -d NBP00 --dnrev A --dnport n3 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM018 --uprev A --upport pwr -d FPS01 --dnrev A --dnport pwr3 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM018 --uprev A --upport e -d NBP00 --dnrev A --dnport e3 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM045 --uprev A --upport e -d NBP00 --dnrev A --dnport e4 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM045 --uprev A --upport n -d NBP00 --dnrev A --dnport n4 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM045 --uprev A --upport pwr -d FPS01 --dnrev A --dnport pwr4 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM041 --uprev A --upport e -d NBP00 --dnrev A --dnport e5 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM041 --uprev A --upport n -d NBP00 --dnrev A --dnport n5 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM041 --uprev A --upport pwr -d FPS01 --dnrev A --dnport pwr5 --date 2025/04/07 --time 23:27
stop_connection.py -u N00 --uprev A --upport ground -d ND00 --dnrev A --dnport ground --date 2025/04/07 --time 23:27
stop_connection.py -u FDV1 --uprev A --upport terminals -d FEM016 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FDV8 --uprev A --upport terminals -d FEM040 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FDV2 --uprev A --upport terminals -d FEM018 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FPS01 --uprev A --upport rack -d N00 --dnrev A --dnport top --date 2025/04/07 --time 23:27
stop_connection.py -u PCH01 --uprev A --upport rack -d N00 --dnrev A --dnport bottom --date 2025/04/07 --time 23:27
stop_connection.py -u FEM016 --uprev A --upport pwr -d FPS01 --dnrev A --dnport pwr1 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM016 --uprev A --upport e -d NBP00 --dnrev A --dnport e1 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM016 --uprev A --upport n -d NBP00 --dnrev A --dnport n1 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM040 --uprev A --upport pwr -d FPS01 --dnrev A --dnport pwr2 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM040 --uprev A --upport e -d NBP00 --dnrev A --dnport e2 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM040 --uprev A --upport n -d NBP00 --dnrev A --dnport n2 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM021 --uprev A --upport e -d NBP00 --dnrev A --dnport e6 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM021 --uprev A --upport n -d NBP00 --dnrev A --dnport n6 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM021 --uprev A --upport pwr -d FPS01 --dnrev A --dnport pwr6 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM022 --uprev A --upport e -d NBP00 --dnrev A --dnport e7 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM022 --uprev A --upport n -d NBP00 --dnrev A --dnport n7 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM022 --uprev A --upport pwr -d FPS01 --dnrev A --dnport pwr7 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM023 --uprev A --upport e -d NBP00 --dnrev A --dnport e8 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM023 --uprev A --upport n -d NBP00 --dnrev A --dnport n8 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM023 --uprev A --upport pwr -d FPS01 --dnrev A --dnport pwr8 --date 2025/04/07 --time 23:27
stop_connection.py -u A11 --uprev H --upport focus -d FDV9 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FDV9 --uprev A --upport terminals -d FEM045 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A12 --uprev H --upport focus -d FDV3 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FDV3 --uprev A --upport terminals -d FEM041 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A13 --uprev H --upport focus -d FDV4 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FDV4 --uprev A --upport terminals -d FEM021 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A14 --uprev H --upport focus -d FDV5 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FDV5 --uprev A --upport terminals -d FEM022 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A23 --uprev H --upport focus -d FDV11 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FDV11 --uprev A --upport terminals -d FEM023 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A24 --uprev H --upport focus -d FDV12 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FDV12 --uprev A --upport terminals -d FEM043 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FEM043 --uprev A --upport pwr -d FPS01 --dnrev A --dnport pwr9 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM043 --uprev A --upport e -d NBP00 --dnrev A --dnport e9 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM043 --uprev A --upport n -d NBP00 --dnrev A --dnport n9 --date 2025/04/07 --time 23:27
stop_connection.py -u A25 --uprev H --upport focus -d FDV6 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FDV6 --uprev A --upport terminals -d FEM025 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FEM025 --uprev A --upport pwr -d FPS01 --dnrev A --dnport pwr10 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM025 --uprev A --upport e -d NBP00 --dnrev A --dnport e10 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM025 --uprev A --upport n -d NBP00 --dnrev A --dnport n10 --date 2025/04/07 --time 23:27
stop_connection.py -u A26 --uprev H --upport focus -d FDV7 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FDV7 --uprev A --upport terminals -d FEM027 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FEM027 --uprev A --upport pwr -d FPS01 --dnrev A --dnport pwr11 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM027 --uprev A --upport e -d NBP00 --dnrev A --dnport e11 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM027 --uprev A --upport n -d NBP00 --dnrev A --dnport n11 --date 2025/04/07 --time 23:27
stop_connection.py -u A39 --uprev H --upport focus -d FDV14 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FDV14 --uprev A --upport terminals -d FEM042 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u FEM042 --uprev A --upport pwr -d FPS01 --dnrev A --dnport pwr12 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM042 --uprev A --upport e -d NBP00 --dnrev A --dnport e12 --date 2025/04/07 --time 23:27
stop_connection.py -u FEM042 --uprev A --upport n -d NBP00 --dnrev A --dnport n12 --date 2025/04/07 --time 23:27
stop_connection.py -u N24 --uprev A --upport ground -d ND24 --dnrev A --dnport ground --date 2025/04/07 --time 23:27
stop_connection.py -u A258 --uprev H --upport focus -d FDV295 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A259 --uprev H --upport focus -d FDV301 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A260 --uprev H --upport focus -d FDV327 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A274 --uprev H --upport focus -d FDV294 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A275 --uprev H --upport focus -d FDV296 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A276 --uprev H --upport focus -d FDV293 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A288 --uprev H --upport focus -d FDV303 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A289 --uprev H --upport focus -d FDV300 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u N25 --uprev A --upport ground -d ND25 --dnrev A --dnport ground --date 2025/04/07 --time 23:27
stop_connection.py -u A230 --uprev H --upport focus -d FDV347 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A247 --uprev H --upport focus -d FDV348 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A248 --uprev H --upport focus -d FDV90 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A249 --uprev H --upport focus -d FDV91 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A263 --uprev H --upport focus -d FDV310 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A264 --uprev H --upport focus -d FDV233 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A265 --uprev H --upport focus -d FDV288 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A279 --uprev H --upport focus -d FDV309 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A280 --uprev H --upport focus -d FDV302 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A335 --uprev H --upport focus -d FDV335 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A339 --uprev H --upport focus -d FDV307 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u N26 --uprev A --upport ground -d ND26 --dnrev A --dnport ground --date 2025/04/07 --time 23:27
stop_connection.py -u A296 --uprev H --upport focus -d FDV262 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A297 --uprev H --upport focus -d FDV340 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A298 --uprev H --upport focus -d FDV345 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A308 --uprev H --upport focus -d FDV275 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A309 --uprev H --upport focus -d FDV329 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A310 --uprev H --upport focus -d FDV333 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A330 --uprev H --upport focus -d FDV306 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A334 --uprev H --upport focus -d FDV304 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A338 --uprev H --upport focus -d FDV328 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A341 --uprev H --upport focus -d FDV316 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u NCM24 --uprev A --upport rack -d N28 --dnrev A --dnport middle --date 2025/04/07 --time 23:27
stop_connection.py -u N29 --uprev A --upport ground -d ND29 --dnrev A --dnport ground --date 2025/04/07 --time 23:27
stop_connection.py -u A277 --uprev H --upport focus -d FDV291 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A278 --uprev H --upport focus -d FDV297 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A292 --uprev H --upport focus -d FDV285 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A293 --uprev H --upport focus -d FDV336 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A294 --uprev H --upport focus -d FDV338 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A306 --uprev H --upport focus -d FDV313 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A307 --uprev H --upport focus -d FDV337 --dnrev A --dnport input --date 2025/04/07 --time 23:27
stop_connection.py -u A319 --uprev H --upport focus -d FDV299 --dnrev A --dnport input --date 2025/04/07 --time 23:27
# add parts for gsheet_not_active
add_part.py -p FEM412 -r A -t front-end -m FEM412 --date 2025/04/07 --time 23:03
add_part.py -p FEM396 -r A -t front-end -m FEM396 --date 2025/04/07 --time 23:03
add_part.py -p FEM401 -r A -t front-end -m FEM401 --date 2025/04/07 --time 23:03
add_part.py -p FDV441 -r A -t feed -m FDV441 --date 2025/04/07 --time 23:03
add_part.py -p FEM395 -r A -t front-end -m FEM395 --date 2025/04/07 --time 23:03
add_part.py -p NCM27 -r A -t node-control-module -m NCM27 --date 2025/04/07 --time 23:03
add_part.py -p FEM318 -r A -t front-end -m FEM318 --date 2025/04/07 --time 23:03
add_part.py -p FEM317 -r A -t front-end -m FEM317 --date 2025/04/07 --time 23:03
add_part.py -p FEM408 -r A -t front-end -m FEM408 --date 2025/04/07 --time 23:03
add_part.py -p FEM392 -r A -t front-end -m FEM392 --date 2025/04/07 --time 23:03
add_part.py -p FEM410 -r A -t front-end -m FEM410 --date 2025/04/07 --time 23:03
add_part.py -p FEM400 -r A -t front-end -m FEM400 --date 2025/04/07 --time 23:03
add_part.py -p FDV344 -r A -t feed -m FDV344 --date 2025/04/07 --time 23:03
add_part.py -p FEM405 -r A -t front-end -m FEM405 --date 2025/04/07 --time 23:03
# add connections for gsheet_not_active
add_connection.py -u A342 --uprev H --upport focus -d FDV344 --dnrev A --dnport input --date 2025/04/07 --time 23:33
add_connection.py -u FDV344 --uprev A --upport terminals -d FEM318 --dnrev A --dnport input --date 2025/04/07 --time 23:33
add_connection.py -u FEM318 --uprev A --upport pwr -d FPS28 --dnrev A --dnport pwr1 --date 2025/04/07 --time 23:33
add_connection.py -u FEM318 --uprev A --upport e -d NBP27 --dnrev A --dnport e1 --date 2025/04/07 --time 23:33
add_connection.py -u FEM318 --uprev A --upport n -d NBP27 --dnrev A --dnport n1 --date 2025/04/07 --time 23:33
add_connection.py -u A343 --uprev H --upport focus -d FDV441 --dnrev A --dnport input --date 2025/04/07 --time 23:33
add_connection.py -u FDV441 --uprev A --upport terminals -d FEM405 --dnrev A --dnport input --date 2025/04/07 --time 23:33
add_connection.py -u FEM405 --uprev A --upport pwr -d FPS28 --dnrev A --dnport pwr2 --date 2025/04/07 --time 23:33
add_connection.py -u FEM405 --uprev A --upport e -d NBP27 --dnrev A --dnport e2 --date 2025/04/07 --time 23:33
add_connection.py -u FEM405 --uprev A --upport n -d NBP27 --dnrev A --dnport n2 --date 2025/04/07 --time 23:33
add_connection.py -u FDV341 --uprev A --upport terminals -d FEM395 --dnrev A --dnport input --date 2025/04/07 --time 23:33
add_connection.py -u FEM395 --uprev A --upport pwr -d FPS28 --dnrev A --dnport pwr3 --date 2025/04/07 --time 23:33
add_connection.py -u FEM395 --uprev A --upport e -d NBP27 --dnrev A --dnport e3 --date 2025/04/07 --time 23:33
add_connection.py -u FEM395 --uprev A --upport n -d NBP27 --dnrev A --dnport n3 --date 2025/04/07 --time 23:33
add_connection.py -u FDV311 --uprev A --upport terminals -d FEM412 --dnrev A --dnport input --date 2025/04/07 --time 23:33
add_connection.py -u FEM412 --uprev A --upport pwr -d FPS28 --dnrev A --dnport pwr5 --date 2025/04/07 --time 23:33
add_connection.py -u FEM412 --uprev A --upport e -d NBP27 --dnrev A --dnport e5 --date 2025/04/07 --time 23:33
add_connection.py -u FEM412 --uprev A --upport n -d NBP27 --dnrev A --dnport n5 --date 2025/04/07 --time 23:33
add_connection.py -u FDV308 --uprev A --upport terminals -d FEM392 --dnrev A --dnport input --date 2025/04/07 --time 23:33
add_connection.py -u FEM392 --uprev A --upport pwr -d FPS28 --dnrev A --dnport pwr6 --date 2025/04/07 --time 23:33
add_connection.py -u FEM392 --uprev A --upport e -d NBP27 --dnrev A --dnport e6 --date 2025/04/07 --time 23:33
add_connection.py -u FEM392 --uprev A --upport n -d NBP27 --dnrev A --dnport n6 --date 2025/04/07 --time 23:33
add_connection.py -u FDV321 --uprev A --upport terminals -d FEM400 --dnrev A --dnport input --date 2025/04/07 --time 23:33
add_connection.py -u FEM400 --uprev A --upport pwr -d FPS28 --dnrev A --dnport pwr7 --date 2025/04/07 --time 23:33
add_connection.py -u FEM400 --uprev A --upport e -d NBP27 --dnrev A --dnport e7 --date 2025/04/07 --time 23:33
add_connection.py -u FEM400 --uprev A --upport n -d NBP27 --dnrev A --dnport n7 --date 2025/04/07 --time 23:33
add_connection.py -u FDV343 --uprev A --upport terminals -d FEM401 --dnrev A --dnport input --date 2025/04/07 --time 23:33
add_connection.py -u FEM401 --uprev A --upport pwr -d FPS28 --dnrev A --dnport pwr8 --date 2025/04/07 --time 23:33
add_connection.py -u FEM401 --uprev A --upport e -d NBP27 --dnrev A --dnport e8 --date 2025/04/07 --time 23:33
add_connection.py -u FEM401 --uprev A --upport n -d NBP27 --dnrev A --dnport n8 --date 2025/04/07 --time 23:33
add_connection.py -u FDV320 --uprev A --upport terminals -d FEM317 --dnrev A --dnport input --date 2025/04/07 --time 23:33
add_connection.py -u FEM317 --uprev A --upport pwr -d FPS28 --dnrev A --dnport pwr9 --date 2025/04/07 --time 23:33
add_connection.py -u FEM317 --uprev A --upport e -d NBP27 --dnrev A --dnport e9 --date 2025/04/07 --time 23:33
add_connection.py -u FEM317 --uprev A --upport n -d NBP27 --dnrev A --dnport n9 --date 2025/04/07 --time 23:33
add_connection.py -u FDV284 --uprev A --upport terminals -d FEM410 --dnrev A --dnport input --date 2025/04/07 --time 23:33
add_connection.py -u FEM410 --uprev A --upport pwr -d FPS28 --dnrev A --dnport pwr10 --date 2025/04/07 --time 23:33
add_connection.py -u FEM410 --uprev A --upport e -d NBP27 --dnrev A --dnport e10 --date 2025/04/07 --time 23:33
add_connection.py -u FEM410 --uprev A --upport n -d NBP27 --dnrev A --dnport n10 --date 2025/04/07 --time 23:33
add_connection.py -u A311 --uprev H --upport focus -d FDV333 --dnrev A --dnport input --date 2025/04/07 --time 23:33
add_connection.py -u FDV333 --uprev A --upport terminals -d FEM408 --dnrev A --dnport input --date 2025/04/07 --time 23:33
add_connection.py -u FEM408 --uprev A --upport pwr -d FPS28 --dnrev A --dnport pwr11 --date 2025/04/07 --time 23:33
add_connection.py -u FEM408 --uprev A --upport e -d NBP27 --dnrev A --dnport e11 --date 2025/04/07 --time 23:33
add_connection.py -u FEM408 --uprev A --upport n -d NBP27 --dnrev A --dnport n11 --date 2025/04/07 --time 23:33
add_connection.py -u FDV324 --uprev A --upport terminals -d FEM396 --dnrev A --dnport input --date 2025/04/07 --time 23:33
add_connection.py -u FEM396 --uprev A --upport pwr -d FPS28 --dnrev A --dnport pwr12 --date 2025/04/07 --time 23:33
add_connection.py -u FEM396 --uprev A --upport e -d NBP27 --dnrev A --dnport e12 --date 2025/04/07 --time 23:33
add_connection.py -u FEM396 --uprev A --upport n -d NBP27 --dnrev A --dnport n12 --date 2025/04/07 --time 23:33
add_connection.py -u NCM27 --uprev A --upport rack -d N28 --dnrev A --dnport middle --date 2025/04/07 --time 23:33
