#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/250618_connupd_1035" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u A345 --uprev H --upport focus -d FDV305 --dnrev A --dnport input --date 2025/06/18 --time 10:29
# add connections for gsheet_not_active
add_connection.py -u A344 --uprev H --upport focus -d FDV305 --dnrev A --dnport input --date 2025/06/18 --time 10:35
