#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/250613_connupd_1735" >> scripts.log 
# stop connections for active_not_gsheet
# add connections for gsheet_not_active
add_connection.py -u FDV69 --uprev A --upport terminals -d FEM139 --dnrev A --dnport input --date 2025/06/13 --time 17:35
add_connection.py -u FEM139 --uprev A --upport pwr -d FPS08 --dnrev A --dnport pwr8 --date 2025/06/13 --time 17:35
add_connection.py -u FEM139 --uprev A --upport e -d NBP10 --dnrev A --dnport e8 --date 2025/06/13 --time 17:35
add_connection.py -u FEM139 --uprev A --upport n -d NBP10 --dnrev A --dnport n8 --date 2025/06/13 --time 17:35
