#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/251111_connupd_0000" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u FEM198 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr5 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM198 --uprev A --upport e -d NBP14 --dnrev A --dnport e5 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM198 --uprev A --upport n -d NBP14 --dnrev A --dnport n5 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM369 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr2 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM369 --uprev A --upport e -d NBP14 --dnrev A --dnport e2 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM369 --uprev A --upport n -d NBP14 --dnrev A --dnport n2 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM378 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr3 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM378 --uprev A --upport e -d NBP14 --dnrev A --dnport e3 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM378 --uprev A --upport n -d NBP14 --dnrev A --dnport n3 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM335 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr4 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM335 --uprev A --upport e -d NBP14 --dnrev A --dnport e4 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM335 --uprev A --upport n -d NBP14 --dnrev A --dnport n4 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM135 --uprev A --upport pwr -d FPS09 --dnrev A --dnport pwr2 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM135 --uprev A --upport e -d NBP03 --dnrev A --dnport e2 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM135 --uprev A --upport n -d NBP03 --dnrev A --dnport n2 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM128 --uprev A --upport pwr -d FPS09 --dnrev A --dnport pwr4 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM128 --uprev A --upport e -d NBP03 --dnrev A --dnport e4 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM128 --uprev A --upport n -d NBP03 --dnrev A --dnport n4 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM114 --uprev A --upport pwr -d FPS05 --dnrev A --dnport pwr8 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM114 --uprev A --upport e -d NBP04 --dnrev A --dnport e8 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM114 --uprev A --upport n -d NBP04 --dnrev A --dnport n8 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM112 --uprev A --upport pwr -d FPS05 --dnrev A --dnport pwr9 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM112 --uprev A --upport e -d NBP04 --dnrev A --dnport e9 --date 2025/11/10 --time 23:54
stop_connection.py -u FEM112 --uprev A --upport n -d NBP04 --dnrev A --dnport n9 --date 2025/11/10 --time 23:54
# add connections for gsheet_not_active
add_connection.py -u FEM369 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr5 --date 2025/11/11 --time 00:00
add_connection.py -u FEM369 --uprev A --upport e -d NBP14 --dnrev A --dnport e5 --date 2025/11/11 --time 00:00
add_connection.py -u FEM369 --uprev A --upport n -d NBP14 --dnrev A --dnport n5 --date 2025/11/11 --time 00:00
add_connection.py -u FEM378 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr2 --date 2025/11/11 --time 00:00
add_connection.py -u FEM378 --uprev A --upport e -d NBP14 --dnrev A --dnport e2 --date 2025/11/11 --time 00:00
add_connection.py -u FEM378 --uprev A --upport n -d NBP14 --dnrev A --dnport n2 --date 2025/11/11 --time 00:00
add_connection.py -u FEM335 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr3 --date 2025/11/11 --time 00:00
add_connection.py -u FEM335 --uprev A --upport e -d NBP14 --dnrev A --dnport e3 --date 2025/11/11 --time 00:00
add_connection.py -u FEM335 --uprev A --upport n -d NBP14 --dnrev A --dnport n3 --date 2025/11/11 --time 00:00
add_connection.py -u FEM198 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr4 --date 2025/11/11 --time 00:00
add_connection.py -u FEM198 --uprev A --upport e -d NBP14 --dnrev A --dnport e4 --date 2025/11/11 --time 00:00
add_connection.py -u FEM198 --uprev A --upport n -d NBP14 --dnrev A --dnport n4 --date 2025/11/11 --time 00:00
add_connection.py -u FEM128 --uprev A --upport pwr -d FPS09 --dnrev A --dnport pwr2 --date 2025/11/11 --time 00:00
add_connection.py -u FEM128 --uprev A --upport e -d NBP03 --dnrev A --dnport e2 --date 2025/11/11 --time 00:00
add_connection.py -u FEM128 --uprev A --upport n -d NBP03 --dnrev A --dnport n2 --date 2025/11/11 --time 00:00
add_connection.py -u FEM135 --uprev A --upport pwr -d FPS09 --dnrev A --dnport pwr4 --date 2025/11/11 --time 00:00
add_connection.py -u FEM135 --uprev A --upport e -d NBP03 --dnrev A --dnport e4 --date 2025/11/11 --time 00:00
add_connection.py -u FEM135 --uprev A --upport n -d NBP03 --dnrev A --dnport n4 --date 2025/11/11 --time 00:00
add_connection.py -u FEM112 --uprev A --upport pwr -d FPS05 --dnrev A --dnport pwr8 --date 2025/11/11 --time 00:00
add_connection.py -u FEM112 --uprev A --upport e -d NBP04 --dnrev A --dnport e8 --date 2025/11/11 --time 00:00
add_connection.py -u FEM112 --uprev A --upport n -d NBP04 --dnrev A --dnport n8 --date 2025/11/11 --time 00:00
add_connection.py -u FEM114 --uprev A --upport pwr -d FPS05 --dnrev A --dnport pwr9 --date 2025/11/11 --time 00:00
add_connection.py -u FEM114 --uprev A --upport e -d NBP04 --dnrev A --dnport e9 --date 2025/11/11 --time 00:00
add_connection.py -u FEM114 --uprev A --upport n -d NBP04 --dnrev A --dnport n9 --date 2025/11/11 --time 00:00
