#! /bin/bash
source ~/.bashrc
echo cc230706_connupd_1529 >> scripts.log
# add_part
add_part.py -p NBP17 -r A -t node-bulkhead -m NBP17 --date 2023/06/27 --time 11:05
add_part.py -p PAM388 -r A -t post-amp -m PAM388 --date 2023/06/27 --time 11:05
add_part.py -p PAM391 -r A -t post-amp -m PAM391 --date 2023/06/27 --time 11:05
add_part.py -p PAM385 -r A -t post-amp -m PAM385 --date 2023/06/27 --time 11:05
add_part.py -p PAM382 -r A -t post-amp -m PAM382 --date 2023/06/27 --time 11:05
add_part.py -p PAM384 -r A -t post-amp -m PAM384 --date 2023/06/27 --time 11:05
add_part.py -p PAM390 -r A -t post-amp -m PAM390 --date 2023/06/27 --time 11:05
add_part.py -p PAM380 -r A -t post-amp -m PAM380 --date 2023/06/27 --time 11:05
add_part.py -p PAM381 -r A -t post-amp -m PAM381 --date 2023/06/27 --time 11:05
add_part.py -p PAM383 -r A -t post-amp -m PAM383 --date 2023/06/27 --time 11:05
add_part.py -p PAM387 -r A -t post-amp -m PAM387 --date 2023/06/27 --time 11:05
add_part.py -p PAM386 -r A -t post-amp -m PAM386 --date 2023/06/27 --time 11:05
add_part.py -p PAM389 -r A -t post-amp -m PAM389 --date 2023/06/27 --time 11:05
# stop_connection
stop_connection.py -u FDV24 --uprev A --upport terminals -d FEM032 --dnrev A --dnport input --date 2023/06/10 --time 15:29
stop_connection.py -u FEM032 --uprev A --upport pwr -d FPS02 --dnrev A --dnport pwr8 --date 2023/06/10 --time 15:29
stop_connection.py -u FEM032 --uprev A --upport n -d NBP09 --dnrev A --dnport n8 --date 2023/06/10 --time 15:29
stop_connection.py -u FEM032 --uprev A --upport e -d NBP09 --dnrev A --dnport e8 --date 2023/06/10 --time 15:29
stop_connection.py -u SNPC000087 --uprev A --upport rack -d N17 --dnrev A --dnport loc0 --date 2023/06/27 --time 11:29
stop_connection.py -u SNPC000052 --uprev A --upport rack -d N17 --dnrev A --dnport loc1 --date 2023/06/27 --time 11:29
stop_connection.py -u SNPC000034 --uprev A --upport rack -d N17 --dnrev A --dnport loc2 --date 2023/06/27 --time 11:29
stop_connection.py -u SNPC000031 --uprev A --upport rack -d N17 --dnrev A --dnport loc3 --date 2023/06/27 --time 11:29
# add_connection
add_connection.py -u FDV24 --uprev A --upport terminals -d FEM359 --dnrev A --dnport input --date 2023/06/10 --time 15:35
add_connection.py -u FEM359 --uprev A --upport pwr -d FPS02 --dnrev A --dnport pwr8 --date 2023/06/10 --time 15:35
add_connection.py -u FEM359 --uprev A --upport e -d NBP09 --dnrev A --dnport E8 --date 2023/06/10 --time 15:35
add_connection.py -u FEM359 --uprev A --upport n -d NBP09 --dnrev A --dnport N8 --date 2023/06/10 --time 15:35
add_connection.py -u NCM04 --uprev A --upport rack -d N17 --dnrev A --dnport middle --date 2023/06/27 --time 11:35
add_connection.py -u SNPC000031 --uprev A --upport rack -d N17 --dnrev A --dnport loc0 --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport E1 -d PAM380 --dnrev A --dnport e --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport N1 -d PAM380 --dnrev A --dnport n --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport E2 -d PAM381 --dnrev A --dnport e --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport N2 -d PAM381 --dnrev A --dnport n --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport E3 -d PAM382 --dnrev A --dnport e --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport N3 -d PAM382 --dnrev A --dnport n --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport E4 -d PAM383 --dnrev A --dnport e --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport N4 -d PAM383 --dnrev A --dnport n --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport E5 -d PAM384 --dnrev A --dnport e --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport N5 -d PAM384 --dnrev A --dnport n --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport E6 -d PAM385 --dnrev A --dnport e --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport N6 -d PAM385 --dnrev A --dnport n --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport E7 -d PAM386 --dnrev A --dnport e --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport N7 -d PAM386 --dnrev A --dnport n --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport E8 -d PAM387 --dnrev A --dnport e --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport N8 -d PAM387 --dnrev A --dnport n --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport E9 -d PAM388 --dnrev A --dnport e --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport N9 -d PAM388 --dnrev A --dnport n --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport E10 -d PAM389 --dnrev A --dnport e --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport N10 -d PAM389 --dnrev A --dnport n --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport E11 -d PAM390 --dnrev A --dnport e --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport N11 -d PAM390 --dnrev A --dnport n --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport E12 -d PAM391 --dnrev A --dnport e --date 2023/06/27 --time 11:35
add_connection.py -u NBP17 --uprev A --upport N12 -d PAM391 --dnrev A --dnport n --date 2023/06/27 --time 11:35
add_connection.py -u PAM380 --uprev A --upport e -d SNPC000031 --dnrev A --dnport e2 --date 2023/06/27 --time 11:35
add_connection.py -u PAM380 --uprev A --upport n -d SNPC000031 --dnrev A --dnport n0 --date 2023/06/27 --time 11:35
add_connection.py -u PAM381 --uprev A --upport e -d SNPC000031 --dnrev A --dnport e6 --date 2023/06/27 --time 11:35
add_connection.py -u PAM381 --uprev A --upport n -d SNPC000031 --dnrev A --dnport n4 --date 2023/06/27 --time 11:35
add_connection.py -u PAM382 --uprev A --upport e -d SNPC000031 --dnrev A --dnport e10 --date 2023/06/27 --time 11:35
add_connection.py -u PAM382 --uprev A --upport n -d SNPC000031 --dnrev A --dnport n8 --date 2023/06/27 --time 11:35
add_connection.py -u SNPC000034 --uprev A --upport rack -d N17 --dnrev A --dnport loc1 --date 2023/06/27 --time 11:35
add_connection.py -u PAM383 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e2 --date 2023/06/27 --time 11:35
add_connection.py -u PAM383 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n0 --date 2023/06/27 --time 11:35
add_connection.py -u PAM384 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e6 --date 2023/06/27 --time 11:35
add_connection.py -u PAM384 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n4 --date 2023/06/27 --time 11:35
add_connection.py -u PAM385 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e10 --date 2023/06/27 --time 11:35
add_connection.py -u PAM385 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n8 --date 2023/06/27 --time 11:35
add_connection.py -u SNPC000052 --uprev A --upport rack -d N17 --dnrev A --dnport loc2 --date 2023/06/27 --time 11:35
add_connection.py -u PAM386 --uprev A --upport e -d SNPC000052 --dnrev A --dnport e2 --date 2023/06/27 --time 11:35
add_connection.py -u PAM386 --uprev A --upport n -d SNPC000052 --dnrev A --dnport n0 --date 2023/06/27 --time 11:35
add_connection.py -u PAM387 --uprev A --upport e -d SNPC000052 --dnrev A --dnport e6 --date 2023/06/27 --time 11:35
add_connection.py -u PAM387 --uprev A --upport n -d SNPC000052 --dnrev A --dnport n4 --date 2023/06/27 --time 11:35
add_connection.py -u PAM388 --uprev A --upport e -d SNPC000052 --dnrev A --dnport e10 --date 2023/06/27 --time 11:35
add_connection.py -u PAM388 --uprev A --upport n -d SNPC000052 --dnrev A --dnport n8 --date 2023/06/27 --time 11:35
add_connection.py -u SNPC000087 --uprev A --upport rack -d N17 --dnrev A --dnport loc3 --date 2023/06/27 --time 11:35
add_connection.py -u PAM389 --uprev A --upport e -d SNPC000087 --dnrev A --dnport e2 --date 2023/06/27 --time 11:35
add_connection.py -u PAM389 --uprev A --upport n -d SNPC000087 --dnrev A --dnport n0 --date 2023/06/27 --time 11:35
add_connection.py -u PAM390 --uprev A --upport e -d SNPC000087 --dnrev A --dnport e6 --date 2023/06/27 --time 11:35
add_connection.py -u PAM390 --uprev A --upport n -d SNPC000087 --dnrev A --dnport n4 --date 2023/06/27 --time 11:35
add_connection.py -u PAM391 --uprev A --upport e -d SNPC000087 --dnrev A --dnport e10 --date 2023/06/27 --time 11:35
add_connection.py -u PAM391 --uprev A --upport n -d SNPC000087 --dnrev A --dnport n8 --date 2023/06/27 --time 11:35
