#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/250830_connupd_1935" >> scripts.log 
# stop connections for active_not_gsheet
# add parts for gsheet_not_active
add_part.py -p N24 -r A -t node -m N24 --date 2025/08/30 --time 19:05
add_part.py -p FDV91 -r A -t feed -m FDV91 --date 2025/08/30 --time 19:05
add_part.py -p FDV302 -r A -t feed -m FDV302 --date 2025/08/30 --time 19:05
add_part.py -p N25 -r A -t node -m N25 --date 2025/08/30 --time 19:05
add_part.py -p FDV310 -r A -t feed -m FDV310 --date 2025/08/30 --time 19:05
add_part.py -p FDV90 -r A -t feed -m FDV90 --date 2025/08/30 --time 19:05
add_part.py -p ND25 -r A -t node -m ND25 --date 2025/08/30 --time 19:05
add_part.py -p FDV233 -r A -t feed -m FDV233 --date 2025/08/30 --time 19:05
add_part.py -p FDV327 -r A -t feed -m FDV327 --date 2025/08/30 --time 19:05
add_part.py -p FDV335 -r A -t feed -m FDV335 --date 2025/08/30 --time 19:05
add_part.py -p FDV348 -r A -t feed -m FDV348 --date 2025/08/30 --time 19:05
add_part.py -p ND24 -r A -t node -m ND24 --date 2025/08/30 --time 19:05
add_part.py -p FDV309 -r A -t feed -m FDV309 --date 2025/08/30 --time 19:05
add_part.py -p FDV347 -r A -t feed -m FDV347 --date 2025/08/30 --time 19:05
add_part.py -p FDV288 -r A -t feed -m FDV288 --date 2025/08/30 --time 19:05
# add connections for gsheet_not_active
add_connection.py -u N24 --uprev A --upport ground -d ND24 --dnrev A --dnport ground --date 2025/08/30 --time 19:35
add_connection.py -u A258 --uprev H --upport focus -d FDV295 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A259 --uprev H --upport focus -d FDV301 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A260 --uprev H --upport focus -d FDV327 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A274 --uprev H --upport focus -d FDV294 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A275 --uprev H --upport focus -d FDV296 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A276 --uprev H --upport focus -d FDV293 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A288 --uprev H --upport focus -d FDV303 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A289 --uprev H --upport focus -d FDV300 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u N25 --uprev A --upport ground -d ND25 --dnrev A --dnport ground --date 2025/08/30 --time 19:35
add_connection.py -u A230 --uprev H --upport focus -d FDV347 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A247 --uprev H --upport focus -d FDV348 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A248 --uprev H --upport focus -d FDV90 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A249 --uprev H --upport focus -d FDV91 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A263 --uprev H --upport focus -d FDV310 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A264 --uprev H --upport focus -d FDV233 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A265 --uprev H --upport focus -d FDV288 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A279 --uprev H --upport focus -d FDV309 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A280 --uprev H --upport focus -d FDV302 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u A335 --uprev H --upport focus -d FDV335 --dnrev A --dnport input --date 2025/08/30 --time 19:35
add_connection.py -u SNPC000041 --uprev A --upport rack -d N25 --dnrev A --dnport loc1 --date 2025/08/30 --time 19:35
