#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/250429_connupd_2335" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u FDV238 --uprev A --upport terminals -d FEM1341 --dnrev A --dnport input --date 2025/04/29 --time 23:29
stop_connection.py -u FEM1341 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr12 --date 2025/04/29 --time 23:29
stop_connection.py -u FEM1341 --uprev A --upport e -d NBP23 --dnrev A --dnport e12 --date 2025/04/29 --time 23:29
stop_connection.py -u FEM1341 --uprev A --upport n -d NBP23 --dnrev A --dnport n12 --date 2025/04/29 --time 23:29
# add parts for gsheet_not_active
add_part.py -p FEM409 -r A -t front-end -m FEM409 --date 2025/04/29 --time 23:05
# add connections for gsheet_not_active
add_connection.py -u FDV238 --uprev A --upport terminals -d FEM409 --dnrev A --dnport input --date 2025/04/29 --time 23:35
add_connection.py -u FEM409 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr12 --date 2025/04/29 --time 23:35
add_connection.py -u FEM409 --uprev A --upport e -d NBP23 --dnrev A --dnport e12 --date 2025/04/29 --time 23:35
add_connection.py -u FEM409 --uprev A --upport n -d NBP23 --dnrev A --dnport n12 --date 2025/04/29 --time 23:35
