#! /usr/bin/env bash
echo "190515_add_chain (do_it = True)" >> scripts.log 
add_part.py -p FEM030 -r A -t front-end -m FEM030 --date 2019/05/15 --time 10:00 --actually_do_it
add_part.py -p CRF106 -r A -t cable-rfof -m CRF106 --date 2019/05/15 --time 10:00 --actually_do_it
add_part.py -p PAM044 -r A -t post-amp -m PAM044 --date 2019/05/15 --time 10:00 --actually_do_it
add_part.py -p SNPC000033 -r A -t snap -m SNPC000033 --date 2019/05/15 --time 10:00 --actually_do_it
add_part.py -p N9 -r A -t node -m N9 --date 2019/05/15 --time 10:00 --actually_do_it
add_connection.py -u FDV20 --uprev A --upport terminals -d FEM030 --dnrev A --dnport input --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u FEM030 --uprev A --upport e -d CRF106 --dnrev A --dnport ea --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u FEM030 --uprev A --upport n -d CRF106 --dnrev A --dnport na --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u CRF106 --uprev A --upport eb -d PAM044 --dnrev A --dnport ea --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u CRF106 --uprev A --upport nb -d PAM044 --dnrev A --dnport na --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u PAM044 --uprev A --upport eb -d SNPC000033 --dnrev A --dnport e2 --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u PAM044 --uprev A --upport nb -d SNPC000033 --dnrev A --dnport n0 --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u SNPC000033 --uprev A --upport rack -d N9 --dnrev A --dnport loc3 --date 2019/05/15 --time 11:00 --actually_do_it
add_part.py -p FEM031 -r A -t front-end -m FEM031 --date 2019/05/15 --time 10:00 --actually_do_it
add_part.py -p CRF107 -r A -t cable-rfof -m CRF107 --date 2019/05/15 --time 10:00 --actually_do_it
add_part.py -p PAM035 -r A -t post-amp -m PAM035 --date 2019/05/15 --time 10:00 --actually_do_it
add_part.py -p SNPC000010 -r A -t snap -m SNPC000010 --date 2019/05/15 --time 10:00 --actually_do_it
add_connection.py -u FDV21 --uprev A --upport terminals -d FEM031 --dnrev A --dnport input --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u FEM031 --uprev A --upport e -d CRF107 --dnrev A --dnport ea --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u FEM031 --uprev A --upport n -d CRF107 --dnrev A --dnport na --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u CRF107 --uprev A --upport eb -d PAM035 --dnrev A --dnport ea --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u CRF107 --uprev A --upport nb -d PAM035 --dnrev A --dnport na --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u PAM035 --uprev A --upport eb -d SNPC000010 --dnrev A --dnport e2 --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u PAM035 --uprev A --upport nb -d SNPC000010 --dnrev A --dnport n0 --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u SNPC000010 --uprev A --upport rack -d N9 --dnrev A --dnport loc0 --date 2019/05/15 --time 11:00 --actually_do_it
add_part.py -p FEM029 -r A -t front-end -m FEM029 --date 2019/05/15 --time 10:00 --actually_do_it
add_part.py -p CRF125 -r A -t cable-rfof -m CRF125 --date 2019/05/15 --time 10:00 --actually_do_it
add_part.py -p PAM046 -r A -t post-amp -m PAM046 --date 2019/05/15 --time 10:00 --actually_do_it
add_connection.py -u FDV25 --uprev A --upport terminals -d FEM029 --dnrev A --dnport input --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u FEM029 --uprev A --upport e -d CRF125 --dnrev A --dnport ea --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u FEM029 --uprev A --upport n -d CRF125 --dnrev A --dnport na --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u CRF125 --uprev A --upport eb -d PAM046 --dnrev A --dnport ea --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u CRF125 --uprev A --upport nb -d PAM046 --dnrev A --dnport na --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u PAM046 --uprev A --upport eb -d SNPC000033 --dnrev A --dnport e10 --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u PAM046 --uprev A --upport nb -d SNPC000033 --dnrev A --dnport n8 --date 2019/05/15 --time 11:00 --actually_do_it
add_connection.py -u SNPC000033 --uprev A --upport rack -d N9 --dnrev A --dnport loc3 --date 2019/05/15 --time 11:00 --actually_do_it
