#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230117_infoupd_0942" >> scripts.log 
add_part_info.py -p HH93 -r A -c "FEM141 declared bad and replaced with FEM351" -l "infoupd" --date 2023/01/17 --time 09:42:00
add_part_info.py -p HH93 -r A -c "FEM141 declared bad and replaced with FEM351" -l "infoupd" --date 2023/01/17 --time 09:42:02
