#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230126_infoupd_0842" >> scripts.log 
add_part_info.py -p HH80 -r A -c "Feed heights (NE/SE/SW/NW): 4.409" -l "infoupd" --date 2023/01/26 --time 08:42:00
add_part_info.py -p HH96 -r A -c "Feed heights (NE/SE/SW/NW): 4.409" -l "infoupd" --date 2023/01/26 --time 08:42:00
add_part_info.py -p HH96 -r A -c "Feed heights (NE/SE/SW/NW): 4.409" -l "infoupd" --date 2023/01/26 --time 08:42:02
