#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230125_infoupd_0942" >> scripts.log 
add_part_info.py -p HH109 -r A -c "Reolace FEM with new FEM" -l "infoupd" --date 2023/01/25 --time 09:42:00
add_part_info.py -p HH109 -r A -c "Feed heights (NE/SE/SW/NW): 4.406" -l "infoupd" --date 2023/01/25 --time 09:42:02
add_part_info.py -p HH109 -r A -c "Feed heights (NE/SE/SW/NW): 4.406" -l "infoupd" --date 2023/01/25 --time 09:42:04
add_part_info.py -p HH111 -r A -c "Feed heights (NE/SE/SW/NW): 4.406" -l "infoupd" --date 2023/01/25 --time 09:42:00
add_part_info.py -p HH111 -r A -c "Feed heights (NE/SE/SW/NW): 4.406" -l "infoupd" --date 2023/01/25 --time 09:42:02
add_part_info.py -p HH128 -r A -c "Feed heights (NE/SE/SW/NW): 4.404" -l "infoupd" --date 2023/01/25 --time 09:42:00
add_part_info.py -p HH128 -r A -c "Feed heights (NE/SE/SW/NW): 4.404" -l "infoupd" --date 2023/01/25 --time 09:42:02
