#! /bin/bash
#source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230130_connupd_B" >> scripts.log 

# stop connections for active_not_gsheet
stop_connection.py -u FEM335 --uprev A --upport e -d NBP23 --dnrev A --dnport E5 --date 2023/01/27 --time 07:42
stop_connection.py -u FEM335 --uprev A --upport n -d NBP23 --dnrev A --dnport N5 --date 2023/01/27 --time 07:42
stop_connection.py -u FEM335 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr5 --date 2023/01/27 --time 07:42
stop_connection.py -u FDV231 --uprev A --upport terminals -d FEM338 --dnrev A --dnport input --date 2023/01/27 --time 07:42
stop_connection.py -u FEM338 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr2 --date 2023/01/27 --time 07:42
stop_connection.py -u FEM338 --uprev A --upport e -d NBP23 --dnrev A --dnport E2 --date 2023/01/27 --time 07:42
stop_connection.py -u FEM338 --uprev A --upport n -d NBP23 --dnrev A --dnport N2 --date 2023/01/27 --time 07:42
stop_connection.py -u FDV237 --uprev A --upport terminals -d FEM335 --dnrev A --dnport input --date 2023/01/27 --time 07:42

# add connections for gsheet_not_active
add_connection.py -u FDV89 --uprev A --upport terminals -d FEM371 --dnrev A --dnport input --date 2023/01/25 --time 09:35
add_connection.py -u FEM371 --uprev A --upport pwr -d FPS08 --dnrev A --dnport pwr4 --date 2023/01/25 --time 09:35
add_connection.py -u FEM371 --uprev A --upport e -d NBP10 --dnrev A --dnport E4 --date 2023/01/25 --time 09:35
add_connection.py -u FEM371 --uprev A --upport n -d NBP10 --dnrev A --dnport N4 --date 2023/01/25 --time 09:35
add_connection.py -u FDV239 --uprev A --upport terminals -d FEM370 --dnrev A --dnport input --date 2023/01/26 --time 08:35
add_connection.py -u FEM370 --uprev A --upport pwr -d FPS18 --dnrev A --dnport pwr3 --date 2023/01/26 --time 08:35
add_connection.py -u FEM370 --uprev A --upport e -d NBP11 --dnrev A --dnport E3 --date 2023/01/26 --time 08:35
add_connection.py -u FEM370 --uprev A --upport n -d NBP11 --dnrev A --dnport N3 --date 2023/01/26 --time 08:35
add_connection.py -u FDV268 --uprev A --upport terminals -d FEM372 --dnrev A --dnport input --date 2023/01/26 --time 08:35
add_connection.py -u FEM372 --uprev A --upport pwr -d FPS18 --dnrev A --dnport pwr7 --date 2023/01/26 --time 08:35
add_connection.py -u FEM372 --uprev A --upport e -d NBP11 --dnrev A --dnport E7 --date 2023/01/26 --time 08:35
add_connection.py -u FEM372 --uprev A --upport n -d NBP11 --dnrev A --dnport N7 --date 2023/01/26 --time 08:35
add_connection.py -u FDV125 --uprev A --upport terminals -d FEM335 --dnrev A --dnport input --date 2023/01/27 --time 08:35
add_connection.py -u FEM335 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr4 --date 2023/01/27 --time 08:35
add_connection.py -u FEM335 --uprev A --upport e -d NBP14 --dnrev A --dnport E4 --date 2023/01/27 --time 08:35
add_connection.py -u FEM335 --uprev A --upport n -d NBP14 --dnrev A --dnport N4 --date 2023/01/27 --time 08:35
# add_connection.py -u FDV112 --uprev A --upport terminals -d FEM378 --dnrev A --dnport input --date 2023/01/27 --time 08:35
# add_connection.py -u FEM378 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr3 --date 2023/01/27 --time 08:35
# add_connection.py -u FEM378 --uprev A --upport e -d NBP14 --dnrev A --dnport E3 --date 2023/01/27 --time 08:35
# add_connection.py -u FEM378 --uprev A --upport n -d NBP14 --dnrev A --dnport N3 --date 2023/01/27 --time 08:35
add_connection.py -u FDV115 --uprev A --upport terminals -d FEM375 --dnrev A --dnport input --date 2023/01/27 --time 08:35
add_connection.py -u FEM375 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr6 --date 2023/01/27 --time 08:35
add_connection.py -u FEM375 --uprev A --upport e -d NBP14 --dnrev A --dnport E6 --date 2023/01/27 --time 08:35
add_connection.py -u FEM375 --uprev A --upport n -d NBP14 --dnrev A --dnport N6 --date 2023/01/27 --time 08:35
add_connection.py -u FDV135 --uprev A --upport terminals -d FEM338 --dnrev A --dnport input --date 2023/01/27 --time 08:35
add_connection.py -u FEM338 --uprev A --upport pwr -d FPS16 --dnrev A --dnport pwr12 --date 2023/01/27 --time 08:35
add_connection.py -u FEM338 --uprev A --upport e -d NBP14 --dnrev A --dnport E12 --date 2023/01/27 --time 08:35
add_connection.py -u FEM338 --uprev A --upport n -d NBP14 --dnrev A --dnport N12 --date 2023/01/27 --time 08:35
