#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230220_infoupd_0842" >> scripts.log 
add_part_info.py -p HH92 -r A -c "Feed heights (NE/SE/SW/NW): 4.406" -l "infoupd" --date 2023/02/20 --time 08:42:00
add_part_info.py -p HH92 -r A -c "Feed heights (NE/SE/SW/NW): 4.406" -l "infoupd" --date 2023/02/20 --time 08:42:02
add_part_info.py -p HH93 -r A -c "Feed heights (NE/SE/SW/NW): 4.4" -l "infoupd" --date 2023/02/20 --time 08:42:00
add_part_info.py -p HH93 -r A -c "Feed heights (NE/SE/SW/NW): 4.4" -l "infoupd" --date 2023/02/20 --time 08:42:02
add_part_info.py -p HH94 -r A -c "Feed heights (NE/SE/SW/NW): 4.397" -l "infoupd" --date 2023/02/20 --time 08:42:00
add_part_info.py -p HH94 -r A -c "Feed heights (NE/SE/SW/NW): 4.397" -l "infoupd" --date 2023/02/20 --time 08:42:02
add_part_info.py -p HH110 -r A -c "Feed heights (NE/SE/SW/NW): 4.407" -l "infoupd" --date 2023/02/20 --time 08:42:00
add_part_info.py -p HH110 -r A -c "Feed heights (NE/SE/SW/NW): 4.407" -l "infoupd" --date 2023/02/20 --time 08:42:02
add_part_info.py -p HH111 -r A -c "Feed heights (NE/SE/SW/NW): 4.409" -l "infoupd" --date 2023/02/20 --time 08:42:00
add_part_info.py -p HH111 -r A -c "Feed heights (NE/SE/SW/NW): 4.409" -l "infoupd" --date 2023/02/20 --time 08:42:02
add_part_info.py -p HH112 -r A -c "Feed heights (NE/SE/SW/NW): 4.409" -l "infoupd" --date 2023/02/20 --time 08:42:00
add_part_info.py -p HH112 -r A -c "Feed heights (NE/SE/SW/NW): 4.409" -l "infoupd" --date 2023/02/20 --time 08:42:02
add_part_info.py -p HH128 -r A -c "Feed heights (NE/SE/SW/NW): 4.401" -l "infoupd" --date 2023/02/20 --time 08:42:00
add_part_info.py -p HH128 -r A -c "Feed heights (NE/SE/SW/NW): 4.401" -l "infoupd" --date 2023/02/20 --time 08:42:02
