#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230222_infoupd_1442" >> scripts.log 
add_part_info.py -p HH69 -r A -c "Feed heights: 4,41" -l "infoupd" --date 2023/02/22 --time 14:42:00
add_part_info.py -p HH69 -r A -c "Feed heights: 4.41" -l "infoupd" --date 2023/02/22 --time 14:42:02
add_part_info.py -p HH40 -r A -c "Feed heights: 4.409" -l "infoupd" --date 2023/02/22 --time 14:42:00
add_part_info.py -p HH40 -r A -c "Feed heights: 4.409" -l "infoupd" --date 2023/02/22 --time 14:42:02
add_part_info.py -p HH55 -r A -c "Feed heights: 4.407" -l "infoupd" --date 2023/02/22 --time 14:42:00
add_part_info.py -p HH55 -r A -c "Feed heights: 4.407" -l "infoupd" --date 2023/02/22 --time 14:42:02
add_part_info.py -p HH70 -r A -c "Feed heights: 4.41" -l "infoupd" --date 2023/02/22 --time 14:42:00
add_part_info.py -p HH70 -r A -c "Feed heights: 4.41" -l "infoupd" --date 2023/02/22 --time 14:42:02
add_part_info.py -p HH71 -r A -c "Feed heights: 4.41" -l "infoupd" --date 2023/02/22 --time 14:42:00
add_part_info.py -p HH71 -r A -c "Feed heights: 4.41" -l "infoupd" --date 2023/02/22 --time 14:42:02
add_part_info.py -p HH41 -r A -c "Feed heights: 4.409" -l "infoupd" --date 2023/02/22 --time 14:42:00
add_part_info.py -p HH41 -r A -c "Feed heights: 4.409" -l "infoupd" --date 2023/02/22 --time 14:42:02
add_part_info.py -p HH57 -r A -c "Feed heights: 4.409" -l "infoupd" --date 2023/02/22 --time 14:42:00
add_part_info.py -p HH57 -r A -c "Feed heights: 4.409" -l "infoupd" --date 2023/02/22 --time 14:42:02
