#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230220_infoupd_1142" >> scripts.log 
add_part_info.py -p HH68 -r A -c "replaced fiber" -l "infoupd" --date 2023/02/20 --time 11:42:00
add_part_info.py -p HB320 -r A -c "has a broken sma" -l "infoupd" --date 2023/02/20 --time 11:42:00
