#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230206_infoupd_0942" >> scripts.log 
update_apriori.py -p HH246 -s dish_maintenance --date 2023/02/06 --time 09:48
add_part_info.py -p HH246 -r A -c "apriori_antenna status change: RF_maintenance > dish_maintenance" -l "apa-infoupd" --date 2023/02/06 --time 09:48
