#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230215_infoupd_0042" >> scripts.log 
update_apriori.py -p HH143 -s RF_maintenance --date 2023/02/15 --time 00:48
add_part_info.py -p HH143 -r A -c "apriori_antenna status change: digital_ok > RF_maintenance" -l "apa-infoupd" --date 2023/02/15 --time 00:48
update_apriori.py -p HH145 -s digital_ok --date 2023/02/15 --time 00:48
add_part_info.py -p HH145 -r A -c "apriori_antenna status change: RF_maintenance > digital_ok" -l "apa-infoupd" --date 2023/02/15 --time 00:48
update_apriori.py -p HH166 -s digital_ok --date 2023/02/15 --time 00:48
add_part_info.py -p HH166 -r A -c "apriori_antenna status change: RF_maintenance > digital_ok" -l "apa-infoupd" --date 2023/02/15 --time 00:48
update_apriori.py -p HH185 -s RF_maintenance --date 2023/02/15 --time 00:48
add_part_info.py -p HH185 -r A -c "apriori_antenna status change: digital_ok > RF_maintenance" -l "apa-infoupd" --date 2023/02/15 --time 00:48
add_part_info.py -p HH185 -r A -c "Feed Heights: 4.406" -l "apa-infoupd" --date 2023/02/15 --time 00:42:00
add_part_info.py -p HH166 -r A -c "FEM 180 replaced with FEM 369" -l "apa-infoupd" --date 2023/02/15 --time 00:42:00
add_part_info.py -p HH166 -r A -c "Feed Heights: 4.402" -l "apa-infoupd" --date 2023/02/15 --time 00:42:02
add_part_info.py -p HH184 -r A -c "swapt the old FEM with a new one" -l "infoupd" --date 2023/02/15 --time 00:42:00
add_part_info.py -p HH184 -r A -c "Feed Heights: 4.407" -l "infoupd" --date 2023/02/15 --time 00:42:02
add_part_info.py -p HH145 -r A -c "FEM Switch error -DCJ" -l "apa-infoupd" --date 2023/02/15 --time 00:42:00
