#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230329_infoupd_0942" >> scripts.log 
add_part_info.py -p HH135 -r A -c "Feed heights (NE/SE/SW/NW): 4.403" -l "infoupd" --date 2023/03/29 --time 09:42:00
add_part_info.py -p HH136 -r A -c "Feed heights (NE/SE/SW/NW): 4.405" -l "infoupd" --date 2023/03/29 --time 09:42:00
add_part_info.py -p HH157 -r A -c "Feed heights (NE/SE/SW/NW): 4.406" -l "infoupd" --date 2023/03/29 --time 09:42:00
