#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230328_infoupd_1442" >> scripts.log 
add_part_info.py -p HH176 -r A -c "Feed heights (NE/SE/SW/NW): 4.411" -l "infoupd" --date 2023/03/28 --time 14:42:00
