#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230430_infoupd_1342" >> scripts.log 
add_part_info.py -p HH155 -r A -c "Feed heights (NE/SE/SW/NW): 4.407" -l "infoupd" --date 2023/04/30 --time 13:42:00
add_part_info.py -p HH155 -r A -c "H6C: Feed Height Before: 4.411 Sticker Targets: Already Present Stiffener Braces: Present Already  Carey Caps: Present Already Protected Fiber: Present Already  Cable Conduit: Already Present Spiral Wrap: Present Already D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2023/04/30 --time 13:42:02
add_part_info.py -p HH156 -r A -c "Feed heights (NE/SE/SW/NW): 4.411" -l "infoupd" --date 2023/04/30 --time 13:42:00
add_part_info.py -p HH156 -r A -c "H6C: Feed Height Before: 4.405 Sticker Targets: Already Present Stiffener Braces: Present Already  Carey Caps: Present Already Protected Fiber: Present Already  Cable Conduit: Already Present Spiral Wrap: Present Already D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2023/04/30 --time 13:42:02
add_part_info.py -p HH102 -r A -c "Feed heights (NE/SE/SW/NW): 4.402" -l "infoupd" --date 2023/04/30 --time 13:42:00
add_part_info.py -p HH102 -r A -c "H6C: Feed Height Before: 4.399 Sticker Targets: Already Present Stiffener Braces: Present Already  Carey Caps: Present Already Protected Fiber: Present Already  Cable Conduit: Already Present Spiral Wrap: Present Already D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2023/04/30 --time 13:42:02
add_part_info.py -p HH120 -r A -c "FEM 160 stated on the checksheet" -l "infoupd" --date 2023/04/30 --time 13:42:00
add_part_info.py -p HH120 -r A -c "Feed heights (NE/SE/SW/NW): 4.402" -l "infoupd" --date 2023/04/30 --time 13:42:02
add_part_info.py -p HH120 -r A -c "H6C: Feed Height Before: Broken fiber Sticker Targets: Already Present Stiffener Braces: Present Already  Carey Caps: Present Already Protected Fiber: Present Already  Cable Conduit: Already Present Spiral Wrap: Present Already D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2023/04/30 --time 13:42:04
add_part_info.py -p HH104 -r A -c "Feed heights (NE/SE/SW/NW): 4.410" -l "infoupd" --date 2023/04/30 --time 13:42:00
add_part_info.py -p HH104 -r A -c "H6C: Feed Height Before: 4.396 Sticker Targets: Already Present Stiffener Braces: Present Already  Carey Caps: Present Already Protected Fiber: Present Already  Cable Conduit: Already Present Spiral Wrap: Present Already D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2023/04/30 --time 13:42:02
add_part_info.py -p HH103 -r A -c "FEM 364 stated on the checksheet" -l "infoupd" --date 2023/04/30 --time 13:42:00
add_part_info.py -p HH103 -r A -c "Feed heights (NE/SE/SW/NW): 4.400" -l "infoupd" --date 2023/04/30 --time 13:42:02
add_part_info.py -p HH103 -r A -c "H6C: Feed Height Before: Broken fiber Sticker Targets: Already Present Stiffener Braces: Present Already  Carey Caps: Present Already Protected Fiber: Present Already  Cable Conduit: Already Present Spiral Wrap: Present Already D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2023/04/30 --time 13:42:04
