#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230418_infoupd_2042" >> scripts.log 
add_part_info.py -p HH167 -r A -c "Feed heights (NE/SE/SW/NW): 4.409" -l "infoupd" --date 2023/04/18 --time 20:42:00
add_part_info.py -p HH167 -r A -c "H6C: Feed Height Before: 4.410 Sticker Targets: Already Present Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Installed Spiral Wrap: Installed D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2023/04/18 --time 20:42:02
add_part_info.py -p HH191 -r A -c "Feed heights (NE/SE/SW/NW): 4.409" -l "infoupd" --date 2023/04/18 --time 20:42:00
add_part_info.py -p HH191 -r A -c "H6C: Feed Height Before: 4.401 Sticker Targets: Already Present Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Present already Spiral Wrap: Installed D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2023/04/18 --time 20:42:02
