#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230503_infoupd_1842" >> scripts.log 
add_part_info.py -p HH76 -r A -c "Feed heights (NE/SE/SW/NW): 4.409" -l "infoupd" --date 2023/05/03 --time 18:42:00
add_part_info.py -p HH76 -r A -c "H6C: Feed Height Before: New connection Sticker Targets: Installed Stiffener Braces: Installed Carey Caps: Installed Protected Fiber: Installed Cable Conduit: Installed Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2023/05/03 --time 18:42:02
