#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230506_infoupd_1542" >> scripts.log 
add_part_info.py -p HH84 -r A -c "FEM305 replaced with FEM 376" -l "infoupd" --date 2023/05/06 --time 15:42:00
add_part_info.py -p HH84 -r A -c "Feed heights (NE/SE/SW/NW): 4.413" -l "infoupd" --date 2023/05/06 --time 15:42:02
add_part_info.py -p HH84 -r A -c "H6C: Feed Height Before: 4.407 Sticker Targets: Present Already Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Already Present Spiral Wrap: Installed D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2023/05/06 --time 15:42:04
