#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230517_infoupd_1442" >> scripts.log 
add_part_info.py -p HH47 -r A -c "Feed heights (NE/SE/SW/NW): 4.408" -l "infoupd" --date 2023/05/17 --time 14:42:00
add_part_info.py -p HH47 -r A -c "H6C: Feed Height Before: 4.396 Sticker Targets: Present Already  Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Installed  Spiral Wrap: Present Already D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2023/05/17 --time 14:42:02
add_part_info.py -p HH61 -r A -c "Feed heights (NE/SE/SW/NW): 4.407" -l "infoupd" --date 2023/05/17 --time 14:42:00
add_part_info.py -p HH61 -r A -c "H6C: Feed Height Before: 4.407 Sticker Targets: Present Already  Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Installed  Spiral Wrap: Present Already D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2023/05/17 --time 14:42:02
add_part_info.py -p HH48 -r A -c "FEM 288 changed to FEM 324" -l "infoupd" --date 2023/05/17 --time 14:42:00
add_part_info.py -p HH48 -r A -c "Feed heights (NE/SE/SW/NW): 4.41" -l "infoupd" --date 2023/05/17 --time 14:42:02
add_part_info.py -p HH48 -r A -c "H6C: Feed Height Before: 4.401 Sticker Targets: Present Already  Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Installed  Spiral Wrap: Present Already D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2023/05/17 --time 14:42:04
add_part_info.py -p HH49 -r A -c "Feed heights (NE/SE/SW/NW): 4.409" -l "infoupd" --date 2023/05/17 --time 14:42:00
add_part_info.py -p HH49 -r A -c "H6C: Feed Height Before: 4.401 Sticker Targets: Present Already  Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Installed  Spiral Wrap: Present Already D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2023/05/17 --time 14:42:02
add_part_info.py -p HH62 -r A -c "Feed heights (NE/SE/SW/NW): 4.407" -l "infoupd" --date 2023/05/17 --time 14:42:00
add_part_info.py -p HH62 -r A -c "H6C: Feed Height Before: 4.399 Sticker Targets: Present Already  Stiffener Braces: Present Already Carey Caps: Present Already Protected Fiber: Present Already Cable Conduit: Installed  Spiral Wrap: Present Already D Shackle Cable Tie: Installed Cables Labelled: Completed" -l "infoupd" --date 2023/05/17 --time 14:42:02
