#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230515_infoupd_1142" >> scripts.log 
add_part_info.py -p HH180 -r A -c "Feed heights (NE/SE/SW/NW): 4.406" -l "infoupd" --date 2023/05/15 --time 11:42:00
add_part_info.py -p HH180 -r A -c "H6C: Feed Height Before: 4.409 Sticker Targets: Already Present Stiffener Braces: Present Already  Carey Caps: Present Already Protected Fiber: Present Already  Cable Conduit: Already Present Spiral Wrap: Present Already D Shackle Cable Tie: Already Present Cables Labelled: Completed" -l "infoupd" --date 2023/05/15 --time 11:42:02
