#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230516_infoupd_1742" >> scripts.log 
add_part_info.py -p HH162 -r A -c "autos reasonable -dcj" -l "infoupd" --date 2023/05/16 --time 17:42:00
add_part_info.py -p HH182 -r A -c "looks ok now -dcj" -l "infoupd" --date 2023/05/16 --time 17:42:00
add_part_info.py -p HH183 -r A -c "autos reasonable -dcj" -l "infoupd" --date 2023/05/16 --time 17:42:00
add_part_info.py -p HH140 -r A -c "autos reasonable -dcj" -l "infoupd" --date 2023/05/16 --time 17:42:00
add_part_info.py -p HH142 -r A -c "autos reasonable -dcj" -l "infoupd" --date 2023/05/16 --time 17:42:00
add_part_info.py -p HH180 -r A -c "N pol still dead -dcj" -l "infoupd" --date 2023/05/16 --time 17:42:00
