#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230607_infoupd_1842" >> scripts.log 
add_part_info.py -p HH27 -r A -c "Changed feedthrough (06/07/2023)" -l "infoupd" --date 2023/06/07 --time 18:42:00
add_part_info.py -p HH27 -r A -c "Optical Power (into node): -1.5" -l "infoupd" --date 2023/06/07 --time 18:42:02
add_part_info.py -p HH27 -r A -c "Optical Power (into PAM): -2" -l "infoupd" --date 2023/06/07 --time 18:42:04
add_part_info.py -p HH27 -r A -c "Optical Power (at FEM): 5.8" -l "infoupd" --date 2023/06/07 --time 18:42:06
add_part_info.py -p HH27 -r A -c "Optical Power (through fiber): -34.5" -l "infoupd" --date 2023/06/07 --time 18:42:08
add_part_info.py -p HH27 -r A -c "FEM -> node cables had swapped pols; this was fixed (06/07/2023)" -l "infoupd" --date 2023/06/07 --time 18:42:10
add_part_info.py -p HH27 -r A -c "Optical Power (into node): 3.2" -l "infoupd" --date 2023/06/07 --time 18:42:12
add_part_info.py -p HH27 -r A -c "Optical Power (into PAM): 2.9" -l "infoupd" --date 2023/06/07 --time 18:42:14
add_part_info.py -p HH27 -r A -c "Optical Power (at FEM): 4" -l "infoupd" --date 2023/06/07 --time 18:42:16
add_part_info.py -p HH27 -r A -c "Optical Power (through fiber): -27.6" -l "infoupd" --date 2023/06/07 --time 18:42:18
add_part_info.py -p HH29 -r A -c "Optical Power (at FEM): 6" -l "infoupd" --date 2023/06/07 --time 18:42:00
add_part_info.py -p HH29 -r A -c "Optical Power (through fiber): null" -l "infoupd" --date 2023/06/07 --time 18:42:02
add_part_info.py -p HH29 -r A -c "Optical Power (at FEM): 5.9" -l "infoupd" --date 2023/06/07 --time 18:42:04
add_part_info.py -p HH29 -r A -c "Optical Power (through fiber): null" -l "infoupd" --date 2023/06/07 --time 18:42:06
