#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230607_infoupd_1642" >> scripts.log 
add_part_info.py -p HH92 -r A -c "Optical Power (into node): E: -49.3" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH92 -r A -c "Optical Power (into PAM): E: -49.7" -l "infoupd" --date 2023/06/07 --time 16:42:02
add_part_info.py -p HH93 -r A -c "Optical Power (into node): E: --55.05" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH93 -r A -c "Optical Power (into PAM): E: -55.2" -l "infoupd" --date 2023/06/07 --time 16:42:02
add_part_info.py -p HH93 -r A -c "Optical Power (into node): N: null" -l "infoupd" --date 2023/06/07 --time 16:42:04
add_part_info.py -p HH93 -r A -c "Optical Power (into PAM): N: null" -l "infoupd" --date 2023/06/07 --time 16:42:06
add_part_info.py -p HH94 -r A -c "Optical Power (into node): E: -57" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH94 -r A -c "Optical Power (into PAM): E: null" -l "infoupd" --date 2023/06/07 --time 16:42:02
add_part_info.py -p HH94 -r A -c "Optical Power (into node): N: 1.2" -l "infoupd" --date 2023/06/07 --time 16:42:04
add_part_info.py -p HH94 -r A -c "Optical Power (into PAM): N: -3.9" -l "infoupd" --date 2023/06/07 --time 16:42:06
add_part_info.py -p HH109 -r A -c "Optical Power (into node): E: -1.15" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH109 -r A -c "Optical Power (into PAM): E: -12.35" -l "infoupd" --date 2023/06/07 --time 16:42:02
add_part_info.py -p HH109 -r A -c "Optical Power (into node): N: -4.35" -l "infoupd" --date 2023/06/07 --time 16:42:04
add_part_info.py -p HH109 -r A -c "Optical Power (into PAM): N: -5.25" -l "infoupd" --date 2023/06/07 --time 16:42:06
add_part_info.py -p HH111 -r A -c "Optical Power (into PAM): N: 4.0" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH127 -r A -c "Optical Power (into node): E: null" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH127 -r A -c "Optical Power (into PAM): E: null" -l "infoupd" --date 2023/06/07 --time 16:42:02
add_part_info.py -p HH136 -r A -c "Optical Power (into node): E: null" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH136 -r A -c "Optical Power (into PAM): E: null" -l "infoupd" --date 2023/06/07 --time 16:42:02
add_part_info.py -p HH155 -r A -c "Optical Power (into node): E: null" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH155 -r A -c "Optical Power (into PAM): E: null" -l "infoupd" --date 2023/06/07 --time 16:42:02
add_part_info.py -p HH156 -r A -c "Optical Power (into node): N: 6.50" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH156 -r A -c "Optical Power (into PAM): N: 6.05" -l "infoupd" --date 2023/06/07 --time 16:42:02
add_part_info.py -p HH142 -r A -c "Optical Power (into node): N: 5.8" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH142 -r A -c "Optical Power (into PAM): N: 5.75" -l "infoupd" --date 2023/06/07 --time 16:42:02
add_part_info.py -p HH160 -r A -c "Optical Power (into node): E: null" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH160 -r A -c "Optical Power (into PAM): E: null" -l "infoupd" --date 2023/06/07 --time 16:42:02
add_part_info.py -p HH180 -r A -c "Optical Power (into node): N: 5.8" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH180 -r A -c "Optical Power (into PAM): N: 6.05" -l "infoupd" --date 2023/06/07 --time 16:42:02
add_part_info.py -p HH166 -r A -c "Optical Power (into node): E: -3.45" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH166 -r A -c "Optical Power (into PAM): E: -7.20" -l "infoupd" --date 2023/06/07 --time 16:42:02
add_part_info.py -p HH143 -r A -c "Optical Power (into node): E: -4.85" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH143 -r A -c "Optical Power (into PAM): E: -9.35" -l "infoupd" --date 2023/06/07 --time 16:42:02
add_part_info.py -p HH143 -r A -c "Optical Power (into node): N: null" -l "infoupd" --date 2023/06/07 --time 16:42:04
add_part_info.py -p HH143 -r A -c "Optical Power (into PAM): N: null" -l "infoupd" --date 2023/06/07 --time 16:42:06
add_part_info.py -p HH200 -r A -c "Optical Power (into PAM): 1.7" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH204 -r A -c "Optical Power (into PAM): E: 4.5" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH204 -r A -c "Optical Power (into PAM): N: 5.9" -l "infoupd" --date 2023/06/07 --time 16:42:02
add_part_info.py -p HH207 -r A -c "Optical Power (into node): N: null" -l "infoupd" --date 2023/06/07 --time 16:42:00
add_part_info.py -p HH207 -r A -c "Optical Power (into PAM): N: null" -l "infoupd" --date 2023/06/07 --time 16:42:02
add_part_info.py -p HH225 -r A -c "Optical Power (into PAM): N: 5.2" -l "infoupd" --date 2023/06/07 --time 16:42:00
