#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230604_connupd_1635" >> scripts.log 
# add connections for gsheet_not_active
add_connection.py -u FDV156 --uprev A --upport terminals -d FEM213 --dnrev A --dnport input --date 2023/06/04 --time 16:35
add_connection.py -u FEM213 --uprev A --upport pwr -d FPS15 --dnrev A --dnport pwr7 --date 2023/06/04 --time 16:35
add_connection.py -u FEM213 --uprev A --upport e -d NBP01 --dnrev A --dnport E7 --date 2023/06/04 --time 16:35
add_connection.py -u FEM213 --uprev A --upport n -d NBP01 --dnrev A --dnport N7 --date 2023/06/04 --time 16:35
