#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230610_infoupd_1442" >> scripts.log 
update_apriori.py -p HH118 -s digital_ok --date 2023/06/10 --time 14:48
add_part_info.py -p HH118 -r A -c "apriori_antenna status change: RF_maintenance > digital_ok" -l "apa-infoupd" --date 2023/06/10 --time 14:48
add_part_info.py -p HH29 -r A -c "Optical Power (at FEM): N: 5.9" -l "infoupd" --date 2023/06/10 --time 14:42:00
add_part_info.py -p HH29 -r A -c "Optical Power (through fiber): N: null" -l "infoupd" --date 2023/06/10 --time 14:42:02
add_part_info.py -p HH92 -r A -c "Site crew changed FEM on 6/7/23 (have to check FEM number) but long fiber cable needs to be fixed (6/8/23)" -l "infoupd" --date 2023/06/10 --time 14:42:00
add_part_info.py -p HH92 -r A -c "Optical Power (into node): E: null" -l "infoupd" --date 2023/06/10 --time 14:42:02
add_part_info.py -p HH92 -r A -c "Optical Power (into PAM): E: null" -l "infoupd" --date 2023/06/10 --time 14:42:04
add_part_info.py -p HH92 -r A -c "Optical Power (at FEM): E: -51.5E: 6.4" -l "infoupd" --date 2023/06/10 --time 14:42:06
add_part_info.py -p HH93 -r A -c "Long fiber cable needs to be fixed (6/6/23)" -l "infoupd" --date 2023/06/10 --time 14:42:00
add_part_info.py -p HH93 -r A -c "Optical Power (into node): E: -55.05" -l "infoupd" --date 2023/06/10 --time 14:42:02
add_part_info.py -p HH94 -r A -c "Optical Power (into PAM): N: -0.15" -l "infoupd" --date 2023/06/10 --time 14:42:00
add_part_info.py -p HH58 -r A -c "Optical Power (into node): N: null" -l "infoupd" --date 2023/06/10 --time 14:42:00
add_part_info.py -p HH58 -r A -c "Optical Power (into PAM): N: null" -l "infoupd" --date 2023/06/10 --time 14:42:02
add_part_info.py -p HH58 -r A -c "Optical Power (through fiber): N: null" -l "infoupd" --date 2023/06/10 --time 14:42:04
add_part_info.py -p HH81 -r A -c "Potential PAM issue" -l "infoupd" --date 2023/06/10 --time 14:42:00
add_part_info.py -p HH81 -r A -c "RF Power: E: -24.13" -l "infoupd" --date 2023/06/10 --time 14:42:02
add_part_info.py -p HH81 -r A -c "Need to fix long fiber for N (6/7/23)" -l "infoupd" --date 2023/06/10 --time 14:42:04
add_part_info.py -p HH81 -r A -c "Optical Power (into node): N: null" -l "infoupd" --date 2023/06/10 --time 14:42:06
add_part_info.py -p HH82 -r A -c "Potential PAM issue" -l "infoupd" --date 2023/06/10 --time 14:42:00
add_part_info.py -p HH82 -r A -c "RF Power: E: -21.12" -l "infoupd" --date 2023/06/10 --time 14:42:02
add_part_info.py -p HH83 -r A -c "Potential PAM issue" -l "infoupd" --date 2023/06/10 --time 14:42:00
add_part_info.py -p HH83 -r A -c "RF Power: E:-1.9" -l "infoupd" --date 2023/06/10 --time 14:42:02
add_part_info.py -p HH117 -r A -c "E long fiber needs fixing (6/6/23)." -l "infoupd" --date 2023/06/10 --time 14:42:00
add_part_info.py -p HH117 -r A -c "Optical Power (into PAM): E:- 0.6" -l "infoupd" --date 2023/06/10 --time 14:42:02
add_part_info.py -p HH117 -r A -c "Identified FEM power issue (6/6/23) and site crew fixed FEM power supply (6/6/23)" -l "infoupd" --date 2023/06/10 --time 14:42:04
add_part_info.py -p HH117 -r A -c "Optical Power (into PAM): N: 4.8" -l "infoupd" --date 2023/06/10 --time 14:42:06
add_part_info.py -p HH117 -r A -c "Optical Power (through fiber): N: -25.4" -l "infoupd" --date 2023/06/10 --time 14:42:08
add_part_info.py -p HH137 -r A -c "Changing attenuation setting had no impact on PAM RF output: potential I2C issue (6/9/23)" -l "infoupd" --date 2023/06/10 --time 14:42:00
add_part_info.py -p HH137 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/06/10 --time 14:42:02
add_part_info.py -p HH124 -r A -c "Dead FEM (6/6/23), was replaced by site crew (6/9/23) twice but still not working. Need to replace FEM." -l "infoupd" --date 2023/06/10 --time 14:42:00
add_part_info.py -p HH124 -r A -c "FEM Power?: No" -l "infoupd" --date 2023/06/10 --time 14:42:02
add_part_info.py -p HH124 -r A -c "Optical Power (at FEM): N: null" -l "infoupd" --date 2023/06/10 --time 14:42:04
