#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230615_infoupd_1042" >> scripts.log 
add_part_info.py -p HH117 -r A -c "Changed FEM 015 with 249" -l "infoupd" --date 2023/06/15 --time 10:42:00
