#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230607_connupd_1135" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u PAM025 --uprev A --upport e -d SNPC000085 --dnrev A --dnport e10 --date 2023/06/07 --time 11:29
stop_connection.py -u PAM025 --uprev A --upport n -d SNPC000085 --dnrev A --dnport n8 --date 2023/06/07 --time 11:29
stop_connection.py -u SNPC000085 --uprev A --upport rack -d N20 --dnrev A --dnport loc2 --date 2023/06/07 --time 11:29
stop_connection.py -u PAM041 --uprev A --upport e -d SNPC000085 --dnrev A --dnport e2 --date 2023/06/07 --time 11:29
stop_connection.py -u PAM041 --uprev A --upport n -d SNPC000085 --dnrev A --dnport n0 --date 2023/06/07 --time 11:29
stop_connection.py -u PAM016 --uprev A --upport e -d SNPC000085 --dnrev A --dnport e6 --date 2023/06/07 --time 11:29
stop_connection.py -u PAM016 --uprev A --upport n -d SNPC000085 --dnrev A --dnport n4 --date 2023/06/07 --time 11:29
# add parts for gsheet_not_active
add_part.py -p SNPC000092 -r A -t snap -m SNPC000092 --date 2023/06/07 --time 11:05
# add connections for gsheet_not_active
add_connection.py -u PAM041 --uprev A --upport e -d SNPC000092 --dnrev A --dnport e2 --date 2023/06/07 --time 11:35
add_connection.py -u PAM041 --uprev A --upport n -d SNPC000092 --dnrev A --dnport n0 --date 2023/06/07 --time 11:35
add_connection.py -u SNPC000092 --uprev A --upport rack -d N20 --dnrev A --dnport loc2 --date 2023/06/07 --time 11:35
add_connection.py -u PAM016 --uprev A --upport e -d SNPC000092 --dnrev A --dnport e6 --date 2023/06/07 --time 11:35
add_connection.py -u PAM016 --uprev A --upport n -d SNPC000092 --dnrev A --dnport n4 --date 2023/06/07 --time 11:35
add_connection.py -u PAM025 --uprev A --upport e -d SNPC000092 --dnrev A --dnport e10 --date 2023/06/07 --time 11:35
add_connection.py -u PAM025 --uprev A --upport n -d SNPC000092 --dnrev A --dnport n8 --date 2023/06/07 --time 11:35
