#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230728_infoupd_1942" >> scripts.log 
add_part_info.py -p HH84 -r A -c "Make a temporary FEM number to account for duplications." -l "infoupd" --date 2023/07/28 --time 19:42:00
