#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230728_infoupd_2002" >> scripts.log 
add_part_info.py -p HH16 -r A -c "Made temporary FEM for duplications" -l "infoupd" --date 2023/07/28 --time 20:02:00
