#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/230913_connupd_0400" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u FEM332 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr11 --date 2023/09/13 --time 03:54
stop_connection.py -u FEM332 --uprev A --upport e -d NBP23 --dnrev A --dnport E11 --date 2023/09/13 --time 03:54
stop_connection.py -u FEM332 --uprev A --upport n -d NBP23 --dnrev A --dnport N11 --date 2023/09/13 --time 03:54
stop_connection.py -u FEM339 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr1 --date 2023/09/13 --time 03:54
stop_connection.py -u FEM339 --uprev A --upport e -d NBP23 --dnrev A --dnport E1 --date 2023/09/13 --time 03:54
stop_connection.py -u FEM339 --uprev A --upport n -d NBP23 --dnrev A --dnport N1 --date 2023/09/13 --time 03:54
stop_connection.py -u FDV236 --uprev A --upport terminals -d FEM333 --dnrev A --dnport input --date 2023/09/13 --time 03:54
stop_connection.py -u FEM333 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr3 --date 2023/09/13 --time 03:54
stop_connection.py -u FEM333 --uprev A --upport e -d NBP23 --dnrev A --dnport E3 --date 2023/09/13 --time 03:54
stop_connection.py -u FEM333 --uprev A --upport n -d NBP23 --dnrev A --dnport N3 --date 2023/09/13 --time 03:54
stop_connection.py -u FDV250 --uprev A --upport terminals -d FEM332 --dnrev A --dnport input --date 2023/09/13 --time 03:54
stop_connection.py -u FDV230 --uprev A --upport terminals -d FEM339 --dnrev A --dnport input --date 2023/09/13 --time 03:54
# add parts for gsheet_not_active
add_part.py -p FEM704 -r A -t front-end -m FEM704 --date 2023/09/13 --time 03:30
add_part.py -p FEM178 -r A -t front-end -m FEM178 --date 2023/09/13 --time 03:30
add_part.py -p FEM242 -r A -t front-end -m FEM242 --date 2023/09/13 --time 03:30
add_part.py -p FEM054 -r A -t front-end -m FEM054 --date 2023/09/13 --time 03:30
add_part.py -p FEM390 -r A -t front-end -m FEM390 --date 2023/09/13 --time 03:30
add_part.py -p FEM705 -r A -t front-end -m FEM705 --date 2023/09/13 --time 03:30
add_part.py -p FEM383 -r A -t front-end -m FEM383 --date 2023/09/13 --time 03:30
add_part.py -p FEM706 -r A -t front-end -m FEM706 --date 2023/09/13 --time 03:30
add_part.py -p FEM391 -r A -t front-end -m FEM391 --date 2023/09/13 --time 03:30
add_part.py -p FEM103 -r A -t front-end -m FEM103 --date 2023/09/13 --time 03:30
# add connections for gsheet_not_active
add_connection.py -u FDV346 --uprev A --upport terminals -d FEM178 --dnrev A --dnport input --date 2023/09/13 --time 04:00
add_connection.py -u FEM178 --uprev A --upport pwr -d FPS25 --dnrev A --dnport pwr6 --date 2023/09/13 --time 04:00
add_connection.py -u FEM178 --uprev A --upport e -d NBP22 --dnrev A --dnport E6 --date 2023/09/13 --time 04:00
add_connection.py -u FEM178 --uprev A --upport n -d NBP22 --dnrev A --dnport N6 --date 2023/09/13 --time 04:00
add_connection.py -u FDV266 --uprev A --upport terminals -d FEM704 --dnrev A --dnport input --date 2023/09/13 --time 04:00
add_connection.py -u FEM704 --uprev A --upport pwr -d FPS25 --dnrev A --dnport pwr11 --date 2023/09/13 --time 04:00
add_connection.py -u FEM704 --uprev A --upport e -d NBP22 --dnrev A --dnport E11 --date 2023/09/13 --time 04:00
add_connection.py -u FEM704 --uprev A --upport n -d NBP22 --dnrev A --dnport N11 --date 2023/09/13 --time 04:00
add_connection.py -u FDV231 --uprev A --upport terminals -d FEM391 --dnrev A --dnport input --date 2023/09/13 --time 04:00
add_connection.py -u FEM391 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr2 --date 2023/09/13 --time 04:00
add_connection.py -u FEM391 --uprev A --upport e -d NBP23 --dnrev A --dnport E2 --date 2023/09/13 --time 04:00
add_connection.py -u FEM391 --uprev A --upport n -d NBP23 --dnrev A --dnport N2 --date 2023/09/13 --time 04:00
add_connection.py -u FDV236 --uprev A --upport terminals -d FEM706 --dnrev A --dnport input --date 2023/09/13 --time 04:00
add_connection.py -u FEM706 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr3 --date 2023/09/13 --time 04:00
add_connection.py -u FEM706 --uprev A --upport e -d NBP23 --dnrev A --dnport E3 --date 2023/09/13 --time 04:00
add_connection.py -u FEM706 --uprev A --upport n -d NBP23 --dnrev A --dnport N3 --date 2023/09/13 --time 04:00
add_connection.py -u FDV269 --uprev A --upport terminals -d FEM242 --dnrev A --dnport input --date 2023/09/13 --time 04:00
add_connection.py -u FEM242 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr4 --date 2023/09/13 --time 04:00
add_connection.py -u FEM242 --uprev A --upport e -d NBP23 --dnrev A --dnport E4 --date 2023/09/13 --time 04:00
add_connection.py -u FEM242 --uprev A --upport n -d NBP23 --dnrev A --dnport N4 --date 2023/09/13 --time 04:00
add_connection.py -u FDV237 --uprev A --upport terminals -d FEM390 --dnrev A --dnport input --date 2023/09/13 --time 04:00
add_connection.py -u FEM390 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr5 --date 2023/09/13 --time 04:00
add_connection.py -u FEM390 --uprev A --upport e -d NBP23 --dnrev A --dnport E5 --date 2023/09/13 --time 04:00
add_connection.py -u FEM390 --uprev A --upport n -d NBP23 --dnrev A --dnport N5 --date 2023/09/13 --time 04:00
add_connection.py -u FDV238 --uprev A --upport terminals -d FEM705 --dnrev A --dnport input --date 2023/09/13 --time 04:00
add_connection.py -u FEM705 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr6 --date 2023/09/13 --time 04:00
add_connection.py -u FEM705 --uprev A --upport e -d NBP23 --dnrev A --dnport E6 --date 2023/09/13 --time 04:00
add_connection.py -u FEM705 --uprev A --upport n -d NBP23 --dnrev A --dnport N6 --date 2023/09/13 --time 04:00
add_connection.py -u FDV218 --uprev A --upport terminals -d FEM103 --dnrev A --dnport input --date 2023/09/13 --time 04:00
add_connection.py -u FEM103 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr8 --date 2023/09/13 --time 04:00
add_connection.py -u FEM103 --uprev A --upport e -d NBP23 --dnrev A --dnport E8 --date 2023/09/13 --time 04:00
add_connection.py -u FEM103 --uprev A --upport n -d NBP23 --dnrev A --dnport N8 --date 2023/09/13 --time 04:00
add_connection.py -u FDV255 --uprev A --upport terminals -d FEM054 --dnrev A --dnport input --date 2023/09/13 --time 04:00
add_connection.py -u FEM054 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr9 --date 2023/09/13 --time 04:00
add_connection.py -u FEM054 --uprev A --upport e -d NBP23 --dnrev A --dnport E9 --date 2023/09/13 --time 04:00
add_connection.py -u FEM054 --uprev A --upport n -d NBP23 --dnrev A --dnport N9 --date 2023/09/13 --time 04:00
add_connection.py -u FDV249 --uprev A --upport terminals -d FEM383 --dnrev A --dnport input --date 2023/09/13 --time 04:00
add_connection.py -u FEM383 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr10 --date 2023/09/13 --time 04:00
add_connection.py -u FEM383 --uprev A --upport e -d NBP23 --dnrev A --dnport E10 --date 2023/09/13 --time 04:00
add_connection.py -u FEM383 --uprev A --upport n -d NBP23 --dnrev A --dnport N10 --date 2023/09/13 --time 04:00
