#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/231129_infoupd_2042" >> scripts.log 
add_part_info.py -p HH51 -r A -c "dish door warps upwards" -l "infoupd" --date 2023/11/29 --time 20:42:00
