#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/231201_infoupd_1942" >> scripts.log 
add_part_info.py -p HH38 -r A -c "Door is open" -l "infoupd" --date 2023/12/01 --time 19:42:00
