#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/231201_infoupd_1842" >> scripts.log 
add_part_info.py -p HH65 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:00
add_part_info.py -p HH65 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:02
add_part_info.py -p HH66 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:00
add_part_info.py -p HH66 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:02
add_part_info.py -p HH67 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:00
add_part_info.py -p HH67 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:02
add_part_info.py -p HH68 -r A -c "E: Replaced feedthrough 6/2/23" -l "infoupd" --date 2023/12/01 --time 18:42:00
add_part_info.py -p HH68 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:02
add_part_info.py -p HH68 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:04
add_part_info.py -p HH37 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:00
add_part_info.py -p HH37 -r A -c "N: Replaced feedthrough 6/2/23" -l "infoupd" --date 2023/12/01 --time 18:42:02
add_part_info.py -p HH37 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:04
add_part_info.py -p HH38 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:00
add_part_info.py -p HH38 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:02
add_part_info.py -p HH53 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:00
add_part_info.py -p HH53 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:02
add_part_info.py -p HB320 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:00
add_part_info.py -p HB320 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:02
add_part_info.py -p HH51 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:00
add_part_info.py -p HH51 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:02
add_part_info.py -p HH52 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:00
add_part_info.py -p HH52 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:02
add_part_info.py -p HH36 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:00
add_part_info.py -p HH36 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:02
add_part_info.py -p HH50 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:00
add_part_info.py -p HH50 -r A -c "FEM Power?: Yes" -l "infoupd" --date 2023/12/01 --time 18:42:02
