#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/231204_infoupd_2042" >> scripts.log 
add_part_info.py -p HH66 -r A -c "Fiber was reseated at PAM input (06/07/2023)" -l "infoupd" --date 2023/12/04 --time 20:42:00
