#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/240920_infoupd_1742" >> scripts.log 
add_part_info.py -p HH213 -r A -c "PAM 292 wasnt switching attenuation" -l "infoupd" --date 2024/09/20 --time 17:42:00
