#! /bin/bash
source ~/.bashrc
echo "200212_infoupd_2042" >> scripts.log 
update_apriori.py -p HH53 -s RF_ok --date 2020/02/12 --time 20:42
update_apriori.py -p HH65 -s RF_maintenance --date 2020/02/12 --time 20:42
update_apriori.py -p HH66 -s RF_maintenance --date 2020/02/12 --time 20:42
update_apriori.py -p HH86 -s RF_maintenance --date 2020/02/12 --time 20:42
update_apriori.py -p HH87 -s RF_maintenance --date 2020/02/12 --time 20:42
update_apriori.py -p HH103 -s RF_maintenance --date 2020/02/12 --time 20:42
update_apriori.py -p HH109 -s RF_maintenance --date 2020/02/12 --time 20:42
update_apriori.py -p HH121 -s RF_maintenance --date 2020/02/12 --time 20:42
update_apriori.py -p HH123 -s RF_maintenance --date 2020/02/12 --time 20:42
add_part_info.py -p HH109 -r A -c "Door is open" -l "infoupd" --date 2020/02/12 --time 20:42:00
add_part_info.py -p HH178 -r A -c "No final check spectra - Preliminary specrta looks fine" -l "infoupd" --date 2020/02/12 --time 20:42:00
add_part_info.py -p HH178 -r A -c "No final check spectra - Preliminary specrta looks fine" -l "infoupd" --date 2020/02/12 --time 20:42:02
add_part_info.py -p HH66 -r A -c "loose central line" -l "infoupd" --date 2020/02/12 --time 20:42:00
add_part_info.py -p HH86 -r A -c "loose central line" -l "infoupd" --date 2020/02/12 --time 20:42:00
add_part_info.py -p HH87 -r A -c "loose central line" -l "infoupd" --date 2020/02/12 --time 20:42:00
add_part_info.py -p HH103 -r A -c "loose central line" -l "infoupd" --date 2020/02/12 --time 20:42:00
add_part_info.py -p HH121 -r A -c "loose central line" -l "infoupd" --date 2020/02/12 --time 20:42:00
add_part_info.py -p HH123 -r A -c "loose central line" -l "infoupd" --date 2020/02/12 --time 20:42:00
