#! /bin/bash
source ~/.bashrc
echo "200211_infoupd_1442" >> scripts.log 
update_apriori.py -p HH135 -s RF_ok --date 2020/02/11 --time 14:42
update_apriori.py -p HH136 -s RF_ok --date 2020/02/11 --time 14:42
update_apriori.py -p HH155 -s RF_ok --date 2020/02/11 --time 14:42
update_apriori.py -p HH157 -s RF_ok --date 2020/02/11 --time 14:42
update_apriori.py -p HH158 -s RF_ok --date 2020/02/11 --time 14:42
update_apriori.py -p HH177 -s RF_ok --date 2020/02/11 --time 14:42
update_apriori.py -p HH179 -s RF_ok --date 2020/02/11 --time 14:42
add_part_info.py -p HH135 -r A -c "Final specrta looks fine" -l "infoupd" --date 2020/02/11 --time 14:42:00
add_part_info.py -p HH135 -r A -c "Final specrta looks fine" -l "infoupd" --date 2020/02/11 --time 14:42:02
add_part_info.py -p HH136 -r A -c "Final specrta looks fine" -l "infoupd" --date 2020/02/11 --time 14:42:00
add_part_info.py -p HH136 -r A -c "Final specrta looks fine" -l "infoupd" --date 2020/02/11 --time 14:42:02
add_part_info.py -p HH155 -r A -c "Final specrta looks fine" -l "infoupd" --date 2020/02/11 --time 14:42:00
add_part_info.py -p HH155 -r A -c "Final specrta looks fine" -l "infoupd" --date 2020/02/11 --time 14:42:02
add_part_info.py -p HH156 -r A -c "Strange bumps in final spectra for 156E - will ask for a check" -l "infoupd" --date 2020/02/11 --time 14:42:00
add_part_info.py -p HH156 -r A -c "Final spectre looks fine" -l "infoupd" --date 2020/02/11 --time 14:42:02
add_part_info.py -p HH157 -r A -c "Final spectre looks fine" -l "infoupd" --date 2020/02/11 --time 14:42:00
add_part_info.py -p HH157 -r A -c "Final spectre looks fine" -l "infoupd" --date 2020/02/11 --time 14:42:02
add_part_info.py -p HH158 -r A -c "Final spectre looks fine" -l "infoupd" --date 2020/02/11 --time 14:42:00
add_part_info.py -p HH158 -r A -c "Feed heights (NE/SE/SW/NW): z distance = 4.411" -l "infoupd" --date 2020/02/11 --time 14:42:02
add_part_info.py -p HH158 -r A -c "Final spectre looks fine" -l "infoupd" --date 2020/02/11 --time 14:42:04
add_part_info.py -p HH177 -r A -c "Final spectra looks fine" -l "infoupd" --date 2020/02/11 --time 14:42:00
add_part_info.py -p HH177 -r A -c "Final spectra looks fine" -l "infoupd" --date 2020/02/11 --time 14:42:02
add_part_info.py -p HH179 -r A -c "Final spectre looks fine" -l "infoupd" --date 2020/02/11 --time 14:42:00
add_part_info.py -p HH179 -r A -c "Final spectre looks fine" -l "infoupd" --date 2020/02/11 --time 14:42:02
