#! /bin/bash
source ~/.bashrc
echo "200223_infoupd_1442" >> scripts.log 
update_apriori.py -p HH86 -s RF_ok --date 2020/02/23 --time 14:42
update_apriori.py -p HH103 -s RF_ok --date 2020/02/23 --time 14:42
update_apriori.py -p HH104 -s RF_ok --date 2020/02/23 --time 14:42
update_apriori.py -p HH122 -s RF_ok --date 2020/02/23 --time 14:42
add_part_info.py -p HH86 -r A -c "z = 4.414" -l "infoupd" --date 2020/02/23 --time 14:42:00
add_part_info.py -p HH103 -r A -c "Z = 4.409" -l "infoupd" --date 2020/02/23 --time 14:42:00
add_part_info.py -p HH104 -r A -c "Z = 4.409" -l "infoupd" --date 2020/02/23 --time 14:42:00
add_part_info.py -p HH104 -r A -c " " -l "infoupd" --date 2020/02/23 --time 14:42:02
add_part_info.py -p HH120 -r A -c "Z = 4.411" -l "infoupd" --date 2020/02/23 --time 14:42:00
add_part_info.py -p HH122 -r A -c "Z = 4.414" -l "infoupd" --date 2020/02/23 --time 14:42:00
add_part_info.py -p HH122 -r A -c " " -l "infoupd" --date 2020/02/23 --time 14:42:02
