#! /bin/bash
source ~/.bashrc
echo "200207_infoupd_1742" >> scripts.log 
update_apriori.py -p HH84 -s RF_ok --date 2020/02/07 --time 17:42
update_apriori.py -p HH86 -s RF_ok --date 2020/02/07 --time 17:42
update_apriori.py -p HH87 -s RF_ok --date 2020/02/07 --time 17:42
update_apriori.py -p HH92 -s RF_ok --date 2020/02/07 --time 17:42
update_apriori.py -p HH93 -s RF_ok --date 2020/02/07 --time 17:42
update_apriori.py -p HH94 -s RF_ok --date 2020/02/07 --time 17:42
update_apriori.py -p HH102 -s RF_ok --date 2020/02/07 --time 17:42
update_apriori.py -p HH103 -s RF_ok --date 2020/02/07 --time 17:42
update_apriori.py -p HH109 -s RF_ok --date 2020/02/07 --time 17:42
update_apriori.py -p HH111 -s RF_ok --date 2020/02/07 --time 17:42
update_apriori.py -p HH112 -s RF_ok --date 2020/02/07 --time 17:42
update_apriori.py -p HH120 -s RF_ok --date 2020/02/07 --time 17:42
update_apriori.py -p HH121 -s RF_ok --date 2020/02/07 --time 17:42
update_apriori.py -p HH123 -s RF_ok --date 2020/02/07 --time 17:42
update_apriori.py -p HH129 -s dish_maintenance --date 2020/02/07 --time 17:42
add_part_info.py -p HH127 -r A -c "Was seen as not raised 29 Jan 2020" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH127 -r A -c "Was seen as not raised 29 Jan 2020" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH128 -r A -c "Central line too loose to be RF OK, door mesh in dish; 'nicest dish' candidate; spectra look great" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH128 -r A -c "Central line too loose to be RF OK, door mesh in dish; 'nicest dish' candidate; spectra look great" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH129 -r A -c "129E very attenuated; 129N looks fine. Has no door, but piece of mesh in dish (curled up and protruding ~40 cm) likely is for the door. Broken PVC rib SE - ~ 3 cm discontinuity" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH129 -r A -c "129E very attenuated; 129N looks fine. Has no door, but piece of mesh in dish (curled up and protruding ~40 cm) likely is for the door. Broken PVC rib SE - ~ 3 cm discontinuity" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH130 -r A -c "Central line too loose to be RF OK, door mesh in dish" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH130 -r A -c "Central line too loose to be RF OK, door mesh in dish" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH177 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH177 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH178 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH178 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH179 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH179 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH135 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH135 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH136 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH136 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH155 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH155 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH156 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH156 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH157 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH157 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH158 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH158 -r A -c "Preliminary specrta looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH140 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH140 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH141 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH141 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH142 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH142 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH160 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH160 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH161 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH161 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH162 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH162 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH180 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH180 -r A -c "Preliminary post-PAM spectra is very low amplitude but not dead" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH181 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH181 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH182 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH182 -r A -c "Preliminary post-PAM spectra looks fine" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH183 -r A -c "Preliminary post-PAM spectra shows 183 N, E dead" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH183 -r A -c "Preliminary post-PAM spectra shows 183 N, E dead" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH116 -r A -c "Post-PAM spectra of 116E has a strange look." -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH85 -r A -c "Feed down as of 31 Jan 2020" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH85 -r A -c "Feed down as of 31 Jan 2020" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH101 -r A -c "101E and N look dead from post-PAM spectra taken the last week of Jan 2020" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH101 -r A -c "101E and N look dead from post-PAM spectra taken the last week of Jan 2020" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH102 -r A -c " " -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH104 -r A -c "Feed down as of 31 Jan 2020" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH104 -r A -c "Feed down as of 31 Jan 2020" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH120 -r A -c " " -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH122 -r A -c "Feed down as of 31 Jan 2020" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH122 -r A -c "Feed down as of 31 Jan 2020" -l "infoupd" --date 2020/02/07 --time 17:42:02
add_part_info.py -p HH106 -r A -c "Late Jan 2020 post-PAM spectra show N pol about half the amplitude of E pol. 31Jan2020 Measured center of feed as differing from center of hub by 2-3 cm. Z= [ 4.424 4.423] from hub (spec is 4.428-4.448)" -l "infoupd" --date 2020/02/07 --time 17:42:00
add_part_info.py -p HH106 -r A -c "Late Jan 2020 post-PAM spectra show N pol about half the amplitude of E pol. 31Jan2020 Measured center of feed as differing from center of hub by 2-3 cm. Z= [ 4.424 4.423] from hub (spec is 4.428-4.448)" -l "infoupd" --date 2020/02/07 --time 17:42:02
