#! /bin/bash
source ~/.bashrc
echo "200317_infoupd_0842" >> scripts.log 
add_part_info.py -p HH141 -r A -c "lz" -l "infoupd" --date 2020/03/17 --time 08:42:00
add_part_info.py -p HH141 -r A -c "-*" -l "infoupd" --date 2020/03/17 --time 08:42:02
