#! /bin/bash
source ~/.bashrc
echo "200318_infoupd_1342" >> scripts.log 
update_apriori.py -p HH186 -s RF_ok --date 2020/03/18 --time 13:42
update_apriori.py -p HH187 -s RF_ok --date 2020/03/18 --time 13:42
add_part_info.py -p HH186 -r A -c 'Feed Heights: Z = 4.409' -l "infoupd" --date 2020/03/18 --time 13:42:00
add_part_info.py -p HH187 -r A -c 'Feed Heights: Z = 4.406' -l "infoupd" --date 2020/03/18 --time 13:42:00
