#! /bin/bash
echo "./200317_add_nodes_1_2.py" >> scripts.log 
add_station.py ND01 --sernum H0030-2601.2#18 --date 2020/02/15 --time 10:00
add_part.py -p FPS15 -r A -t fem-power-supply -m FPS15 --date 2020/02/15 --time 10:00
add_part.py -p PCH13 -r A -t pam-chassis -m PCH13 --date 2020/02/15 --time 10:00
add_part.py -p NCM13 -r A -t node-control-module -m NCM13 --date 2020/02/15 --time 10:00
add_part.py -p N01 -r A -t node -m H0030-2601.2#18 --date 2020/02/15 --time 10:00
add_part.py -p NBP01 -r A -t node-bulkhead -m H0030-2601.2#18 --date 2020/02/15 --time 10:00
add_part.py -p PAM209 -r A -t post-amp -m 209 --date 2020/02/15 --time 10:00
add_part.py -p PAM210 -r A -t post-amp -m 210 --date 2020/02/15 --time 10:00
add_part.py -p PAM211 -r A -t post-amp -m 211 --date 2020/02/15 --time 10:00
add_part.py -p PAM212 -r A -t post-amp -m 212 --date 2020/02/15 --time 10:00
add_part.py -p PAM213 -r A -t post-amp -m 213 --date 2020/02/15 --time 10:00
add_part.py -p PAM214 -r A -t post-amp -m 214 --date 2020/02/15 --time 10:00
add_part.py -p PAM215 -r A -t post-amp -m 215 --date 2020/02/15 --time 10:00
add_part.py -p PAM216 -r A -t post-amp -m 216 --date 2020/02/15 --time 10:00
add_part.py -p PAM217 -r A -t post-amp -m 217 --date 2020/02/15 --time 10:00
add_part.py -p PAM218 -r A -t post-amp -m 218 --date 2020/02/15 --time 10:00
add_part.py -p PAM219 -r A -t post-amp -m 219 --date 2020/02/15 --time 10:00
add_part.py -p PAM220 -r A -t post-amp -m 220 --date 2020/02/15 --time 10:00
add_part.py -p SNPC000063 -r A -t snap -m C000063 --date 2020/02/15 --time 10:00
add_part.py -p SNPC000071 -r A -t snap -m C000071 --date 2020/02/15 --time 10:00
add_part.py -p SNPC000067 -r A -t snap -m C000067 --date 2020/02/15 --time 10:00
add_part.py -p SNPC000064 -r A -t snap -m C000064 --date 2020/02/15 --time 10:00
add_connection.py -u N01 --uprev A --upport @ground -d ND01 --dnrev A --dnport @ground --date 2020/02/15 --time 11:00
add_connection.py -u FPS15 --uprev A --upport @rack -d N01 --dnrev A --dnport @top --date 2020/02/15 --time 11:00
add_connection.py -u PCH13 --uprev A --upport @rack -d N01 --dnrev A --dnport @bottom --date 2020/02/15 --time 11:00
add_connection.py -u NCM13 --uprev A --upport @rack -d N01 --dnrev A --dnport @middle --date 2020/02/15 --time 11:00
add_connection.py -u PAM209 --uprev A --upport @slot -d PCH13 --dnrev A --dnport @slot1 --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport e1 -d PAM209 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport n1 -d PAM209 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM210 --uprev A --upport @slot -d PCH13 --dnrev A --dnport @slot2 --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport e2 -d PAM210 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport n2 -d PAM210 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM211 --uprev A --upport @slot -d PCH13 --dnrev A --dnport @slot3 --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport e3 -d PAM211 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport n3 -d PAM211 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM212 --uprev A --upport @slot -d PCH13 --dnrev A --dnport @slot4 --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport e4 -d PAM212 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport n4 -d PAM212 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM213 --uprev A --upport @slot -d PCH13 --dnrev A --dnport @slot5 --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport e5 -d PAM213 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport n5 -d PAM213 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM214 --uprev A --upport @slot -d PCH13 --dnrev A --dnport @slot6 --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport e6 -d PAM214 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport n6 -d PAM214 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM215 --uprev A --upport @slot -d PCH13 --dnrev A --dnport @slot7 --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport e7 -d PAM215 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport n7 -d PAM215 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM216 --uprev A --upport @slot -d PCH13 --dnrev A --dnport @slot8 --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport e8 -d PAM216 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport n8 -d PAM216 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM217 --uprev A --upport @slot -d PCH13 --dnrev A --dnport @slot9 --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport e9 -d PAM217 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport n9 -d PAM217 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM218 --uprev A --upport @slot -d PCH13 --dnrev A --dnport @slot10 --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport e10 -d PAM218 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport n10 -d PAM218 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM219 --uprev A --upport @slot -d PCH13 --dnrev A --dnport @slot11 --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport e11 -d PAM219 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport n11 -d PAM219 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM220 --uprev A --upport @slot -d PCH13 --dnrev A --dnport @slot12 --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport e12 -d PAM220 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP01 --uprev A --upport n12 -d PAM220 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u SNPC000063 --uprev A --upport rack -d N01 --dnrev A --dnport loc0 --date 2020/02/15 --time 11:00
add_connection.py -u PAM209 --uprev A --upport e -d SNPC000063 --dnrev A --dnport e2 --date 2020/02/15 --time 11:00
add_connection.py -u PAM210 --uprev A --upport e -d SNPC000063 --dnrev A --dnport e6 --date 2020/02/15 --time 11:00
add_connection.py -u PAM211 --uprev A --upport e -d SNPC000063 --dnrev A --dnport e10 --date 2020/02/15 --time 11:00
add_connection.py -u PAM209 --uprev A --upport n -d SNPC000063 --dnrev A --dnport n0 --date 2020/02/15 --time 11:00
add_connection.py -u PAM210 --uprev A --upport n -d SNPC000063 --dnrev A --dnport n4 --date 2020/02/15 --time 11:00
add_connection.py -u PAM211 --uprev A --upport n -d SNPC000063 --dnrev A --dnport n8 --date 2020/02/15 --time 11:00
add_connection.py -u SNPC000071 --uprev A --upport rack -d N01 --dnrev A --dnport loc1 --date 2020/02/15 --time 11:00
add_connection.py -u PAM212 --uprev A --upport e -d SNPC000071 --dnrev A --dnport e2 --date 2020/02/15 --time 11:00
add_connection.py -u PAM213 --uprev A --upport e -d SNPC000071 --dnrev A --dnport e6 --date 2020/02/15 --time 11:00
add_connection.py -u PAM214 --uprev A --upport e -d SNPC000071 --dnrev A --dnport e10 --date 2020/02/15 --time 11:00
add_connection.py -u PAM212 --uprev A --upport n -d SNPC000071 --dnrev A --dnport n0 --date 2020/02/15 --time 11:00
add_connection.py -u PAM213 --uprev A --upport n -d SNPC000071 --dnrev A --dnport n4 --date 2020/02/15 --time 11:00
add_connection.py -u PAM214 --uprev A --upport n -d SNPC000071 --dnrev A --dnport n8 --date 2020/02/15 --time 11:00
add_connection.py -u SNPC000067 --uprev A --upport rack -d N01 --dnrev A --dnport loc2 --date 2020/02/15 --time 11:00
add_connection.py -u PAM215 --uprev A --upport e -d SNPC000067 --dnrev A --dnport e2 --date 2020/02/15 --time 11:00
add_connection.py -u PAM216 --uprev A --upport e -d SNPC000067 --dnrev A --dnport e6 --date 2020/02/15 --time 11:00
add_connection.py -u PAM217 --uprev A --upport e -d SNPC000067 --dnrev A --dnport e10 --date 2020/02/15 --time 11:00
add_connection.py -u PAM215 --uprev A --upport n -d SNPC000067 --dnrev A --dnport n0 --date 2020/02/15 --time 11:00
add_connection.py -u PAM216 --uprev A --upport n -d SNPC000067 --dnrev A --dnport n4 --date 2020/02/15 --time 11:00
add_connection.py -u PAM217 --uprev A --upport n -d SNPC000067 --dnrev A --dnport n8 --date 2020/02/15 --time 11:00
add_connection.py -u SNPC000064 --uprev A --upport rack -d N01 --dnrev A --dnport loc3 --date 2020/02/15 --time 11:00
add_connection.py -u PAM218 --uprev A --upport e -d SNPC000064 --dnrev A --dnport e2 --date 2020/02/15 --time 11:00
add_connection.py -u PAM219 --uprev A --upport e -d SNPC000064 --dnrev A --dnport e6 --date 2020/02/15 --time 11:00
add_connection.py -u PAM220 --uprev A --upport e -d SNPC000064 --dnrev A --dnport e10 --date 2020/02/15 --time 11:00
add_connection.py -u PAM218 --uprev A --upport n -d SNPC000064 --dnrev A --dnport n0 --date 2020/02/15 --time 11:00
add_connection.py -u PAM219 --uprev A --upport n -d SNPC000064 --dnrev A --dnport n4 --date 2020/02/15 --time 11:00
add_connection.py -u PAM220 --uprev A --upport n -d SNPC000064 --dnrev A --dnport n8 --date 2020/02/15 --time 11:00
add_station.py ND02 --sernum H0030-2601.2#19 --date 2020/02/15 --time 10:00
add_part.py -p FPS14 -r A -t fem-power-supply -m FPS14 --date 2020/02/15 --time 10:00
add_part.py -p PCH14 -r A -t pam-chassis -m PCH14 --date 2020/02/15 --time 10:00
add_part.py -p NCM14 -r A -t node-control-module -m NCM14 --date 2020/02/15 --time 10:00
add_part.py -p N02 -r A -t node -m H0030-2601.2#19 --date 2020/02/15 --time 10:00
add_part.py -p NBP02 -r A -t node-bulkhead -m H0030-2601.2#19 --date 2020/02/15 --time 10:00
add_part.py -p PAM197 -r A -t post-amp -m 197 --date 2020/02/15 --time 10:00
add_part.py -p PAM198 -r A -t post-amp -m 198 --date 2020/02/15 --time 10:00
add_part.py -p PAM199 -r A -t post-amp -m 199 --date 2020/02/15 --time 10:00
add_part.py -p PAM200 -r A -t post-amp -m 200 --date 2020/02/15 --time 10:00
add_part.py -p PAM201 -r A -t post-amp -m 201 --date 2020/02/15 --time 10:00
add_part.py -p PAM202 -r A -t post-amp -m 202 --date 2020/02/15 --time 10:00
add_part.py -p PAM203 -r A -t post-amp -m 203 --date 2020/02/15 --time 10:00
add_part.py -p PAM204 -r A -t post-amp -m 204 --date 2020/02/15 --time 10:00
add_part.py -p PAM205 -r A -t post-amp -m 205 --date 2020/02/15 --time 10:00
add_part.py -p PAM206 -r A -t post-amp -m 206 --date 2020/02/15 --time 10:00
add_part.py -p PAM207 -r A -t post-amp -m 207 --date 2020/02/15 --time 10:00
add_part.py -p PAM208 -r A -t post-amp -m 208 --date 2020/02/15 --time 10:00
add_part.py -p SNPC000066 -r A -t snap -m C000066 --date 2020/02/15 --time 10:00
add_part.py -p SNPC000074 -r A -t snap -m C000074 --date 2020/02/15 --time 10:00
add_part.py -p SNPC000079 -r A -t snap -m C000079 --date 2020/02/15 --time 10:00
add_part.py -p SNPC000081 -r A -t snap -m C000081 --date 2020/02/15 --time 10:00
add_connection.py -u N02 --uprev A --upport @ground -d ND02 --dnrev A --dnport @ground --date 2020/02/15 --time 11:00
add_connection.py -u FPS14 --uprev A --upport @rack -d N02 --dnrev A --dnport @top --date 2020/02/15 --time 11:00
add_connection.py -u PCH14 --uprev A --upport @rack -d N02 --dnrev A --dnport @bottom --date 2020/02/15 --time 11:00
add_connection.py -u NCM14 --uprev A --upport @rack -d N02 --dnrev A --dnport @middle --date 2020/02/15 --time 11:00
add_connection.py -u PAM197 --uprev A --upport @slot -d PCH14 --dnrev A --dnport @slot1 --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport e1 -d PAM197 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport n1 -d PAM197 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM198 --uprev A --upport @slot -d PCH14 --dnrev A --dnport @slot2 --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport e2 -d PAM198 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport n2 -d PAM198 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM199 --uprev A --upport @slot -d PCH14 --dnrev A --dnport @slot3 --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport e3 -d PAM199 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport n3 -d PAM199 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM200 --uprev A --upport @slot -d PCH14 --dnrev A --dnport @slot4 --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport e4 -d PAM200 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport n4 -d PAM200 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM201 --uprev A --upport @slot -d PCH14 --dnrev A --dnport @slot5 --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport e5 -d PAM201 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport n5 -d PAM201 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM202 --uprev A --upport @slot -d PCH14 --dnrev A --dnport @slot6 --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport e6 -d PAM202 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport n6 -d PAM202 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM203 --uprev A --upport @slot -d PCH14 --dnrev A --dnport @slot7 --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport e7 -d PAM203 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport n7 -d PAM203 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM204 --uprev A --upport @slot -d PCH14 --dnrev A --dnport @slot8 --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport e8 -d PAM204 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport n8 -d PAM204 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM205 --uprev A --upport @slot -d PCH14 --dnrev A --dnport @slot9 --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport e9 -d PAM205 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport n9 -d PAM205 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM206 --uprev A --upport @slot -d PCH14 --dnrev A --dnport @slot10 --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport e10 -d PAM206 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport n10 -d PAM206 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM207 --uprev A --upport @slot -d PCH14 --dnrev A --dnport @slot11 --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport e11 -d PAM207 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport n11 -d PAM207 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u PAM208 --uprev A --upport @slot -d PCH14 --dnrev A --dnport @slot12 --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport e12 -d PAM208 --dnrev A --dnport e --date 2020/02/15 --time 11:00
add_connection.py -u NBP02 --uprev A --upport n12 -d PAM208 --dnrev A --dnport n --date 2020/02/15 --time 11:00
add_connection.py -u SNPC000066 --uprev A --upport rack -d N02 --dnrev A --dnport loc0 --date 2020/02/15 --time 11:00
add_connection.py -u PAM197 --uprev A --upport e -d SNPC000066 --dnrev A --dnport e2 --date 2020/02/15 --time 11:00
add_connection.py -u PAM198 --uprev A --upport e -d SNPC000066 --dnrev A --dnport e6 --date 2020/02/15 --time 11:00
add_connection.py -u PAM199 --uprev A --upport e -d SNPC000066 --dnrev A --dnport e10 --date 2020/02/15 --time 11:00
add_connection.py -u PAM197 --uprev A --upport n -d SNPC000066 --dnrev A --dnport n0 --date 2020/02/15 --time 11:00
add_connection.py -u PAM198 --uprev A --upport n -d SNPC000066 --dnrev A --dnport n4 --date 2020/02/15 --time 11:00
add_connection.py -u PAM199 --uprev A --upport n -d SNPC000066 --dnrev A --dnport n8 --date 2020/02/15 --time 11:00
add_connection.py -u SNPC000074 --uprev A --upport rack -d N02 --dnrev A --dnport loc1 --date 2020/02/15 --time 11:00
add_connection.py -u PAM200 --uprev A --upport e -d SNPC000074 --dnrev A --dnport e2 --date 2020/02/15 --time 11:00
add_connection.py -u PAM201 --uprev A --upport e -d SNPC000074 --dnrev A --dnport e6 --date 2020/02/15 --time 11:00
add_connection.py -u PAM202 --uprev A --upport e -d SNPC000074 --dnrev A --dnport e10 --date 2020/02/15 --time 11:00
add_connection.py -u PAM200 --uprev A --upport n -d SNPC000074 --dnrev A --dnport n0 --date 2020/02/15 --time 11:00
add_connection.py -u PAM201 --uprev A --upport n -d SNPC000074 --dnrev A --dnport n4 --date 2020/02/15 --time 11:00
add_connection.py -u PAM202 --uprev A --upport n -d SNPC000074 --dnrev A --dnport n8 --date 2020/02/15 --time 11:00
add_connection.py -u SNPC000079 --uprev A --upport rack -d N02 --dnrev A --dnport loc2 --date 2020/02/15 --time 11:00
add_connection.py -u PAM203 --uprev A --upport e -d SNPC000079 --dnrev A --dnport e2 --date 2020/02/15 --time 11:00
add_connection.py -u PAM204 --uprev A --upport e -d SNPC000079 --dnrev A --dnport e6 --date 2020/02/15 --time 11:00
add_connection.py -u PAM205 --uprev A --upport e -d SNPC000079 --dnrev A --dnport e10 --date 2020/02/15 --time 11:00
add_connection.py -u PAM203 --uprev A --upport n -d SNPC000079 --dnrev A --dnport n0 --date 2020/02/15 --time 11:00
add_connection.py -u PAM204 --uprev A --upport n -d SNPC000079 --dnrev A --dnport n4 --date 2020/02/15 --time 11:00
add_connection.py -u PAM205 --uprev A --upport n -d SNPC000079 --dnrev A --dnport n8 --date 2020/02/15 --time 11:00
add_connection.py -u SNPC000081 --uprev A --upport rack -d N02 --dnrev A --dnport loc3 --date 2020/02/15 --time 11:00
add_connection.py -u PAM206 --uprev A --upport e -d SNPC000081 --dnrev A --dnport e2 --date 2020/02/15 --time 11:00
add_connection.py -u PAM207 --uprev A --upport e -d SNPC000081 --dnrev A --dnport e6 --date 2020/02/15 --time 11:00
add_connection.py -u PAM208 --uprev A --upport e -d SNPC000081 --dnrev A --dnport e10 --date 2020/02/15 --time 11:00
add_connection.py -u PAM206 --uprev A --upport n -d SNPC000081 --dnrev A --dnport n0 --date 2020/02/15 --time 11:00
add_connection.py -u PAM207 --uprev A --upport n -d SNPC000081 --dnrev A --dnport n4 --date 2020/02/15 --time 11:00
add_connection.py -u PAM208 --uprev A --upport n -d SNPC000081 --dnrev A --dnport n8 --date 2020/02/15 --time 11:00
