#! /bin/bash
source ~/.bashrc
echo "200316_infoupd_1442" >> scripts.log 
update_apriori.py -p HH144 -s RF_ok --date 2020/03/16 --time 14:42
update_apriori.py -p HH145 -s RF_ok --date 2020/03/16 --time 14:42
update_apriori.py -p HH163 -s RF_ok --date 2020/03/16 --time 14:42
update_apriori.py -p HH164 -s RF_ok --date 2020/03/16 --time 14:42
update_apriori.py -p HH165 -s RF_ok --date 2020/03/16 --time 14:42
update_apriori.py -p HH185 -s RF_ok --date 2020/03/16 --time 14:42
