#! /bin/bash
echo "./200316_add_node_15.py" >> scripts.log 
add_station.py ND15 --sernum H0030-2601.2#15 --date 2020/01/28 --time 10:00
add_part.py -p FPS13 -r A -t fem-power-supply -m FPS13 --date 2020/01/28 --time 10:00
add_part.py -p PCH12 -r A -t pam-chassis -m PCH12 --date 2020/01/28 --time 10:00
add_part.py -p NCMProd9 -r A -t node-control-module -m NCMProd9 --date 2020/01/28 --time 10:00
add_part.py -p N15 -r A -t node -m H0030-2601.2#15 --date 2020/01/28 --time 10:00
add_part.py -p NBP15 -r A -t node-bulkhead -m H0030-2601.2#15 --date 2020/01/28 --time 10:00
add_part.py -p PAM185 -r A -t post-amp -m 185 --date 2020/01/28 --time 10:00
add_part.py -p PAM186 -r A -t post-amp -m 186 --date 2020/01/28 --time 10:00
add_part.py -p PAM187 -r A -t post-amp -m 187 --date 2020/01/28 --time 10:00
add_part.py -p PAM188 -r A -t post-amp -m 188 --date 2020/01/28 --time 10:00
add_part.py -p PAM189 -r A -t post-amp -m 189 --date 2020/01/28 --time 10:00
add_part.py -p PAM190 -r A -t post-amp -m 190 --date 2020/01/28 --time 10:00
add_part.py -p PAM191 -r A -t post-amp -m 191 --date 2020/01/28 --time 10:00
add_part.py -p PAM192 -r A -t post-amp -m 192 --date 2020/01/28 --time 10:00
add_part.py -p PAM193 -r A -t post-amp -m 193 --date 2020/01/28 --time 10:00
add_part.py -p PAM194 -r A -t post-amp -m 194 --date 2020/01/28 --time 10:00
add_part.py -p PAM195 -r A -t post-amp -m 195 --date 2020/01/28 --time 10:00
add_part.py -p PAM196 -r A -t post-amp -m 196 --date 2020/01/28 --time 10:00
add_part.py -p SNPC000006 -r A -t snap -m C000006 --date 2020/01/28 --time 10:00
add_part.py -p SNPC000024 -r A -t snap -m C000024 --date 2020/01/28 --time 10:00
add_part.py -p SNPC000009 -r A -t snap -m C000009 --date 2020/01/28 --time 10:00
add_part.py -p SNPC000076 -r A -t snap -m C000076 --date 2020/01/28 --time 10:00
add_connection.py -u N15 --uprev A --upport @ground -d ND15 --dnrev A --dnport @ground --date 2020/01/28 --time 11:00
add_connection.py -u FPS13 --uprev A --upport @rack -d N15 --dnrev A --dnport @top --date 2020/01/28 --time 11:00
add_connection.py -u PCH12 --uprev A --upport @rack -d N15 --dnrev A --dnport @bottom --date 2020/01/28 --time 11:00
add_connection.py -u NCMProd9 --uprev A --upport @rack -d N15 --dnrev A --dnport @middle --date 2020/01/28 --time 11:00
add_connection.py -u PAM185 --uprev A --upport @slot -d PCH12 --dnrev A --dnport @slot1 --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport e1 -d PAM185 --dnrev A --dnport e --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport n1 -d PAM185 --dnrev A --dnport n --date 2020/01/28 --time 11:00
add_connection.py -u PAM186 --uprev A --upport @slot -d PCH12 --dnrev A --dnport @slot2 --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport e2 -d PAM186 --dnrev A --dnport e --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport n2 -d PAM186 --dnrev A --dnport n --date 2020/01/28 --time 11:00
add_connection.py -u PAM187 --uprev A --upport @slot -d PCH12 --dnrev A --dnport @slot3 --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport e3 -d PAM187 --dnrev A --dnport e --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport n3 -d PAM187 --dnrev A --dnport n --date 2020/01/28 --time 11:00
add_connection.py -u PAM188 --uprev A --upport @slot -d PCH12 --dnrev A --dnport @slot4 --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport e4 -d PAM188 --dnrev A --dnport e --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport n4 -d PAM188 --dnrev A --dnport n --date 2020/01/28 --time 11:00
add_connection.py -u PAM189 --uprev A --upport @slot -d PCH12 --dnrev A --dnport @slot5 --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport e5 -d PAM189 --dnrev A --dnport e --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport n5 -d PAM189 --dnrev A --dnport n --date 2020/01/28 --time 11:00
add_connection.py -u PAM190 --uprev A --upport @slot -d PCH12 --dnrev A --dnport @slot6 --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport e6 -d PAM190 --dnrev A --dnport e --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport n6 -d PAM190 --dnrev A --dnport n --date 2020/01/28 --time 11:00
add_connection.py -u PAM191 --uprev A --upport @slot -d PCH12 --dnrev A --dnport @slot7 --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport e7 -d PAM191 --dnrev A --dnport e --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport n7 -d PAM191 --dnrev A --dnport n --date 2020/01/28 --time 11:00
add_connection.py -u PAM192 --uprev A --upport @slot -d PCH12 --dnrev A --dnport @slot8 --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport e8 -d PAM192 --dnrev A --dnport e --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport n8 -d PAM192 --dnrev A --dnport n --date 2020/01/28 --time 11:00
add_connection.py -u PAM193 --uprev A --upport @slot -d PCH12 --dnrev A --dnport @slot9 --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport e9 -d PAM193 --dnrev A --dnport e --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport n9 -d PAM193 --dnrev A --dnport n --date 2020/01/28 --time 11:00
add_connection.py -u PAM194 --uprev A --upport @slot -d PCH12 --dnrev A --dnport @slot10 --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport e10 -d PAM194 --dnrev A --dnport e --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport n10 -d PAM194 --dnrev A --dnport n --date 2020/01/28 --time 11:00
add_connection.py -u PAM195 --uprev A --upport @slot -d PCH12 --dnrev A --dnport @slot11 --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport e11 -d PAM195 --dnrev A --dnport e --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport n11 -d PAM195 --dnrev A --dnport n --date 2020/01/28 --time 11:00
add_connection.py -u PAM196 --uprev A --upport @slot -d PCH12 --dnrev A --dnport @slot12 --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport e12 -d PAM196 --dnrev A --dnport e --date 2020/01/28 --time 11:00
add_connection.py -u NBP15 --uprev A --upport n12 -d PAM196 --dnrev A --dnport n --date 2020/01/28 --time 11:00
add_connection.py -u SNPC000006 --uprev A --upport rack -d N15 --dnrev A --dnport loc0 --date 2020/01/28 --time 11:00
add_connection.py -u PAM185 --uprev A --upport e -d SNPC000006 --dnrev A --dnport e2 --date 2020/01/28 --time 11:00
add_connection.py -u PAM186 --uprev A --upport e -d SNPC000006 --dnrev A --dnport e6 --date 2020/01/28 --time 11:00
add_connection.py -u PAM187 --uprev A --upport e -d SNPC000006 --dnrev A --dnport e10 --date 2020/01/28 --time 11:00
add_connection.py -u PAM185 --uprev A --upport n -d SNPC000006 --dnrev A --dnport n0 --date 2020/01/28 --time 11:00
add_connection.py -u PAM186 --uprev A --upport n -d SNPC000006 --dnrev A --dnport n4 --date 2020/01/28 --time 11:00
add_connection.py -u PAM187 --uprev A --upport n -d SNPC000006 --dnrev A --dnport n8 --date 2020/01/28 --time 11:00
add_connection.py -u SNPC000024 --uprev A --upport rack -d N15 --dnrev A --dnport loc1 --date 2020/01/28 --time 11:00
add_connection.py -u PAM188 --uprev A --upport e -d SNPC000024 --dnrev A --dnport e2 --date 2020/01/28 --time 11:00
add_connection.py -u PAM189 --uprev A --upport e -d SNPC000024 --dnrev A --dnport e6 --date 2020/01/28 --time 11:00
add_connection.py -u PAM190 --uprev A --upport e -d SNPC000024 --dnrev A --dnport e10 --date 2020/01/28 --time 11:00
add_connection.py -u PAM188 --uprev A --upport n -d SNPC000024 --dnrev A --dnport n0 --date 2020/01/28 --time 11:00
add_connection.py -u PAM189 --uprev A --upport n -d SNPC000024 --dnrev A --dnport n4 --date 2020/01/28 --time 11:00
add_connection.py -u PAM190 --uprev A --upport n -d SNPC000024 --dnrev A --dnport n8 --date 2020/01/28 --time 11:00
add_connection.py -u SNPC000009 --uprev A --upport rack -d N15 --dnrev A --dnport loc2 --date 2020/01/28 --time 11:00
add_connection.py -u PAM191 --uprev A --upport e -d SNPC000009 --dnrev A --dnport e2 --date 2020/01/28 --time 11:00
add_connection.py -u PAM192 --uprev A --upport e -d SNPC000009 --dnrev A --dnport e6 --date 2020/01/28 --time 11:00
add_connection.py -u PAM193 --uprev A --upport e -d SNPC000009 --dnrev A --dnport e10 --date 2020/01/28 --time 11:00
add_connection.py -u PAM191 --uprev A --upport n -d SNPC000009 --dnrev A --dnport n0 --date 2020/01/28 --time 11:00
add_connection.py -u PAM192 --uprev A --upport n -d SNPC000009 --dnrev A --dnport n4 --date 2020/01/28 --time 11:00
add_connection.py -u PAM193 --uprev A --upport n -d SNPC000009 --dnrev A --dnport n8 --date 2020/01/28 --time 11:00
add_connection.py -u SNPC000076 --uprev A --upport rack -d N15 --dnrev A --dnport loc3 --date 2020/01/28 --time 11:00
add_connection.py -u PAM194 --uprev A --upport e -d SNPC000076 --dnrev A --dnport e2 --date 2020/01/28 --time 11:00
add_connection.py -u PAM195 --uprev A --upport e -d SNPC000076 --dnrev A --dnport e6 --date 2020/01/28 --time 11:00
add_connection.py -u PAM196 --uprev A --upport e -d SNPC000076 --dnrev A --dnport e10 --date 2020/01/28 --time 11:00
add_connection.py -u PAM194 --uprev A --upport n -d SNPC000076 --dnrev A --dnport n0 --date 2020/01/28 --time 11:00
add_connection.py -u PAM195 --uprev A --upport n -d SNPC000076 --dnrev A --dnport n4 --date 2020/01/28 --time 11:00
add_connection.py -u PAM196 --uprev A --upport n -d SNPC000076 --dnrev A --dnport n8 --date 2020/01/28 --time 11:00
