#! /bin/bash
source ~/.bashrc
echo "200722_infoupd_0942" >> scripts.log 
update_apriori.py -p HH110 -s RF_ok --date 2020/07/22 --time 09:42
add_part_info.py -p HH109 -r A -c 'Door closed ' -l "infoupd" --date 2020/07/22 --time 09:42:00
add_part_info.py -p HH110 -r A -c 'Feed raised' -l "infoupd" --date 2020/07/22 --time 09:42:00
add_part_info.py -p HH110 -r A -c 'Feed raised' -l "infoupd" --date 2020/07/22 --time 09:42:02
add_part_info.py -p HH127 -r A -c 'Feed raised' -l "infoupd" --date 2020/07/22 --time 09:42:00
add_part_info.py -p HH127 -r A -c 'Feed raised' -l "infoupd" --date 2020/07/22 --time 09:42:02
add_part_info.py -p HH130 -r A -c 'Central line too loose to be RF OK, door mesh closed' -l "infoupd" --date 2020/07/22 --time 09:42:00
add_part_info.py -p HH130 -r A -c 'Central line too loose to be RF OK, door mesh closed' -l "infoupd" --date 2020/07/22 --time 09:42:02
