#! /bin/bash
source ~/.bashrc
echo "200809_infoupd_2042" >> scripts.log 
update_apriori.py -p HH0 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH1 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH2 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH12 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH13 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH14 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH23 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH25 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH26 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH36 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH37 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH38 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH39 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH40 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH41 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH43 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH44 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH45 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH46 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH51 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH53 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH56 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH58 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH59 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH60 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH67 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH68 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH69 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH70 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH73 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH75 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH81 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH82 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH83 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH98 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH99 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH100 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH117 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH118 -s digital_ok --date 2020/08/09 --time 20:42
update_apriori.py -p HH119 -s digital_ok --date 2020/08/09 --time 20:42
add_part_info.py -p HH0 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH0 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH2 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH2 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH1 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH1 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH12 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH12 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH13 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH13 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH14 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH14 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH23 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH23 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH25 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH25 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH26 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH26 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH39 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH39 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH67 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH67 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH68 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH68 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH37 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH37 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH38 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH38 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH53 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH53 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH51 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH51 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH36 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH36 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH40 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH41 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH41 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH56 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH56 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH69 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH69 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH70 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH70 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH43 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH43 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH44 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH44 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH45 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH45 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH46 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH46 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH58 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH58 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH59 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH59 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH60 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH60 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH73 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH73 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH75 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH75 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH81 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH81 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH82 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH82 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH83 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH83 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH100 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH100 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH119 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH119 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH98 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH98 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH99 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH99 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH117 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH117 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH118 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH118 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH85 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH85 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH101 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH101 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH102 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH102 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH103 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH103 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH104 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH104 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
add_part_info.py -p HH122 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:00
add_part_info.py -p HH122 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 20:42:02
