#! /bin/bash
source ~/.bashrc
echo "200805_infoupd_2242" >> scripts.log 
add_part_info.py -p HH183 -r A -c 'Preliminary post-PAM spectra looks fine' -l "infoupd" --date 2020/08/05 --time 22:42:00
add_part_info.py -p HH183 -r A -c 'Preliminary post-PAM spectra looks fine' -l "infoupd" --date 2020/08/05 --time 22:42:02
