#! /bin/bash
source ~/.bashrc
echo "200804_infoupd_2242" >> scripts.log 
add_part_info.py -p HH24 -r A -c 'No central line for this feed' -l "infoupd" --date 2020/08/04 --time 22:42:00
add_part_info.py -p HH24 -r A -c 'No central line for this feed' -l "infoupd" --date 2020/08/04 --time 22:42:02
add_part_info.py -p HH65 -r A -c '65E looks dead' -l "infoupd" --date 2020/08/04 --time 22:42:00
add_part_info.py -p HH42 -r A -c '43E looks dead' -l "infoupd" --date 2020/08/04 --time 22:42:00
add_part_info.py -p HH55 -r A -c '55N looks dead' -l "infoupd" --date 2020/08/04 --time 22:42:00
add_part_info.py -p HH57 -r A -c 'central line is detached' -l "infoupd" --date 2020/08/04 --time 22:42:00
add_part_info.py -p HH57 -r A -c 'central line is detached' -l "infoupd" --date 2020/08/04 --time 22:42:02
add_part_info.py -p HH71 -r A -c '71E looks very atypical' -l "infoupd" --date 2020/08/04 --time 22:42:00
add_part_info.py -p HH74 -r A -c '74E and N look dead' -l "infoupd" --date 2020/08/04 --time 22:42:00
add_part_info.py -p HH74 -r A -c '74E and N look dead' -l "infoupd" --date 2020/08/04 --time 22:42:02
