#! /bin/bash
source ~/.bashrc
echo "200810_infoupd_2242" >> scripts.log 
add_part_info.py -p HH178 -r A -c 'No final check spectra - Preliminary specrta looks fine' -l "infoupd" --date 2020/08/10 --time 22:42:00
add_part_info.py -p HH178 -r A -c 'No final check spectra - Preliminary specrta looks fine' -l "infoupd" --date 2020/08/10 --time 22:42:02
add_part_info.py -p HH66 -r A -c 'loose central line' -l "infoupd" --date 2020/08/10 --time 22:42:00
add_part_info.py -p HH87 -r A -c 'loose central line' -l "infoupd" --date 2020/08/10 --time 22:42:00
add_part_info.py -p HH121 -r A -c 'loose central line' -l "infoupd" --date 2020/08/10 --time 22:42:00
add_part_info.py -p HH123 -r A -c 'loose central line' -l "infoupd" --date 2020/08/10 --time 22:42:00
