#! /bin/bash
source ~/.bashrc
echo "200805_infoupd_1942" >> scripts.log 
add_part_info.py -p HH129 -r A -c '129E very attenuated; 129N looks fine. Has no door, but piece of mesh in dish (curled up and protruding ~40 cm) likely is for the door. Broken PVC rib SE - ~ 3 cm discontinuity' -l "infoupd" --date 2020/08/05 --time 19:42:00
add_part_info.py -p HH129 -r A -c '129E very attenuated; 129N looks fine. Has no door, but piece of mesh in dish (curled up and protruding ~40 cm) likely is for the door. Broken PVC rib SE - ~ 3 cm discontinuity' -l "infoupd" --date 2020/08/05 --time 19:42:02
add_part_info.py -p HH140 -r A -c 'Preliminary post-PAM spectra looks fine' -l "infoupd" --date 2020/08/05 --time 19:42:00
add_part_info.py -p HH140 -r A -c 'Preliminary post-PAM spectra looks fine' -l "infoupd" --date 2020/08/05 --time 19:42:02
add_part_info.py -p HH142 -r A -c 'Preliminary post-PAM spectra looks fine' -l "infoupd" --date 2020/08/05 --time 19:42:00
add_part_info.py -p HH142 -r A -c 'Preliminary post-PAM spectra looks fine' -l "infoupd" --date 2020/08/05 --time 19:42:02
add_part_info.py -p HH180 -r A -c 'Preliminary post-PAM spectra looks fine' -l "infoupd" --date 2020/08/05 --time 19:42:00
add_part_info.py -p HH180 -r A -c 'Preliminary post-PAM spectra is very low amplitude but not dead' -l "infoupd" --date 2020/08/05 --time 19:42:02
add_part_info.py -p HH116 -r A -c 'Post-PAM spectra of 116E has a strange look.' -l "infoupd" --date 2020/08/05 --time 19:42:00
