#! /bin/bash
source ~/.bashrc
echo "200825_infoupd_1842" >> scripts.log 
update_apriori.py -p HH75 -s RF_maintenance --date 2020/08/25 --time 18:42
update_apriori.py -p HH81 -s RF_maintenance --date 2020/08/25 --time 18:42
update_apriori.py -p HH82 -s RF_maintenance --date 2020/08/25 --time 18:42
update_apriori.py -p HH101 -s RF_maintenance --date 2020/08/25 --time 18:42
update_apriori.py -p HH155 -s RF_maintenance --date 2020/08/25 --time 18:42
update_apriori.py -p HH165 -s RF_maintenance --date 2020/08/25 --time 18:42
add_part_info.py -p HH110 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:00
add_part_info.py -p HH111 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:00
add_part_info.py -p HH112 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:00
add_part_info.py -p HH155 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:00
add_part_info.py -p HH155 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:02
add_part_info.py -p HH165 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:00
add_part_info.py -p HH165 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:02
add_part_info.py -p HH185 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:00
add_part_info.py -p HH186 -r A -c ' ' -l "infoupd" --date 2020/08/25 --time 18:42:00
add_part_info.py -p HH75 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:00
add_part_info.py -p HH75 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:02
add_part_info.py -p HH81 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:00
add_part_info.py -p HH81 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:02
add_part_info.py -p HH82 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:00
add_part_info.py -p HH82 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:02
add_part_info.py -p HH83 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:00
add_part_info.py -p HH83 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:02
add_part_info.py -p HH101 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:00
add_part_info.py -p HH101 -r A -c 'sbcd 25 aug due to heranow autos' -l "infoupd" --date 2020/08/25 --time 18:42:02
