#! /bin/bash
source ~/.bashrc
echo "200813_connupd_0417" >> scripts.log 
add_part.py -p FDV130 -r A -t feed -m FDV130 --date 2020/08/13 --time 10:00
add_part.py -p FEM199 -r A -t front-end -m FEM199 --date 2020/08/13 --time 10:00
add_part.py -p FEM214 -r A -t front-end -m FEM214 --date 2020/08/13 --time 10:00
add_part.py -p FDV131 -r A -t feed -m FDV131 --date 2020/08/13 --time 10:00
add_part.py -p FDV141 -r A -t feed -m FDV141 --date 2020/08/13 --time 10:00
add_part.py -p FEM200 -r A -t front-end -m FEM200 --date 2020/08/13 --time 10:00
add_part.py -p FEM207 -r A -t front-end -m FEM207 --date 2020/08/13 --time 10:00
add_part.py -p FDV128 -r A -t feed -m FDV128 --date 2020/08/13 --time 10:00
add_part.py -p FDV136 -r A -t feed -m FDV136 --date 2020/08/13 --time 10:00
add_part.py -p FEM220 -r A -t front-end -m FEM220 --date 2020/08/13 --time 10:00
add_part.py -p FEM213 -r A -t front-end -m FEM213 --date 2020/08/13 --time 10:00
add_part.py -p FEM201 -r A -t front-end -m FEM201 --date 2020/08/13 --time 10:00
add_part.py -p FDV132 -r A -t feed -m FDV132 --date 2020/08/13 --time 10:00
add_part.py -p FEM206 -r A -t front-end -m FEM206 --date 2020/08/13 --time 10:00
add_part.py -p FEM197 -r A -t front-end -m FEM197 --date 2020/08/13 --time 10:00
add_part.py -p FDV126 -r A -t feed -m FDV126 --date 2020/08/13 --time 10:00
add_part.py -p FEM208 -r A -t front-end -m FEM208 --date 2020/08/13 --time 10:00
add_part.py -p FDV137 -r A -t feed -m FDV137 --date 2020/08/13 --time 10:00
add_part.py -p FDV134 -r A -t feed -m FDV134 --date 2020/08/13 --time 10:00
add_part.py -p FDV129 -r A -t feed -m FDV129 --date 2020/08/13 --time 10:00
add_part.py -p FDV138 -r A -t feed -m FDV138 --date 2020/08/13 --time 10:00
add_part.py -p FEM202 -r A -t front-end -m FEM202 --date 2020/08/13 --time 10:00
add_connection.py -u A147 --uprev H --upport focus -d FDV132 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FDV132 --uprev A --upport terminals -d FEM202 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FEM202 --uprev A --upport e -d NBP15 --dnrev A --dnport e1 --date 2020/08/13 --time 11:00
add_connection.py -u FEM202 --uprev A --upport n -d NBP15 --dnrev A --dnport n1 --date 2020/08/13 --time 11:00
add_connection.py -u A148 --uprev H --upport focus -d FDV126 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FDV126 --uprev A --upport terminals -d FEM220 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FEM220 --uprev A --upport e -d NBP15 --dnrev A --dnport e2 --date 2020/08/13 --time 11:00
add_connection.py -u FEM220 --uprev A --upport n -d NBP15 --dnrev A --dnport n2 --date 2020/08/13 --time 11:00
add_connection.py -u A149 --uprev H --upport focus -d FDV130 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FDV130 --uprev A --upport terminals -d FEM208 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FEM208 --uprev A --upport e -d NBP15 --dnrev A --dnport e3 --date 2020/08/13 --time 11:00
add_connection.py -u FEM208 --uprev A --upport n -d NBP15 --dnrev A --dnport n3 --date 2020/08/13 --time 11:00
add_connection.py -u A150 --uprev H --upport focus -d FDV134 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FDV134 --uprev A --upport terminals -d FEM206 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FEM206 --uprev A --upport e -d NBP15 --dnrev A --dnport e4 --date 2020/08/13 --time 11:00
add_connection.py -u FEM206 --uprev A --upport n -d NBP15 --dnrev A --dnport n4 --date 2020/08/13 --time 11:00
add_connection.py -u A167 --uprev H --upport focus -d FDV129 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FDV129 --uprev A --upport terminals -d FEM199 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FEM199 --uprev A --upport e -d NBP15 --dnrev A --dnport e5 --date 2020/08/13 --time 11:00
add_connection.py -u FEM199 --uprev A --upport n -d NBP15 --dnrev A --dnport n5 --date 2020/08/13 --time 11:00
add_connection.py -u A168 --uprev H --upport focus -d FDV138 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FDV138 --uprev A --upport terminals -d FEM207 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FEM207 --uprev A --upport e -d NBP15 --dnrev A --dnport e7 --date 2020/08/13 --time 11:00
add_connection.py -u FEM207 --uprev A --upport n -d NBP15 --dnrev A --dnport n7 --date 2020/08/13 --time 11:00
add_connection.py -u A169 --uprev H --upport focus -d FDV128 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FDV128 --uprev A --upport terminals -d FEM214 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FEM214 --uprev A --upport e -d NBP15 --dnrev A --dnport e8 --date 2020/08/13 --time 11:00
add_connection.py -u FEM214 --uprev A --upport n -d NBP15 --dnrev A --dnport n8 --date 2020/08/13 --time 11:00
add_connection.py -u A170 --uprev H --upport focus -d FDV136 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FDV136 --uprev A --upport terminals -d FEM201 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FEM201 --uprev A --upport e -d NBP15 --dnrev A --dnport e9 --date 2020/08/13 --time 11:00
add_connection.py -u FEM201 --uprev A --upport n -d NBP15 --dnrev A --dnport n9 --date 2020/08/13 --time 11:00
add_connection.py -u A189 --uprev H --upport focus -d FDV141 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FDV141 --uprev A --upport terminals -d FEM213 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FEM213 --uprev A --upport e -d NBP15 --dnrev A --dnport e10 --date 2020/08/13 --time 11:00
add_connection.py -u FEM213 --uprev A --upport n -d NBP15 --dnrev A --dnport n10 --date 2020/08/13 --time 11:00
add_connection.py -u A190 --uprev H --upport focus -d FDV137 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FDV137 --uprev A --upport terminals -d FEM200 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FEM200 --uprev A --upport e -d NBP15 --dnrev A --dnport e11 --date 2020/08/13 --time 11:00
add_connection.py -u FEM200 --uprev A --upport n -d NBP15 --dnrev A --dnport n11 --date 2020/08/13 --time 11:00
add_connection.py -u A191 --uprev H --upport focus -d FDV131 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FDV131 --uprev A --upport terminals -d FEM197 --dnrev A --dnport input --date 2020/08/13 --time 11:00
add_connection.py -u FEM197 --uprev A --upport e -d NBP15 --dnrev A --dnport e12 --date 2020/08/13 --time 11:00
add_connection.py -u FEM197 --uprev A --upport n -d NBP15 --dnrev A --dnport n12 --date 2020/08/13 --time 11:00
