#! /bin/bash
echo "./200824_add_nodes.py" >> scripts.log 
add_station.py ND06 --sernum H0030-2601.2#16 --date 2020/08/01 --time 10:00
add_part.py -p N06 -r A -t node -m H0030-2601.2#16 --date 2020/08/01 --time 10:00
add_station.py ND09 --sernum H0030-2601.1#1 --date 2020/08/01 --time 10:00
add_station.py ND11 --sernum H0030-2601.2#20 --date 2020/08/01 --time 10:00
add_part.py -p N11 -r A -t node -m H0030-2601.2#20 --date 2020/08/01 --time 10:00
add_station.py ND16 --sernum H0030-2601.2#17 --date 2020/08/01 --time 10:00
add_part.py -p N16 -r A -t node -m H0030-2601.2#17 --date 2020/08/01 --time 10:00
add_station.py ND17 --sernum H0030-2601.2#12 --date 2020/08/01 --time 10:00
add_part.py -p N17 -r A -t node -m H0030-2601.2#12 --date 2020/08/01 --time 10:00
add_station.py ND18 --sernum H0030-2601.2#11 --date 2020/08/01 --time 10:00
add_part.py -p N18 -r A -t node -m H0030-2601.2#11 --date 2020/08/01 --time 10:00
add_station.py ND19 --sernum H0030-2601.2#10 --date 2020/08/01 --time 10:00
add_part.py -p N19 -r A -t node -m H0030-2601.2#10 --date 2020/08/01 --time 10:00
add_station.py ND20 --sernum H0030-2601.2# --date 2020/08/01 --time 10:00
add_part.py -p N20 -r A -t node -m H0030-2601.2# --date 2020/08/01 --time 10:00
add_station.py ND21 --sernum H0030-2601.2# --date 2020/08/01 --time 10:00
add_part.py -p N21 -r A -t node -m H0030-2601.2# --date 2020/08/01 --time 10:00
add_station.py ND22 --sernum H0030-2601.2# --date 2020/08/01 --time 10:00
add_part.py -p N22 -r A -t node -m H0030-2601.2# --date 2020/08/01 --time 10:00
add_station.py ND23 --sernum H0030-2601.2# --date 2020/08/01 --time 10:00
add_part.py -p N23 -r A -t node -m H0030-2601.2# --date 2020/08/01 --time 10:00
add_station.py ND24 --sernum H0030-2601.2# --date 2020/08/01 --time 10:00
add_part.py -p N24 -r A -t node -m H0030-2601.2# --date 2020/08/01 --time 10:00
add_station.py ND25 --sernum H0030-2601.2# --date 2020/08/01 --time 10:00
add_part.py -p N25 -r A -t node -m H0030-2601.2# --date 2020/08/01 --time 10:00
add_station.py ND26 --sernum H0030-2601.2# --date 2020/08/01 --time 10:00
add_part.py -p N26 -r A -t node -m H0030-2601.2# --date 2020/08/01 --time 10:00
add_station.py ND27 --sernum H0030-2601.2# --date 2020/08/01 --time 10:00
add_part.py -p N27 -r A -t node -m H0030-2601.2# --date 2020/08/01 --time 10:00
add_part_info.py -p ND00 -r A -c 'Door direction: E' --date 2020/08/01 --time 12:00
add_part_info.py -p ND01 -r A -c 'Door direction: NW' --date 2020/08/01 --time 12:00
add_part_info.py -p ND02 -r A -c 'Door direction: E' --date 2020/08/01 --time 12:00
add_part_info.py -p ND03 -r A -c 'Door direction: SW' --date 2020/08/01 --time 12:00
add_part_info.py -p ND04 -r A -c 'Door direction: NW' --date 2020/08/01 --time 12:00
add_part_info.py -p ND05 -r A -c 'Door direction: NE' --date 2020/08/01 --time 12:00
add_part_info.py -p ND06 -r A -c 'Door direction: SE' --date 2020/08/01 --time 12:00
add_part_info.py -p ND07 -r A -c 'Door direction: N' --date 2020/08/01 --time 12:00
add_part_info.py -p ND08 -r A -c 'Door direction: NE' --date 2020/08/01 --time 12:00
add_part_info.py -p ND09 -r A -c 'Door direction: E' --date 2020/08/01 --time 12:00
add_part_info.py -p ND10 -r A -c 'Door direction: SE' --date 2020/08/01 --time 12:00
add_part_info.py -p ND11 -r A -c 'Door direction: SW' --date 2020/08/01 --time 12:00
add_part_info.py -p ND12 -r A -c 'Door direction: NW' --date 2020/08/01 --time 12:00
add_part_info.py -p ND13 -r A -c 'Door direction: NE' --date 2020/08/01 --time 12:00
add_part_info.py -p ND14 -r A -c 'Door direction: SE' --date 2020/08/01 --time 12:00
add_part_info.py -p ND15 -r A -c 'Door direction: SW' --date 2020/08/01 --time 12:00
add_part_info.py -p ND16 -r A -c 'Door direction: S' --date 2020/08/01 --time 12:00
add_part_info.py -p ND17 -r A -c 'Door direction: E' --date 2020/08/01 --time 12:00
add_part_info.py -p ND18 -r A -c 'Door direction: SE' --date 2020/08/01 --time 12:00
add_part_info.py -p ND19 -r A -c 'Door direction: SE' --date 2020/08/01 --time 12:00
add_part_info.py -p ND20 -r A -c 'Door direction: NW' --date 2020/08/01 --time 12:00
add_part_info.py -p ND21 -r A -c 'Door direction: NE' --date 2020/08/01 --time 12:00
add_part_info.py -p ND22 -r A -c 'Door direction: NW' --date 2020/08/01 --time 12:00
add_part_info.py -p ND23 -r A -c 'Door direction: NW' --date 2020/08/01 --time 12:00
add_part_info.py -p ND24 -r A -c 'Door direction: NE' --date 2020/08/01 --time 12:00
add_part_info.py -p ND25 -r A -c 'Door direction: SE' --date 2020/08/01 --time 12:00
add_part_info.py -p ND26 -r A -c 'Door direction: SW' --date 2020/08/01 --time 12:00
add_part_info.py -p ND27 -r A -c 'Door direction: NW' --date 2020/08/01 --time 12:00
