#! /bin/bash
source ~/.bashrc
echo "200809_infoupd_2142" >> scripts.log 
update_apriori.py -p HH92 -s digital_ok --date 2020/08/09 --time 21:42
update_apriori.py -p HH93 -s digital_ok --date 2020/08/09 --time 21:42
update_apriori.py -p HH94 -s digital_ok --date 2020/08/09 --time 21:42
update_apriori.py -p HH110 -s digital_ok --date 2020/08/09 --time 21:42
update_apriori.py -p HH111 -s digital_ok --date 2020/08/09 --time 21:42
update_apriori.py -p HH112 -s digital_ok --date 2020/08/09 --time 21:42
add_part_info.py -p HH92 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:00
add_part_info.py -p HH92 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:02
add_part_info.py -p HH93 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:00
add_part_info.py -p HH93 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:02
add_part_info.py -p HH94 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:00
add_part_info.py -p HH94 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:02
add_part_info.py -p HH110 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:00
add_part_info.py -p HH110 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:02
add_part_info.py -p HH111 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:00
add_part_info.py -p HH111 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:02
add_part_info.py -p HH112 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:00
add_part_info.py -p HH112 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:02
add_part_info.py -p HH135 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:00
add_part_info.py -p HH135 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:02
add_part_info.py -p HH136 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:00
add_part_info.py -p HH136 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:02
add_part_info.py -p HH155 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:00
add_part_info.py -p HH155 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:02
add_part_info.py -p HH156 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:00
add_part_info.py -p HH157 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:00
add_part_info.py -p HH157 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:02
add_part_info.py -p HH158 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:00
add_part_info.py -p HH158 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:02
add_part_info.py -p HH177 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:00
add_part_info.py -p HH177 -r A -c 'reported sync ok by dgorki Aug 7 ' -l "infoupd" --date 2020/08/09 --time 21:42:02
