#! /bin/bash
source ~/.bashrc
echo "200809_infoupd_1642" >> scripts.log 
add_part_info.py -p HH135 -r A -c 'Final specrta looks fine' -l "infoupd" --date 2020/08/09 --time 16:42:00
add_part_info.py -p HH135 -r A -c 'Final specrta looks fine' -l "infoupd" --date 2020/08/09 --time 16:42:02
add_part_info.py -p HH136 -r A -c 'Final specrta looks fine' -l "infoupd" --date 2020/08/09 --time 16:42:00
add_part_info.py -p HH136 -r A -c 'Final specrta looks fine' -l "infoupd" --date 2020/08/09 --time 16:42:02
add_part_info.py -p HH155 -r A -c 'Final specrta looks fine' -l "infoupd" --date 2020/08/09 --time 16:42:00
add_part_info.py -p HH155 -r A -c 'Final specrta looks fine' -l "infoupd" --date 2020/08/09 --time 16:42:02
add_part_info.py -p HH156 -r A -c 'Final spectre looks fine' -l "infoupd" --date 2020/08/09 --time 16:42:00
add_part_info.py -p HH157 -r A -c 'Final spectre looks fine' -l "infoupd" --date 2020/08/09 --time 16:42:00
add_part_info.py -p HH157 -r A -c 'Final spectre looks fine' -l "infoupd" --date 2020/08/09 --time 16:42:02
add_part_info.py -p HH158 -r A -c 'Final spectre looks fine' -l "infoupd" --date 2020/08/09 --time 16:42:00
add_part_info.py -p HH158 -r A -c 'Feed heights (NE/SE/SW/NW): z distance = 4.411' -l "infoupd" --date 2020/08/09 --time 16:42:02
add_part_info.py -p HH158 -r A -c 'Final spectre looks fine' -l "infoupd" --date 2020/08/09 --time 16:42:04
add_part_info.py -p HH177 -r A -c 'Final spectra looks fine' -l "infoupd" --date 2020/08/09 --time 16:42:00
add_part_info.py -p HH177 -r A -c 'Final spectra looks fine' -l "infoupd" --date 2020/08/09 --time 16:42:02
