#! /bin/bash
source ~/.bashrc
echo "200918_infoupd_2142" >> scripts.log 
update_apriori.py -p HH81 -s RF_ok --date 2020/09/18 --time 21:42
update_apriori.py -p HH82 -s RF_ok --date 2020/09/18 --time 21:42
update_apriori.py -p HH86 -s RF_ok --date 2020/09/18 --time 21:42
update_apriori.py -p HH88 -s RF_ok --date 2020/09/18 --time 21:42
update_apriori.py -p HH108 -s RF_ok --date 2020/09/18 --time 21:42
update_apriori.py -p HH110 -s RF_ok --date 2020/09/18 --time 21:42
update_apriori.py -p HH120 -s RF_ok --date 2020/09/18 --time 21:42
update_apriori.py -p HH123 -s RF_ok --date 2020/09/18 --time 21:42
update_apriori.py -p HH156 -s RF_ok --date 2020/09/18 --time 21:42
update_apriori.py -p HH182 -s RF_ok --date 2020/09/18 --time 21:42
add_part_info.py -p HH110 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:00
add_part_info.py -p HH156 -r A -c 'Nice SNAP auto 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:00
add_part_info.py -p HH156 -r A -c 'Nice SNAP auto 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:02
add_part_info.py -p HH182 -r A -c 'Nice SNAP auto 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:00
add_part_info.py -p HH182 -r A -c 'Nice SNAP auto 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:02
add_part_info.py -p HH81 -r A -c 'SNAP auto looks fine 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:00
add_part_info.py -p HH81 -r A -c 'SNAP auto looks fine 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:02
add_part_info.py -p HH82 -r A -c 'SNAP auto looks fine 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:00
add_part_info.py -p HH82 -r A -c 'SNAP auto looks fine 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:02
add_part_info.py -p HH86 -r A -c 'Nice SNAP auto 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:00
add_part_info.py -p HH86 -r A -c 'Nice SNAP auto 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:02
add_part_info.py -p HH120 -r A -c 'OK looking SNAP spectra 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:00
add_part_info.py -p HH120 -r A -c 'OK looking SNAP spectra 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:02
add_part_info.py -p HH123 -r A -c 'Nice SNAP autos 178 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:00
add_part_info.py -p HH123 -r A -c 'Nice SNAP autos 178 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:02
add_part_info.py -p HH88 -r A -c 'autos look fine in 59111 DN' -l "apa-infoupd" --date 2020/09/18 --time 21:42:00
add_part_info.py -p HH88 -r A -c 'autos look fine in 59111 DN' -l "apa-infoupd" --date 2020/09/18 --time 21:42:02
add_part_info.py -p HH108 -r A -c 'nice autos in SNAP spectra 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:00
add_part_info.py -p HH108 -r A -c 'nice autos in SNAP spectra 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 21:42:02
