#! /bin/bash
source ~/.bashrc
echo "200917_infoupd_1842" >> scripts.log 
update_apriori.py -p HH92 -s RF_ok --date 2020/09/17 --time 18:42
update_apriori.py -p HH94 -s RF_ok --date 2020/09/17 --time 18:42
update_apriori.py -p HH109 -s RF_ok --date 2020/09/17 --time 18:42
update_apriori.py -p HH111 -s RF_ok --date 2020/09/17 --time 18:42
update_apriori.py -p HH112 -s RF_ok --date 2020/09/17 --time 18:42
update_apriori.py -p HH127 -s RF_ok --date 2020/09/17 --time 18:42
update_apriori.py -p HH129 -s RF_ok --date 2020/09/17 --time 18:42
add_part_info.py -p HH92 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/17 --time 18:42:00
add_part_info.py -p HH92 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/17 --time 18:42:02
add_part_info.py -p HH93 -r A -c 'Looks dead in post-PAM spectre 17 Sept' -l "infoupd" --date 2020/09/17 --time 18:42:00
add_part_info.py -p HH93 -r A -c 'Looks dead in post-PAM spectre 17 Sept' -l "infoupd" --date 2020/09/17 --time 18:42:02
add_part_info.py -p HH94 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/17 --time 18:42:00
add_part_info.py -p HH94 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/17 --time 18:42:02
add_part_info.py -p HH109 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/17 --time 18:42:00
add_part_info.py -p HH109 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/17 --time 18:42:02
add_part_info.py -p HH110 -r A -c 'Nice post-PAM autos 17 Sept, but SNAP spectra looks wonky' -l "infoupd" --date 2020/09/17 --time 18:42:00
add_part_info.py -p HH110 -r A -c 'OK post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/17 --time 18:42:02
add_part_info.py -p HH111 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/17 --time 18:42:00
add_part_info.py -p HH111 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/17 --time 18:42:02
add_part_info.py -p HH112 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/17 --time 18:42:00
add_part_info.py -p HH112 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/17 --time 18:42:02
add_part_info.py -p HH127 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/17 --time 18:42:00
add_part_info.py -p HH127 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/17 --time 18:42:02
add_part_info.py -p HH129 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/17 --time 18:42:00
add_part_info.py -p HH129 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/17 --time 18:42:02
add_part_info.py -p HH45 -r A -c 'post-PAM spectre looks fine 17 sept' -l "infoupd" --date 2020/09/17 --time 18:42:00
add_part_info.py -p HH45 -r A -c 'post-PAM spectre looks fine 17 sept' -l "infoupd" --date 2020/09/17 --time 18:42:02
add_part_info.py -p HH59 -r A -c '59E has rising tail in 17 spet post-pam spectre' -l "infoupd" --date 2020/09/17 --time 18:42:00
add_part_info.py -p HH59 -r A -c '59E has rising tail in 17 spet post-pam spectre' -l "infoupd" --date 2020/09/17 --time 18:42:02
