#! /bin/bash
source ~/.bashrc
echo "200918_infoupd_2042" >> scripts.log 
update_apriori.py -p HH11 -s RF_ok --date 2020/09/18 --time 20:42
update_apriori.py -p HH13 -s RF_ok --date 2020/09/18 --time 20:42
update_apriori.py -p HH43 -s RF_maintenance --date 2020/09/18 --time 20:42
update_apriori.py -p HH46 -s RF_ok --date 2020/09/18 --time 20:42
update_apriori.py -p HH60 -s digital_maintenance --date 2020/09/18 --time 20:42
update_apriori.py -p HH72 -s RF_ok --date 2020/09/18 --time 20:42
update_apriori.py -p HH83 -s RF_ok --date 2020/09/18 --time 20:42
add_part_info.py -p HH2 -r A -c '2E looks fine 18 Sept' -l "infoupd" --date 2020/09/18 --time 20:42:00
add_part_info.py -p HH2 -r A -c '2N still looks wonky in SNAP spectra 18 Sept' -l "infoupd" --date 2020/09/18 --time 20:42:02
add_part_info.py -p HH11 -r A -c 'sbcd 18 sept due to heranow autos and SNAP spectra' -l "apa-infoupd" --date 2020/09/18 --time 20:42:00
add_part_info.py -p HH11 -r A -c 'sbcd 18 sept due to heranow autos and SNAP spectra' -l "apa-infoupd" --date 2020/09/18 --time 20:42:02
add_part_info.py -p HH13 -r A -c 'sbcd 18 sept due to heranow autos and SNAP spectra' -l "apa-infoupd" --date 2020/09/18 --time 20:42:00
add_part_info.py -p HH13 -r A -c 'sbcd 18 sept due to heranow autos and SNAP spectra' -l "apa-infoupd" --date 2020/09/18 --time 20:42:02
add_part_info.py -p HH67 -r A -c 'SNAP autos look low, flat, spiky ,as does all of N3 18 Sept' -l "infoupd" --date 2020/09/18 --time 20:42:00
add_part_info.py -p HH67 -r A -c 'SNAP autos look low, flat, spiky ,as does all of N3 18 Sept' -l "infoupd" --date 2020/09/18 --time 20:42:02
add_part_info.py -p HH72 -r A -c '72E looks fine in 18 Sept SNAP sprectra' -l "apa-infoupd" --date 2020/09/18 --time 20:42:00
add_part_info.py -p HH72 -r A -c '72N looks fine in 18 Sept SNAP sprectra' -l "apa-infoupd" --date 2020/09/18 --time 20:42:02
add_part_info.py -p HH46 -r A -c 'fine SNAP spectra on 18-Sept' -l "apa-infoupd" --date 2020/09/18 --time 20:42:00
add_part_info.py -p HH46 -r A -c 'fine SNAP spectra on 18-Sept' -l "apa-infoupd" --date 2020/09/18 --time 20:42:02
add_part_info.py -p HH60 -r A -c 'SNAP spectra look bad  18 sept; N5S2 last data is from March' -l "apa-infoupd" --date 2020/09/18 --time 20:42:00
add_part_info.py -p HH60 -r A -c 'SNAP spectra look bad  18 sept; N5S2 last data is from March' -l "apa-infoupd" --date 2020/09/18 --time 20:42:02
add_part_info.py -p HH83 -r A -c 'SNAP auto looks fine 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 20:42:00
add_part_info.py -p HH83 -r A -c 'SNAP auto looks fine 18 Sept' -l "apa-infoupd" --date 2020/09/18 --time 20:42:02
