#! /bin/bash
source ~/.bashrc
echo "200928_infoupd_1842" >> scripts.log 
update_apriori.py -p HH66 -s RF_ok --date 2020/09/28 --time 18:42
add_part_info.py -p HH66 -r A -c 'apriori_antenna status change: RF_maintenance -> RF_ok' -l "apa-infoupd" --date 2020/09/28 --time 18:42
update_apriori.py -p HH87 -s RF_ok --date 2020/09/28 --time 18:42
add_part_info.py -p HH87 -r A -c 'apriori_antenna status change: RF_maintenance -> RF_ok' -l "apa-infoupd" --date 2020/09/28 --time 18:42
update_apriori.py -p HH130 -s RF_ok --date 2020/09/28 --time 18:42
add_part_info.py -p HH130 -r A -c 'apriori_antenna status change: RF_maintenance -> RF_ok' -l "apa-infoupd" --date 2020/09/28 --time 18:42
add_part_info.py -p HH24 -r A -c ' ' -l "infoupd" --date 2020/09/28 --time 18:42:00
add_part_info.py -p HH24 -r A -c 'Feed Heights: Ant 24 Z= 4.415' -l "infoupd" --date 2020/09/28 --time 18:42:02
add_part_info.py -p HH24 -r A -c ' ' -l "infoupd" --date 2020/09/28 --time 18:42:04
add_part_info.py -p HH130 -r A -c 'N10A130 xyz positoned and spectra looks fine 28 Sept.' -l "apa-infoupd" --date 2020/09/28 --time 18:42:00
add_part_info.py -p HH130 -r A -c 'Feed heights (NE/SE/SW/NW): Ant 130 Z= 4.409' -l "apa-infoupd" --date 2020/09/28 --time 18:42:02
add_part_info.py -p HH130 -r A -c ' ' -l "apa-infoupd" --date 2020/09/28 --time 18:42:04
add_part_info.py -p HH66 -r A -c 'N3A66 xyz positioned and spectra looks very fine 28 Sept.' -l "apa-infoupd" --date 2020/09/28 --time 18:42:00
add_part_info.py -p HH66 -r A -c 'Feed heights (NE/SE/SW/NW): Ant 66 Z= 4.402' -l "apa-infoupd" --date 2020/09/28 --time 18:42:02
add_part_info.py -p HH66 -r A -c ' ' -l "apa-infoupd" --date 2020/09/28 --time 18:42:04
add_part_info.py -p HH87 -r A -c 'N8A86 xyz positioned and SNAP spectra looks fine 28 Sept.' -l "apa-infoupd" --date 2020/09/28 --time 18:42:00
