#! /bin/bash
source ~/.bashrc
echo "200918_infoupd_1942" >> scripts.log 
update_apriori.py -p HH37 -s RF_maintenance --date 2020/09/18 --time 19:42
update_apriori.py -p HH38 -s RF_maintenance --date 2020/09/18 --time 19:42
add_part_info.py -p HH12 -r A -c 'Post-PAM spectra of 18 Sept show both pols looking dead' -l "infoupd" --date 2020/09/18 --time 19:42:00
add_part_info.py -p HH12 -r A -c 'Post-PAM spectra of 18 Sept show both pols looking dead' -l "infoupd" --date 2020/09/18 --time 19:42:02
add_part_info.py -p HH23 -r A -c 'Post-PAM spectra of 18 Sept show both pols low amplitude and showing correct atuo shape' -l "infoupd" --date 2020/09/18 --time 19:42:00
add_part_info.py -p HH37 -r A -c 'post-PAM spectra of 18 Sept show nice E spectra; N looks dead' -l "apa-infoupd" --date 2020/09/18 --time 19:42:00
add_part_info.py -p HH37 -r A -c 'post-PAM spectra of 18 Sept show nice E spectra; N looks dead' -l "apa-infoupd" --date 2020/09/18 --time 19:42:02
add_part_info.py -p HH38 -r A -c 'post-PAM spectra of 18 Sept show nice E spectra; N looks dead' -l "apa-infoupd" --date 2020/09/18 --time 19:42:00
add_part_info.py -p HH38 -r A -c 'post-PAM spectra of 18 Sept show nice E spectra; N looks dead' -l "apa-infoupd" --date 2020/09/18 --time 19:42:02
add_part_info.py -p HH41 -r A -c 'Looks fine in 18 Sept post-PAM sprectra' -l "infoupd" --date 2020/09/18 --time 19:42:00
add_part_info.py -p HH41 -r A -c 'Looks fine in 18 Sept post-PAM sprectra' -l "infoupd" --date 2020/09/18 --time 19:42:02
add_part_info.py -p HH42 -r A -c '42 E looks dead and spiky in 18 Sept post-PAM spectre' -l "infoupd" --date 2020/09/18 --time 19:42:00
add_part_info.py -p HH42 -r A -c '42 N looks ok (not great) in 18 Sept post-PAM spectre' -l "infoupd" --date 2020/09/18 --time 19:42:02
add_part_info.py -p HH56 -r A -c 'Looks fine in 18 Sept post_PAM spectre' -l "infoupd" --date 2020/09/18 --time 19:42:00
add_part_info.py -p HH56 -r A -c 'Looks fine in 18 Sept post_PAM spectre' -l "infoupd" --date 2020/09/18 --time 19:42:02
add_part_info.py -p HH71 -r A -c '71E looks atypical in 18 Sept post-PAM sprectra' -l "infoupd" --date 2020/09/18 --time 19:42:00
add_part_info.py -p HH71 -r A -c '71N looks fine in 18 Sept post-PAM sprectra' -l "infoupd" --date 2020/09/18 --time 19:42:02
add_part_info.py -p HH43 -r A -c '43 E looks dead  in 18 Sept post-PAM spectre' -l "infoupd" --date 2020/09/18 --time 19:42:00
add_part_info.py -p HH43 -r A -c '43 N looks fine in 18 Sept post-PAM spectre' -l "infoupd" --date 2020/09/18 --time 19:42:02
