#! /bin/bash
source ~/.bashrc
echo "200921_infoupd_2042" >> scripts.log 
update_apriori.py -p HH51 -s digital_maintenance --date 2020/09/21 --time 20:42
update_apriori.py -p HH53 -s digital_maintenance --date 2020/09/21 --time 20:42
update_apriori.py -p HH67 -s digital_maintenance --date 2020/09/21 --time 20:42
update_apriori.py -p HH68 -s digital_maintenance --date 2020/09/21 --time 20:42
update_apriori.py -p HH110 -s RF_maintenance --date 2020/09/21 --time 20:42
update_apriori.py -p HH182 -s RF_maintenance --date 2020/09/21 --time 20:42
add_part_info.py -p HH110 -r A -c 'Ant 110 N has rising slope at hi freq and looks bad in 113 DN. 21 Sept.' -l "apa-infoupd" --date 2020/09/21 --time 20:42:00
add_part_info.py -p HH110 -r A -c 'Ant 110 N has rising slope at hi freq and looks bad in 113 DN. 21 Sept.' -l "apa-infoupd" --date 2020/09/21 --time 20:42:02
add_part_info.py -p HH182 -r A -c '113 DN has E pol showing high niosy line (knwon FFT issue, I think)...' -l "apa-infoupd" --date 2020/09/21 --time 20:42:00
add_part_info.py -p HH182 -r A -c '113 DN has E pol showing high niosy line (knwon FFT issue, I think)...' -l "apa-infoupd" --date 2020/09/21 --time 20:42:02
add_part_info.py -p HH51 -r A -c 'Daily notebook on 113 shows bad data. Was dig_ok.' -l "apa-infoupd" --date 2020/09/21 --time 20:42:00
add_part_info.py -p HH51 -r A -c 'Daily notebook on 113 shows bad data. Was dig_ok.' -l "apa-infoupd" --date 2020/09/21 --time 20:42:02
add_part_info.py -p HH53 -r A -c 'Daily notebook on 113 shows bad data. Was dig_ok.' -l "apa-infoupd" --date 2020/09/21 --time 20:42:00
add_part_info.py -p HH53 -r A -c 'Daily notebook on 113 shows bad data. Was dig_ok.' -l "apa-infoupd" --date 2020/09/21 --time 20:42:02
add_part_info.py -p HH67 -r A -c 'Daily notebook on 113 shows bad data. Was dig_ok.' -l "apa-infoupd" --date 2020/09/21 --time 20:42:00
add_part_info.py -p HH67 -r A -c 'Daily notebook on 113 shows bad data. Was dig_ok.' -l "apa-infoupd" --date 2020/09/21 --time 20:42:02
add_part_info.py -p HH68 -r A -c 'Daily notebook on 113 shows bad data. Was dig_ok.' -l "apa-infoupd" --date 2020/09/21 --time 20:42:00
add_part_info.py -p HH68 -r A -c 'Daily notebook on 113 shows bad data. Was dig_ok.' -l "apa-infoupd" --date 2020/09/21 --time 20:42:02
add_part_info.py -p HH107 -r A -c '107 SNAP autos have a fine shape; N pol is lower amplidude. DN autos look the same. 21 Sept. ' -l "infoupd" --date 2020/09/21 --time 20:42:00
add_part_info.py -p HH107 -r A -c '107 SNAP autos have a fine shape; N pol is lower amplidude. DN autos look the same. 21 Sept.' -l "infoupd" --date 2020/09/21 --time 20:42:02
