#! /bin/bash
source ~/.bashrc
echo "200918_infoupd_1742" >> scripts.log 
update_apriori.py -p HH84 -s RF_ok --date 2020/09/18 --time 17:42
update_apriori.py -p HH135 -s RF_ok --date 2020/09/18 --time 17:42
update_apriori.py -p HH140 -s RF_ok --date 2020/09/18 --time 17:42
update_apriori.py -p HH144 -s RF_ok --date 2020/09/18 --time 17:42
update_apriori.py -p HH162 -s RF_ok --date 2020/09/18 --time 17:42
update_apriori.py -p HH163 -s RF_ok --date 2020/09/18 --time 17:42
update_apriori.py -p HH165 -s RF_ok --date 2020/09/18 --time 17:42
update_apriori.py -p HH166 -s RF_ok --date 2020/09/18 --time 17:42
update_apriori.py -p HH177 -s RF_ok --date 2020/09/18 --time 17:42
update_apriori.py -p HH178 -s RF_ok --date 2020/09/18 --time 17:42
update_apriori.py -p HH179 -s RF_ok --date 2020/09/18 --time 17:42
update_apriori.py -p HH181 -s RF_ok --date 2020/09/18 --time 17:42
update_apriori.py -p HH184 -s RF_ok --date 2020/09/18 --time 17:42
update_apriori.py -p HH185 -s RF_ok --date 2020/09/18 --time 17:42
add_part_info.py -p HH23 -r A -c 'loose central line' -l "infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH135 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH135 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH155 -r A -c 'low, flat  post-PAM auto 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH155 -r A -c 'low, flat  post-PAM auto 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH177 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH177 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH178 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH178 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH179 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH179 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH162 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH162 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH183 -r A -c 'Nice post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH183 -r A -c 'Nice post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH140 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH140 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH142 -r A -c 'Nice post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH142 -r A -c 'post-PAM auto is low and flat 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH160 -r A -c 'Nice post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH160 -r A -c 'Nice post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH180 -r A -c 'post-PAM auto looks strange - lopsided at low freq 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH180 -r A -c 'post-PAM auto is low and flat 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH181 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH181 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH144 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH144 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH145 -r A -c 'Nice post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH145 -r A -c 'Nice post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH163 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH163 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH164 -r A -c 'Nice post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH164 -r A -c 'Nice post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH165 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH165 -r A -c 'Nice post-PAM autos 17 Sept,' -l "apa-infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH166 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH166 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH184 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH184 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH185 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH185 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH186 -r A -c 'Nice post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH186 -r A -c 'Nice post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH84 -r A -c 'Nice post-PAM auto 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:00
add_part_info.py -p HH84 -r A -c 'Nice post-PAM auto 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 17:42:02
add_part_info.py -p HH87 -r A -c 'Nice post-PAM auto 17 Sept' -l "infoupd" --date 2020/09/18 --time 17:42:00
