#! /bin/bash
source ~/.bashrc
echo "200909_infoupd_1942" >> scripts.log 
update_apriori.py -p HH143 -s RF_ok --date 2020/09/09 --time 19:42
update_apriori.py -p HH144 -s RF_maintenance --date 2020/09/09 --time 19:42
update_apriori.py -p HH148 -s RF_ok --date 2020/09/09 --time 19:42
update_apriori.py -p HH150 -s RF_ok --date 2020/09/09 --time 19:42
update_apriori.py -p HH163 -s RF_maintenance --date 2020/09/09 --time 19:42
update_apriori.py -p HH167 -s RF_ok --date 2020/09/09 --time 19:42
update_apriori.py -p HH168 -s RF_ok --date 2020/09/09 --time 19:42
update_apriori.py -p HH169 -s RF_ok --date 2020/09/09 --time 19:42
update_apriori.py -p HH170 -s RF_ok --date 2020/09/09 --time 19:42
update_apriori.py -p HH189 -s RF_ok --date 2020/09/09 --time 19:42
update_apriori.py -p HH190 -s RF_ok --date 2020/09/09 --time 19:42
update_apriori.py -p HH191 -s RF_ok --date 2020/09/09 --time 19:42
