#! /bin/bash
source ~/.bashrc
echo "200921_infoupd_1942" >> scripts.log 
update_apriori.py -p HH107 -s RF_ok --date 2020/09/21 --time 19:42
add_part_info.py -p HH138 -r A -c '138N SNAP auto looks too bumpy on 21 Sept.' -l "infoupd" --date 2020/09/21 --time 19:42:00
add_part_info.py -p HH138 -r A -c '138N SNAP auto looks too bumpy on 21 Sept.' -l "infoupd" --date 2020/09/21 --time 19:42:02
