#! /bin/bash
source ~/.bashrc
echo "200918_infoupd_1642" >> scripts.log 
update_apriori.py -p HH90 -s RF_maintenance --date 2020/09/18 --time 16:42
update_apriori.py -p HH122 -s RF_ok --date 2020/09/18 --time 16:42
update_apriori.py -p HH157 -s RF_ok --date 2020/09/18 --time 16:42
add_part_info.py -p HH155 -r A -c 'low post-PAM auto 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:00
add_part_info.py -p HH156 -r A -c 'Nice post-PAM auto 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:00
add_part_info.py -p HH156 -r A -c 'low post-PAM auto 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:02
add_part_info.py -p HH157 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 16:42:00
add_part_info.py -p HH157 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 16:42:02
add_part_info.py -p HH116 -r A -c '116 autos look dead in post-PAM auto 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:00
add_part_info.py -p HH116 -r A -c '116 autos look dead in post-PAM auto 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:02
add_part_info.py -p HH137 -r A -c '137 autos look dead in post-PAM auto 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:00
add_part_info.py -p HH137 -r A -c '137 autos look dead in post-PAM auto 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:02
add_part_info.py -p HH101 -r A -c 'Nice post-PAM auto 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:00
add_part_info.py -p HH101 -r A -c '101N looks dead in post-PAM auto  17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:02
add_part_info.py -p HH102 -r A -c 'Nice post-PAM auto 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:00
add_part_info.py -p HH102 -r A -c 'Nice post-PAM auto 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:02
add_part_info.py -p HH103 -r A -c 'Nice post-PAM auto 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:00
add_part_info.py -p HH103 -r A -c 'Nice post-PAM auto 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:02
add_part_info.py -p HH122 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 16:42:00
add_part_info.py -p HH122 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 16:42:02
add_part_info.py -p HH123 -r A -c 'Auto is just a low hump in post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:00
add_part_info.py -p HH123 -r A -c 'Nice post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:02
add_part_info.py -p HH89 -r A -c 'Nice post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:00
add_part_info.py -p HH89 -r A -c 'Nice post-PAM autos 17 Sept' -l "infoupd" --date 2020/09/18 --time 16:42:02
add_part_info.py -p HH90 -r A -c '90N low in post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 16:42:00
add_part_info.py -p HH90 -r A -c 'Nice post-PAM autos 17 Sept' -l "apa-infoupd" --date 2020/09/18 --time 16:42:02
