#! /bin/bash
source ~/.bashrc
echo "200922_infoupd_2342" >> scripts.log 
update_apriori.py -p HH81 -s RF_maintenance --date 2020/09/22 --time 23:42
update_apriori.py -p HH90 -s RF_ok --date 2020/09/22 --time 23:42
update_apriori.py -p HH184 -s RF_maintenance --date 2020/09/22 --time 23:42
add_part_info.py -p HH184 -r A -c 'Ant 184 N newly high under and over the bandpass; bandpass looks flatter than expected. See Observing review for day 591115 issue. ' -l "apa-infoupd" --date 2020/09/22 --time 23:42:00
add_part_info.py -p HH184 -r A -c ' ' -l "apa-infoupd" --date 2020/09/22 --time 23:42:02
add_part_info.py -p HH42 -r A -c '42 E looks dead and spiky in 18 Sept post-PAM spectre. 42 N looks ok (not great) in 18 Sept post-PAM spectre' -l "infoupd" --date 2020/09/22 --time 23:42:00
add_part_info.py -p HH42 -r A -c ' ' -l "infoupd" --date 2020/09/22 --time 23:42:02
add_part_info.py -p HH81 -r A -c 'N7A81 E is too low. N looks fine. 22 Sept. See Observing review for day 591115 issue' -l "apa-infoupd" --date 2020/09/22 --time 23:42:00
add_part_info.py -p HH81 -r A -c ' ' -l "apa-infoupd" --date 2020/09/22 --time 23:42:02
add_part_info.py -p HH90 -r A -c 'N9A90 E has lower power, but looks fine. 22 Sept. See Observing review for day 591115 issue' -l "apa-infoupd" --date 2020/09/22 --time 23:42:00
add_part_info.py -p HH90 -r A -c ' ' -l "apa-infoupd" --date 2020/09/22 --time 23:42:02
