#! /bin/bash
source ~/.bashrc
echo "201008_infoupd_1542" >> scripts.log 
update_apriori.py -p HH3 -s digital_ok --date 2020/10/08 --time 15:43
add_part_info.py -p HH3 -r A -c 'apriori_antenna status change: RF_maintenance -> digital_ok' -l "apa-infoupd" --date 2020/10/08 --time 15:43
update_apriori.py -p HH4 -s RF_maintenance --date 2020/10/08 --time 15:43
add_part_info.py -p HH4 -r A -c 'apriori_antenna status change: digital_ok -> RF_maintenance' -l "apa-infoupd" --date 2020/10/08 --time 15:43
update_apriori.py -p HH5 -s digital_ok --date 2020/10/08 --time 15:43
add_part_info.py -p HH5 -r A -c 'apriori_antenna status change: RF_maintenance -> digital_ok' -l "apa-infoupd" --date 2020/10/08 --time 15:43
update_apriori.py -p HH15 -s RF_maintenance --date 2020/10/08 --time 15:43
add_part_info.py -p HH15 -r A -c 'apriori_antenna status change: digital_ok -> RF_maintenance' -l "apa-infoupd" --date 2020/10/08 --time 15:43
update_apriori.py -p HH16 -s RF_maintenance --date 2020/10/08 --time 15:43
add_part_info.py -p HH16 -r A -c 'apriori_antenna status change: digital_ok -> RF_maintenance' -l "apa-infoupd" --date 2020/10/08 --time 15:43
update_apriori.py -p HH18 -s digital_ok --date 2020/10/08 --time 15:43
add_part_info.py -p HH18 -r A -c 'apriori_antenna status change: RF_maintenance -> digital_ok' -l "apa-infoupd" --date 2020/10/08 --time 15:43
update_apriori.py -p HH147 -s digital_ok --date 2020/10/08 --time 15:43
add_part_info.py -p HH147 -r A -c 'apriori_antenna status change: RF_maintenance -> digital_ok' -l "apa-infoupd" --date 2020/10/08 --time 15:43
update_apriori.py -p HH150 -s RF_maintenance --date 2020/10/08 --time 15:43
add_part_info.py -p HH150 -r A -c 'apriori_antenna status change: digital_ok -> RF_maintenance' -l "apa-infoupd" --date 2020/10/08 --time 15:43
update_apriori.py -p HH168 -s RF_maintenance --date 2020/10/08 --time 15:43
add_part_info.py -p HH168 -r A -c 'apriori_antenna status change: digital_ok -> RF_maintenance' -l "apa-infoupd" --date 2020/10/08 --time 15:43
add_part_info.py -p HH18 -r A -c '59131 SNAP auto look fine. No DN to check other metrics' -l "apa-infoupd" --date 2020/10/08 --time 15:42:00
add_part_info.py -p HH3 -r A -c '59131 SNAP auto look fine. No DN to check other metrics' -l "apa-infoupd" --date 2020/10/08 --time 15:42:00
add_part_info.py -p HH4 -r A -c '59131 SNAP auto looks like N1A4 is seeing sky' -l "apa-infoupd" --date 2020/10/08 --time 15:42:00
add_part_info.py -p HH5 -r A -c '59131 SNAP auto look fine. No DN to check other metrics' -l "apa-infoupd" --date 2020/10/08 --time 15:42:00
add_part_info.py -p HH15 -r A -c '59131  N1A5 e  SNAP auto has a glitch at 185 MHz' -l "apa-infoupd" --date 2020/10/08 --time 15:42:00
add_part_info.py -p HH16 -r A -c '59131 SNAP auto looks like N1A4 is seeing sky' -l "apa-infoupd" --date 2020/10/08 --time 15:42:00
add_part_info.py -p HH147 -r A -c '59131 SNAP auto look fine. No DN to check other metrics' -l "apa-infoupd" --date 2020/10/08 --time 15:42:00
add_part_info.py -p HH148 -r A -c '59131 SNAP auto look fine. No DN to check other metrics' -l "infoupd" --date 2020/10/08 --time 15:42:00
add_part_info.py -p HH149 -r A -c '59131 N15A149 n SNAP auto has unexpected wobbles.' -l "infoupd" --date 2020/10/08 --time 15:42:00
add_part_info.py -p HH150 -r A -c '59131 N15A150 SNAP auto looks like sky/load.' -l "apa-infoupd" --date 2020/10/08 --time 15:42:00
add_part_info.py -p HH168 -r A -c '59131 N15A149 n SNAP auto has unexpected glitch @ 213 MHz' -l "apa-infoupd" --date 2020/10/08 --time 15:42:00
