#! /bin/bash
echo "./201012_add_wr_rd_rosetta.py" >> scripts.log 
update_part_rosetta.py 'WR-len4p0' 'heraNode0wr' --date 2020/03/01 --time 10:00
update_part_rosetta.py 'RD02' 'heraNode0' --date 2020/03/01 --time 10:00
update_part_rosetta.py 'WRA000096' 'heraNode1wr' --date 2020/02/15 --time 10:00
update_part_rosetta.py 'RD18' 'heraNode1' --date 2020/02/15 --time 10:00
update_part_rosetta.py 'WRA000089' 'heraNode3wr' --date 2019/11/13 --time 10:00
update_part_rosetta.py 'RD06' 'heraNode3' --date 2019/11/13 --time 10:00
update_part_rosetta.py 'WR-unknown' 'heraNode4wr' --date 2019/10/31 --time 10:00
update_part_rosetta.py 'RD41' 'heraNode4' --date 2019/10/31 --time 10:00
update_part_rosetta.py 'WRA000084' 'heraNode5wr' --date 2019/10/31 --time 10:00
update_part_rosetta.py 'RD42' 'heraNode5' --date 2019/10/31 --time 10:00
update_part_rosetta.py 'WRA000028' 'heraNode7wr' --date 2019/08/02 --time 10:00
update_part_rosetta.py 'RD31' 'heraNode7' --date 2019/08/02 --time 10:00
update_part_rosetta.py 'WRA000086' 'heraNode8wr' --date 2019/08/02 --time 10:00
update_part_rosetta.py 'RD45' 'heraNode8' --date 2019/08/02 --time 10:00
update_part_rosetta.py 'WRA000083' 'heraNode9wr' --date 2019/05/15 --time 10:00
update_part_rosetta.py 'RD46' 'heraNode9' --date 2019/05/15 --time 10:00
update_part_rosetta.py 'WRA000093' 'heraNode10wr' --date 2019/11/13 --time 10:00
update_part_rosetta.py 'RD20' 'heraNode10' --date 2019/11/13 --time 10:00
update_part_rosetta.py 'WRA000091' 'heraNode12wr' --date 2020/01/31 --time 10:00
update_part_rosetta.py 'RD15' 'heraNode12' --date 2020/01/31 --time 10:00
update_part_rosetta.py 'WRA000094' 'heraNode13wr' --date 2020/01/31 --time 10:00
update_part_rosetta.py 'RD19' 'heraNode13' --date 2020/01/31 --time 10:00
update_part_rosetta.py 'WRA000097' 'heraNode14wr' --date 2020/01/31 --time 10:00
update_part_rosetta.py 'RD43' 'heraNode14' --date 2020/01/31 --time 10:00
update_part_rosetta.py 'WRA000006' 'heraNode15wr' --date 2020/01/28 --time 10:00
update_part_rosetta.py 'RD40' 'heraNode15' --date 2020/01/28 --time 10:00
