#! /bin/bash
source ~/.bashrc
echo "201005_infoupd_1742" >> scripts.log 
add_part_info.py -p HH11 -r A -c 'placing in dig_maint from rf_ok 29 Sept.' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH13 -r A -c 'placing in dig_maint from rf_ok 29 Sept.' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH14 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH26 -r A -c 'reducing to digital maintenance from dig_ok per Comm weekly 29 Sept: dont use N0 for science' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH6 -r A -c 'cable too short to reach Node' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH158 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH158 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:02
add_part_info.py -p HH184 -r A -c 'Ant 184 N newly high under and over the bandpass; bandpass looks flatter than expected. See Observing review for day 591115 issue.' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH36 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH36 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:02
add_part_info.py -p HH67 -r A -c 'N3A67 N is low amplitude. moving from dig_maint to rf_maint. 24 Sept.' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH40 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH69 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH69 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:02
add_part_info.py -p HH70 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH70 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:02
add_part_info.py -p HH73 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH73 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:02
add_part_info.py -p HH75 -r A -c 'sbcd 17 Sept due to low N post-PAM spectra' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH75 -r A -c 'sbcd 17 Sept due to low N post-PAM spectra' -l "infoupd" --date 2020/10/05 --time 17:42:02
add_part_info.py -p HH84 -r A -c 'N8A84 E is low amplitude. Moving from RF_ok to RF_maint. 24 Sept.' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH85 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH85 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:02
add_part_info.py -p HH86 -r A -c 'N8A86 N shows unexpected bump around 200 MHz. Moving from RF_ok to RF_maint. 24 Sept.' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH104 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:00
add_part_info.py -p HH104 -r A -c 'reported sync ok by dgorki Aug 7' -l "infoupd" --date 2020/10/05 --time 17:42:02
