#! /bin/bash
source ~/.bashrc
echo "201006_infoupd_1742" >> scripts.log 
update_apriori.py -p HH50 -s digital_ok --date 2020/10/06 --time 17:43
add_part_info.py -p HH50 -r A -c 'apriori_antenna status change: RF_ok -> digital_ok' -l "apa-infoupd" --date 2020/10/06 --time 17:43
update_apriori.py -p HH52 -s digital_ok --date 2020/10/06 --time 17:43
add_part_info.py -p HH52 -r A -c 'apriori_antenna status change: RF_ok -> digital_ok' -l "apa-infoupd" --date 2020/10/06 --time 17:43
update_apriori.py -p HH66 -s digital_ok --date 2020/10/06 --time 17:43
add_part_info.py -p HH66 -r A -c 'apriori_antenna status change: RF_ok -> digital_ok' -l "apa-infoupd" --date 2020/10/06 --time 17:43
update_apriori.py -p HH67 -s digital_ok --date 2020/10/06 --time 17:43
add_part_info.py -p HH67 -r A -c 'apriori_antenna status change: RF_maintenance -> digital_ok' -l "apa-infoupd" --date 2020/10/06 --time 17:43
update_apriori.py -p HH123 -s digital_ok --date 2020/10/06 --time 17:43
add_part_info.py -p HH123 -r A -c 'apriori_antenna status change: RF_maintenance -> digital_ok' -l "apa-infoupd" --date 2020/10/06 --time 17:43
update_apriori.py -p HH162 -s digital_maintenance --date 2020/10/06 --time 17:43
add_part_info.py -p HH162 -r A -c 'apriori_antenna status change: digital_ok -> digital_maintenance' -l "apa-infoupd" --date 2020/10/06 --time 17:43
update_apriori.py -p HH166 -s digital_ok --date 2020/10/06 --time 17:43
add_part_info.py -p HH166 -r A -c 'apriori_antenna status change: RF_maintenance -> digital_ok' -l "apa-infoupd" --date 2020/10/06 --time 17:43
add_part_info.py -p HH166 -r A -c 'Moved from rf_maint  to dig_ok  as looks like seing sky rather than load. 06 Oct.' -l "apa-infoupd" --date 2020/10/06 --time 17:42:00
add_part_info.py -p HH50 -r A -c 'Looks OK in heranow autos and 59125 DN, moving from rf_maint to dig_ok. 06 Oct.' -l "apa-infoupd" --date 2020/10/06 --time 17:42:00
add_part_info.py -p HH52 -r A -c 'Looks OK in heranow autos and 59125 DN, moving from rf_maint to dig_ok. 06 Oct.' -l "apa-infoupd" --date 2020/10/06 --time 17:42:00
add_part_info.py -p HH66 -r A -c 'Looks OK in heranow autos and 59125 DN, moving from rf_maint to dig_ok. 06 Oct.' -l "apa-infoupd" --date 2020/10/06 --time 17:42:00
add_part_info.py -p HH67 -r A -c 'N3A67 n and e auto amplitudes look OK in heranow autos, moving from rf_maint to dig_ok. 06 Oct.' -l "apa-infoupd" --date 2020/10/06 --time 17:42:00
add_part_info.py -p HH123 -r A -c 'Looks OK in heranow autos and 59125 DN, moving from rf_maint to dig_ok. 06 Oct.' -l "apa-infoupd" --date 2020/10/06 --time 17:42:00
