#! /bin/bash
source ~/.bashrc
echo "201110_infoupd_1642" >> scripts.log 
add_part_info.py -p HH161 -r A -c 'Final post-PAM spectra looks fine' -l "infoupd" --date 2020/11/10 --time 16:42:00
add_part_info.py -p HH161 -r A -c 'Final post-PAM spectra looks fine' -l "infoupd" --date 2020/11/10 --time 16:42:02
