#! /bin/bash
source ~/.bashrc
echo "210112_infoupd_1142" >> scripts.log 
add_part_info.py -p HH147 -r A -c 'Feed heights (NE/SE/SW/NW): Z = 4.412' -l "infoupd" --date 2021/01/12 --time 11:42:00
add_part_info.py -p HH148 -r A -c 'Feed heights (NE/SE/SW/NW): Z = 4.407' -l "infoupd" --date 2021/01/12 --time 11:42:00
add_part_info.py -p HH149 -r A -c 'Feed heights (NE/SE/SW/NW): Z = 4.405' -l "infoupd" --date 2021/01/12 --time 11:42:00
add_part_info.py -p HH150 -r A -c 'Feed heights (NE/SE/SW/NW): Z = 4.411' -l "infoupd" --date 2021/01/12 --time 11:42:00
add_part_info.py -p HH167 -r A -c 'Feed heights (NE/SE/SW/NW): Z = 4.410' -l "infoupd" --date 2021/01/12 --time 11:42:00
add_part_info.py -p HH168 -r A -c 'Feed heights (NE/SE/SW/NW): Z = 4.407' -l "infoupd" --date 2021/01/12 --time 11:42:00
add_part_info.py -p HH170 -r A -c 'Feed heights (NE/SE/SW/NW): Z = 4.405' -l "infoupd" --date 2021/01/12 --time 11:42:00
add_part_info.py -p HH189 -r A -c 'Feed heights (NE/SE/SW/NW): Z = 4.409' -l "infoupd" --date 2021/01/12 --time 11:42:00
add_part_info.py -p HH190 -r A -c 'Feed heights (NE/SE/SW/NW): Z = 4.410' -l "infoupd" --date 2021/01/12 --time 11:42:00
add_part_info.py -p HH191 -r A -c 'Feed heights (NE/SE/SW/NW): Z = 4.410' -l "infoupd" --date 2021/01/12 --time 11:42:00
