#! /bin/bash
source ~/.bashrc
echo "210125_infoupd_1142" >> scripts.log 
add_part_info.py -p HH139 -r A -c 'SMA and CAT7 cables too short to connect feed to node' -l "infoupd" --date 2021/01/25 --time 11:42:00
add_part_info.py -p HH139 -r A -c 'SMA and CAT7 cables too short to connect feed to node' -l "infoupd" --date 2021/01/25 --time 11:42:02
add_part_info.py -p HH159 -r A -c 'SMA and CAT7 cables too short to connect feed to node' -l "infoupd" --date 2021/01/25 --time 11:42:00
add_part_info.py -p HH159 -r A -c 'SMA and CAT7 cables too short to connect feed to node' -l "infoupd" --date 2021/01/25 --time 11:42:02
