#! /bin/bash
source ~/.bashrc
echo "210122_infoupd_1042" >> scripts.log 
add_part_info.py -p HH2 -r A -c 'History: FEM: 17 | PAM: 23' -l "infoupd" --date 2021/01/22 --time 10:42:00
add_part_info.py -p HH11 -r A -c 'History: FEM: 19 | PAM: 25' -l "infoupd" --date 2021/01/22 --time 10:42:00
add_part_info.py -p HH12 -r A -c 'History: FEM: 20 | PAM: 26' -l "infoupd" --date 2021/01/22 --time 10:42:00
add_part_info.py -p HH14 -r A -c 'History: FEM: 28' -l "infoupd" --date 2021/01/22 --time 10:42:00
add_part_info.py -p HH24 -r A -c 'History: PAM: 24' -l "infoupd" --date 2021/01/22 --time 10:42:00
add_part_info.py -p HH25 -r A -c 'History: FEM: 31' -l "infoupd" --date 2021/01/22 --time 10:42:00
add_part_info.py -p HH26 -r A -c 'History: PAM: 26' -l "infoupd" --date 2021/01/22 --time 10:42:00
add_part_info.py -p HH39 -r A -c 'History: PAM: 27' -l "infoupd" --date 2021/01/22 --time 10:42:00
add_part_info.py -p HH103 -r A -c 'History: FEM: 60' -l "infoupd" --date 2021/01/22 --time 10:42:00
add_part_info.py -p HH103 -r A -c 'History: FEM: 60' -l "infoupd" --date 2021/01/22 --time 10:42:02
add_part_info.py -p HH89 -r A -c 'History: PAM: 43' -l "infoupd" --date 2021/01/22 --time 10:42:00
add_part_info.py -p HH124 -r A -c 'History: PAM: 42' -l "infoupd" --date 2021/01/22 --time 10:42:00
