#! /bin/bash
echo "210308_connupd_1516" >> scripts.log 
# Adding missing parts
add_part.py -p FDV192 -r A -t feed -m FDV192 --date 2021/03/08 --time 15:11
add_part.py -p FEM222 -r A -t front-end -m FEM222 --date 2021/03/08 --time 15:11
add_part.py -p FDV203 -r A -t feed -m FDV203 --date 2021/03/08 --time 15:11
add_part.py -p FEM227 -r A -t front-end -m FEM227 --date 2021/03/08 --time 15:11
add_part.py -p FEM264 -r A -t front-end -m FEM264 --date 2021/03/08 --time 15:11
add_part.py -p FEM254 -r A -t front-end -m FEM254 --date 2021/03/08 --time 15:11
add_part.py -p FDV202 -r A -t feed -m FDV202 --date 2021/03/08 --time 15:11
add_part.py -p FDV189 -r A -t feed -m FDV189 --date 2021/03/08 --time 15:11
add_part.py -p FDV172 -r A -t feed -m FDV172 --date 2021/03/08 --time 15:11
add_part.py -p FEM229 -r A -t front-end -m FEM229 --date 2021/03/08 --time 15:11
add_part.py -p FEM223 -r A -t front-end -m FEM223 --date 2021/03/08 --time 15:11
add_part.py -p FDV197 -r A -t feed -m FDV197 --date 2021/03/08 --time 15:11
add_part.py -p FDV186 -r A -t feed -m FDV186 --date 2021/03/08 --time 15:11
add_part.py -p FDV183 -r A -t feed -m FDV183 --date 2021/03/08 --time 15:11
add_part.py -p FEM231 -r A -t front-end -m FEM231 --date 2021/03/08 --time 15:11
add_part.py -p FEM260 -r A -t front-end -m FEM260 --date 2021/03/08 --time 15:11
add_part.py -p FDV184 -r A -t feed -m FDV184 --date 2021/03/08 --time 15:11
add_part.py -p FEM265 -r A -t front-end -m FEM265 --date 2021/03/08 --time 15:11
add_part.py -p FEM230 -r A -t front-end -m FEM230 --date 2021/03/08 --time 15:11
add_part.py -p FDV185 -r A -t feed -m FDV185 --date 2021/03/08 --time 15:11
add_part.py -p FEM225 -r A -t front-end -m FEM225 --date 2021/03/08 --time 15:11
add_part.py -p FDV193 -r A -t feed -m FDV193 --date 2021/03/08 --time 15:11
add_part.py -p FDV182 -r A -t feed -m FDV182 --date 2021/03/08 --time 15:11
add_part.py -p FEM224 -r A -t front-end -m FEM224 --date 2021/03/08 --time 15:11
add_part.py -p FEM228 -r A -t front-end -m FEM228 --date 2021/03/08 --time 15:11
add_part.py -p FDV176 -r A -t feed -m FDV176 --date 2021/03/08 --time 15:11
add_part.py -p FEM255 -r A -t front-end -m FEM255 --date 2021/03/08 --time 15:11
add_part.py -p FEM249 -r A -t front-end -m FEM249 --date 2021/03/08 --time 15:11
add_part.py -p FEM226 -r A -t front-end -m FEM226 --date 2021/03/08 --time 15:11
add_part.py -p FEM252 -r A -t front-end -m FEM252 --date 2021/03/08 --time 15:11
add_part.py -p FDV188 -r A -t feed -m FDV188 --date 2021/03/08 --time 15:11
add_part.py -p FEM259 -r A -t front-end -m FEM259 --date 2021/03/08 --time 15:11
add_part.py -p FDV210 -r A -t feed -m FDV210 --date 2021/03/08 --time 15:11
add_part.py -p FDV198 -r A -t feed -m FDV198 --date 2021/03/08 --time 15:11
add_part.py -p FEM266 -r A -t front-end -m FEM266 --date 2021/03/08 --time 15:11
add_part.py -p FDV191 -r A -t feed -m FDV191 --date 2021/03/08 --time 15:11
add_part.py -p FDV170 -r A -t feed -m FDV170 --date 2021/03/08 --time 15:11
add_part.py -p FDV196 -r A -t feed -m FDV196 --date 2021/03/08 --time 15:11
add_part.py -p FEM257 -r A -t front-end -m FEM257 --date 2021/03/08 --time 15:11
add_part.py -p FEM262 -r A -t front-end -m FEM262 --date 2021/03/08 --time 15:11
add_part.py -p FDV169 -r A -t feed -m FDV169 --date 2021/03/08 --time 15:11
add_part.py -p FDV187 -r A -t feed -m FDV187 --date 2021/03/08 --time 15:11
add_part.py -p FDV211 -r A -t feed -m FDV211 --date 2021/03/08 --time 15:11
add_part.py -p FDV190 -r A -t feed -m FDV190 --date 2021/03/08 --time 15:11
add_part.py -p FEM248 -r A -t front-end -m FEM248 --date 2021/03/08 --time 15:11
add_part.py -p FDV195 -r A -t feed -m FDV195 --date 2021/03/08 --time 15:11
add_part.py -p FEM221 -r A -t front-end -m FEM221 --date 2021/03/08 --time 15:11
add_part.py -p FEM232 -r A -t front-end -m FEM232 --date 2021/03/08 --time 15:11
# Adding missing connections
add_connection.py -u A204 --uprev H --upport focus -d FDV197 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV197 --uprev A --upport terminals -d FEM231 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM231 --uprev A --upport e -d NBP19 --dnrev A --dnport e1 --date 2021/03/08 --time 15:16
add_connection.py -u FEM231 --uprev A --upport n -d NBP19 --dnrev A --dnport n1 --date 2021/03/08 --time 15:16
add_connection.py -u A205 --uprev H --upport focus -d FDV211 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV211 --uprev A --upport terminals -d FEM224 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM224 --uprev A --upport e -d NBP19 --dnrev A --dnport e2 --date 2021/03/08 --time 15:16
add_connection.py -u FEM224 --uprev A --upport n -d NBP19 --dnrev A --dnport n2 --date 2021/03/08 --time 15:16
add_connection.py -u A206 --uprev H --upport focus -d FDV184 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV184 --uprev A --upport terminals -d FEM221 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM221 --uprev A --upport e -d NBP19 --dnrev A --dnport e3 --date 2021/03/08 --time 15:16
add_connection.py -u FEM221 --uprev A --upport n -d NBP19 --dnrev A --dnport n3 --date 2021/03/08 --time 15:16
add_connection.py -u A207 --uprev H --upport focus -d FDV210 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV210 --uprev A --upport terminals -d FEM232 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM232 --uprev A --upport e -d NBP19 --dnrev A --dnport e4 --date 2021/03/08 --time 15:16
add_connection.py -u FEM232 --uprev A --upport n -d NBP19 --dnrev A --dnport n4 --date 2021/03/08 --time 15:16
add_connection.py -u A208 --uprev H --upport focus -d FDV195 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV195 --uprev A --upport terminals -d FEM259 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM259 --uprev A --upport e -d NBP20 --dnrev A --dnport e7 --date 2021/03/08 --time 15:16
add_connection.py -u FEM259 --uprev A --upport n -d NBP20 --dnrev A --dnport n7 --date 2021/03/08 --time 15:16
add_connection.py -u A209 --uprev H --upport focus -d FDV196 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV196 --uprev A --upport terminals -d FEM265 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM265 --uprev A --upport e -d NBP20 --dnrev A --dnport e8 --date 2021/03/08 --time 15:16
add_connection.py -u FEM265 --uprev A --upport n -d NBP20 --dnrev A --dnport n8 --date 2021/03/08 --time 15:16
add_connection.py -u A210 --uprev H --upport focus -d FDV190 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV190 --uprev A --upport terminals -d FEM260 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM260 --uprev A --upport e -d NBP20 --dnrev A --dnport e9 --date 2021/03/08 --time 15:16
add_connection.py -u FEM260 --uprev A --upport n -d NBP20 --dnrev A --dnport n9 --date 2021/03/08 --time 15:16
add_connection.py -u A211 --uprev H --upport focus -d FDV191 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV191 --uprev A --upport terminals -d FEM262 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM262 --uprev A --upport e -d NBP20 --dnrev A --dnport e1 --date 2021/03/08 --time 15:16
add_connection.py -u FEM262 --uprev A --upport n -d NBP20 --dnrev A --dnport n1 --date 2021/03/08 --time 15:16
add_connection.py -u A223 --uprev H --upport focus -d FDV172 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV172 --uprev A --upport terminals -d FEM227 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM227 --uprev A --upport e -d NBP19 --dnrev A --dnport e5 --date 2021/03/08 --time 15:16
add_connection.py -u FEM227 --uprev A --upport n -d NBP19 --dnrev A --dnport n5 --date 2021/03/08 --time 15:16
add_connection.py -u A224 --uprev H --upport focus -d FDV202 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV202 --uprev A --upport terminals -d FEM228 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM228 --uprev A --upport e -d NBP19 --dnrev A --dnport e6 --date 2021/03/08 --time 15:16
add_connection.py -u FEM228 --uprev A --upport n -d NBP19 --dnrev A --dnport n6 --date 2021/03/08 --time 15:16
add_connection.py -u A225 --uprev H --upport focus -d FDV198 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV198 --uprev A --upport terminals -d FEM230 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM230 --uprev A --upport e -d NBP19 --dnrev A --dnport e7 --date 2021/03/08 --time 15:16
add_connection.py -u FEM230 --uprev A --upport n -d NBP19 --dnrev A --dnport n7 --date 2021/03/08 --time 15:16
add_connection.py -u A226 --uprev H --upport focus -d FDV185 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV185 --uprev A --upport terminals -d FEM225 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM225 --uprev A --upport e -d NBP19 --dnrev A --dnport e8 --date 2021/03/08 --time 15:16
add_connection.py -u FEM225 --uprev A --upport n -d NBP19 --dnrev A --dnport n8 --date 2021/03/08 --time 15:16
add_connection.py -u A227 --uprev H --upport focus -d FDV186 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV186 --uprev A --upport terminals -d FEM255 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM255 --uprev A --upport e -d NBP20 --dnrev A --dnport e10 --date 2021/03/08 --time 15:16
add_connection.py -u FEM255 --uprev A --upport n -d NBP20 --dnrev A --dnport n10 --date 2021/03/08 --time 15:16
add_connection.py -u A228 --uprev H --upport focus -d FDV192 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV192 --uprev A --upport terminals -d FEM266 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM266 --uprev A --upport e -d NBP20 --dnrev A --dnport e11 --date 2021/03/08 --time 15:16
add_connection.py -u FEM266 --uprev A --upport n -d NBP20 --dnrev A --dnport n11 --date 2021/03/08 --time 15:16
add_connection.py -u A229 --uprev H --upport focus -d FDV183 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV183 --uprev A --upport terminals -d FEM254 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM254 --uprev A --upport e -d NBP20 --dnrev A --dnport e12 --date 2021/03/08 --time 15:16
add_connection.py -u FEM254 --uprev A --upport n -d NBP20 --dnrev A --dnport n12 --date 2021/03/08 --time 15:16
add_connection.py -u A240 --uprev H --upport focus -d FDV182 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV182 --uprev A --upport terminals -d FEM229 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM229 --uprev A --upport e -d NBP19 --dnrev A --dnport e9 --date 2021/03/08 --time 15:16
add_connection.py -u FEM229 --uprev A --upport n -d NBP19 --dnrev A --dnport n9 --date 2021/03/08 --time 15:16
add_connection.py -u A241 --uprev H --upport focus -d FDV203 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV203 --uprev A --upport terminals -d FEM223 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM223 --uprev A --upport e -d NBP19 --dnrev A --dnport e10 --date 2021/03/08 --time 15:16
add_connection.py -u FEM223 --uprev A --upport n -d NBP19 --dnrev A --dnport n10 --date 2021/03/08 --time 15:16
add_connection.py -u A242 --uprev H --upport focus -d FDV176 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV176 --uprev A --upport terminals -d FEM226 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM226 --uprev A --upport e -d NBP19 --dnrev A --dnport e11 --date 2021/03/08 --time 15:16
add_connection.py -u FEM226 --uprev A --upport n -d NBP19 --dnrev A --dnport n11 --date 2021/03/08 --time 15:16
add_connection.py -u A243 --uprev H --upport focus -d FDV193 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV193 --uprev A --upport terminals -d FEM222 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM222 --uprev A --upport e -d NBP19 --dnrev A --dnport e12 --date 2021/03/08 --time 15:16
add_connection.py -u FEM222 --uprev A --upport n -d NBP19 --dnrev A --dnport n12 --date 2021/03/08 --time 15:16
add_connection.py -u A244 --uprev H --upport focus -d FDV187 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV187 --uprev A --upport terminals -d FEM252 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM252 --uprev A --upport e -d NBP20 --dnrev A --dnport e2 --date 2021/03/08 --time 15:16
add_connection.py -u FEM252 --uprev A --upport n -d NBP20 --dnrev A --dnport n2 --date 2021/03/08 --time 15:16
add_connection.py -u A245 --uprev H --upport focus -d FDV189 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV189 --uprev A --upport terminals -d FEM257 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM257 --uprev A --upport e -d NBP20 --dnrev A --dnport e3 --date 2021/03/08 --time 15:16
add_connection.py -u FEM257 --uprev A --upport n -d NBP20 --dnrev A --dnport n3 --date 2021/03/08 --time 15:16
add_connection.py -u A246 --uprev H --upport focus -d FDV169 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV169 --uprev A --upport terminals -d FEM249 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM249 --uprev A --upport e -d NBP20 --dnrev A --dnport e4 --date 2021/03/08 --time 15:16
add_connection.py -u FEM249 --uprev A --upport n -d NBP20 --dnrev A --dnport n4 --date 2021/03/08 --time 15:16
add_connection.py -u A261 --uprev H --upport focus -d FDV188 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV188 --uprev A --upport terminals -d FEM248 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM248 --uprev A --upport e -d NBP20 --dnrev A --dnport e5 --date 2021/03/08 --time 15:16
add_connection.py -u FEM248 --uprev A --upport n -d NBP20 --dnrev A --dnport n5 --date 2021/03/08 --time 15:16
add_connection.py -u A262 --uprev H --upport focus -d FDV170 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FDV170 --uprev A --upport terminals -d FEM264 --dnrev A --dnport input --date 2021/03/08 --time 15:16
add_connection.py -u FEM264 --uprev A --upport e -d NBP20 --dnrev A --dnport e6 --date 2021/03/08 --time 15:16
add_connection.py -u FEM264 --uprev A --upport n -d NBP20 --dnrev A --dnport n6 --date 2021/03/08 --time 15:16
# Adding missing parts
