#! /bin/bash
source ~/.bashrc
echo "210312_infoupd_1842" >> scripts.log 
update_apriori.py -p HH2 -s RF_maintenance --date 2021/03/12 --time 18:43
add_part_info.py -p HH2 -r A -c 'apriori_antenna status change: dish_ok > RF_maintenance' -l "apa-infoupd" --date 2021/03/12 --time 18:43
