#! /bin/bash
source ~/.bashrc
echo "210311_infoupd_1942" >> scripts.log 
update_apriori.py -p HH18 -s RF_maintenance --date 2021/03/11 --time 19:43
add_part_info.py -p HH18 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2021/03/11 --time 19:43
update_apriori.py -p HH94 -s RF_maintenance --date 2021/03/11 --time 19:43
add_part_info.py -p HH94 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2021/03/11 --time 19:43
update_apriori.py -p HH98 -s digital_maintenance --date 2021/03/11 --time 19:43
add_part_info.py -p HH98 -r A -c 'apriori_antenna status change: digital_ok > digital_maintenance' -l "apa-infoupd" --date 2021/03/11 --time 19:43
update_apriori.py -p HH100 -s RF_maintenance --date 2021/03/11 --time 19:43
add_part_info.py -p HH100 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2021/03/11 --time 19:43
update_apriori.py -p HH119 -s RF_maintenance --date 2021/03/11 --time 19:43
add_part_info.py -p HH119 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2021/03/11 --time 19:43
update_apriori.py -p HH123 -s RF_maintenance --date 2021/03/11 --time 19:43
add_part_info.py -p HH123 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2021/03/11 --time 19:43
update_apriori.py -p HH125 -s RF_maintenance --date 2021/03/11 --time 19:43
add_part_info.py -p HH125 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2021/03/11 --time 19:43
update_apriori.py -p HH143 -s RF_maintenance --date 2021/03/11 --time 19:43
add_part_info.py -p HH143 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2021/03/11 --time 19:43
update_apriori.py -p HH156 -s RF_maintenance --date 2021/03/11 --time 19:43
add_part_info.py -p HH156 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2021/03/11 --time 19:43
update_apriori.py -p HH157 -s RF_maintenance --date 2021/03/11 --time 19:43
add_part_info.py -p HH157 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2021/03/11 --time 19:43
update_apriori.py -p HH158 -s RF_maintenance --date 2021/03/11 --time 19:43
add_part_info.py -p HH158 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2021/03/11 --time 19:43
update_apriori.py -p HH166 -s RF_maintenance --date 2021/03/11 --time 19:43
add_part_info.py -p HH166 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2021/03/11 --time 19:43
update_apriori.py -p HH187 -s RF_maintenance --date 2021/03/11 --time 19:43
add_part_info.py -p HH187 -r A -c 'apriori_antenna status change: digital_ok > RF_maintenance' -l "apa-infoupd" --date 2021/03/11 --time 19:43
add_part_info.py -p HH18 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH18 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:02
add_part_info.py -p HH28 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH28 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "infoupd" --date 2021/03/11 --time 19:42:02
add_part_info.py -p HH30 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH30 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "infoupd" --date 2021/03/11 --time 19:42:02
add_part_info.py -p HH94 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH94 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:02
add_part_info.py -p HH156 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH156 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:02
add_part_info.py -p HH158 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH158 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:02
add_part_info.py -p HH143 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH143 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:02
add_part_info.py -p HH166 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH166 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:02
add_part_info.py -p HH184 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH184 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "infoupd" --date 2021/03/11 --time 19:42:02
add_part_info.py -p HH187 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH187 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:02
add_part_info.py -p HH100 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH100 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:02
add_part_info.py -p HH119 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH119 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:02
add_part_info.py -p HH98 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH98 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:02
add_part_info.py -p HH86 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH86 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "infoupd" --date 2021/03/11 --time 19:42:02
add_part_info.py -p HH123 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH123 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:02
add_part_info.py -p HH125 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:00
add_part_info.py -p HH125 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/660' -l "apa-infoupd" --date 2021/03/11 --time 19:42:02
