#! /bin/bash
source ~/.bashrc
echo "210302_infoupd_1742" >> scripts.log 
update_apriori.py -p HH0 -s RF_maintenance --date 2021/03/02 --time 17:43
add_part_info.py -p HH0 -r A -c 'apriori_antenna status change: digital_maintenance -> RF_maintenance' -l "apa-infoupd" --date 2021/03/02 --time 17:43
update_apriori.py -p HH1 -s RF_maintenance --date 2021/03/02 --time 17:43
add_part_info.py -p HH1 -r A -c 'apriori_antenna status change: digital_maintenance -> RF_maintenance' -l "apa-infoupd" --date 2021/03/02 --time 17:43
update_apriori.py -p HH11 -s RF_maintenance --date 2021/03/02 --time 17:43
add_part_info.py -p HH11 -r A -c 'apriori_antenna status change: digital_maintenance -> RF_maintenance' -l "apa-infoupd" --date 2021/03/02 --time 17:43
update_apriori.py -p HH13 -s RF_maintenance --date 2021/03/02 --time 17:43
add_part_info.py -p HH13 -r A -c 'apriori_antenna status change: digital_maintenance -> RF_maintenance' -l "apa-infoupd" --date 2021/03/02 --time 17:43
update_apriori.py -p HH14 -s RF_maintenance --date 2021/03/02 --time 17:43
add_part_info.py -p HH14 -r A -c 'apriori_antenna status change: digital_maintenance -> RF_maintenance' -l "apa-infoupd" --date 2021/03/02 --time 17:43
update_apriori.py -p HH25 -s RF_maintenance --date 2021/03/02 --time 17:43
add_part_info.py -p HH25 -r A -c 'apriori_antenna status change: digital_maintenance -> RF_maintenance' -l "apa-infoupd" --date 2021/03/02 --time 17:43
update_apriori.py -p HH26 -s RF_maintenance --date 2021/03/02 --time 17:43
add_part_info.py -p HH26 -r A -c 'apriori_antenna status change: digital_maintenance -> RF_maintenance' -l "apa-infoupd" --date 2021/03/02 --time 17:43
update_apriori.py -p HH39 -s RF_maintenance --date 2021/03/02 --time 17:43
add_part_info.py -p HH39 -r A -c 'apriori_antenna status change: digital_maintenance -> RF_maintenance' -l "apa-infoupd" --date 2021/03/02 --time 17:43
add_part_info.py -p HH0 -r A -c 'PAM not turning on.' -l "apa-infoupd" --date 2021/03/02 --time 17:42:00
add_part_info.py -p HH2 -r A -c 'PAM not turning on.' -l "infoupd" --date 2021/03/02 --time 17:42:00
add_part_info.py -p HH1 -r A -c 'PAM not turning on.' -l "apa-infoupd" --date 2021/03/02 --time 17:42:00
add_part_info.py -p HH11 -r A -c 'PAM not turning on.' -l "apa-infoupd" --date 2021/03/02 --time 17:42:00
add_part_info.py -p HH12 -r A -c 'PAM not turning on.' -l "infoupd" --date 2021/03/02 --time 17:42:00
add_part_info.py -p HH13 -r A -c 'PAM not turning on.' -l "apa-infoupd" --date 2021/03/02 --time 17:42:00
add_part_info.py -p HH14 -r A -c 'PAM not turning on.' -l "apa-infoupd" --date 2021/03/02 --time 17:42:00
add_part_info.py -p HH23 -r A -c 'PAM not turning on.' -l "infoupd" --date 2021/03/02 --time 17:42:00
add_part_info.py -p HH24 -r A -c 'PAM not turning on.' -l "infoupd" --date 2021/03/02 --time 17:42:00
add_part_info.py -p HH25 -r A -c 'PAM not turning on.' -l "apa-infoupd" --date 2021/03/02 --time 17:42:00
add_part_info.py -p HH26 -r A -c 'PAM not turning on.' -l "apa-infoupd" --date 2021/03/02 --time 17:42:00
add_part_info.py -p HH39 -r A -c 'PAM not turning on.' -l "apa-infoupd" --date 2021/03/02 --time 17:42:00
