#! /bin/bash
source ~/.bashrc
echo "210312_infoupd_1742" >> scripts.log 
update_apriori.py -p HH2 -s dish_ok --date 2021/03/12 --time 17:43
add_part_info.py -p HH2 -r A -c 'apriori_antenna status change: RF_maintenance > dish_ok' -l "apa-infoupd" --date 2021/03/12 --time 17:43
add_part_info.py -p HH0 -r A -c 'Test warning' -l "apa-infoupd" --date 2021/03/12 --time 17:42:00
add_part_info.py -p HH2 -r A -c 'Test apriori change' -l "apa-infoupd" --date 2021/03/12 --time 17:42:00
