#! /bin/bash
source ~/.bashrc
echo "210311_infoupd_1742" >> scripts.log 
update_apriori.py -p HH15 -s digital_ok --date 2021/03/11 --time 17:43
add_part_info.py -p HH15 -r A -c 'apriori_antenna status change: RF_maintenance -> digital_ok' -l "apa-infoupd" --date 2021/03/11 --time 17:43
update_apriori.py -p HH81 -s digital_ok --date 2021/03/11 --time 17:43
add_part_info.py -p HH81 -r A -c 'apriori_antenna status change: RF_maintenance -> digital_ok' -l "apa-infoupd" --date 2021/03/11 --time 17:43
update_apriori.py -p HH138 -s digital_ok --date 2021/03/11 --time 17:43
add_part_info.py -p HH138 -r A -c 'apriori_antenna status change: RF_maintenance -> digital_ok' -l "apa-infoupd" --date 2021/03/11 --time 17:43
add_part_info.py -p HH15 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/659' -l "apa-infoupd" --date 2021/03/11 --time 17:42:00
add_part_info.py -p HH15 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/659' -l "apa-infoupd" --date 2021/03/11 --time 17:42:02
add_part_info.py -p HH81 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/659' -l "apa-infoupd" --date 2021/03/11 --time 17:42:00
add_part_info.py -p HH81 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/659' -l "apa-infoupd" --date 2021/03/11 --time 17:42:02
add_part_info.py -p HH138 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/659' -l "apa-infoupd" --date 2021/03/11 --time 17:42:00
add_part_info.py -p HH138 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/659' -l "apa-infoupd" --date 2021/03/11 --time 17:42:02
