#! /bin/bash
echo "./210308_readd_nodes_210225.py" >> scripts.log 
add_station.py ND18 --sernum ND18 --date 2021/02/25 --time 10:00
add_part.py -p FPS20 -r A -t fem-power-supply -m FPS20 --date 2021/02/25 --time 10:00
add_part.py -p PCH15 -r A -t pam-chassis -m PCH15 --date 2021/02/25 --time 10:00
add_part.py -p NBP18 -r A -t node-bulkhead -m NBP18 --date 2021/02/25 --time 10:00
add_part.py -p PAM233 -r A -t post-amp -m 233 --date 2021/02/25 --time 10:00
add_part.py -p PAM234 -r A -t post-amp -m 234 --date 2021/02/25 --time 10:00
add_part.py -p PAM235 -r A -t post-amp -m 235 --date 2021/02/25 --time 10:00
add_part.py -p PAM236 -r A -t post-amp -m 236 --date 2021/02/25 --time 10:00
add_part.py -p PAM237 -r A -t post-amp -m 237 --date 2021/02/25 --time 10:00
add_part.py -p PAM238 -r A -t post-amp -m 238 --date 2021/02/25 --time 10:00
add_part.py -p PAM239 -r A -t post-amp -m 239 --date 2021/02/25 --time 10:00
add_part.py -p PAM240 -r A -t post-amp -m 240 --date 2021/02/25 --time 10:00
add_part.py -p PAM241 -r A -t post-amp -m 241 --date 2021/02/25 --time 10:00
add_part.py -p PAM242 -r A -t post-amp -m 242 --date 2021/02/25 --time 10:00
add_part.py -p PAM243 -r A -t post-amp -m 243 --date 2021/02/25 --time 10:00
add_part.py -p PAM244 -r A -t post-amp -m 244 --date 2021/02/25 --time 10:00
add_part.py -p SNPA000022 -r A -t snap -m A00022 --date 2021/02/25 --time 10:00
add_part.py -p SNPC000065 -r A -t snap -m 65 --date 2021/02/25 --time 10:00
add_part.py -p SNPC000083 -r A -t snap -m 83 --date 2021/02/25 --time 10:00
add_part.py -p SNPC000068 -r A -t snap -m 68 --date 2021/02/25 --time 10:00
add_connection.py -u N18 --uprev A --upport ground -d ND18 --dnrev A --dnport ground --date 2021/02/25 --time 10:00
add_connection.py -u FPS20 --uprev A --upport rack -d N18 --dnrev A --dnport top --date 2021/02/25 --time 10:00
add_connection.py -u PCH15 --uprev A --upport rack -d N18 --dnrev A --dnport bottom --date 2021/02/25 --time 10:00
add_connection.py -u NCM12 --uprev A --upport rack -d N18 --dnrev A --dnport middle --date 2021/02/25 --time 10:00
add_connection.py -u PAM233 --uprev A --upport slot -d PCH15 --dnrev A --dnport slot1 --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport e1 -d PAM233 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport n1 -d PAM233 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM234 --uprev A --upport slot -d PCH15 --dnrev A --dnport slot2 --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport e2 -d PAM234 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport n2 -d PAM234 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM235 --uprev A --upport slot -d PCH15 --dnrev A --dnport slot3 --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport e3 -d PAM235 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport n3 -d PAM235 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM236 --uprev A --upport slot -d PCH15 --dnrev A --dnport slot4 --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport e4 -d PAM236 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport n4 -d PAM236 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM237 --uprev A --upport slot -d PCH15 --dnrev A --dnport slot5 --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport e5 -d PAM237 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport n5 -d PAM237 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM238 --uprev A --upport slot -d PCH15 --dnrev A --dnport slot6 --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport e6 -d PAM238 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport n6 -d PAM238 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM239 --uprev A --upport slot -d PCH15 --dnrev A --dnport slot7 --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport e7 -d PAM239 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport n7 -d PAM239 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM240 --uprev A --upport slot -d PCH15 --dnrev A --dnport slot8 --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport e8 -d PAM240 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport n8 -d PAM240 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM241 --uprev A --upport slot -d PCH15 --dnrev A --dnport slot9 --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport e9 -d PAM241 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport n9 -d PAM241 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM242 --uprev A --upport slot -d PCH15 --dnrev A --dnport slot10 --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport e10 -d PAM242 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport n10 -d PAM242 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM243 --uprev A --upport slot -d PCH15 --dnrev A --dnport slot11 --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport e11 -d PAM243 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport n11 -d PAM243 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM244 --uprev A --upport slot -d PCH15 --dnrev A --dnport slot12 --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport e12 -d PAM244 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP18 --uprev A --upport n12 -d PAM244 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u SNPA000022 --uprev A --upport rack -d N18 --dnrev A --dnport loc0 --date 2021/02/25 --time 10:00
add_connection.py -u PAM233 --uprev A --upport e -d SNPA000022 --dnrev A --dnport e2 --date 2021/02/25 --time 10:00
add_connection.py -u PAM234 --uprev A --upport e -d SNPA000022 --dnrev A --dnport e6 --date 2021/02/25 --time 10:00
add_connection.py -u PAM235 --uprev A --upport e -d SNPA000022 --dnrev A --dnport e10 --date 2021/02/25 --time 10:00
add_connection.py -u PAM233 --uprev A --upport n -d SNPA000022 --dnrev A --dnport n0 --date 2021/02/25 --time 10:00
add_connection.py -u PAM234 --uprev A --upport n -d SNPA000022 --dnrev A --dnport n4 --date 2021/02/25 --time 10:00
add_connection.py -u PAM235 --uprev A --upport n -d SNPA000022 --dnrev A --dnport n8 --date 2021/02/25 --time 10:00
add_connection.py -u SNPC000065 --uprev A --upport rack -d N18 --dnrev A --dnport loc1 --date 2021/02/25 --time 10:00
add_connection.py -u PAM236 --uprev A --upport e -d SNPC000065 --dnrev A --dnport e2 --date 2021/02/25 --time 10:00
add_connection.py -u PAM237 --uprev A --upport e -d SNPC000065 --dnrev A --dnport e6 --date 2021/02/25 --time 10:00
add_connection.py -u PAM238 --uprev A --upport e -d SNPC000065 --dnrev A --dnport e10 --date 2021/02/25 --time 10:00
add_connection.py -u PAM236 --uprev A --upport n -d SNPC000065 --dnrev A --dnport n0 --date 2021/02/25 --time 10:00
add_connection.py -u PAM237 --uprev A --upport n -d SNPC000065 --dnrev A --dnport n4 --date 2021/02/25 --time 10:00
add_connection.py -u PAM238 --uprev A --upport n -d SNPC000065 --dnrev A --dnport n8 --date 2021/02/25 --time 10:00
add_connection.py -u SNPC000083 --uprev A --upport rack -d N18 --dnrev A --dnport loc2 --date 2021/02/25 --time 10:00
add_connection.py -u PAM239 --uprev A --upport e -d SNPC000083 --dnrev A --dnport e2 --date 2021/02/25 --time 10:00
add_connection.py -u PAM240 --uprev A --upport e -d SNPC000083 --dnrev A --dnport e6 --date 2021/02/25 --time 10:00
add_connection.py -u PAM241 --uprev A --upport e -d SNPC000083 --dnrev A --dnport e10 --date 2021/02/25 --time 10:00
add_connection.py -u PAM239 --uprev A --upport n -d SNPC000083 --dnrev A --dnport n0 --date 2021/02/25 --time 10:00
add_connection.py -u PAM240 --uprev A --upport n -d SNPC000083 --dnrev A --dnport n4 --date 2021/02/25 --time 10:00
add_connection.py -u PAM241 --uprev A --upport n -d SNPC000083 --dnrev A --dnport n8 --date 2021/02/25 --time 10:00
add_connection.py -u SNPC000068 --uprev A --upport rack -d N18 --dnrev A --dnport loc3 --date 2021/02/25 --time 10:00
add_connection.py -u PAM242 --uprev A --upport e -d SNPC000068 --dnrev A --dnport e2 --date 2021/02/25 --time 10:00
add_connection.py -u PAM243 --uprev A --upport e -d SNPC000068 --dnrev A --dnport e6 --date 2021/02/25 --time 10:00
add_connection.py -u PAM244 --uprev A --upport e -d SNPC000068 --dnrev A --dnport e10 --date 2021/02/25 --time 10:00
add_connection.py -u PAM242 --uprev A --upport n -d SNPC000068 --dnrev A --dnport n0 --date 2021/02/25 --time 10:00
add_connection.py -u PAM243 --uprev A --upport n -d SNPC000068 --dnrev A --dnport n4 --date 2021/02/25 --time 10:00
add_connection.py -u PAM244 --uprev A --upport n -d SNPC000068 --dnrev A --dnport n8 --date 2021/02/25 --time 10:00
add_station.py ND19 --sernum ND19 --date 2021/02/25 --time 10:00
add_part.py -p FPS17 -r A -t fem-power-supply -m FPS17 --date 2021/02/25 --time 10:00
add_part.py -p PCH16 -r A -t pam-chassis -m PCH16 --date 2021/02/25 --time 10:00
add_part.py -p NBP19 -r A -t node-bulkhead -m NBP19 --date 2021/02/25 --time 10:00
add_part.py -p PAM221 -r A -t post-amp -m 221 --date 2021/02/25 --time 10:00
add_part.py -p PAM222 -r A -t post-amp -m 222 --date 2021/02/25 --time 10:00
add_part.py -p PAM223 -r A -t post-amp -m 223 --date 2021/02/25 --time 10:00
add_part.py -p PAM224 -r A -t post-amp -m 224 --date 2021/02/25 --time 10:00
add_part.py -p PAM225 -r A -t post-amp -m 225 --date 2021/02/25 --time 10:00
add_part.py -p PAM226 -r A -t post-amp -m 226 --date 2021/02/25 --time 10:00
add_part.py -p PAM227 -r A -t post-amp -m 227 --date 2021/02/25 --time 10:00
add_part.py -p PAM228 -r A -t post-amp -m 228 --date 2021/02/25 --time 10:00
add_part.py -p PAM229 -r A -t post-amp -m 229 --date 2021/02/25 --time 10:00
add_part.py -p PAM230 -r A -t post-amp -m 230 --date 2021/02/25 --time 10:00
add_part.py -p PAM231 -r A -t post-amp -m 231 --date 2021/02/25 --time 10:00
add_part.py -p PAM232 -r A -t post-amp -m 232 --date 2021/02/25 --time 10:00
add_part.py -p SNPC000078 -r A -t snap -m 78 --date 2021/02/25 --time 10:00
add_part.py -p SNPC000008 -r A -t snap -m 8 --date 2021/02/25 --time 10:00
add_part.py -p SNPC000061 -r A -t snap -m 61 --date 2021/02/25 --time 10:00
add_part.py -p SNPC000025 -r A -t snap -m 25 --date 2021/02/25 --time 10:00
add_connection.py -u N19 --uprev A --upport ground -d ND19 --dnrev A --dnport ground --date 2021/02/25 --time 10:00
add_connection.py -u FPS17 --uprev A --upport rack -d N19 --dnrev A --dnport top --date 2021/02/25 --time 10:00
add_connection.py -u PCH16 --uprev A --upport rack -d N19 --dnrev A --dnport bottom --date 2021/02/25 --time 10:00
add_connection.py -u NCM18 --uprev A --upport rack -d N19 --dnrev A --dnport middle --date 2021/02/25 --time 10:00
add_connection.py -u PAM221 --uprev A --upport slot -d PCH16 --dnrev A --dnport slot1 --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport e1 -d PAM221 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport n1 -d PAM221 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM222 --uprev A --upport slot -d PCH16 --dnrev A --dnport slot2 --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport e2 -d PAM222 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport n2 -d PAM222 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM223 --uprev A --upport slot -d PCH16 --dnrev A --dnport slot3 --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport e3 -d PAM223 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport n3 -d PAM223 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM224 --uprev A --upport slot -d PCH16 --dnrev A --dnport slot4 --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport e4 -d PAM224 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport n4 -d PAM224 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM225 --uprev A --upport slot -d PCH16 --dnrev A --dnport slot5 --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport e5 -d PAM225 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport n5 -d PAM225 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM226 --uprev A --upport slot -d PCH16 --dnrev A --dnport slot6 --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport e6 -d PAM226 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport n6 -d PAM226 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM227 --uprev A --upport slot -d PCH16 --dnrev A --dnport slot7 --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport e7 -d PAM227 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport n7 -d PAM227 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM228 --uprev A --upport slot -d PCH16 --dnrev A --dnport slot8 --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport e8 -d PAM228 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport n8 -d PAM228 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM229 --uprev A --upport slot -d PCH16 --dnrev A --dnport slot9 --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport e9 -d PAM229 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport n9 -d PAM229 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM230 --uprev A --upport slot -d PCH16 --dnrev A --dnport slot10 --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport e10 -d PAM230 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport n10 -d PAM230 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM231 --uprev A --upport slot -d PCH16 --dnrev A --dnport slot11 --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport e11 -d PAM231 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport n11 -d PAM231 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM232 --uprev A --upport slot -d PCH16 --dnrev A --dnport slot12 --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport e12 -d PAM232 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP19 --uprev A --upport n12 -d PAM232 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u SNPC000078 --uprev A --upport rack -d N19 --dnrev A --dnport loc0 --date 2021/02/25 --time 10:00
add_connection.py -u PAM221 --uprev A --upport e -d SNPC000078 --dnrev A --dnport e2 --date 2021/02/25 --time 10:00
add_connection.py -u PAM222 --uprev A --upport e -d SNPC000078 --dnrev A --dnport e6 --date 2021/02/25 --time 10:00
add_connection.py -u PAM223 --uprev A --upport e -d SNPC000078 --dnrev A --dnport e10 --date 2021/02/25 --time 10:00
add_connection.py -u PAM221 --uprev A --upport n -d SNPC000078 --dnrev A --dnport n0 --date 2021/02/25 --time 10:00
add_connection.py -u PAM222 --uprev A --upport n -d SNPC000078 --dnrev A --dnport n4 --date 2021/02/25 --time 10:00
add_connection.py -u PAM223 --uprev A --upport n -d SNPC000078 --dnrev A --dnport n8 --date 2021/02/25 --time 10:00
add_connection.py -u SNPC000008 --uprev A --upport rack -d N19 --dnrev A --dnport loc1 --date 2021/02/25 --time 10:00
add_connection.py -u PAM224 --uprev A --upport e -d SNPC000008 --dnrev A --dnport e2 --date 2021/02/25 --time 10:00
add_connection.py -u PAM225 --uprev A --upport e -d SNPC000008 --dnrev A --dnport e6 --date 2021/02/25 --time 10:00
add_connection.py -u PAM226 --uprev A --upport e -d SNPC000008 --dnrev A --dnport e10 --date 2021/02/25 --time 10:00
add_connection.py -u PAM224 --uprev A --upport n -d SNPC000008 --dnrev A --dnport n0 --date 2021/02/25 --time 10:00
add_connection.py -u PAM225 --uprev A --upport n -d SNPC000008 --dnrev A --dnport n4 --date 2021/02/25 --time 10:00
add_connection.py -u PAM226 --uprev A --upport n -d SNPC000008 --dnrev A --dnport n8 --date 2021/02/25 --time 10:00
add_connection.py -u SNPC000061 --uprev A --upport rack -d N19 --dnrev A --dnport loc2 --date 2021/02/25 --time 10:00
add_connection.py -u PAM227 --uprev A --upport e -d SNPC000061 --dnrev A --dnport e2 --date 2021/02/25 --time 10:00
add_connection.py -u PAM228 --uprev A --upport e -d SNPC000061 --dnrev A --dnport e6 --date 2021/02/25 --time 10:00
add_connection.py -u PAM229 --uprev A --upport e -d SNPC000061 --dnrev A --dnport e10 --date 2021/02/25 --time 10:00
add_connection.py -u PAM227 --uprev A --upport n -d SNPC000061 --dnrev A --dnport n0 --date 2021/02/25 --time 10:00
add_connection.py -u PAM228 --uprev A --upport n -d SNPC000061 --dnrev A --dnport n4 --date 2021/02/25 --time 10:00
add_connection.py -u PAM229 --uprev A --upport n -d SNPC000061 --dnrev A --dnport n8 --date 2021/02/25 --time 10:00
add_connection.py -u SNPC000025 --uprev A --upport rack -d N19 --dnrev A --dnport loc3 --date 2021/02/25 --time 10:00
add_connection.py -u PAM230 --uprev A --upport e -d SNPC000025 --dnrev A --dnport e2 --date 2021/02/25 --time 10:00
add_connection.py -u PAM231 --uprev A --upport e -d SNPC000025 --dnrev A --dnport e6 --date 2021/02/25 --time 10:00
add_connection.py -u PAM232 --uprev A --upport e -d SNPC000025 --dnrev A --dnport e10 --date 2021/02/25 --time 10:00
add_connection.py -u PAM230 --uprev A --upport n -d SNPC000025 --dnrev A --dnport n0 --date 2021/02/25 --time 10:00
add_connection.py -u PAM231 --uprev A --upport n -d SNPC000025 --dnrev A --dnport n4 --date 2021/02/25 --time 10:00
add_connection.py -u PAM232 --uprev A --upport n -d SNPC000025 --dnrev A --dnport n8 --date 2021/02/25 --time 10:00
add_station.py ND20 --sernum ND20 --date 2021/02/25 --time 10:00
add_part.py -p FPS19 -r A -t fem-power-supply -m FPS19 --date 2021/02/25 --time 10:00
add_part.py -p PCH17 -r A -t pam-chassis -m PCH17 --date 2021/02/25 --time 10:00
add_part.py -p NBP20 -r A -t node-bulkhead -m NBP20 --date 2021/02/25 --time 10:00
add_part.py -p PAM257 -r A -t post-amp -m 257 --date 2021/02/25 --time 10:00
add_part.py -p PAM258 -r A -t post-amp -m 258 --date 2021/02/25 --time 10:00
add_part.py -p PAM259 -r A -t post-amp -m 259 --date 2021/02/25 --time 10:00
add_part.py -p PAM260 -r A -t post-amp -m 260 --date 2021/02/25 --time 10:00
add_part.py -p PAM261 -r A -t post-amp -m 261 --date 2021/02/25 --time 10:00
add_part.py -p PAM262 -r A -t post-amp -m 262 --date 2021/02/25 --time 10:00
add_part.py -p PAM263 -r A -t post-amp -m 263 --date 2021/02/25 --time 10:00
add_part.py -p PAM264 -r A -t post-amp -m 264 --date 2021/02/25 --time 10:00
add_part.py -p PAM265 -r A -t post-amp -m 265 --date 2021/02/25 --time 10:00
add_part.py -p PAM266 -r A -t post-amp -m 266 --date 2021/02/25 --time 10:00
add_part.py -p PAM267 -r A -t post-amp -m 267 --date 2021/02/25 --time 10:00
add_part.py -p PAM268 -r A -t post-amp -m 268 --date 2021/02/25 --time 10:00
add_part.py -p SNPC000070 -r A -t snap -m 70 --date 2021/02/25 --time 10:00
add_part.py -p SNPC000082 -r A -t snap -m 82 --date 2021/02/25 --time 10:00
add_part.py -p SNPC000085 -r A -t snap -m 85 --date 2021/02/25 --time 10:00
add_part.py -p SNPC000086 -r A -t snap -m 86 --date 2021/02/25 --time 10:00
add_connection.py -u N20 --uprev A --upport ground -d ND20 --dnrev A --dnport ground --date 2021/02/25 --time 10:00
add_connection.py -u FPS19 --uprev A --upport rack -d N20 --dnrev A --dnport top --date 2021/02/25 --time 10:00
add_connection.py -u PCH17 --uprev A --upport rack -d N20 --dnrev A --dnport bottom --date 2021/02/25 --time 10:00
add_connection.py -u NCM15 --uprev A --upport rack -d N20 --dnrev A --dnport middle --date 2021/02/25 --time 10:00
add_connection.py -u PAM257 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot1 --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport e1 -d PAM257 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport n1 -d PAM257 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM258 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot2 --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport e2 -d PAM258 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport n2 -d PAM258 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM259 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot3 --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport e3 -d PAM259 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport n3 -d PAM259 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM260 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot4 --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport e4 -d PAM260 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport n4 -d PAM260 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM261 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot5 --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport e5 -d PAM261 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport n5 -d PAM261 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM262 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot6 --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport e6 -d PAM262 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport n6 -d PAM262 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM263 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot7 --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport e7 -d PAM263 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport n7 -d PAM263 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM264 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot8 --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport e8 -d PAM264 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport n8 -d PAM264 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM265 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot9 --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport e9 -d PAM265 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport n9 -d PAM265 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM266 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot10 --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport e10 -d PAM266 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport n10 -d PAM266 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM267 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot11 --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport e11 -d PAM267 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport n11 -d PAM267 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u PAM268 --uprev A --upport slot -d PCH17 --dnrev A --dnport slot12 --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport e12 -d PAM268 --dnrev A --dnport e --date 2021/02/25 --time 10:00
add_connection.py -u NBP20 --uprev A --upport n12 -d PAM268 --dnrev A --dnport n --date 2021/02/25 --time 10:00
add_connection.py -u SNPC000070 --uprev A --upport rack -d N20 --dnrev A --dnport loc0 --date 2021/02/25 --time 10:00
add_connection.py -u PAM257 --uprev A --upport e -d SNPC000070 --dnrev A --dnport e2 --date 2021/02/25 --time 10:00
add_connection.py -u PAM258 --uprev A --upport e -d SNPC000070 --dnrev A --dnport e6 --date 2021/02/25 --time 10:00
add_connection.py -u PAM259 --uprev A --upport e -d SNPC000070 --dnrev A --dnport e10 --date 2021/02/25 --time 10:00
add_connection.py -u PAM257 --uprev A --upport n -d SNPC000070 --dnrev A --dnport n0 --date 2021/02/25 --time 10:00
add_connection.py -u PAM258 --uprev A --upport n -d SNPC000070 --dnrev A --dnport n4 --date 2021/02/25 --time 10:00
add_connection.py -u PAM259 --uprev A --upport n -d SNPC000070 --dnrev A --dnport n8 --date 2021/02/25 --time 10:00
add_connection.py -u SNPC000082 --uprev A --upport rack -d N20 --dnrev A --dnport loc1 --date 2021/02/25 --time 10:00
add_connection.py -u PAM260 --uprev A --upport e -d SNPC000082 --dnrev A --dnport e2 --date 2021/02/25 --time 10:00
add_connection.py -u PAM261 --uprev A --upport e -d SNPC000082 --dnrev A --dnport e6 --date 2021/02/25 --time 10:00
add_connection.py -u PAM262 --uprev A --upport e -d SNPC000082 --dnrev A --dnport e10 --date 2021/02/25 --time 10:00
add_connection.py -u PAM260 --uprev A --upport n -d SNPC000082 --dnrev A --dnport n0 --date 2021/02/25 --time 10:00
add_connection.py -u PAM261 --uprev A --upport n -d SNPC000082 --dnrev A --dnport n4 --date 2021/02/25 --time 10:00
add_connection.py -u PAM262 --uprev A --upport n -d SNPC000082 --dnrev A --dnport n8 --date 2021/02/25 --time 10:00
add_connection.py -u SNPC000085 --uprev A --upport rack -d N20 --dnrev A --dnport loc2 --date 2021/02/25 --time 10:00
add_connection.py -u PAM263 --uprev A --upport e -d SNPC000085 --dnrev A --dnport e2 --date 2021/02/25 --time 10:00
add_connection.py -u PAM264 --uprev A --upport e -d SNPC000085 --dnrev A --dnport e6 --date 2021/02/25 --time 10:00
add_connection.py -u PAM265 --uprev A --upport e -d SNPC000085 --dnrev A --dnport e10 --date 2021/02/25 --time 10:00
add_connection.py -u PAM263 --uprev A --upport n -d SNPC000085 --dnrev A --dnport n0 --date 2021/02/25 --time 10:00
add_connection.py -u PAM264 --uprev A --upport n -d SNPC000085 --dnrev A --dnport n4 --date 2021/02/25 --time 10:00
add_connection.py -u PAM265 --uprev A --upport n -d SNPC000085 --dnrev A --dnport n8 --date 2021/02/25 --time 10:00
add_connection.py -u SNPC000086 --uprev A --upport rack -d N20 --dnrev A --dnport loc3 --date 2021/02/25 --time 10:00
add_connection.py -u PAM266 --uprev A --upport e -d SNPC000086 --dnrev A --dnport e2 --date 2021/02/25 --time 10:00
add_connection.py -u PAM267 --uprev A --upport e -d SNPC000086 --dnrev A --dnport e6 --date 2021/02/25 --time 10:00
add_connection.py -u PAM268 --uprev A --upport e -d SNPC000086 --dnrev A --dnport e10 --date 2021/02/25 --time 10:00
add_connection.py -u PAM266 --uprev A --upport n -d SNPC000086 --dnrev A --dnport n0 --date 2021/02/25 --time 10:00
add_connection.py -u PAM267 --uprev A --upport n -d SNPC000086 --dnrev A --dnport n4 --date 2021/02/25 --time 10:00
add_connection.py -u PAM268 --uprev A --upport n -d SNPC000086 --dnrev A --dnport n8 --date 2021/02/25 --time 10:00
