#! /bin/bash
source ~/.bashrc
echo "210314_infoupd_2042" >> scripts.log 
add_part_info.py -p HH99 -r A -c 'FEM turned back on 15 Sept 2020' -l "infoupd" --date 2021/03/14 --time 20:42:00
add_part_info.py -p HH99 -r A -c 'FEM turned back on 15 Sept 2020' -l "infoupd" --date 2021/03/14 --time 20:42:02
add_part_info.py -p HH117 -r A -c 'FEM turned back on 15 Sept 2020' -l "infoupd" --date 2021/03/14 --time 20:42:00
add_part_info.py -p HH117 -r A -c 'FEM turned back on 15 Sept 2020' -l "infoupd" --date 2021/03/14 --time 20:42:02
add_part_info.py -p HH118 -r A -c 'FEM turned back on 15 Sept 2020' -l "infoupd" --date 2021/03/14 --time 20:42:00
add_part_info.py -p HH118 -r A -c 'FEM turned back on 15 Sept 2020' -l "infoupd" --date 2021/03/14 --time 20:42:02
