#! /bin/bash
echo "./210716_add_nodes.py" >> scripts.log 
add_station.py ND06 --sernum ND06 --date 2021/07/01 --time 10:00
add_part.py -p FPS21 -r A -t fem-power-supply -m FPS21 --date 2021/07/01 --time 10:00
add_part.py -p PCH18 -r A -t pam-chassis -m PCH18 --date 2021/07/01 --time 10:00
add_part.py -p NBP06 -r A -t node-bulkhead -m NBP06 --date 2021/07/01 --time 10:00
add_part.py -p PAM269 -r A -t post-amp -m 269 --date 2021/07/01 --time 10:00
add_part.py -p PAM270 -r A -t post-amp -m 270 --date 2021/07/01 --time 10:00
add_part.py -p PAM271 -r A -t post-amp -m 271 --date 2021/07/01 --time 10:00
add_part.py -p PAM272 -r A -t post-amp -m 272 --date 2021/07/01 --time 10:00
add_part.py -p PAM273 -r A -t post-amp -m 273 --date 2021/07/01 --time 10:00
add_part.py -p PAM274 -r A -t post-amp -m 274 --date 2021/07/01 --time 10:00
add_part.py -p PAM275 -r A -t post-amp -m 275 --date 2021/07/01 --time 10:00
add_part.py -p PAM276 -r A -t post-amp -m 276 --date 2021/07/01 --time 10:00
add_part.py -p PAM277 -r A -t post-amp -m 277 --date 2021/07/01 --time 10:00
add_part.py -p PAM278 -r A -t post-amp -m 278 --date 2021/07/01 --time 10:00
add_part.py -p PAM279 -r A -t post-amp -m 279 --date 2021/07/01 --time 10:00
add_part.py -p PAM280 -r A -t post-amp -m 280 --date 2021/07/01 --time 10:00
add_connection.py -u N06 --uprev A --upport ground -d ND06 --dnrev A --dnport ground --date 2021/07/01 --time 10:00
add_connection.py -u FPS21 --uprev A --upport rack -d N06 --dnrev A --dnport top --date 2021/07/01 --time 10:00
add_connection.py -u PCH18 --uprev A --upport rack -d N06 --dnrev A --dnport bottom --date 2021/07/01 --time 10:00
add_connection.py -u NCM16 --uprev A --upport rack -d N06 --dnrev A --dnport middle --date 2021/07/01 --time 10:00
add_connection.py -u PAM269 --uprev A --upport slot -d PCH18 --dnrev A --dnport slot1 --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport e1 -d PAM269 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport n1 -d PAM269 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM270 --uprev A --upport slot -d PCH18 --dnrev A --dnport slot2 --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport e2 -d PAM270 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport n2 -d PAM270 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM271 --uprev A --upport slot -d PCH18 --dnrev A --dnport slot3 --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport e3 -d PAM271 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport n3 -d PAM271 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM272 --uprev A --upport slot -d PCH18 --dnrev A --dnport slot4 --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport e4 -d PAM272 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport n4 -d PAM272 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM273 --uprev A --upport slot -d PCH18 --dnrev A --dnport slot5 --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport e5 -d PAM273 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport n5 -d PAM273 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM274 --uprev A --upport slot -d PCH18 --dnrev A --dnport slot6 --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport e6 -d PAM274 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport n6 -d PAM274 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM275 --uprev A --upport slot -d PCH18 --dnrev A --dnport slot7 --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport e7 -d PAM275 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport n7 -d PAM275 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM276 --uprev A --upport slot -d PCH18 --dnrev A --dnport slot8 --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport e8 -d PAM276 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport n8 -d PAM276 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM277 --uprev A --upport slot -d PCH18 --dnrev A --dnport slot9 --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport e9 -d PAM277 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport n9 -d PAM277 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM278 --uprev A --upport slot -d PCH18 --dnrev A --dnport slot10 --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport e10 -d PAM278 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport n10 -d PAM278 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM279 --uprev A --upport slot -d PCH18 --dnrev A --dnport slot11 --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport e11 -d PAM279 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport n11 -d PAM279 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM280 --uprev A --upport slot -d PCH18 --dnrev A --dnport slot12 --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport e12 -d PAM280 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP06 --uprev A --upport n12 -d PAM280 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u SNPC000095 --uprev A --upport rack -d N06 --dnrev A --dnport loc0 --date 2021/07/01 --time 10:00
add_connection.py -u PAM269 --uprev A --upport e -d SNPC000095 --dnrev A --dnport e2 --date 2021/07/01 --time 10:00
add_connection.py -u PAM270 --uprev A --upport e -d SNPC000095 --dnrev A --dnport e6 --date 2021/07/01 --time 10:00
add_connection.py -u PAM271 --uprev A --upport e -d SNPC000095 --dnrev A --dnport e10 --date 2021/07/01 --time 10:00
add_connection.py -u PAM269 --uprev A --upport n -d SNPC000095 --dnrev A --dnport n0 --date 2021/07/01 --time 10:00
add_connection.py -u PAM270 --uprev A --upport n -d SNPC000095 --dnrev A --dnport n4 --date 2021/07/01 --time 10:00
add_connection.py -u PAM271 --uprev A --upport n -d SNPC000095 --dnrev A --dnport n8 --date 2021/07/01 --time 10:00
add_connection.py -u SNPC000036 --uprev A --upport rack -d N06 --dnrev A --dnport loc1 --date 2021/07/01 --time 10:00
add_connection.py -u PAM272 --uprev A --upport e -d SNPC000036 --dnrev A --dnport e2 --date 2021/07/01 --time 10:00
add_connection.py -u PAM273 --uprev A --upport e -d SNPC000036 --dnrev A --dnport e6 --date 2021/07/01 --time 10:00
add_connection.py -u PAM274 --uprev A --upport e -d SNPC000036 --dnrev A --dnport e10 --date 2021/07/01 --time 10:00
add_connection.py -u PAM272 --uprev A --upport n -d SNPC000036 --dnrev A --dnport n0 --date 2021/07/01 --time 10:00
add_connection.py -u PAM273 --uprev A --upport n -d SNPC000036 --dnrev A --dnport n4 --date 2021/07/01 --time 10:00
add_connection.py -u PAM274 --uprev A --upport n -d SNPC000036 --dnrev A --dnport n8 --date 2021/07/01 --time 10:00
add_connection.py -u SNPC000084 --uprev A --upport rack -d N06 --dnrev A --dnport loc2 --date 2021/07/01 --time 10:00
add_connection.py -u PAM275 --uprev A --upport e -d SNPC000084 --dnrev A --dnport e2 --date 2021/07/01 --time 10:00
add_connection.py -u PAM276 --uprev A --upport e -d SNPC000084 --dnrev A --dnport e6 --date 2021/07/01 --time 10:00
add_connection.py -u PAM277 --uprev A --upport e -d SNPC000084 --dnrev A --dnport e10 --date 2021/07/01 --time 10:00
add_connection.py -u PAM275 --uprev A --upport n -d SNPC000084 --dnrev A --dnport n0 --date 2021/07/01 --time 10:00
add_connection.py -u PAM276 --uprev A --upport n -d SNPC000084 --dnrev A --dnport n4 --date 2021/07/01 --time 10:00
add_connection.py -u PAM277 --uprev A --upport n -d SNPC000084 --dnrev A --dnport n8 --date 2021/07/01 --time 10:00
add_connection.py -u SNPC000100 --uprev A --upport rack -d N06 --dnrev A --dnport loc3 --date 2021/07/01 --time 10:00
add_connection.py -u PAM278 --uprev A --upport e -d SNPC000100 --dnrev A --dnport e2 --date 2021/07/01 --time 10:00
add_connection.py -u PAM279 --uprev A --upport e -d SNPC000100 --dnrev A --dnport e6 --date 2021/07/01 --time 10:00
add_connection.py -u PAM280 --uprev A --upport e -d SNPC000100 --dnrev A --dnport e10 --date 2021/07/01 --time 10:00
add_connection.py -u PAM278 --uprev A --upport n -d SNPC000100 --dnrev A --dnport n0 --date 2021/07/01 --time 10:00
add_connection.py -u PAM279 --uprev A --upport n -d SNPC000100 --dnrev A --dnport n4 --date 2021/07/01 --time 10:00
add_connection.py -u PAM280 --uprev A --upport n -d SNPC000100 --dnrev A --dnport n8 --date 2021/07/01 --time 10:00
add_station.py ND11 --sernum ND11 --date 2021/07/01 --time 10:00
add_part.py -p FPS18 -r A -t fem-power-supply -m FPS18 --date 2021/07/01 --time 10:00
add_part.py -p PCH19 -r A -t pam-chassis -m PCH19 --date 2021/07/01 --time 10:00
add_part.py -p NBP11 -r A -t node-bulkhead -m NBP11 --date 2021/07/01 --time 10:00
add_part.py -p PAM245 -r A -t post-amp -m 245 --date 2021/07/01 --time 10:00
add_part.py -p PAM246 -r A -t post-amp -m 246 --date 2021/07/01 --time 10:00
add_part.py -p PAM247 -r A -t post-amp -m 247 --date 2021/07/01 --time 10:00
add_part.py -p PAM248 -r A -t post-amp -m 248 --date 2021/07/01 --time 10:00
add_part.py -p PAM249 -r A -t post-amp -m 249 --date 2021/07/01 --time 10:00
add_part.py -p PAM250 -r A -t post-amp -m 250 --date 2021/07/01 --time 10:00
add_part.py -p PAM251 -r A -t post-amp -m 251 --date 2021/07/01 --time 10:00
add_part.py -p PAM252 -r A -t post-amp -m 252 --date 2021/07/01 --time 10:00
add_part.py -p PAM253 -r A -t post-amp -m 253 --date 2021/07/01 --time 10:00
add_part.py -p PAM254 -r A -t post-amp -m 254 --date 2021/07/01 --time 10:00
add_part.py -p PAM255 -r A -t post-amp -m 255 --date 2021/07/01 --time 10:00
add_part.py -p PAM256 -r A -t post-amp -m 256 --date 2021/07/01 --time 10:00
add_connection.py -u N11 --uprev A --upport ground -d ND11 --dnrev A --dnport ground --date 2021/07/01 --time 10:00
add_connection.py -u FPS18 --uprev A --upport rack -d N11 --dnrev A --dnport top --date 2021/07/01 --time 10:00
add_connection.py -u PCH19 --uprev A --upport rack -d N11 --dnrev A --dnport bottom --date 2021/07/01 --time 10:00
add_connection.py -u NCM20 --uprev A --upport rack -d N11 --dnrev A --dnport middle --date 2021/07/01 --time 10:00
add_connection.py -u PAM245 --uprev A --upport slot -d PCH19 --dnrev A --dnport slot1 --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport e1 -d PAM245 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport n1 -d PAM245 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM246 --uprev A --upport slot -d PCH19 --dnrev A --dnport slot2 --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport e2 -d PAM246 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport n2 -d PAM246 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM247 --uprev A --upport slot -d PCH19 --dnrev A --dnport slot3 --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport e3 -d PAM247 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport n3 -d PAM247 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM248 --uprev A --upport slot -d PCH19 --dnrev A --dnport slot4 --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport e4 -d PAM248 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport n4 -d PAM248 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM249 --uprev A --upport slot -d PCH19 --dnrev A --dnport slot5 --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport e5 -d PAM249 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport n5 -d PAM249 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM250 --uprev A --upport slot -d PCH19 --dnrev A --dnport slot6 --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport e6 -d PAM250 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport n6 -d PAM250 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM251 --uprev A --upport slot -d PCH19 --dnrev A --dnport slot7 --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport e7 -d PAM251 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport n7 -d PAM251 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM252 --uprev A --upport slot -d PCH19 --dnrev A --dnport slot8 --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport e8 -d PAM252 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport n8 -d PAM252 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM253 --uprev A --upport slot -d PCH19 --dnrev A --dnport slot9 --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport e9 -d PAM253 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport n9 -d PAM253 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM254 --uprev A --upport slot -d PCH19 --dnrev A --dnport slot10 --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport e10 -d PAM254 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport n10 -d PAM254 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM255 --uprev A --upport slot -d PCH19 --dnrev A --dnport slot11 --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport e11 -d PAM255 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport n11 -d PAM255 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM256 --uprev A --upport slot -d PCH19 --dnrev A --dnport slot12 --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport e12 -d PAM256 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP11 --uprev A --upport n12 -d PAM256 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u SNPC000059 --uprev A --upport rack -d N11 --dnrev A --dnport loc0 --date 2021/07/01 --time 10:00
add_connection.py -u PAM245 --uprev A --upport e -d SNPC000059 --dnrev A --dnport e2 --date 2021/07/01 --time 10:00
add_connection.py -u PAM246 --uprev A --upport e -d SNPC000059 --dnrev A --dnport e6 --date 2021/07/01 --time 10:00
add_connection.py -u PAM247 --uprev A --upport e -d SNPC000059 --dnrev A --dnport e10 --date 2021/07/01 --time 10:00
add_connection.py -u PAM245 --uprev A --upport n -d SNPC000059 --dnrev A --dnport n0 --date 2021/07/01 --time 10:00
add_connection.py -u PAM246 --uprev A --upport n -d SNPC000059 --dnrev A --dnport n4 --date 2021/07/01 --time 10:00
add_connection.py -u PAM247 --uprev A --upport n -d SNPC000059 --dnrev A --dnport n8 --date 2021/07/01 --time 10:00
add_connection.py -u SNPC000093 --uprev A --upport rack -d N11 --dnrev A --dnport loc1 --date 2021/07/01 --time 10:00
add_connection.py -u PAM248 --uprev A --upport e -d SNPC000093 --dnrev A --dnport e2 --date 2021/07/01 --time 10:00
add_connection.py -u PAM249 --uprev A --upport e -d SNPC000093 --dnrev A --dnport e6 --date 2021/07/01 --time 10:00
add_connection.py -u PAM250 --uprev A --upport e -d SNPC000093 --dnrev A --dnport e10 --date 2021/07/01 --time 10:00
add_connection.py -u PAM248 --uprev A --upport n -d SNPC000093 --dnrev A --dnport n0 --date 2021/07/01 --time 10:00
add_connection.py -u PAM249 --uprev A --upport n -d SNPC000093 --dnrev A --dnport n4 --date 2021/07/01 --time 10:00
add_connection.py -u PAM250 --uprev A --upport n -d SNPC000093 --dnrev A --dnport n8 --date 2021/07/01 --time 10:00
add_connection.py -u SNPC000026 --uprev A --upport rack -d N11 --dnrev A --dnport loc2 --date 2021/07/01 --time 10:00
add_connection.py -u PAM251 --uprev A --upport e -d SNPC000026 --dnrev A --dnport e2 --date 2021/07/01 --time 10:00
add_connection.py -u PAM252 --uprev A --upport e -d SNPC000026 --dnrev A --dnport e6 --date 2021/07/01 --time 10:00
add_connection.py -u PAM253 --uprev A --upport e -d SNPC000026 --dnrev A --dnport e10 --date 2021/07/01 --time 10:00
add_connection.py -u PAM251 --uprev A --upport n -d SNPC000026 --dnrev A --dnport n0 --date 2021/07/01 --time 10:00
add_connection.py -u PAM252 --uprev A --upport n -d SNPC000026 --dnrev A --dnport n4 --date 2021/07/01 --time 10:00
add_connection.py -u PAM253 --uprev A --upport n -d SNPC000026 --dnrev A --dnport n8 --date 2021/07/01 --time 10:00
add_connection.py -u SNPC000089 --uprev A --upport rack -d N11 --dnrev A --dnport loc3 --date 2021/07/01 --time 10:00
add_connection.py -u PAM254 --uprev A --upport e -d SNPC000089 --dnrev A --dnport e2 --date 2021/07/01 --time 10:00
add_connection.py -u PAM255 --uprev A --upport e -d SNPC000089 --dnrev A --dnport e6 --date 2021/07/01 --time 10:00
add_connection.py -u PAM256 --uprev A --upport e -d SNPC000089 --dnrev A --dnport e10 --date 2021/07/01 --time 10:00
add_connection.py -u PAM254 --uprev A --upport n -d SNPC000089 --dnrev A --dnport n0 --date 2021/07/01 --time 10:00
add_connection.py -u PAM255 --uprev A --upport n -d SNPC000089 --dnrev A --dnport n4 --date 2021/07/01 --time 10:00
add_connection.py -u PAM256 --uprev A --upport n -d SNPC000089 --dnrev A --dnport n8 --date 2021/07/01 --time 10:00
add_station.py ND16 --sernum ND16 --date 2021/07/01 --time 10:00
add_part.py -p FPS22 -r A -t fem-power-supply -m FPS22 --date 2021/07/01 --time 10:00
add_part.py -p PCH20 -r A -t pam-chassis -m PCH20 --date 2021/07/01 --time 10:00
add_part.py -p NBP16 -r A -t node-bulkhead -m NBP16 --date 2021/07/01 --time 10:00
add_part.py -p PAM281 -r A -t post-amp -m 281 --date 2021/07/01 --time 10:00
add_part.py -p PAM282 -r A -t post-amp -m 282 --date 2021/07/01 --time 10:00
add_part.py -p PAM283 -r A -t post-amp -m 283 --date 2021/07/01 --time 10:00
add_part.py -p PAM284 -r A -t post-amp -m 284 --date 2021/07/01 --time 10:00
add_part.py -p PAM285 -r A -t post-amp -m 285 --date 2021/07/01 --time 10:00
add_part.py -p PAM286 -r A -t post-amp -m 286 --date 2021/07/01 --time 10:00
add_part.py -p PAM287 -r A -t post-amp -m 287 --date 2021/07/01 --time 10:00
add_part.py -p PAM288 -r A -t post-amp -m 288 --date 2021/07/01 --time 10:00
add_part.py -p PAM289 -r A -t post-amp -m 289 --date 2021/07/01 --time 10:00
add_part.py -p PAM290 -r A -t post-amp -m 290 --date 2021/07/01 --time 10:00
add_part.py -p PAM291 -r A -t post-amp -m 291 --date 2021/07/01 --time 10:00
add_part.py -p PAM292 -r A -t post-amp -m 292 --date 2021/07/01 --time 10:00
add_connection.py -u N16 --uprev A --upport ground -d ND16 --dnrev A --dnport ground --date 2021/07/01 --time 10:00
add_connection.py -u FPS22 --uprev A --upport rack -d N16 --dnrev A --dnport top --date 2021/07/01 --time 10:00
add_connection.py -u PCH20 --uprev A --upport rack -d N16 --dnrev A --dnport bottom --date 2021/07/01 --time 10:00
add_connection.py -u NCM11 --uprev A --upport rack -d N16 --dnrev A --dnport middle --date 2021/07/01 --time 10:00
add_connection.py -u PAM281 --uprev A --upport slot -d PCH20 --dnrev A --dnport slot1 --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport e1 -d PAM281 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport n1 -d PAM281 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM282 --uprev A --upport slot -d PCH20 --dnrev A --dnport slot2 --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport e2 -d PAM282 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport n2 -d PAM282 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM283 --uprev A --upport slot -d PCH20 --dnrev A --dnport slot3 --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport e3 -d PAM283 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport n3 -d PAM283 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM284 --uprev A --upport slot -d PCH20 --dnrev A --dnport slot4 --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport e4 -d PAM284 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport n4 -d PAM284 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM285 --uprev A --upport slot -d PCH20 --dnrev A --dnport slot5 --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport e5 -d PAM285 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport n5 -d PAM285 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM286 --uprev A --upport slot -d PCH20 --dnrev A --dnport slot6 --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport e6 -d PAM286 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport n6 -d PAM286 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM287 --uprev A --upport slot -d PCH20 --dnrev A --dnport slot7 --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport e7 -d PAM287 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport n7 -d PAM287 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM288 --uprev A --upport slot -d PCH20 --dnrev A --dnport slot8 --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport e8 -d PAM288 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport n8 -d PAM288 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM289 --uprev A --upport slot -d PCH20 --dnrev A --dnport slot9 --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport e9 -d PAM289 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport n9 -d PAM289 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM290 --uprev A --upport slot -d PCH20 --dnrev A --dnport slot10 --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport e10 -d PAM290 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport n10 -d PAM290 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM291 --uprev A --upport slot -d PCH20 --dnrev A --dnport slot11 --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport e11 -d PAM291 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport n11 -d PAM291 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u PAM292 --uprev A --upport slot -d PCH20 --dnrev A --dnport slot12 --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport e12 -d PAM292 --dnrev A --dnport e --date 2021/07/01 --time 10:00
add_connection.py -u NBP16 --uprev A --upport n12 -d PAM292 --dnrev A --dnport n --date 2021/07/01 --time 10:00
add_connection.py -u SNPC000012 --uprev A --upport rack -d N16 --dnrev A --dnport loc0 --date 2021/07/01 --time 10:00
add_connection.py -u PAM281 --uprev A --upport e -d SNPC000012 --dnrev A --dnport e2 --date 2021/07/01 --time 10:00
add_connection.py -u PAM282 --uprev A --upport e -d SNPC000012 --dnrev A --dnport e6 --date 2021/07/01 --time 10:00
add_connection.py -u PAM283 --uprev A --upport e -d SNPC000012 --dnrev A --dnport e10 --date 2021/07/01 --time 10:00
add_connection.py -u PAM281 --uprev A --upport n -d SNPC000012 --dnrev A --dnport n0 --date 2021/07/01 --time 10:00
add_connection.py -u PAM282 --uprev A --upport n -d SNPC000012 --dnrev A --dnport n4 --date 2021/07/01 --time 10:00
add_connection.py -u PAM283 --uprev A --upport n -d SNPC000012 --dnrev A --dnport n8 --date 2021/07/01 --time 10:00
add_connection.py -u SNPC000090 --uprev A --upport rack -d N16 --dnrev A --dnport loc1 --date 2021/07/01 --time 10:00
add_connection.py -u PAM284 --uprev A --upport e -d SNPC000090 --dnrev A --dnport e2 --date 2021/07/01 --time 10:00
add_connection.py -u PAM285 --uprev A --upport e -d SNPC000090 --dnrev A --dnport e6 --date 2021/07/01 --time 10:00
add_connection.py -u PAM286 --uprev A --upport e -d SNPC000090 --dnrev A --dnport e10 --date 2021/07/01 --time 10:00
add_connection.py -u PAM284 --uprev A --upport n -d SNPC000090 --dnrev A --dnport n0 --date 2021/07/01 --time 10:00
add_connection.py -u PAM285 --uprev A --upport n -d SNPC000090 --dnrev A --dnport n4 --date 2021/07/01 --time 10:00
add_connection.py -u PAM286 --uprev A --upport n -d SNPC000090 --dnrev A --dnport n8 --date 2021/07/01 --time 10:00
add_connection.py -u SNPC000101 --uprev A --upport rack -d N16 --dnrev A --dnport loc2 --date 2021/07/01 --time 10:00
add_connection.py -u PAM287 --uprev A --upport e -d SNPC000101 --dnrev A --dnport e2 --date 2021/07/01 --time 10:00
add_connection.py -u PAM288 --uprev A --upport e -d SNPC000101 --dnrev A --dnport e6 --date 2021/07/01 --time 10:00
add_connection.py -u PAM289 --uprev A --upport e -d SNPC000101 --dnrev A --dnport e10 --date 2021/07/01 --time 10:00
add_connection.py -u PAM287 --uprev A --upport n -d SNPC000101 --dnrev A --dnport n0 --date 2021/07/01 --time 10:00
add_connection.py -u PAM288 --uprev A --upport n -d SNPC000101 --dnrev A --dnport n4 --date 2021/07/01 --time 10:00
add_connection.py -u PAM289 --uprev A --upport n -d SNPC000101 --dnrev A --dnport n8 --date 2021/07/01 --time 10:00
add_connection.py -u SNPC000120 --uprev A --upport rack -d N16 --dnrev A --dnport loc3 --date 2021/07/01 --time 10:00
add_connection.py -u PAM290 --uprev A --upport e -d SNPC000120 --dnrev A --dnport e2 --date 2021/07/01 --time 10:00
add_connection.py -u PAM291 --uprev A --upport e -d SNPC000120 --dnrev A --dnport e6 --date 2021/07/01 --time 10:00
add_connection.py -u PAM292 --uprev A --upport e -d SNPC000120 --dnrev A --dnport e10 --date 2021/07/01 --time 10:00
add_connection.py -u PAM290 --uprev A --upport n -d SNPC000120 --dnrev A --dnport n0 --date 2021/07/01 --time 10:00
add_connection.py -u PAM291 --uprev A --upport n -d SNPC000120 --dnrev A --dnport n4 --date 2021/07/01 --time 10:00
add_connection.py -u PAM292 --uprev A --upport n -d SNPC000120 --dnrev A --dnport n8 --date 2021/07/01 --time 10:00
