#! /bin/bash
echo "./210717_add_built_ants.py" >> scripts.log 
add_station.py HB320 --sernum 324 --date 2021/05/11 --time 10:00
add_part.py -p A320 -r H -t antenna -m H324 --date 2021/05/11 --time 10:00
add_connection.py -u HB320 --uprev A --upport ground -d A320 --dnrev H --dnport ground --date 2021/05/11 --time 10:00
add_station.py HB321 --sernum 325 --date 2021/05/11 --time 10:00
add_part.py -p A321 -r H -t antenna -m H325 --date 2021/05/11 --time 10:00
add_connection.py -u HB321 --uprev A --upport ground -d A321 --dnrev H --dnport ground --date 2021/05/11 --time 10:00
add_station.py HB324 --sernum 326 --date 2021/05/11 --time 10:00
add_part.py -p A324 -r H -t antenna -m H326 --date 2021/05/11 --time 10:00
add_connection.py -u HB324 --uprev A --upport ground -d A324 --dnrev H --dnport ground --date 2021/05/11 --time 10:00
add_station.py HA325 --sernum 327 --date 2021/05/11 --time 10:00
add_part.py -p A325 -r H -t antenna -m H327 --date 2021/05/11 --time 10:00
add_connection.py -u HA325 --uprev A --upport ground -d A325 --dnrev H --dnport ground --date 2021/05/11 --time 10:00
add_station.py HB322 --sernum 328 --date 2021/05/12 --time 10:00
add_part.py -p A322 -r H -t antenna -m H328 --date 2021/05/12 --time 10:00
add_connection.py -u HB322 --uprev A --upport ground -d A322 --dnrev H --dnport ground --date 2021/05/12 --time 10:00
add_station.py HB323 --sernum 329 --date 2021/05/13 --time 10:00
add_part.py -p A323 -r H -t antenna -m H329 --date 2021/05/13 --time 10:00
add_connection.py -u HB323 --uprev A --upport ground -d A323 --dnrev H --dnport ground --date 2021/05/13 --time 10:00
add_station.py HA326 --sernum 330 --date 2021/05/13 --time 10:00
add_part.py -p A326 -r H -t antenna -m H330 --date 2021/05/13 --time 10:00
add_connection.py -u HA326 --uprev A --upport ground -d A326 --dnrev H --dnport ground --date 2021/05/13 --time 10:00
add_station.py HA327 --sernum 331 --date 2021/05/13 --time 10:00
add_part.py -p A327 -r H -t antenna -m H331 --date 2021/05/13 --time 10:00
add_connection.py -u HA327 --uprev A --upport ground -d A327 --dnrev H --dnport ground --date 2021/05/13 --time 10:00
add_station.py HB328 --sernum 332 --date 2021/05/13 --time 10:00
add_part.py -p A328 -r H -t antenna -m H332 --date 2021/05/13 --time 10:00
add_connection.py -u HB328 --uprev A --upport ground -d A328 --dnrev H --dnport ground --date 2021/05/13 --time 10:00
