#! /bin/bash
source ~/.bashrc
echo "210915_infoupd_1942" >> scripts.log 
add_part_info.py -p HH16 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/666' -l "infoupd" --date 2021/09/15 --time 19:42:00
add_part_info.py -p HH127 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/666' -l "infoupd" --date 2021/09/15 --time 19:42:00
add_part_info.py -p HH130 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/666' -l "infoupd" --date 2021/09/15 --time 19:42:00
add_part_info.py -p HH144 -r A -c 'Feed Heights: https://github.com/HERA-Team/HERA_Commissioning/issues/666' -l "infoupd" --date 2021/09/15 --time 19:42:00
add_part_info.py -p HH73 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/666' -l "infoupd" --date 2021/09/15 --time 19:42:00
