#! /bin/bash
source ~/.bashrc
echo "211025_infoupd_1542" >> scripts.log 
add_part_info.py -p HH201 -r A -c 'door closed 25/10/2021' -l "infoupd" --date 2021/10/25 --time 15:42:00
add_part_info.py -p HH202 -r A -c 'door closed 25/10/2021' -l "infoupd" --date 2021/10/25 --time 15:42:00
add_part_info.py -p HH219 -r A -c 'door closed 25/10/2021' -l "infoupd" --date 2021/10/25 --time 15:42:00
add_part_info.py -p HH220 -r A -c 'door closed 25/10/2021' -l "infoupd" --date 2021/10/25 --time 15:42:00
add_part_info.py -p HH221 -r A -c 'door closed 25/10/2021' -l "infoupd" --date 2021/10/25 --time 15:42:00
add_part_info.py -p HH222 -r A -c 'door closed 25/10/2021' -l "infoupd" --date 2021/10/25 --time 15:42:00
add_part_info.py -p HH239 -r A -c 'door closed 25/10/2021' -l "infoupd" --date 2021/10/25 --time 15:42:00
