#! /bin/bash
source ~/.bashrc
echo "211018_infoupd_0642" >> scripts.log 
add_part_info.py -p HH16 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/666' -l "infoupd" --date 2021/10/18 --time 06:42:00
add_part_info.py -p HH127 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/666' -l "infoupd" --date 2021/10/18 --time 06:42:00
add_part_info.py -p HH130 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/666' -l "infoupd" --date 2021/10/18 --time 06:42:00
add_part_info.py -p HH144 -r A -c 'Feed Heights: https://github.com/HERA-Team/HERA_Commissioning/issues/666' -l "infoupd" --date 2021/10/18 --time 06:42:00
add_part_info.py -p HH73 -r A -c 'https://github.com/HERA-Team/HERA_Commissioning/issues/666' -l "infoupd" --date 2021/10/18 --time 06:42:00
