#! /bin/bash
echo "211017_infoupd_0912" >> scripts.log 
add_part_info.py -p HH18 -r A -c 'Josh noted time variability over a few nights.' -l "infoupd" --date 2021/10/17 --time 09:12:00
add_part_info.py -p HH94 -r A -c 'Josh noted time variability over a few nights.' -l "infoupd" --date 2021/10/17 --time 09:12:00
add_part_info.py -p HH136 -r A -c 'Josh noted time variability over a few nights.' -l "infoupd" --date 2021/10/17 --time 09:12:00
add_part_info.py -p HH179 -r A -c 'Josh noted time variability over a few nights.' -l "infoupd" --date 2021/10/17 --time 09:12:00
add_part_info.py -p HH36 -r A -c 'Spectra: n3p1E' -l "infoupd" --date 2021/10/17 --time 09:12:00
add_part_info.py -p HH36 -r A -c 'Spectra: N3P1N' -l "infoupd" --date 2021/10/17 --time 09:12:02
add_part_info.py -p HH37 -r A -c 'Spectra: N3P2E' -l "infoupd" --date 2021/10/17 --time 09:12:00
add_part_info.py -p HH37 -r A -c 'Spectra: N3P2N' -l "infoupd" --date 2021/10/17 --time 09:12:02
add_part_info.py -p HH38 -r A -c 'Spectra: N3P3E' -l "infoupd" --date 2021/10/17 --time 09:12:00
add_part_info.py -p HH38 -r A -c 'Spectra: N3P3N' -l "infoupd" --date 2021/10/17 --time 09:12:02
add_part_info.py -p HH99 -r A -c 'Josh noted time variability over a few nights.' -l "infoupd" --date 2021/10/17 --time 09:12:00
add_part_info.py -p N04 -r A -c 'WR endpoint is not functioning properly (works as a switch, but not for timing) -- swapped it (NCM4) with the one in node 21 (NCM21)' -l "infoupd" --date 2021/10/17 --time 09:12:00
add_part_info.py -p N21 -r A -c 'Removed NCM to put in node 4' -l "infoupd" --date 2021/10/17 --time 09:12:00
