#! /bin/bash
source ~/.bashrc
echo "211013_infoupd_1242" >> scripts.log 
add_part_info.py -p HH0 -r A -c 'Spectra: n3p1E' -l "infoupd" --date 2021/10/13 --time 12:42:00
add_part_info.py -p HH0 -r A -c 'Spectra: N3P1N' -l "infoupd" --date 2021/10/13 --time 12:42:02
add_part_info.py -p HH2 -r A -c 'Spectra: N3P2E' -l "infoupd" --date 2021/10/13 --time 12:42:00
add_part_info.py -p HH2 -r A -c 'Spectra: N3P2N' -l "infoupd" --date 2021/10/13 --time 12:42:02
add_part_info.py -p HH1 -r A -c 'Spectra: N3P3E' -l "infoupd" --date 2021/10/13 --time 12:42:00
add_part_info.py -p HH1 -r A -c 'Spectra: N3P3N' -l "infoupd" --date 2021/10/13 --time 12:42:02
add_part_info.py -p HH26 -r A -c 'Spectra: N3P11E' -l "infoupd" --date 2021/10/13 --time 12:42:00
