#! /bin/bash
source ~/.bashrc
echo "211017_infoupd_1642" >> scripts.log 
add_part_info.py -p N04 -r A -c 'WR endpoint is not functioning properly (works as a switch, but not for timing) -- swapped it (NCM4) with the one in node 21 (NCM21)' -l "infoupd" --date 2021/10/17 --time 16:42:00
add_part_info.py -p N21 -r A -c 'Removed NCM to put in node 4' -l "infoupd" --date 2021/10/17 --time 16:42:00
