#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/211123_infoupd_2219" >> scripts.log 
add_part_info.py -p HH211 -r A -c 'door closed 19/11/2021' -l "infoupd" --date 2021/11/23 --time 22:19:00
add_part_info.py -p HH211 -r A -c 'Spectre: N20P1E' -l "infoupd" --date 2021/11/23 --time 22:19:02
add_part_info.py -p HH211 -r A -c 'Feed heights (NE/SE/SW/NW): 4.407' -l "infoupd" --date 2021/11/23 --time 22:19:04
add_part_info.py -p HH211 -r A -c 'Spectre: N20P1N' -l "infoupd" --date 2021/11/23 --time 22:19:06
add_part_info.py -p HH244 -r A -c 'Spectre: N2OP2E' -l "infoupd" --date 2021/11/23 --time 22:19:00
add_part_info.py -p HH244 -r A -c 'Feed heights (NE/SE/SW/NW): 4.399' -l "infoupd" --date 2021/11/23 --time 22:19:02
add_part_info.py -p HH244 -r A -c 'Spectre: N20P2N' -l "infoupd" --date 2021/11/23 --time 22:19:04
add_part_info.py -p HH245 -r A -c 'door closed 19/11/2021' -l "infoupd" --date 2021/11/23 --time 22:19:00
add_part_info.py -p HH245 -r A -c 'Spectre: N20P3E' -l "infoupd" --date 2021/11/23 --time 22:19:02
add_part_info.py -p HH245 -r A -c 'Feed heights (NE/SE/SW/NW): 4.404' -l "infoupd" --date 2021/11/23 --time 22:19:04
add_part_info.py -p HH245 -r A -c 'Spectre: N20P3N' -l "infoupd" --date 2021/11/23 --time 22:19:06
add_part_info.py -p HH246 -r A -c 'Spectre: N20P4E' -l "infoupd" --date 2021/11/23 --time 22:19:00
add_part_info.py -p HH246 -r A -c 'Spectre: N20P3N' -l "infoupd" --date 2021/11/23 --time 22:19:02
add_part_info.py -p HH261 -r A -c 'door closed 19/11/2021' -l "infoupd" --date 2021/11/23 --time 22:19:00
add_part_info.py -p HH261 -r A -c 'Spectre: N20P4E' -l "infoupd" --date 2021/11/23 --time 22:19:02
add_part_info.py -p HH261 -r A -c 'Feed heights (NE/SE/SW/NW): 4.403' -l "infoupd" --date 2021/11/23 --time 22:19:04
add_part_info.py -p HH261 -r A -c 'Spectre: N20P4N' -l "infoupd" --date 2021/11/23 --time 22:19:06
add_part_info.py -p HH227 -r A -c 'door closed 19/11/2021' -l "infoupd" --date 2021/11/23 --time 22:19:00
add_part_info.py -p HH228 -r A -c 'Spectre: N20P11E' -l "infoupd" --date 2021/11/23 --time 22:19:00
add_part_info.py -p HH228 -r A -c 'Feed heights (NE/SE/SW/NW): 4.403' -l "infoupd" --date 2021/11/23 --time 22:19:02
add_part_info.py -p HH228 -r A -c 'Spectre: N20P11N' -l "infoupd" --date 2021/11/23 --time 22:19:04
add_part_info.py -p HH229 -r A -c 'door closed 19/11/2021' -l "infoupd" --date 2021/11/23 --time 22:19:00
add_part_info.py -p HH229 -r A -c 'Spectre: N20P12E' -l "infoupd" --date 2021/11/23 --time 22:19:02
add_part_info.py -p HH229 -r A -c 'Spectre: N20P12N' -l "infoupd" --date 2021/11/23 --time 22:19:04
