#! /bin/bash
source ~/.bashrc
echo "211109_infoupd_1042" >> scripts.log 
add_part_info.py -p HH205 -r A -c 'door closed 08/11/2021' -l "infoupd" --date 2021/11/09 --time 10:42:00
add_part_info.py -p HH206 -r A -c 'door closed 08/11/21' -l "infoupd" --date 2021/11/09 --time 10:42:00
add_part_info.py -p HH207 -r A -c 'door closed 08/11/2021' -l "infoupd" --date 2021/11/09 --time 10:42:00
add_part_info.py -p HH223 -r A -c 'door closed 08/11/2021' -l "infoupd" --date 2021/11/09 --time 10:42:00
add_part_info.py -p HH224 -r A -c 'door closed 08/11/2021' -l "infoupd" --date 2021/11/09 --time 10:42:00
add_part_info.py -p HH225 -r A -c 'door closed 08/11/2021' -l "infoupd" --date 2021/11/09 --time 10:42:00
add_part_info.py -p HH226 -r A -c 'door closed 08/11/2021' -l "infoupd" --date 2021/11/09 --time 10:42:00
add_part_info.py -p HH241 -r A -c 'door closed 08/11/2021' -l "infoupd" --date 2021/11/09 --time 10:42:00
add_part_info.py -p HH242 -r A -c 'door closed 08/11/2021' -l "infoupd" --date 2021/11/09 --time 10:42:00
add_part_info.py -p HH243 -r A -c 'door closed 08/11/2021' -l "infoupd" --date 2021/11/09 --time 10:42:00
