#! /usr/bin/env bash
echo 171011_broken_pam_swap >> scripts.log
stop_connection.py -u RI5B4E --uprev A --upport b -d PAM75112 --dnrev B --dnport ea --date 2017/10/11 --time 15:00 --actually_do_it
stop_connection.py -u RI5B4N --uprev A --upport b -d PAM75112 --dnrev B --dnport na --date 2017/10/11 --time 15:00 --actually_do_it
stop_connection.py -u PAM75112 --uprev B --upport eb -d RO5B4E --dnrev A --dnport a --date 2017/10/11 --time 15:00 --actually_do_it
stop_connection.py -u PAM75112 --uprev B --upport nb -d RO5B4N --dnrev A --dnport a --date 2017/10/11 --time 15:00 --actually_do_it
add_part.py -p PAM75168 -r B -t post-amp -m 75168 --date 2017/10/11 --time 15:00 --actually_do_it
add_connection.py -u RI5B4E --uprev A --upport b -d PAM75168 --dnrev B --dnport ea --date 2017/10/11 --time 15:00 --actually_do_it
add_connection.py -u RI5B4N --uprev A --upport b -d PAM75168 --dnrev B --dnport na --date 2017/10/11 --time 15:00 --actually_do_it
add_connection.py -u PAM75168 --uprev B --upport eb -d RO5B4E --dnrev A --dnport a --date 2017/10/11 --time 15:00 --actually_do_it
add_connection.py -u PAM75168 --uprev B --upport nb -d RO5B4N --dnrev A --dnport a --date 2017/10/11 --time 15:00 --actually_do_it
