#! /usr/bin/env bash
echo 171125_A142 >> scripts.log
add_part.py -p FEM75041 -r A -t front-end -m 75041 --date 2017/11/23 --time 9:00 --actually_do_it
add_part.py -p PAM75122 -r B -t post-amp -m 75122 --date 2017/11/23 --time 9:00 --actually_do_it
stop_connection.py -u C7F142 --uprev A --upport eb -d RI4B7E --dnrev A --dnport a --date 2017/11/19 --time 9:00 --actually_do_it
stop_connection.py -u C7F142 --uprev A --upport nb -d RI4B7N --dnrev A --dnport a --date 2017/11/19 --time 9:00 --actually_do_it
stop_connection.py -u FEA32 --uprev A --upport e -d C7F142 --dnrev A --dnport ea --date 2017/11/19 --time 9:00 --actually_do_it
stop_connection.py -u FEA32 --uprev A --upport n -d C7F142 --dnrev A --dnport na --date 2017/11/19 --time 9:00 --actually_do_it
stop_connection.py -u FDA32 --uprev B --upport terminals -d FEA32 --dnrev A --dnport input --date 2017/11/19 --time 9:00 --actually_do_it
add_connection.py -u FDA32 --uprev B --upport terminals -d FEM75041 --dnrev A --dnport input --date 2017/11/23 --time 9:00 --actually_do_it
add_connection.py -u FEM75041 --uprev A --upport e -d C7F142 --dnrev A --dnport ea --date 2017/11/23 --time 9:00 --actually_do_it
add_connection.py -u FEM75041 --uprev A --upport n -d C7F142 --dnrev A --dnport na --date 2017/11/23 --time 9:00 --actually_do_it
add_connection.py -u C7F142 --uprev A --upport eb -d RI3A6E --dnrev A --dnport a --date 2017/11/23 --time 9:00 --actually_do_it
add_connection.py -u C7F142 --uprev A --upport nb -d RI3A6N --dnrev A --dnport a --date 2017/11/23 --time 9:00 --actually_do_it
add_connection.py -u RI3A6E --uprev A --upport b -d PAM75122 --dnrev B --dnport ea --date 2017/11/23 --time 9:00 --actually_do_it
add_connection.py -u RI3A6N --uprev A --upport b -d PAM75122 --dnrev B --dnport na --date 2017/11/23 --time 9:00 --actually_do_it
add_connection.py -u PAM75122 --uprev B --upport eb -d RO3A6E --dnrev A --dnport b --date 2017/11/23 --time 9:00 --actually_do_it
add_connection.py -u PAM75122 --uprev B --upport nb -d RO3A6N --dnrev A --dnport b --date 2017/11/23 --time 9:00 --actually_do_it
