#! /usr/bin/env bash
echo 180314_fix_68 >> scripts.log
add_part.py -p PAM75158 -r B -t post-amp -m 75158 --date 2018/03/13 --time 10:00 --actually_do_it
stop_connection.py -u C7F68 --uprev A --upport eb -d RI5A6E --dnrev A --dnport a --date 2018/03/13 --time 11:00 --actually_do_it
stop_connection.py -u C7F68 --uprev A --upport nb -d RI5A6N --dnrev A --dnport a --date 2018/03/13 --time 11:00 --actually_do_it
add_connection.py -u C7F68 --uprev A --upport eb -d RI2A7E --dnrev A --dnport a --date 2018/03/13 --time 12:00 --actually_do_it
add_connection.py -u C7F68 --uprev A --upport nb -d RI2A7N --dnrev A --dnport a --date 2018/03/13 --time 12:00 --actually_do_it
add_connection.py -u RI2A7E --uprev A --upport b -d PAM75158 --dnrev B --dnport ea --date 2018/03/13 --time 12:00 --actually_do_it
add_connection.py -u RI2A7N --uprev A --upport b -d PAM75158 --dnrev B --dnport na --date 2018/03/13 --time 12:00 --actually_do_it
add_connection.py -u PAM75158 --uprev B --upport eb -d RO2A7E --dnrev A --dnport a --date 2018/03/13 --time 12:00 --actually_do_it
add_connection.py -u PAM75158 --uprev B --upport nb -d RO2A7N --dnrev A --dnport a --date 2018/03/13 --time 12:00 --actually_do_it
