#! /usr/bin/env bash
echo 180329_add_stations >> scripts.log
add_station.py HH73
add_station.py HH74
add_station.py HH89
add_station.py HH90
add_station.py HH91
add_station.py HH178
add_station.py HH179
add_station.py HH184
add_station.py HH185
add_station.py HH186
add_station.py HH198
add_station.py HH199
add_station.py HH200
add_station.py HH201
add_station.py HH202
add_station.py HH203
add_station.py HH204
add_station.py HH216
add_station.py HH217
add_station.py HH218
add_station.py HH220
add_station.py HH221
add_station.py HH222
add_station.py HH223
add_station.py HH224
add_station.py HH225
add_station.py HH233
add_station.py HH235
add_station.py HH236
add_station.py HH237
add_station.py HH238
add_station.py HH239
add_station.py HH240
add_station.py HH241
add_station.py HH242
add_station.py HH243
add_station.py HH250
add_station.py HH252
add_station.py HH253
add_station.py HH254
add_station.py HH255
add_station.py HH256
add_station.py HH257
add_station.py HH258
add_station.py HH259
add_station.py HH260
add_station.py HH266
add_station.py HH281
add_part.py -p A73 -r H -t antenna -m S/N84 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A74 -r H -t antenna -m S/N85 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A89 -r H -t antenna -m S/N86 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A90 -r H -t antenna -m S/N87 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A91 -r H -t antenna -m S/N88 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A178 -r H -t antenna -m S/N89 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A179 -r H -t antenna -m S/N90 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A184 -r H -t antenna -m S/N91 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A185 -r H -t antenna -m S/N92 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A186 -r H -t antenna -m S/N93 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A198 -r H -t antenna -m S/N94 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A199 -r H -t antenna -m S/N95 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A200 -r H -t antenna -m S/N96 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A201 -r H -t antenna -m S/N97 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A202 -r H -t antenna -m S/N98 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A203 -r H -t antenna -m S/N99 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A204 -r H -t antenna -m S/N100 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A216 -r H -t antenna -m S/N101 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A217 -r H -t antenna -m S/N102 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A218 -r H -t antenna -m S/N103 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A220 -r H -t antenna -m S/N104 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A221 -r H -t antenna -m S/N105 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A222 -r H -t antenna -m S/N106 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A223 -r H -t antenna -m S/N107 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A224 -r H -t antenna -m S/N108 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A225 -r H -t antenna -m S/N109 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A233 -r H -t antenna -m S/N110 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A235 -r H -t antenna -m S/N111 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A236 -r H -t antenna -m S/N112 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A237 -r H -t antenna -m S/N113 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A238 -r H -t antenna -m S/N114 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A239 -r H -t antenna -m S/N115 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A240 -r H -t antenna -m S/N116 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A241 -r H -t antenna -m S/N117 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A242 -r H -t antenna -m S/N118 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A243 -r H -t antenna -m S/N119 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A250 -r H -t antenna -m S/N120 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A252 -r H -t antenna -m S/N121 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A253 -r H -t antenna -m S/N122 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A254 -r H -t antenna -m S/N123 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A255 -r H -t antenna -m S/N124 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A256 -r H -t antenna -m S/N125 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A257 -r H -t antenna -m S/N126 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A258 -r H -t antenna -m S/N127 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A259 -r H -t antenna -m S/N128 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A260 -r H -t antenna -m S/N129 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A266 -r H -t antenna -m S/N130 --date 2018/03/29 --time 10:00 --actually_do_it
add_part.py -p A281 -r H -t antenna -m S/N131 --date 2018/03/29 --time 10:00 --actually_do_it
add_connection.py -u HH73 --uprev A --upport ground -d A73 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH74 --uprev A --upport ground -d A74 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH89 --uprev A --upport ground -d A89 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH90 --uprev A --upport ground -d A90 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH91 --uprev A --upport ground -d A91 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH178 --uprev A --upport ground -d A178 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH179 --uprev A --upport ground -d A179 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH184 --uprev A --upport ground -d A184 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH185 --uprev A --upport ground -d A185 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH186 --uprev A --upport ground -d A186 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH198 --uprev A --upport ground -d A198 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH199 --uprev A --upport ground -d A199 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH200 --uprev A --upport ground -d A200 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH201 --uprev A --upport ground -d A201 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH202 --uprev A --upport ground -d A202 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH203 --uprev A --upport ground -d A203 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH204 --uprev A --upport ground -d A204 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH216 --uprev A --upport ground -d A216 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH217 --uprev A --upport ground -d A217 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH218 --uprev A --upport ground -d A218 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH220 --uprev A --upport ground -d A220 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH221 --uprev A --upport ground -d A221 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH222 --uprev A --upport ground -d A222 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH223 --uprev A --upport ground -d A223 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH224 --uprev A --upport ground -d A224 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH225 --uprev A --upport ground -d A225 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH233 --uprev A --upport ground -d A233 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH235 --uprev A --upport ground -d A235 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH236 --uprev A --upport ground -d A236 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH237 --uprev A --upport ground -d A237 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH238 --uprev A --upport ground -d A238 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH239 --uprev A --upport ground -d A239 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH240 --uprev A --upport ground -d A240 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH241 --uprev A --upport ground -d A241 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH242 --uprev A --upport ground -d A242 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH243 --uprev A --upport ground -d A243 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH250 --uprev A --upport ground -d A250 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH252 --uprev A --upport ground -d A252 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH253 --uprev A --upport ground -d A253 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH254 --uprev A --upport ground -d A254 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH255 --uprev A --upport ground -d A255 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH256 --uprev A --upport ground -d A256 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH257 --uprev A --upport ground -d A257 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH258 --uprev A --upport ground -d A258 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH259 --uprev A --upport ground -d A259 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH260 --uprev A --upport ground -d A260 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH266 --uprev A --upport ground -d A266 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
add_connection.py -u HH281 --uprev A --upport ground -d A281 --dnrev H --dnport ground --date 2018/03/29 --time 12:00 --actually_do_it
