#! /usr/bin/env bash
echo 180327_add_ants >> scripts.log
add_station.py HH180
add_station.py HH181
add_station.py HH182
add_station.py HH183
add_part.py -p A180 -r H -t antenna -m S/N80 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p A181 -r H -t antenna -m S/N81 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p A182 -r H -t antenna -m S/N82 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p A183 -r H -t antenna -m S/N83 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p FDA69 -r B -t feed -m P69 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p FDA70 -r B -t feed -m P70 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p FDA71 -r B -t feed -m P71 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p FDA73 -r B -t feed -m P73 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p FEM75064 -r A -t front-end -m 75064 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p FEM75065 -r A -t front-end -m 75065 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p FEM75047 -r A -t front-end -m 75047 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p C7F180 -r A -t cable-feed75 -m P180 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p C7F181 -r A -t cable-feed75 -m P181 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p C7F182 -r A -t cable-feed75 -m P182 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p C7F183 -r A -t cable-feed75 -m P183 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p PAM75153 -r B -t post-amp -m 75153 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p PAM75154 -r B -t post-amp -m 75154 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p PAM75155 -r B -t post-amp -m 75155 --date 2018/03/26 --time 10:00 --actually_do_it
add_part.py -p PAM75156 -r B -t post-amp -m 75156 --date 2018/03/26 --time 10:00 --actually_do_it
add_connection.py -u HH180 --uprev A --upport ground -d A180 --dnrev H --dnport ground --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u A180 --uprev H --upport focus -d FDA69 --dnrev B --dnport input --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u FDA69 --uprev B --upport terminals -d FEM75064 --dnrev A --dnport input --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u FEM75064 --uprev A --upport e -d C7F180 --dnrev A --dnport ea --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u FEM75064 --uprev A --upport n -d C7F180 --dnrev A --dnport na --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u C7F180 --uprev A --upport eb -d RI2B1E --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u C7F180 --uprev A --upport nb -d RI2B1N --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u RI2B1E --uprev A --upport b -d PAM75156 --dnrev B --dnport ea --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u RI2B1N --uprev A --upport b -d PAM75156 --dnrev B --dnport na --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u PAM75156 --uprev B --upport eb -d RO2B1E --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u PAM75156 --uprev B --upport nb -d RO2B1N --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u HH181 --uprev A --upport ground -d A181 --dnrev H --dnport ground --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u A181 --uprev H --upport focus -d FDA70 --dnrev B --dnport input --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u FDA70 --uprev B --upport terminals -d FEM75065 --dnrev A --dnport input --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u FEM75065 --uprev A --upport e -d C7F181 --dnrev A --dnport ea --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u FEM75065 --uprev A --upport n -d C7F181 --dnrev A --dnport na --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u C7F181 --uprev A --upport eb -d RI2B2E --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u C7F181 --uprev A --upport nb -d RI2B2N --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u RI2B2E --uprev A --upport b -d PAM75155 --dnrev B --dnport ea --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u RI2B2N --uprev A --upport b -d PAM75155 --dnrev B --dnport na --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u PAM75155 --uprev B --upport eb -d RO2B2E --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u PAM75155 --uprev B --upport nb -d RO2B2N --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u HH182 --uprev A --upport ground -d A182 --dnrev H --dnport ground --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u A182 --uprev H --upport focus -d FDA71 --dnrev B --dnport input --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u FDA71 --uprev B --upport terminals -d FEM75043 --dnrev A --dnport input --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u FEM75043 --uprev A --upport e -d C7F182 --dnrev A --dnport ea --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u FEM75043 --uprev A --upport n -d C7F182 --dnrev A --dnport na --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u C7F182 --uprev A --upport eb -d RI2B3E --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u C7F182 --uprev A --upport nb -d RI2B3N --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u RI2B3E --uprev A --upport b -d PAM75154 --dnrev B --dnport ea --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u RI2B3N --uprev A --upport b -d PAM75154 --dnrev B --dnport na --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u PAM75154 --uprev B --upport eb -d RO2B3E --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u PAM75154 --uprev B --upport nb -d RO2B3N --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u HH183 --uprev A --upport ground -d A183 --dnrev H --dnport ground --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u A183 --uprev H --upport focus -d FDA73 --dnrev B --dnport input --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u FDA73 --uprev B --upport terminals -d FEM75047 --dnrev A --dnport input --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u FEM75047 --uprev A --upport e -d C7F183 --dnrev A --dnport ea --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u FEM75047 --uprev A --upport n -d C7F183 --dnrev A --dnport na --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u C7F183 --uprev A --upport eb -d RI2B4E --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u C7F183 --uprev A --upport nb -d RI2B4N --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u RI2B4E --uprev A --upport b -d PAM75153 --dnrev B --dnport ea --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u RI2B4N --uprev A --upport b -d PAM75153 --dnrev B --dnport na --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u PAM75153 --uprev B --upport eb -d RO2B4E --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
add_connection.py -u PAM75153 --uprev B --upport nb -d RO2B4N --dnrev A --dnport a --date 2018/03/26 --time 12:00 --actually_do_it
