#! /usr/bin/env bash
echo 180521_add_sigpath_A12 >> scripts.log
add_part.py -p FDV3 -r A -t feed -m MIT3 --date 2018/05/21 --time 11:00 --actually_do_it
add_part.py -p FEM02 -r A -t fem -m FEMxxx02 --date 2018/05/21 --time 11:00 --actually_do_it
add_part.py -p CRF012 -r A -t cable-rfof -m orangegray --date 2018/05/21 --time 11:00 --actually_do_it
add_connection.py -u A12 --uprev H --upport focus -d FDV3 --dnrev A --dnport input --date 2018/05/21 --time 12:00 --actually_do_it
add_connection.py -u FDV3 --uprev A --upport terminals -d FEM02 --dnrev A --dnport input --date 2018/05/21 --time 12:00 --actually_do_it
add_connection.py -u FEM02 --uprev A --upport e -d CRF012 --dnrev A --dnport ea --date 2018/05/21 --time 12:00 --actually_do_it
add_connection.py -u FEM02 --uprev A --upport n -d CRF012 --dnrev A --dnport na --date 2018/05/21 --time 12:00 --actually_do_it
add_connection.py -u CRF012 --uprev A --upport eb -d PAM05 --dnrev A --dnport ea --date 2018/05/21 --time 12:00 --actually_do_it
add_connection.py -u CRF012 --uprev A --upport nb -d PAM05 --dnrev A --dnport na --date 2018/05/21 --time 12:00 --actually_do_it
add_connection.py -u PAM05 --uprev A --upport eb -d SNP1 --dnrev A --dnport e3 --date 2018/05/21 --time 12:00 --actually_do_it
add_connection.py -u PAM05 --uprev A --upport nb -d SNP1 --dnrev A --dnport n3 --date 2018/05/21 --time 12:00 --actually_do_it
