#! /usr/bin/env bash
echo 180813_node0_contents >> scripts.log
add_part.py -p PCH1 -r A -t pam-chassis -m PCH1 --date 2018/07/18 --time 11:00 --actually_do_it
add_part.py -p SNP023 -r A -t snap -m SNP023 --date 2018/07/18 --time 11:00 --actually_do_it
add_part.py -p SNP008 -r A -t snap -m SNP008 --date 2018/07/18 --time 11:00 --actually_do_it
add_part.py -p FPS1 -r A -t fem-power-supply -m FPS1 --date 2018/07/18 --time 11:00 --actually_do_it
add_part.py -p SNP024 -r A -t snap -m SNP024 --date 2018/07/18 --time 11:00 --actually_do_it
add_part.py -p N0 -r A -t node -m N0 --date 2018/07/18 --time 11:00 --actually_do_it
add_part.py -p NCM1 -r A -t node-control-module -m NCM1 --date 2018/07/18 --time 11:00 --actually_do_it
add_part.py -p PAM75194 -r A -t post-amp -m PAM75194 --date 2018/07/18 --time 11:00 --actually_do_it
add_part.py -p PAM75195 -r A -t post-amp -m PAM75195 --date 2018/07/18 --time 11:00 --actually_do_it
add_part.py -p PAM75196 -r A -t post-amp -m PAM75196 --date 2018/07/18 --time 11:00 --actually_do_it
add_part.py -p PAM75191 -r A -t post-amp -m PAM75191 --date 2018/07/18 --time 11:00 --actually_do_it
add_part.py -p PAM75192 -r A -t post-amp -m PAM75192 --date 2018/07/18 --time 11:00 --actually_do_it
add_part.py -p PAM75193 -r A -t post-amp -m PAM75193 --date 2018/07/18 --time 11:00 --actually_do_it
add_connection.py -u PCH1 --uprev A --upport @rack -d N0 --dnrev A --dnport @loc0 --date 2018/07/18 --time 12:00 --actually_do_it
add_connection.py -u SNP023 --uprev A --upport rack -d N0 --dnrev A --dnport loc3 --date 2018/07/18 --time 12:00 --actually_do_it
add_connection.py -u SNP008 --uprev A --upport rack -d N0 --dnrev A --dnport loc1 --date 2018/07/18 --time 12:00 --actually_do_it
add_connection.py -u FPS1 --uprev A --upport @rack -d N0 --dnrev A --dnport @loc6 --date 2018/07/18 --time 12:00 --actually_do_it
add_connection.py -u SNP024 --uprev A --upport rack -d N0 --dnrev A --dnport loc2 --date 2018/07/18 --time 12:00 --actually_do_it
add_connection.py -u N0 --uprev A --upport @ground -d ND0 --dnrev A --dnport @ground --date 2018/07/18 --time 12:00 --actually_do_it
add_connection.py -u NCM1 --uprev A --upport @rack -d N0 --dnrev A --dnport @loc5 --date 2018/07/18 --time 12:00 --actually_do_it
add_connection.py -u PAM75194 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot03 --date 2018/07/18 --time 12:00 --actually_do_it
add_connection.py -u PAM75195 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot05 --date 2018/07/18 --time 12:00 --actually_do_it
add_connection.py -u PAM75196 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot06 --date 2018/07/18 --time 12:00 --actually_do_it
add_connection.py -u PAM75191 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot07 --date 2018/07/18 --time 12:00 --actually_do_it
add_connection.py -u PAM75192 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot01 --date 2018/07/18 --time 12:00 --actually_do_it
add_connection.py -u PAM75193 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot02 --date 2018/07/18 --time 12:00 --actually_do_it
