#! /usr/bin/env bash
echo 180921_update_sys >> scripts.log
stop_connection.py -u PAM75191 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot07 --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u PAM75192 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot01 --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u PAM75193 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot02 --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u PAM75194 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot03 --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u PAM75195 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot05 --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u PAM75195 --uprev A --upport eb -d SNP008 --dnrev A --dnport e6 --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u PAM75195 --uprev A --upport nb -d SNP008 --dnrev A --dnport n4 --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u PAM75196 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot06 --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u PAM75196 --uprev A --upport eb -d SNP008 --dnrev A --dnport e2 --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u PAM75196 --uprev A --upport nb -d SNP008 --dnrev A --dnport n0 --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u SNP008 --uprev A --upport rack -d N0 --dnrev A --dnport loc1 --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u SNP023 --uprev A --upport rack -d N0 --dnrev A --dnport loc3 --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u SNP024 --uprev A --upport rack -d N0 --dnrev A --dnport loc2 --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u FEM06 --uprev A --upport e -d CRF000 --dnrev A --dnport ea --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u FEM06 --uprev A --upport n -d CRF000 --dnrev A --dnport na --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u FDV1 --uprev A --upport terminals -d FEM06 --dnrev A --dnport input --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u FDV2 --uprev A --upport terminals -d FEM04 --dnrev A --dnport input --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u CRF000 --uprev A --upport eb -d PAM75196 --dnrev A --dnport ea --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u CRF000 --uprev A --upport nb -d PAM75196 --dnrev A --dnport na --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u FEM04 --uprev A --upport e -d CRF001 --dnrev A --dnport ea --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u FEM04 --uprev A --upport n -d CRF001 --dnrev A --dnport na --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u CRF001 --uprev A --upport eb -d PAM75195 --dnrev A --dnport ea --date 2018/09/19 --time 10:00 --actually_do_it
stop_connection.py -u CRF001 --uprev A --upport nb -d PAM75195 --dnrev A --dnport na --date 2018/09/19 --time 10:00 --actually_do_it
stop_part.py -p FEM06 -r A --date 2018/09/19 --time 10:10 --actually_do_it
stop_part.py -p FEM04 -r A --date 2018/09/19 --time 10:10 --actually_do_it
stop_part.py -p SNP008 -r A --date 2018/09/19 --time 10:10 --actually_do_it
stop_part.py -p SNP023 -r A --date 2018/09/19 --time 10:10 --actually_do_it
stop_part.py -p SNP024 -r A --date 2018/09/19 --time 10:10 --actually_do_it
add_part.py -p FEM96 -r A -t front-end -m FEMxxx96 --date 2018/09/19 --time 10:20 --actually_do_it
add_part.py -p FEM92 -r A -t front-end -m FEMxxx92 --date 2018/09/19 --time 10:20 --actually_do_it
add_part.py -p SNPA000024 -r A -t snap -m A000024 --date 2018/09/19 --time 10:20 --actually_do_it
add_part.py -p SNPA000022 -r A -t snap -m A000022 --date 2018/09/19 --time 10:20 --actually_do_it
add_part.py -p SNPA000008 -r A -t snap -m A000008 --date 2018/09/19 --time 10:20 --actually_do_it
add_part.py -p PAM75199 -r A -t post-amp -m PAM75199 --date 2018/09/19 --time 10:20 --actually_do_it
add_connection.py -u PAM75196 --uprev A --upport @slot -d PCH1 --dnrev A --dnport @slot02 --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u PAM75196 --uprev A --upport eb -d SNPA000022 --dnrev A --dnport e6 --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u PAM75196 --uprev A --upport nb -d SNPA000022 --dnrev A --dnport n4 --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u FDV1 --uprev A --upport terminals -d FEM96 --dnrev A --dnport input --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u FEM96 --uprev A --upport e -d CRF000 --dnrev A --dnport ea --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u FEM96 --uprev A --upport n -d CRF000 --dnrev A --dnport na --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u CRF000 --uprev A --upport eb -d PAM75199 --dnrev A --dnport ea --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u CRF000 --uprev A --upport nb -d PAM75199 --dnrev A --dnport na --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u PAM75199 --uprev A --upport eb -d SNPA000022 --dnrev A --dnport e2 --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u PAM75199 --uprev A --upport nb -d SNPA000022 --dnrev A --dnport n0 --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u SNPA000022 --uprev A --upport rack -d N0 --dnrev A --dnport loc1 --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u FDV2 --uprev A --upport terminals -d FEM92 --dnrev A --dnport input --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u FEM92 --uprev A --upport e -d CRF001 --dnrev A --dnport ea --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u FEM92 --uprev A --upport n -d CRF001 --dnrev A --dnport na --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u CRF001 --uprev A --upport eb -d PAM75196 --dnrev A --dnport ea --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u CRF001 --uprev A --upport nb -d PAM75196 --dnrev A --dnport na --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u PAM75196 --uprev A --upport eb -d SNPA000022 --dnrev A --dnport e6 --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u PAM75196 --uprev A --upport nb -d SNPA000022 --dnrev A --dnport n4 --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u SNPA000024 --uprev A --upport rack -d N0 --dnrev A --dnport loc2 --date 2018/09/19 --time 10:30 --actually_do_it
add_connection.py -u SNPA000008 --uprev A --upport rack -d N0 --dnrev A --dnport loc3 --date 2018/09/19 --time 10:30 --actually_do_it
