#! /usr/bin/env bash
echo 190126_add_stations >> scripts.log
add_station.py HH297 --sernum 202 --date 2018/12/13 --time 10:00
add_station.py HH298 --sernum 203 --date 2018/12/13 --time 10:00
add_station.py HH299 --sernum 204 --date 2018/12/13 --time 10:00
add_station.py HH309 --sernum 205 --date 2018/12/13 --time 10:00
add_station.py HH286 --sernum 206 --date 2018/12/13 --time 10:00
add_station.py HH311 --sernum 207 --date 2018/12/13 --time 10:00
add_part.py -p A297 -r H -t antenna -m S/N202 --date 2018/12/13 --time 10:00 --actually_do_it
add_part.py -p A298 -r H -t antenna -m S/N203 --date 2018/12/13 --time 10:00 --actually_do_it
add_part.py -p A299 -r H -t antenna -m S/N204 --date 2018/12/13 --time 10:00 --actually_do_it
add_part.py -p A309 -r H -t antenna -m S/N205 --date 2018/12/13 --time 10:00 --actually_do_it
add_part.py -p A286 -r H -t antenna -m S/N206 --date 2018/12/13 --time 10:00 --actually_do_it
add_part.py -p A311 -r H -t antenna -m S/N207 --date 2018/12/13 --time 10:00 --actually_do_it
add_connection.py -u HH297 --uprev A --upport ground -d A297 --dnrev H --dnport ground --date 2018/12/13 --time 12:00 --actually_do_it
add_connection.py -u HH298 --uprev A --upport ground -d A298 --dnrev H --dnport ground --date 2018/12/13 --time 12:00 --actually_do_it
add_connection.py -u HH299 --uprev A --upport ground -d A299 --dnrev H --dnport ground --date 2018/12/13 --time 12:00 --actually_do_it
add_connection.py -u HH309 --uprev A --upport ground -d A309 --dnrev H --dnport ground --date 2018/12/13 --time 12:00 --actually_do_it
add_connection.py -u HH286 --uprev A --upport ground -d A286 --dnrev H --dnport ground --date 2018/12/13 --time 12:00 --actually_do_it
add_connection.py -u HH311 --uprev A --upport ground -d A311 --dnrev H --dnport ground --date 2018/12/13 --time 12:00 --actually_do_it
