#! /usr/bin/env bash
echo 190223_update (do_it = True) >> scripts.log 
stop_connection.py -u CRF014 --uprev A --upport eb -d PAM028 --dnrev A --dnport ea --date 2019/02/23 --time 10:00 --actually_do_it
stop_connection.py -u CRF014 --uprev A --upport nb -d PAM028 --dnrev A --dnport na --date 2019/02/23 --time 10:00 --actually_do_it
stop_connection.py -u PAM028 --uprev A --upport eb -d SNPA000024 --dnrev A --dnport e2 --date 2019/02/23 --time 10:00 --actually_do_it
stop_connection.py -u PAM028 --uprev A --upport nb -d SNPA000024 --dnrev A --dnport n0 --date 2019/02/23 --time 10:00 --actually_do_it
stop_part.py -p PAM028 -r A --date 2019/02/23 --time 10:10 --actually_do_it
