#! /usr/bin/env bash
echo 190206_connect_feeds >> scripts.log
add_connection.py -u A2 --uprev H --upport focus -d FDV8 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A11 --uprev H --upport focus -d FDV9 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A23 --uprev H --upport focus -d FDV11 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A24 --uprev H --upport focus -d FDV12 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A39 --uprev H --upport focus -d FDV14 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A88 --uprev H --upport focus -d FDV15 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A89 --uprev H --upport focus -d FDV16 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A90 --uprev H --upport focus -d FDV17 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A91 --uprev H --upport focus -d FDV18 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A104 --uprev H --upport focus -d FDV10 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A105 --uprev H --upport focus -d FDV19 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A106 --uprev H --upport focus -d FDV20 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A107 --uprev H --upport focus -d FDV21 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A108 --uprev H --upport focus -d FDV22 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A123 --uprev H --upport focus -d FDV23 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A124 --uprev H --upport focus -d FDV24 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A125 --uprev H --upport focus -d FDV25 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
add_connection.py -u A126 --uprev H --upport focus -d FDV13 --dnrev A --dnport input --date 2019/02/01 --time 12:00 --actually_do_it
