#! /usr/bin/env bash
echo "190513_cavendish (do_it = True)" >> scripts.log 
stop_connection.py -u FDV8 --uprev A --upport terminals -d FEM017 --dnrev A --dnport input --date 2019/05/13 --time 10:00 --actually_do_it
stop_connection.py -u FEM017 --uprev A --upport e -d CRF002 --dnrev A --dnport ea --date 2019/05/13 --time 10:10 --actually_do_it
stop_connection.py -u FEM017 --uprev A --upport n -d CRF002 --dnrev A --dnport na --date 2019/05/13 --time 10:10 --actually_do_it
stop_connection.py -u FDV3 --uprev A --upport terminals -d FEM020 --dnrev A --dnport input --date 2019/05/13 --time 10:20 --actually_do_it
stop_connection.py -u FEM020 --uprev A --upport e -d CRF012 --dnrev A --dnport ea --date 2019/05/13 --time 10:30 --actually_do_it
stop_connection.py -u FEM020 --uprev A --upport n -d CRF012 --dnrev A --dnport na --date 2019/05/13 --time 10:30 --actually_do_it
stop_connection.py -u FDV12 --uprev A --upport terminals -d FEM024 --dnrev A --dnport input --date 2019/05/13 --time 10:40 --actually_do_it
stop_connection.py -u FEM024 --uprev A --upport e -d CRF024 --dnrev A --dnport ea --date 2019/05/13 --time 10:50 --actually_do_it
stop_connection.py -u FEM024 --uprev A --upport n -d CRF024 --dnrev A --dnport na --date 2019/05/13 --time 10:50 --actually_do_it
add_part.py -p FEM040 -r A -t front-end -m 040 --date 2019/05/13 --time 11:00 --actually_do_it
add_part.py -p FEM041 -r A -t front-end -m 041 --date 2019/05/13 --time 11:00 --actually_do_it
add_part.py -p FEM043 -r A -t front-end -m 043 --date 2019/05/13 --time 11:00 --actually_do_it
add_connection.py -u FDV8 --uprev A --upport terminals -d FEM040 --dnrev A --dnport input --date 2019/05/13 --time 11:10 --actually_do_it
add_connection.py -u FEM040 --uprev A --upport e -d CRF002 --dnrev A --dnport ea --date 2019/05/13 --time 11:20 --actually_do_it
add_connection.py -u FEM040 --uprev A --upport n -d CRF002 --dnrev A --dnport na --date 2019/05/13 --time 11:20 --actually_do_it
add_connection.py -u FDV3 --uprev A --upport terminals -d FEM041 --dnrev A --dnport input --date 2019/05/13 --time 11:30 --actually_do_it
add_connection.py -u FEM041 --uprev A --upport e -d CRF012 --dnrev A --dnport ea --date 2019/05/13 --time 11:40 --actually_do_it
add_connection.py -u FEM041 --uprev A --upport n -d CRF012 --dnrev A --dnport na --date 2019/05/13 --time 11:40 --actually_do_it
add_connection.py -u FDV12 --uprev A --upport terminals -d FEM043 --dnrev A --dnport input --date 2019/05/13 --time 11:50 --actually_do_it
add_connection.py -u FEM043 --uprev A --upport e -d CRF024 --dnrev A --dnport ea --date 2019/05/13 --time 12:00 --actually_do_it
add_connection.py -u FEM043 --uprev A --upport n -d CRF024 --dnrev A --dnport na --date 2019/05/13 --time 12:00 --actually_do_it
