#! /usr/bin/env bash
echo "190514_fix_pam47 (do_it = True)" >> scripts.log 
stop_connection.py -u PAM047 --uprev A --upport nb -d SNPA000024 --dnrev A --dnport n4 --date 2019/05/12 --time 11:30 --actually_do_it
add_connection.py -u PAM047 --uprev A --upport nb -d SNPA000024 --dnrev A --dnport n0 --date 2019/05/12 --time 11:30 --actually_do_it
