#! /usr/bin/env bash
echo "190802_add_nodes7_8" >> scripts.log 
add_station.py ND07 --sernum ND07 --date 2019/08/02 --time 10:00
add_part.py -p FPS05 -r A -t fem-power-supply -m FPS05 --date 2019/08/02 --time 10:00
add_part.py -p PCH04 -r A -t pam-chassis -m PCH04 --date 2019/08/02 --time 10:00
add_part.py -p NCMPre2 -r A -t node-control-module -m NCMPre2 --date 2019/08/02 --time 10:00
add_part.py -p N07 -r A -t node -m 3 --date 2019/08/02 --time 10:00
add_part.py -p NBP07 -r A -t node-bulkhead -m NBP07 --date 2019/08/02 --time 10:00
add_part.py -p PAM053 -r A -t post-amp -m 053 --date 2019/08/02 --time 10:00
add_part.py -p PAM054 -r A -t post-amp -m 054 --date 2019/08/02 --time 10:00
add_part.py -p PAM055 -r A -t post-amp -m 055 --date 2019/08/02 --time 10:00
add_part.py -p PAM056 -r A -t post-amp -m 056 --date 2019/08/02 --time 10:00
add_part.py -p PAM057 -r A -t post-amp -m 057 --date 2019/08/02 --time 10:00
add_part.py -p PAM058 -r A -t post-amp -m 058 --date 2019/08/02 --time 10:00
add_part.py -p PAM059 -r A -t post-amp -m 059 --date 2019/08/02 --time 10:00
add_part.py -p PAM060 -r A -t post-amp -m 060 --date 2019/08/02 --time 10:00
add_part.py -p PAM061 -r A -t post-amp -m 061 --date 2019/08/02 --time 10:00
add_part.py -p PAM062 -r A -t post-amp -m 062 --date 2019/08/02 --time 10:00
add_part.py -p PAM063 -r A -t post-amp -m 063 --date 2019/08/02 --time 10:00
add_part.py -p PAM049 -r A -t post-amp -m 049 --date 2019/08/02 --time 10:00
add_part.py -p SNPC000019 -r A -t snap -m C000019 --date 2019/08/02 --time 10:00
add_part.py -p SNPC000021 -r A -t snap -m C000021 --date 2019/08/02 --time 10:00
add_part.py -p SNPC000030 -r A -t snap -m C000030 --date 2019/08/02 --time 10:00
add_part.py -p SNPC000031 -r A -t snap -m C000031 --date 2019/08/02 --time 10:00
add_connection.py -u N07 --uprev A --upport @ground -d ND07 --dnrev A --dnport @ground --date 2019/08/02 --time 11:00
add_connection.py -u FPS05 --uprev A --upport @rack -d N07 --dnrev A --dnport @top --date 2019/08/02 --time 11:00
add_connection.py -u PCH04 --uprev A --upport @rack -d N07 --dnrev A --dnport @bottom --date 2019/08/02 --time 11:00
add_connection.py -u NCMPre2 --uprev A --upport @rack -d N07 --dnrev A --dnport @middle --date 2019/08/02 --time 11:00
add_connection.py -u PAM053 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot1 --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport e1 -d PAM053 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport n1 -d PAM053 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM054 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot2 --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport e2 -d PAM054 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport n2 -d PAM054 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM055 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot3 --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport e3 -d PAM055 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport n3 -d PAM055 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM056 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot4 --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport e4 -d PAM056 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport n4 -d PAM056 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM057 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot5 --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport e5 -d PAM057 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport n5 -d PAM057 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM058 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot6 --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport e6 -d PAM058 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport n6 -d PAM058 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM059 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot7 --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport e7 -d PAM059 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport n7 -d PAM059 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM060 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot8 --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport e8 -d PAM060 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport n8 -d PAM060 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM061 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot9 --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport e9 -d PAM061 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport n9 -d PAM061 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM062 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot10 --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport e10 -d PAM062 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport n10 -d PAM062 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM063 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot11 --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport e11 -d PAM063 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport n11 -d PAM063 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM049 --uprev A --upport @slot -d PCH04 --dnrev A --dnport @slot12 --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport e12 -d PAM049 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP07 --uprev A --upport n12 -d PAM049 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u SNPC000019 --uprev A --upport @rack -d N07 --dnrev A --dnport @loc0 --date 2019/08/02 --time 11:00
add_connection.py -u PAM053 --uprev A --upport e -d SNPC000019 --dnrev A --dnport e2 --date 2019/08/02 --time 11:00
add_connection.py -u PAM054 --uprev A --upport e -d SNPC000019 --dnrev A --dnport e6 --date 2019/08/02 --time 11:00
add_connection.py -u PAM055 --uprev A --upport e -d SNPC000019 --dnrev A --dnport e10 --date 2019/08/02 --time 11:00
add_connection.py -u PAM053 --uprev A --upport n -d SNPC000019 --dnrev A --dnport n0 --date 2019/08/02 --time 11:00
add_connection.py -u PAM054 --uprev A --upport n -d SNPC000019 --dnrev A --dnport n4 --date 2019/08/02 --time 11:00
add_connection.py -u PAM055 --uprev A --upport n -d SNPC000019 --dnrev A --dnport n8 --date 2019/08/02 --time 11:00
add_connection.py -u SNPC000021 --uprev A --upport @rack -d N07 --dnrev A --dnport @loc1 --date 2019/08/02 --time 11:00
add_connection.py -u PAM056 --uprev A --upport e -d SNPC000021 --dnrev A --dnport e2 --date 2019/08/02 --time 11:00
add_connection.py -u PAM057 --uprev A --upport e -d SNPC000021 --dnrev A --dnport e6 --date 2019/08/02 --time 11:00
add_connection.py -u PAM058 --uprev A --upport e -d SNPC000021 --dnrev A --dnport e10 --date 2019/08/02 --time 11:00
add_connection.py -u PAM056 --uprev A --upport n -d SNPC000021 --dnrev A --dnport n0 --date 2019/08/02 --time 11:00
add_connection.py -u PAM057 --uprev A --upport n -d SNPC000021 --dnrev A --dnport n4 --date 2019/08/02 --time 11:00
add_connection.py -u PAM058 --uprev A --upport n -d SNPC000021 --dnrev A --dnport n8 --date 2019/08/02 --time 11:00
add_connection.py -u SNPC000030 --uprev A --upport @rack -d N07 --dnrev A --dnport @loc2 --date 2019/08/02 --time 11:00
add_connection.py -u PAM059 --uprev A --upport e -d SNPC000030 --dnrev A --dnport e2 --date 2019/08/02 --time 11:00
add_connection.py -u PAM060 --uprev A --upport e -d SNPC000030 --dnrev A --dnport e6 --date 2019/08/02 --time 11:00
add_connection.py -u PAM061 --uprev A --upport e -d SNPC000030 --dnrev A --dnport e10 --date 2019/08/02 --time 11:00
add_connection.py -u PAM059 --uprev A --upport n -d SNPC000030 --dnrev A --dnport n0 --date 2019/08/02 --time 11:00
add_connection.py -u PAM060 --uprev A --upport n -d SNPC000030 --dnrev A --dnport n4 --date 2019/08/02 --time 11:00
add_connection.py -u PAM061 --uprev A --upport n -d SNPC000030 --dnrev A --dnport n8 --date 2019/08/02 --time 11:00
add_connection.py -u SNPC000031 --uprev A --upport @rack -d N07 --dnrev A --dnport @loc3 --date 2019/08/02 --time 11:00
add_connection.py -u PAM062 --uprev A --upport e -d SNPC000031 --dnrev A --dnport e2 --date 2019/08/02 --time 11:00
add_connection.py -u PAM063 --uprev A --upport e -d SNPC000031 --dnrev A --dnport e6 --date 2019/08/02 --time 11:00
add_connection.py -u PAM049 --uprev A --upport e -d SNPC000031 --dnrev A --dnport e10 --date 2019/08/02 --time 11:00
add_connection.py -u PAM062 --uprev A --upport n -d SNPC000031 --dnrev A --dnport n0 --date 2019/08/02 --time 11:00
add_connection.py -u PAM063 --uprev A --upport n -d SNPC000031 --dnrev A --dnport n4 --date 2019/08/02 --time 11:00
add_connection.py -u PAM049 --uprev A --upport n -d SNPC000031 --dnrev A --dnport n8 --date 2019/08/02 --time 11:00
add_station.py ND08 --sernum ND08 --date 2019/08/02 --time 10:00
add_part.py -p FPS04 -r A -t fem-power-supply -m FPS04 --date 2019/08/02 --time 10:00
add_part.py -p PCH03 -r A -t pam-chassis -m PCH03 --date 2019/08/02 --time 10:00
add_part.py -p NCMPro1 -r A -t node-control-module -m NCMPro1 --date 2019/08/02 --time 10:00
add_part.py -p N08 -r A -t node -m 2 --date 2019/08/02 --time 10:00
add_part.py -p NBP08 -r A -t node-bulkhead -m NBP08 --date 2019/08/02 --time 10:00
add_part.py -p PAM010 -r A -t post-amp -m 010 --date 2019/08/02 --time 10:00
add_part.py -p PAM011 -r A -t post-amp -m 011 --date 2019/08/02 --time 10:00
add_part.py -p PAM012 -r A -t post-amp -m 012 --date 2019/08/02 --time 10:00
add_part.py -p PAM013 -r A -t post-amp -m 013 --date 2019/08/02 --time 10:00
add_part.py -p PAM014 -r A -t post-amp -m 014 --date 2019/08/02 --time 10:00
add_part.py -p PAM015 -r A -t post-amp -m 015 --date 2019/08/02 --time 10:00
add_part.py -p PAM016 -r A -t post-amp -m 016 --date 2019/08/02 --time 10:00
add_part.py -p PAM017 -r A -t post-amp -m 017 --date 2019/08/02 --time 10:00
add_part.py -p PAM018 -r A -t post-amp -m 018 --date 2019/08/02 --time 10:00
add_part.py -p PAM019 -r A -t post-amp -m 019 --date 2019/08/02 --time 10:00
add_part.py -p PAM020 -r A -t post-amp -m 020 --date 2019/08/02 --time 10:00
add_part.py -p PAM021 -r A -t post-amp -m 021 --date 2019/08/02 --time 10:00
add_part.py -p SNPC000023 -r A -t snap -m C000023 --date 2019/08/02 --time 10:00
add_part.py -p SNPC000044 -r A -t snap -m C000044 --date 2019/08/02 --time 10:00
add_part.py -p SNPC000055 -r A -t snap -m C000055 --date 2019/08/02 --time 10:00
add_part.py -p SNPC000056 -r A -t snap -m C000056 --date 2019/08/02 --time 10:00
add_connection.py -u N08 --uprev A --upport @ground -d ND08 --dnrev A --dnport @ground --date 2019/08/02 --time 11:00
add_connection.py -u FPS04 --uprev A --upport @rack -d N08 --dnrev A --dnport @top --date 2019/08/02 --time 11:00
add_connection.py -u PCH03 --uprev A --upport @rack -d N08 --dnrev A --dnport @bottom --date 2019/08/02 --time 11:00
add_connection.py -u NCMPro1 --uprev A --upport @rack -d N08 --dnrev A --dnport @middle --date 2019/08/02 --time 11:00
add_connection.py -u PAM010 --uprev A --upport @slot -d PCH03 --dnrev A --dnport @slot1 --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport e1 -d PAM010 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport n1 -d PAM010 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM011 --uprev A --upport @slot -d PCH03 --dnrev A --dnport @slot2 --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport e2 -d PAM011 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport n2 -d PAM011 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM012 --uprev A --upport @slot -d PCH03 --dnrev A --dnport @slot3 --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport e3 -d PAM012 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport n3 -d PAM012 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM013 --uprev A --upport @slot -d PCH03 --dnrev A --dnport @slot4 --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport e4 -d PAM013 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport n4 -d PAM013 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM014 --uprev A --upport @slot -d PCH03 --dnrev A --dnport @slot5 --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport e5 -d PAM014 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport n5 -d PAM014 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM015 --uprev A --upport @slot -d PCH03 --dnrev A --dnport @slot6 --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport e6 -d PAM015 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport n6 -d PAM015 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM016 --uprev A --upport @slot -d PCH03 --dnrev A --dnport @slot7 --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport e7 -d PAM016 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport n7 -d PAM016 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM017 --uprev A --upport @slot -d PCH03 --dnrev A --dnport @slot8 --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport e8 -d PAM017 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport n8 -d PAM017 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM018 --uprev A --upport @slot -d PCH03 --dnrev A --dnport @slot9 --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport e9 -d PAM018 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport n9 -d PAM018 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM019 --uprev A --upport @slot -d PCH03 --dnrev A --dnport @slot10 --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport e10 -d PAM019 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport n10 -d PAM019 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM020 --uprev A --upport @slot -d PCH03 --dnrev A --dnport @slot11 --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport e11 -d PAM020 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport n11 -d PAM020 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u PAM021 --uprev A --upport @slot -d PCH03 --dnrev A --dnport @slot12 --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport e12 -d PAM021 --dnrev A --dnport e --date 2019/08/02 --time 11:00
add_connection.py -u NBP08 --uprev A --upport n12 -d PAM021 --dnrev A --dnport n --date 2019/08/02 --time 11:00
add_connection.py -u SNPC000023 --uprev A --upport @rack -d N08 --dnrev A --dnport @loc0 --date 2019/08/02 --time 11:00
add_connection.py -u PAM010 --uprev A --upport e -d SNPC000023 --dnrev A --dnport e2 --date 2019/08/02 --time 11:00
add_connection.py -u PAM011 --uprev A --upport e -d SNPC000023 --dnrev A --dnport e6 --date 2019/08/02 --time 11:00
add_connection.py -u PAM012 --uprev A --upport e -d SNPC000023 --dnrev A --dnport e10 --date 2019/08/02 --time 11:00
add_connection.py -u PAM010 --uprev A --upport n -d SNPC000023 --dnrev A --dnport n0 --date 2019/08/02 --time 11:00
add_connection.py -u PAM011 --uprev A --upport n -d SNPC000023 --dnrev A --dnport n4 --date 2019/08/02 --time 11:00
add_connection.py -u PAM012 --uprev A --upport n -d SNPC000023 --dnrev A --dnport n8 --date 2019/08/02 --time 11:00
add_connection.py -u SNPC000044 --uprev A --upport @rack -d N08 --dnrev A --dnport @loc1 --date 2019/08/02 --time 11:00
add_connection.py -u PAM013 --uprev A --upport e -d SNPC000044 --dnrev A --dnport e2 --date 2019/08/02 --time 11:00
add_connection.py -u PAM014 --uprev A --upport e -d SNPC000044 --dnrev A --dnport e6 --date 2019/08/02 --time 11:00
add_connection.py -u PAM015 --uprev A --upport e -d SNPC000044 --dnrev A --dnport e10 --date 2019/08/02 --time 11:00
add_connection.py -u PAM013 --uprev A --upport n -d SNPC000044 --dnrev A --dnport n0 --date 2019/08/02 --time 11:00
add_connection.py -u PAM014 --uprev A --upport n -d SNPC000044 --dnrev A --dnport n4 --date 2019/08/02 --time 11:00
add_connection.py -u PAM015 --uprev A --upport n -d SNPC000044 --dnrev A --dnport n8 --date 2019/08/02 --time 11:00
add_connection.py -u SNPC000055 --uprev A --upport @rack -d N08 --dnrev A --dnport @loc2 --date 2019/08/02 --time 11:00
add_connection.py -u PAM016 --uprev A --upport e -d SNPC000055 --dnrev A --dnport e2 --date 2019/08/02 --time 11:00
add_connection.py -u PAM017 --uprev A --upport e -d SNPC000055 --dnrev A --dnport e6 --date 2019/08/02 --time 11:00
add_connection.py -u PAM018 --uprev A --upport e -d SNPC000055 --dnrev A --dnport e10 --date 2019/08/02 --time 11:00
add_connection.py -u PAM016 --uprev A --upport n -d SNPC000055 --dnrev A --dnport n0 --date 2019/08/02 --time 11:00
add_connection.py -u PAM017 --uprev A --upport n -d SNPC000055 --dnrev A --dnport n4 --date 2019/08/02 --time 11:00
add_connection.py -u PAM018 --uprev A --upport n -d SNPC000055 --dnrev A --dnport n8 --date 2019/08/02 --time 11:00
add_connection.py -u SNPC000056 --uprev A --upport @rack -d N08 --dnrev A --dnport @loc3 --date 2019/08/02 --time 11:00
add_connection.py -u PAM019 --uprev A --upport e -d SNPC000056 --dnrev A --dnport e2 --date 2019/08/02 --time 11:00
add_connection.py -u PAM020 --uprev A --upport e -d SNPC000056 --dnrev A --dnport e6 --date 2019/08/02 --time 11:00
add_connection.py -u PAM021 --uprev A --upport e -d SNPC000056 --dnrev A --dnport e10 --date 2019/08/02 --time 11:00
add_connection.py -u PAM019 --uprev A --upport n -d SNPC000056 --dnrev A --dnport n0 --date 2019/08/02 --time 11:00
add_connection.py -u PAM020 --uprev A --upport n -d SNPC000056 --dnrev A --dnport n4 --date 2019/08/02 --time 11:00
add_connection.py -u PAM021 --uprev A --upport n -d SNPC000056 --dnrev A --dnport n8 --date 2019/08/02 --time 11:00
