#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/250210_infoupd_0942" >> scripts.log 
add_part_info.py -p HH51 -r A -c "FEM replaced 341" -l "infoupd" --date 2025/02/10 --time 09:42:00
