#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/250208_infoupd_1242" >> scripts.log 
add_part_info.py -p HH70 -r A -c "Removed LP filter" -l "infoupd" --date 2025/02/08 --time 12:42:00
