#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/250211_connupd_2139" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u PAM113 --uprev A --upport e -d SNPC000056 --dnrev A --dnport e2 --date 2025/02/11 --time 21:33
stop_connection.py -u PAM113 --uprev A --upport n -d SNPC000056 --dnrev A --dnport n0 --date 2025/02/11 --time 21:33
stop_connection.py -u SNPC000056 --uprev A --upport rack -d N05 --dnrev A --dnport loc0 --date 2025/02/11 --time 21:33
stop_connection.py -u PAM114 --uprev A --upport e -d SNPC000056 --dnrev A --dnport e6 --date 2025/02/11 --time 21:33
stop_connection.py -u PAM114 --uprev A --upport n -d SNPC000056 --dnrev A --dnport n4 --date 2025/02/11 --time 21:33
stop_connection.py -u PAM115 --uprev A --upport e -d SNPC000056 --dnrev A --dnport e10 --date 2025/02/11 --time 21:33
stop_connection.py -u PAM115 --uprev A --upport n -d SNPC000056 --dnrev A --dnport n8 --date 2025/02/11 --time 21:33
# add parts for gsheet_not_active
add_part.py -p SNPC000109 -r A -t snap -m SNPC000109 --date 2025/02/11 --time 21:09
add_part.py -p FEM404 -r A -t front-end -m FEM404 --date 2025/02/11 --time 21:09
# add connections for gsheet_not_active
add_connection.py -u FDV219 --uprev A --upport terminals -d FEM404 --dnrev A --dnport input --date 2025/02/11 --time 21:39
add_connection.py -u FEM404 --uprev A --upport pwr -d FPS24 --dnrev A --dnport pwr9 --date 2025/02/11 --time 21:39
add_connection.py -u FEM404 --uprev A --upport e -d NBP21 --dnrev A --dnport e9 --date 2025/02/11 --time 21:39
add_connection.py -u FEM404 --uprev A --upport n -d NBP21 --dnrev A --dnport n9 --date 2025/02/11 --time 21:39
add_connection.py -u PAM113 --uprev A --upport e -d SNPC000109 --dnrev A --dnport e2 --date 2025/02/11 --time 21:39
add_connection.py -u PAM113 --uprev A --upport n -d SNPC000109 --dnrev A --dnport n0 --date 2025/02/11 --time 21:39
add_connection.py -u SNPC000109 --uprev A --upport rack -d N05 --dnrev A --dnport loc0 --date 2025/02/11 --time 21:39
add_connection.py -u PAM114 --uprev A --upport e -d SNPC000109 --dnrev A --dnport e6 --date 2025/02/11 --time 21:39
add_connection.py -u PAM114 --uprev A --upport n -d SNPC000109 --dnrev A --dnport n4 --date 2025/02/11 --time 21:39
add_connection.py -u PAM115 --uprev A --upport e -d SNPC000109 --dnrev A --dnport e10 --date 2025/02/11 --time 21:39
add_connection.py -u PAM115 --uprev A --upport n -d SNPC000109 --dnrev A --dnport n8 --date 2025/02/11 --time 21:39
