#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/250605_infoupd_1742" >> scripts.log 
add_part_info.py -p HH232 -r A -c "Ticket: Feed conduit feel out and is hanging on the cables." -l "infoupd" --date 2025/06/05 --time 17:42:00
