#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/250623_connupd_1135" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u A345 --uprev H --upport focus -d FDV305 --dnrev A --dnport input --date 2025/06/23 --time 11:29
stop_connection.py -u FDV177 --uprev A --upport terminals -d FEM194 --dnrev A --dnport input --date 2025/06/23 --time 11:29
stop_connection.py -u FEM194 --uprev A --upport pwr -d FPS21 --dnrev A --dnport pwr2 --date 2025/06/23 --time 11:29
stop_connection.py -u FEM194 --uprev A --upport e -d NBP06 --dnrev A --dnport e2 --date 2025/06/23 --time 11:29
stop_connection.py -u FEM194 --uprev A --upport n -d NBP06 --dnrev A --dnport n2 --date 2025/06/23 --time 11:29
# add connections for gsheet_not_active
add_connection.py -u A344 --uprev H --upport focus -d FDV305 --dnrev A --dnport input --date 2025/06/23 --time 11:35
add_connection.py -u FDV177 --uprev A --upport terminals -d FEM405 --dnrev A --dnport input --date 2025/06/23 --time 11:35
add_connection.py -u FEM405 --uprev A --upport pwr -d FPS21 --dnrev A --dnport pwr2 --date 2025/06/23 --time 11:35
add_connection.py -u FEM405 --uprev A --upport e -d NBP06 --dnrev A --dnport e2 --date 2025/06/23 --time 11:35
add_connection.py -u FEM405 --uprev A --upport n -d NBP06 --dnrev A --dnport n2 --date 2025/06/23 --time 11:35
