#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/250618_infoupd_1042" >> scripts.log 
add_part_info.py -p HA344 -r A -c "per ARP 23 May 2025" -l "infoupd" --date 2025/06/18 --time 10:42:00
add_part_info.py -p HA344 -r A -c "per ARP 23 May 2025" -l "infoupd" --date 2025/06/18 --time 10:42:02
