#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/250623_connupd_1235" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u A345 --uprev H --upport focus -d FDV305 --dnrev A --dnport input --date 2025/06/23 --time 12:29
stop_connection.py -u A236 --uprev H --upport focus -d FDV51 --dnrev A --dnport input --date 2025/06/23 --time 12:29
stop_connection.py -u FDV51 --uprev A --upport terminals -d FEM267 --dnrev A --dnport input --date 2025/06/23 --time 12:29
stop_connection.py -u FEM267 --uprev A --upport pwr -d FPS20 --dnrev A --dnport pwr6 --date 2025/06/23 --time 12:29
stop_connection.py -u FEM267 --uprev A --upport e -d NBP18 --dnrev A --dnport e6 --date 2025/06/23 --time 12:29
stop_connection.py -u FEM267 --uprev A --upport n -d NBP18 --dnrev A --dnport n6 --date 2025/06/23 --time 12:29
stop_connection.py -u FDV177 --uprev A --upport terminals -d FEM194 --dnrev A --dnport input --date 2025/06/23 --time 12:29
stop_connection.py -u FEM194 --uprev A --upport pwr -d FPS21 --dnrev A --dnport pwr2 --date 2025/06/23 --time 12:29
stop_connection.py -u FEM194 --uprev A --upport e -d NBP06 --dnrev A --dnport e2 --date 2025/06/23 --time 12:29
stop_connection.py -u FEM194 --uprev A --upport n -d NBP06 --dnrev A --dnport n2 --date 2025/06/23 --time 12:29
# add parts for gsheet_not_active
add_part.py -p FDV340 -r A -t feed -m FDV340 --date 2025/06/23 --time 12:05
# add connections for gsheet_not_active
add_connection.py -u A236 --uprev H --upport focus -d FDV340 --dnrev A --dnport input --date 2025/06/23 --time 12:35
add_connection.py -u A344 --uprev H --upport focus -d FDV305 --dnrev A --dnport input --date 2025/06/23 --time 12:35
add_connection.py -u FDV177 --uprev A --upport terminals -d FEM405 --dnrev A --dnport input --date 2025/06/23 --time 12:35
add_connection.py -u FEM405 --uprev A --upport pwr -d FPS21 --dnrev A --dnport pwr2 --date 2025/06/23 --time 12:35
add_connection.py -u FEM405 --uprev A --upport e -d NBP06 --dnrev A --dnport e2 --date 2025/06/23 --time 12:35
add_connection.py -u FEM405 --uprev A --upport n -d NBP06 --dnrev A --dnport n2 --date 2025/06/23 --time 12:35
