#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/250819_connupd_1135" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u A345 --uprev H --upport focus -d FDV305 --dnrev A --dnport input --date 2025/08/19 --time 11:29
stop_connection.py -u FDV282 --uprev A --upport terminals -d FEM856 --dnrev A --dnport input --date 2025/08/19 --time 11:29
stop_connection.py -u FEM856 --uprev A --upport pwr -d FPS27 --dnrev A --dnport pwr7 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM856 --uprev A --upport e -d NBP28 --dnrev A --dnport e7 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM856 --uprev A --upport n -d NBP28 --dnrev A --dnport n7 --date 2025/08/19 --time 11:29
stop_connection.py -u FDV339 --uprev A --upport terminals -d FEM857 --dnrev A --dnport input --date 2025/08/19 --time 11:29
stop_connection.py -u FEM857 --uprev A --upport pwr -d FPS27 --dnrev A --dnport pwr8 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM857 --uprev A --upport e -d NBP28 --dnrev A --dnport e8 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM857 --uprev A --upport n -d NBP28 --dnrev A --dnport n8 --date 2025/08/19 --time 11:29
stop_connection.py -u FDV330 --uprev A --upport terminals -d FEM858 --dnrev A --dnport input --date 2025/08/19 --time 11:29
stop_connection.py -u FEM858 --uprev A --upport pwr -d FPS27 --dnrev A --dnport pwr9 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM858 --uprev A --upport e -d NBP28 --dnrev A --dnport e9 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM858 --uprev A --upport n -d NBP28 --dnrev A --dnport n9 --date 2025/08/19 --time 11:29
stop_connection.py -u FDV277 --uprev A --upport terminals -d FEM859 --dnrev A --dnport input --date 2025/08/19 --time 11:29
stop_connection.py -u FEM859 --uprev A --upport pwr -d FPS27 --dnrev A --dnport pwr10 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM859 --uprev A --upport e -d NBP28 --dnrev A --dnport e10 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM859 --uprev A --upport n -d NBP28 --dnrev A --dnport n10 --date 2025/08/19 --time 11:29
stop_connection.py -u FDV286 --uprev A --upport terminals -d FEM860 --dnrev A --dnport input --date 2025/08/19 --time 11:29
stop_connection.py -u FEM860 --uprev A --upport pwr -d FPS27 --dnrev A --dnport pwr11 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM860 --uprev A --upport e -d NBP28 --dnrev A --dnport e11 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM860 --uprev A --upport n -d NBP28 --dnrev A --dnport n11 --date 2025/08/19 --time 11:29
stop_connection.py -u FDV861 --uprev A --upport terminals -d FEM861 --dnrev A --dnport input --date 2025/08/19 --time 11:29
stop_connection.py -u FEM861 --uprev A --upport pwr -d FPS27 --dnrev A --dnport pwr12 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM861 --uprev A --upport e -d NBP28 --dnrev A --dnport e12 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM861 --uprev A --upport n -d NBP28 --dnrev A --dnport n12 --date 2025/08/19 --time 11:29
stop_connection.py -u A236 --uprev H --upport focus -d FDV51 --dnrev A --dnport input --date 2025/08/19 --time 11:29
stop_connection.py -u FDV51 --uprev A --upport terminals -d FEM267 --dnrev A --dnport input --date 2025/08/19 --time 11:29
stop_connection.py -u FEM267 --uprev A --upport pwr -d FPS20 --dnrev A --dnport pwr6 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM267 --uprev A --upport e -d NBP18 --dnrev A --dnport e6 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM267 --uprev A --upport n -d NBP18 --dnrev A --dnport n6 --date 2025/08/19 --time 11:29
stop_connection.py -u FDV177 --uprev A --upport terminals -d FEM194 --dnrev A --dnport input --date 2025/08/19 --time 11:29
stop_connection.py -u FEM194 --uprev A --upport pwr -d FPS21 --dnrev A --dnport pwr2 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM194 --uprev A --upport e -d NBP06 --dnrev A --dnport e2 --date 2025/08/19 --time 11:29
stop_connection.py -u FEM194 --uprev A --upport n -d NBP06 --dnrev A --dnport n2 --date 2025/08/19 --time 11:29
# add parts for gsheet_not_active
add_part.py -p FDV340 -r A -t feed -m FDV340 --date 2025/08/19 --time 11:05
add_part.py -p FEM060 -r A -t front-end -m FEM060 --date 2025/08/19 --time 11:05
add_part.py -p FEM328 -r A -t front-end -m FEM328 --date 2025/08/19 --time 11:05
add_part.py -p FEM356 -r A -t front-end -m FEM356 --date 2025/08/19 --time 11:05
add_part.py -p FEM393 -r A -t front-end -m FEM393 --date 2025/08/19 --time 11:05
add_part.py -p FEM314 -r A -t front-end -m FEM314 --date 2025/08/19 --time 11:05
# add connections for gsheet_not_active
add_connection.py -u A236 --uprev H --upport focus -d FDV340 --dnrev A --dnport input --date 2025/08/19 --time 11:35
add_connection.py -u A344 --uprev H --upport focus -d FDV305 --dnrev A --dnport input --date 2025/08/19 --time 11:35
add_connection.py -u FDV282 --uprev A --upport terminals -d FEM314 --dnrev A --dnport input --date 2025/08/19 --time 11:35
add_connection.py -u FEM314 --uprev A --upport pwr -d FPS27 --dnrev A --dnport pwr7 --date 2025/08/19 --time 11:35
add_connection.py -u FEM314 --uprev A --upport e -d NBP28 --dnrev A --dnport e7 --date 2025/08/19 --time 11:35
add_connection.py -u FEM314 --uprev A --upport n -d NBP28 --dnrev A --dnport n7 --date 2025/08/19 --time 11:35
add_connection.py -u FDV339 --uprev A --upport terminals -d FEM328 --dnrev A --dnport input --date 2025/08/19 --time 11:35
add_connection.py -u FEM328 --uprev A --upport pwr -d FPS27 --dnrev A --dnport pwr8 --date 2025/08/19 --time 11:35
add_connection.py -u FEM328 --uprev A --upport e -d NBP28 --dnrev A --dnport e8 --date 2025/08/19 --time 11:35
add_connection.py -u FEM328 --uprev A --upport n -d NBP28 --dnrev A --dnport n8 --date 2025/08/19 --time 11:35
add_connection.py -u FDV330 --uprev A --upport terminals -d FEM393 --dnrev A --dnport input --date 2025/08/19 --time 11:35
add_connection.py -u FEM393 --uprev A --upport pwr -d FPS27 --dnrev A --dnport pwr9 --date 2025/08/19 --time 11:35
add_connection.py -u FEM393 --uprev A --upport e -d NBP28 --dnrev A --dnport e9 --date 2025/08/19 --time 11:35
add_connection.py -u FEM393 --uprev A --upport n -d NBP28 --dnrev A --dnport n9 --date 2025/08/19 --time 11:35
add_connection.py -u FDV277 --uprev A --upport terminals -d FEM060 --dnrev A --dnport input --date 2025/08/19 --time 11:35
add_connection.py -u FEM060 --uprev A --upport pwr -d FPS27 --dnrev A --dnport pwr10 --date 2025/08/19 --time 11:35
add_connection.py -u FEM060 --uprev A --upport e -d NBP28 --dnrev A --dnport e10 --date 2025/08/19 --time 11:35
add_connection.py -u FEM060 --uprev A --upport n -d NBP28 --dnrev A --dnport n10 --date 2025/08/19 --time 11:35
add_connection.py -u FDV286 --uprev A --upport terminals -d FEM051 --dnrev A --dnport input --date 2025/08/19 --time 11:35
add_connection.py -u FEM051 --uprev A --upport pwr -d FPS27 --dnrev A --dnport pwr11 --date 2025/08/19 --time 11:35
add_connection.py -u FEM051 --uprev A --upport e -d NBP28 --dnrev A --dnport e11 --date 2025/08/19 --time 11:35
add_connection.py -u FEM051 --uprev A --upport n -d NBP28 --dnrev A --dnport n11 --date 2025/08/19 --time 11:35
add_connection.py -u FDV861 --uprev A --upport terminals -d FEM356 --dnrev A --dnport input --date 2025/08/19 --time 11:35
add_connection.py -u FEM356 --uprev A --upport pwr -d FPS27 --dnrev A --dnport pwr12 --date 2025/08/19 --time 11:35
add_connection.py -u FEM356 --uprev A --upport e -d NBP28 --dnrev A --dnport e12 --date 2025/08/19 --time 11:35
add_connection.py -u FEM356 --uprev A --upport n -d NBP28 --dnrev A --dnport n12 --date 2025/08/19 --time 11:35
add_connection.py -u FDV177 --uprev A --upport terminals -d FEM405 --dnrev A --dnport input --date 2025/08/19 --time 11:35
add_connection.py -u FEM405 --uprev A --upport pwr -d FPS21 --dnrev A --dnport pwr2 --date 2025/08/19 --time 11:35
add_connection.py -u FEM405 --uprev A --upport e -d NBP06 --dnrev A --dnport e2 --date 2025/08/19 --time 11:35
add_connection.py -u FEM405 --uprev A --upport n -d NBP06 --dnrev A --dnport n2 --date 2025/08/19 --time 11:35
