#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/250822_infoupd_1642" >> scripts.log 
add_part_info.py -p HH290 -r A -c "Was FEM051 but is a duplicate to changing to FEM517" -l "infoupd" --date 2025/08/22 --time 16:42:00
add_part_info.py -p HH34 -r A -c "FEM405 was added but is duplicated, so changing to 457" -l "infoupd" --date 2025/08/22 --time 16:42:00
