#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/251110_infoupd_2342" >> scripts.log 
update_apriori.py -p HH166 -s RF_maintenance --date 2025/11/10 --time 23:48
add_part_info.py -p HH166 -r A -c "apriori_antenna status change: digital_ok > RF_maintenance" -l "apa-infoupd" --date 2025/11/10 --time 23:48
update_apriori.py -p HH184 -s digital_ok --date 2025/11/10 --time 23:48
add_part_info.py -p HH184 -r A -c "apriori_antenna status change: RF_maintenance > digital_ok" -l "apa-infoupd" --date 2025/11/10 --time 23:48
update_apriori.py -p HH185 -s RF_maintenance --date 2025/11/10 --time 23:48
add_part_info.py -p HH185 -r A -c "apriori_antenna status change: dish_maintenance > RF_maintenance" -l "apa-infoupd" --date 2025/11/10 --time 23:48
update_apriori.py -p HH186 -s dish_maintenance --date 2025/11/10 --time 23:48
add_part_info.py -p HH186 -r A -c "apriori_antenna status change: RF_maintenance > dish_maintenance" -l "apa-infoupd" --date 2025/11/10 --time 23:48
add_part_info.py -p HH71 -r A -c "Removed LP filter" -l "infoupd" --date 2025/11/10 --time 23:42:00
