#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/240131_connupd_0403" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u PAM113 --uprev A --upport e -d SNPC000058 --dnrev A --dnport e2 --date 2024/01/31 --time 03:57
stop_connection.py -u PAM113 --uprev A --upport n -d SNPC000058 --dnrev A --dnport n0 --date 2024/01/31 --time 03:57
stop_connection.py -u PAM114 --uprev A --upport e -d SNPC000058 --dnrev A --dnport e6 --date 2024/01/31 --time 03:57
stop_connection.py -u PAM114 --uprev A --upport n -d SNPC000058 --dnrev A --dnport n4 --date 2024/01/31 --time 03:57
stop_connection.py -u PAM253 --uprev A --upport e -d SNPC000082 --dnrev A --dnport e2 --date 2024/01/31 --time 03:57
stop_connection.py -u PAM253 --uprev A --upport n -d SNPC000082 --dnrev A --dnport n0 --date 2024/01/31 --time 03:57
stop_connection.py -u PAM039 --uprev A --upport e -d SNPC000082 --dnrev A --dnport e10 --date 2024/01/31 --time 03:57
stop_connection.py -u PAM039 --uprev A --upport n -d SNPC000082 --dnrev A --dnport n8 --date 2024/01/31 --time 03:57
stop_connection.py -u SNPC000082 --uprev A --upport rack -d N20 --dnrev A --dnport loc1 --date 2024/01/31 --time 03:57
stop_connection.py -u PAM261 --uprev A --upport e -d SNPC000082 --dnrev A --dnport e6 --date 2024/01/31 --time 03:57
stop_connection.py -u PAM261 --uprev A --upport n -d SNPC000082 --dnrev A --dnport n4 --date 2024/01/31 --time 03:57
stop_connection.py -u PAM115 --uprev A --upport n -d SNPC000058 --dnrev A --dnport n8 --date 2024/01/31 --time 03:57
stop_connection.py -u PAM115 --uprev A --upport e -d SNPC000058 --dnrev A --dnport e10 --date 2024/01/31 --time 03:57
stop_connection.py -u SNPC000058 --uprev A --upport rack -d N05 --dnrev A --dnport loc0 --date 2024/01/31 --time 03:57
# add parts for gsheet_not_active
add_part.py -p SNPC000034 -r A -t snap -m SNPC000034 --date 2024/01/31 --time 03:33
add_part.py -p SNPC000115 -r A -t snap -m SNPC000115 --date 2024/01/31 --time 03:33
# add connections for gsheet_not_active
add_connection.py -u PAM253 --uprev A --upport e -d SNPC000115 --dnrev A --dnport e2 --date 2024/01/31 --time 04:03
add_connection.py -u PAM253 --uprev A --upport n -d SNPC000115 --dnrev A --dnport n0 --date 2024/01/31 --time 04:03
add_connection.py -u SNPC000115 --uprev A --upport rack -d N20 --dnrev A --dnport loc1 --date 2024/01/31 --time 04:03
add_connection.py -u PAM261 --uprev A --upport e -d SNPC000115 --dnrev A --dnport e6 --date 2024/01/31 --time 04:03
add_connection.py -u PAM261 --uprev A --upport n -d SNPC000115 --dnrev A --dnport n4 --date 2024/01/31 --time 04:03
add_connection.py -u PAM039 --uprev A --upport e -d SNPC000115 --dnrev A --dnport e10 --date 2024/01/31 --time 04:03
add_connection.py -u PAM039 --uprev A --upport n -d SNPC000115 --dnrev A --dnport n8 --date 2024/01/31 --time 04:03
add_connection.py -u PAM113 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e2 --date 2024/01/31 --time 04:03
add_connection.py -u PAM113 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n0 --date 2024/01/31 --time 04:03
add_connection.py -u SNPC000034 --uprev A --upport rack -d N05 --dnrev A --dnport loc0 --date 2024/01/31 --time 04:03
add_connection.py -u PAM114 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e6 --date 2024/01/31 --time 04:03
add_connection.py -u PAM114 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n4 --date 2024/01/31 --time 04:03
add_connection.py -u PAM115 --uprev A --upport e -d SNPC000034 --dnrev A --dnport e10 --date 2024/01/31 --time 04:03
add_connection.py -u PAM115 --uprev A --upport n -d SNPC000034 --dnrev A --dnport n8 --date 2024/01/31 --time 04:03
