#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/240202_infoupd_0342" >> scripts.log 
update_apriori.py -p HH236 -s dish_maintenance --date 2024/02/02 --time 03:48
add_part_info.py -p HH236 -r A -c "apriori_antenna status change: not_connected > dish_maintenance" -l "apa-infoupd" --date 2024/02/02 --time 03:48
