#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/240202_connupd_1535" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u FEM391 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr2 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM391 --uprev A --upport e -d NBP23 --dnrev A --dnport e2 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM391 --uprev A --upport n -d NBP23 --dnrev A --dnport n2 --date 2024/02/02 --time 15:29
stop_connection.py -u FDV236 --uprev A --upport terminals -d FEM706 --dnrev A --dnport input --date 2024/02/02 --time 15:29
stop_connection.py -u FEM706 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr3 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM706 --uprev A --upport e -d NBP23 --dnrev A --dnport e3 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM706 --uprev A --upport n -d NBP23 --dnrev A --dnport n3 --date 2024/02/02 --time 15:29
stop_connection.py -u FDV269 --uprev A --upport terminals -d FEM242 --dnrev A --dnport input --date 2024/02/02 --time 15:29
stop_connection.py -u FEM242 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr4 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM242 --uprev A --upport e -d NBP23 --dnrev A --dnport e4 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM242 --uprev A --upport n -d NBP23 --dnrev A --dnport n4 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM390 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr5 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM390 --uprev A --upport e -d NBP23 --dnrev A --dnport e5 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM390 --uprev A --upport n -d NBP23 --dnrev A --dnport n5 --date 2024/02/02 --time 15:29
stop_connection.py -u FDV238 --uprev A --upport terminals -d FEM705 --dnrev A --dnport input --date 2024/02/02 --time 15:29
stop_connection.py -u FEM705 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr6 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM705 --uprev A --upport e -d NBP23 --dnrev A --dnport e6 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM705 --uprev A --upport n -d NBP23 --dnrev A --dnport n6 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM103 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr8 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM103 --uprev A --upport e -d NBP23 --dnrev A --dnport e8 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM103 --uprev A --upport n -d NBP23 --dnrev A --dnport n8 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM054 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr9 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM054 --uprev A --upport e -d NBP23 --dnrev A --dnport e9 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM054 --uprev A --upport n -d NBP23 --dnrev A --dnport n9 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM383 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr10 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM383 --uprev A --upport e -d NBP23 --dnrev A --dnport e10 --date 2024/02/02 --time 15:29
stop_connection.py -u FEM383 --uprev A --upport n -d NBP23 --dnrev A --dnport n10 --date 2024/02/02 --time 15:29
# add connections for gsheet_not_active
add_connection.py -u FEM103 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr2 --date 2024/02/02 --time 15:35
add_connection.py -u FEM103 --uprev A --upport e -d NBP23 --dnrev A --dnport e2 --date 2024/02/02 --time 15:35
add_connection.py -u FEM103 --uprev A --upport n -d NBP23 --dnrev A --dnport n2 --date 2024/02/02 --time 15:35
add_connection.py -u FEM054 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr3 --date 2024/02/02 --time 15:35
add_connection.py -u FEM054 --uprev A --upport e -d NBP23 --dnrev A --dnport e3 --date 2024/02/02 --time 15:35
add_connection.py -u FEM054 --uprev A --upport n -d NBP23 --dnrev A --dnport n3 --date 2024/02/02 --time 15:35
add_connection.py -u FEM383 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr4 --date 2024/02/02 --time 15:35
add_connection.py -u FEM383 --uprev A --upport e -d NBP23 --dnrev A --dnport e4 --date 2024/02/02 --time 15:35
add_connection.py -u FEM383 --uprev A --upport n -d NBP23 --dnrev A --dnport n4 --date 2024/02/02 --time 15:35
add_connection.py -u FEM391 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr8 --date 2024/02/02 --time 15:35
add_connection.py -u FEM391 --uprev A --upport e -d NBP23 --dnrev A --dnport e8 --date 2024/02/02 --time 15:35
add_connection.py -u FEM391 --uprev A --upport n -d NBP23 --dnrev A --dnport n8 --date 2024/02/02 --time 15:35
add_connection.py -u FEM390 --uprev A --upport pwr -d FPS26 --dnrev A --dnport pwr11 --date 2024/02/02 --time 15:35
add_connection.py -u FEM390 --uprev A --upport e -d NBP23 --dnrev A --dnport e11 --date 2024/02/02 --time 15:35
add_connection.py -u FEM390 --uprev A --upport n -d NBP23 --dnrev A --dnport n11 --date 2024/02/02 --time 15:35
