#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/240510_infoupd_2242" >> scripts.log 
update_apriori.py -p HH66 -s digital_ok --date 2024/05/10 --time 22:48
add_part_info.py -p HH66 -r A -c "apriori_antenna status change: RF_ok > digital_ok" -l "apa-infoupd" --date 2024/05/10 --time 22:48
