#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/240510_connupd_2141" >> scripts.log 
# stop connections for active_not_gsheet
stop_connection.py -u FEM135 --uprev A --upport pwr -d FPS09 --dnrev A --dnport pwr2 --date 2024/05/10 --time 21:35
stop_connection.py -u FEM135 --uprev A --upport e -d NBP03 --dnrev A --dnport e2 --date 2024/05/10 --time 21:35
stop_connection.py -u FEM135 --uprev A --upport n -d NBP03 --dnrev A --dnport n2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD31 --uprev A --upport mnt -d NCMP2 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u FEM128 --uprev A --upport pwr -d FPS09 --dnrev A --dnport pwr4 --date 2024/05/10 --time 21:35
stop_connection.py -u FEM128 --uprev A --upport e -d NBP03 --dnrev A --dnport e4 --date 2024/05/10 --time 21:35
stop_connection.py -u FEM128 --uprev A --upport n -d NBP03 --dnrev A --dnport n4 --date 2024/05/10 --time 21:35
stop_connection.py -u RD06 --uprev A --upport mnt -d NCM05 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD40 --uprev A --upport mnt -d NCM09 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD05 --uprev A --upport mnt -d NCM21 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD02 --uprev A --upport mnt -d NCMP1 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD04 --uprev A --upport mnt -d NCM15 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD42 --uprev A --upport mnt -d NCM03 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD15 --uprev A --upport mnt -d NCM07 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD11 --uprev A --upport mnt -d NCM11 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD45 --uprev A --upport mnt -d NCM01 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD17 --uprev A --upport mnt -d NCM12 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD41 --uprev A --upport mnt -d NCM04 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD07 --uprev A --upport mnt -d NCM16 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD47 --uprev A --upport mnt -d NCM17 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD48 --uprev A --upport mnt -d NCM19 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD13 --uprev A --upport mnt -d NCM14 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD46 --uprev A --upport mnt -d NCM02 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD20 --uprev A --upport mnt -d NCM06 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD43 --uprev A --upport mnt -d NCM10 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD18 --uprev A --upport mnt -d NCM13 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD19 --uprev A --upport mnt -d NCM08 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD09 --uprev A --upport mnt -d NCM22 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD14 --uprev A --upport mnt -d NCM20 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
stop_connection.py -u RD16 --uprev A --upport mnt -d NCM18 --dnrev A --dnport mnt2 --date 2024/05/10 --time 21:35
# add connections for gsheet_not_active
add_connection.py -u FEM128 --uprev A --upport pwr -d FPS09 --dnrev A --dnport pwr2 --date 2024/05/10 --time 21:41
add_connection.py -u FEM128 --uprev A --upport e -d NBP03 --dnrev A --dnport e2 --date 2024/05/10 --time 21:41
add_connection.py -u FEM128 --uprev A --upport n -d NBP03 --dnrev A --dnport n2 --date 2024/05/10 --time 21:41
add_connection.py -u FEM135 --uprev A --upport pwr -d FPS09 --dnrev A --dnport pwr4 --date 2024/05/10 --time 21:41
add_connection.py -u FEM135 --uprev A --upport e -d NBP03 --dnrev A --dnport e4 --date 2024/05/10 --time 21:41
add_connection.py -u FEM135 --uprev A --upport n -d NBP03 --dnrev A --dnport n4 --date 2024/05/10 --time 21:41
