#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/240610_infoupd_1542" >> scripts.log 
add_part_info.py -p HH232 -r A -c "Ticket: Feed conduit feel out and is hanging on the cables." -l "infoupd" --date 2024/06/10 --time 15:42:00
