#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/240726_infoupd_2142" >> scripts.log 
add_part_info.py -p N03 -r A -c "Clean top" -l "infoupd" --date 2024/07/26 --time 21:42:00
add_part_info.py -p N03 -r A -c "Fan outside is working fine" -l "infoupd" --date 2024/07/26 --time 21:42:02
add_part_info.py -p N03 -r A -c "Good airflow and internal fans working" -l "infoupd" --date 2024/07/26 --time 21:42:04
add_part_info.py -p N03 -r A -c "Door opens easily" -l "infoupd" --date 2024/07/26 --time 21:42:06
add_part_info.py -p N04 -r A -c "Clean top" -l "infoupd" --date 2024/07/26 --time 21:42:00
add_part_info.py -p N04 -r A -c "Fan outside is working fine" -l "infoupd" --date 2024/07/26 --time 21:42:02
add_part_info.py -p N04 -r A -c "Good airflow and internal fans working" -l "infoupd" --date 2024/07/26 --time 21:42:04
add_part_info.py -p N04 -r A -c "Door opens easily" -l "infoupd" --date 2024/07/26 --time 21:42:06
add_part_info.py -p N07 -r A -c "Clean top" -l "infoupd" --date 2024/07/26 --time 21:42:00
add_part_info.py -p N07 -r A -c "Fan outside is working fine" -l "infoupd" --date 2024/07/26 --time 21:42:02
add_part_info.py -p N07 -r A -c "Good airflow and internal fans working" -l "infoupd" --date 2024/07/26 --time 21:42:04
add_part_info.py -p N07 -r A -c "Door was slightly tough to open" -l "infoupd" --date 2024/07/26 --time 21:42:06
