#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/240727_infoupd_1442" >> scripts.log 
add_part_info.py -p N14 -r A -c "Ferrite installed on PAM power line" -l "infoupd" --date 2024/07/27 --time 14:42:00
add_part_info.py -p N15 -r A -c "Ferrite installed on PAM power line" -l "infoupd" --date 2024/07/27 --time 14:42:00
add_part_info.py -p N16 -r A -c "Ferrite installed on PAM power line" -l "infoupd" --date 2024/07/27 --time 14:42:00
add_part_info.py -p N17 -r A -c "Ferrite installed on PAM power line" -l "infoupd" --date 2024/07/27 --time 14:42:00
add_part_info.py -p N18 -r A -c "Ferrite installed on PAM power line" -l "infoupd" --date 2024/07/27 --time 14:42:00
add_part_info.py -p N19 -r A -c "Ferrite installed on PAM power line" -l "infoupd" --date 2024/07/27 --time 14:42:00
add_part_info.py -p N20 -r A -c "Ferrite installed on PAM power line" -l "infoupd" --date 2024/07/27 --time 14:42:00
add_part_info.py -p N21 -r A -c "Ferrite installed on PAM power line" -l "infoupd" --date 2024/07/27 --time 14:42:00
add_part_info.py -p N22 -r A -c "Ferrite installed on PAM power line" -l "infoupd" --date 2024/07/27 --time 14:42:00
add_part_info.py -p N23 -r A -c "Ferrite installed on PAM power line" -l "infoupd" --date 2024/07/27 --time 14:42:00
