#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/240812_infoupd_1142" >> scripts.log 
add_part_info.py -p HH70 -r A -c "Removed LP filter" -l "infoupd" --date 2024/08/12 --time 11:42:00
