#! /bin/bash
source ~/.bashrc
echo "/home/obs/src/hera_cm_db_updates/241207_infoupd_1642" >> scripts.log 
add_part_info.py -p HH232 -r A -c "Ticket: Feed conduit feel out and is hanging on the cables." -l "infoupd" --date 2024/12/07 --time 16:42:00
