#! /usr/bin/env bash
echo "190226_update (do_it = True)" >> scripts.log 
add_part_info.py -p HH2 -r A -c "no power coax braid" --date 2019/02/26 --time 17:00
add_part_info.py -p HH11 -r A -c "no power coax braid" --date 2019/02/26 --time 17:00
add_part_info.py -p HH14 -r A -c "no power coax braid" --date 2019/02/26 --time 17:00
add_part_info.py -p HH23 -r A -c "no power coax braid" --date 2019/02/26 --time 17:00
add_part_info.py -p HH24 -r A -c "no power coax braid" --date 2019/02/26 --time 17:00
add_part_info.py -p HH39 -r A -c "no power coax braid/springs grounded" --date 2019/02/26 --time 17:00
