#! /usr/bin/env bash
echo "190327_add_stations (do_it = True)" >> scripts.log 
add_station.py HH148 --sernum 223 --date 2019/03/20 --time 10:00
add_part.py -p A148 -r H -t antenna -m S/N223 --date 2019/03/20 --time 10:00 --actually_do_it
add_connection.py -u HH148 --uprev A --upport ground -d A148 --dnrev H --dnport ground --date 2019/03/20 --time 10:00 --actually_do_it
add_station.py HH149 --sernum 224 --date 2019/03/20 --time 10:00
add_part.py -p A149 -r H -t antenna -m S/N224 --date 2019/03/20 --time 10:00 --actually_do_it
add_connection.py -u HH149 --uprev A --upport ground -d A149 --dnrev H --dnport ground --date 2019/03/20 --time 10:00 --actually_do_it
add_station.py HH170 --sernum 225 --date 2019/03/20 --time 10:00
add_part.py -p A170 -r H -t antenna -m S/N225 --date 2019/03/20 --time 10:00 --actually_do_it
add_connection.py -u HH170 --uprev A --upport ground -d A170 --dnrev H --dnport ground --date 2019/03/20 --time 10:00 --actually_do_it
add_station.py HH191 --sernum 226 --date 2019/03/21 --time 10:00
add_part.py -p A191 -r H -t antenna -m S/N226 --date 2019/03/21 --time 10:00 --actually_do_it
add_connection.py -u HH191 --uprev A --upport ground -d A191 --dnrev H --dnport ground --date 2019/03/21 --time 10:00 --actually_do_it
add_station.py HH211 --sernum 227 --date 2019/03/23 --time 10:00
add_part.py -p A211 -r H -t antenna -m S/N227 --date 2019/03/23 --time 10:00 --actually_do_it
add_connection.py -u HH211 --uprev A --upport ground -d A211 --dnrev H --dnport ground --date 2019/03/23 --time 10:00 --actually_do_it
