#! /usr/bin/env bash
echo "190312_add_stations (do_it = True)" >> scripts.log 
add_station.py HH130 --sernum 213 --date 2019/03/06 --time 10:00
add_part.py -p A130 -r H -t antenna -m S/N213 --date 2019/03/06 --time 10:00 --actually_do_it
add_connection.py -u HH130 --uprev A --upport ground -d A130 --dnrev H --dnport ground --date 2019/03/06 --time 10:00 --actually_do_it
add_station.py HH129 --sernum 214 --date 2019/03/07 --time 10:00
add_part.py -p A129 -r H -t antenna -m S/N214 --date 2019/03/07 --time 10:00 --actually_do_it
add_connection.py -u HH129 --uprev A --upport ground -d A129 --dnrev H --dnport ground --date 2019/03/07 --time 10:00 --actually_do_it
add_station.py HH127 --sernum 215 --date 2019/03/08 --time 10:00
add_part.py -p A127 -r H -t antenna -m S/N215 --date 2019/03/08 --time 10:00 --actually_do_it
add_connection.py -u HH127 --uprev A --upport ground -d A127 --dnrev H --dnport ground --date 2019/03/08 --time 10:00 --actually_do_it
add_station.py HH128 --sernum 216 --date 2019/03/08 --time 10:00
add_part.py -p A128 -r H -t antenna -m S/N216 --date 2019/03/08 --time 10:00 --actually_do_it
add_connection.py -u HH128 --uprev A --upport ground -d A128 --dnrev H --dnport ground --date 2019/03/08 --time 10:00 --actually_do_it
