#! /usr/bin/env bash
echo "190317_add_stations (do_it = True)" >> scripts.log 
add_station.py HH135 --sernum 222 --date 2019/03/14 --time 10:00
add_part.py -p A135 -r H -t antenna -m S/N222 --date 2019/03/14 --time 10:00 --actually_do_it
add_connection.py -u HH135 --uprev A --upport ground -d A135 --dnrev H --dnport ground --date 2019/03/14 --time 10:00 --actually_do_it
add_station.py HH146 --sernum 221 --date 2019/03/13 --time 10:00
add_part.py -p A146 -r H -t antenna -m S/N221 --date 2019/03/13 --time 10:00 --actually_do_it
add_connection.py -u HH146 --uprev A --upport ground -d A146 --dnrev H --dnport ground --date 2019/03/13 --time 10:00 --actually_do_it
add_station.py HH147 --sernum 220 --date 2019/03/13 --time 10:00
add_part.py -p A147 -r H -t antenna -m S/N220 --date 2019/03/13 --time 10:00 --actually_do_it
add_connection.py -u HH147 --uprev A --upport ground -d A147 --dnrev H --dnport ground --date 2019/03/13 --time 10:00 --actually_do_it
add_station.py HH168 --sernum 217 --date 2019/02/15 --time 10:00
add_part.py -p A168 -r H -t antenna -m S/N217 --date 2019/02/15 --time 10:00 --actually_do_it
add_connection.py -u HH168 --uprev A --upport ground -d A168 --dnrev H --dnport ground --date 2019/02/15 --time 10:00 --actually_do_it
add_station.py HH169 --sernum 218 --date 2019/02/15 --time 10:00
add_part.py -p A169 -r H -t antenna -m S/N218 --date 2019/02/15 --time 10:00 --actually_do_it
add_connection.py -u HH169 --uprev A --upport ground -d A169 --dnrev H --dnport ground --date 2019/02/15 --time 10:00 --actually_do_it
add_station.py HH188 --sernum 219 --date 2019/02/15 --time 10:00
add_part.py -p A188 -r H -t antenna -m S/N219 --date 2019/02/15 --time 10:00 --actually_do_it
add_connection.py -u HH188 --uprev A --upport ground -d A188 --dnrev H --dnport ground --date 2019/02/15 --time 10:00 --actually_do_it
