#! /usr/bin/env bash
echo "190308_add_stations (do_it = True)" >> scripts.log 
add_station.py HH228 --sernum 208 --date 2019/02/28 --time 10:00
add_part.py -p A228 -r H -t antenna -m S/N208 --date 2019/02/28 --time 10:00 --actually_do_it
add_connection.py -u HH228 --uprev A --upport ground -d A228 --dnrev H --dnport ground --date 2019/02/28 --time 10:00 --actually_do_it
add_station.py HH189 --sernum 209 --date 2019/02/28 --time 10:00
add_part.py -p A189 -r H -t antenna -m S/N209 --date 2019/02/28 --time 10:00 --actually_do_it
add_connection.py -u HH189 --uprev A --upport ground -d A189 --dnrev H --dnport ground --date 2019/02/28 --time 10:00 --actually_do_it
add_station.py HH190 --sernum 210 --date 2019/02/28 --time 10:00
add_part.py -p A190 -r H -t antenna -m S/N210 --date 2019/02/28 --time 10:00 --actually_do_it
add_connection.py -u HH190 --uprev A --upport ground -d A190 --dnrev H --dnport ground --date 2019/02/28 --time 10:00 --actually_do_it
add_station.py HH209 --sernum 211 --date 2019/02/28 --time 10:00
add_part.py -p A209 -r H -t antenna -m S/N211 --date 2019/02/28 --time 10:00 --actually_do_it
add_connection.py -u HH209 --uprev A --upport ground -d A209 --dnrev H --dnport ground --date 2019/02/28 --time 10:00 --actually_do_it
add_station.py HH210 --sernum 212 --date 2019/02/28 --time 10:00
add_part.py -p A210 -r H -t antenna -m S/N212 --date 2019/02/28 --time 10:00 --actually_do_it
add_connection.py -u HH210 --uprev A --upport ground -d A210 --dnrev H --dnport ground --date 2019/02/28 --time 10:00 --actually_do_it
