#! /usr/bin/env bash
echo "190426_add_stations (do_it = True)" >> scripts.log 
add_station.py HH110 --sernum 228 --date 2019/02/18 --time 10:00
add_part.py -p A110 -r H -t antenna -m S/N228 --date 2019/02/18 --time 10:00 --actually_do_it
add_connection.py -u HH110 --uprev A --upport ground -d A110 --dnrev H --dnport ground --date 2019/02/18 --time 10:00 --actually_do_it
add_station.py HH208 --sernum 229 --date 2019/02/19 --time 10:00
add_part.py -p A208 -r H -t antenna -m S/N229 --date 2019/02/19 --time 10:00 --actually_do_it
add_connection.py -u HH208 --uprev A --upport ground -d A208 --dnrev H --dnport ground --date 2019/02/19 --time 10:00 --actually_do_it
add_station.py HH226 --sernum 230 --date 2019/02/19 --time 10:00
add_part.py -p A226 -r H -t antenna -m S/N230 --date 2019/02/19 --time 10:00 --actually_do_it
add_connection.py -u HH226 --uprev A --upport ground -d A226 --dnrev H --dnport ground --date 2019/02/19 --time 10:00 --actually_do_it
add_station.py HH227 --sernum 231 --date 2019/02/19 --time 10:00
add_part.py -p A227 -r H -t antenna -m S/N231 --date 2019/02/19 --time 10:00 --actually_do_it
add_connection.py -u HH227 --uprev A --upport ground -d A227 --dnrev H --dnport ground --date 2019/02/19 --time 10:00 --actually_do_it
add_station.py HH244 --sernum 232 --date 2019/02/19 --time 10:00
add_part.py -p A244 -r H -t antenna -m S/N232 --date 2019/02/19 --time 10:00 --actually_do_it
add_connection.py -u HH244 --uprev A --upport ground -d A244 --dnrev H --dnport ground --date 2019/02/19 --time 10:00 --actually_do_it
add_station.py HH109 --sernum 233 --date 2019/02/20 --time 10:00
add_part.py -p A109 -r H -t antenna -m S/N233 --date 2019/02/20 --time 10:00 --actually_do_it
add_connection.py -u HH109 --uprev A --upport ground -d A109 --dnrev H --dnport ground --date 2019/02/20 --time 10:00 --actually_do_it
add_station.py HH187 --sernum 234 --date 2019/02/20 --time 10:00
add_part.py -p A187 -r H -t antenna -m S/N234 --date 2019/02/20 --time 10:00 --actually_do_it
add_connection.py -u HH187 --uprev A --upport ground -d A187 --dnrev H --dnport ground --date 2019/02/20 --time 10:00 --actually_do_it
add_station.py HH207 --sernum 235 --date 2019/02/20 --time 10:00
add_part.py -p A207 -r H -t antenna -m S/N235 --date 2019/02/20 --time 10:00 --actually_do_it
add_connection.py -u HH207 --uprev A --upport ground -d A207 --dnrev H --dnport ground --date 2019/02/20 --time 10:00 --actually_do_it
add_station.py HH166 --sernum 236 --date 2019/02/21 --time 10:00
add_part.py -p A166 -r H -t antenna -m S/N236 --date 2019/02/21 --time 10:00 --actually_do_it
add_connection.py -u HH166 --uprev A --upport ground -d A166 --dnrev H --dnport ground --date 2019/02/21 --time 10:00 --actually_do_it
add_station.py HH111 --sernum 237 --date 2019/04/25 --time 10:00
add_part.py -p A111 -r H -t antenna -m S/N237 --date 2019/04/25 --time 10:00 --actually_do_it
add_connection.py -u HH111 --uprev A --upport ground -d A111 --dnrev H --dnport ground --date 2019/04/25 --time 10:00 --actually_do_it
add_station.py HH112 --sernum 238 --date 2019/04/25 --time 10:00
add_part.py -p A112 -r H -t antenna -m S/N238 --date 2019/04/25 --time 10:00 --actually_do_it
add_connection.py -u HH112 --uprev A --upport ground -d A112 --dnrev H --dnport ground --date 2019/04/25 --time 10:00 --actually_do_it
add_station.py HH150 --sernum 239 --date 2019/04/25 --time 10:00
add_part.py -p A150 -r H -t antenna -m S/N239 --date 2019/04/25 --time 10:00 --actually_do_it
add_connection.py -u HH150 --uprev A --upport ground -d A150 --dnrev H --dnport ground --date 2019/04/25 --time 10:00 --actually_do_it
