#! /usr/bin/env bash
echo "190516_add_chain (do_it = True)" >> scripts.log 
add_part.py -p FEM044 -r A -t front-end -m FEM044 --date 2019/05/16 --time 10:00 --actually_do_it
add_part.py -p CRF089 -r A -t cable-rfof -m CRF089 --date 2019/05/16 --time 10:00 --actually_do_it
add_part.py -p PAM043 -r A -t post-amp -m PAM043 --date 2019/05/16 --time 10:00 --actually_do_it
add_part.py -p SNPC000013 -r A -t snap -m SNPC000013 --date 2019/05/16 --time 10:00 --actually_do_it
add_connection.py -u FDV16 --uprev A --upport terminals -d FEM044 --dnrev A --dnport input --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u FEM044 --uprev A --upport e -d CRF089 --dnrev A --dnport ea --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u FEM044 --uprev A --upport n -d CRF089 --dnrev A --dnport na --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u CRF089 --uprev A --upport eb -d PAM043 --dnrev A --dnport ea --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u CRF089 --uprev A --upport nb -d PAM043 --dnrev A --dnport na --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u PAM043 --uprev A --upport eb -d SNPC000013 --dnrev A --dnport e10 --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u PAM043 --uprev A --upport nb -d SNPC000013 --dnrev A --dnport n8 --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u SNPC000013 --uprev A --upport rack -d N9 --dnrev A --dnport loc2 --date 2019/05/16 --time 11:00 --actually_do_it
add_part.py -p FEM032 -r A -t front-end -m FEM032 --date 2019/05/16 --time 10:00 --actually_do_it
add_part.py -p CRF124 -r A -t cable-rfof -m CRF124 --date 2019/05/16 --time 10:00 --actually_do_it
add_part.py -p PAM042 -r A -t post-amp -m PAM042 --date 2019/05/16 --time 10:00 --actually_do_it
add_connection.py -u FDV24 --uprev A --upport terminals -d FEM032 --dnrev A --dnport input --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u FEM032 --uprev A --upport e -d CRF124 --dnrev A --dnport ea --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u FEM032 --uprev A --upport n -d CRF124 --dnrev A --dnport na --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u CRF124 --uprev A --upport eb -d PAM042 --dnrev A --dnport ea --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u CRF124 --uprev A --upport nb -d PAM042 --dnrev A --dnport na --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u PAM042 --uprev A --upport eb -d SNPC000013 --dnrev A --dnport e6 --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u PAM042 --uprev A --upport nb -d SNPC000013 --dnrev A --dnport n4 --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u SNPC000013 --uprev A --upport rack -d N9 --dnrev A --dnport loc2 --date 2019/05/16 --time 11:00 --actually_do_it
add_part.py -p FEM028 -r A -t front-end -m FEM028 --date 2019/05/16 --time 10:00 --actually_do_it
add_part.py -p CRF126 -r A -t cable-rfof -m CRF126 --date 2019/05/16 --time 10:00 --actually_do_it
add_part.py -p PAM045 -r A -t post-amp -m PAM045 --date 2019/05/16 --time 10:00 --actually_do_it
add_connection.py -u FDV13 --uprev A --upport terminals -d FEM028 --dnrev A --dnport input --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u FEM028 --uprev A --upport e -d CRF126 --dnrev A --dnport ea --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u FEM028 --uprev A --upport n -d CRF126 --dnrev A --dnport na --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u CRF126 --uprev A --upport eb -d PAM045 --dnrev A --dnport ea --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u CRF126 --uprev A --upport nb -d PAM045 --dnrev A --dnport na --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u PAM045 --uprev A --upport eb -d SNPC000033 --dnrev A --dnport e6 --date 2019/05/16 --time 11:00 --actually_do_it
add_connection.py -u PAM045 --uprev A --upport nb -d SNPC000033 --dnrev A --dnport n4 --date 2019/05/16 --time 11:00 --actually_do_it
