#! /usr/bin/env bash
echo "190512_add_stations (do_it = True)" >> scripts.log 
add_station.py HH268 --sernum 240 --date 2019/05/03 --time 10:00
add_part.py -p A268 -r H -t antenna -m S/N240 --date 2019/05/03 --time 10:00 --actually_do_it
add_connection.py -u HH268 --uprev A --upport ground -d A268 --dnrev H --dnport ground --date 2019/05/03 --time 10:00 --actually_do_it
add_station.py HH269 --sernum 241 --date 2019/05/03 --time 10:00
add_part.py -p A269 -r H -t antenna -m S/N241 --date 2019/05/03 --time 10:00 --actually_do_it
add_connection.py -u HH269 --uprev A --upport ground -d A269 --dnrev H --dnport ground --date 2019/05/03 --time 10:00 --actually_do_it
add_station.py HH167 --sernum 242 --date 2019/02/21 --time 10:00
add_part.py -p A167 -r H -t antenna -m S/N242 --date 2019/02/21 --time 10:00 --actually_do_it
add_connection.py -u HH167 --uprev A --upport ground -d A167 --dnrev H --dnport ground --date 2019/02/21 --time 10:00 --actually_do_it
