#! /usr/bin/env bash
echo "190516_add_node_internal (do_it = True)" >> scripts.log 
add_part.py -p FPS02 -r A -t fem-power-supply -m FPS02 --date 2019/05/14 --time 12:00 --actually_do_it
add_part.py -p NCMC000196 -r A -t node-control-module -m C000196 --date 2019/05/14 --time 12:00 --actually_do_it
add_part.py -p PCH02 -r A -t pam-chassis -m PCH02 --date 2019/05/14 --time 12:00 --actually_do_it
add_part.py -p PAM036 -r A -t post-amp -m PAM036 --date 2019/05/15 --time 12:00 --actually_do_it
add_part.py -p PAM037 -r A -t post-amp -m PAM037 --date 2019/05/15 --time 12:00 --actually_do_it
add_part.py -p PAM038 -r A -t post-amp -m PAM038 --date 2019/05/15 --time 12:00 --actually_do_it
add_part.py -p PAM039 -r A -t post-amp -m PAM039 --date 2019/05/15 --time 12:00 --actually_do_it
add_part.py -p PAM040 -r A -t post-amp -m PAM040 --date 2019/05/15 --time 12:00 --actually_do_it
add_part.py -p PAM041 -r A -t post-amp -m PAM041 --date 2019/05/15 --time 12:00 --actually_do_it
add_connection.py -u PCH02 --uprev A --upport @rack -d N9 --dnrev A --dnport @loc0 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u PAM035 --uprev A --upport @slot -d PCH02 --dnrev A --dnport @slot1 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u PAM036 --uprev A --upport @slot -d PCH02 --dnrev A --dnport @slot2 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u PAM037 --uprev A --upport @slot -d PCH02 --dnrev A --dnport @slot3 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u PAM038 --uprev A --upport @slot -d PCH02 --dnrev A --dnport @slot4 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u PAM039 --uprev A --upport @slot -d PCH02 --dnrev A --dnport @slot5 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u PAM040 --uprev A --upport @slot -d PCH02 --dnrev A --dnport @slot6 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u PAM041 --uprev A --upport @slot -d PCH02 --dnrev A --dnport @slot7 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u PAM042 --uprev A --upport @slot -d PCH02 --dnrev A --dnport @slot8 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u PAM043 --uprev A --upport @slot -d PCH02 --dnrev A --dnport @slot9 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u PAM044 --uprev A --upport @slot -d PCH02 --dnrev A --dnport @slot10 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u PAM045 --uprev A --upport @slot -d PCH02 --dnrev A --dnport @slot11 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u PAM046 --uprev A --upport @slot -d PCH02 --dnrev A --dnport @slot12 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u NCMC000196 --uprev A --upport @rack -d N9 --dnrev A --dnport @loc5 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u FPS02 --uprev A --upport @rack -d N9 --dnrev A --dnport @loc6 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u FEM044 --uprev A --upport @pwr -d FPS02 --dnrev A --dnport @pwr9 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u FEM030 --uprev A --upport @pwr -d FPS02 --dnrev A --dnport @pwr10 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u FEM031 --uprev A --upport @pwr -d FPS02 --dnrev A --dnport @pwr1 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u FEM032 --uprev A --upport @pwr -d FPS02 --dnrev A --dnport @pwr8 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u FEM029 --uprev A --upport @pwr -d FPS02 --dnrev A --dnport @pwr12 --date 2019/05/14 --time 12:30 --actually_do_it
add_connection.py -u FEM028 --uprev A --upport @pwr -d FPS02 --dnrev A --dnport @pwr11 --date 2019/05/14 --time 12:30 --actually_do_it
