#! /usr/bin/env bash
echo "190604_swap_parts (do_it = True)" >> scripts.log 
add_part.py -p PAM048 -r A -t post-amp -m PAM048 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u NBP00 --uprev A --upport e2 -d PAM023 --dnrev A --dnport e --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u NBP00 --uprev A --upport n2 -d PAM023 --dnrev A --dnport n --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u PAM023 --uprev A --upport @slot -d PCH01 --dnrev A --dnport @slot02 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u PAM023 --uprev A --upport e -d SNPC000057 --dnrev A --dnport e6 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u PAM023 --uprev A --upport n -d SNPC000057 --dnrev A --dnport n4 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u NBP00 --uprev A --upport e2 -d PAM048 --dnrev A --dnport e --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u NBP00 --uprev A --upport n2 -d PAM048 --dnrev A --dnport n --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u PAM048 --uprev A --upport @slot -d PCH01 --dnrev A --dnport @slot02 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u PAM048 --uprev A --upport e -d SNPC000057 --dnrev A --dnport e6 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u PAM048 --uprev A --upport n -d SNPC000057 --dnrev A --dnport n4 --date 2019/05/17 --time 11:00 --actually_do_it
add_part.py -p FEM045 -r A -t front-end -m FEM045 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u FDV9 --uprev A --upport terminals -d FEM019 --dnrev A --dnport input --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u FEM019 --uprev A --upport e -d NBP00 --dnrev A --dnport e4 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u FEM019 --uprev A --upport n -d NBP00 --dnrev A --dnport n4 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u FDV9 --uprev A --upport terminals -d FEM045 --dnrev A --dnport input --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u FEM045 --uprev A --upport e -d NBP00 --dnrev A --dnport e4 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u FEM045 --uprev A --upport n -d NBP00 --dnrev A --dnport n4 --date 2019/05/17 --time 11:00 --actually_do_it
add_part.py -p PAM052 -r A -t post-amp -m PAM052 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u NBP00 --uprev A --upport e4 -d PAM025 --dnrev A --dnport e --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u NBP00 --uprev A --upport n4 -d PAM025 --dnrev A --dnport n --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u PAM025 --uprev A --upport @slot -d PCH01 --dnrev A --dnport @slot04 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u PAM025 --uprev A --upport e -d SNPA000008 --dnrev A --dnport e2 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u PAM025 --uprev A --upport n -d SNPA000008 --dnrev A --dnport n0 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u NBP00 --uprev A --upport e4 -d PAM052 --dnrev A --dnport e --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u NBP00 --uprev A --upport n4 -d PAM052 --dnrev A --dnport n --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u PAM052 --uprev A --upport @slot -d PCH01 --dnrev A --dnport @slot04 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u PAM052 --uprev A --upport e -d SNPA000008 --dnrev A --dnport e2 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u PAM052 --uprev A --upport n -d SNPA000008 --dnrev A --dnport n0 --date 2019/05/17 --time 11:00 --actually_do_it
add_part.py -p PAM050 -r A -t post-amp -m PAM050 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u NBP00 --uprev A --upport e5 -d PAM026 --dnrev A --dnport e --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u NBP00 --uprev A --upport n5 -d PAM026 --dnrev A --dnport n --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u PAM026 --uprev A --upport @slot -d PCH01 --dnrev A --dnport @slot05 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u PAM026 --uprev A --upport e -d SNPA000008 --dnrev A --dnport e6 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u PAM026 --uprev A --upport n -d SNPA000008 --dnrev A --dnport n4 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u NBP00 --uprev A --upport e5 -d PAM050 --dnrev A --dnport e --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u NBP00 --uprev A --upport n5 -d PAM050 --dnrev A --dnport n --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u PAM050 --uprev A --upport @slot -d PCH01 --dnrev A --dnport @slot05 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u PAM050 --uprev A --upport e -d SNPA000008 --dnrev A --dnport e6 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u PAM050 --uprev A --upport n -d SNPA000008 --dnrev A --dnport n4 --date 2019/05/17 --time 11:00 --actually_do_it
add_part.py -p PAM051 -r A -t post-amp -m PAM051 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u NBP00 --uprev A --upport e10 -d PAM031 --dnrev A --dnport e --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u NBP00 --uprev A --upport n10 -d PAM031 --dnrev A --dnport n --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u PAM031 --uprev A --upport @slot -d PCH01 --dnrev A --dnport @slot10 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u PAM031 --uprev A --upport e -d SNPA000020 --dnrev A --dnport e2 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u PAM031 --uprev A --upport n -d SNPA000020 --dnrev A --dnport n0 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u NBP00 --uprev A --upport e10 -d PAM051 --dnrev A --dnport e --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u NBP00 --uprev A --upport n10 -d PAM051 --dnrev A --dnport n --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u PAM051 --uprev A --upport @slot -d PCH01 --dnrev A --dnport @slot10 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u PAM051 --uprev A --upport e -d SNPA000020 --dnrev A --dnport e2 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u PAM051 --uprev A --upport n -d SNPA000020 --dnrev A --dnport n0 --date 2019/05/17 --time 11:00 --actually_do_it
add_part.py -p FEM042 -r A -t front-end -m FEM042 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u FDV14 --uprev A --upport terminals -d FEM027 --dnrev A --dnport input --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u FEM027 --uprev A --upport n -d NBP00 --dnrev A --dnport n12 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u FEM027 --uprev A --upport e -d NBP00 --dnrev A --dnport e12 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u FDV14 --uprev A --upport terminals -d FEM042 --dnrev A --dnport input --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u FEM042 --uprev A --upport n -d NBP00 --dnrev A --dnport n12 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u FEM042 --uprev A --upport e -d NBP00 --dnrev A --dnport e12 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u FDV7 --uprev A --upport terminals -d FEM026 --dnrev A --dnport input --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u FEM026 --uprev A --upport n -d NBP00 --dnrev A --dnport n11 --date 2019/05/17 --time 11:00 --actually_do_it
stop_connection.py -u FEM026 --uprev A --upport e -d NBP00 --dnrev A --dnport e11 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u FDV7 --uprev A --upport terminals -d FEM027 --dnrev A --dnport input --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u FEM027 --uprev A --upport n -d NBP00 --dnrev A --dnport n11 --date 2019/05/17 --time 11:00 --actually_do_it
add_connection.py -u FEM027 --uprev A --upport e -d NBP00 --dnrev A --dnport e11 --date 2019/05/17 --time 11:00 --actually_do_it
