#! /usr/bin/env bash
echo "20190815_overview_update_2009" >> scripts.log 
add_part_info.py -p HH0 -r A -c "FEM I2C: y" --date 2019/06/13 --time 12:00
add_part_info.py -p HH0 -r A -c "PAM I2C: y" --date 2019/06/13 --time 12:00:01
add_part_info.py -p HH0 -r A -c "RF PWR E: 1.7" --date 2019/06/13 --time 12:00:02
add_part_info.py -p HH0 -r A -c "Goodness E: OK?" --date 2019/06/13 --time 12:00:03
add_part_info.py -p HH0 -r A -c "Feed Height (m): 4.428" --date 2019/08/01 --time 12:00
add_part_info.py -p HH0 -r A -c "Tension N:W:E (lbs): 330:355:330" --date 2019/08/01 --time 12:00:01
add_part_info.py -p HH0 -r A -c "Eye-bolt N:W:E (m): 6.50:6.35:6.41" --date 2019/08/01 --time 12:00:02
add_part_info.py -p HH0 -r A -c "RF PWR N: -4.9" --date 2019/06/13 --time 12:00:04
add_part_info.py -p HH0 -r A -c "Goodness N: OK?" --date 2019/06/13 --time 12:00:05
add_part_info.py -p HH1 -r A -c "FEM I2C: y" --date 2019/06/13 --time 12:00
add_part_info.py -p HH1 -r A -c "PAM I2C: y" --date 2019/06/13 --time 12:00:01
add_part_info.py -p HH1 -r A -c "RF PWR E: 0.6" --date 2019/06/13 --time 12:00:02
add_part_info.py -p HH1 -r A -c "Goodness E: OK?" --date 2019/06/13 --time 12:00:03
add_part_info.py -p HH1 -r A -c "Feed Height (m): 4.397" --date 2019/08/01 --time 12:00
add_part_info.py -p HH1 -r A -c "Tension N:W:E (lbs): 460:315:400" --date 2019/08/01 --time 12:00:01
add_part_info.py -p HH1 -r A -c "Eye-bolt N:W:E (m): 6.41:6.37:6.33" --date 2019/08/01 --time 12:00:02
add_part_info.py -p HH1 -r A -c "RF PWR N: -3.7" --date 2019/06/13 --time 12:00:04
add_part_info.py -p HH1 -r A -c "Goodness N: OK?" --date 2019/06/13 --time 12:00:05
add_part_info.py -p HH2 -r A -c "FEM I2C: y" --date 2019/06/13 --time 12:00
add_part_info.py -p HH2 -r A -c "PAM I2C: y" --date 2019/06/13 --time 12:00:01
add_part_info.py -p HH2 -r A -c "RF PWR E: 0.1" --date 2019/06/13 --time 12:00:02
add_part_info.py -p HH2 -r A -c "Goodness E: OK?" --date 2019/06/13 --time 12:00:03
add_part_info.py -p HH2 -r A -c "Broken fibres (spliced), antenna support broken" --date 2019/06/13 --time 12:00:04
add_part_info.py -p HH2 -r A -c "Feed Height (m): 4.405" --date 2019/08/01 --time 12:00
add_part_info.py -p HH2 -r A -c "Tension N:W:E (lbs): 490:290:445" --date 2019/08/01 --time 12:00:01
add_part_info.py -p HH2 -r A -c "Eye-bolt N:W:E (m): 6.23:6.15:6.18" --date 2019/08/01 --time 12:00:02
add_part_info.py -p HH2 -r A -c "RF PWR N: -10.5" --date 2019/06/13 --time 12:00:05
add_part_info.py -p HH2 -r A -c "Goodness N: Bad" --date 2019/06/13 --time 12:00:06
add_part_info.py -p HH2 -r A -c "Broken fibres (spliced maybe not fixed?), antenna support broken. Bad PAM confirmed after swapping with other input. " --date 2019/06/13 --time 12:00:07
add_part_info.py -p HH11 -r A -c "FEM I2C: n" --date 2019/06/13 --time 12:00
add_part_info.py -p HH11 -r A -c "PAM I2C: y" --date 2019/06/13 --time 12:00:01
add_part_info.py -p HH11 -r A -c "RF PWR E: -0.5" --date 2019/06/13 --time 12:00:02
add_part_info.py -p HH11 -r A -c "Goodness E: OK?" --date 2019/06/13 --time 12:00:03
add_part_info.py -p HH11 -r A -c "Internal CAT cable broken (fixed?), +5V RFoF FEM and PAM" --date 2019/06/13 --time 12:00:04
add_part_info.py -p HH11 -r A -c "Feed Height (m): 4.408" --date 2019/08/01 --time 12:00
add_part_info.py -p HH11 -r A -c "Tension N:W:E (lbs): 335:340:400" --date 2019/08/01 --time 12:00:01
add_part_info.py -p HH11 -r A -c "Eye-bolt N:W:E (m): 6.48:6.41:6.33" --date 2019/08/01 --time 12:00:02
add_part_info.py -p HH11 -r A -c "RF PWR N: -7.4" --date 2019/06/13 --time 12:00:05
add_part_info.py -p HH11 -r A -c "Goodness N: OK?" --date 2019/06/13 --time 12:00:06
add_part_info.py -p HH11 -r A -c "Internal CAT cable broken (fixed?), +5V RFoF FEM and PAM" --date 2019/06/13 --time 12:00:07
add_part_info.py -p HH12 -r A -c "FEM I2C: y" --date 2019/06/13 --time 12:00
add_part_info.py -p HH12 -r A -c "PAM I2C: y" --date 2019/06/13 --time 12:00:01
add_part_info.py -p HH12 -r A -c "RF PWR E: -3.2" --date 2019/06/13 --time 12:00:02
add_part_info.py -p HH12 -r A -c "Goodness E: OK?" --date 2019/06/13 --time 12:00:03
add_part_info.py -p HH12 -r A -c "Feed Height (m): 4.408" --date 2019/08/01 --time 12:00
add_part_info.py -p HH12 -r A -c "Tension N:W:E (lbs): 310:370:315" --date 2019/08/01 --time 12:00:01
add_part_info.py -p HH12 -r A -c "Eye-bolt N:W:E (m): 6.43:6.35:6.37" --date 2019/08/01 --time 12:00:02
add_part_info.py -p HH12 -r A -c "RF PWR N: -5.9" --date 2019/06/13 --time 12:00:04
add_part_info.py -p HH12 -r A -c "Goodness N: OK?" --date 2019/06/13 --time 12:00:05
add_part_info.py -p HH12 -r A -c "broken fibre (spliced)" --date 2019/08/12 --time 12:00
add_part_info.py -p HH12 -r A -c "Testing" --date 2019/08/12 --time 12:00:01
add_part_info.py -p HH13 -r A -c "FEM I2C: n" --date 2019/06/13 --time 12:00
add_part_info.py -p HH13 -r A -c "PAM I2C: y" --date 2019/06/13 --time 12:00:01
add_part_info.py -p HH13 -r A -c "RF PWR E: 0.4" --date 2019/06/13 --time 12:00:02
add_part_info.py -p HH13 -r A -c "Goodness E: OK?" --date 2019/06/13 --time 12:00:03
add_part_info.py -p HH13 -r A -c "Feed Height (m): 4.4" --date 2019/08/01 --time 12:00
add_part_info.py -p HH13 -r A -c "Tension N:W:E (lbs): 475:420:405" --date 2019/08/01 --time 12:00:01
add_part_info.py -p HH13 -r A -c "Eye-bolt N:W:E (m): 6.35:6.32:6.30" --date 2019/08/01 --time 12:00:02
add_part_info.py -p HH13 -r A -c "RF PWR N: -6.2" --date 2019/06/13 --time 12:00:04
add_part_info.py -p HH13 -r A -c "Goodness N: OK?" --date 2019/06/13 --time 12:00:05
add_part_info.py -p HH14 -r A -c "FEM I2C: y" --date 2019/06/13 --time 12:00
add_part_info.py -p HH14 -r A -c "PAM I2C: y" --date 2019/06/13 --time 12:00:01
add_part_info.py -p HH14 -r A -c "RF PWR E: -0.8" --date 2019/06/13 --time 12:00:02
add_part_info.py -p HH14 -r A -c "Goodness E: OK?" --date 2019/06/13 --time 12:00:03
add_part_info.py -p HH14 -r A -c "Feed Height (m): 4.407" --date 2019/08/01 --time 12:00
add_part_info.py -p HH14 -r A -c "Tension N:W:E (lbs): 425:365:395" --date 2019/08/01 --time 12:00:01
add_part_info.py -p HH14 -r A -c "Eye-bolt N:W:E (m): 6.25:6.24:6.22" --date 2019/08/01 --time 12:00:02
add_part_info.py -p HH14 -r A -c "RF PWR N: -14.2" --date 2019/06/13 --time 12:00:04
add_part_info.py -p HH14 -r A -c "Goodness N: Check!" --date 2019/06/13 --time 12:00:05
add_part_info.py -p HH14 -r A -c "Maybe damaged fibre?" --date 2019/06/13 --time 12:00:06
add_part_info.py -p HH23 -r A -c "FEM I2C: y" --date 2019/06/13 --time 12:00
add_part_info.py -p HH23 -r A -c "PAM I2C: y" --date 2019/06/13 --time 12:00:01
add_part_info.py -p HH23 -r A -c "RF PWR E: -2.6" --date 2019/06/13 --time 12:00:02
add_part_info.py -p HH23 -r A -c "Goodness E: OK?" --date 2019/06/13 --time 12:00:03
add_part_info.py -p HH23 -r A -c "Tension N:W:E (lbs): 430:455:390" --date 2019/08/01 --time 12:00
add_part_info.py -p HH23 -r A -c "Eye-bolt N:W:E (m): 6.52:6.39:6.37" --date 2019/08/01 --time 12:00:01
add_part_info.py -p HH23 -r A -c "RF PWR N: -7.3" --date 2019/06/13 --time 12:00:04
add_part_info.py -p HH23 -r A -c "Goodness N: OK?" --date 2019/06/13 --time 12:00:05
add_part_info.py -p HH24 -r A -c "FEM I2C: y" --date 2019/06/13 --time 12:00
add_part_info.py -p HH24 -r A -c "PAM I2C: y" --date 2019/06/13 --time 12:00:01
add_part_info.py -p HH24 -r A -c "RF PWR E: -16.1" --date 2019/06/13 --time 12:00:02
add_part_info.py -p HH24 -r A -c "Goodness E: NO?" --date 2019/06/13 --time 12:00:03
add_part_info.py -p HH24 -r A -c "Broken fibres (spliced but not fixed),was used for notch tests" --date 2019/06/13 --time 12:00:04
add_part_info.py -p HH24 -r A -c "Feed Height (m): 4.409" --date 2019/08/01 --time 12:00
add_part_info.py -p HH24 -r A -c "Tension N:W:E (lbs): 210:240:220" --date 2019/08/01 --time 12:00:01
add_part_info.py -p HH24 -r A -c "Eye-bolt N:W:E (m): 6.46:6.29:6.19" --date 2019/08/01 --time 12:00:02
add_part_info.py -p HH24 -r A -c "RF PWR N: -5.9" --date 2019/06/13 --time 12:00:05
add_part_info.py -p HH24 -r A -c "Goodness N: OK?" --date 2019/06/13 --time 12:00:06
add_part_info.py -p HH24 -r A -c "Broken fibres (spliced), was used for notch tests" --date 2019/06/13 --time 12:00:07
add_part_info.py -p HH25 -r A -c "FEM I2C: y" --date 2019/06/13 --time 12:00
add_part_info.py -p HH25 -r A -c "PAM I2C: y" --date 2019/06/13 --time 12:00:01
add_part_info.py -p HH25 -r A -c "RF PWR E: -5.1" --date 2019/06/13 --time 12:00:02
add_part_info.py -p HH25 -r A -c "Goodness E: OK?" --date 2019/06/13 --time 12:00:03
add_part_info.py -p HH25 -r A -c "Long CAT cable broken (intermittent), wrong FEM screws, +5V RFoF FEM and PAM" --date 2019/06/13 --time 12:00:04
add_part_info.py -p HH25 -r A -c "Feed Height (m): 4.406" --date 2019/08/01 --time 12:00
add_part_info.py -p HH25 -r A -c "Tension N:W:E (lbs): 370:345:375" --date 2019/08/01 --time 12:00:01
add_part_info.py -p HH25 -r A -c "Eye-bolt N:W:E (m): 6.50:6.28:6.23" --date 2019/08/01 --time 12:00:02
add_part_info.py -p HH25 -r A -c "RF PWR N: -4.5" --date 2019/06/13 --time 12:00:05
add_part_info.py -p HH25 -r A -c "Goodness N: OK?" --date 2019/06/13 --time 12:00:06
add_part_info.py -p HH25 -r A -c "Long CAT cable broken (intermittent), wrong FEM screws, +5V RFoF FEM and PAM" --date 2019/06/13 --time 12:00:07
add_part_info.py -p HH26 -r A -c "FEM I2C: n" --date 2019/06/13 --time 12:00
add_part_info.py -p HH26 -r A -c "PAM I2C: y" --date 2019/06/13 --time 12:00:01
add_part_info.py -p HH26 -r A -c "RF PWR E: -0.3" --date 2019/06/13 --time 12:00:02
add_part_info.py -p HH26 -r A -c "Goodness E: OK?" --date 2019/06/13 --time 12:00:03
add_part_info.py -p HH26 -r A -c "Long CAT cable broken, wrong FEM screws" --date 2019/06/13 --time 12:00:04
add_part_info.py -p HH26 -r A -c "Feed Height (m): 4.405" --date 2019/08/01 --time 12:00
add_part_info.py -p HH26 -r A -c "Tension N:W:E (lbs): 305:455:300" --date 2019/08/01 --time 12:00:01
add_part_info.py -p HH26 -r A -c "Eye-bolt N:W:E (m): 6.43:6.17:6.40" --date 2019/08/01 --time 12:00:02
add_part_info.py -p HH26 -r A -c "RF PWR N: -4.7" --date 2019/06/13 --time 12:00:05
add_part_info.py -p HH26 -r A -c "Goodness N: OK?" --date 2019/06/13 --time 12:00:06
add_part_info.py -p HH26 -r A -c "Long CAT cable broken, wrong FEM screws" --date 2019/06/13 --time 12:00:07
add_part_info.py -p HH39 -r A -c "FEM I2C: y" --date 2019/06/13 --time 12:00
add_part_info.py -p HH39 -r A -c "PAM I2C: y" --date 2019/06/13 --time 12:00:01
add_part_info.py -p HH39 -r A -c "RF PWR E: -1.7" --date 2019/06/13 --time 12:00:02
add_part_info.py -p HH39 -r A -c "Goodness E: OK?" --date 2019/06/13 --time 12:00:03
add_part_info.py -p HH39 -r A -c "Feed Height (m): 4.406" --date 2019/08/01 --time 12:00
add_part_info.py -p HH39 -r A -c "Tension N:W:E (lbs): 220:340:290" --date 2019/08/01 --time 12:00:01
add_part_info.py -p HH39 -r A -c "Eye-bolt N:W:E (m): 6.58:6.46:6.47" --date 2019/08/01 --time 12:00:02
add_part_info.py -p HH39 -r A -c "RF PWR N: -7.1" --date 2019/06/13 --time 12:00:04
add_part_info.py -p HH39 -r A -c "Goodness N: OK?" --date 2019/06/13 --time 12:00:05
add_part_info.py -p HH88 -r A -c "Goodness E: ?" --date 2019/08/05 --time 12:00
add_part_info.py -p HH88 -r A -c "Not checked (node 9 off the network)" --date 2019/08/05 --time 12:00:01
add_part_info.py -p HH88 -r A -c "Danny Aug 2-5: No fibre" --date 2019/08/05 --time 12:00:02
add_part_info.py -p HH88 -r A -c "Goodness N: ?" --date 2019/08/05 --time 12:00:03
add_part_info.py -p HH88 -r A -c "Not checked (node 9 off the network)" --date 2019/08/05 --time 12:00:04
add_part_info.py -p HH88 -r A -c "Danny Aug 2-5: No fibre" --date 2019/08/05 --time 12:00:05
add_part_info.py -p HH89 -r A -c "Goodness E: OK" --date 2019/08/05 --time 12:00
add_part_info.py -p HH89 -r A -c "Danny Aug 2-5: no PAM I2C data, VERY high ADC power... 2k vs 200" --date 2019/08/05 --time 12:00:01
add_part_info.py -p HH89 -r A -c "Goodness N: OK" --date 2019/08/05 --time 12:00:02
add_part_info.py -p HH89 -r A -c "Danny Aug 2-5: no PAM I2C data, VERY high ADC power... 2k vs 200" --date 2019/08/05 --time 12:00:03
add_part_info.py -p HH90 -r A -c "Goodness E: ?" --date 2019/08/05 --time 12:00
add_part_info.py -p HH90 -r A -c "Not checked (node 9 off the network)" --date 2019/08/05 --time 12:00:01
add_part_info.py -p HH90 -r A -c "Danny Aug 2-5: power ok, check spectra, add to mc" --date 2019/08/05 --time 12:00:02
add_part_info.py -p HH90 -r A -c "Goodness N: ?" --date 2019/08/05 --time 12:00:03
add_part_info.py -p HH90 -r A -c "Not checked (node 9 off the network)" --date 2019/08/05 --time 12:00:04
add_part_info.py -p HH90 -r A -c "Danny Aug 2-5: power ok, check spectra, add to mc" --date 2019/08/05 --time 12:00:05
add_part_info.py -p HH91 -r A -c "Goodness E: NA" --date 2019/08/05 --time 12:00
add_part_info.py -p HH91 -r A -c "Awaiting cabling and lifting" --date 2019/08/05 --time 12:00:01
add_part_info.py -p HH91 -r A -c "Danny Aug 2-5: no fiber" --date 2019/08/05 --time 12:00:02
add_part_info.py -p HH91 -r A -c "Goodness N: NA" --date 2019/08/05 --time 12:00:03
add_part_info.py -p HH91 -r A -c "Awaiting cabling and lifting" --date 2019/08/05 --time 12:00:04
add_part_info.py -p HH91 -r A -c "Danny Aug 2-5: no fiber" --date 2019/08/05 --time 12:00:05
add_part_info.py -p HH105 -r A -c "Goodness E: ?" --date 2019/08/05 --time 12:00
add_part_info.py -p HH105 -r A -c "Not checked (node 9 off the network)" --date 2019/08/05 --time 12:00:01
add_part_info.py -p HH105 -r A -c "Danny Aug 2-5: ok" --date 2019/08/05 --time 12:00:02
add_part_info.py -p HH105 -r A -c "Goodness N: ?" --date 2019/08/05 --time 12:00:03
add_part_info.py -p HH105 -r A -c "Not checked (node 9 off the network)" --date 2019/08/05 --time 12:00:04
add_part_info.py -p HH105 -r A -c "Danny Aug 2-5: ok" --date 2019/08/05 --time 12:00:05
add_part_info.py -p HH106 -r A -c "Goodness E: Bad" --date 2019/08/05 --time 12:00
add_part_info.py -p HH106 -r A -c "Dead FEM/PAM channel?" --date 2019/08/05 --time 12:00:01
add_part_info.py -p HH106 -r A -c "Danny Aug 2-5: ok" --date 2019/08/05 --time 12:00:02
add_part_info.py -p HH106 -r A -c "Goodness N: OK" --date 2019/08/05 --time 12:00:03
add_part_info.py -p HH106 -r A -c "Danny Aug 2-5: ok" --date 2019/08/05 --time 12:00:04
add_part_info.py -p HH107 -r A -c "Goodness E: ?" --date 2019/08/05 --time 12:00
add_part_info.py -p HH107 -r A -c "Not checked (node 9 off the network). Was re-done since E passband was still wonky." --date 2019/08/05 --time 12:00:01
add_part_info.py -p HH107 -r A -c "Danny Aug 2-5: ok" --date 2019/08/05 --time 12:00:02
add_part_info.py -p HH107 -r A -c "Goodness N: ?" --date 2019/08/05 --time 12:00:03
add_part_info.py -p HH107 -r A -c "Not checked (node 9 off the network). It was fine before." --date 2019/08/05 --time 12:00:04
add_part_info.py -p HH107 -r A -c "Danny Aug 2-5: ok" --date 2019/08/05 --time 12:00:05
add_part_info.py -p HH108 -r A -c "Goodness E: ?" --date 2019/08/05 --time 12:00
add_part_info.py -p HH108 -r A -c "It was fine before. Not checked (node 9 off the network). Had to be re-lifted due to a broken eye bolt in one of the poles (related to removal of the springs? -> it broke twice!)" --date 2019/08/05 --time 12:00:01
add_part_info.py -p HH108 -r A -c "Danny Aug 2-5: ok" --date 2019/08/05 --time 12:00:02
add_part_info.py -p HH108 -r A -c "Goodness N: ?" --date 2019/08/05 --time 12:00:03
add_part_info.py -p HH108 -r A -c "It was fine before. Not checked (node 9 off the network). Had to be re-lifted due to a broken eye bolt in one of the poles (related to removal of the springs? -> it broke twice!)" --date 2019/08/05 --time 12:00:04
add_part_info.py -p HH108 -r A -c "Danny Aug 2-5: ok" --date 2019/08/05 --time 12:00:05
add_part_info.py -p HH124 -r A -c "Goodness E: Bad" --date 2019/08/05 --time 12:00
add_part_info.py -p HH124 -r A -c "Dead FEM/PAM channel?" --date 2019/08/05 --time 12:00:01
add_part_info.py -p HH124 -r A -c "Danny Aug 2-5: swapped PAM 42 with 41 which was slot in pam slot #3 (just to the right of this pam)" --date 2019/08/05 --time 12:00:02
add_part_info.py -p HH124 -r A -c "Goodness N: OK" --date 2019/08/05 --time 12:00:03
add_part_info.py -p HH124 -r A -c "Danny Aug 2-5: swapped PAM 42 with 41 which was slot in pam slot #3 (just to the right of this pam)" --date 2019/08/05 --time 12:00:04
add_part_info.py -p HH125 -r A -c "Goodness E: OK" --date 2019/08/05 --time 12:00
add_part_info.py -p HH125 -r A -c "Goodness N: OK" --date 2019/08/05 --time 12:00:01
add_part_info.py -p HH126 -r A -c "Goodness E: OK" --date 2019/08/05 --time 12:00
add_part_info.py -p HH126 -r A -c "Goodness N: OK" --date 2019/08/05 --time 12:00:01
add_part_info.py -p HH126 -r A -c "Danny Aug 2-5: spectrum looks flat, bad fiber?" --date 2019/08/05 --time 12:00:02
