#! /usr/bin/env bash
echo "190808_add_antennas" >> scripts.log 
add_connection.py -u A84 --uprev H --upport focus -d FDV35 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FDV35 --uprev A --upport terminals -d FEM054 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FEM054 --uprev A --upport e -d NBP08 --dnrev A --dnport e10 --date 2019/08/07 --time 11:00
add_connection.py -u FEM054 --uprev A --upport n -d NBP08 --dnrev A --dnport n10 --date 2019/08/07 --time 11:00
add_part.py -p FDV36 -r A -t feed -m FDV36 --date 2019/08/07 --time 10:00
add_part.py -p FEM055 -r A -t front-end -m FEM055 --date 2019/08/07 --time 10:00
add_connection.py -u A85 --uprev H --upport focus -d FDV36 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FDV36 --uprev A --upport terminals -d FEM055 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FEM055 --uprev A --upport e -d NBP08 --dnrev A --dnport e2 --date 2019/08/07 --time 11:00
add_connection.py -u FEM055 --uprev A --upport n -d NBP08 --dnrev A --dnport n2 --date 2019/08/07 --time 11:00
add_part.py -p FDV37 -r A -t feed -m FDV37 --date 2019/08/07 --time 10:00
add_part.py -p FEM056 -r A -t front-end -m FEM056 --date 2019/08/07 --time 10:00
add_connection.py -u A86 --uprev H --upport focus -d FDV37 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FDV37 --uprev A --upport terminals -d FEM056 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FEM056 --uprev A --upport e -d NBP08 --dnrev A --dnport e3 --date 2019/08/07 --time 11:00
add_connection.py -u FEM056 --uprev A --upport n -d NBP08 --dnrev A --dnport n3 --date 2019/08/07 --time 11:00
add_part.py -p FDV38 -r A -t feed -m FDV38 --date 2019/08/07 --time 10:00
add_part.py -p FEM057 -r A -t front-end -m FEM057 --date 2019/08/07 --time 10:00
add_connection.py -u A87 --uprev H --upport focus -d FDV38 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FDV38 --uprev A --upport terminals -d FEM057 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FEM057 --uprev A --upport e -d NBP08 --dnrev A --dnport e7 --date 2019/08/07 --time 11:00
add_connection.py -u FEM057 --uprev A --upport n -d NBP08 --dnrev A --dnport n7 --date 2019/08/07 --time 11:00
add_part.py -p FDV39 -r A -t feed -m FDV39 --date 2019/08/07 --time 10:00
add_part.py -p FEM058 -r A -t front-end -m FEM058 --date 2019/08/07 --time 10:00
add_connection.py -u A101 --uprev H --upport focus -d FDV39 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FDV39 --uprev A --upport terminals -d FEM058 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FEM058 --uprev A --upport e -d NBP08 --dnrev A --dnport e8 --date 2019/08/07 --time 11:00
add_connection.py -u FEM058 --uprev A --upport n -d NBP08 --dnrev A --dnport n8 --date 2019/08/07 --time 11:00
add_part.py -p FDV40 -r A -t feed -m FDV40 --date 2019/08/07 --time 10:00
add_part.py -p FEM059 -r A -t front-end -m FEM059 --date 2019/08/07 --time 10:00
add_connection.py -u A102 --uprev H --upport focus -d FDV40 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FDV40 --uprev A --upport terminals -d FEM059 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FEM059 --uprev A --upport e -d NBP08 --dnrev A --dnport e1 --date 2019/08/07 --time 11:00
add_connection.py -u FEM059 --uprev A --upport n -d NBP08 --dnrev A --dnport n1 --date 2019/08/07 --time 11:00
add_part.py -p FDV41 -r A -t feed -m FDV41 --date 2019/08/07 --time 10:00
add_part.py -p FEM060 -r A -t front-end -m FEM060 --date 2019/08/07 --time 10:00
add_connection.py -u A103 --uprev H --upport focus -d FDV41 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FDV41 --uprev A --upport terminals -d FEM060 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FEM060 --uprev A --upport e -d NBP08 --dnrev A --dnport e6 --date 2019/08/07 --time 11:00
add_connection.py -u FEM060 --uprev A --upport n -d NBP08 --dnrev A --dnport n6 --date 2019/08/07 --time 11:00
add_part.py -p FEM061 -r A -t front-end -m FEM061 --date 2019/08/07 --time 10:00
add_connection.py -u FDV10 --uprev A --upport terminals -d FEM061 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FEM061 --uprev A --upport e -d NBP08 --dnrev A --dnport e5 --date 2019/08/07 --time 11:00
add_connection.py -u FEM061 --uprev A --upport n -d NBP08 --dnrev A --dnport n5 --date 2019/08/07 --time 11:00
add_part.py -p FDV42 -r A -t feed -m FDV42 --date 2019/08/07 --time 10:00
add_part.py -p FEM062 -r A -t front-end -m FEM062 --date 2019/08/07 --time 10:00
add_connection.py -u A120 --uprev H --upport focus -d FDV42 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FDV42 --uprev A --upport terminals -d FEM062 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FEM062 --uprev A --upport e -d NBP08 --dnrev A --dnport e4 --date 2019/08/07 --time 11:00
add_connection.py -u FEM062 --uprev A --upport n -d NBP08 --dnrev A --dnport n4 --date 2019/08/07 --time 11:00
add_part.py -p FDV43 -r A -t feed -m FDV43 --date 2019/08/07 --time 10:00
add_part.py -p FEM063 -r A -t front-end -m FEM063 --date 2019/08/07 --time 10:00
add_connection.py -u A121 --uprev H --upport focus -d FDV43 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FDV43 --uprev A --upport terminals -d FEM063 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FEM063 --uprev A --upport e -d NBP08 --dnrev A --dnport e12 --date 2019/08/07 --time 11:00
add_connection.py -u FEM063 --uprev A --upport n -d NBP08 --dnrev A --dnport n12 --date 2019/08/07 --time 11:00
add_part.py -p FDV44 -r A -t feed -m FDV44 --date 2019/08/07 --time 10:00
add_part.py -p FEM064 -r A -t front-end -m FEM064 --date 2019/08/07 --time 10:00
add_connection.py -u A122 --uprev H --upport focus -d FDV44 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FDV44 --uprev A --upport terminals -d FEM064 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FEM064 --uprev A --upport e -d NBP08 --dnrev A --dnport e9 --date 2019/08/07 --time 11:00
add_connection.py -u FEM064 --uprev A --upport n -d NBP08 --dnrev A --dnport n9 --date 2019/08/07 --time 11:00
add_part.py -p FDV45 -r A -t feed -m FDV45 --date 2019/08/07 --time 10:00
add_part.py -p FEM065 -r A -t front-end -m FEM065 --date 2019/08/07 --time 10:00
add_connection.py -u FDV45 --uprev A --upport terminals -d FEM065 --dnrev A --dnport input --date 2019/08/07 --time 11:00
add_connection.py -u FEM065 --uprev A --upport e -d NBP08 --dnrev A --dnport e11 --date 2019/08/07 --time 11:00
add_connection.py -u FEM065 --uprev A --upport n -d NBP08 --dnrev A --dnport n11 --date 2019/08/07 --time 11:00
