#! /usr/bin/env bash
echo "190917_fix_N9fems" >> scripts.log 
add_part.py -p FEM038 -r A -t front-end -m FEM038 --date 2019/09/01 --time 12:00
add_part.py -p FEM039 -r A -t front-end -m FEM039 --date 2019/09/01 --time 12:00
add_part.py -p FEM035 -r A -t front-end -m FEM035 --date 2019/09/01 --time 12:00
add_part.py -p FEM036 -r A -t front-end -m FEM036 --date 2019/09/01 --time 12:00
add_connection.py -u FEM038 --uprev A --upport e -d NBP09 --dnrev A --dnport e3 --date 2019/09/01 --time 12:30
add_connection.py -u FEM039 --uprev A --upport e -d NBP09 --dnrev A --dnport e2 --date 2019/09/01 --time 12:30
add_connection.py -u FEM035 --uprev A --upport e -d NBP09 --dnrev A --dnport e6 --date 2019/09/01 --time 12:30
add_connection.py -u FEM036 --uprev A --upport e -d NBP09 --dnrev A --dnport e4 --date 2019/09/01 --time 12:30
add_connection.py -u FEM038 --uprev A --upport n -d NBP09 --dnrev A --dnport n3 --date 2019/09/01 --time 12:30
add_connection.py -u FEM039 --uprev A --upport n -d NBP09 --dnrev A --dnport n2 --date 2019/09/01 --time 12:30
add_connection.py -u FEM035 --uprev A --upport n -d NBP09 --dnrev A --dnport n6 --date 2019/09/01 --time 12:30
add_connection.py -u FEM036 --uprev A --upport n -d NBP09 --dnrev A --dnport n4 --date 2019/09/01 --time 12:30
add_connection.py -u FDV15 --uprev A --upport terminals -d FEM038 --dnrev A --dnport input --date 2019/09/01 --time 12:30
add_connection.py -u FDV17 --uprev A --upport terminals -d FEM039 --dnrev A --dnport input --date 2019/09/01 --time 12:30
add_connection.py -u FDV18 --uprev A --upport terminals -d FEM035 --dnrev A --dnport input --date 2019/09/01 --time 12:30
add_connection.py -u FDV19 --uprev A --upport terminals -d FEM036 --dnrev A --dnport input --date 2019/09/01 --time 12:30
add_connection.py -u PAM037 --uprev A --upport e -d SNPC000010 --dnrev A --dnport e10 --date 2019/09/01 --time 12:30
add_connection.py -u PAM037 --uprev A --upport n -d SNPC000010 --dnrev A --dnport n8 --date 2019/09/01 --time 12:30
add_connection.py -u PAM036 --uprev A --upport e -d SNPC000010 --dnrev A --dnport e6 --date 2019/09/01 --time 12:30
add_connection.py -u PAM036 --uprev A --upport n -d SNPC000010 --dnrev A --dnport n4 --date 2019/09/01 --time 12:30
add_connection.py -u PAM040 --uprev A --upport e -d SNPC000011 --dnrev A --dnport e10 --date 2019/09/01 --time 12:30
add_connection.py -u PAM040 --uprev A --upport n -d SNPC000011 --dnrev A --dnport n8 --date 2019/09/01 --time 12:30
add_connection.py -u PAM038 --uprev A --upport e -d SNPC000011 --dnrev A --dnport e2 --date 2019/09/01 --time 12:30
add_connection.py -u PAM038 --uprev A --upport n -d SNPC000011 --dnrev A --dnport n0 --date 2019/09/01 --time 12:30
