#! /usr/bin/env bash
echo "../cm_updates/191101_overview_update_1312" >> scripts.log 
add_part_info.py -p HH82 -r A -c "lowered" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH82 -r A -c "lowered" --date 2019/11/01 --time 12:00:01
add_part_info.py -p HH83 -r A -c "broken PAM input" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH99 -r A -c "lowered, broken RF fiber" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH99 -r A -c "lowered" --date 2019/11/01 --time 12:00:01
add_part_info.py -p HH100 -r A -c "lowered" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH100 -r A -c "lowered" --date 2019/11/01 --time 12:00:01
add_part_info.py -p HH118 -r A -c "lowered" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH118 -r A -c "lowered" --date 2019/11/01 --time 12:00:01
add_part_info.py -p HH119 -r A -c "lowered" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH119 -r A -c "lowered" --date 2019/11/01 --time 12:00:01
add_part_info.py -p HH137 -r A -c "lowered" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH137 -r A -c "lowered" --date 2019/11/01 --time 12:00:01
add_part_info.py -p HH138 -r A -c "lowered" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH138 -r A -c "lowered" --date 2019/11/01 --time 12:00:01
add_part_info.py -p HH84 -r A -c "height raised from 4.117m to 4.492m 10/31/19" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH84 -r A -c "height raised from 4.117m to 4.492m 10/31/19" --date 2019/11/01 --time 12:00:01
add_part_info.py -p HH86 -r A -c "Cat7 cable connection is questionable" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH87 -r A -c "One tension is frayed" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH101 -r A -c "Cat7 cable connection is questionable" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH101 -r A -c "Not raised - waiting on pulldown rope" --date 2019/11/01 --time 12:00:01
add_part_info.py -p HH102 -r A -c "Not raised - waiting on pulldown rope" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH120 -r A -c "Not raised - waiting on pulldown rope" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH123 -r A -c "height raised from 4.041m to 4.406m 10/31/19" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH123 -r A -c "height raised from 4.041m to 4.406m 10/31/19" --date 2019/11/01 --time 12:00:01
add_part_info.py -p HH88 -r A -c "height raised from 4.205m to 4.418m 10/31/19" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH88 -r A -c "height raised from 4.205m to 4.418m 10/31/19" --date 2019/11/01 --time 12:00:01
add_part_info.py -p HH126 -r A -c "height raised from 4.15m to 4.446m 10/31/19" --date 2019/11/01 --time 12:00:00
add_part_info.py -p HH126 -r A -c "height raised from 4.15m to 4.446m 10/31/19" --date 2019/11/01 --time 12:00:01
