#! /bin/bash
source ~/.bashrc
echo "191213_connupd_0535" >> scripts.log 
add_part.py -p FEM107 -r A -t front-end -m FEM107 --date 2019/12/13 --time 05:35
add_connection.py -u FDV85 --uprev A --upport terminals -d FEM107 --dnrev A --dnport input --date 2019/12/13 --time 05:35
# <FEM129:A<e|e10>NBP03:A>         <--->   <FEM107:A<e|e10>NBP03:A>
add_connection.py -u FDV85 --uprev A --upport terminals -d FEM107 --dnrev A --dnport input --date 2019/12/13 --time 05:35
# <FEM129:A<n|n10>NBP03:A>         <--->   <FEM107:A<n|n10>NBP03:A>
add_part.py -p FEM128 -r A -t front-end -m FEM128 --date 2019/12/13 --time 05:35
add_connection.py -u FDV77 --uprev A --upport terminals -d FEM128 --dnrev A --dnport input --date 2019/12/13 --time 05:35
# <FEM130:A<e|e4>NBP03:A>          <--->   <FEM128:A<e|e4>NBP03:A>
add_connection.py -u FDV77 --uprev A --upport terminals -d FEM128 --dnrev A --dnport input --date 2019/12/13 --time 05:35
# <FEM130:A<n|n4>NBP03:A>          <--->   <FEM128:A<n|n4>NBP03:A>
