#! /bin/bash
source ~/.bashrc
echo "191212_infoupd_1042" >> scripts.log 
add_part_info.py -p HH94 -r A -c "Feed heights (NE/SE/SW/NW): Z distance from jig = 4.397" --date 2019/12/12 --time 10:42:00
add_part_info.py -p HH109 -r A -c "Feed heights (NE/SE/SW/NW): Z distance from jig = 4.406" --date 2019/12/12 --time 10:42:00
add_part_info.py -p HH111 -r A -c "Feed heights (NE/SE/SW/NW): Z disntace from jig = 4.414" --date 2019/12/12 --time 10:42:00
add_part_info.py -p HH112 -r A -c "Feed heights (NE/SE/SW/NW): Z distance from jig =4.404" --date 2019/12/12 --time 10:42:00
add_part_info.py -p HH128 -r A -c "Feed heights (NE/SE/SW/NW): Z distance from jig = 4.400" --date 2019/12/12 --time 10:42:00
add_part_info.py -p HH129 -r A -c "Feed heights (NE/SE/SW/NW): Z distance from jig = 4.402" --date 2019/12/12 --time 10:42:00
add_part_info.py -p HH130 -r A -c "Feed heights (NE/SE/SW/NW): Z distance from jif = 4.400" --date 2019/12/12 --time 10:42:00
add_part_info.py -p HH68 -r A -c "FEM replaced with 128. PAM replaced with 124" --date 2019/12/12 --time 10:42:00
add_part_info.py -p HH52 -r A -c "moved from port 8 to 10. PAm changed to 134" --date 2019/12/12 --time 10:42:00
add_part_info.py -p HH50 -r A -c "moved from port 10 to 12.FEM replaced with 107" --date 2019/12/12 --time 10:42:00
add_part_info.py -p HH50 -r A -c "Feed heights (NE/SE/SW/NW): Z distance from jig - 4.413" --date 2019/12/12 --time 10:42:02
