#! /bin/bash
source ~/.bashrc
echo "191212_infoupd_1442" >> scripts.log 
update_apriori.py -p HH36 -s passed_checks --date 2019/12/12 --time 14:42
update_apriori.py -p HH37 -s passed_checks --date 2019/12/12 --time 14:42
update_apriori.py -p HH51 -s passed_checks --date 2019/12/12 --time 14:42
update_apriori.py -p HH53 -s needs_checking --date 2019/12/12 --time 14:42
update_apriori.py -p HH65 -s passed_checks --date 2019/12/12 --time 14:42
update_apriori.py -p HH66 -s passed_checks --date 2019/12/12 --time 14:42
update_apriori.py -p HH67 -s passed_checks --date 2019/12/12 --time 14:42
add_part_info.py -p HH65 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/12 --time 14:42:00
add_part_info.py -p HH65 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/12 --time 14:42:02
add_part_info.py -p HH66 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/12 --time 14:42:00
add_part_info.py -p HH66 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/12 --time 14:42:02
add_part_info.py -p HH67 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/12 --time 14:42:00
add_part_info.py -p HH67 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/12 --time 14:42:02
add_part_info.py -p HH37 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/12 --time 14:42:00
add_part_info.py -p HH37 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/12 --time 14:42:02
add_part_info.py -p HH53 -r A -c "sbcd: shape is fine; plateau is low but peaks look of good power. Needs checking" --date 2019/12/12 --time 14:42:00
add_part_info.py -p HH53 -r A -c "sbcd: shape is fine; plateau is low but peaks look of good power. Needs checking" --date 2019/12/12 --time 14:42:02
add_part_info.py -p HH51 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/12 --time 14:42:00
add_part_info.py -p HH51 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/12 --time 14:42:02
add_part_info.py -p HH36 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/12 --time 14:42:00
add_part_info.py -p HH36 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/12 --time 14:42:02
