#! /bin/bash
source ~/.bashrc
echo "191217_connupd_2135" >> scripts.log 
add_part.py -p FEM107 -r A -t front-end -m FEM107 --date 2019/12/17 --time 21:35
add_connection.py -u FDV85 --uprev A --upport terminals -d FEM107 --dnrev A --dnport input --date 2019/12/17 --time 21:35
add_connection.py -u FEM107 --uprev A --upport e -d NBP03 --dnrev A --dnport e12 --date 2019/12/17 --time 21:35
# <PAM134:A<e|e2>SNPC000054:A>     <--->   <PAM136:A<e|e2>SNPC000054:A>
add_connection.py -u FDV85 --uprev A --upport terminals -d FEM107 --dnrev A --dnport input --date 2019/12/17 --time 21:35
add_connection.py -u FEM107 --uprev A --upport n -d NBP03 --dnrev A --dnport n12 --date 2019/12/17 --time 21:35
# <PAM134:A<n|n0>SNPC000054:A>     <--->   <PAM136:A<n|n0>SNPC000054:A>
# <FEM129:A<e|e10>NBP03:A>         <--->   <FEM134:A<e|e10>NBP03:A>
# <PAM132:A<e|e6>SNPC000037:A>     <--->   <PAM134:A<e|e6>SNPC000037:A>
# <FEM129:A<n|n10>NBP03:A>         <--->   <FEM134:A<n|n10>NBP03:A>
# <PAM132:A<n|n4>SNPC000037:A>     <--->   <PAM134:A<n|n4>SNPC000037:A>
add_part.py -p FEM128 -r A -t front-end -m FEM128 --date 2019/12/17 --time 21:35
add_connection.py -u FDV77 --uprev A --upport terminals -d FEM128 --dnrev A --dnport input --date 2019/12/17 --time 21:35
# <FEM130:A<e|e4>NBP03:A>          <--->   <FEM128:A<e|e4>NBP03:A>
# <PAM128:A<e|e2>SNPC000002:A>     <--->   <PAM124:A<e|e2>SNPC000002:A>
# <NBP05:A<e12|e>PAM124:A>         <--->   <NBP03:A<e4|e>PAM124:A>
# <PAM116:A<@slot|@slot4>PCH06:A>   <--->   <PAM124:A<@slot|@slot4>PCH06:A>
add_connection.py -u FDV77 --uprev A --upport terminals -d FEM128 --dnrev A --dnport input --date 2019/12/17 --time 21:35
# <FEM130:A<n|n4>NBP03:A>          <--->   <FEM128:A<n|n4>NBP03:A>
# <PAM128:A<n|n0>SNPC000002:A>     <--->   <PAM124:A<n|n0>SNPC000002:A>
# <NBP05:A<n12|n>PAM124:A>         <--->   <NBP03:A<n4|n>PAM124:A>
# <PAM116:A<@slot|@slot4>PCH06:A>   <--->   <PAM124:A<@slot|@slot4>PCH06:A>
# <PAM145:A<e|e10>SNPC000042:A>    <--->   <PAM144:A<e|e10>SNPC000042:A>
# <PAM145:A<n|n8>SNPC000042:A>     <--->   <PAM144:A<n|n8>SNPC000042:A>
# <PAM144:A<e|e6>SNPC000042:A>     <--->   <PAM145:A<e|e6>SNPC000042:A>
# <PAM144:A<n|n4>SNPC000042:A>     <--->   <PAM145:A<n|n4>SNPC000042:A>
# <PAM147:A<e|e6>SNPC000045:A>     <--->   <PAM146:A<e|e6>SNPC000045:A>
# <PAM147:A<n|n4>SNPC000045:A>     <--->   <PAM146:A<n|n4>SNPC000045:A>
# <PAM146:A<e|e2>SNPC000045:A>     <--->   <PAM147:A<e|e2>SNPC000045:A>
# <PAM146:A<n|n0>SNPC000045:A>     <--->   <PAM147:A<n|n0>SNPC000045:A>
