#! /bin/bash
echo "191208_pamswap" >> scripts.log 
stop_connection.py -u PAM103 --uprev A --upport e -d SNPC000022 --dnrev A --dnport e10 --date 2019/12/01 --time 10:00
stop_connection.py -u PAM103 --uprev A --upport n -d SNPC000022 --dnrev A --dnport n8 --date 2019/12/01 --time 10:00
stop_connection.py -u PAM103 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot3 --date 2019/12/01 --time 10:00
stop_connection.py -u NBP04 --uprev A --upport e3 -d PAM103 --dnrev A --dnport e --date 2019/12/01 --time 10:00
stop_connection.py -u NBP04 --uprev A --upport n3 -d PAM103 --dnrev A --dnport n --date 2019/12/01 --time 10:00
stop_connection.py -u PAM112 --uprev A --upport e -d SNPC000040 --dnrev A --dnport e10 --date 2019/12/01 --time 10:00
stop_connection.py -u PAM112 --uprev A --upport n -d SNPC000040 --dnrev A --dnport n8 --date 2019/12/01 --time 10:00
stop_connection.py -u PAM112 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot12 --date 2019/12/01 --time 10:00
stop_connection.py -u NBP04 --uprev A --upport e12 -d PAM112 --dnrev A --dnport e --date 2019/12/01 --time 10:00
stop_connection.py -u NBP04 --uprev A --upport n12 -d PAM112 --dnrev A --dnport n --date 2019/12/01 --time 10:00
add_connection.py -u PAM112 --uprev A --upport e -d SNPC000022 --dnrev A --dnport e10 --date 2019/12/01 --time 10:01
add_connection.py -u PAM112 --uprev A --upport n -d SNPC000022 --dnrev A --dnport n8 --date 2019/12/01 --time 10:01
add_connection.py -u PAM112 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot3 --date 2019/12/01 --time 10:01
add_connection.py -u NBP04 --uprev A --upport e3 -d PAM112 --dnrev A --dnport e --date 2019/12/01 --time 10:01
add_connection.py -u NBP04 --uprev A --upport n3 -d PAM112 --dnrev A --dnport n --date 2019/12/01 --time 10:01
add_connection.py -u PAM103 --uprev A --upport e -d SNPC000040 --dnrev A --dnport e10 --date 2019/12/01 --time 10:01
add_connection.py -u PAM103 --uprev A --upport n -d SNPC000040 --dnrev A --dnport n8 --date 2019/12/01 --time 10:01
add_connection.py -u PAM103 --uprev A --upport @slot -d PCH05 --dnrev A --dnport @slot12 --date 2019/12/01 --time 10:01
add_connection.py -u NBP04 --uprev A --upport e12 -d PAM103 --dnrev A --dnport e --date 2019/12/01 --time 10:01
add_connection.py -u NBP04 --uprev A --upport n12 -d PAM103 --dnrev A --dnport n --date 2019/12/01 --time 10:01
# <PAM103:A<e|e10>SNPC000022:A>    <--->   <PAM112:A<e|e10>SNPC000022:A>
# <PAM103:A<n|n8>SNPC000022:A>     <--->   <PAM112:A<n|n8>SNPC000022:A>
# <PAM103:A<@slot|@slot3>PCH05:A>   <--->   <PAM112:A<@slot|@slot3>PCH05:A>
# <NBP04:A<e12|e>PAM112:A>         <--->   <NBP04:A<e3|e>PAM112:A>
# <NBP04:A<n12|n>PAM112:A>         <--->   <NBP04:A<n3|n>PAM112:A>
# <PAM103:A<@slot|@slot3>PCH05:A>   <--->   <PAM112:A<@slot|@slot3>PCH05:A>