#! /bin/bash
source ~/.bashrc
echo "191213_infoupd_1742" >> scripts.log 
add_part_info.py -p HH92 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/13 --time 17:42:00
add_part_info.py -p HH92 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/13 --time 17:42:02
add_part_info.py -p HH93 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/13 --time 17:42:00
add_part_info.py -p HH93 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/13 --time 17:42:02
add_part_info.py -p HH94 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/13 --time 17:42:00
add_part_info.py -p HH94 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/13 --time 17:42:02
add_part_info.py -p HH109 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/13 --time 17:42:00
add_part_info.py -p HH109 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/13 --time 17:42:02
add_part_info.py -p HH111 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/13 --time 17:42:00
add_part_info.py -p HH111 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/13 --time 17:42:02
add_part_info.py -p HH112 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/13 --time 17:42:00
add_part_info.py -p HH112 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/13 --time 17:42:02
add_part_info.py -p HH128 -r A -c "Final spectra for 128E look sterrible" --date 2019/12/13 --time 17:42:00
add_part_info.py -p HH130 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/13 --time 17:42:00
add_part_info.py -p HH130 -r A -c "Sbcd thinks final spectra look good; ready to pass to commissioning" --date 2019/12/13 --time 17:42:02
