#! /usr/bin/env bash
echo 180222_fix_65 >> scripts.log
add_part.py -p FEM75066 -r A -t front-end -m 75066 --date 2018/02/21 --time 10:00 --actually_do_it
add_part.py -p PAM75159 -r B -t post-amp -m 75159 --date 2018/02/21 --time 10:00 --actually_do_it
stop_connection.py -u FDA5 --uprev B --upport terminals -d FEA5 --dnrev A --dnport input --date 2018/02/21 --time 11:00 --actually_do_it
stop_connection.py -u FEA5 --uprev A --upport e -d C7F65 --dnrev A --dnport ea --date 2018/02/21 --time 11:00 --actually_do_it
stop_connection.py -u FEA5 --uprev A --upport n -d C7F65 --dnrev A --dnport na --date 2018/02/21 --time 11:00 --actually_do_it
stop_connection.py -u C7F65 --uprev A --upport eb -d RI4A4E --dnrev A --dnport a --date 2018/02/21 --time 11:00 --actually_do_it
stop_connection.py -u C7F65 --uprev A --upport nb -d RI4A4N --dnrev A --dnport a --date 2018/02/21 --time 11:00 --actually_do_it
add_connection.py -u FDA5 --uprev B --upport terminals -d FEM75066 --dnrev A --dnport input --date 2018/02/21 --time 12:00 --actually_do_it
add_connection.py -u FEM75066 --uprev A --upport e -d C7F65 --dnrev A --dnport ea --date 2018/02/21 --time 12:00 --actually_do_it
add_connection.py -u FEM75066 --uprev A --upport n -d C7F65 --dnrev A --dnport na --date 2018/02/21 --time 12:00 --actually_do_it
add_connection.py -u C7F65 --uprev A --upport eb -d RI2A6E --dnrev A --dnport a --date 2018/02/21 --time 12:00 --actually_do_it
add_connection.py -u C7F65 --uprev A --upport nb -d RI2A6N --dnrev A --dnport a --date 2018/02/21 --time 12:00 --actually_do_it
add_connection.py -u RI2A6E --uprev A --upport b -d PAM75159 --dnrev B --dnport ea --date 2018/02/21 --time 12:00 --actually_do_it
add_connection.py -u RI2A6N --uprev A --upport b -d PAM75159 --dnrev B --dnport na --date 2018/02/21 --time 12:00 --actually_do_it
add_connection.py -u PAM75159 --uprev B --upport eb -d RO2A6E --dnrev A --dnport a --date 2018/02/21 --time 12:00 --actually_do_it
add_connection.py -u PAM75159 --uprev B --upport nb -d RO2A6N --dnrev A --dnport a --date 2018/02/21 --time 12:00 --actually_do_it
