#! /usr/bin/env bash
echo 180813_add_sigpaths >> scripts.log
add_part.py -p FEM06 -r A -t front-end -m FEMxxx06 --date 2018/08/13 --time 11:00 --actually_do_it
add_part.py -p CRF000 -r A -t cable-rfof -m bluewhite --date 2018/08/13 --time 11:00 --actually_do_it
add_part.py -p FEM04 -r A -t front-end -m FEMxxx04 --date 2018/08/13 --time 11:00 --actually_do_it
add_part.py -p CRF001 -r A -t cable-rfof -m browngreen --date 2018/08/13 --time 11:00 --actually_do_it
add_connection.py -u A0 --uprev H --upport focus -d FDV1 --dnrev A --dnport input --date 2018/08/13 --time 12:00 --actually_do_it
add_connection.py -u FDV1 --uprev A --upport terminals -d FEM06 --dnrev A --dnport input --date 2018/08/13 --time 12:00 --actually_do_it
add_connection.py -u FEM06 --uprev A --upport e -d CRF000 --dnrev A --dnport ea --date 2018/08/13 --time 12:00 --actually_do_it
add_connection.py -u FEM06 --uprev A --upport n -d CRF000 --dnrev A --dnport na --date 2018/08/13 --time 12:00 --actually_do_it
add_connection.py -u CRF000 --uprev A --upport eb -d PAM75196 --dnrev A --dnport ea --date 2018/08/13 --time 12:00 --actually_do_it
add_connection.py -u CRF000 --uprev A --upport nb -d PAM75196 --dnrev A --dnport na --date 2018/08/13 --time 12:00 --actually_do_it
add_connection.py -u PAM75196 --uprev A --upport eb -d SNP008 --dnrev A --dnport e2 --date 2018/08/13 --time 12:00 --actually_do_it
add_connection.py -u PAM75196 --uprev A --upport nb -d SNP008 --dnrev A --dnport n0 --date 2018/08/13 --time 12:00 --actually_do_it
add_connection.py -u A1 --uprev H --upport focus -d FDV2 --dnrev A --dnport input --date 2018/08/13 --time 12:00 --actually_do_it
add_connection.py -u FDV2 --uprev A --upport terminals -d FEM04 --dnrev A --dnport input --date 2018/08/13 --time 12:00 --actually_do_it
add_connection.py -u FEM04 --uprev A --upport e -d CRF001 --dnrev A --dnport ea --date 2018/08/13 --time 12:00 --actually_do_it
add_connection.py -u FEM04 --uprev A --upport n -d CRF001 --dnrev A --dnport na --date 2018/08/13 --time 12:00 --actually_do_it
add_connection.py -u CRF001 --uprev A --upport eb -d PAM75195 --dnrev A --dnport ea --date 2018/08/13 --time 12:00 --actually_do_it
add_connection.py -u CRF001 --uprev A --upport nb -d PAM75195 --dnrev A --dnport na --date 2018/08/13 --time 12:00 --actually_do_it
add_connection.py -u PAM75195 --uprev A --upport eb -d SNP008 --dnrev A --dnport e6 --date 2018/08/13 --time 12:00 --actually_do_it
add_connection.py -u PAM75195 --uprev A --upport nb -d SNP008 --dnrev A --dnport n4 --date 2018/08/13 --time 12:00 --actually_do_it
