#! /usr/bin/env bash
echo 181203_add_stations >> scripts.log
add_station.py HH10 --date 2018/12/03 --time 10:00
add_station.py HH22 --date 2018/12/03 --time 10:00
add_station.py HH47 --date 2018/12/03 --time 10:00
add_station.py HH78 --date 2018/12/03 --time 10:00
add_station.py HH34 --date 2018/12/03 --time 10:00
add_station.py HH95 --date 2018/12/03 --time 10:00
add_part.py -p A10 -r H -t antenna -m S/N153 --date 2018/12/03 --time 10:00 --actually_do_it
add_part.py -p A22 -r H -t antenna -m S/N154 --date 2018/12/03 --time 10:00 --actually_do_it
add_part.py -p A47 -r H -t antenna -m S/N155 --date 2018/12/03 --time 10:00 --actually_do_it
add_part.py -p A78 -r H -t antenna -m S/N156 --date 2018/12/03 --time 10:00 --actually_do_it
add_part.py -p A34 -r H -t antenna -m S/N157 --date 2018/12/03 --time 10:00 --actually_do_it
add_part.py -p A95 -r H -t antenna -m S/N158 --date 2018/12/03 --time 10:00 --actually_do_it
add_connection.py -u HH10 --uprev A --upport ground -d A10 --dnrev H --dnport ground --date 2018/12/03 --time 12:00 --actually_do_it
add_connection.py -u HH22 --uprev A --upport ground -d A22 --dnrev H --dnport ground --date 2018/12/03 --time 12:00 --actually_do_it
add_connection.py -u HH47 --uprev A --upport ground -d A47 --dnrev H --dnport ground --date 2018/12/03 --time 12:00 --actually_do_it
add_connection.py -u HH78 --uprev A --upport ground -d A78 --dnrev H --dnport ground --date 2018/12/03 --time 12:00 --actually_do_it
add_connection.py -u HH34 --uprev A --upport ground -d A34 --dnrev H --dnport ground --date 2018/12/03 --time 12:00 --actually_do_it
add_connection.py -u HH95 --uprev A --upport ground -d A95 --dnrev H --dnport ground --date 2018/12/03 --time 12:00 --actually_do_it
